OTTO: otto::board::ui::EGLConnection Class Reference
otto::board::ui::EGLConnection Class Reference
#include <egl_connection.hpp>
Classes
struct EGLData
struct EGLState
struct Size
Public Types
using DMXDisplay = DISPMANX_DISPLAY_HANDLE_T
using DMXResource = DISPMANX_RESOURCE_HANDLE_T
using DMXWindow = EGL_DISPMANX_WINDOW_T
using DMXElement = DISPMANX_ELEMENT_HANDLE_T
using DMXUpdate = DISPMANX_UPDATE_HANDLE_T
using VCRect = VC_RECT_T
Public Member Functions
void init ()
void exit ()
void beginFrame ()
void endFrame ()
void initEGL ()
Public Attributes
struct otto::board::ui::EGLConnection::EGLData eglData
struct otto::board::ui::EGLConnection::Size draw_size
struct otto::board::ui::EGLConnection::EGLState state
Detailed Description
Definition at line 8 of file egl_connection.hpp.
Member Typedef Documentation
DMXDisplay
using otto::board::ui::EGLConnection::DMXDisplay = DISPMANX_DISPLAY_HANDLE_T
Definition at line 10 of file egl_connection.hpp.
DMXElement
using otto::board::ui::EGLConnection::DMXElement = DISPMANX_ELEMENT_HANDLE_T
Definition at line 13 of file egl_connection.hpp.
DMXResource
using otto::board::ui::EGLConnection::DMXResource = DISPMANX_RESOURCE_HANDLE_T
Definition at line 11 of file egl_connection.hpp.
DMXUpdate
using otto::board::ui::EGLConnection::DMXUpdate = DISPMANX_UPDATE_HANDLE_T
Definition at line 14 of file egl_connection.hpp.
DMXWindow
using otto::board::ui::EGLConnection::DMXWindow = EGL_DISPMANX_WINDOW_T
Definition at line 12 of file egl_connection.hpp.
VCRect
using otto::board::ui::EGLConnection::VCRect = VC_RECT_T
Definition at line 15 of file egl_connection.hpp.
Member Function Documentation
beginFrame()
void otto::board::ui::EGLConnection::beginFrame ()
Definition at line 152 of file egl_connection.cpp.
References draw_size, otto::board::ui::EGLConnection::Size::height, and otto::board::ui::EGLConnection::Size::width.
Referenced by otto::service::ui::main_ui_loop().
   {
     // Start with a clear screen
     glViewport(0, 0, draw_size.width, draw_size.height);
     glClearColor(0, 0, 0, 0);
     glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT | GL_STENCIL_BUFFER_BIT);
     glEnable(GL_BLEND);
     glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
     glEnable(GL_CULL_FACE);
     glEnable(GL_STENCIL_TEST);
   }
endFrame()
void otto::board::ui::EGLConnection::endFrame ()
Definition at line 166 of file egl_connection.cpp.
References otto::board::ui::EGLConnection::EGLState::display, state, and otto::board::ui::EGLConnection::EGLState::surface.
Referenced by otto::service::ui::main_ui_loop().
   {
     eglSwapBuffers(state.display, state.surface);
   }
exit()
void otto::board::ui::EGLConnection::exit ()
Definition at line 130 of file egl_connection.cpp.
References otto::board::ui::EGLConnection::EGLState::context, otto::board::ui::EGLConnection::EGLData::data, otto::board::ui::EGLConnection::EGLData::display, otto::board::ui::EGLConnection::EGLState::display, eglData, otto::board::ui::EGLConnection::EGLData::nativeWindow, otto::board::ui::EGLConnection::EGLData::resource, state, and otto::board::ui::EGLConnection::EGLState::surface.
Referenced by otto::service::ui::main_ui_loop().
   {
     glClear(GL_COLOR_BUFFER_BIT);
     eglSwapBuffers(state.display, state.surface);
     // Release OpenGL resources
     eglDestroySurface(state.display, state.surface);
     DMXUpdate dmxUpdate = vc_dispmanx_update_start(0);
     vc_dispmanx_element_remove(dmxUpdate, eglData.nativeWindow.element);
     vc_dispmanx_update_submit_sync(dmxUpdate);
     vc_dispmanx_resource_delete(eglData.resource);
     vc_dispmanx_display_close(eglData.display);
     eglMakeCurrent(state.display, EGL_NO_SURFACE, EGL_NO_SURFACE,
                    EGL_NO_CONTEXT);
     eglDestroyContext(state.display, state.context);
     eglTerminate(state.display);
     free(eglData.data);
   }
init()
void otto::board::ui::EGLConnection::init ()
Definition at line 6 of file egl_connection.cpp.
References initEGL().
Referenced by otto::service::ui::main_ui_loop().
   {
     bcm_host_init();
     initEGL();
   }
initEGL()
void otto::board::ui::EGLConnection::initEGL ()
Definition at line 13 of file egl_connection.cpp.
References otto::board::ui::EGLConnection::EGLData::bitdepth, otto::board::ui::EGLConnection::EGLState::context, otto::board::ui::EGLConnection::EGLData::data, otto::board::ui::EGLConnection::EGLData::display, otto::board::ui::EGLConnection::EGLState::display, draw_size, eglData, otto::board::ui::f, otto::board::ui::EGLConnection::EGLData::height, otto::board::ui::EGLConnection::Size::height, otto::board::ui::EGLConnection::EGLState::height, otto::board::ui::EGLConnection::EGLData::nativeWindow, otto::board::ui::EGLConnection::EGLData::nConfig, otto::board::ui::EGLConnection::EGLData::rect, otto::board::ui::EGLConnection::EGLData::resource, otto::board::ui::EGLConnection::EGLData::screenDatasize, state, otto::board::ui::EGLConnection::EGLState::surface, otto::board::ui::EGLConnection::EGLData::width, otto::board::ui::EGLConnection::Size::width, and otto::board::ui::EGLConnection::EGLState::width.
Referenced by init().
   {
     static const EGLint attribute_list[] = {EGL_RED_SIZE,     8,
                                             EGL_GREEN_SIZE,   8,
                                             EGL_BLUE_SIZE,    8,
                                             EGL_ALPHA_SIZE,   8,
                                             EGL_DEPTH_SIZE,   16,
                                             EGL_STENCIL_SIZE, 8,
                                             EGL_SURFACE_TYPE, EGL_WINDOW_BIT,
                                             EGL_NONE};
     static const EGLint context_attributes[] = {EGL_CONTEXT_CLIENT_VERSION, 2,
                                                 EGL_NONE};
     state.display = eglGetDisplay(EGL_DEFAULT_DISPLAY);
     if (state.display == EGL_NO_DISPLAY) {
       LOGF("Error opening EGL display");
     }
     EGLBoolean result = eglInitialize(state.display, nullptr, nullptr);
     if (result == EGL_FALSE) {
       LOGF("Error initializing EGL display");
     }
     EGLConfig config;
     result = eglChooseConfig(state.display, attribute_list, &config, 1,
                              &eglData.nConfig);
     if (result == EGL_FALSE) {
       LOGF("Error choosing EGL config");
     }
     result = eglBindAPI(EGL_OPENGL_ES_API);
     if (result == EGL_FALSE) {
       LOGF("Error binding EGL API");
     }
     state.context = eglCreateContext(state.display, config, EGL_NO_CONTEXT,
                                      context_attributes);
     if (state.context == EGL_NO_CONTEXT) {
       LOGF("Error creating EGL context");
     }
     int success = graphics_get_display_size(0, &state.width, &state.height);
     if (success < 0) {
       LOGF("Error getting display size");
     }
     LOGI("EGL Display size: {} x {}", state.width, state.height);
     // What does this do?
     vc_dispmanx_rect_set(&eglData.rect, 0, 0, draw_size.width, draw_size.height);
     eglData.width = state.width;
     eglData.height = state.height;
     eglData.screenDatasize = eglData.width * eglData.height * eglData.bitdepth;
     eglData.data = (unsigned short*) malloc(eglData.screenDatasize);
     // What does this do?
     uint imagePrt;
     eglData.resource = vc_dispmanx_resource_create(VC_IMAGE_RGB565, state.width,
                                                    state.height, &imagePrt);
     if (!eglData.resource) {
       LOGF("Error getting resource");
     }
     VCRect srcRect;
     VCRect dstRect;
     srcRect.x = 0;
     srcRect.y = 0;
     srcRect.width = draw_size.width << 16;
     srcRect.height = draw_size.height << 16;
     dstRect.x = 0;
     dstRect.y = 0;
     dstRect.width = state.width;
     dstRect.height = state.height;
     eglData.display = vc_dispmanx_display_open(0);
     if (!eglData.display) {
       LOGF("Error opening display");
     }
     DMXDisplay dmxDisplay = eglData.display;
     DMXUpdate dmxUpdate = vc_dispmanx_update_start(0);
     DMXElement dmxElement = vc_dispmanx_element_add(
       dmxUpdate, dmxDisplay, 0, &dstRect, 0, &srcRect, DISPMANX_PROTECTION_NONE,
       0, 0, DISPMANX_TRANSFORM_T());
     eglData.nativeWindow.element = dmxElement;
     eglData.nativeWindow.width = draw_size.width;
     eglData.nativeWindow.height = draw_size.height;
     vc_dispmanx_update_submit_sync(dmxUpdate);
     state.surface = eglCreateWindowSurface(state.display, config,
                                            &eglData.nativeWindow, nullptr);
     if (state.surface == EGL_NO_SURFACE) {
       LOGF("Error creating EGL surface");
     }
     result = eglMakeCurrent(state.display, state.surface, state.surface,
                             state.context);
     if (result == EGL_FALSE) {
       LOGF("Error connecting the context to the surface");
     }
     // Set background color and clear buffers
     glClearColor(1.f, 1.f, 1.f, 1.f);
     // Enable back face culling.
     glEnable(GL_CULL_FACE);
   }
Member Data Documentation
draw_size
struct otto::board::ui::EGLConnection::Size otto::board::ui::EGLConnection::draw_size
Referenced by beginFrame(), initEGL(), and otto::service::ui::main_ui_loop().
eglData
struct otto::board::ui::EGLConnection::EGLData otto::board::ui::EGLConnection::eglData
Referenced by exit(), initEGL(), and otto::service::ui::main_ui_loop().
state
struct otto::board::ui::EGLConnection::EGLState otto::board::ui::EGLConnection::state
Referenced by endFrame(), exit(), and initEGL().
The documentation for this class was generated from the following files:
/home/topisani/dev/OTTO/boards/parts/ui/egl/src/egl_connection.hpp
/home/topisani/dev/OTTO/boards/parts/ui/egl/src/egl_connection.cpp