OTTO: ChorusEffect< T > Class Template Reference
ChorusEffect< T > Class Template Reference
Detailed Description
template<class T = gam::real>
class ChorusEffect< T >
Definition at line 108 of file chorus.hpp.
#include <chorus.hpp>
Public Member Functions
ChorusEffect (float delayMax=0.042, float depth=0.007, float freq1=0.15, float freq2=0.4, float ffd=0.7, float fbk=0.0)
ChorusEffect & maxDelay (float v)
ChorusEffect & fbk (float v)
ChorusEffect & ffd (float v)
ChorusEffect & freq1 (float v)
ChorusEffect & freq2 (float v)
ChorusEffect & depth (float v)
ChorusEffect & center (float v)
float center ()
void rate (float v)
void operator() (const T &in, T &o1, T &o2)
Filter sample (mono-stereo)
void modulate ()
Perform delay modulation step (must manually step play heads after use!)
Public Attributes
ChorusComb< T, gam::ipl::Linear > comb
Multitap comb filter.
gam::Sine mod1A
gam::Sine mod1B
gam::Sine mod1C
gam::Sine mod2A
gam::Sine mod2B
gam::Sine mod2C
Modulators.
Constructor & Destructor Documentation
ChorusEffect()
template<class T = gam::real> ChorusEffect< T >::ChorusEffect (float delayMax = 0.042, float depth = 0.007, float freq1 = 0.15, float freq2 = 0.4, float ffd = 0.7, float fbk = 0.0)
Parameters
[in] delay Delay interval
[in] depth Depth of delay-line modulation
[in] freq Frequency of modulation
[in] ffd Feedforward amount
[in] fbk Feedback amount
Definition at line 115 of file chorus.hpp.
References ChorusEffect< T >::depth().
Member Function Documentation
maxDelay()
template<class T = gam::real> ChorusEffect& ChorusEffect< T >::maxDelay (float v)
Definition at line 125 of file chorus.hpp.
References ChorusEffect< T >::comb.
fbk()
template<class T = gam::real> ChorusEffect& ChorusEffect< T >::fbk (float v)
Definition at line 126 of file chorus.hpp.
References ChorusEffect< T >::comb, and ChorusComb< Tv, Si, Tp, Td >::fbk().
ffd()
template<class T = gam::real> ChorusEffect& ChorusEffect< T >::ffd (float v)
Definition at line 127 of file chorus.hpp.
References ChorusEffect< T >::comb, and ChorusComb< Tv, Si, Tp, Td >::ffd().
freq1()
template<class T = gam::real> ChorusEffect& ChorusEffect< T >::freq1 (float v)
Definition at line 128 of file chorus.hpp.
References ChorusEffect< T >::mod1A, and ChorusEffect< T >::mod1C.
Referenced by ChorusEffect< T >::rate().
freq2()
template<class T = gam::real> ChorusEffect& ChorusEffect< T >::freq2 (float v)
Definition at line 129 of file chorus.hpp.
References ChorusEffect< T >::mod2A, and ChorusEffect< T >::mod2C.
Referenced by ChorusEffect< T >::rate().
depth()
template<class T = gam::real> ChorusEffect& ChorusEffect< T >::depth (float v)
Definition at line 130 of file chorus.hpp.
Referenced by ChorusEffect< T >::ChorusEffect().
center() [1/2]
template<class T = gam::real> ChorusEffect& ChorusEffect< T >::center (float v)
Definition at line 131 of file chorus.hpp.
center() [2/2]
template<class T = gam::real> float ChorusEffect< T >::center ()
Definition at line 132 of file chorus.hpp.
rate()
template<class T = gam::real> void ChorusEffect< T >::rate (float v)
Definition at line 133 of file chorus.hpp.
References ChorusEffect< T >::freq1(), and ChorusEffect< T >::freq2().
operator()()
template<class T = gam::real> void ChorusEffect< T >::operator() (const T & in, T & o1, T & o2)
Filter sample (mono-stereo)
Definition at line 137 of file chorus.hpp.
References ChorusEffect< T >::comb, and ChorusEffect< T >::modulate().
modulate()
template<class T = gam::real> void ChorusEffect< T >::modulate ()
Perform delay modulation step (must manually step play heads after use!)
Definition at line 144 of file chorus.hpp.
References ChorusEffect< T >::comb, ChorusEffect< T >::mod1A, ChorusEffect< T >::mod1B, ChorusEffect< T >::mod1C, ChorusEffect< T >::mod2A, ChorusEffect< T >::mod2B, ChorusEffect< T >::mod2C, and ChorusComb< Tv, Si, Tp, Td >::set_delays().
Referenced by ChorusEffect< T >::operator()().
Member Data Documentation
comb
template<class T = gam::real> ChorusComb<T, gam::ipl::Linear> ChorusEffect< T >::comb
Multitap comb filter.
Definition at line 152 of file chorus.hpp.
Referenced by ChorusEffect< T >::fbk(), ChorusEffect< T >::ffd(), ChorusEffect< T >::maxDelay(), ChorusEffect< T >::modulate(), and ChorusEffect< T >::operator()().
mod1A
template<class T = gam::real> gam::Sine ChorusEffect< T >::mod1A
Definition at line 153 of file chorus.hpp.
Referenced by ChorusEffect< T >::freq1(), and ChorusEffect< T >::modulate().
mod1B
template<class T = gam::real> gam::Sine ChorusEffect< T >::mod1B
Definition at line 153 of file chorus.hpp.
Referenced by ChorusEffect< T >::modulate().
mod1C
template<class T = gam::real> gam::Sine ChorusEffect< T >::mod1C
Definition at line 153 of file chorus.hpp.
Referenced by ChorusEffect< T >::freq1(), and ChorusEffect< T >::modulate().
mod2A
template<class T = gam::real> gam::Sine ChorusEffect< T >::mod2A
Definition at line 153 of file chorus.hpp.
Referenced by ChorusEffect< T >::freq2(), and ChorusEffect< T >::modulate().
mod2B
template<class T = gam::real> gam::Sine ChorusEffect< T >::mod2B
Definition at line 153 of file chorus.hpp.
Referenced by ChorusEffect< T >::modulate().
mod2C
template<class T = gam::real> gam::Sine ChorusEffect< T >::mod2C
Modulators.
Definition at line 153 of file chorus.hpp.
Referenced by ChorusEffect< T >::freq2(), and ChorusEffect< T >::modulate().
The documentation for this class was generated from the following file:
/home/travis/build/topisani/OTTO/src/util/dsp/chorus.hpp