OTTO: RtMidiIn Class Reference
RtMidiIn Class Reference
Detailed Description
A realtime MIDI input class.
This class provides a common, platform-independent API for realtime MIDI input. It allows access to a single MIDI input port. Incoming MIDI messages are either saved to a queue for retrieval using the getMessage() function or immediately passed to a user-specified callback function. Create multiple instances of this class to connect to more than one MIDI device at the same time. With the OS-X, Linux ALSA, and JACK MIDI APIs, it is also possible to open a virtual input port to which other MIDI software clients can connect.
by Gary P. Scavone, 2003-2017.
Definition at line 223 of file RtMidi.h.
#include <RtMidi.h>
Public Types
typedef void(* RtMidiCallback) (double timeStamp, std::vector< unsigned char > *message, void *userData)
User callback function type definition.
Public Types inherited from RtMidi
enum Api {
UNSPECIFIED, MACOSX_CORE, LINUX_ALSA, UNIX_JACK,
WINDOWS_MM, RTMIDI_DUMMY
}
MIDI API specifier arguments.
Public Member Functions
RtMidiIn (RtMidi::Api api=UNSPECIFIED, const std::string &clientName="RtMidi Input Client", unsigned int queueSizeLimit=100)
Default constructor that allows an optional api, client name and queue size.
~RtMidiIn (void) throw ()
If a MIDI connection is still open, it will be closed by the destructor.
RtMidi::Api getCurrentApi (void) throw ()
Returns the MIDI API specifier for the current instance of RtMidiIn.
void openPort (unsigned int portNumber=0, const std::string &portName=std::string("RtMidi Input"))
Open a MIDI input connection given by enumeration number.
void openVirtualPort (const std::string &portName=std::string("RtMidi Input"))
Create a virtual input port, with optional name, to allow software connections (OS X, JACK and ALSA only).
void setCallback (RtMidiCallback callback, void *userData=0)
Set a callback function to be invoked for incoming MIDI messages.
void cancelCallback ()
Cancel use of the current callback function (if one exists).
void closePort (void)
Close an open MIDI connection (if one exists).
virtual bool isPortOpen () const
Returns true if a port is open and false if not.
unsigned int getPortCount ()
Return the number of available MIDI input ports.
std::string getPortName (unsigned int portNumber=0)
Return a string identifier for the specified MIDI input port number.
void ignoreTypes (bool midiSysex=true, bool midiTime=true, bool midiSense=true)
Specify whether certain MIDI message types should be queued or ignored during input.
double getMessage (std::vector< unsigned char > *message)
Fill the user-provided vector with the data bytes for the next available MIDI message in the input queue and return the event delta-time in seconds.
virtual void setErrorCallback (RtMidiErrorCallback errorCallback=NULL, void *userData=0)
Set an error callback function to be invoked when an error has occured.
Public Member Functions inherited from RtMidi
void setClientName (const std::string &clientName)
void setPortName (const std::string &portName)
Protected Member Functions
void openMidiApi (RtMidi::Api api, const std::string &clientName, unsigned int queueSizeLimit)
Protected Member Functions inherited from RtMidi
RtMidi ()
virtual ~RtMidi ()
Additional Inherited Members
Static Public Member Functions inherited from RtMidi
static std::string getVersion (void) throw ()
A static function to determine the current RtMidi version.
static void getCompiledApi (std::vector< RtMidi::Api > &apis) throw ()
A static function to determine the available compiled MIDI APIs.
Protected Attributes inherited from RtMidi
MidiApi * rtapi_
Member Typedef Documentation
RtMidiCallback
typedef void(* RtMidiIn::RtMidiCallback) (double timeStamp, std::vector< unsigned char > *message, void *userData)
User callback function type definition.
Definition at line 228 of file RtMidi.h.
Constructor & Destructor Documentation
RtMidiIn()
RtMidiIn::RtMidiIn (RtMidi::Api api = UNSPECIFIED, const std::string & clientName = "RtMidi Input Client", unsigned int queueSizeLimit = 100)
Default constructor that allows an optional api, client name and queue size.
An exception will be thrown if a MIDI system initialization error occurs. The queue size defines the maximum number of messages that can be held in the MIDI queue (when not using a callback function). If the queue size limit is reached, incoming messages will be ignored.
If no API argument is specified and multiple API support has been compiled, the default order of use is ALSA, JACK (Linux) and CORE, JACK (OS-X).
Parameters
api An optional API id can be specified.
clientName An optional client name can be specified. This will be used to group the ports that are created by the application.
queueSizeLimit An optional size of the MIDI input queue can be specified.
~RtMidiIn()
RtMidiIn::~RtMidiIn (void) throw ()
If a MIDI connection is still open, it will be closed by the destructor.
Member Function Documentation
getCurrentApi()
RtMidi::Api RtMidiIn::getCurrentApi (void) throw ()
Returns the MIDI API specifier for the current instance of RtMidiIn.
Definition at line 586 of file RtMidi.h.
openPort()
void RtMidiIn::openPort (unsigned int portNumber = 0, const std::string & portName = std::string("RtMidi Input")) virtual
Open a MIDI input connection given by enumeration number.
Parameters
portNumber An optional port number greater than 0 can be specified. Otherwise, the default or first port found is opened.
portName An optional name for the application port that is used to connect to portId can be specified.
Implements RtMidi.
Definition at line 587 of file RtMidi.h.
References MidiApi::openPort(), and RtMidi::rtapi_.
openVirtualPort()
void RtMidiIn::openVirtualPort (const std::string & portName = std::string("RtMidi Input")) virtual
Create a virtual input port, with optional name, to allow software connections (OS X, JACK and ALSA only).
This function creates a virtual MIDI input port to which other software applications can connect. This type of functionality is currently only supported by the Macintosh OS-X, any JACK, and Linux ALSA APIs (the function returns an error for the other APIs).
Parameters
portName An optional name for the application port that is used to connect to portId can be specified.
Implements RtMidi.
Definition at line 588 of file RtMidi.h.
References MidiApi::openVirtualPort(), and RtMidi::rtapi_.
setCallback()
void RtMidiIn::setCallback (RtMidiCallback callback, void * userData = 0)
Set a callback function to be invoked for incoming MIDI messages.
The callback function will be called whenever an incoming MIDI message is received. While not absolutely necessary, it is best to set the callback function before opening a MIDI port to avoid leaving some messages in the queue.
Parameters
callback A callback function must be given.
userData Optionally, a pointer to additional data can be passed to the callback function whenever it is called.
Definition at line 591 of file RtMidi.h.
References RtMidi::rtapi_.
cancelCallback()
void RtMidiIn::cancelCallback (void)
Cancel use of the current callback function (if one exists).
Subsequent incoming MIDI messages will be written to the queue and can be retrieved with the getMessage function.
Definition at line 592 of file RtMidi.h.
References RtMidi::rtapi_.
closePort()
void RtMidiIn::closePort (void) virtual
Close an open MIDI connection (if one exists).
Implements RtMidi.
Definition at line 589 of file RtMidi.h.
References MidiApi::closePort(), and RtMidi::rtapi_.
isPortOpen()
bool RtMidiIn::isPortOpen (void) const virtual
Returns true if a port is open and false if not.
Note that this only applies to connections made with the openPort() function, not to virtual ports.
Implements RtMidi.
Definition at line 590 of file RtMidi.h.
References MidiApi::isPortOpen(), and RtMidi::rtapi_.
getPortCount()
unsigned int RtMidiIn::getPortCount (void) virtual
Return the number of available MIDI input ports.
Returns
This function returns the number of MIDI ports of the selected API.
Implements RtMidi.
Definition at line 593 of file RtMidi.h.
References MidiApi::getPortCount(), and RtMidi::rtapi_.
getPortName()
std::string RtMidiIn::getPortName (unsigned int portNumber = 0) virtual
Return a string identifier for the specified MIDI input port number.
Returns
The name of the port with the given Id is returned.
Return values
An empty string is returned if an invalid port specifier is provided. User code should assume a UTF-8 encoding.
Implements RtMidi.
Definition at line 594 of file RtMidi.h.
References MidiApi::getPortName(), and RtMidi::rtapi_.
ignoreTypes()
void RtMidiIn::ignoreTypes (bool midiSysex = true, bool midiTime = true, bool midiSense = true)
Specify whether certain MIDI message types should be queued or ignored during input.
By default, MIDI timing and active sensing messages are ignored during message input because of their relative high data rates. MIDI sysex messages are ignored by default as well. Variable values of "true" imply that the respective message type will be ignored.
Definition at line 595 of file RtMidi.h.
References RtMidi::rtapi_.
getMessage()
double RtMidiIn::getMessage (std::vector< unsigned char > * message)
Fill the user-provided vector with the data bytes for the next available MIDI message in the input queue and return the event delta-time in seconds.
This function returns immediately whether a new message is available or not. A valid message is indicated by a non-zero vector size. An exception is thrown if an error occurs during message retrieval or an input connection was not previously established.
Definition at line 596 of file RtMidi.h.
References RtMidi::rtapi_.
setErrorCallback()
void RtMidiIn::setErrorCallback (RtMidiErrorCallback errorCallback = NULL, void * userData = 0) virtual
Set an error callback function to be invoked when an error has occured.
The callback function will be called whenever an error has occured. It is best to set the error callback function before opening a port.
Implements RtMidi.
Definition at line 597 of file RtMidi.h.
References RtMidi::rtapi_, and MidiApi::setErrorCallback().
openMidiApi()
void RtMidiIn::openMidiApi (RtMidi::Api api, const std::string & clientName, unsigned int queueSizeLimit) protected
The documentation for this class was generated from the following file:
/home/travis/build/topisani/OTTO/boards/parts/audio/rtaudio/include/RtMidi.h