OTTO: ADSR_lite< Tv, Tp, Td > Class Template Reference
ADSR_lite< Tv, Tp, Td > Class Template Reference
Detailed Description
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver>
class ADSR_lite< Tv, Tp, Td >
ADSR (Attack, Decay, Sustain, Release) envelope. Uses the Env_lite envelope template.
Template Parameters
Tv value (sample) type
Tp parameter type
Td domain observer type
Definition at line 401 of file ADSR_lite.hpp.
#include <ADSR_lite.hpp>
Public Member Functions
ADSR_lite (float(*voice)(void), Tp att=Tp(0.01), Tp dec=Tp(0.1), Tv sus=Tv(0.7), Tp rel=Tp(1.), Tv amp=Tv(1), Tp crv=Tp(-4))
ADSR_lite & attack (Tp len)
Set attack length.
ADSR_lite & decay (Tp len)
Set decay length.
ADSR_lite & sustain (Tv val)
Set sustain level.
ADSR_lite & release (Tp len)
Set release length.
ADSR_lite & amp (Tv v)
Set amplitude.
Tp attack () const
Get attack length.
Tp decay () const
Get decay length.
Tv sustain () const
Get sustain level.
Tp release () const
Get release length.
Tv amp () const
Get amplitude.
Public Member Functions inherited from Env_lite< 3, Tv, Tp, Td >
Env_lite (float(*voice)(void))
Env_lite (Tp lvl1, Tp len1, Tp lvl2, float(*voice)(void))
Env_lite (Tp lvl1, Tp len1, Tp lvl2, Tp len2, Tp lvl3, float(*voice)(void))
Env_lite (Tp lvl1, Tp len1, Tp lvl2, Tp len2, Tp lvl3, Tp len3, Tp lvl4, float(*voice)(void))
int size () const
Get the number of segments.
unsigned position () const
Get the position, in samples, within the current segment.
int sustainPoint () const
Get the sustain break-point.
Env_lite & sustainPoint (int v)
Sets the point at which the envelope holds its value until released.
int stage () const
Get the envelope's current segment.
Tv value () const
Get the current envelope value.
bool done () const
Returns whether the envelope is done.
bool released () const
Returns whether the envelope is released.
bool sustained () const
Returns whether the envelope is currently sustained.
Tv operator() ()
Generate next value.
void release ()
Release the envelope.
Env_lite & loop (bool v)
Set whether envelope loops.
Env_lite & sustainDisable ()
Disable sustain.
void reset ()
Reset envelope to starting point.
void resetSoft ()
Reset envelope to starting point setting first level to current level.
void finish ()
Jump to end of envelope.
Tp * lengths ()
Get segment lengths array.
const Tp * lengths () const
Env_lite & lengths (const V *vals, int len)
Set break-point values.
Env_lite & lengths (Tp a, Tp b)
Set first two segment lengths.
Env_lite & lengths (Tp a, Tp b, Tp c)
Set first three segment lengths.
Env_lite & lengths (Tp a, Tp b, Tp c, Tp d)
Set first four segment lengths.
Env_lite & lengths (Tp a, Tp b, Tp c, Tp d, Tp e)
Set first five segment lengths.
Tp totalLength () const
Get total length of all envelope segments.
Env_lite & totalLength (Tp length, int modSegment)
Set total length of envelope by adjusting one segment length.
Env_lite & totalLength (Tp length)
Set total length of envelope by scaling all segment lengths.
Tp * curves ()
Get segment curvature array.
const Tp * curves () const
Env_lite & curves (const V *vals, int len)
Set segment curve amounts.
Env_lite & curves (Tp ca, Tp cb)
Set curvature of first two segments.
Env_lite & curves (Tp ca, Tp cb, Tp cc)
Set curvature of first three segments.
Env_lite & curves (Tp ca, Tp cb, Tp cc, Tp cd)
Set curvature of first four segments.
Env_lite & curve (Tp v)
Set curvature of all segments.
Env_lite & segment (int i, Tp len, Tp crv)
Set length and curvature of a segment.
Env_lite & segments (const V *lens, const V *crvs, int len, int begin=0)
Set length and curvature of many segments.
Env_lite & segments (Tp la, Tp ca, Tp lb, Tp cb)
Set length and curvature of first two segments.
Env_lite & segments (Tp la, Tp ca, Tp lb, Tp cb, Tp lc, Tp cc)
Set length and curvature of first three segments.
Env_lite & segments (Tp la, Tp ca, Tp lb, Tp cb, Tp lc, Tp cc, Tp ld, Tp cd)
Set length and curvature of first four segments.
Tv * levels ()
Get break-point levels array.
const Tv * levels () const
Env_lite & levels (const V *vals, int len)
Set break-point values.
Env_lite & levels (Tv a, Tv b)
Set first two break-point levels.
Env_lite & levels (Tv a, Tv b, Tv c)
Set first three break-point levels.
Env_lite & levels (Tv a, Tv b, Tv c, Tv d)
Set first four break-point levels.
Env_lite & levels (Tv a, Tv b, Tv c, Tv d, Tv e)
Set first five break-point levels.
Env_lite & maxLevel (Tv v)
Set maximum level.
Env_lite & setVoice (float(*voice)(void))
Set function pointer.
Protected Member Functions
ADSR_lite & setLen (int i, Tp v)
Protected Member Functions inherited from Env_lite< 3, Tv, Tp, Td >
void setLen (int i)
Additional Inherited Members
Protected Attributes inherited from Env_lite< 3, Tv, Tp, Td >
gam::Curve< Tv, Tp > mCurve
Tp mLengths [N]
Tp mCurves [N]
Tv mLevels [N+1]
unsigned mPos
unsigned mLen
int mStage
int mSustain
int mLoop
float(* voice_)(void)
Constructor & Destructor Documentation
ADSR_lite()
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> ADSR_lite< Tv, Tp, Td >::ADSR_lite (float(*)(void) voice, Tp att = Tp(0.01), Tp dec = Tp(0.1), Tv sus = Tv(0.7), Tp rel = Tp(1.), Tv amp = Tv(1), Tp crv = Tp(-4))
Parameters
[in] att Attack length
[in] dec Decay length
[in] sus Sustain level (as factor of amplitude)
[in] rel Release length
[in] amp Amplitude
[in] crv Curvature of all segments
Definition at line 411 of file ADSR_lite.hpp.
References ADSR_lite< Tv, Tp, Td >::amp(), ADSR_lite< Tv, Tp, Td >::attack(), Env_lite< 3, Tv, Tp, Td >::curve(), Env_lite< 3, Tv, Tp, Td >::levels(), Env_lite< 3, Tv, Tp, Td >::setVoice(), and Env_lite< 3, Tv, Tp, Td >::sustainPoint().
Member Function Documentation
attack() [1/2]
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> ADSR_lite& ADSR_lite< Tv, Tp, Td >::attack (Tp len)
Set attack length.
Definition at line 426 of file ADSR_lite.hpp.
References ADSR_lite< Tv, Tp, Td >::setLen().
decay() [1/2]
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> ADSR_lite& ADSR_lite< Tv, Tp, Td >::decay (Tp len)
Set decay length.
Definition at line 429 of file ADSR_lite.hpp.
References ADSR_lite< Tv, Tp, Td >::setLen().
sustain() [1/2]
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> ADSR_lite& ADSR_lite< Tv, Tp, Td >::sustain (Tv val)
Set sustain level.
Definition at line 432 of file ADSR_lite.hpp.
References Env_lite< 3, Tv, Tp, Td >::levels().
release() [1/2]
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> ADSR_lite& ADSR_lite< Tv, Tp, Td >::release (Tp len)
Set release length.
Definition at line 438 of file ADSR_lite.hpp.
References ADSR_lite< Tv, Tp, Td >::setLen().
amp() [1/2]
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> ADSR_lite& ADSR_lite< Tv, Tp, Td >::amp (Tv v)
Set amplitude.
Definition at line 441 of file ADSR_lite.hpp.
References Env_lite< 3, Tv, Tp, Td >::maxLevel().
attack() [2/2]
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tp ADSR_lite< Tv, Tp, Td >::attack () const
Get attack length.
Definition at line 445 of file ADSR_lite.hpp.
References Env_lite< 3, Tv, Tp, Td >::lengths().
Referenced by ADSR_lite< Tv, Tp, Td >::ADSR_lite().
decay() [2/2]
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tp ADSR_lite< Tv, Tp, Td >::decay () const
Get decay length.
Definition at line 448 of file ADSR_lite.hpp.
References Env_lite< 3, Tv, Tp, Td >::lengths().
sustain() [2/2]
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tv ADSR_lite< Tv, Tp, Td >::sustain () const
Get sustain level.
Definition at line 451 of file ADSR_lite.hpp.
References Env_lite< 3, Tv, Tp, Td >::levels().
release() [2/2]
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tp ADSR_lite< Tv, Tp, Td >::release () const
Get release length.
Definition at line 454 of file ADSR_lite.hpp.
References Env_lite< 3, Tv, Tp, Td >::lengths().
amp() [2/2]
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tv ADSR_lite< Tv, Tp, Td >::amp () const
Get amplitude.
Definition at line 457 of file ADSR_lite.hpp.
References Env_lite< 3, Tv, Tp, Td >::levels().
Referenced by ADSR_lite< Tv, Tp, Td >::ADSR_lite().
setLen()
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> ADSR_lite& ADSR_lite< Tv, Tp, Td >::setLen (int i, Tp v) protected
Definition at line 460 of file ADSR_lite.hpp.
References Env_lite< 3, Tv, Tp, Td >::lengths().
Referenced by ADSR_lite< Tv, Tp, Td >::attack(), ADSR_lite< Tv, Tp, Td >::decay(), and ADSR_lite< Tv, Tp, Td >::release().
The documentation for this class was generated from the following file:
/home/travis/build/topisani/OTTO/src/util/dsp/ADSR_lite.hpp