OTTO: otto::filesystem::file_status Class Reference
otto::filesystem::file_status Class Reference
#include <filesystem.hpp>
Public Member Functions
file_status () noexcept
file_status (file_type ft, perms prms=perms::unknown) noexcept
file_status (const file_status &) noexcept=default
file_status (file_status &&) noexcept=default
~file_status ()
file_status & operator= (const file_status &) noexcept=default
file_status & operator= (file_status &&) noexcept=default
void type (file_type ft) noexcept
void permissions (perms prms) noexcept
file_type type () const noexcept
perms permissions () const noexcept
Detailed Description
Definition at line 292 of file filesystem.hpp.
Constructor & Destructor Documentation
file_status() [1/4]
otto::filesystem::file_status::file_status () inline noexcept
Definition at line 296 of file filesystem.hpp.
 : file_status(file_type::none) {}
file_status() [2/4]
otto::filesystem::file_status::file_status (file_type ft, perms prms = perms::unknown) explicit noexcept
Definition at line 729 of file filesystem.cpp.
     : _type(ft), _perms(prms)
   {}
file_status() [3/4]
otto::filesystem::file_status::file_status (const file_status &) default noexcept
file_status() [4/4]
otto::filesystem::file_status::file_status (file_status &&) default noexcept
~file_status()
otto::filesystem::file_status::~file_status ()
Definition at line 733 of file filesystem.cpp.
 {}
Member Function Documentation
operator=() [1/2]
file_status& otto::filesystem::file_status::operator= (const file_status &) default noexcept
operator=() [2/2]
file_status& otto::filesystem::file_status::operator= (file_status &&) default noexcept
permissions() [1/2]
void otto::filesystem::file_status::permissions (perms prms) noexcept
Definition at line 742 of file filesystem.cpp.
   {
     _perms = prms;
   }
permissions() [2/2]
perms otto::filesystem::file_status::permissions () const noexcept
Definition at line 755 of file filesystem.cpp.
   {
     return _perms;
   }
type() [1/2]
void otto::filesystem::file_status::type (file_type ft) noexcept
Definition at line 737 of file filesystem.cpp.
Referenced by otto::filesystem::exists(), otto::filesystem::is_block_file(), otto::filesystem::is_character_file(), otto::filesystem::is_directory(), otto::filesystem::is_fifo(), otto::filesystem::is_regular_file(), otto::filesystem::is_socket(), and otto::filesystem::is_symlink().
   {
     _type = ft;
   }
type() [2/2]
file_type otto::filesystem::file_status::type () const noexcept
Definition at line 750 of file filesystem.cpp.
   {
     return _type;
   }
The documentation for this class was generated from the following files:
/home/topisani/dev/OTTO/src/util/filesystem.hpp
/home/topisani/dev/OTTO/src/util/filesystem.cpp