OTTO: MidiApi Class Reference
MidiApi Class Reference abstract
#include <RtMidi.h>
Public Member Functions
MidiApi ()
virtual ~MidiApi ()
virtual RtMidi::Api getCurrentApi (void)=0
virtual void openPort (unsigned int portNumber, const std::string &portName)=0
virtual void openVirtualPort (const std::string &portName)=0
virtual void closePort (void)=0
virtual void setClientName (const std::string &clientName)=0
virtual void setPortName (const std::string &portName)=0
virtual unsigned int getPortCount (void)=0
virtual std::string getPortName (unsigned int portNumber)=0
bool isPortOpen () const
void setErrorCallback (RtMidiErrorCallback errorCallback, void *userData)
void error (RtMidiError::Type type, std::string errorString)
A basic error reporting function for RtMidi classes.
Protected Member Functions
virtual void initialize (const std::string &clientName)=0
Protected Attributes
void * apiData_
bool connected_
std::string errorString_
RtMidiErrorCallback errorCallback_
bool firstErrorOccurred_
void * errorCallbackUserData_
Detailed Description
Definition at line 474 of file RtMidi.h.
Constructor & Destructor Documentation
MidiApi()
MidiApi::MidiApi (void)
Definition at line 464 of file RtMidi.cpp.
   : apiData_( 0 ), connected_( false ), errorCallback_(0), firstErrorOccurred_(false), errorCallbackUserData_(0)
 {
 }
~MidiApi()
MidiApi::~MidiApi (void) virtual
Definition at line 469 of file RtMidi.cpp.
 {
 }
Member Function Documentation
closePort()
virtual void MidiApi::closePort (void) pure virtual
Implemented in MidiOutDummy, and MidiInDummy.
Referenced by RtMidiIn::closePort(), and RtMidiOut::closePort().
error()
void MidiApi::error (RtMidiError::Type type, std::string errorString)
A basic error reporting function for RtMidi classes.
Definition at line 479 of file RtMidi.cpp.
References RtMidiError::DEBUG_WARNING, errorCallback_, errorCallbackUserData_, firstErrorOccurred_, and RtMidiError::WARNING.
Referenced by MidiInApi::cancelCallback(), MidiInApi::getMessage(), MidiInDummy::MidiInDummy(), MidiOutDummy::MidiOutDummy(), and MidiInApi::setCallback().
 {
   if ( errorCallback_ ) {
     if ( firstErrorOccurred_ )
       return;
     firstErrorOccurred_ = true;
     const std::string errorMessage = errorString;
     errorCallback_( type, errorMessage, errorCallbackUserData_);
     firstErrorOccurred_ = false;
     return;
   }
   if ( type == RtMidiError::WARNING ) {
     std::cerr << '\n' << errorString << "\n\n";
   }
   else if ( type == RtMidiError::DEBUG_WARNING ) {
 #if defined(__RTMIDI_DEBUG__)
     std::cerr << '\n' << errorString << "\n\n";
 #endif
   }
   else {
     std::cerr << '\n' << errorString << "\n\n";
     throw RtMidiError( errorString, type );
   }
 }
getCurrentApi()
virtual RtMidi::Api MidiApi::getCurrentApi (void) pure virtual
Implemented in MidiOutDummy, and MidiInDummy.
getPortCount()
virtual unsigned int MidiApi::getPortCount (void) pure virtual
Implemented in MidiOutDummy, and MidiInDummy.
Referenced by RtMidiIn::getPortCount(), RtMidiOut::getPortCount(), RtMidiIn::RtMidiIn(), and RtMidiOut::RtMidiOut().
getPortName()
virtual std::string MidiApi::getPortName (unsigned int portNumber) pure virtual
Implemented in MidiOutDummy, and MidiInDummy.
Referenced by RtMidiIn::getPortName(), and RtMidiOut::getPortName().
initialize()
virtual void MidiApi::initialize (const std::string & clientName) protected pure virtual
Implemented in MidiOutDummy, and MidiInDummy.
isPortOpen()
bool MidiApi::isPortOpen (void) const inline
Definition at line 490 of file RtMidi.h.
Referenced by RtMidiIn::isPortOpen(), and RtMidiOut::isPortOpen().
 { return connected_; }
openPort()
virtual void MidiApi::openPort (unsigned int portNumber, const std::string & portName) pure virtual
Implemented in MidiOutDummy, and MidiInDummy.
Referenced by RtMidiIn::openPort(), and RtMidiOut::openPort().
openVirtualPort()
virtual void MidiApi::openVirtualPort (const std::string & portName) pure virtual
Implemented in MidiOutDummy, and MidiInDummy.
Referenced by RtMidiIn::openVirtualPort(), and RtMidiOut::openVirtualPort().
setClientName()
virtual void MidiApi::setClientName (const std::string & clientName) pure virtual
Implemented in MidiOutDummy, and MidiInDummy.
Referenced by RtMidi::setClientName().
setErrorCallback()
void MidiApi::setErrorCallback (RtMidiErrorCallback errorCallback, void * userData = 0)
Definition at line 473 of file RtMidi.cpp.
References errorCallback_, and errorCallbackUserData_.
Referenced by RtMidiIn::setErrorCallback(), and RtMidiOut::setErrorCallback().
 {
     errorCallback_ = errorCallback;
     errorCallbackUserData_ = userData;
 }
setPortName()
virtual void MidiApi::setPortName (const std::string & portName) pure virtual
Implemented in MidiOutDummy, and MidiInDummy.
Referenced by RtMidi::setPortName().
Member Data Documentation
apiData_
void* MidiApi::apiData_ protected
Definition at line 499 of file RtMidi.h.
connected_
bool MidiApi::connected_ protected
Definition at line 500 of file RtMidi.h.
errorCallback_
RtMidiErrorCallback MidiApi::errorCallback_ protected
Definition at line 502 of file RtMidi.h.
Referenced by error(), and setErrorCallback().
errorCallbackUserData_
void* MidiApi::errorCallbackUserData_ protected
Definition at line 504 of file RtMidi.h.
Referenced by error(), and setErrorCallback().
errorString_
std::string MidiApi::errorString_ protected
Definition at line 501 of file RtMidi.h.
Referenced by MidiInApi::cancelCallback(), MidiInApi::getMessage(), MidiInDummy::MidiInDummy(), MidiOutDummy::MidiOutDummy(), and MidiInApi::setCallback().
firstErrorOccurred_
bool MidiApi::firstErrorOccurred_ protected
Definition at line 503 of file RtMidi.h.
Referenced by error().
The documentation for this class was generated from the following files:
/home/topisani/dev/OTTO/boards/parts/audio/rtaudio/include/RtMidi.h
/home/topisani/dev/OTTO/boards/parts/audio/rtaudio/src/RtMidi.cpp