OTTO: RtApi Class Reference
RtApi Class Reference abstract
#include <RtAudio.h>
Classes
struct ConvertInfo
struct RtApiStream
Public Member Functions
RtApi ()
virtual ~RtApi ()
virtual RtAudio::Api getCurrentApi (void)=0
virtual unsigned int getDeviceCount (void)=0
virtual RtAudio::DeviceInfo getDeviceInfo (unsigned int device)=0
virtual unsigned int getDefaultInputDevice (void)
virtual unsigned int getDefaultOutputDevice (void)
void openStream (RtAudio::StreamParameters *outputParameters, RtAudio::StreamParameters *inputParameters, RtAudioFormat format, unsigned int sampleRate, unsigned int *bufferFrames, RtAudioCallback callback, void *userData, RtAudio::StreamOptions *options, RtAudioErrorCallback errorCallback)
virtual void closeStream (void)
virtual void startStream (void)=0
virtual void stopStream (void)=0
virtual void abortStream (void)=0
long getStreamLatency (void)
unsigned int getStreamSampleRate (void)
virtual double getStreamTime (void)
virtual void setStreamTime (double time)
bool isStreamOpen (void) const
bool isStreamRunning (void) const
void showWarnings (bool value)
Protected Types
enum { FAILURE, SUCCESS }
enum StreamState { STREAM_STOPPED, STREAM_STOPPING, STREAM_RUNNING, STREAM_CLOSED = -50 }
enum StreamMode { OUTPUT, INPUT, DUPLEX, UNINITIALIZED = -75 }
typedef S24 Int24
typedef signed short Int16
typedef signed int Int32
typedef float Float32
typedef double Float64
Protected Member Functions
virtual bool probeDeviceOpen (unsigned int device, StreamMode mode, unsigned int channels, unsigned int firstChannel, unsigned int sampleRate, RtAudioFormat format, unsigned int *bufferSize, RtAudio::StreamOptions *options)
void tickStreamTime (void)
A protected function used to increment the stream time.
void clearStreamInfo ()
Protected common method to clear an RtApiStream structure.
void verifyStream (void)
void error (RtAudioError::Type type)
Protected common error method to allow global control over error handling.
void convertBuffer (char *outBuffer, char *inBuffer, ConvertInfo &info)
void byteSwapBuffer (char *buffer, unsigned int samples, RtAudioFormat format)
Protected common method used to perform byte-swapping on buffers.
unsigned int formatBytes (RtAudioFormat format)
Protected common method that returns the number of bytes for a given format.
void setConvertInfo (StreamMode mode, unsigned int firstChannel)
Protected common method that sets up the parameters for buffer conversion.
Protected Attributes
std::ostringstream errorStream_
std::string errorText_
bool showWarnings_
RtApiStream stream_
bool firstErrorOccurred_
Static Protected Attributes
static const unsigned int MAX_SAMPLE_RATES = 14
static const unsigned int SAMPLE_RATES []
Detailed Description
Definition at line 684 of file RtAudio.h.
Member Typedef Documentation
Float32
typedef float RtApi::Float32 protected
Definition at line 781 of file RtAudio.h.
Float64
typedef double RtApi::Float64 protected
Definition at line 782 of file RtAudio.h.
Int16
typedef signed short RtApi::Int16 protected
Definition at line 779 of file RtAudio.h.
Int24
typedef S24 RtApi::Int24 protected
Definition at line 778 of file RtAudio.h.
Int32
typedef signed int RtApi::Int32 protected
Definition at line 780 of file RtAudio.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
FAILURE
SUCCESS
Definition at line 719 of file RtAudio.h.
 { FAILURE, SUCCESS };
StreamMode
enum RtApi::StreamMode protected
Enumerator
OUTPUT
INPUT
DUPLEX
UNINITIALIZED
Definition at line 728 of file RtAudio.h.
                   {
     OUTPUT,
     INPUT,
     DUPLEX,
     UNINITIALIZED = -75
   };
StreamState
enum RtApi::StreamState protected
Enumerator
STREAM_STOPPED
STREAM_STOPPING
STREAM_RUNNING
STREAM_CLOSED
Definition at line 721 of file RtAudio.h.
                    {
     STREAM_STOPPED,
     STREAM_STOPPING,
     STREAM_RUNNING,
     STREAM_CLOSED = -50
   };
Constructor & Destructor Documentation
RtApi()
RtApi::RtApi ()
Definition at line 239 of file RtAudio.cpp.
References RtApi::RtApiStream::apiHandle, firstErrorOccurred_, RtApi::RtApiStream::mode, RtApi::RtApiStream::mutex, showWarnings_, RtApi::RtApiStream::state, stream_, STREAM_CLOSED, UNINITIALIZED, and RtApi::RtApiStream::userBuffer.
 {
   stream_.state = STREAM_CLOSED;
   stream_.mode = UNINITIALIZED;
   stream_.apiHandle = 0;
   stream_.userBuffer[0] = 0;
   stream_.userBuffer[1] = 0;
   MUTEX_INITIALIZE( &stream_.mutex );
   showWarnings_ = true;
   firstErrorOccurred_ = false;
 }
~RtApi()
RtApi::~RtApi () virtual
Definition at line 251 of file RtAudio.cpp.
References RtApi::RtApiStream::mutex, and stream_.
 {
   MUTEX_DESTROY( &stream_.mutex );
 }
Member Function Documentation
abortStream()
virtual void RtApi::abortStream (void) pure virtual
Implemented in RtApiDummy.
Referenced by RtAudio::abortStream(), and error().
byteSwapBuffer()
void RtApi::byteSwapBuffer (char * buffer, unsigned int samples, RtAudioFormat format) protected
Protected common method used to perform byte-swapping on buffers.
Definition at line 10158 of file RtAudio.cpp.
 {
   char val;
   char *ptr;
   ptr = buffer;
   if ( format == RTAUDIO_SINT16 ) {
     for ( unsigned int i=0; i<samples; i++ ) {
       // Swap 1st and 2nd bytes.
       val = *(ptr);
       *(ptr) = *(ptr+1);
       *(ptr+1) = val;
       // Increment 2 bytes.
       ptr += 2;
     }
   }
   else if ( format == RTAUDIO_SINT32 ||
             format == RTAUDIO_FLOAT32 ) {
     for ( unsigned int i=0; i<samples; i++ ) {
       // Swap 1st and 4th bytes.
       val = *(ptr);
       *(ptr) = *(ptr+3);
       *(ptr+3) = val;
       // Swap 2nd and 3rd bytes.
       ptr += 1;
       val = *(ptr);
       *(ptr) = *(ptr+1);
       *(ptr+1) = val;
       // Increment 3 more bytes.
       ptr += 3;
     }
   }
   else if ( format == RTAUDIO_SINT24 ) {
     for ( unsigned int i=0; i<samples; i++ ) {
       // Swap 1st and 3rd bytes.
       val = *(ptr);
       *(ptr) = *(ptr+2);
       *(ptr+2) = val;
       // Increment 2 more bytes.
       ptr += 2;
     }
   }
   else if ( format == RTAUDIO_FLOAT64 ) {
     for ( unsigned int i=0; i<samples; i++ ) {
       // Swap 1st and 8th bytes
       val = *(ptr);
       *(ptr) = *(ptr+7);
       *(ptr+7) = val;
       // Swap 2nd and 7th bytes
       ptr += 1;
       val = *(ptr);
       *(ptr) = *(ptr+5);
       *(ptr+5) = val;
       // Swap 3rd and 6th bytes
       ptr += 1;
       val = *(ptr);
       *(ptr) = *(ptr+3);
       *(ptr+3) = val;
       // Swap 4th and 5th bytes
       ptr += 1;
       val = *(ptr);
       *(ptr) = *(ptr+1);
       *(ptr+1) = val;
       // Increment 5 more bytes.
       ptr += 5;
     }
   }
 }
clearStreamInfo()
void RtApi::clearStreamInfo () protected
Protected common method to clear an RtApiStream structure.
Definition at line 9585 of file RtAudio.cpp.
References RtApi::RtApiStream::apiHandle, RtApi::RtApiStream::bufferSize, CallbackInfo::callback, RtApi::RtApiStream::callbackInfo, RtApi::RtApiStream::channelOffset, RtApi::ConvertInfo::channels, RtApi::RtApiStream::convertInfo, RtApi::RtApiStream::device, RtApi::RtApiStream::deviceBuffer, RtApi::RtApiStream::deviceFormat, RtApi::RtApiStream::deviceInterleaved, RtApi::RtApiStream::doByteSwap, RtApi::RtApiStream::doConvertBuffer, CallbackInfo::errorCallback, RtApi::ConvertInfo::inFormat, RtApi::ConvertInfo::inJump, RtApi::ConvertInfo::inOffset, CallbackInfo::isRunning, RtApi::RtApiStream::latency, RtApi::RtApiStream::mode, RtApi::RtApiStream::nBuffers, RtApi::RtApiStream::nDeviceChannels, RtApi::RtApiStream::nUserChannels, RtApi::ConvertInfo::outFormat, RtApi::ConvertInfo::outJump, RtApi::ConvertInfo::outOffset, RtApi::RtApiStream::sampleRate, RtApi::RtApiStream::state, stream_, STREAM_CLOSED, RtApi::RtApiStream::streamTime, UNINITIALIZED, RtApi::RtApiStream::userBuffer, CallbackInfo::userData, RtApi::RtApiStream::userFormat, and RtApi::RtApiStream::userInterleaved.
Referenced by openStream().
 {
   stream_.mode = UNINITIALIZED;
   stream_.state = STREAM_CLOSED;
   stream_.sampleRate = 0;
   stream_.bufferSize = 0;
   stream_.nBuffers = 0;
   stream_.userFormat = 0;
   stream_.userInterleaved = true;
   stream_.streamTime = 0.0;
   stream_.apiHandle = 0;
   stream_.deviceBuffer = 0;
   stream_.callbackInfo.callback = 0;
   stream_.callbackInfo.userData = 0;
   stream_.callbackInfo.isRunning = false;
   stream_.callbackInfo.errorCallback = 0;
   for ( int i=0; i<2; i++ ) {
     stream_.device[i] = 11111;
     stream_.doConvertBuffer[i] = false;
     stream_.deviceInterleaved[i] = true;
     stream_.doByteSwap[i] = false;
     stream_.nUserChannels[i] = 0;
     stream_.nDeviceChannels[i] = 0;
     stream_.channelOffset[i] = 0;
     stream_.deviceFormat[i] = 0;
     stream_.latency[i] = 0;
     stream_.userBuffer[i] = 0;
     stream_.convertInfo[i].channels = 0;
     stream_.convertInfo[i].inJump = 0;
     stream_.convertInfo[i].outJump = 0;
     stream_.convertInfo[i].inFormat = 0;
     stream_.convertInfo[i].outFormat = 0;
     stream_.convertInfo[i].inOffset.clear();
     stream_.convertInfo[i].outOffset.clear();
   }
 }
closeStream()
void RtApi::closeStream (void) virtual
Reimplemented in RtApiDummy.
Definition at line 361 of file RtAudio.cpp.
Referenced by RtAudio::closeStream(), and openStream().
 {
   // MUST be implemented in subclasses!
   return;
 }
convertBuffer()
void RtApi::convertBuffer (char * outBuffer, char * inBuffer, ConvertInfo & info) protected
Protected method used to perform format, channel number, and/or interleaving conversions between the user and device buffers.
Definition at line 9721 of file RtAudio.cpp.
References S24::asInt(), RtApi::RtApiStream::bufferSize, RtApi::ConvertInfo::channels, RtApi::RtApiStream::deviceBuffer, DUPLEX, formatBytes(), RtApi::ConvertInfo::inFormat, RtApi::ConvertInfo::inJump, RtApi::ConvertInfo::inOffset, RtApi::RtApiStream::mode, RtApi::RtApiStream::nDeviceChannels, RtApi::ConvertInfo::outFormat, RtApi::ConvertInfo::outJump, RtApi::ConvertInfo::outOffset, and stream_.
 {
   // This function does format conversion, input/output channel compensation, and
   // data interleaving/deinterleaving.  24-bit integers are assumed to occupy
   // the lower three bytes of a 32-bit integer.
   // Clear our device buffer when in/out duplex device channels are different
   if ( outBuffer == stream_.deviceBuffer && stream_.mode == DUPLEX &&
        ( stream_.nDeviceChannels[0] < stream_.nDeviceChannels[1] ) )
     memset( outBuffer, 0, stream_.bufferSize * info.outJump * formatBytes( info.outFormat ) );
   int j;
   if (info.outFormat == RTAUDIO_FLOAT64) {
     Float64 scale;
     Float64 *out = (Float64 *)outBuffer;
     if (info.inFormat == RTAUDIO_SINT8) {
       signed char *in = (signed char *)inBuffer;
       scale = 1.0 / 127.5;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Float64) in[info.inOffset[j]];
           out[info.outOffset[j]] += 0.5;
           out[info.outOffset[j]] *= scale;
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_SINT16) {
       Int16 *in = (Int16 *)inBuffer;
       scale = 1.0 / 32767.5;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Float64) in[info.inOffset[j]];
           out[info.outOffset[j]] += 0.5;
           out[info.outOffset[j]] *= scale;
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_SINT24) {
       Int24 *in = (Int24 *)inBuffer;
       scale = 1.0 / 8388607.5;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Float64) (in[info.inOffset[j]].asInt());
           out[info.outOffset[j]] += 0.5;
           out[info.outOffset[j]] *= scale;
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_SINT32) {
       Int32 *in = (Int32 *)inBuffer;
       scale = 1.0 / 2147483647.5;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Float64) in[info.inOffset[j]];
           out[info.outOffset[j]] += 0.5;
           out[info.outOffset[j]] *= scale;
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_FLOAT32) {
       Float32 *in = (Float32 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Float64) in[info.inOffset[j]];
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_FLOAT64) {
       // Channel compensation and/or (de)interleaving only.
       Float64 *in = (Float64 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = in[info.inOffset[j]];
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
   }
   else if (info.outFormat == RTAUDIO_FLOAT32) {
     Float32 scale;
     Float32 *out = (Float32 *)outBuffer;
     if (info.inFormat == RTAUDIO_SINT8) {
       signed char *in = (signed char *)inBuffer;
       scale = (Float32) ( 1.0 / 127.5 );
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Float32) in[info.inOffset[j]];
           out[info.outOffset[j]] += 0.5;
           out[info.outOffset[j]] *= scale;
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_SINT16) {
       Int16 *in = (Int16 *)inBuffer;
       scale = (Float32) ( 1.0 / 32767.5 );
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Float32) in[info.inOffset[j]];
           out[info.outOffset[j]] += 0.5;
           out[info.outOffset[j]] *= scale;
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_SINT24) {
       Int24 *in = (Int24 *)inBuffer;
       scale = (Float32) ( 1.0 / 8388607.5 );
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Float32) (in[info.inOffset[j]].asInt());
           out[info.outOffset[j]] += 0.5;
           out[info.outOffset[j]] *= scale;
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_SINT32) {
       Int32 *in = (Int32 *)inBuffer;
       scale = (Float32) ( 1.0 / 2147483647.5 );
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Float32) in[info.inOffset[j]];
           out[info.outOffset[j]] += 0.5;
           out[info.outOffset[j]] *= scale;
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_FLOAT32) {
       // Channel compensation and/or (de)interleaving only.
       Float32 *in = (Float32 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = in[info.inOffset[j]];
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_FLOAT64) {
       Float64 *in = (Float64 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Float32) in[info.inOffset[j]];
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
   }
   else if (info.outFormat == RTAUDIO_SINT32) {
     Int32 *out = (Int32 *)outBuffer;
     if (info.inFormat == RTAUDIO_SINT8) {
       signed char *in = (signed char *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Int32) in[info.inOffset[j]];
           out[info.outOffset[j]] <<= 24;
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_SINT16) {
       Int16 *in = (Int16 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Int32) in[info.inOffset[j]];
           out[info.outOffset[j]] <<= 16;
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_SINT24) {
       Int24 *in = (Int24 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Int32) in[info.inOffset[j]].asInt();
           out[info.outOffset[j]] <<= 8;
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_SINT32) {
       // Channel compensation and/or (de)interleaving only.
       Int32 *in = (Int32 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = in[info.inOffset[j]];
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_FLOAT32) {
       Float32 *in = (Float32 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Int32) (in[info.inOffset[j]] * 2147483647.5 - 0.5);
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_FLOAT64) {
       Float64 *in = (Float64 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Int32) (in[info.inOffset[j]] * 2147483647.5 - 0.5);
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
   }
   else if (info.outFormat == RTAUDIO_SINT24) {
     Int24 *out = (Int24 *)outBuffer;
     if (info.inFormat == RTAUDIO_SINT8) {
       signed char *in = (signed char *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Int32) (in[info.inOffset[j]] << 16);
           //out[info.outOffset[j]] <<= 16;
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_SINT16) {
       Int16 *in = (Int16 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Int32) (in[info.inOffset[j]] << 8);
           //out[info.outOffset[j]] <<= 8;
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_SINT24) {
       // Channel compensation and/or (de)interleaving only.
       Int24 *in = (Int24 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = in[info.inOffset[j]];
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_SINT32) {
       Int32 *in = (Int32 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Int32) (in[info.inOffset[j]] >> 8);
           //out[info.outOffset[j]] >>= 8;
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_FLOAT32) {
       Float32 *in = (Float32 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Int32) (in[info.inOffset[j]] * 8388607.5 - 0.5);
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_FLOAT64) {
       Float64 *in = (Float64 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Int32) (in[info.inOffset[j]] * 8388607.5 - 0.5);
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
   }
   else if (info.outFormat == RTAUDIO_SINT16) {
     Int16 *out = (Int16 *)outBuffer;
     if (info.inFormat == RTAUDIO_SINT8) {
       signed char *in = (signed char *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Int16) in[info.inOffset[j]];
           out[info.outOffset[j]] <<= 8;
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_SINT16) {
       // Channel compensation and/or (de)interleaving only.
       Int16 *in = (Int16 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = in[info.inOffset[j]];
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_SINT24) {
       Int24 *in = (Int24 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Int16) (in[info.inOffset[j]].asInt() >> 8);
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_SINT32) {
       Int32 *in = (Int32 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Int16) ((in[info.inOffset[j]] >> 16) & 0x0000ffff);
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_FLOAT32) {
       Float32 *in = (Float32 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Int16) (in[info.inOffset[j]] * 32767.5 - 0.5);
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_FLOAT64) {
       Float64 *in = (Float64 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (Int16) (in[info.inOffset[j]] * 32767.5 - 0.5);
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
   }
   else if (info.outFormat == RTAUDIO_SINT8) {
     signed char *out = (signed char *)outBuffer;
     if (info.inFormat == RTAUDIO_SINT8) {
       // Channel compensation and/or (de)interleaving only.
       signed char *in = (signed char *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = in[info.inOffset[j]];
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     if (info.inFormat == RTAUDIO_SINT16) {
       Int16 *in = (Int16 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (signed char) ((in[info.inOffset[j]] >> 8) & 0x00ff);
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_SINT24) {
       Int24 *in = (Int24 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (signed char) (in[info.inOffset[j]].asInt() >> 16);
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_SINT32) {
       Int32 *in = (Int32 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (signed char) ((in[info.inOffset[j]] >> 24) & 0x000000ff);
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_FLOAT32) {
       Float32 *in = (Float32 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (signed char) (in[info.inOffset[j]] * 127.5 - 0.5);
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
     else if (info.inFormat == RTAUDIO_FLOAT64) {
       Float64 *in = (Float64 *)inBuffer;
       for (unsigned int i=0; i<stream_.bufferSize; i++) {
         for (j=0; j<info.channels; j++) {
           out[info.outOffset[j]] = (signed char) (in[info.inOffset[j]] * 127.5 - 0.5);
         }
         in += info.inJump;
         out += info.outJump;
       }
     }
   }
 }
error()
void RtApi::error (RtAudioError::Type type) protected
Protected common error method to allow global control over error handling.
Definition at line 9547 of file RtAudio.cpp.
References abortStream(), RtApi::RtApiStream::callbackInfo, CallbackInfo::errorCallback, errorStream_, errorText_, firstErrorOccurred_, CallbackInfo::isRunning, showWarnings_, RtApi::RtApiStream::state, stream_, STREAM_STOPPED, and RtAudioError::WARNING.
Referenced by formatBytes(), openStream(), RtApiDummy::RtApiDummy(), and verifyStream().
 {
   errorStream_.str(""); // clear the ostringstream
   RtAudioErrorCallback errorCallback = (RtAudioErrorCallback) stream_.callbackInfo.errorCallback;
   if ( errorCallback ) {
     // abortStream() can generate new error messages. Ignore them. Just keep original one.
     if ( firstErrorOccurred_ )
       return;
     firstErrorOccurred_ = true;
     const std::string errorMessage = errorText_;
     if ( type != RtAudioError::WARNING && stream_.state != STREAM_STOPPED) {
       stream_.callbackInfo.isRunning = false; // exit from the thread
       abortStream();
     }
     errorCallback( type, errorMessage );
     firstErrorOccurred_ = false;
     return;
   }
   if ( type == RtAudioError::WARNING && showWarnings_ == true )
     std::cerr << '\n' << errorText_ << "\n\n";
   else if ( type != RtAudioError::WARNING )
     throw( RtAudioError( errorText_, type ) );
 }
formatBytes()
unsigned int RtApi::formatBytes (RtAudioFormat format) protected
Protected common method that returns the number of bytes for a given format.
Definition at line 9622 of file RtAudio.cpp.
References error(), errorText_, and RtAudioError::WARNING.
Referenced by convertBuffer(), and openStream().
 {
   if ( format == RTAUDIO_SINT16 )
     return 2;
   else if ( format == RTAUDIO_SINT32 || format == RTAUDIO_FLOAT32 )
     return 4;
   else if ( format == RTAUDIO_FLOAT64 )
     return 8;
   else if ( format == RTAUDIO_SINT24 )
     return 3;
   else if ( format == RTAUDIO_SINT8 )
     return 1;
   errorText_ = "RtApi::formatBytes: undefined format.";
   error( RtAudioError::WARNING );
   return 0;
 }
getCurrentApi()
virtual RtAudio::Api RtApi::getCurrentApi (void) pure virtual
Implemented in RtApiDummy.
Referenced by RtAudio::getCurrentApi().
getDefaultInputDevice()
unsigned int RtApi::getDefaultInputDevice (void) virtual
Definition at line 349 of file RtAudio.cpp.
Referenced by RtAudio::getDefaultInputDevice().
 {
   // Should be implemented in subclasses if possible.
   return 0;
 }
getDefaultOutputDevice()
unsigned int RtApi::getDefaultOutputDevice (void) virtual
Definition at line 355 of file RtAudio.cpp.
Referenced by RtAudio::getDefaultOutputDevice().
 {
   // Should be implemented in subclasses if possible.
   return 0;
 }
getDeviceCount()
virtual unsigned int RtApi::getDeviceCount (void) pure virtual
Implemented in RtApiDummy.
Referenced by RtAudio::getDeviceCount(), openStream(), and RtAudio::RtAudio().
getDeviceInfo()
virtual RtAudio::DeviceInfo RtApi::getDeviceInfo (unsigned int device) pure virtual
Implemented in RtApiDummy.
Referenced by RtAudio::getDeviceInfo().
getStreamLatency()
long RtApi::getStreamLatency (void)
Definition at line 389 of file RtAudio.cpp.
References DUPLEX, INPUT, RtApi::RtApiStream::latency, RtApi::RtApiStream::mode, OUTPUT, stream_, and verifyStream().
Referenced by RtAudio::getStreamLatency().
 {
   verifyStream();
   long totalLatency = 0;
   if ( stream_.mode == OUTPUT || stream_.mode == DUPLEX )
     totalLatency = stream_.latency[0];
   if ( stream_.mode == INPUT || stream_.mode == DUPLEX )
     totalLatency += stream_.latency[1];
   return totalLatency;
 }
getStreamSampleRate()
unsigned int RtApi::getStreamSampleRate (void)
Definition at line 436 of file RtAudio.cpp.
References RtApi::RtApiStream::sampleRate, stream_, and verifyStream().
Referenced by RtAudio::getStreamSampleRate().
 {
  verifyStream();
  return stream_.sampleRate;
 }
getStreamTime()
double RtApi::getStreamTime (void) virtual
Definition at line 402 of file RtAudio.cpp.
References RtApi::RtApiStream::state, stream_, STREAM_RUNNING, RtApi::RtApiStream::streamTime, and verifyStream().
Referenced by RtAudio::getStreamTime().
 {
   verifyStream();
 #if defined( HAVE_GETTIMEOFDAY )
   // Return a very accurate estimate of the stream time by
   // adding in the elapsed time since the last tick.
   struct timeval then;
   struct timeval now;
   if ( stream_.state != STREAM_RUNNING || stream_.streamTime == 0.0 )
     return stream_.streamTime;
   gettimeofday( &now, NULL );
   then = stream_.lastTickTimestamp;
   return stream_.streamTime +
     ((now.tv_sec + 0.000001 * now.tv_usec) -
      (then.tv_sec + 0.000001 * then.tv_usec));
 #else
   return stream_.streamTime;
 #endif
 }
isStreamOpen()
bool RtApi::isStreamOpen (void) const inline
Definition at line 709 of file RtAudio.h.
Referenced by RtAudio::isStreamOpen().
 { return stream_.state != STREAM_CLOSED; }
isStreamRunning()
bool RtApi::isStreamRunning (void) const inline
Definition at line 710 of file RtAudio.h.
Referenced by RtAudio::isStreamRunning().
 { return stream_.state == STREAM_RUNNING; }
openStream()
void RtApi::openStream (RtAudio::StreamParameters * outputParameters, RtAudio::StreamParameters * inputParameters, RtAudioFormat format, unsigned int sampleRate, unsigned int * bufferFrames, RtAudioCallback callback, void * userData, RtAudio::StreamOptions * options, RtAudioErrorCallback errorCallback)
Definition at line 256 of file RtAudio.cpp.
References CallbackInfo::callback, RtApi::RtApiStream::callbackInfo, clearStreamInfo(), closeStream(), RtAudio::StreamParameters::deviceId, error(), CallbackInfo::errorCallback, errorText_, RtAudio::StreamParameters::firstChannel, formatBytes(), getDeviceCount(), INPUT, RtAudioError::INVALID_USE, RtApi::RtApiStream::nBuffers, RtAudio::StreamParameters::nChannels, RtAudio::StreamOptions::numberOfBuffers, OUTPUT, probeDeviceOpen(), RtApi::RtApiStream::state, stream_, STREAM_CLOSED, STREAM_STOPPED, RtAudioError::SYSTEM_ERROR, and CallbackInfo::userData.
Referenced by RtAudio::openStream().
 {
   if ( stream_.state != STREAM_CLOSED ) {
     errorText_ = "RtApi::openStream: a stream is already open!";
     error( RtAudioError::INVALID_USE );
     return;
   }
   // Clear stream information potentially left from a previously open stream.
   clearStreamInfo();
   if ( oParams && oParams->nChannels < 1 ) {
     errorText_ = "RtApi::openStream: a non-NULL output StreamParameters structure cannot have an nChannels value less than one.";
     error( RtAudioError::INVALID_USE );
     return;
   }
   if ( iParams && iParams->nChannels < 1 ) {
     errorText_ = "RtApi::openStream: a non-NULL input StreamParameters structure cannot have an nChannels value less than one.";
     error( RtAudioError::INVALID_USE );
     return;
   }
   if ( oParams == NULL && iParams == NULL ) {
     errorText_ = "RtApi::openStream: input and output StreamParameters structures are both NULL!";
     error( RtAudioError::INVALID_USE );
     return;
   }
   if ( formatBytes(format) == 0 ) {
     errorText_ = "RtApi::openStream: 'format' parameter value is undefined.";
     error( RtAudioError::INVALID_USE );
     return;
   }
   unsigned int nDevices = getDeviceCount();
   unsigned int oChannels = 0;
   if ( oParams ) {
     oChannels = oParams->nChannels;
     if ( oParams->deviceId >= nDevices ) {
       errorText_ = "RtApi::openStream: output device parameter value is invalid.";
       error( RtAudioError::INVALID_USE );
       return;
     }
   }
   unsigned int iChannels = 0;
   if ( iParams ) {
     iChannels = iParams->nChannels;
     if ( iParams->deviceId >= nDevices ) {
       errorText_ = "RtApi::openStream: input device parameter value is invalid.";
       error( RtAudioError::INVALID_USE );
       return;
     }
   }
   bool result;
   if ( oChannels > 0 ) {
     result = probeDeviceOpen( oParams->deviceId, OUTPUT, oChannels, oParams->firstChannel,
                               sampleRate, format, bufferFrames, options );
     if ( result == false ) {
       error( RtAudioError::SYSTEM_ERROR );
       return;
     }
   }
   if ( iChannels > 0 ) {
     result = probeDeviceOpen( iParams->deviceId, INPUT, iChannels, iParams->firstChannel,
                               sampleRate, format, bufferFrames, options );
     if ( result == false ) {
       if ( oChannels > 0 ) closeStream();
       error( RtAudioError::SYSTEM_ERROR );
       return;
     }
   }
   stream_.callbackInfo.callback = (void *) callback;
   stream_.callbackInfo.userData = userData;
   stream_.callbackInfo.errorCallback = (void *) errorCallback;
   if ( options ) options->numberOfBuffers = stream_.nBuffers;
   stream_.state = STREAM_STOPPED;
 }
probeDeviceOpen()
bool RtApi::probeDeviceOpen (unsigned int device, StreamMode mode, unsigned int channels, unsigned int firstChannel, unsigned int sampleRate, RtAudioFormat format, unsigned int * bufferSize, RtAudio::StreamOptions * options) protected virtual
Protected, api-specific method that attempts to open a device with the given parameters. This function MUST be implemented by all subclasses. If an error is encountered during the probe, a "warning" message is reported and FAILURE is returned. A successful probe is indicated by a return value of SUCCESS.
Definition at line 367 of file RtAudio.cpp.
References FAILURE.
Referenced by openStream().
 {
   // MUST be implemented in subclasses!
   return FAILURE;
 }
setConvertInfo()
void RtApi::setConvertInfo (StreamMode mode, unsigned int firstChannel) protected
Protected common method that sets up the parameters for buffer conversion.
Definition at line 9641 of file RtAudio.cpp.
References RtApi::RtApiStream::bufferSize, RtApi::ConvertInfo::channels, RtApi::RtApiStream::convertInfo, RtApi::RtApiStream::deviceFormat, RtApi::RtApiStream::deviceInterleaved, RtApi::ConvertInfo::inFormat, RtApi::ConvertInfo::inJump, RtApi::ConvertInfo::inOffset, INPUT, RtApi::RtApiStream::nDeviceChannels, RtApi::RtApiStream::nUserChannels, RtApi::ConvertInfo::outFormat, RtApi::ConvertInfo::outJump, RtApi::ConvertInfo::outOffset, OUTPUT, stream_, RtApi::RtApiStream::userFormat, and RtApi::RtApiStream::userInterleaved.
 {
   if ( mode == INPUT ) { // convert device to user buffer
     stream_.convertInfo[mode].inJump = stream_.nDeviceChannels[1];
     stream_.convertInfo[mode].outJump = stream_.nUserChannels[1];
     stream_.convertInfo[mode].inFormat = stream_.deviceFormat[1];
     stream_.convertInfo[mode].outFormat = stream_.userFormat;
   }
   else { // convert user to device buffer
     stream_.convertInfo[mode].inJump = stream_.nUserChannels[0];
     stream_.convertInfo[mode].outJump = stream_.nDeviceChannels[0];
     stream_.convertInfo[mode].inFormat = stream_.userFormat;
     stream_.convertInfo[mode].outFormat = stream_.deviceFormat[0];
   }
   if ( stream_.convertInfo[mode].inJump < stream_.convertInfo[mode].outJump )
     stream_.convertInfo[mode].channels = stream_.convertInfo[mode].inJump;
   else
     stream_.convertInfo[mode].channels = stream_.convertInfo[mode].outJump;
   // Set up the interleave/deinterleave offsets.
   if ( stream_.deviceInterleaved[mode] != stream_.userInterleaved ) {
     if ( ( mode == OUTPUT && stream_.deviceInterleaved[mode] ) ||
          ( mode == INPUT && stream_.userInterleaved ) ) {
       for ( int k=0; k<stream_.convertInfo[mode].channels; k++ ) {
         stream_.convertInfo[mode].inOffset.push_back( k * stream_.bufferSize );
         stream_.convertInfo[mode].outOffset.push_back( k );
         stream_.convertInfo[mode].inJump = 1;
       }
     }
     else {
       for ( int k=0; k<stream_.convertInfo[mode].channels; k++ ) {
         stream_.convertInfo[mode].inOffset.push_back( k );
         stream_.convertInfo[mode].outOffset.push_back( k * stream_.bufferSize );
         stream_.convertInfo[mode].outJump = 1;
       }
     }
   }
   else { // no (de)interleaving
     if ( stream_.userInterleaved ) {
       for ( int k=0; k<stream_.convertInfo[mode].channels; k++ ) {
         stream_.convertInfo[mode].inOffset.push_back( k );
         stream_.convertInfo[mode].outOffset.push_back( k );
       }
     }
     else {
       for ( int k=0; k<stream_.convertInfo[mode].channels; k++ ) {
         stream_.convertInfo[mode].inOffset.push_back( k * stream_.bufferSize );
         stream_.convertInfo[mode].outOffset.push_back( k * stream_.bufferSize );
         stream_.convertInfo[mode].inJump = 1;
         stream_.convertInfo[mode].outJump = 1;
       }
     }
   }
   // Add channel offset.
   if ( firstChannel > 0 ) {
     if ( stream_.deviceInterleaved[mode] ) {
       if ( mode == OUTPUT ) {
         for ( int k=0; k<stream_.convertInfo[mode].channels; k++ )
           stream_.convertInfo[mode].outOffset[k] += firstChannel;
       }
       else {
         for ( int k=0; k<stream_.convertInfo[mode].channels; k++ )
           stream_.convertInfo[mode].inOffset[k] += firstChannel;
       }
     }
     else {
       if ( mode == OUTPUT ) {
         for ( int k=0; k<stream_.convertInfo[mode].channels; k++ )
           stream_.convertInfo[mode].outOffset[k] += ( firstChannel * stream_.bufferSize );
       }
       else {
         for ( int k=0; k<stream_.convertInfo[mode].channels; k++ )
           stream_.convertInfo[mode].inOffset[k] += ( firstChannel  * stream_.bufferSize );
       }
     }
   }
 }
setStreamTime()
void RtApi::setStreamTime (double time) virtual
Definition at line 425 of file RtAudio.cpp.
References stream_, RtApi::RtApiStream::streamTime, and verifyStream().
Referenced by RtAudio::setStreamTime().
 {
   verifyStream();
   if ( time >= 0.0 )
     stream_.streamTime = time;
 #if defined( HAVE_GETTIMEOFDAY )
   gettimeofday( &stream_.lastTickTimestamp, NULL );
 #endif
 }
showWarnings()
void RtApi::showWarnings (bool value) inline
Definition at line 711 of file RtAudio.h.
Referenced by RtAudio::showWarnings().
 { showWarnings_ = value; }
startStream()
virtual void RtApi::startStream (void) pure virtual
Implemented in RtApiDummy.
Referenced by RtAudio::startStream().
stopStream()
virtual void RtApi::stopStream (void) pure virtual
Implemented in RtApiDummy.
Referenced by RtAudio::stopStream().
tickStreamTime()
void RtApi::tickStreamTime (void) protected
A protected function used to increment the stream time.
Definition at line 376 of file RtAudio.cpp.
References RtApi::RtApiStream::bufferSize, RtApi::RtApiStream::sampleRate, stream_, and RtApi::RtApiStream::streamTime.
 {
   // Subclasses that do not provide their own implementation of
   // getStreamTime should call this function once per buffer I/O to
   // provide basic stream time support.
   stream_.streamTime += ( stream_.bufferSize * 1.0 / stream_.sampleRate );
 #if defined( HAVE_GETTIMEOFDAY )
   gettimeofday( &stream_.lastTickTimestamp, NULL );
 #endif
 }
verifyStream()
void RtApi::verifyStream (void) protected
Protected common method that throws an RtAudioError (type = INVALID_USE) if a stream is not open.
Definition at line 9577 of file RtAudio.cpp.
References error(), errorText_, RtAudioError::INVALID_USE, RtApi::RtApiStream::state, stream_, and STREAM_CLOSED.
Referenced by getStreamLatency(), getStreamSampleRate(), getStreamTime(), and setStreamTime().
 {
   if ( stream_.state == STREAM_CLOSED ) {
     errorText_ = "RtApi:: a stream is not open!";
     error( RtAudioError::INVALID_USE );
   }
 }
Member Data Documentation
errorStream_
std::ostringstream RtApi::errorStream_ protected
Definition at line 784 of file RtAudio.h.
Referenced by error().
errorText_
std::string RtApi::errorText_ protected
Definition at line 785 of file RtAudio.h.
Referenced by error(), formatBytes(), openStream(), RtApiDummy::RtApiDummy(), and verifyStream().
firstErrorOccurred_
bool RtApi::firstErrorOccurred_ protected
Definition at line 788 of file RtAudio.h.
Referenced by error(), and RtApi().
MAX_SAMPLE_RATES
const unsigned int RtApi::MAX_SAMPLE_RATES = 14 static protected
Definition at line 716 of file RtAudio.h.
SAMPLE_RATES
const unsigned int RtApi::SAMPLE_RATES static protected
Initial value:
= {
  4000, 5512, 8000, 9600, 11025, 16000, 22050,
  32000, 44100, 48000, 88200, 96000, 176400, 192000
}
Definition at line 717 of file RtAudio.h.
showWarnings_
bool RtApi::showWarnings_ protected
Definition at line 786 of file RtAudio.h.
Referenced by error(), and RtApi().
stream_
RtApiStream RtApi::stream_ protected
Definition at line 787 of file RtAudio.h.
Referenced by clearStreamInfo(), convertBuffer(), error(), getStreamLatency(), getStreamSampleRate(), getStreamTime(), openStream(), RtApi(), setConvertInfo(), setStreamTime(), tickStreamTime(), verifyStream(), and ~RtApi().
The documentation for this class was generated from the following files:
/home/topisani/dev/OTTO/boards/parts/audio/rtaudio/include/RtAudio.h
/home/topisani/dev/OTTO/boards/parts/audio/rtaudio/src/RtAudio.cpp