OTTO: otto::filesystem::path Class Reference
otto::filesystem::path Class Reference
#include <filesystem.hpp>
Classes
class iterator
Public Types
enum format { native_format, generic_format, auto_format }
using value_type = char
using string_type = std::basic_string< value_type >
using const_iterator = iterator
Public Member Functions
path () noexcept
path (const path &p)
path (path &&p) noexcept
path (const string_type &source, format fmt=auto_format)
path (string_type &&source, format fmt=auto_format)
path (std::basic_string_view< value_type > source, format fmt=auto_format)
path (const value_type *source, format fmt=auto_format)
template<class Source , typename >
path (const Source &source, format fmt=auto_format)
template<class InputIterator >
path (InputIterator first, InputIterator last, format fmt=auto_format)
~path ()
path & operator= (const path &p)
path & operator= (path &&p)
path & operator= (string_type &&source)
path & assign (string_type &&source)
template<class Source >
path & operator= (const Source &source)
template<class Source >
path & assign (const Source &source)
template<class InputIterator >
path & assign (InputIterator first, InputIterator last)
path & operator/= (const path &p)
template<class Source >
path & operator/= (const Source &source)
template<class Source >
path & append (const Source &source)
template<class InputIterator >
path & append (InputIterator first, InputIterator last)
path & operator+= (const path &x)
path & operator+= (const string_type &x)
path & operator+= (std::basic_string_view< value_type > x)
path & operator+= (const value_type *x)
path & operator+= (value_type x)
template<class Source >
path & operator+= (const Source &x)
template<class EcharT >
path & operator+= (EcharT x)
template<class Source >
path & concat (const Source &x)
template<class InputIterator >
path & concat (InputIterator first, InputIterator last)
void clear () noexcept
path & make_preferred ()
path & remove_filename ()
path & replace_filename (const path &replacement)
path & replace_extension (const path &replacement=path())
void swap (path &rhs) noexcept
const string_type & native () const noexcept
const value_type * c_str () const noexcept
operator string_type () const
std::string string () const
std::string generic_string () const
int compare (const path &p) const noexcept
int compare (const string_type &s) const
int compare (std::basic_string_view< value_type > s) const
int compare (const value_type *s) const
path root_name () const
path root_directory () const
path root_path () const
path relative_path () const
path parent_path () const
path filename () const
path stem () const
path extension () const
bool empty () const noexcept
bool has_root_name () const
bool has_root_directory () const
bool has_root_path () const
bool has_relative_path () const
bool has_parent_path () const
bool has_filename () const
bool has_stem () const
bool has_extension () const
bool is_absolute () const
bool is_relative () const
path lexically_normal () const
path lexically_relative (const path &base) const
path lexically_proximate (const path &base) const
iterator begin () const
iterator end () const
Static Public Attributes
static constexpr value_type preferred_separator = '/'
Protected Attributes
format _format
std::string _path
Detailed Description
Definition at line 21 of file filesystem.hpp.
Member Typedef Documentation
const_iterator
using otto::filesystem::path::const_iterator = iterator
Definition at line 183 of file filesystem.hpp.
string_type
using otto::filesystem::path::string_type = std::basic_string<value_type>
Definition at line 25 of file filesystem.hpp.
value_type
using otto::filesystem::path::value_type = char
Definition at line 23 of file filesystem.hpp.
Member Enumeration Documentation
format
enum otto::filesystem::path::format
Enumerator
native_format
generic_format
auto_format
Definition at line 29 of file filesystem.hpp.
 { native_format, generic_format, auto_format };
Constructor & Destructor Documentation
path() [1/9]
otto::filesystem::path::path () noexcept
Definition at line 248 of file filesystem.cpp.
Referenced by append(), compare(), concat(), extension(), filename(), otto::filesystem::path::iterator::operator*(), operator+=(), operator/=(), relative_path(), root_directory(), and root_name().
 {}
path() [2/9]
otto::filesystem::path::path (const path & p) default
path() [3/9]
otto::filesystem::path::path (path && p) noexcept
Definition at line 252 of file filesystem.cpp.
                               : _format(p._format), _path(std::move(p._path))
   {}
path() [4/9]
otto::filesystem::path::path (const string_type & source, format fmt = auto_format)
Definition at line 260 of file filesystem.cpp.
     : _format(fmt),
       _path(source)
   {}
path() [5/9]
otto::filesystem::path::path (string_type && source, format fmt = auto_format)
Definition at line 255 of file filesystem.cpp.
     : _format(fmt),
       _path(std::move(source))
   {}
path() [6/9]
otto::filesystem::path::path (std::basic_string_view< value_type > source, format fmt = auto_format)
Definition at line 265 of file filesystem.cpp.
     : _format(fmt),
       _path(source)
   {}
path() [7/9]
otto::filesystem::path::path (const value_type * source, format fmt = auto_format)
Definition at line 270 of file filesystem.cpp.
     : _format(fmt),
        _path(source)
   {}
path() [8/9]
template<class Source , typename = std::enable_if_t< std::is_constructible_v<path::string_type, Source>>> otto::filesystem::path::path (const Source & source, format fmt = auto_format)
Definition at line 726 of file filesystem.hpp.
                                              : path(string_type(source), fmt)
   {}
path() [9/9]
template<class InputIterator > otto::filesystem::path::path (InputIterator first, InputIterator last, format fmt = auto_format)
Definition at line 731 of file filesystem.hpp.
     : path(string_type(first, last), fmt)
   {}
~path()
otto::filesystem::path::~path () default
Member Function Documentation
append() [1/2]
template<class Source > path & otto::filesystem::path::append (const Source & source)
Definition at line 761 of file filesystem.hpp.
References operator/=(), and path().
Referenced by replace_filename().
   {
     return operator/=(path(source));
   }
append() [2/2]
template<class InputIterator > path & otto::filesystem::path::append (InputIterator first, InputIterator last)
Definition at line 767 of file filesystem.hpp.
References operator/=(), and path().
   {
     return operator/=(path(first, last));
   }
assign() [1/3]
path & otto::filesystem::path::assign (string_type && source)
Definition at line 289 of file filesystem.cpp.
References _format, _path, and otto::filesystem::px::detect_format().
Referenced by assign(), operator/=(), and operator=().
   {
     _format = px::detect_format(source);
     _path   = std::move(source);
     return *this;
   }
assign() [2/3]
template<class Source > path & otto::filesystem::path::assign (const Source & source)
Definition at line 742 of file filesystem.hpp.
References assign().
   {
     return assign(string_type(source));
   }
assign() [3/3]
template<class InputIterator > path & otto::filesystem::path::assign (InputIterator first, InputIterator last)
Definition at line 749 of file filesystem.hpp.
References assign().
   {
     return assign(string_type{first, last});
   }
begin()
path::iterator otto::filesystem::path::begin () const
Definition at line 596 of file filesystem.cpp.
References _path.
   {
     return {_path.data(), _path.data()};
   }
c_str()
const path::value_type * otto::filesystem::path::c_str () const noexcept
Definition at line 409 of file filesystem.cpp.
References _path.
Referenced by otto::service::logger::init(), otto::util::JsonFile::read(), otto::util::SoundFile::read_file(), and otto::util::JsonFile::write().
   {
     return _path.c_str();
   }
clear()
void otto::filesystem::path::clear () noexcept
Definition at line 345 of file filesystem.cpp.
References _path.
Referenced by otto::filesystem::canonical(), and otto::filesystem::current_path().
   {
     _path.clear();
   }
compare() [1/4]
int otto::filesystem::path::compare (const path & p) const noexcept
Definition at line 433 of file filesystem.cpp.
Referenced by compare().
   {
     return native() < p.native();
   }
compare() [2/4]
int otto::filesystem::path::compare (const string_type & s) const
Definition at line 438 of file filesystem.cpp.
References compare(), and path().
   {
     return compare(path(s));
   }
compare() [3/4]
int otto::filesystem::path::compare (std::basic_string_view< value_type > s) const
Definition at line 443 of file filesystem.cpp.
References compare(), and path().
   {
     return compare(path(s));
   }
compare() [4/4]
int otto::filesystem::path::compare (const value_type * s) const
Definition at line 448 of file filesystem.cpp.
References compare(), and path().
   {
     return compare(path(s));
   }
concat() [1/2]
template<class Source > path & otto::filesystem::path::concat (const Source & x)
Definition at line 787 of file filesystem.hpp.
References _path, native(), and path().
Referenced by replace_extension().
   {
     _path.append(path(x).native());
     return *this;
   }
concat() [2/2]
template<class InputIterator > path & otto::filesystem::path::concat (InputIterator first, InputIterator last)
Definition at line 794 of file filesystem.hpp.
References path().
   {
     return *this += path(first, last);
   }
empty()
bool otto::filesystem::path::empty () const noexcept
Definition at line 520 of file filesystem.cpp.
References _path.
Referenced by has_extension(), and replace_extension().
   {
     return _path.empty();
   }
end()
path::iterator otto::filesystem::path::end () const
Definition at line 601 of file filesystem.cpp.
References _path.
Referenced by filename().
   {
     return {_path.data(), _path.end().base()};
   }
extension()
path otto::filesystem::path::extension () const
Definition at line 511 of file filesystem.cpp.
References filename(), generic_string(), path(), and stem().
Referenced by has_extension().
   {
     auto v = StringView{filename().generic_string()};
     v.remove_prefix(stem().generic_string().length());
     return path(v);
   }
filename()
path otto::filesystem::path::filename () const
Definition at line 494 of file filesystem.cpp.
References end(), has_relative_path(), and path().
Referenced by extension(), and stem().
   {
     return has_relative_path() ? *--end() : path();
   }
generic_string()
std::string otto::filesystem::path::generic_string () const
Definition at line 426 of file filesystem.cpp.
References _path.
Referenced by extension().
   {
     return _path;
   }
has_extension()
bool otto::filesystem::path::has_extension () const
Definition at line 562 of file filesystem.cpp.
References empty(), and extension().
   {
     return !extension().empty();
   }
has_filename()
bool otto::filesystem::path::has_filename () const
Definition at line 552 of file filesystem.cpp.
References _path, and otto::filesystem::px::is_separator().
Referenced by has_stem(), operator/=(), remove_filename(), and replace_extension().
   {
     return !_path.empty() && !px::is_separator(_path.back());
   }
has_parent_path()
bool otto::filesystem::path::has_parent_path () const
Definition at line 547 of file filesystem.cpp.
References _path, and otto::filesystem::px::separators.
   {
     return _path.find_first_of(px::separators) != _path.npos;
   }
has_relative_path()
bool otto::filesystem::path::has_relative_path () const
Definition at line 542 of file filesystem.cpp.
References _path, and otto::filesystem::px::separators.
Referenced by filename(), and parent_path().
   {
     return _path.find_first_not_of(px::separators) != _path.npos;
   }
has_root_directory()
bool otto::filesystem::path::has_root_directory () const
Definition at line 531 of file filesystem.cpp.
Referenced by has_root_path().
   {
     // TODO: Real implementation
     return false;
   }
has_root_name()
bool otto::filesystem::path::has_root_name () const
Definition at line 525 of file filesystem.cpp.
Referenced by has_root_path().
   {
     // TODO: Real implementation
     return false;
   }
has_root_path()
bool otto::filesystem::path::has_root_path () const
Definition at line 537 of file filesystem.cpp.
References has_root_directory(), and has_root_name().
   {
     return has_root_name() || has_root_directory();
   }
has_stem()
bool otto::filesystem::path::has_stem () const
Definition at line 557 of file filesystem.cpp.
References has_filename().
   {
     return has_filename();
   }
is_absolute()
bool otto::filesystem::path::is_absolute () const
Definition at line 567 of file filesystem.cpp.
References _path, and otto::filesystem::px::is_separator().
Referenced by is_relative(), and relative_path().
   {
     return !_path.empty() && px::is_separator(_path.front());
   }
is_relative()
bool otto::filesystem::path::is_relative () const
Definition at line 572 of file filesystem.cpp.
References is_absolute().
   {
     return !is_absolute();
   }
lexically_normal()
path otto::filesystem::path::lexically_normal () const
Definition at line 578 of file filesystem.cpp.
   {
     // TODO: Implement
     return *this;
   }
lexically_proximate()
path otto::filesystem::path::lexically_proximate (const path & base) const
Definition at line 590 of file filesystem.cpp.
   {
     // TODO: Implement
     return *this;
   }
lexically_relative()
path otto::filesystem::path::lexically_relative (const path & base) const
Definition at line 584 of file filesystem.cpp.
   {
     // TODO: Implement
     return *this;
   }
make_preferred()
path & otto::filesystem::path::make_preferred ()
Definition at line 350 of file filesystem.cpp.
Referenced by remove_filename(), and replace_extension().
   {
     // Nothing to do on posix
     return *this;
   }
native()
const path::string_type & otto::filesystem::path::native () const noexcept
Definition at line 404 of file filesystem.cpp.
References _path.
Referenced by concat(), operator+=(), and string().
   {
     return _path;
   }
operator string_type()
otto::filesystem::path::operator string_type () const
Definition at line 414 of file filesystem.cpp.
   {
     return native();
   }
operator+=() [1/7]
path & otto::filesystem::path::operator+= (const path & x)
Definition at line 314 of file filesystem.cpp.
References _path.
   {
     _path.append(x.native());
     return *this;
   }
operator+=() [2/7]
path & otto::filesystem::path::operator+= (const string_type & x)
Definition at line 320 of file filesystem.cpp.
References _path, native(), and path().
   {
     _path.append(path(x).native());
     return *this;
   }
operator+=() [3/7]
path & otto::filesystem::path::operator+= (std::basic_string_view< value_type > x)
Definition at line 326 of file filesystem.cpp.
References _path.
   {
     _path.append(x);
     return *this;
   }
operator+=() [4/7]
path & otto::filesystem::path::operator+= (const value_type * x)
Definition at line 332 of file filesystem.cpp.
References _path.
   {
     _path.append(x);
     return *this;
   }
operator+=() [5/7]
path & otto::filesystem::path::operator+= (value_type x)
Definition at line 338 of file filesystem.cpp.
References _path.
   {
     _path.push_back(x);
     return *this;
   }
operator+=() [6/7]
template<class Source > path & otto::filesystem::path::operator+= (const Source & x)
Definition at line 773 of file filesystem.hpp.
References _path, native(), and path().
   {
     _path.append(path(x).native());
     return *this;
   }
operator+=() [7/7]
template<class EcharT > path & otto::filesystem::path::operator+= (EcharT x)
Definition at line 780 of file filesystem.hpp.
References _path, native(), and path().
   {
     _path.append(path(x).native());
     return *this;
   }
operator/=() [1/2]
path & otto::filesystem::path::operator/= (const path & p)
Definition at line 299 of file filesystem.cpp.
References _path, assign(), has_filename(), preferred_separator, and root_name().
Referenced by append(), and operator/=().
   {
     if (p.is_absolute() ||
         (p.has_root_name() && p.root_name() != root_name())) {
       assign(p);
     } else {
       if (has_filename()) {
         _path.push_back(preferred_separator);
       }
       _path.append(p);
     }
     return *this;
   }
operator/=() [2/2]
template<class Source > path & otto::filesystem::path::operator/= (const Source & source)
Definition at line 755 of file filesystem.hpp.
References operator/=(), and path().
   {
     return operator/=(path(source));
   }
operator=() [1/4]
path & otto::filesystem::path::operator= (const path & p) default
operator=() [2/4]
path & otto::filesystem::path::operator= (path && p) default
operator=() [3/4]
path & otto::filesystem::path::operator= (string_type && source)
Definition at line 283 of file filesystem.cpp.
References assign().
   {
     assign(std::move(source));
     return *this;
   }
operator=() [4/4]
template<class Source > path & otto::filesystem::path::operator= (const Source & source)
Definition at line 736 of file filesystem.hpp.
References assign().
   {
     return assign(source);
   }
parent_path()
path otto::filesystem::path::parent_path () const
Definition at line 481 of file filesystem.cpp.
References _path, and has_relative_path().
   {
     if (!has_relative_path()) {
       return *this;
     }
     path res{_path};
     while (!res.has_filename()) {
       res._path.resize(res._path.size() - 1);
     }
     res.remove_filename();
     return res;
   }
relative_path()
path otto::filesystem::path::relative_path () const
Definition at line 472 of file filesystem.cpp.
References _path, is_absolute(), and path().
   {
     // TODO: Real implementation
     if (is_absolute()) {
       return {_path.begin() + 1, _path.end()};
     }
     return path();
   }
remove_filename()
path & otto::filesystem::path::remove_filename ()
Definition at line 356 of file filesystem.cpp.
References _path, has_filename(), make_preferred(), and otto::filesystem::px::separators.
Referenced by replace_filename(), and otto::util::JsonFile::write().
   {
     make_preferred();
     if (has_filename()) {
       auto pos = _path.find_last_of(px::separators);
       _path.resize(pos + 1);
     }
     return *this;
   }
replace_extension()
path & otto::filesystem::path::replace_extension (const path & replacement = path())
Definition at line 373 of file filesystem.cpp.
References _path, concat(), empty(), otto::filesystem::exists(), has_filename(), make_preferred(), and otto::filesystem::px::separators.
   {
     make_preferred();
     if (has_filename()) {
       // Remove extension
       auto sep = _path.find_last_of(px::separators);
       auto dot = _path.find_last_of(".");
       if (dot > sep || sep == _path.npos) {
         if (dot != _path.npos) {
           _path.resize(dot);
         }
       }
       // Add extension
       if (!(replacement.empty() || replacement._path.front() == '.')) {
         concat(".");
       }
       concat(replacement);
       exists(replacement);
     }
     return *this;
   }
replace_filename()
path & otto::filesystem::path::replace_filename (const path & replacement)
Definition at line 366 of file filesystem.cpp.
References append(), and remove_filename().
   {
     remove_filename();
     append(replacement);
     return *this;
   }
root_directory()
path otto::filesystem::path::root_directory () const
Definition at line 461 of file filesystem.cpp.
References path().
Referenced by root_path().
   {
     // TODO: implement this;
     return path();
   }
root_name()
path otto::filesystem::path::root_name () const
Definition at line 455 of file filesystem.cpp.
References path().
Referenced by operator/=(), and root_path().
   {
     // TODO: implement this;
     return path();
   }
root_path()
path otto::filesystem::path::root_path () const
Definition at line 467 of file filesystem.cpp.
References root_directory(), and root_name().
   {
     return root_name() / root_directory();
   }
stem()
path otto::filesystem::path::stem () const
Definition at line 499 of file filesystem.cpp.
References filename().
Referenced by extension().
   {
     path f = filename();
     auto v = StringView{f.generic_string()};
     v.remove_prefix(1);
     auto dot = v.find_last_of('.');
     if (v != "." && dot != v.npos) {
       f._path.resize(dot + 1);
     }
     return f;
   }
string()
std::string otto::filesystem::path::string () const
Definition at line 419 of file filesystem.cpp.
References native().
   {
     return {native()};
   }
swap()
void otto::filesystem::path::swap (path & rhs) noexcept
Definition at line 395 of file filesystem.cpp.
References otto::filesystem::swap().
   {
     using std::swap;
     swap(_format, rhs._format);
     swap(_path, rhs._path);
   }
Member Data Documentation
_format
format otto::filesystem::path::_format protected
Definition at line 188 of file filesystem.hpp.
Referenced by assign().
_path
std::string otto::filesystem::path::_path protected
Definition at line 189 of file filesystem.hpp.
Referenced by assign(), begin(), c_str(), clear(), concat(), empty(), end(), generic_string(), has_filename(), has_parent_path(), has_relative_path(), is_absolute(), native(), operator+=(), operator/=(), parent_path(), relative_path(), remove_filename(), and replace_extension().
preferred_separator
constexpr value_type otto::filesystem::path::preferred_separator = '/' static
Definition at line 24 of file filesystem.hpp.
Referenced by operator/=().
The documentation for this class was generated from the following files:
/home/topisani/dev/OTTO/src/util/filesystem.hpp
/home/topisani/dev/OTTO/src/util/filesystem.cpp