OTTO: Env_lite< N, Tv, Tp, Td > Class Template Reference
Env_lite< N, Tv, Tp, Td > Class Template Reference
Detailed Description
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver>
class Env_lite< N, Tv, Tp, Td >
Envelope with a fixed number of exponential segments and a sustain point.
The envelope consists of N exponential curve 'segments' and N+1 break-point levels. The curvature and length of each segment and the break-point levels can be controlled independently. This class can be used to construct many specialized envelopes such as an AD (Attack Decay), an ADSR (Attack Decay Sustain Release), and an ADSHR (Attack Decay Sustain Hold Release). The number of envelope segments is fixed to ensure better memory locality.
Template Parameters
N number of segments
Tv value (sample) type
Tp parameter type
Definition at line 20 of file ADSR_lite.hpp.
#include <ADSR_lite.hpp>
Public Member Functions
Env_lite (float(*voice)(void))
Env_lite (Tp lvl1, Tp len1, Tp lvl2, float(*voice)(void))
Env_lite (Tp lvl1, Tp len1, Tp lvl2, Tp len2, Tp lvl3, float(*voice)(void))
Env_lite (Tp lvl1, Tp len1, Tp lvl2, Tp len2, Tp lvl3, Tp len3, Tp lvl4, float(*voice)(void))
int size () const
Get the number of segments.
unsigned position () const
Get the position, in samples, within the current segment.
int sustainPoint () const
Get the sustain break-point.
int stage () const
Get the envelope's current segment.
Tv value () const
Get the current envelope value.
bool done () const
Returns whether the envelope is done.
bool released () const
Returns whether the envelope is released.
bool sustained () const
Returns whether the envelope is currently sustained.
Tv operator() ()
Generate next value.
void release ()
Release the envelope.
Env_lite & loop (bool v)
Set whether envelope loops.
Env_lite & sustainPoint (int v)
Sets the point at which the envelope holds its value until released.
Env_lite & sustainDisable ()
Disable sustain.
void reset ()
Reset envelope to starting point.
void resetSoft ()
Reset envelope to starting point setting first level to current level.
void finish ()
Jump to end of envelope.
Tp * lengths ()
Get segment lengths array.
const Tp * lengths () const
template<class V >
Env_lite & lengths (const V *vals, int len)
Set break-point values.
Env_lite & lengths (Tp a, Tp b)
Set first two segment lengths.
Env_lite & lengths (Tp a, Tp b, Tp c)
Set first three segment lengths.
Env_lite & lengths (Tp a, Tp b, Tp c, Tp d)
Set first four segment lengths.
Env_lite & lengths (Tp a, Tp b, Tp c, Tp d, Tp e)
Set first five segment lengths.
Tp totalLength () const
Get total length of all envelope segments.
Env_lite & totalLength (Tp length, int modSegment)
Set total length of envelope by adjusting one segment length.
Env_lite & totalLength (Tp length)
Set total length of envelope by scaling all segment lengths.
Tp * curves ()
Get segment curvature array.
const Tp * curves () const
Env_lite & curve (Tp v)
Set curvature of all segments.
template<class V >
Env_lite & curves (const V *vals, int len)
Set segment curve amounts.
Env_lite & curves (Tp ca, Tp cb)
Set curvature of first two segments.
Env_lite & curves (Tp ca, Tp cb, Tp cc)
Set curvature of first three segments.
Env_lite & curves (Tp ca, Tp cb, Tp cc, Tp cd)
Set curvature of first four segments.
Env_lite & segment (int i, Tp len, Tp crv)
Set length and curvature of a segment.
template<class V >
Env_lite & segments (const V *lens, const V *crvs, int len, int begin=0)
Set length and curvature of many segments.
Env_lite & segments (Tp la, Tp ca, Tp lb, Tp cb)
Set length and curvature of first two segments.
Env_lite & segments (Tp la, Tp ca, Tp lb, Tp cb, Tp lc, Tp cc)
Set length and curvature of first three segments.
Env_lite & segments (Tp la, Tp ca, Tp lb, Tp cb, Tp lc, Tp cc, Tp ld, Tp cd)
Set length and curvature of first four segments.
Tv * levels ()
Get break-point levels array.
const Tv * levels () const
template<class V >
Env_lite & levels (const V *vals, int len)
Set break-point values.
Env_lite & levels (Tv a, Tv b)
Set first two break-point levels.
Env_lite & levels (Tv a, Tv b, Tv c)
Set first three break-point levels.
Env_lite & levels (Tv a, Tv b, Tv c, Tv d)
Set first four break-point levels.
Env_lite & levels (Tv a, Tv b, Tv c, Tv d, Tv e)
Set first five break-point levels.
Env_lite & maxLevel (Tv v)
Set maximum level.
Env_lite & setVoice (float(*voice)(void))
Set function pointer.
Protected Member Functions
void setLen (int i)
Protected Attributes
gam::Curve< Tv, Tp > mCurve
Tp mLengths [N]
Tp mCurves [N]
Tv mLevels [N+1]
unsigned mPos
unsigned mLen
int mStage
int mSustain
int mLoop
float(* voice_)(void)
Constructor & Destructor Documentation
Env_lite() [1/4]
template<int N, class Tv , class Tp , class Td > Env_lite< N, Tv, Tp, Td >::Env_lite (float(*)(void) voice)
Definition at line 238 of file ADSR_lite.hpp.
Env_lite() [2/4]
template<int N, class Tv , class Tp, class Td > Env_lite< N, Tv, Tp, Td >::Env_lite (Tp lvl1, Tp len1, Tp lvl2, float(*)(void) voice)
Definition at line 250 of file ADSR_lite.hpp.
Env_lite() [3/4]
template<int N, class Tv , class Tp, class Td > Env_lite< N, Tv, Tp, Td >::Env_lite (Tp lvl1, Tp len1, Tp lvl2, Tp len2, Tp lvl3, float(*)(void) voice)
Definition at line 260 of file ADSR_lite.hpp.
Env_lite() [4/4]
template<int N, class Tv , class Tp, class Td > Env_lite< N, Tv, Tp, Td >::Env_lite (Tp lvl1, Tp len1, Tp lvl2, Tp len2, Tp lvl3, Tp len3, Tp lvl4, float(*)(void) voice)
Definition at line 270 of file ADSR_lite.hpp.
Member Function Documentation
size()
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> int Env_lite< N, Tv, Tp, Td >::size () const
Get the number of segments.
Definition at line 33 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::curves(), Env_lite< 3, Tv, Tp, Td >::done(), Env_lite< 3, Tv, Tp, Td >::lengths(), Env_lite< 3, Tv, Tp, Td >::levels(), and Env_lite< 3, Tv, Tp, Td >::segments().
position()
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> unsigned Env_lite< N, Tv, Tp, Td >::position () const
Get the position, in samples, within the current segment.
Definition at line 36 of file ADSR_lite.hpp.
sustainPoint() [1/2]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> int Env_lite< N, Tv, Tp, Td >::sustainPoint () const
Get the sustain break-point.
Definition at line 39 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::sustainDisable().
stage()
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> int Env_lite< N, Tv, Tp, Td >::stage () const
Get the envelope's current segment.
Definition at line 42 of file ADSR_lite.hpp.
value()
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tv Env_lite< N, Tv, Tp, Td >::value () const
Get the current envelope value.
Definition at line 45 of file ADSR_lite.hpp.
done()
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> bool Env_lite< N, Tv, Tp, Td >::done () const
Returns whether the envelope is done.
Definition at line 48 of file ADSR_lite.hpp.
released()
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> bool Env_lite< N, Tv, Tp, Td >::released () const
Returns whether the envelope is released.
Definition at line 51 of file ADSR_lite.hpp.
sustained()
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> bool Env_lite< N, Tv, Tp, Td >::sustained () const
Returns whether the envelope is currently sustained.
Definition at line 54 of file ADSR_lite.hpp.
operator()()
template<int N, class Tv , class Tp , class Td > Tv Env_lite< N, Tv, Tp, Td >::operator() ()
Generate next value.
Definition at line 280 of file ADSR_lite.hpp.
release()
template<int N, class Tv , class Tp , class Td > void Env_lite< N, Tv, Tp, Td >::release ()
Release the envelope.
Definition at line 315 of file ADSR_lite.hpp.
loop()
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Env_lite& Env_lite< N, Tv, Tp, Td >::loop (bool v)
Set whether envelope loops.
Note that when this is activated the last segment moves from the second to last level to the first level. Thus, the very last level is ignored. This is done to avoid clicking due to mismatched levels when the envelope wraps around.
Definition at line 70 of file ADSR_lite.hpp.
sustainPoint() [2/2]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Env_lite& Env_lite< N, Tv, Tp, Td >::sustainPoint (int v)
Sets the point at which the envelope holds its value until released.
Definition at line 73 of file ADSR_lite.hpp.
sustainDisable()
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Env_lite& Env_lite< N, Tv, Tp, Td >::sustainDisable ()
Disable sustain.
Definition at line 76 of file ADSR_lite.hpp.
reset()
template<int N, class Tv , class Tp , class Td > void Env_lite< N, Tv, Tp, Td >::reset ()
Reset envelope to starting point.
Definition at line 332 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::Env_lite().
resetSoft()
template<int N, class Tv , class Tp , class Td > void Env_lite< N, Tv, Tp, Td >::resetSoft ()
Reset envelope to starting point setting first level to current level.
Definition at line 341 of file ADSR_lite.hpp.
finish()
template<int N, class Tv , class Tp , class Td > void Env_lite< N, Tv, Tp, Td >::finish ()
Jump to end of envelope.
Definition at line 351 of file ADSR_lite.hpp.
lengths() [1/7]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tp* Env_lite< N, Tv, Tp, Td >::lengths ()
Get segment lengths array.
Definition at line 89 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::Env_lite(), and Env_lite< 3, Tv, Tp, Td >::lengths().
lengths() [2/7]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> const Tp* Env_lite< N, Tv, Tp, Td >::lengths () const
Definition at line 90 of file ADSR_lite.hpp.
lengths() [3/7]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> template<class V > Env_lite& Env_lite< N, Tv, Tp, Td >::lengths (const V * vals, int len)
Set break-point values.
Definition at line 94 of file ADSR_lite.hpp.
lengths() [4/7]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Env_lite& Env_lite< N, Tv, Tp, Td >::lengths (Tp a, Tp b)
Set first two segment lengths.
Definition at line 101 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::lengths().
lengths() [5/7]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Env_lite& Env_lite< N, Tv, Tp, Td >::lengths (Tp a, Tp b, Tp c)
Set first three segment lengths.
Definition at line 104 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::lengths().
lengths() [6/7]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Env_lite& Env_lite< N, Tv, Tp, Td >::lengths (Tp a, Tp b, Tp c, Tp d)
Set first four segment lengths.
Definition at line 107 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::lengths().
lengths() [7/7]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Env_lite& Env_lite< N, Tv, Tp, Td >::lengths (Tp a, Tp b, Tp c, Tp d, Tp e)
Set first five segment lengths.
Definition at line 110 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::lengths().
totalLength() [1/3]
template<int N, class Tv , class Tp , class Td > Tp Env_lite< N, Tv, Tp, Td >::totalLength () const
Get total length of all envelope segments.
Definition at line 358 of file ADSR_lite.hpp.
totalLength() [2/3]
template<int N, class Tv , class Tp, class Td > Env_lite< N, Tv, Tp, Td > & Env_lite< N, Tv, Tp, Td >::totalLength (Tp length, int modSegment)
Set total length of envelope by adjusting one segment length.
Parameters
[in] length desired length
[in] modSegment segment whose length is modified to match desired length
Definition at line 365 of file ADSR_lite.hpp.
totalLength() [3/3]
template<int N, class Tv , class Tp, class Td > Env_lite< N, Tv, Tp, Td > & Env_lite< N, Tv, Tp, Td >::totalLength (Tp length)
Set total length of envelope by scaling all segment lengths.
Definition at line 372 of file ADSR_lite.hpp.
curves() [1/6]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tp* Env_lite< N, Tv, Tp, Td >::curves ()
Get segment curvature array.
Definition at line 126 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::curve(), and Env_lite< 3, Tv, Tp, Td >::curves().
curves() [2/6]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> const Tp* Env_lite< N, Tv, Tp, Td >::curves () const
Definition at line 127 of file ADSR_lite.hpp.
curve()
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Env_lite& Env_lite< N, Tv, Tp, Td >::curve (Tp v)
Set curvature of all segments.
Definition at line 130 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::Env_lite().
curves() [3/6]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> template<class V > Env_lite& Env_lite< N, Tv, Tp, Td >::curves (const V * vals, int len)
Set segment curve amounts.
Definition at line 137 of file ADSR_lite.hpp.
curves() [4/6]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Env_lite& Env_lite< N, Tv, Tp, Td >::curves (Tp ca, Tp cb)
Set curvature of first two segments.
Definition at line 144 of file ADSR_lite.hpp.
curves() [5/6]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Env_lite& Env_lite< N, Tv, Tp, Td >::curves (Tp ca, Tp cb, Tp cc)
Set curvature of first three segments.
Definition at line 148 of file ADSR_lite.hpp.
curves() [6/6]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Env_lite& Env_lite< N, Tv, Tp, Td >::curves (Tp ca, Tp cb, Tp cc, Tp cd)
Set curvature of first four segments.
Definition at line 152 of file ADSR_lite.hpp.
segment()
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Env_lite& Env_lite< N, Tv, Tp, Td >::segment (int i, Tp len, Tp crv)
Set length and curvature of a segment.
Definition at line 157 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::segments().
segments() [1/4]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> template<class V > Env_lite& Env_lite< N, Tv, Tp, Td >::segments (const V * lens, const V * crvs, int len, int begin = 0)
Set length and curvature of many segments.
Definition at line 165 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::segments().
segments() [2/4]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Env_lite& Env_lite< N, Tv, Tp, Td >::segments (Tp la, Tp ca, Tp lb, Tp cb)
Set length and curvature of first two segments.
Definition at line 175 of file ADSR_lite.hpp.
segments() [3/4]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Env_lite& Env_lite< N, Tv, Tp, Td >::segments (Tp la, Tp ca, Tp lb, Tp cb, Tp lc, Tp cc)
Set length and curvature of first three segments.
Definition at line 179 of file ADSR_lite.hpp.
segments() [4/4]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Env_lite& Env_lite< N, Tv, Tp, Td >::segments (Tp la, Tp ca, Tp lb, Tp cb, Tp lc, Tp cc, Tp ld, Tp cd)
Set length and curvature of first four segments.
Definition at line 183 of file ADSR_lite.hpp.
levels() [1/7]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tv* Env_lite< N, Tv, Tp, Td >::levels ()
Get break-point levels array.
Definition at line 188 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::Env_lite(), and Env_lite< 3, Tv, Tp, Td >::levels().
levels() [2/7]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> const Tv* Env_lite< N, Tv, Tp, Td >::levels () const
Definition at line 189 of file ADSR_lite.hpp.
levels() [3/7]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> template<class V > Env_lite& Env_lite< N, Tv, Tp, Td >::levels (const V * vals, int len)
Set break-point values.
Definition at line 193 of file ADSR_lite.hpp.
levels() [4/7]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Env_lite& Env_lite< N, Tv, Tp, Td >::levels (Tv a, Tv b)
Set first two break-point levels.
Definition at line 200 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::levels().
levels() [5/7]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Env_lite& Env_lite< N, Tv, Tp, Td >::levels (Tv a, Tv b, Tv c)
Set first three break-point levels.
Definition at line 203 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::levels().
levels() [6/7]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Env_lite& Env_lite< N, Tv, Tp, Td >::levels (Tv a, Tv b, Tv c, Tv d)
Set first four break-point levels.
Definition at line 206 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::levels().
levels() [7/7]
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Env_lite& Env_lite< N, Tv, Tp, Td >::levels (Tv a, Tv b, Tv c, Tv d, Tv e)
Set first five break-point levels.
Definition at line 209 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::levels().
maxLevel()
template<int N, class Tv, class Tp , class Td > Env_lite< N, Tv, Tp, Td > & Env_lite< N, Tv, Tp, Td >::maxLevel (Tv v)
Set maximum level.
Definition at line 381 of file ADSR_lite.hpp.
setVoice()
template<int N, class Tv , class Tp , class Td > Env_lite< N, Tv, Tp, Td > & Env_lite< N, Tv, Tp, Td >::setVoice (float(*)(void) voice)
Set function pointer.
Definition at line 390 of file ADSR_lite.hpp.
setLen()
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> void Env_lite< N, Tv, Tp, Td >::setLen (int i) protected
Definition at line 228 of file ADSR_lite.hpp.
Member Data Documentation
mCurve
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> gam::Curve<Tv,Tp> Env_lite< N, Tv, Tp, Td >::mCurve protected
Definition at line 218 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::value().
mLengths
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tp Env_lite< N, Tv, Tp, Td >::mLengths[N] protected
Definition at line 219 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::Env_lite(), Env_lite< 3, Tv, Tp, Td >::lengths(), Env_lite< 3, Tv, Tp, Td >::segment(), and Env_lite< 3, Tv, Tp, Td >::setLen().
mCurves
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tp Env_lite< N, Tv, Tp, Td >::mCurves[N] protected
Definition at line 220 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::curves(), Env_lite< 3, Tv, Tp, Td >::Env_lite(), and Env_lite< 3, Tv, Tp, Td >::segment().
mLevels
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tv Env_lite< N, Tv, Tp, Td >::mLevels[N+1] protected
Definition at line 221 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::Env_lite(), and Env_lite< 3, Tv, Tp, Td >::levels().
mPos
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> unsigned Env_lite< N, Tv, Tp, Td >::mPos protected
Definition at line 223 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::position().
mLen
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> unsigned Env_lite< N, Tv, Tp, Td >::mLen protected
Definition at line 223 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::setLen().
mStage
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> int Env_lite< N, Tv, Tp, Td >::mStage protected
Definition at line 224 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::done(), Env_lite< 3, Tv, Tp, Td >::stage(), and Env_lite< 3, Tv, Tp, Td >::sustained().
mSustain
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> int Env_lite< N, Tv, Tp, Td >::mSustain protected
Definition at line 225 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::released(), Env_lite< 3, Tv, Tp, Td >::sustained(), and Env_lite< 3, Tv, Tp, Td >::sustainPoint().
mLoop
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> int Env_lite< N, Tv, Tp, Td >::mLoop protected
Definition at line 226 of file ADSR_lite.hpp.
Referenced by Env_lite< 3, Tv, Tp, Td >::loop().
voice_
template<int N, class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> float(* Env_lite< N, Tv, Tp, Td >::voice_) (void) protected
Definition at line 230 of file ADSR_lite.hpp.
The documentation for this class was generated from the following file:
/home/travis/build/topisani/OTTO/src/util/dsp/ADSR_lite.hpp