OTTO: otto::util::iterator::float_step_iterator< I, V > Class Template Reference
otto::util::iterator::float_step_iterator< I, V > Class Template Reference
Detailed Description
template<typename I, typename V = typename detail::value_type<I>::type>
class otto::util::iterator::float_step_iterator< I, V >
An iterator wrapper to iterate with a non-integer ratio
This iterates through contiguous data, or simply increments an integer value, with floating point steps. It keeps track of the error, and corrects it while iterating.
The most common use case is iterating over data at a non-integer rate ratio. In the OTTO it is used to read sound samples at a different rate than how they were recorded.
When used to iterator through data, it is preferred to use first < last as the loop condition, as opposed to the conventional first != last. The need for doing this depends on the relationship between the first and last iterators. If one was created from the other, using <operator+> or operator-, they are guarantied to be reachable from the other using operator++ or operator-- as applicable, as long as the step member variable on the mutating iterator is unchanged.
It has the same iterator category as the wrapped iteratory, except for random access iterators, which will be wrapped as bidirectional iterators. This is because a lot of the random access optimizations dont really apply to this.
Template Parameters
I Any iterator that will be wrapped.
V The value type.
Definition at line 422 of file iterator.hpp.
#include <iterator.hpp>
Public Types
using wrapped_type = I
using value_type = V
using reference = typename std::iterator_traits< wrapped_type >::reference
using pointer = typename std::iterator_traits< wrapped_type >::pointer
using difference_type = typename std::iterator_traits< wrapped_type >::difference_type
using iterator_category = std::common_type_t< typename detail::iterator_category< I >::type, std::bidirectional_iterator_tag >
Public Member Functions
float_step_iterator (const wrapped_type &iter, float step=1.f)
Construct an iterator, pointing to ptr
float_step_iterator (const float_step_iterator &r)
Copy constructor.
float_step_iterator (float_step_iterator &&r)
Move constructor.
float_step_iterator & operator= (const float_step_iterator &)=default
float_step_iterator & operator= (float_step_iterator &&)=default
decltype(auto) operator* ()
Dereference the iterator.
decltype(auto) operator* () const
bool operator== (const float_step_iterator &r) const
Compare equal.
bool operator!= (const float_step_iterator &r) const
Compare inequal.
auto operator< (const float_step_iterator &r) const -> decltype(std::declval< wrapped_type >()< std::declval< wrapped_type >())
Compare less than.
auto operator> (const float_step_iterator &r) const -> decltype(std::declval< wrapped_type >() > std::declval< wrapped_type >())
Compare greater than.
auto operator<= (const float_step_iterator &r) const -> decltype(std::declval< wrapped_type >()< std::declval< wrapped_type >())
Compare less than or equal to.
auto operator>= (const float_step_iterator &r) const -> decltype(std::declval< wrapped_type >() > std::declval< wrapped_type >())
Compare greater than or equal to.
std::ptrdiff_t operator- (const float_step_iterator &rhs) const
Get the number of iterations to get from rhs to this.
float_step_iterator & operator+= (difference_type n)
Increment this by n
float_step_iterator operator+ (difference_type d)
float_step_iterator & operator++ ()
Increment this by one.
float_step_iterator operator++ (int)
Increment this by one.
auto operator-= (difference_type n) -> std::enable_if_t< std::is_base_of_v< std::bidirectional_iterator_tag, iterator_category >, float_step_iterator & >
Decrement this by n
auto operator- (difference_type d) -> std::enable_if_t< std::is_base_of_v< std::bidirectional_iterator_tag, iterator_category >, float_step_iterator >
auto operator-- () -> std::enable_if_t< std::is_base_of_v< std::bidirectional_iterator_tag, iterator_category >, float_step_iterator & >
Decrement this by one.
auto operator-- (int) -> std::enable_if_t< std::is_base_of_v< std::bidirectional_iterator_tag, iterator_category >, float_step_iterator & >
Decrement this by one.
wrapped_type data () const
Get a copy of the underlying pointer.
float error () const
The inaccuracy of the element this iterator points to.
auto difference (const float_step_iterator &rhs) -> std::enable_if_t< std::is_same_v< typename std::iterator_traits< wrapped_type >::iterator_category, std::random_access_iterator_tag >, float >
The real numeric difference between this and rhs.
Public Attributes
float step = 1.f
The size of one step.
Member Typedef Documentation
wrapped_type
template<typename I , typename V = typename detail::value_type<I>::type> using otto::util::iterator::float_step_iterator< I, V >::wrapped_type = I
Definition at line 428 of file iterator.hpp.
value_type
template<typename I , typename V = typename detail::value_type<I>::type> using otto::util::iterator::float_step_iterator< I, V >::value_type = V
Definition at line 431 of file iterator.hpp.
reference
template<typename I , typename V = typename detail::value_type<I>::type> using otto::util::iterator::float_step_iterator< I, V >::reference = typename std::iterator_traits<wrapped_type>::reference
Definition at line 432 of file iterator.hpp.
pointer
template<typename I , typename V = typename detail::value_type<I>::type> using otto::util::iterator::float_step_iterator< I, V >::pointer = typename std::iterator_traits<wrapped_type>::pointer
Definition at line 433 of file iterator.hpp.
difference_type
template<typename I , typename V = typename detail::value_type<I>::type> using otto::util::iterator::float_step_iterator< I, V >::difference_type = typename std::iterator_traits<wrapped_type>::difference_type
Definition at line 434 of file iterator.hpp.
iterator_category
template<typename I , typename V = typename detail::value_type<I>::type> using otto::util::iterator::float_step_iterator< I, V >::iterator_category = std::common_type_t<typename detail::iterator_category<I>::type, std::bidirectional_iterator_tag>
Definition at line 436 of file iterator.hpp.
Constructor & Destructor Documentation
float_step_iterator() [1/3]
template<typename I , typename V = typename detail::value_type<I>::type> otto::util::iterator::float_step_iterator< I, V >::float_step_iterator (const wrapped_type & iter, float step = 1.f)
Construct an iterator, pointing to ptr
Definition at line 443 of file iterator.hpp.
References otto::util::iterator::float_step_iterator< I, V >::step.
float_step_iterator() [2/3]
template<typename I , typename V = typename detail::value_type<I>::type> otto::util::iterator::float_step_iterator< I, V >::float_step_iterator (const float_step_iterator< I, V > & r)
Copy constructor.
Definition at line 446 of file iterator.hpp.
float_step_iterator() [3/3]
template<typename I , typename V = typename detail::value_type<I>::type> otto::util::iterator::float_step_iterator< I, V >::float_step_iterator (float_step_iterator< I, V > && r)
Move constructor.
Definition at line 451 of file iterator.hpp.
References std::move().
Member Function Documentation
operator=() [1/2]
template<typename I , typename V = typename detail::value_type<I>::type> float_step_iterator& otto::util::iterator::float_step_iterator< I, V >::operator= (const float_step_iterator< I, V > &) default
operator=() [2/2]
template<typename I , typename V = typename detail::value_type<I>::type> float_step_iterator& otto::util::iterator::float_step_iterator< I, V >::operator= (float_step_iterator< I, V > &&) default
operator*() [1/2]
template<typename I , typename V = typename detail::value_type<I>::type> decltype(auto) otto::util::iterator::float_step_iterator< I, V >::operator* ()
Dereference the iterator.
Propagates to the dereference operator of <ptr>
Definition at line 464 of file iterator.hpp.
operator*() [2/2]
template<typename I , typename V = typename detail::value_type<I>::type> decltype(auto) otto::util::iterator::float_step_iterator< I, V >::operator* () const
Definition at line 468 of file iterator.hpp.
operator==()
template<typename I , typename V = typename detail::value_type<I>::type> bool otto::util::iterator::float_step_iterator< I, V >::operator== (const float_step_iterator< I, V > & r) const
Compare equal.
Requires members <ptr> and <_error> to be equal. Ignores <step>, as it has no effect on the dereferenced value.
Definition at line 477 of file iterator.hpp.
operator!=()
template<typename I , typename V = typename detail::value_type<I>::type> bool otto::util::iterator::float_step_iterator< I, V >::operator!= (const float_step_iterator< I, V > & r) const
Compare inequal.
Implemented as if by !(*this == r)
Definition at line 485 of file iterator.hpp.
operator<()
template<typename I , typename V = typename detail::value_type<I>::type> auto otto::util::iterator::float_step_iterator< I, V >::operator< (const float_step_iterator< I, V > & r) const -> decltype(std::declval<wrapped_type>() < std::declval<wrapped_type>())
Compare less than.
Only avaliable if wrapped_type is less than comparable to itself. If the two wrapped instances are equal, the error values are compared.
Definition at line 494 of file iterator.hpp.
operator>()
template<typename I , typename V = typename detail::value_type<I>::type> auto otto::util::iterator::float_step_iterator< I, V >::operator> (const float_step_iterator< I, V > & r) const -> decltype(std::declval<wrapped_type>() > std::declval<wrapped_type>())
Compare greater than.
Only avaliable if wrapped_type is greater than comparable to itself. If the two wrapped instances are equal, the error values are compared.
Definition at line 504 of file iterator.hpp.
operator<=()
template<typename I , typename V = typename detail::value_type<I>::type> auto otto::util::iterator::float_step_iterator< I, V >::operator<= (const float_step_iterator< I, V > & r) const -> decltype(std::declval<wrapped_type>() < std::declval<wrapped_type>())
Compare less than or equal to.
Only avaliable if wrapped_type is less than comparable to itself. If the two wrapped instances are equal, the error values are compared.
Definition at line 514 of file iterator.hpp.
operator>=()
template<typename I , typename V = typename detail::value_type<I>::type> auto otto::util::iterator::float_step_iterator< I, V >::operator>= (const float_step_iterator< I, V > & r) const -> decltype(std::declval<wrapped_type>() > std::declval<wrapped_type>())
Compare greater than or equal to.
Only avaliable if wrapped_type is greater than comparable to itself. If the two wrapped instances are equal, the error values are compared.
Definition at line 524 of file iterator.hpp.
operator-() [1/2]
template<typename I , typename V = typename detail::value_type<I>::type> std::ptrdiff_t otto::util::iterator::float_step_iterator< I, V >::operator- (const float_step_iterator< I, V > & rhs) const
Get the number of iterations to get from rhs to this.
Takes the error values into account.
Definition at line 533 of file iterator.hpp.
References otto::util::iterator::float_step_iterator< I, V >::step.
operator+=()
template<typename I , typename V = typename detail::value_type<I>::type> float_step_iterator& otto::util::iterator::float_step_iterator< I, V >::operator+= (difference_type n)
Increment this by n
\effects Advance the iterator by floor(error + n * speed), and store the remainder in error.
Returns
A reference to this
Definition at line 544 of file iterator.hpp.
References std::advance(), std::modf(), and otto::util::iterator::float_step_iterator< I, V >::step.
operator+()
template<typename I , typename V = typename detail::value_type<I>::type> float_step_iterator otto::util::iterator::float_step_iterator< I, V >::operator+ (difference_type d)
Definition at line 556 of file iterator.hpp.
operator++() [1/2]
template<typename I , typename V = typename detail::value_type<I>::type> float_step_iterator& otto::util::iterator::float_step_iterator< I, V >::operator++ ()
Increment this by one.
\effects Same as *this += 1
Returns
A reference to this
Definition at line 567 of file iterator.hpp.
Referenced by otto::util::iterator::float_step_iterator< I, V >::operator++().
operator++() [2/2]
template<typename I , typename V = typename detail::value_type<I>::type> float_step_iterator otto::util::iterator::float_step_iterator< I, V >::operator++ (int)
Increment this by one.
\effects Same as *this += 1
Returns
A copy of this pre increment
Definition at line 577 of file iterator.hpp.
References otto::util::iterator::float_step_iterator< I, V >::operator++().
operator-=()
template<typename I , typename V = typename detail::value_type<I>::type> auto otto::util::iterator::float_step_iterator< I, V >::operator-= (difference_type n) -> std::enable_if_t<std::is_base_of_v<std::bidirectional_iterator_tag, iterator_category>, float_step_iterator&>
Decrement this by n
\effects Same as *this += -n
Returns
A reference to this \requires wrapped_type shall be at least a Bidirectional Iterator, or this function will not exist.
Definition at line 590 of file iterator.hpp.
operator-() [2/2]
template<typename I , typename V = typename detail::value_type<I>::type> auto otto::util::iterator::float_step_iterator< I, V >::operator- (difference_type d) -> std::enable_if_t<std::is_base_of_v<std::bidirectional_iterator_tag, iterator_category>, float_step_iterator>
Definition at line 597 of file iterator.hpp.
operator--() [1/2]
template<typename I , typename V = typename detail::value_type<I>::type> auto otto::util::iterator::float_step_iterator< I, V >::operator-- () -> std::enable_if_t<std::is_base_of_v<std::bidirectional_iterator_tag, iterator_category>, float_step_iterator&>
Decrement this by one.
\effects Same as *this += -1
Returns
A reference to this \requires wrapped_type shall be at least a Bidirectional Iterator, or this function will not exist.
Definition at line 613 of file iterator.hpp.
operator--() [2/2]
template<typename I , typename V = typename detail::value_type<I>::type> auto otto::util::iterator::float_step_iterator< I, V >::operator-- (int) -> std::enable_if_t<std::is_base_of_v<std::bidirectional_iterator_tag, iterator_category>, float_step_iterator&>
Decrement this by one.
\effects Same as *this += -1
Returns
A copy of this pre increment \requires wrapped_type shall be at least a Bidirectional Iterator, or this function will not exist.
Definition at line 626 of file iterator.hpp.
data()
template<typename I , typename V = typename detail::value_type<I>::type> wrapped_type otto::util::iterator::float_step_iterator< I, V >::data () const
Get a copy of the underlying pointer.
Definition at line 638 of file iterator.hpp.
error()
template<typename I , typename V = typename detail::value_type<I>::type> float otto::util::iterator::float_step_iterator< I, V >::error () const
The inaccuracy of the element this iterator points to.
While <step> is an integer, this value will be constant. Otherwise it is in the range [0, 1), signifying the fractional part of the real index. I.e. ptr + error() == real_index.
Definition at line 649 of file iterator.hpp.
Referenced by otto::util::iterator::float_step_iterator< I, V >::difference().
difference()
template<typename I , typename V = typename detail::value_type<I>::type> auto otto::util::iterator::float_step_iterator< I, V >::difference (const float_step_iterator< I, V > & rhs) -> std::enable_if_t< std::is_same_v<typename std::iterator_traits<wrapped_type>::iterator_category, std::random_access_iterator_tag>, float>
The real numeric difference between this and rhs.
Only avaliable if wrapped_type is random access.
Definition at line 657 of file iterator.hpp.
References otto::util::iterator::float_step_iterator< I, V >::error().
Member Data Documentation
step
template<typename I , typename V = typename detail::value_type<I>::type> float otto::util::iterator::float_step_iterator< I, V >::step = 1.f
The size of one step.
When incrementing, <ptr> will be effectively be incremented by this value.
Changing this value does not invalidate any iterator, but be aware that an end iterator previously created using *this + n might no longer be reachable by incrementing this. If you need to change the iterator step while looping, prefer using iter < last over iter != last
Definition at line 679 of file iterator.hpp.
Referenced by otto::util::iterator::float_step_iterator< I, V >::float_step_iterator(), otto::util::iterator::float_step_iterator< I, V >::operator+=(), and otto::util::iterator::float_step_iterator< I, V >::operator-().
The documentation for this class was generated from the following file:
/home/travis/build/topisani/OTTO/src/util/iterator.hpp