OTTO: otto::util::ByteFile Class Reference
otto::util::ByteFile Class Reference
TODO: Documentation.
#include <bytefile.hpp>
Classes
struct Chunk
struct Error
Public Types
using Position = int
using Path = filesystem::path
Public Member Functions
ByteFile ()
ByteFile (const Path &)
ByteFile (ByteFile &)=delete
ByteFile (ByteFile &&)
virtual ~ByteFile ()
ByteFile & operator= (ByteFile)
void open (const Path &)
void close ()
void flush ()
bool is_open () const
virtual void create_file ()
virtual void read_file ()
virtual void write_file ()
Position seek (Position, std::ios::seekdir=std::ios::beg)
Position position ()
Position size ()
template<typename OutIter , typename = std::enable_if<is_iterator_v<OutIter, std::byte, std::output_iterator_tag>>>
result< void, OutIter > read_bytes (OutIter, OutIter)
template<typename OutIter , typename = std::enable_if<is_iterator_v<OutIter, std::byte, std::output_iterator_tag>>>
result< void, std::streampos > read_bytes (OutIter, int)
template<std::size_t N>
result< void, std::streampos > read_bytes (bytes< N > &)
template<typename InIter , typename = std::enable_if<is_iterator_v<InIter, std::byte, std::input_iterator_tag>>>
void write_bytes (InIter, InIter)
template<typename InIter , typename = std::enable_if<is_iterator_v<InIter, std::byte, std::input_iterator_tag>>>
void write_bytes (InIter, int)
template<std::size_t N>
void write_bytes (const bytes< N > &)
template<typename F >
auto for_chunks_in_range (Position, Position, F &&f) -> std::enable_if_t< util::is_invocable_v< F, Chunk &>, void >
Public Attributes
Path path
Protected Attributes
std::fstream fstream
Friends
void swap (ByteFile &, ByteFile &)
Detailed Description
TODO: Documentation.
Definition at line 100 of file bytefile.hpp.
Member Typedef Documentation
Path
using otto::util::ByteFile::Path = filesystem::path
Definition at line 137 of file bytefile.hpp.
Position
using otto::util::ByteFile::Position = int
Definition at line 136 of file bytefile.hpp.
Constructor & Destructor Documentation
ByteFile() [1/4]
otto::util::ByteFile::ByteFile ()
Definition at line 11 of file bytefile.cpp.
 {}
ByteFile() [2/4]
otto::util::ByteFile::ByteFile (const Path & p)
Definition at line 13 of file bytefile.cpp.
References open().
{
     open(p);
   }
ByteFile() [3/4]
otto::util::ByteFile::ByteFile (ByteFile &) delete
ByteFile() [4/4]
otto::util::ByteFile::ByteFile (ByteFile &&)
Definition at line 17 of file bytefile.cpp.
{
     // TODO: Do moves
   }
~ByteFile()
otto::util::ByteFile::~ByteFile () virtual
Definition at line 21 of file bytefile.cpp.
References close().
                       {
     close();
   }
Member Function Documentation
close()
void otto::util::ByteFile::close ()
Definition at line 48 of file bytefile.cpp.
References fstream, and write_file().
Referenced by create_file(), and ~ByteFile().
{
     if (fstream.is_open()) {
       write_file();
       fstream.close();
     };
   }
create_file()
void otto::util::ByteFile::create_file () virtual
Definition at line 62 of file bytefile.cpp.
References close(), fstream, path, and write_file().
Referenced by open(), and otto::util::SoundFile::read_file().
{
     close();
     fstream.open(path, std::ios::trunc | std::ios::out | std::ios::binary);
     fstream.close();
     fstream.open(path, std::ios::in | std::ios::out | std::ios::binary);
     write_file();
   }
flush()
void otto::util::ByteFile::flush ()
Definition at line 55 of file bytefile.cpp.
References fstream, and write_file().
{
     if (fstream.is_open()) {
       write_file();
       fstream.flush();
     };
   }
for_chunks_in_range()
template<typename F > auto otto::util::ByteFile::for_chunks_in_range (Position i, Position o, F && f) -> std::enable_if_t<util::is_invocable_v<F, Chunk&>, void>
Definition at line 342 of file bytefile.hpp.
References otto::util::ByteFile::Chunk::beginning(), otto::util::ByteFile::Chunk::past_end(), and otto::util::ByteFile::Chunk::read().
Referenced by otto::util::Header::read_fields().
{
     seek(i);
     if (o > size()) {
       o = size();
     }
     while (position() < o) {
       Chunk chunk;
       chunk.read(*this);
       seek(chunk.beginning());
       std::invoke(std::forward<F>(f), chunk);
       seek(chunk.past_end());
     }
   }
is_open()
bool otto::util::ByteFile::is_open () const
Definition at line 77 of file bytefile.cpp.
References fstream.
Referenced by open(), position(), read_bytes(), seek(), size(), and write_bytes().
{
     return fstream.is_open();
   }
open()
void otto::util::ByteFile::open (const Path & p)
Definition at line 35 of file bytefile.cpp.
References create_file(), fstream, is_open(), path, read_file(), and size().
Referenced by ByteFile().
{
     if (is_open()) {
       throw "File already open";
     }
     path = p;
     fstream.open(p.c_str(), std::ios::in | std::ios::out | std::ios::binary);
     if (!fstream || size() == 0) {
       // File didnt exist, create it
       create_file();
     }
     read_file();
   }
operator=()
ByteFile & otto::util::ByteFile::operator= (ByteFile other)
Definition at line 25 of file bytefile.cpp.
References swap.
{
     swap(*this, other);
     return *this;
   }
position()
ByteFile::Position otto::util::ByteFile::position ()
Definition at line 90 of file bytefile.cpp.
References otto::util::ByteFile::Error::ExceptionThrown, otto::util::ByteFile::Error::FileNotOpen, fstream, and is_open().
Referenced by otto::util::SoundFile::position(), otto::util::ByteFile::Chunk::read(), and otto::util::ByteFile::Chunk::write().
{
     if (!is_open()) throw Error(Error::Type::FileNotOpen, "ByteFile::position()");
     auto r = fstream.tellg();
     if (!fstream.good()) {
       fstream.clear();
       throw Error(Error::Type::ExceptionThrown,
         std::strerror(errno));
     }
     return r;
   }
read_bytes() [1/3]
template<typename OutIter , typename > result< void, OutIter > otto::util::ByteFile::read_bytes (OutIter f, OutIter l)
Definition at line 256 of file bytefile.hpp.
References otto::util::ByteFile::Error::FileNotOpen, fstream, and is_open().
Referenced by otto::util::ByteFile::Chunk::read(), otto::util::Header::read_fields(), otto::util::WAVE_fmt::read_fields(), and otto::util::SoundFile::read_samples().
{
     if (!is_open()) throw Error(Error::Type::FileNotOpen);
     result<void, OutIter> res {std::monostate()};
     // If OutIter is a pointer, copy everything at once
     if constexpr (std::is_pointer_v<OutIter>) {
       fstream.read((char*) f, l - f);
       if (fstream.eof()) {
         res = f + fstream.gcount() / sizeof(std::remove_pointer_t<OutIter>);
         fstream.clear();
       }
     } else {
       char* ptr;
       std::streamsize i = 0;
       for (OutIter iter = f; iter != l; iter++, i++) {
         fstream.read(ptr, 1);
         if (fstream.eof()) {
           res = iter;
           fstream.clear();
           break;
         }
         **iter = *ptr;
       }
     }
     return res;
   }
read_bytes() [2/3]
template<typename OutIter , typename > result< void, std::streampos > otto::util::ByteFile::read_bytes (OutIter iter, int n)
Definition at line 283 of file bytefile.hpp.
References otto::util::ByteFile::Error::FileNotOpen, fstream, and is_open().
{
     if (!is_open()) throw Error(Error::Type::FileNotOpen);
     // If OutIter is a pointer, copy everything at once
     if constexpr (std::is_pointer_v<OutIter>) {
         fstream.read((char*) iter, n);
       } else {
       char buf;
       std::generate_n(iter, n, [&] {
           fstream.read(&buf, 1);
           return std::byte(buf);
         });
     }
     if (fstream.eof()) {
       fstream.clear();
       return {fstream.tellg()};
     }
     return result<void, std::streampos>::Ok();
   }
read_bytes() [3/3]
template<std::size_t N> result< void, std::streampos > otto::util::ByteFile::read_bytes (bytes< N > & bs)
Definition at line 303 of file bytefile.hpp.
References fstream.
{
     fstream.read((char*)bs, N);
     if (fstream.eof()) {
       fstream.clear();
       return {fstream.tellg()};
     }
     return result<void, std::streampos>::Ok();
   }
read_file()
void otto::util::ByteFile::read_file () virtual
Reimplemented in otto::util::SoundFile.
Definition at line 70 of file bytefile.cpp.
References seek().
Referenced by open().
{
     seek(0);
   }
seek()
ByteFile::Position otto::util::ByteFile::seek (Position p, std::ios::seekdir d = std::ios::beg)
Definition at line 81 of file bytefile.cpp.
References otto::util::ByteFile::Error::FileNotOpen, fstream, and is_open().
Referenced by otto::util::SoundFile::read_file(), read_file(), otto::util::SoundFile::seek(), otto::util::ByteFile::Chunk::write(), otto::util::SoundFile::write_file(), and write_file().
{
     if (!is_open()) throw Error(Error::Type::FileNotOpen, "ByteFile::seek(p, d)");
     if (p < 0 && d == std::ios::beg) {
       p = 0;
     }
     fstream.seekg(p, d);
     return p;
   }
size()
ByteFile::Position otto::util::ByteFile::size ()
Definition at line 101 of file bytefile.cpp.
References otto::util::ByteFile::Error::FileNotOpen, fstream, and is_open().
Referenced by otto::util::SoundFile::length(), open(), and otto::util::SoundFile::write_file().
{
     if (!is_open()) throw Error(Error::Type::FileNotOpen, "ByteFile::size()");
     auto p = fstream.tellg();
     auto end = fstream.seekg(0, std::fstream::end).tellg();
     fstream.seekg(p);
     return Position(end);
   }
write_bytes() [1/3]
template<typename InIter , typename > void otto::util::ByteFile::write_bytes (InIter f, InIter l)
Definition at line 313 of file bytefile.hpp.
References otto::util::ByteFile::Error::FileNotOpen, fstream, and is_open().
Referenced by otto::util::ByteFile::Chunk::write(), otto::util::Header::write_fields(), otto::util::WAVE_fmt::write_fields(), and otto::util::SoundFile::write_samples().
{
     if (!is_open()) throw Error(Error::Type::FileNotOpen);
     // If InIter is a pointer, copy everything at once
     if constexpr (std::is_pointer_v<InIter>) {
         fstream.write((char*)f, l - f);
       } else {
       std::for_each(f, l, [&] (auto& b) {fstream.write((char*)&b, 1);});
     }
   }
write_bytes() [2/3]
template<typename InIter , typename > void otto::util::ByteFile::write_bytes (InIter iter, int n)
Definition at line 324 of file bytefile.hpp.
References otto::util::ByteFile::Error::FileNotOpen, fstream, and is_open().
{
     if (!is_open()) throw Error(Error::Type::FileNotOpen);
     // If InIter is a pointer, copy everything at once
     if constexpr (std::is_pointer_v<InIter>) {
         fstream.write((char*)iter, n);
       } else {
       for (int i = 0; i < n; i++, iter++) {
         fstream.write(reinterpret_cast<char*>(&(*iter)), 1);
       }
     }
   }
write_bytes() [3/3]
template<std::size_t N> void otto::util::ByteFile::write_bytes (const bytes< N > & bs)
Definition at line 337 of file bytefile.hpp.
References otto::util::bytes< len >::data, and fstream.
{
     fstream.write((char*)bs.data, N);
   }
write_file()
void otto::util::ByteFile::write_file () virtual
Reimplemented in otto::util::SoundFile.
Definition at line 73 of file bytefile.cpp.
References seek().
Referenced by close(), create_file(), and flush().
{
     seek(0);
   }
Friends And Related Function Documentation
swap
void swap (ByteFile & first, ByteFile & sec) friend
Definition at line 30 of file bytefile.cpp.
Referenced by operator=().
{
     using std::swap;
     // TODO: Do swaps;
   }
Member Data Documentation
fstream
std::fstream otto::util::ByteFile::fstream protected
Definition at line 248 of file bytefile.hpp.
Referenced by close(), create_file(), flush(), is_open(), open(), position(), read_bytes(), seek(), size(), write_bytes(), and otto::util::SoundFile::write_file().
path
Path otto::util::ByteFile::path
Definition at line 188 of file bytefile.hpp.
Referenced by create_file(), open(), otto::util::SoundFile::read_file(), and otto::util::SoundFile::write_file().
The documentation for this class was generated from the following files:
/home/topisani/dev/OTTO/src/util/bytefile.hpp
/home/topisani/dev/OTTO/src/util/bytefile.cpp