OTTO: otto::service::debug_ui::graph< N > Class Template Reference
otto::service::debug_ui::graph< N > Class Template Reference
Detailed Description
template<std::size_t N>
class otto::service::debug_ui::graph< N >
Definition at line 25 of file debug_ui.hpp.
#include <debug_ui.hpp>
Public Member Functions
void push (float val)
void plot (std::string name)
void plot (std::string name, float min, float max)
Member Function Documentation
template<std::size_t N> void otto::service::debug_ui::graph< N >::push (float val)
Definition at line 27 of file debug_ui.hpp.
References std::max(), std::min(), std::move(), and otto::util::ringbuffer< T, N >::push().
template<std::size_t N> void otto::service::debug_ui::graph< N >::plot (std::string name)
Definition at line 36 of file debug_ui.hpp.
template<std::size_t N> void otto::service::debug_ui::graph< N >::plot (std::string name, float min, float max)
Definition at line 43 of file debug_ui.hpp.
References std::string::c_str(), and otto::util::ringbuffer< T, N >::size().
The documentation for this class was generated from the following file:
/home/travis/build/topisani/OTTO/src/services/debug_ui.hpp