OTTO: BiquadSoftReset< Tv, Tp, Td > Class Template Reference
BiquadSoftReset< Tv, Tp, Td > Class Template Reference
Detailed Description
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver>
class BiquadSoftReset< Tv, Tp, Td >
2-pole/2-zero IIR filter with soft reset
The biquadratic filter contains 2 zeros and 2 poles in its transfer function. The zeros provide a better response near the DC and Nyquist frequencies than an all-pole filter would. Second-order IIRs have a 12 dB/octave cutoff slope and are normally cascaded (run in series) to obtain a sharper response. This particular implementation utilizes the RBJ Sallen-Key/Butterworth design from:
http://www.musicdsp.org/files/Audio-EQ-Cookbook.txt
Template Parameters
Tv Value (sample) type
Tp Parameter type
Td Domain observer type
Definition at line 51 of file BiquadSoftReset.hpp.
#include <BiquadSoftReset.hpp>
Public Member Functions
BiquadSoftReset (Tp frq=Tp(1000), Tp res=Tp(0.707), gam::FilterType type=gam::LOW_PASS)
Tp * a ()
Get array of 3 feedforward coefficients.
Tp * b ()
Get array of 3 feedback coefficients (first element, b0, is not used)
const Tp * a () const
const Tp * b () const
void coef (Tp a0, Tp a1, Tp a2, Tp b1, Tp b2)
Set feedforward (a) and feedback (b) coefficients directly.
void freq (Tp v)
Set center frequency.
void res (Tp v)
Set resonance (Q)
void level (Tp v)
Set level (PEAKING, LOW_SHELF, HIGH_SHELF types only)
void set (Tp frq, Tp res)
Set filter center frequency and resonance.
void set (Tp frq, Tp res, gam::FilterType type)
Set all filter params.
void type (gam::FilterType type)
Set type of filter.
void zero ()
Zero internal delays. Softly.
void smoothOutput ()
Manual smoothing of the output.
void smoothTime (Tp time)
Set smoothing time.
Tv operator() (Tv in)
Filter next sample.
Tv nextBP (Tv in)
Optimized for band-pass types.
Tp freq () const
Get center frequency.
Tp res () const
Get resonance (Q)
Tp level () const
Get level.
gam::FilterType type () const
Get filter type.
void onDomainChange (double r)
Protected Member Functions
void resRecip (Tp v)
Protected Attributes
Tp mA [3]
Tp mB [3]
Tv d1
Tv d2
Tp mFreq
Tp mResRecip
Tp mLevel
gam::FilterType mType
Tp mReal
Tp mImag
Tp mAlpha
Tp mBeta
Tp mFrqToRad
Tv o0 = 0
PanFromConstant< Tv, Td > smooth {0.004}
Constructor & Destructor Documentation
BiquadSoftReset()
template<class Tv , class Tp , class Td > BiquadSoftReset< Tv, Tp, Td >::BiquadSoftReset (Tp frq = Tp(1000), Tp res = Tp(0.707), gam::FilterType type = gam::LOW_PASS)
Parameters
[in] frq Center frequency
[in] res Resonance (Q) amount in [1, inf)
[in] type Type of filter
Definition at line 113 of file BiquadSoftReset.hpp.
References BiquadSoftReset< Tv, Tp, Td >::onDomainChange(), BiquadSoftReset< Tv, Tp, Td >::res(), BiquadSoftReset< Tv, Tp, Td >::set(), and BiquadSoftReset< Tv, Tp, Td >::type().
Member Function Documentation
a() [1/2]
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tp* BiquadSoftReset< Tv, Tp, Td >::a ()
Get array of 3 feedforward coefficients.
Definition at line 61 of file BiquadSoftReset.hpp.
References BiquadSoftReset< Tv, Tp, Td >::mA.
b() [1/2]
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tp* BiquadSoftReset< Tv, Tp, Td >::b ()
Get array of 3 feedback coefficients (first element, b0, is not used)
Definition at line 64 of file BiquadSoftReset.hpp.
References BiquadSoftReset< Tv, Tp, Td >::mB.
a() [2/2]
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> const Tp* BiquadSoftReset< Tv, Tp, Td >::a () const
Definition at line 66 of file BiquadSoftReset.hpp.
References BiquadSoftReset< Tv, Tp, Td >::mA.
b() [2/2]
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> const Tp* BiquadSoftReset< Tv, Tp, Td >::b () const
Definition at line 67 of file BiquadSoftReset.hpp.
References BiquadSoftReset< Tv, Tp, Td >::mB.
coef()
template<class Tv , class Tp , class Td > void BiquadSoftReset< Tv, Tp, Td >::coef (Tp a0, Tp a1, Tp a2, Tp b1, Tp b2)
Set feedforward (a) and feedback (b) coefficients directly.
Definition at line 165 of file BiquadSoftReset.hpp.
freq() [1/2]
template<class Tv , class Tp , class Td > void BiquadSoftReset< Tv, Tp, Td >::freq (Tp v)
Set center frequency.
Definition at line 170 of file BiquadSoftReset.hpp.
res() [1/2]
template<class Tv , class Tp , class Td > void BiquadSoftReset< Tv, Tp, Td >::res (Tp v)
Set resonance (Q)
Definition at line 214 of file BiquadSoftReset.hpp.
level() [1/2]
template<class Tv , class Tp , class Td > void BiquadSoftReset< Tv, Tp, Td >::level (Tp v)
Set level (PEAKING, LOW_SHELF, HIGH_SHELF types only)
Definition at line 179 of file BiquadSoftReset.hpp.
References std::pow().
set() [1/2]
template<class Tv , class Tp , class Td > void BiquadSoftReset< Tv, Tp, Td >::set (Tp frq, Tp res)
Set filter center frequency and resonance.
Definition at line 146 of file BiquadSoftReset.hpp.
Referenced by BiquadSoftReset< Tv, Tp, Td >::BiquadSoftReset().
set() [2/2]
template<class Tv , class Tp , class Td > void BiquadSoftReset< Tv, Tp, Td >::set (Tp frq, Tp res, gam::FilterType type)
Set all filter params.
Definition at line 139 of file BiquadSoftReset.hpp.
type() [1/2]
template<class Tv , class Tp , class Td > void BiquadSoftReset< Tv, Tp, Td >::type (gam::FilterType type)
Set type of filter.
Definition at line 219 of file BiquadSoftReset.hpp.
zero()
template<class Tv , class Tp , class Td > void BiquadSoftReset< Tv, Tp, Td >::zero ()
Zero internal delays. Softly.
Definition at line 149 of file BiquadSoftReset.hpp.
smoothOutput()
template<class Tv , class Tp , class Td > void BiquadSoftReset< Tv, Tp, Td >::smoothOutput ()
Manual smoothing of the output.
Definition at line 155 of file BiquadSoftReset.hpp.
smoothTime()
template<class Tv , class Tp , class Td > void BiquadSoftReset< Tv, Tp, Td >::smoothTime (Tp time)
Set smoothing time.
Definition at line 160 of file BiquadSoftReset.hpp.
operator()()
template<class Tv , class Tp , class Td > Tv BiquadSoftReset< Tv, Tp, Td >::operator() (Tv in)
Filter next sample.
Definition at line 287 of file BiquadSoftReset.hpp.
nextBP()
template<class Tv , class Tp , class Td > Tv BiquadSoftReset< Tv, Tp, Td >::nextBP (Tv in)
Optimized for band-pass types.
Definition at line 296 of file BiquadSoftReset.hpp.
freq() [2/2]
template<class Tv , class Tp , class Td > Tp BiquadSoftReset< Tv, Tp, Td >::freq () const
Get center frequency.
Definition at line 127 of file BiquadSoftReset.hpp.
res() [2/2]
template<class Tv , class Tp , class Td > Tp BiquadSoftReset< Tv, Tp, Td >::res () const
Get resonance (Q)
Definition at line 130 of file BiquadSoftReset.hpp.
Referenced by BiquadSoftReset< Tv, Tp, Td >::BiquadSoftReset().
level() [2/2]
template<class Tv , class Tp , class Td > Tp BiquadSoftReset< Tv, Tp, Td >::level () const
Get level.
Definition at line 133 of file BiquadSoftReset.hpp.
type() [2/2]
template<class Tv , class Tp , class Td > gam::FilterType BiquadSoftReset< Tv, Tp, Td >::type () const
Get filter type.
Definition at line 136 of file BiquadSoftReset.hpp.
Referenced by BiquadSoftReset< Tv, Tp, Td >::BiquadSoftReset().
onDomainChange()
template<class Tv , class Tp , class Td > void BiquadSoftReset< Tv, Tp, Td >::onDomainChange (double r)
Definition at line 121 of file BiquadSoftReset.hpp.
Referenced by BiquadSoftReset< Tv, Tp, Td >::BiquadSoftReset().
resRecip()
template<class Tv , class Tp , class Td > void BiquadSoftReset< Tv, Tp, Td >::resRecip (Tp v) protected
Definition at line 196 of file BiquadSoftReset.hpp.
Member Data Documentation
mA
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tp BiquadSoftReset< Tv, Tp, Td >::mA[3] protected
Definition at line 94 of file BiquadSoftReset.hpp.
Referenced by BiquadSoftReset< Tv, Tp, Td >::a().
mB
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tp BiquadSoftReset< Tv, Tp, Td >::mB[3] protected
Definition at line 95 of file BiquadSoftReset.hpp.
Referenced by BiquadSoftReset< Tv, Tp, Td >::b().
d1
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tv BiquadSoftReset< Tv, Tp, Td >::d1 protected
Definition at line 96 of file BiquadSoftReset.hpp.
d2
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tv BiquadSoftReset< Tv, Tp, Td >::d2 protected
Definition at line 96 of file BiquadSoftReset.hpp.
mFreq
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tp BiquadSoftReset< Tv, Tp, Td >::mFreq protected
Definition at line 97 of file BiquadSoftReset.hpp.
mResRecip
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tp BiquadSoftReset< Tv, Tp, Td >::mResRecip protected
Definition at line 97 of file BiquadSoftReset.hpp.
mLevel
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tp BiquadSoftReset< Tv, Tp, Td >::mLevel protected
Definition at line 98 of file BiquadSoftReset.hpp.
mType
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> gam::FilterType BiquadSoftReset< Tv, Tp, Td >::mType protected
Definition at line 99 of file BiquadSoftReset.hpp.
mReal
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tp BiquadSoftReset< Tv, Tp, Td >::mReal protected
Definition at line 100 of file BiquadSoftReset.hpp.
mImag
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tp BiquadSoftReset< Tv, Tp, Td >::mImag protected
Definition at line 100 of file BiquadSoftReset.hpp.
mAlpha
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tp BiquadSoftReset< Tv, Tp, Td >::mAlpha protected
Definition at line 101 of file BiquadSoftReset.hpp.
mBeta
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tp BiquadSoftReset< Tv, Tp, Td >::mBeta protected
Definition at line 101 of file BiquadSoftReset.hpp.
mFrqToRad
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tp BiquadSoftReset< Tv, Tp, Td >::mFrqToRad protected
Definition at line 102 of file BiquadSoftReset.hpp.
o0
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> Tv BiquadSoftReset< Tv, Tp, Td >::o0 = 0 protected
Definition at line 103 of file BiquadSoftReset.hpp.
smooth
template<class Tv = gam::real, class Tp = gam::real, class Td = gam::DomainObserver> PanFromConstant<Tv, Td> BiquadSoftReset< Tv, Tp, Td >::smooth {0.004} protected
Definition at line 104 of file BiquadSoftReset.hpp.
The documentation for this class was generated from the following file:
/home/travis/build/topisani/OTTO/src/util/dsp/BiquadSoftReset.hpp