OTTO: MidiInApi Class Reference
MidiInApi Class Reference
#include <RtMidi.h>
Classes
struct MidiMessage
struct MidiQueue
struct RtMidiInData
Public Member Functions
MidiInApi (unsigned int queueSizeLimit)
virtual ~MidiInApi (void)
void setCallback (RtMidiIn::RtMidiCallback callback, void *userData)
void cancelCallback (void)
virtual void ignoreTypes (bool midiSysex, bool midiTime, bool midiSense)
double getMessage (std::vector< unsigned char > *message)
Public Member Functions inherited from MidiApi
MidiApi ()
virtual ~MidiApi ()
virtual RtMidi::Api getCurrentApi (void)=0
virtual void openPort (unsigned int portNumber, const std::string &portName)=0
virtual void openVirtualPort (const std::string &portName)=0
virtual void closePort (void)=0
virtual void setClientName (const std::string &clientName)=0
virtual void setPortName (const std::string &portName)=0
virtual unsigned int getPortCount (void)=0
virtual std::string getPortName (unsigned int portNumber)=0
bool isPortOpen () const
void setErrorCallback (RtMidiErrorCallback errorCallback, void *userData)
void error (RtMidiError::Type type, std::string errorString)
A basic error reporting function for RtMidi classes.
Protected Attributes
RtMidiInData inputData_
Protected Attributes inherited from MidiApi
void * apiData_
bool connected_
std::string errorString_
RtMidiErrorCallback errorCallback_
bool firstErrorOccurred_
void * errorCallbackUserData_
Additional Inherited Members
Protected Member Functions inherited from MidiApi
virtual void initialize (const std::string &clientName)=0
Detailed Description
Definition at line 507 of file RtMidi.h.
Constructor & Destructor Documentation
MidiInApi()
MidiInApi::MidiInApi (unsigned int queueSizeLimit)
Definition at line 512 of file RtMidi.cpp.
References inputData_, MidiInApi::RtMidiInData::queue, MidiInApi::MidiQueue::ring, and MidiInApi::MidiQueue::ringSize.
   : MidiApi()
 {
   // Allocate the MIDI queue.
   inputData_.queue.ringSize = queueSizeLimit;
   if ( inputData_.queue.ringSize > 0 )
     inputData_.queue.ring = new MidiMessage[ inputData_.queue.ringSize ];
 }
~MidiInApi()
MidiInApi::~MidiInApi (void) virtual
Definition at line 521 of file RtMidi.cpp.
References inputData_, MidiInApi::RtMidiInData::queue, MidiInApi::MidiQueue::ring, and MidiInApi::MidiQueue::ringSize.
 {
   // Delete the MIDI queue.
   if ( inputData_.queue.ringSize > 0 ) delete [] inputData_.queue.ring;
 }
Member Function Documentation
cancelCallback()
void MidiInApi::cancelCallback (void)
Definition at line 546 of file RtMidi.cpp.
References MidiApi::error(), MidiApi::errorString_, inputData_, MidiInApi::RtMidiInData::userCallback, MidiInApi::RtMidiInData::userData, MidiInApi::RtMidiInData::usingCallback, and RtMidiError::WARNING.
 {
   if ( !inputData_.usingCallback ) {
     errorString_ = "RtMidiIn::cancelCallback: no callback function was set!";
     error( RtMidiError::WARNING, errorString_ );
     return;
   }
   inputData_.userCallback = 0;
   inputData_.userData = 0;
   inputData_.usingCallback = false;
 }
getMessage()
double MidiInApi::getMessage (std::vector< unsigned char > * message)
Definition at line 567 of file RtMidi.cpp.
References MidiApi::error(), MidiApi::errorString_, inputData_, MidiInApi::MidiQueue::pop(), MidiInApi::RtMidiInData::queue, MidiInApi::RtMidiInData::usingCallback, and RtMidiError::WARNING.
 {
   message->clear();
   if ( inputData_.usingCallback ) {
     errorString_ = "RtMidiIn::getNextMessage: a user callback is currently set for this port.";
     error( RtMidiError::WARNING, errorString_ );
     return 0.0;
   }
   double timeStamp;
   if (!inputData_.queue.pop(message, &timeStamp))
     return 0.0;
   return timeStamp;
 }
ignoreTypes()
void MidiInApi::ignoreTypes (bool midiSysex, bool midiTime, bool midiSense) virtual
Definition at line 559 of file RtMidi.cpp.
References MidiInApi::RtMidiInData::ignoreFlags, and inputData_.
 {
   inputData_.ignoreFlags = 0;
   if ( midiSysex ) inputData_.ignoreFlags = 0x01;
   if ( midiTime ) inputData_.ignoreFlags |= 0x02;
   if ( midiSense ) inputData_.ignoreFlags |= 0x04;
 }
setCallback()
void MidiInApi::setCallback (RtMidiIn::RtMidiCallback callback, void * userData)
Definition at line 527 of file RtMidi.cpp.
References MidiApi::error(), MidiApi::errorString_, inputData_, MidiInApi::RtMidiInData::userCallback, MidiInApi::RtMidiInData::userData, MidiInApi::RtMidiInData::usingCallback, and RtMidiError::WARNING.
 {
   if ( inputData_.usingCallback ) {
     errorString_ = "MidiInApi::setCallback: a callback function is already set!";
     error( RtMidiError::WARNING, errorString_ );
     return;
   }
   if ( !callback ) {
     errorString_ = "RtMidiIn::setCallback: callback function value is invalid!";
     error( RtMidiError::WARNING, errorString_ );
     return;
   }
   inputData_.userCallback = callback;
   inputData_.userData = userData;
   inputData_.usingCallback = true;
 }
Member Data Documentation
inputData_
RtMidiInData MidiInApi::inputData_ protected
Definition at line 568 of file RtMidi.h.
Referenced by cancelCallback(), getMessage(), ignoreTypes(), MidiInApi(), setCallback(), and ~MidiInApi().
The documentation for this class was generated from the following files:
/home/topisani/dev/OTTO/boards/parts/audio/rtaudio/include/RtMidi.h
/home/topisani/dev/OTTO/boards/parts/audio/rtaudio/src/RtMidi.cpp