OTTO: RtAudio Class Reference
RtAudio Class Reference
Realtime audio i/o C++ classes.
#include <RtAudio.h>
Classes
struct DeviceInfo
The public device information structure for returning queried values.
struct StreamOptions
The structure for specifying stream options.
struct StreamParameters
The structure for specifying input or ouput stream parameters.
Public Types
enum Api {
UNSPECIFIED, LINUX_ALSA, LINUX_PULSE, LINUX_OSS,
UNIX_JACK, MACOSX_CORE, WINDOWS_WASAPI, WINDOWS_ASIO,
WINDOWS_DS, RTAUDIO_DUMMY
}
Audio API specifier arguments.
Public Member Functions
RtAudio (RtAudio::Api api=UNSPECIFIED)
The class constructor.
~RtAudio ()
The destructor.
RtAudio::Api getCurrentApi (void)
Returns the audio API specifier for the current instance of RtAudio.
unsigned int getDeviceCount (void)
A public function that queries for the number of audio devices available.
RtAudio::DeviceInfo getDeviceInfo (unsigned int device)
Return an RtAudio::DeviceInfo structure for a specified device number.
unsigned int getDefaultOutputDevice (void)
A function that returns the index of the default output device.
unsigned int getDefaultInputDevice (void)
A function that returns the index of the default input device.
void openStream (RtAudio::StreamParameters *outputParameters, RtAudio::StreamParameters *inputParameters, RtAudioFormat format, unsigned int sampleRate, unsigned int *bufferFrames, RtAudioCallback callback, void *userData=NULL, RtAudio::StreamOptions *options=NULL, RtAudioErrorCallback errorCallback=NULL)
A public function for opening a stream with the specified parameters.
void closeStream (void)
A function that closes a stream and frees any associated stream memory.
void startStream (void)
A function that starts a stream.
void stopStream (void)
Stop a stream, allowing any samples remaining in the output queue to be played.
void abortStream (void)
Stop a stream, discarding any samples remaining in the input/output queue.
bool isStreamOpen (void) const
Returns true if a stream is open and false if not.
bool isStreamRunning (void) const
Returns true if the stream is running and false if it is stopped or not open.
double getStreamTime (void)
Returns the number of elapsed seconds since the stream was started.
void setStreamTime (double time)
Set the stream time to a time in seconds greater than or equal to 0.0.
long getStreamLatency (void)
Returns the internal stream latency in sample frames.
unsigned int getStreamSampleRate (void)
Returns actual sample rate in use by the stream.
void showWarnings (bool value=true)
Specify whether warning messages should be printed to stderr.
Static Public Member Functions
static std::string getVersion (void)
A static function to determine the current RtAudio version.
static void getCompiledApi (std::vector< RtAudio::Api > &apis)
A static function to determine the available compiled audio APIs.
Protected Member Functions
void openRtApi (RtAudio::Api api)
Protected Attributes
RtApi * rtapi_
Detailed Description
Realtime audio i/o C++ classes.
RtAudio provides a common API (Application Programming Interface) for realtime audio input/output across Linux (native ALSA, Jack, and OSS), Macintosh OS X (CoreAudio and Jack), and Windows (DirectSound, ASIO and WASAPI) operating systems.
RtAudio WWW site: http://www.music.mcgill.ca/~gary/rtaudio/
RtAudio: realtime audio i/o C++ classes Copyright (c) 2001-2017 Gary P. Scavone
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
Any person wishing to distribute modifications to the Software is asked to send the modifications to the original developer so that they can be incorporated into the canonical version. This is, however, not a binding provision of this license.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 273 of file RtAudio.h.
Member Enumeration Documentation
Api
enum RtAudio::Api
Audio API specifier arguments.
Enumerator
UNSPECIFIED
Search for a working compiled API.
LINUX_ALSA
The Advanced Linux Sound Architecture API.
LINUX_PULSE
The Linux PulseAudio API.
LINUX_OSS
The Linux Open Sound System API.
UNIX_JACK
The Jack Low-Latency Audio Server API.
MACOSX_CORE
Macintosh OS-X Core Audio API.
WINDOWS_WASAPI
The Microsoft WASAPI API.
WINDOWS_ASIO
The Steinberg Audio Stream I/O API.
WINDOWS_DS
The Microsoft Direct Sound API.
RTAUDIO_DUMMY
A compilable but non-functional API.
Definition at line 278 of file RtAudio.h.
            {
     UNSPECIFIED,
     LINUX_ALSA,
     LINUX_PULSE,
     LINUX_OSS,
     UNIX_JACK,
     MACOSX_CORE,
     WINDOWS_WASAPI,
     WINDOWS_ASIO,
     WINDOWS_DS,
     RTAUDIO_DUMMY
   };
Constructor & Destructor Documentation
RtAudio()
RtAudio::RtAudio (RtAudio::Api api = UNSPECIFIED)
The class constructor.
The constructor performs minor initialization tasks. An exception can be thrown if no API support is compiled.
If no API argument is specified and multiple API support has been compiled, the default order of use is JACK, ALSA, OSS (Linux systems) and ASIO, DS (Windows systems).
Definition at line 180 of file RtAudio.cpp.
References getCompiledApi(), RtApi::getDeviceCount(), openRtApi(), rtapi_, RtAudioError::UNSPECIFIED, and UNSPECIFIED.
 {
   rtapi_ = 0;
   if ( api != UNSPECIFIED ) {
     // Attempt to open the specified API.
     openRtApi( api );
     if ( rtapi_ ) return;
     // No compiled support for specified API value.  Issue a debug
     // warning and continue as if no API was specified.
     std::cerr << "\nRtAudio: no compiled support for specified API argument!\n" << std::endl;
   }
   // Iterate through the compiled APIs and return as soon as we find
   // one with at least one device or we reach the end of the list.
   std::vector< RtAudio::Api > apis;
   getCompiledApi( apis );
   for ( unsigned int i=0; i<apis.size(); i++ ) {
     openRtApi( apis[i] );
     if ( rtapi_ && rtapi_->getDeviceCount() ) break;
   }
   if ( rtapi_ ) return;
   // It should not be possible to get here because the preprocessor
   // definition __RTAUDIO_DUMMY__ is automatically defined if no
   // API-specific definitions are passed to the compiler. But just in
   // case something weird happens, we'll thow an error.
   std::string errorText = "\nRtAudio: no compiled API support found ... critical error!!\n\n";
   throw( RtAudioError( errorText, RtAudioError::UNSPECIFIED ) );
 }
~RtAudio()
RtAudio::~RtAudio ()
The destructor.
If a stream is running or open, it will be stopped and closed automatically.
Definition at line 213 of file RtAudio.cpp.
References rtapi_.
 {
   if ( rtapi_ )
     delete rtapi_;
 }
Member Function Documentation
abortStream()
void RtAudio::abortStream (void) inline
Stop a stream, discarding any samples remaining in the input/output queue.
An RtAudioError (type = SYSTEM_ERROR) is thrown if an error occurs during processing. An RtAudioError (type = INVALID_USE) is thrown if a stream is not open. A warning is issued if the stream is already stopped.
Definition at line 847 of file RtAudio.h.
References RtApi::abortStream(), and rtapi_.
 { return rtapi_->abortStream(); }
closeStream()
void RtAudio::closeStream (void) inline
A function that closes a stream and frees any associated stream memory.
If a stream is not open, this function issues a warning and returns (no exception is thrown).
Definition at line 844 of file RtAudio.h.
References RtApi::closeStream(), and rtapi_.
Referenced by otto::service::audio::RTAudioDriver::shutdown().
 { return rtapi_->closeStream(); }
getCompiledApi()
void RtAudio::getCompiledApi (std::vector< RtAudio::Api > & apis) static
A static function to determine the available compiled audio APIs.
The values returned in the std::vector can be compared against the enumerated list values. Note that there can be more than one API compiled for certain operating systems.
Definition at line 101 of file RtAudio.cpp.
References LINUX_ALSA, LINUX_OSS, LINUX_PULSE, MACOSX_CORE, RTAUDIO_DUMMY, UNIX_JACK, WINDOWS_ASIO, WINDOWS_DS, and WINDOWS_WASAPI.
Referenced by RtAudio().
 {
   apis.clear();
   // The order here will control the order of RtAudio's API search in
   // the constructor.
 #if defined(__UNIX_JACK__)
   apis.push_back( UNIX_JACK );
 #endif
 #if defined(__LINUX_PULSE__)
   apis.push_back( LINUX_PULSE );
 #endif
 #if defined(__LINUX_ALSA__)
   apis.push_back( LINUX_ALSA );
 #endif
 #if defined(__LINUX_OSS__)
   apis.push_back( LINUX_OSS );
 #endif
 #if defined(__WINDOWS_ASIO__)
   apis.push_back( WINDOWS_ASIO );
 #endif
 #if defined(__WINDOWS_WASAPI__)
   apis.push_back( WINDOWS_WASAPI );
 #endif
 #if defined(__WINDOWS_DS__)
   apis.push_back( WINDOWS_DS );
 #endif
 #if defined(__MACOSX_CORE__)
   apis.push_back( MACOSX_CORE );
 #endif
 #if defined(__RTAUDIO_DUMMY__)
   apis.push_back( RTAUDIO_DUMMY );
 #endif
 }
getCurrentApi()
RtAudio::Api RtAudio::getCurrentApi (void) inline
Returns the audio API specifier for the current instance of RtAudio.
Definition at line 839 of file RtAudio.h.
References RtApi::getCurrentApi(), and rtapi_.
 { return rtapi_->getCurrentApi(); }
getDefaultInputDevice()
unsigned int RtAudio::getDefaultInputDevice (void) inline
A function that returns the index of the default input device.
If the underlying audio API does not provide a "default device", or if no devices are available, the return value will be 0. Note that this is a valid device identifier and it is the client's responsibility to verify that a device is available before attempting to open a stream.
Definition at line 842 of file RtAudio.h.
References RtApi::getDefaultInputDevice(), and rtapi_.
 { return rtapi_->getDefaultInputDevice(); }
getDefaultOutputDevice()
unsigned int RtAudio::getDefaultOutputDevice (void) inline
A function that returns the index of the default output device.
If the underlying audio API does not provide a "default device", or if no devices are available, the return value will be 0. Note that this is a valid device identifier and it is the client's responsibility to verify that a device is available before attempting to open a stream.
Definition at line 843 of file RtAudio.h.
References RtApi::getDefaultOutputDevice(), and rtapi_.
 { return rtapi_->getDefaultOutputDevice(); }
getDeviceCount()
unsigned int RtAudio::getDeviceCount (void) inline
A public function that queries for the number of audio devices available.
This function performs a system query of available devices each time it is called, thus supporting devices connected after instantiation. If a system error occurs during processing, a warning will be issued.
Definition at line 840 of file RtAudio.h.
References RtApi::getDeviceCount(), and rtapi_.
 { return rtapi_->getDeviceCount(); }
getDeviceInfo()
RtAudio::DeviceInfo RtAudio::getDeviceInfo (unsigned int device) inline
Return an RtAudio::DeviceInfo structure for a specified device number.
Any device integer between 0 and getDeviceCount() - 1 is valid. If an invalid argument is provided, an RtAudioError (type = INVALID_USE) will be thrown. If a device is busy or otherwise unavailable, the structure member "probed" will have a value of "false" and all other members are undefined. If the specified device is the current default input or output device, the corresponding "isDefault" member will have a value of "true".
Definition at line 841 of file RtAudio.h.
References RtApi::getDeviceInfo(), and rtapi_.
 { return rtapi_->getDeviceInfo( device ); }
getStreamLatency()
long RtAudio::getStreamLatency (void) inline
Returns the internal stream latency in sample frames.
The stream latency refers to delay in audio input and/or output caused by internal buffering by the audio system and/or hardware. For duplex streams, the returned value will represent the sum of the input and output latencies. If a stream is not open, an RtAudioError (type = INVALID_USE) will be thrown. If the API does not report latency, the return value will be zero.
Definition at line 850 of file RtAudio.h.
References RtApi::getStreamLatency(), and rtapi_.
 { return rtapi_->getStreamLatency(); }
getStreamSampleRate()
unsigned int RtAudio::getStreamSampleRate (void) inline
Returns actual sample rate in use by the stream.
On some systems, the sample rate used may be slightly different than that specified in the stream parameters. If a stream is not open, an RtAudioError (type = INVALID_USE) will be thrown.
Definition at line 851 of file RtAudio.h.
References RtApi::getStreamSampleRate(), and rtapi_.
 { return rtapi_->getStreamSampleRate(); }
getStreamTime()
double RtAudio::getStreamTime (void) inline
Returns the number of elapsed seconds since the stream was started.
If a stream is not open, an RtAudioError (type = INVALID_USE) will be thrown.
Definition at line 852 of file RtAudio.h.
References RtApi::getStreamTime(), and rtapi_.
 { return rtapi_->getStreamTime(); }
getVersion()
std::string RtAudio::getVersion (void) static
A static function to determine the current RtAudio version.
Definition at line 96 of file RtAudio.cpp.
 {
   return RTAUDIO_VERSION;
 }
isStreamOpen()
bool RtAudio::isStreamOpen (void) const inline
Returns true if a stream is open and false if not.
Definition at line 848 of file RtAudio.h.
References RtApi::isStreamOpen(), and rtapi_.
Referenced by otto::service::audio::RTAudioDriver::shutdown().
 { return rtapi_->isStreamOpen(); }
isStreamRunning()
bool RtAudio::isStreamRunning (void) const inline
Returns true if the stream is running and false if it is stopped or not open.
Definition at line 849 of file RtAudio.h.
References RtApi::isStreamRunning(), and rtapi_.
 { return rtapi_->isStreamRunning(); }
openRtApi()
void RtAudio::openRtApi (RtAudio::Api api) protected
Definition at line 136 of file RtAudio.cpp.
References LINUX_ALSA, LINUX_OSS, LINUX_PULSE, MACOSX_CORE, rtapi_, RTAUDIO_DUMMY, UNIX_JACK, WINDOWS_ASIO, WINDOWS_DS, and WINDOWS_WASAPI.
Referenced by RtAudio().
 {
   if ( rtapi_ )
     delete rtapi_;
   rtapi_ = 0;
 #if defined(__UNIX_JACK__)
   if ( api == UNIX_JACK )
     rtapi_ = new RtApiJack();
 #endif
 #if defined(__LINUX_ALSA__)
   if ( api == LINUX_ALSA )
     rtapi_ = new RtApiAlsa();
 #endif
 #if defined(__LINUX_PULSE__)
   if ( api == LINUX_PULSE )
     rtapi_ = new RtApiPulse();
 #endif
 #if defined(__LINUX_OSS__)
   if ( api == LINUX_OSS )
     rtapi_ = new RtApiOss();
 #endif
 #if defined(__WINDOWS_ASIO__)
   if ( api == WINDOWS_ASIO )
     rtapi_ = new RtApiAsio();
 #endif
 #if defined(__WINDOWS_WASAPI__)
   if ( api == WINDOWS_WASAPI )
     rtapi_ = new RtApiWasapi();
 #endif
 #if defined(__WINDOWS_DS__)
   if ( api == WINDOWS_DS )
     rtapi_ = new RtApiDs();
 #endif
 #if defined(__MACOSX_CORE__)
   if ( api == MACOSX_CORE )
     rtapi_ = new RtApiCore();
 #endif
 #if defined(__RTAUDIO_DUMMY__)
   if ( api == RTAUDIO_DUMMY )
     rtapi_ = new RtApiDummy();
 #endif
 }
openStream()
void RtAudio::openStream (RtAudio::StreamParameters * outputParameters, RtAudio::StreamParameters * inputParameters, RtAudioFormat format, unsigned int sampleRate, unsigned int * bufferFrames, RtAudioCallback callback, void * userData = NULL, RtAudio::StreamOptions * options = NULL, RtAudioErrorCallback errorCallback = NULL)
A public function for opening a stream with the specified parameters.
An RtAudioError (type = SYSTEM_ERROR) is thrown if a stream cannot be opened with the specified parameters or an error occurs during processing. An RtAudioError (type = INVALID_USE) is thrown if any invalid device ID or channel number parameters are specified.
Parameters
outputParameters Specifies output stream parameters to use when opening a stream, including a device ID, number of channels, and starting channel number. For input-only streams, this argument should be NULL. The device ID is an index value between 0 and getDeviceCount() - 1.
inputParameters Specifies input stream parameters to use when opening a stream, including a device ID, number of channels, and starting channel number. For output-only streams, this argument should be NULL. The device ID is an index value between 0 and getDeviceCount() - 1.
format An RtAudioFormat specifying the desired sample data format.
sampleRate The desired sample rate (sample frames per second).
*bufferFrames A pointer to a value indicating the desired internal buffer size in sample frames. The actual value used by the device is returned via the same pointer. A value of zero can be specified, in which case the lowest allowable value is determined.
callback A client-defined function that will be invoked when input data is available and/or output data is needed.
userData An optional pointer to data that can be accessed from within the callback function.
options An optional pointer to a structure containing various global stream options, including a list of OR'ed RtAudioStreamFlags and a suggested number of stream buffers that can be used to control stream latency. More buffers typically result in more robust performance, though at a cost of greater latency. If a value of zero is specified, a system-specific median value is chosen. If the RTAUDIO_MINIMIZE_LATENCY flag bit is set, the lowest allowable value is used. The actual value used is returned via the structure argument. The parameter is API dependent.
errorCallback A client-defined function that will be invoked when an error has occured.
Definition at line 219 of file RtAudio.cpp.
References RtApi::openStream(), and rtapi_.
 {
   return rtapi_->openStream( outputParameters, inputParameters, format,
                              sampleRate, bufferFrames, callback,
                              userData, options, errorCallback );
 }
setStreamTime()
void RtAudio::setStreamTime (double time) inline
Set the stream time to a time in seconds greater than or equal to 0.0.
If a stream is not open, an RtAudioError (type = INVALID_USE) will be thrown.
Definition at line 853 of file RtAudio.h.
References rtapi_, and RtApi::setStreamTime().
 { return rtapi_->setStreamTime( time ); }
showWarnings()
void RtAudio::showWarnings (bool value = true) inline
Specify whether warning messages should be printed to stderr.
Definition at line 854 of file RtAudio.h.
References rtapi_, and RtApi::showWarnings().
 { rtapi_->showWarnings( value ); }
startStream()
void RtAudio::startStream (void) inline
A function that starts a stream.
An RtAudioError (type = SYSTEM_ERROR) is thrown if an error occurs during processing. An RtAudioError (type = INVALID_USE) is thrown if a stream is not open. A warning is issued if the stream is already running.
Definition at line 845 of file RtAudio.h.
References rtapi_, and RtApi::startStream().
 { return rtapi_->startStream(); }
stopStream()
void RtAudio::stopStream (void) inline
Stop a stream, allowing any samples remaining in the output queue to be played.
An RtAudioError (type = SYSTEM_ERROR) is thrown if an error occurs during processing. An RtAudioError (type = INVALID_USE) is thrown if a stream is not open. A warning is issued if the stream is already stopped.
Definition at line 846 of file RtAudio.h.
References rtapi_, and RtApi::stopStream().
 { return rtapi_->stopStream(); }
Member Data Documentation
rtapi_
RtApi* RtAudio::rtapi_ protected
Definition at line 585 of file RtAudio.h.
Referenced by abortStream(), closeStream(), getCurrentApi(), getDefaultInputDevice(), getDefaultOutputDevice(), getDeviceCount(), getDeviceInfo(), getStreamLatency(), getStreamSampleRate(), getStreamTime(), isStreamOpen(), isStreamRunning(), openRtApi(), openStream(), RtAudio(), setStreamTime(), showWarnings(), startStream(), stopStream(), and ~RtAudio().
The documentation for this class was generated from the following files:
/home/topisani/dev/OTTO/boards/parts/audio/rtaudio/include/RtAudio.h
/home/topisani/dev/OTTO/boards/parts/audio/rtaudio/src/RtAudio.cpp