OTTO: otto::util::dyn_array< T > Class Template Reference
otto::util::dyn_array< T > Class Template Reference
#include <dyn-array.hpp>
Public Member Functions
dyn_array (std::size_t size)
decltype(auto) operator[] (std::size_t i)
decltype(auto) operator[] (std::size_t i) const
T * begin ()
T * end ()
const T * begin () const
const T * end () const
T * data ()
const T * data () const
std::size_t size () const
void resize (std::size_t new_size)
void clear ()
Fill the array with default initialized values.
Detailed Description
template<typename T>
class otto::util::dyn_array< T >
Dynamic array
Default initialized. Cleared on resize.
Definition at line 16 of file dyn-array.hpp.
Constructor & Destructor Documentation
dyn_array()
template<typename T> otto::util::dyn_array< T >::dyn_array (std::size_t size) inline
Definition at line 21 of file dyn-array.hpp.
       : cur_size (size),
         _data (std::make_unique<T[]>(size))
     {
       clear();
     }
Member Function Documentation
begin() [1/2]
template<typename T> T* otto::util::dyn_array< T >::begin () inline
Definition at line 31 of file dyn-array.hpp.
Referenced by otto::util::dyn_array< double >::clear().
 { return _data.get(); }
begin() [2/2]
template<typename T> const T* otto::util::dyn_array< T >::begin () const inline
Definition at line 34 of file dyn-array.hpp.
 { return _data.get(); }
clear()
template<typename T> void otto::util::dyn_array< T >::clear () inline
Fill the array with default initialized values.
Definition at line 53 of file dyn-array.hpp.
Referenced by otto::util::dyn_array< double >::dyn_array(), and otto::util::dyn_array< double >::resize().
     {
       if (cur_size != 0) std::fill(begin(), end(), T{});
     }
data() [1/2]
template<typename T> T* otto::util::dyn_array< T >::data () inline
Definition at line 37 of file dyn-array.hpp.
 { return _data.get(); }
data() [2/2]
template<typename T> const T* otto::util::dyn_array< T >::data () const inline
Definition at line 38 of file dyn-array.hpp.
 { return _data.get(); }
end() [1/2]
template<typename T> T* otto::util::dyn_array< T >::end () inline
Definition at line 32 of file dyn-array.hpp.
Referenced by otto::util::dyn_array< double >::clear().
 { return _data.get() + cur_size; }
end() [2/2]
template<typename T> const T* otto::util::dyn_array< T >::end () const inline
Definition at line 35 of file dyn-array.hpp.
 { return _data.get() + cur_size; }
operator[]() [1/2]
template<typename T> decltype(auto) otto::util::dyn_array< T >::operator[] (std::size_t i) inline
Definition at line 28 of file dyn-array.hpp.
 {return _data[i];}
operator[]() [2/2]
template<typename T> decltype(auto) otto::util::dyn_array< T >::operator[] (std::size_t i) const inline
Definition at line 29 of file dyn-array.hpp.
 {return _data[i];}
resize()
template<typename T> void otto::util::dyn_array< T >::resize (std::size_t new_size) inline
Replace the array with a new one of size new_size
Also default initializes the data
Definition at line 45 of file dyn-array.hpp.
     {
       _data = std::make_unique<T[]>(new_size);
       cur_size = new_size;
       clear();
     }
size()
template<typename T> std::size_t otto::util::dyn_array< T >::size () const inline
Definition at line 40 of file dyn-array.hpp.
 { return cur_size; }
The documentation for this class was generated from the following file:
/home/topisani/dev/OTTO/src/util/dyn-array.hpp