OTTO: RtMidiOut Class Reference
RtMidiOut Class Reference
A realtime MIDI output class.
#include <RtMidi.h>
Public Member Functions
RtMidiOut (RtMidi::Api api=UNSPECIFIED, const std::string &clientName="RtMidi Output Client")
Default constructor that allows an optional client name.
~RtMidiOut (void) throw ()
The destructor closes any open MIDI connections.
RtMidi::Api getCurrentApi (void) throw ()
Returns the MIDI API specifier for the current instance of RtMidiOut.
void openPort (unsigned int portNumber=0, const std::string &portName=std::string("RtMidi Output"))
Open a MIDI output connection.
void closePort (void)
Close an open MIDI connection (if one exists).
virtual bool isPortOpen () const
Returns true if a port is open and false if not.
void openVirtualPort (const std::string &portName=std::string("RtMidi Output"))
Create a virtual output port, with optional name, to allow software connections (OS X, JACK and ALSA only).
unsigned int getPortCount (void)
Return the number of available MIDI output ports.
std::string getPortName (unsigned int portNumber=0)
Return a string identifier for the specified MIDI port type and number.
void sendMessage (const std::vector< unsigned char > *message)
Immediately send a single message out an open MIDI output port.
void sendMessage (const unsigned char *message, size_t size)
Immediately send a single message out an open MIDI output port.
virtual void setErrorCallback (RtMidiErrorCallback errorCallback=NULL, void *userData=0)
Set an error callback function to be invoked when an error has occured.
Public Member Functions inherited from RtMidi
void setClientName (const std::string &clientName)
void setPortName (const std::string &portName)
Protected Member Functions
void openMidiApi (RtMidi::Api api, const std::string &clientName)
Protected Member Functions inherited from RtMidi
RtMidi ()
virtual ~RtMidi ()
Additional Inherited Members
Public Types inherited from RtMidi
enum Api {
UNSPECIFIED, MACOSX_CORE, LINUX_ALSA, UNIX_JACK,
WINDOWS_MM, RTMIDI_DUMMY
}
MIDI API specifier arguments.
Static Public Member Functions inherited from RtMidi
static std::string getVersion (void) throw ()
A static function to determine the current RtMidi version.
static void getCompiledApi (std::vector< RtMidi::Api > &apis) throw ()
A static function to determine the available compiled MIDI APIs.
Protected Attributes inherited from RtMidi
MidiApi * rtapi_
Detailed Description
A realtime MIDI output class.
This class provides a common, platform-independent API for MIDI output. It allows one to probe available MIDI output ports, to connect to one such port, and to send MIDI bytes immediately over the connection. Create multiple instances of this class to connect to more than one MIDI device at the same time. With the OS-X, Linux ALSA and JACK MIDI APIs, it is also possible to open a virtual port to which other MIDI software clients can connect.
by Gary P. Scavone, 2003-2017.
Definition at line 370 of file RtMidi.h.
Constructor & Destructor Documentation
RtMidiOut()
RTMIDI_DLL_PUBLIC RtMidiOut::RtMidiOut (RtMidi::Api api = UNSPECIFIED, const std::string & clientName = "RtMidi Output Client")
Default constructor that allows an optional client name.
An exception will be thrown if a MIDI system initialization error occurs.
If no API argument is specified and multiple API support has been compiled, the default order of use is ALSA, JACK (Linux) and CORE, JACK (OS-X).
Definition at line 425 of file RtMidi.cpp.
References RtMidi::getCompiledApi(), MidiApi::getPortCount(), openMidiApi(), RtMidi::rtapi_, RtMidiError::UNSPECIFIED, and RtMidi::UNSPECIFIED.
 {
   if ( api != UNSPECIFIED ) {
     // Attempt to open the specified API.
     openMidiApi( api, clientName );
     if ( rtapi_ ) return;
     // No compiled support for specified API value.  Issue a warning
     // and continue as if no API was specified.
     std::cerr << "\nRtMidiOut: no compiled support for specified API argument!\n\n" << std::endl;
   }
   // Iterate through the compiled APIs and return as soon as we find
   // one with at least one port or we reach the end of the list.
   std::vector< RtMidi::Api > apis;
   getCompiledApi( apis );
   for ( unsigned int i=0; i<apis.size(); i++ ) {
     openMidiApi( apis[i], clientName );
     if ( rtapi_ && rtapi_->getPortCount() ) break;
   }
   if ( rtapi_ ) return;
   // It should not be possible to get here because the preprocessor
   // definition __RTMIDI_DUMMY__ is automatically defined if no
   // API-specific definitions are passed to the compiler. But just in
   // case something weird happens, we'll thrown an error.
   std::string errorText = "RtMidiOut: no compiled API support found ... critical error!!";
   throw( RtMidiError( errorText, RtMidiError::UNSPECIFIED ) );
 }
~RtMidiOut()
RtMidiOut::~RtMidiOut (void) throw ()
The destructor closes any open MIDI connections.
Definition at line 456 of file RtMidi.cpp.
 {
 }
Member Function Documentation
closePort()
void RtMidiOut::closePort (void) inline virtual
Close an open MIDI connection (if one exists).
Implements RtMidi.
Definition at line 602 of file RtMidi.h.
References MidiApi::closePort(), and RtMidi::rtapi_.
 { rtapi_->closePort(); }
getCurrentApi()
RtMidi::Api RtMidiOut::getCurrentApi (void) throw () inline
Returns the MIDI API specifier for the current instance of RtMidiOut.
Definition at line 599 of file RtMidi.h.
 { return rtapi_->getCurrentApi(); }
getPortCount()
unsigned int RtMidiOut::getPortCount (void) inline virtual
Return the number of available MIDI output ports.
Implements RtMidi.
Definition at line 604 of file RtMidi.h.
References MidiApi::getPortCount(), and RtMidi::rtapi_.
 { return rtapi_->getPortCount(); }
getPortName()
std::string RtMidiOut::getPortName (unsigned int portNumber = 0) inline virtual
Return a string identifier for the specified MIDI port type and number.
Returns
The name of the port with the given Id is returned.
Return values
An empty string is returned if an invalid port specifier is provided. User code should assume a UTF-8 encoding.
Implements RtMidi.
Definition at line 605 of file RtMidi.h.
References MidiApi::getPortName(), and RtMidi::rtapi_.
 { return rtapi_->getPortName( portNumber ); }
isPortOpen()
bool RtMidiOut::isPortOpen (void) const inline virtual
Returns true if a port is open and false if not.
Note that this only applies to connections made with the openPort() function, not to virtual ports.
Implements RtMidi.
Definition at line 603 of file RtMidi.h.
References MidiApi::isPortOpen(), and RtMidi::rtapi_.
 { return rtapi_->isPortOpen(); }
openMidiApi()
void RtMidiOut::openMidiApi (RtMidi::Api api, const std::string & clientName) protected
Definition at line 398 of file RtMidi.cpp.
References RtMidi::LINUX_ALSA, RtMidi::MACOSX_CORE, RtMidi::rtapi_, RtMidi::RTMIDI_DUMMY, RtMidi::UNIX_JACK, and RtMidi::WINDOWS_MM.
Referenced by RtMidiOut().
 {
   delete rtapi_;
   rtapi_ = 0;
 #if defined(__UNIX_JACK__)
   if ( api == UNIX_JACK )
     rtapi_ = new MidiOutJack( clientName );
 #endif
 #if defined(__LINUX_ALSA__)
   if ( api == LINUX_ALSA )
     rtapi_ = new MidiOutAlsa( clientName );
 #endif
 #if defined(__WINDOWS_MM__)
   if ( api == WINDOWS_MM )
     rtapi_ = new MidiOutWinMM( clientName );
 #endif
 #if defined(__MACOSX_CORE__)
   if ( api == MACOSX_CORE )
     rtapi_ = new MidiOutCore( clientName );
 #endif
 #if defined(__RTMIDI_DUMMY__)
   if ( api == RTMIDI_DUMMY )
     rtapi_ = new MidiOutDummy( clientName );
 #endif
 }
openPort()
void RtMidiOut::openPort (unsigned int portNumber = 0, const std::string & portName = std::string("RtMidi Output")) inline virtual
Open a MIDI output connection.
An optional port number greater than 0 can be specified. Otherwise, the default or first port found is opened. An exception is thrown if an error occurs while attempting to make the port connection.
Implements RtMidi.
Definition at line 600 of file RtMidi.h.
References MidiApi::openPort(), and RtMidi::rtapi_.
 { rtapi_->openPort( portNumber, portName ); }
openVirtualPort()
void RtMidiOut::openVirtualPort (const std::string & portName = std::string("RtMidi Output")) inline virtual
Create a virtual output port, with optional name, to allow software connections (OS X, JACK and ALSA only).
This function creates a virtual MIDI output port to which other software applications can connect. This type of functionality is currently only supported by the Macintosh OS-X, Linux ALSA and JACK APIs (the function does nothing with the other APIs). An exception is thrown if an error occurs while attempting to create the virtual port.
Implements RtMidi.
Definition at line 601 of file RtMidi.h.
References MidiApi::openVirtualPort(), and RtMidi::rtapi_.
 { rtapi_->openVirtualPort( portName ); }
sendMessage() [1/2]
void RtMidiOut::sendMessage (const std::vector< unsigned char > * message) inline
Immediately send a single message out an open MIDI output port.
An exception is thrown if an error occurs during output or an output connection was not previously established.
Definition at line 606 of file RtMidi.h.
References RtMidi::rtapi_.
 { ((MidiOutApi *)rtapi_)->sendMessage( &message->at(0), message->size() ); }
sendMessage() [2/2]
void RtMidiOut::sendMessage (const unsigned char * message, size_t size) inline
Immediately send a single message out an open MIDI output port.
An exception is thrown if an error occurs during output or an output connection was not previously established.
Parameters
message A pointer to the MIDI message as raw bytes
size Length of the MIDI message in bytes
Definition at line 607 of file RtMidi.h.
References RtMidi::rtapi_.
 { ((MidiOutApi *)rtapi_)->sendMessage( message, size ); }
setErrorCallback()
void RtMidiOut::setErrorCallback (RtMidiErrorCallback errorCallback = NULL, void * userData = 0) inline virtual
Set an error callback function to be invoked when an error has occured.
The callback function will be called whenever an error has occured. It is best to set the error callback function before opening a port.
Implements RtMidi.
Definition at line 608 of file RtMidi.h.
References RtMidi::rtapi_, and MidiApi::setErrorCallback().
 { rtapi_->setErrorCallback(errorCallback, userData); }
The documentation for this class was generated from the following files:
/home/topisani/dev/OTTO/boards/parts/audio/rtaudio/include/RtMidi.h
/home/topisani/dev/OTTO/boards/parts/audio/rtaudio/src/RtMidi.cpp