OTTO: otto::filesystem::directory_entry Class Reference
otto::filesystem::directory_entry Class Reference
#include <filesystem.hpp>
Public Member Functions
directory_entry ()=default
directory_entry (const directory_entry &)=default
directory_entry (directory_entry &&)=default
directory_entry (const path &p)
directory_entry (const path &p, std::error_code &ec)
~directory_entry ()
directory_entry & operator= (const directory_entry &)=default
directory_entry & operator= (directory_entry &&)=default
void assign (const path &p)
void assign (const path &p, std::error_code &ec)
void replace_filename (const path &p)
void replace_filename (const path &p, std::error_code &ec)
void refresh ()
void refresh (std::error_code &ec) noexcept
const class path & path () const
operator const class path & () const
bool exists () const
bool exists (std::error_code &) const noexcept
bool is_block_file () const
bool is_block_file (std::error_code &) const noexcept
bool is_character_file () const
bool is_character_file (std::error_code &) const noexcept
bool is_directory () const
bool is_directory (std::error_code &) const noexcept
bool is_fifo () const
bool is_fifo (std::error_code &) const noexcept
bool is_other () const
bool is_other (std::error_code &) const noexcept
bool is_regular_file () const
bool is_regular_file (std::error_code &) const noexcept
bool is_socket () const
bool is_socket (std::error_code &) const noexcept
bool is_symlink () const
bool is_symlink (std::error_code &) const noexcept
uintmax_t file_size () const
uintmax_t file_size (std::error_code &) const noexcept
uintmax_t hard_link_count () const
uintmax_t hard_link_count (std::error_code &) const noexcept
file_time_type last_write_time () const
file_time_type last_write_time (std::error_code &) const noexcept
file_status status () const
file_status status (std::error_code &) const noexcept
file_status symlink_status () const
file_status symlink_status (std::error_code &) const noexcept
bool operator< (const directory_entry &rhs) const noexcept
bool operator== (const directory_entry &rhs) const noexcept
bool operator!= (const directory_entry &rhs) const noexcept
bool operator<= (const directory_entry &rhs) const noexcept
bool operator> (const directory_entry &rhs) const noexcept
bool operator>= (const directory_entry &rhs) const noexcept
Friends
class directory_iterator
Detailed Description
Definition at line 346 of file filesystem.hpp.
Constructor & Destructor Documentation
directory_entry() [1/5]
otto::filesystem::directory_entry::directory_entry () default
directory_entry() [2/5]
otto::filesystem::directory_entry::directory_entry (const directory_entry &) default
directory_entry() [3/5]
otto::filesystem::directory_entry::directory_entry (directory_entry &&) default
directory_entry() [4/5]
otto::filesystem::directory_entry::directory_entry (const path & p) explicit
directory_entry() [5/5]
otto::filesystem::directory_entry::directory_entry (const path & p, std::error_code & ec)
~directory_entry()
otto::filesystem::DEntr::~directory_entry ()
Definition at line 828 of file filesystem.cpp.
 {}
Member Function Documentation
assign() [1/2]
void otto::filesystem::directory_entry::assign (const path & p)
assign() [2/2]
void otto::filesystem::directory_entry::assign (const path & p, std::error_code & ec)
exists() [1/2]
bool otto::filesystem::DEntr::exists () const
Definition at line 895 of file filesystem.cpp.
References otto::filesystem::exists().
   {
     return filesystem::exists(_status);
   }
exists() [2/2]
bool otto::filesystem::DEntr::exists (std::error_code & ec) const noexcept
Definition at line 890 of file filesystem.cpp.
References otto::filesystem::exists().
   {
     return filesystem::exists(_status);
   }
file_size() [1/2]
uintmax_t otto::filesystem::DEntr::file_size () const
Definition at line 985 of file filesystem.cpp.
   {
     return _file_size;
   }
file_size() [2/2]
uintmax_t otto::filesystem::DEntr::file_size (std::error_code & ec) const noexcept
Definition at line 980 of file filesystem.cpp.
   {
     return _file_size;
   }
hard_link_count() [1/2]
uintmax_t otto::filesystem::DEntr::hard_link_count () const
Definition at line 995 of file filesystem.cpp.
   {
     return _hard_link_count;
   }
hard_link_count() [2/2]
uintmax_t otto::filesystem::DEntr::hard_link_count (std::error_code & ec) const noexcept
Definition at line 990 of file filesystem.cpp.
   {
     return _hard_link_count;
   }
is_block_file() [1/2]
bool otto::filesystem::DEntr::is_block_file () const
Definition at line 905 of file filesystem.cpp.
References otto::filesystem::is_block_file().
   {
     return filesystem::is_block_file(_status);
   }
is_block_file() [2/2]
bool otto::filesystem::DEntr::is_block_file (std::error_code & ec) const noexcept
Definition at line 900 of file filesystem.cpp.
References otto::filesystem::is_block_file().
   {
     return filesystem::is_block_file(_status);
   }
is_character_file() [1/2]
bool otto::filesystem::DEntr::is_character_file () const
Definition at line 915 of file filesystem.cpp.
References otto::filesystem::is_character_file().
   {
     return filesystem::is_character_file(_status);
   }
is_character_file() [2/2]
bool otto::filesystem::DEntr::is_character_file (std::error_code & ec) const noexcept
Definition at line 910 of file filesystem.cpp.
References otto::filesystem::is_character_file().
   {
     return filesystem::is_character_file(_status);
   }
is_directory() [1/2]
bool otto::filesystem::DEntr::is_directory () const
Definition at line 925 of file filesystem.cpp.
References otto::filesystem::is_directory().
   {
     return filesystem::is_directory(_status);
   }
is_directory() [2/2]
bool otto::filesystem::DEntr::is_directory (std::error_code & ec) const noexcept
Definition at line 920 of file filesystem.cpp.
References otto::filesystem::is_directory().
   {
     return filesystem::is_directory(_status);
   }
is_fifo() [1/2]
bool otto::filesystem::DEntr::is_fifo () const
Definition at line 935 of file filesystem.cpp.
References otto::filesystem::is_fifo().
   {
     return filesystem::is_fifo(_status);
   }
is_fifo() [2/2]
bool otto::filesystem::DEntr::is_fifo (std::error_code & ec) const noexcept
Definition at line 930 of file filesystem.cpp.
References otto::filesystem::is_fifo().
   {
     return filesystem::is_fifo(_status);
   }
is_other() [1/2]
bool otto::filesystem::DEntr::is_other () const
Definition at line 945 of file filesystem.cpp.
References otto::filesystem::is_other().
   {
     return filesystem::is_other(_status);
   }
is_other() [2/2]
bool otto::filesystem::DEntr::is_other (std::error_code & ec) const noexcept
Definition at line 940 of file filesystem.cpp.
References otto::filesystem::is_other().
   {
     return filesystem::is_other(_status);
   }
is_regular_file() [1/2]
bool otto::filesystem::DEntr::is_regular_file () const
Definition at line 955 of file filesystem.cpp.
References otto::filesystem::is_regular_file().
   {
     return filesystem::is_regular_file(_status);
   }
is_regular_file() [2/2]
bool otto::filesystem::DEntr::is_regular_file (std::error_code & ec) const noexcept
Definition at line 950 of file filesystem.cpp.
References otto::filesystem::is_regular_file().
   {
     return filesystem::is_regular_file(_status);
   }
is_socket() [1/2]
bool otto::filesystem::DEntr::is_socket () const
Definition at line 965 of file filesystem.cpp.
References otto::filesystem::is_socket().
   {
     return filesystem::is_socket(_status);
   }
is_socket() [2/2]
bool otto::filesystem::DEntr::is_socket (std::error_code & ec) const noexcept
Definition at line 960 of file filesystem.cpp.
References otto::filesystem::is_socket().
   {
     return filesystem::is_socket(_status);
   }
is_symlink() [1/2]
bool otto::filesystem::DEntr::is_symlink () const
Definition at line 975 of file filesystem.cpp.
References otto::filesystem::is_symlink().
   {
     return filesystem::is_symlink(_status);
   }
is_symlink() [2/2]
bool otto::filesystem::DEntr::is_symlink (std::error_code & ec) const noexcept
Definition at line 970 of file filesystem.cpp.
References otto::filesystem::is_symlink().
   {
     return filesystem::is_symlink(_status);
   }
last_write_time() [1/2]
file_time_type otto::filesystem::DEntr::last_write_time () const
Definition at line 1005 of file filesystem.cpp.
References otto::filesystem::last_write_time().
   {
     return filesystem::last_write_time(pathobject);
   }
last_write_time() [2/2]
file_time_type otto::filesystem::DEntr::last_write_time (std::error_code & ec) const noexcept
Definition at line 1000 of file filesystem.cpp.
References otto::filesystem::last_write_time().
   {
     return filesystem::last_write_time(pathobject, ec);
   }
operator const class path &()
otto::filesystem::DEntr::operator const class path & () const
Definition at line 885 of file filesystem.cpp.
   {
     return path();
   }
operator!=()
bool otto::filesystem::DEntr::operator!= (const directory_entry & rhs) const noexcept
Definition at line 1035 of file filesystem.cpp.
   {
     return pathobject != rhs.pathobject;
   }
operator<()
bool otto::filesystem::directory_entry::operator< (const directory_entry & rhs) const noexcept
operator<=()
bool otto::filesystem::directory_entry::operator<= (const directory_entry & rhs) const noexcept
operator=() [1/2]
directory_entry& otto::filesystem::directory_entry::operator= (const directory_entry &) default
operator=() [2/2]
directory_entry& otto::filesystem::directory_entry::operator= (directory_entry &&) default
operator==()
bool otto::filesystem::DEntr::operator== (const directory_entry & rhs) const noexcept
Definition at line 1030 of file filesystem.cpp.
   {
     return pathobject == rhs.pathobject;
   }
operator>()
bool otto::filesystem::directory_entry::operator> (const directory_entry & rhs) const noexcept
operator>=()
bool otto::filesystem::directory_entry::operator>= (const directory_entry & rhs) const noexcept
path()
const class path & otto::filesystem::DEntr::path () const
Definition at line 880 of file filesystem.cpp.
   {
     return pathobject;
   }
refresh() [1/2]
void otto::filesystem::DEntr::refresh ()
Definition at line 855 of file filesystem.cpp.
   {
     std::error_code ec;
     refresh(ec);
     if (ec != std::error_code()) {
       throw filesystem_error("While refreshing directory entry", pathobject,
                              ec);
     }
   }
refresh() [2/2]
void otto::filesystem::DEntr::refresh (std::error_code & ec) noexcept
Definition at line 865 of file filesystem.cpp.
References otto::filesystem::exists(), and otto::filesystem::symlink_status().
   {
     struct stat st;
     _status = px::status(pathobject, st, ec);
     if (filesystem::exists(_status)) {
       _file_size       = px::file_size(st, ec);
       _hard_link_count = px::hard_link_count(st, ec);
     } else {
       _file_size       = 0;
       _hard_link_count = 0;
     }
     _symlink_status = filesystem::symlink_status(pathobject, ec);
   }
replace_filename() [1/2]
void otto::filesystem::directory_entry::replace_filename (const path & p)
replace_filename() [2/2]
void otto::filesystem::directory_entry::replace_filename (const path & p, std::error_code & ec)
status() [1/2]
file_status otto::filesystem::DEntr::status () const
Definition at line 1015 of file filesystem.cpp.
   {
     return _status;
   }
status() [2/2]
file_status otto::filesystem::DEntr::status (std::error_code & ec) const noexcept
Definition at line 1010 of file filesystem.cpp.
   {
     return _status;
   }
symlink_status() [1/2]
file_status otto::filesystem::DEntr::symlink_status () const
Definition at line 1025 of file filesystem.cpp.
   {
     return _symlink_status;
   }
symlink_status() [2/2]
file_status otto::filesystem::DEntr::symlink_status (std::error_code & ec) const noexcept
Definition at line 1020 of file filesystem.cpp.
   {
     return _symlink_status;
   }
Friends And Related Function Documentation
directory_iterator
friend class directory_iterator friend
Definition at line 431 of file filesystem.hpp.
The documentation for this class was generated from the following files:
/home/topisani/dev/OTTO/src/util/filesystem.hpp
/home/topisani/dev/OTTO/src/util/filesystem.cpp