OTTO: otto::filesystem::recursive_directory_iterator Class Reference
otto::filesystem::recursive_directory_iterator Class Reference
#include <filesystem.hpp>
Public Types
using iterator_category = std::input_iterator_tag
using value_type = directory_entry
using difference_type = ptrdiff_t
using pointer = const directory_entry *
using reference = const directory_entry &
Public Member Functions
recursive_directory_iterator () noexcept
recursive_directory_iterator (const path &p)
recursive_directory_iterator (const recursive_directory_iterator &rhs)
recursive_directory_iterator (recursive_directory_iterator &&rhs) noexcept
~recursive_directory_iterator ()
int depth () const
const directory_entry & operator* () const
const directory_entry * operator-> () const
recursive_directory_iterator & operator= (const recursive_directory_iterator &rhs)
recursive_directory_iterator & operator= (recursive_directory_iterator &&rhs) noexcept
recursive_directory_iterator & operator++ ()
void pop ()
bool operator== (const recursive_directory_iterator &other) const
bool operator!= (const recursive_directory_iterator &other) const
recursive_directory_iterator operator++ (int)
Detailed Description
Definition at line 494 of file filesystem.hpp.
Member Typedef Documentation
difference_type
using otto::filesystem::recursive_directory_iterator::difference_type = ptrdiff_t
Definition at line 498 of file filesystem.hpp.
iterator_category
using otto::filesystem::recursive_directory_iterator::iterator_category = std::input_iterator_tag
Definition at line 496 of file filesystem.hpp.
pointer
using otto::filesystem::recursive_directory_iterator::pointer = const directory_entry*
Definition at line 499 of file filesystem.hpp.
reference
using otto::filesystem::recursive_directory_iterator::reference = const directory_entry&
Definition at line 500 of file filesystem.hpp.
value_type
using otto::filesystem::recursive_directory_iterator::value_type = directory_entry
Definition at line 497 of file filesystem.hpp.
Constructor & Destructor Documentation
recursive_directory_iterator() [1/4]
otto::filesystem::RDIter::recursive_directory_iterator () noexcept
Definition at line 1186 of file filesystem.cpp.
 {}
recursive_directory_iterator() [2/4]
otto::filesystem::RDIter::recursive_directory_iterator (const path & p) explicit
Definition at line 1188 of file filesystem.cpp.
References otto::filesystem::is_directory().
   {
     if (fs::is_directory(p)) {
       _data = std::make_shared<std::vector<DIter>>();
       std::error_code ec;
       _data->emplace_back(p, ec);
       if (_data->front() == DIter()) {
         _data = nullptr;
       }
       if (ec.value() != 0) {
         throw filesystem_error("Error constructing recursive_directory_iterator", p, ec);
       }
     }
   }
recursive_directory_iterator() [3/4]
otto::filesystem::RDIter::recursive_directory_iterator (const recursive_directory_iterator & rhs) default
recursive_directory_iterator() [4/4]
otto::filesystem::RDIter::recursive_directory_iterator (recursive_directory_iterator && rhs) default noexcept
~recursive_directory_iterator()
otto::filesystem::RDIter::~recursive_directory_iterator ()
Definition at line 1207 of file filesystem.cpp.
 {}
Member Function Documentation
depth()
int otto::filesystem::RDIter::depth () const
Definition at line 1211 of file filesystem.cpp.
   {
     return _data->size();
   }
operator!=()
bool otto::filesystem::RDIter::operator!= (const recursive_directory_iterator & other) const
Definition at line 1275 of file filesystem.cpp.
   {
     return !(*this == other);
   }
operator*()
const directory_entry & otto::filesystem::RDIter::operator* () const
Definition at line 1217 of file filesystem.cpp.
   {
     return *_data->back();
   }
operator++() [1/2]
RDIter & otto::filesystem::RDIter::operator++ ()
Definition at line 1234 of file filesystem.cpp.
References otto::filesystem::end().
   {
     if (_data != nullptr) {
       if (_data->back()->is_directory()) {
         std::error_code ec;
         _data->emplace_back(_data->back()->path(), ec);
         if (ec.value() != 0) {
           throw filesystem_error("", ec);
         }
       } else {
         ++_data->back();
         if (_data->back() == end(_data->back())) {
           pop();
         }
       }
     }
     return *this;
   }
operator++() [2/2]
RDIter otto::filesystem::RDIter::operator++ (int)
Definition at line 1280 of file filesystem.cpp.
   {
     auto tmp = *this;
     ++(*this);
     return tmp;
   }
operator->()
const directory_entry * otto::filesystem::RDIter::operator-> () const
Definition at line 1222 of file filesystem.cpp.
   {
     return _data->back().operator->();
   }
operator=() [1/2]
RDIter & otto::filesystem::RDIter::operator= (const recursive_directory_iterator & rhs) default
operator=() [2/2]
RDIter & otto::filesystem::RDIter::operator= (recursive_directory_iterator && rhs) default noexcept
operator==()
bool otto::filesystem::RDIter::operator== (const recursive_directory_iterator & other) const
Definition at line 1268 of file filesystem.cpp.
   {
     return (_data == other._data) ||
            (_data != nullptr && other._data != nullptr &&
              _data->back() == other._data->back());
   }
pop()
void otto::filesystem::RDIter::pop ()
Definition at line 1253 of file filesystem.cpp.
References otto::filesystem::end().
   {
     if (_data != nullptr) {
       _data->pop_back();
       if (_data->size() == 0) {
         _data = nullptr;
       } else {
         ++(_data->back());
         if (_data->back() == end(_data->back())) {
           pop();
         }
       }
     }
   }
The documentation for this class was generated from the following files:
/home/topisani/dev/OTTO/src/util/filesystem.hpp
/home/topisani/dev/OTTO/src/util/filesystem.cpp