OTTO: faust_master Class Reference
faust_master Class Reference
#include <master.faust.hpp>
Public Member Functions
void metadata (Meta *m)
virtual int getNumInputs ()
virtual int getNumOutputs ()
virtual int getInputRate (int channel)
virtual int getOutputRate (int channel)
virtual void instanceConstants (int samplingFreq)
virtual void instanceResetUserInterface ()
virtual void instanceClear ()
virtual void init (int samplingFreq)
virtual void instanceInit (int samplingFreq)
virtual faust_master * clone ()
virtual int getSampleRate ()
virtual void buildUserInterface (UI *ui_interface)
virtual void compute (int count, FAUSTFLOAT **inputs, FAUSTFLOAT **outputs)
Static Public Member Functions
static void classInit (int samplingFreq)
Detailed Description
Definition at line 46 of file master.faust.hpp.
Member Function Documentation
buildUserInterface()
virtual void faust_master::buildUserInterface (UI * ui_interface) inline virtual
Definition at line 181 of file master.faust.hpp.
{
         ui_interface->openVerticalBox("master");
         ui_interface->closeBox();
     }
classInit()
static void faust_master::classInit (int samplingFreq) inline static
Definition at line 129 of file master.faust.hpp.
Referenced by init().
{
     }
clone()
virtual faust_master* faust_master::clone () inline virtual
Definition at line 173 of file master.faust.hpp.
{
         return new faust_master();
     }
compute()
virtual void faust_master::compute (int count, FAUSTFLOAT ** inputs, FAUSTFLOAT ** outputs) inline virtual
Definition at line 187 of file master.faust.hpp.
{
         FAUSTFLOAT* input0 = inputs[0];
         FAUSTFLOAT* input1 = inputs[1];
         FAUSTFLOAT* output0 = outputs[0];
         FAUSTFLOAT* output1 = outputs[1];
         for (int i = 0; (i < count); i = (i + 1)) {
             float fTemp0 = float(input1[i]);
             float fTemp1 = float(input0[i]);
             float fTemp2 = std::fabs((std::fabs(fTemp0) + std::fabs(fTemp1)));
             float fTemp3 = ((fRec1[1] > fTemp2)?fConst4:fConst3);
             fRec2[0] = ((fRec2[1] * fTemp3) + (fTemp2 * (1.0f - fTemp3)));
             fRec1[0] = fRec2[0];
             fRec0[0] = ((fConst1 * fRec0[1]) + (fConst2 * (0.0f - (0.75f * std::max(((20.0f * std::log10(fRec1[0])) + 6.0f), 0.0f)))));
             float fTemp4 = exp10f((0.0500000007f * fRec0[0]));
             output0[i] = FAUSTFLOAT((fTemp4 * fTemp1));
             output1[i] = FAUSTFLOAT((fTemp4 * fTemp0));
             fRec2[1] = fRec2[0];
             fRec1[1] = fRec1[0];
             fRec0[1] = fRec0[0];
         }
     }
getInputRate()
virtual int faust_master::getInputRate (int channel) inline virtual
Definition at line 88 of file master.faust.hpp.
{
         int rate;
         switch (channel) {
             case 0: {
                 rate = 1;
                 break;
             }
             case 1: {
                 rate = 1;
                 break;
             }
             default: {
                 rate = -1;
                 break;
             }
         }
         return rate;
     }
getNumInputs()
virtual int faust_master::getNumInputs () inline virtual
Definition at line 80 of file master.faust.hpp.
{
         return 2;
     }
getNumOutputs()
virtual int faust_master::getNumOutputs () inline virtual
Definition at line 84 of file master.faust.hpp.
{
         return 2;
     }
getOutputRate()
virtual int faust_master::getOutputRate (int channel) inline virtual
Definition at line 108 of file master.faust.hpp.
{
         int rate;
         switch (channel) {
             case 0: {
                 rate = 1;
                 break;
             }
             case 1: {
                 rate = 1;
                 break;
             }
             default: {
                 rate = -1;
                 break;
             }
         }
         return rate;
     }
getSampleRate()
virtual int faust_master::getSampleRate () inline virtual
Definition at line 176 of file master.faust.hpp.
{
         return fSamplingFreq;
     }
init()
virtual void faust_master::init (int samplingFreq) inline virtual
Definition at line 163 of file master.faust.hpp.
References classInit(), and instanceInit().
{
         classInit(samplingFreq);
         instanceInit(samplingFreq);
     }
instanceClear()
virtual void faust_master::instanceClear () inline virtual
Definition at line 147 of file master.faust.hpp.
Referenced by instanceInit().
{
         for (int l0 = 0; (l0 < 2); l0 = (l0 + 1)) {
             fRec2[l0] = 0.0f;
         }
         for (int l1 = 0; (l1 < 2); l1 = (l1 + 1)) {
             fRec1[l1] = 0.0f;
         }
         for (int l2 = 0; (l2 < 2); l2 = (l2 + 1)) {
             fRec0[l2] = 0.0f;
         }
     }
instanceConstants()
virtual void faust_master::instanceConstants (int samplingFreq) inline virtual
Definition at line 133 of file master.faust.hpp.
Referenced by instanceInit().
{
         fSamplingFreq = samplingFreq;
         fConst0 = std::min(192000.0f, std::max(1.0f, float(fSamplingFreq)));
         fConst1 = std::exp((0.0f - (2500.0f / fConst0)));
         fConst2 = (1.0f - fConst1);
         fConst3 = std::exp((0.0f - (1250.0f / fConst0)));
         fConst4 = std::exp((0.0f - (2.0f / fConst0)));
     }
instanceInit()
virtual void faust_master::instanceInit (int samplingFreq) inline virtual
Definition at line 167 of file master.faust.hpp.
References instanceClear(), instanceConstants(), and instanceResetUserInterface().
Referenced by init().
{
         instanceConstants(samplingFreq);
         instanceResetUserInterface();
         instanceClear();
     }
instanceResetUserInterface()
virtual void faust_master::instanceResetUserInterface () inline virtual
Definition at line 143 of file master.faust.hpp.
Referenced by instanceInit().
{
     }
metadata()
void faust_master::metadata (Meta * m) inline
Definition at line 62 of file master.faust.hpp.
{
         m->declare("analyzers.lib/name", "Faust Analyzer Library");
         m->declare("analyzers.lib/version", "0.0");
         m->declare("basics.lib/name", "Faust Basic Element Library");
         m->declare("basics.lib/version", "0.0");
         m->declare("compressors.lib/name", "Faust Compressor Effect Library");
         m->declare("compressors.lib/version", "0.0");
         m->declare("filename", "master");
         m->declare("maths.lib/author", "GRAME");
         m->declare("maths.lib/copyright", "GRAME");
         m->declare("maths.lib/license", "LGPL with exception");
         m->declare("maths.lib/name", "Faust Math Library");
         m->declare("maths.lib/version", "2.1");
         m->declare("name", "master");
         m->declare("signals.lib/name", "Faust Signal Routing Library");
         m->declare("signals.lib/version", "0.0");
     }
The documentation for this class was generated from the following file:
/home/topisani/dev/OTTO/src/engines/misc/master/master.faust.hpp