OTTO: SegExpBypass< T, Td > Class Template Reference
SegExpBypass< T, Td > Class Template Reference
Detailed Description
template<class T = gam::real, class Td = gam::DomainObserver>
class SegExpBypass< T, Td >
Exponential envelope segment for smoothing out value changes.
Definition at line 16 of file SegExpBypass.hpp.
#include <SegExpBypass.hpp>
Public Member Functions
SegExpBypass (T len, T crv=-3, T start=1, T end=0)
bool done () const
Returns whether envelope is done.
void finish ()
Jumps to the end of the curve.
T operator() ()
Generate next value.
void operator= (T v)
Set new end value. Start value is set to current value.
T getEnd ()
void curve (T v)
Set curvature. Negative gives faster change, positive gives slower change.
void period (T v)
Set length in domain units.
void reset ()
void set (T len, T crv)
Set length and curvature.
void onDomainChange (double r)
Protected Attributes
T mLen
T mCrv
T mVal1
T mVal0
gam::Curve< T, T > mCurve
Constructor & Destructor Documentation
SegExpBypass()
template<class T = gam::real, class Td = gam::DomainObserver> SegExpBypass< T, Td >::SegExpBypass (T len, T crv = -3, T start = 1, T end = 0)
Parameters
[in] len Length of segment in domain units
[in] crv Curvature of segment
[in] start Start value
[in] end End value
Definition at line 23 of file SegExpBypass.hpp.
References SegExpBypass< T, Td >::onDomainChange().
Member Function Documentation
done()
template<class T = gam::real, class Td = gam::DomainObserver> bool SegExpBypass< T, Td >::done () const
Returns whether envelope is done.
Definition at line 30 of file SegExpBypass.hpp.
References SegExpBypass< T, Td >::mCurve.
Referenced by SegExpBypass< T, Td >::operator()().
finish()
template<class T = gam::real, class Td = gam::DomainObserver> void SegExpBypass< T, Td >::finish ()
Jumps to the end of the curve.
Definition at line 33 of file SegExpBypass.hpp.
References SegExpBypass< T, Td >::mCurve.
operator()()
template<class T = gam::real, class Td = gam::DomainObserver> T SegExpBypass< T, Td >::operator() ()
Generate next value.
Definition at line 36 of file SegExpBypass.hpp.
References SegExpBypass< T, Td >::done(), SegExpBypass< T, Td >::mCurve, SegExpBypass< T, Td >::mVal0, and SegExpBypass< T, Td >::mVal1.
operator=()
template<class T = gam::real, class Td = gam::DomainObserver> void SegExpBypass< T, Td >::operator= (T v)
Set new end value. Start value is set to current value.
Definition at line 42 of file SegExpBypass.hpp.
References SegExpBypass< T, Td >::mCurve, SegExpBypass< T, Td >::mVal0, and SegExpBypass< T, Td >::mVal1.
getEnd()
template<class T = gam::real, class Td = gam::DomainObserver> T SegExpBypass< T, Td >::getEnd ()
Definition at line 48 of file SegExpBypass.hpp.
References SegExpBypass< T, Td >::mVal0.
curve()
template<class T = gam::real, class Td = gam::DomainObserver> void SegExpBypass< T, Td >::curve (T v)
Set curvature. Negative gives faster change, positive gives slower change.
Definition at line 51 of file SegExpBypass.hpp.
References SegExpBypass< T, Td >::mLen, and SegExpBypass< T, Td >::set().
period()
template<class T = gam::real, class Td = gam::DomainObserver> void SegExpBypass< T, Td >::period (T v)
Set length in domain units.
Definition at line 54 of file SegExpBypass.hpp.
References SegExpBypass< T, Td >::mCrv, and SegExpBypass< T, Td >::set().
reset()
template<class T = gam::real, class Td = gam::DomainObserver> void SegExpBypass< T, Td >::reset ()
Definition at line 56 of file SegExpBypass.hpp.
References SegExpBypass< T, Td >::mCurve.
set()
template<class T = gam::real, class Td = gam::DomainObserver> void SegExpBypass< T, Td >::set (T len, T crv)
Set length and curvature.
Definition at line 59 of file SegExpBypass.hpp.
References SegExpBypass< T, Td >::mCrv, SegExpBypass< T, Td >::mCurve, and SegExpBypass< T, Td >::mLen.
Referenced by SegExpBypass< T, Td >::curve(), SegExpBypass< T, Td >::onDomainChange(), and SegExpBypass< T, Td >::period().
onDomainChange()
template<class T = gam::real, class Td = gam::DomainObserver> void SegExpBypass< T, Td >::onDomainChange (double r)
Definition at line 64 of file SegExpBypass.hpp.
References SegExpBypass< T, Td >::mCrv, SegExpBypass< T, Td >::mLen, and SegExpBypass< T, Td >::set().
Referenced by SegExpBypass< T, Td >::SegExpBypass().
Member Data Documentation
mLen
template<class T = gam::real, class Td = gam::DomainObserver> T SegExpBypass< T, Td >::mLen protected
Definition at line 67 of file SegExpBypass.hpp.
Referenced by SegExpBypass< T, Td >::curve(), SegExpBypass< T, Td >::onDomainChange(), and SegExpBypass< T, Td >::set().
mCrv
template<class T = gam::real, class Td = gam::DomainObserver> T SegExpBypass< T, Td >::mCrv protected
Definition at line 67 of file SegExpBypass.hpp.
Referenced by SegExpBypass< T, Td >::onDomainChange(), SegExpBypass< T, Td >::period(), and SegExpBypass< T, Td >::set().
mVal1
template<class T = gam::real, class Td = gam::DomainObserver> T SegExpBypass< T, Td >::mVal1 protected
Definition at line 67 of file SegExpBypass.hpp.
Referenced by SegExpBypass< T, Td >::operator()(), and SegExpBypass< T, Td >::operator=().
mVal0
template<class T = gam::real, class Td = gam::DomainObserver> T SegExpBypass< T, Td >::mVal0 protected
Definition at line 67 of file SegExpBypass.hpp.
Referenced by SegExpBypass< T, Td >::getEnd(), SegExpBypass< T, Td >::operator()(), and SegExpBypass< T, Td >::operator=().
mCurve
template<class T = gam::real, class Td = gam::DomainObserver> gam::Curve<T,T> SegExpBypass< T, Td >::mCurve protected
Definition at line 68 of file SegExpBypass.hpp.
Referenced by SegExpBypass< T, Td >::done(), SegExpBypass< T, Td >::finish(), SegExpBypass< T, Td >::operator()(), SegExpBypass< T, Td >::operator=(), SegExpBypass< T, Td >::reset(), and SegExpBypass< T, Td >::set().
The documentation for this class was generated from the following file:
/home/travis/build/topisani/OTTO/src/util/dsp/SegExpBypass.hpp