OTTO: S24 Class Reference
S24 Class Reference
Detailed Description
Definition at line 649 of file RtAudio.h.
#include <RtAudio.h>
Public Member Functions
S24 ()
S24 & operator= (const int &i)
S24 (const S24 &v)
S24 (const double &d)
S24 (const float &f)
S24 (const signed short &s)
S24 (const char &c)
int asInt ()
Protected Attributes
unsigned char c3 [3]
Constructor & Destructor Documentation
S24::S24 ()
Definition at line 655 of file RtAudio.h.
S24::S24 (const S24 & v)
Definition at line 664 of file RtAudio.h.
S24::S24 (const double & d)
Definition at line 665 of file RtAudio.h.
References operator=().
S24::S24 (const float & f)
Definition at line 666 of file RtAudio.h.
References operator=().
S24::S24 (const signed short & s)
Definition at line 667 of file RtAudio.h.
References operator=().
S24::S24 (const char & c)
Definition at line 668 of file RtAudio.h.
References operator=().
Member Function Documentation
S24& S24::operator= (const int & i)
Definition at line 657 of file RtAudio.h.
References c3.
Referenced by S24().
int S24::asInt ()
Definition at line 670 of file RtAudio.h.
References c3.
Member Data Documentation
unsigned char S24::c3[3] protected
Definition at line 652 of file RtAudio.h.
Referenced by asInt(), and operator=().
The documentation for this class was generated from the following file:
/home/travis/build/topisani/OTTO/boards/parts/audio/rtaudio/include/RtAudio.h