OTTO: otto::util::SoundFile Class Reference
otto::util::SoundFile Class Reference
A file handler for sound (wav, aiff) files.
#include <soundfile.hpp>
Classes
struct Error
struct Info
Public Types
using Position = int
Used for indexing into the file.
using Sample = float
The type of a sample.
using Chunk = ByteFile::Chunk
Public Types inherited from otto::util::ByteFile
using Position = int
using Path = filesystem::path
Public Member Functions
SoundFile ()
virtual ~SoundFile ()=default
void write_file () override
void read_file () override
Position seek (Position)
Position position ()
Position length ()
template<typename OutIter , typename = std::enable_if< is_iterator_v<OutIter, Sample, std::output_iterator_tag>>>
void read_samples (OutIter, OutIter)
template<typename OutIter , typename = std::enable_if< is_iterator_v<OutIter, Sample, std::output_iterator_tag>>>
void read_samples (OutIter &&, int)
template<typename InIter , typename = std::enable_if< is_iterator_v<InIter, Sample, std::input_iterator_tag>>>
void write_samples (InIter, InIter)
template<typename InIter , typename = std::enable_if< is_iterator_v<InIter, Sample, std::input_iterator_tag>>>
void write_samples (InIter &&, int)
void open (const Path &)
void close ()
void flush ()
bool is_open () const
Public Member Functions inherited from otto::util::ByteFile
ByteFile ()
ByteFile (const Path &)
ByteFile (ByteFile &)=delete
ByteFile (ByteFile &&)
virtual ~ByteFile ()
ByteFile & operator= (ByteFile)
void open (const Path &)
void close ()
void flush ()
bool is_open () const
virtual void create_file ()
Position seek (Position, std::ios::seekdir=std::ios::beg)
Position position ()
Position size ()
template<typename OutIter , typename = std::enable_if<is_iterator_v<OutIter, std::byte, std::output_iterator_tag>>>
result< void, OutIter > read_bytes (OutIter, OutIter)
template<typename OutIter , typename = std::enable_if<is_iterator_v<OutIter, std::byte, std::output_iterator_tag>>>
result< void, std::streampos > read_bytes (OutIter, int)
template<std::size_t N>
result< void, std::streampos > read_bytes (bytes< N > &)
template<typename InIter , typename = std::enable_if<is_iterator_v<InIter, std::byte, std::input_iterator_tag>>>
void write_bytes (InIter, InIter)
template<typename InIter , typename = std::enable_if<is_iterator_v<InIter, std::byte, std::input_iterator_tag>>>
void write_bytes (InIter, int)
template<std::size_t N>
void write_bytes (const bytes< N > &)
template<typename F >
auto for_chunks_in_range (Position, Position, F &&f) -> std::enable_if_t< util::is_invocable_v< F, Chunk &>, void >
Public Attributes
struct otto::util::SoundFile::Info info
Public Attributes inherited from otto::util::ByteFile
Path path
Static Public Attributes
static constexpr std::size_t sample_size = sizeof(Sample)
Size in bytes of one sample.
Protected Member Functions
virtual void add_custom_chunks (std::vector< std::unique_ptr< Chunk >> &v)
virtual void replace_custom_chunk (std::unique_ptr< Chunk > &ptr)
Sample bytes_to_sample (bytes< sample_size > bytes)
bytes< sample_size > sample_to_bytes (Sample sample)
Protected Attributes
ByteFile::Position audioOffset {0}
Protected Attributes inherited from otto::util::ByteFile
std::fstream fstream
Friends
struct Header
struct WAVE_fmt
struct WAVE_data
Detailed Description
A file handler for sound (wav, aiff) files.
Definition at line 12 of file soundfile.hpp.
Member Typedef Documentation
Chunk
using otto::util::SoundFile::Chunk = ByteFile::Chunk
Definition at line 18 of file soundfile.hpp.
Position
using otto::util::SoundFile::Position = int
Used for indexing into the file.
Definition at line 15 of file soundfile.hpp.
Sample
using otto::util::SoundFile::Sample = float
The type of a sample.
Definition at line 17 of file soundfile.hpp.
Constructor & Destructor Documentation
SoundFile()
otto::util::SoundFile::SoundFile ()
Definition at line 104 of file soundfile.cpp.
 {}
~SoundFile()
virtual otto::util::SoundFile::~SoundFile () virtual default
Member Function Documentation
add_custom_chunks()
virtual void otto::util::SoundFile::add_custom_chunks (std::vector< std::unique_ptr< Chunk >> & v) inline protected virtual
When extending <SoundFile>, override this function.
It should push back any custom metadata chunks to v
Reimplemented in otto::util::TapeFile.
Definition at line 76 of file soundfile.hpp.
Referenced by write_file().
 {}
bytes_to_sample()
Sample otto::util::SoundFile::bytes_to_sample (bytes< sample_size > bytes) inline protected
Definition at line 92 of file soundfile.hpp.
References otto::util::bytes< len >::cast().
Referenced by read_samples().
{
       return bytes.cast<Sample>();
     }
close()
void otto::util::ByteFile::close
Definition at line 48 of file bytefile.cpp.
{
     if (fstream.is_open()) {
       write_file();
       fstream.close();
     };
   }
flush()
void otto::util::ByteFile::flush
Definition at line 55 of file bytefile.cpp.
{
     if (fstream.is_open()) {
       write_file();
       fstream.flush();
     };
   }
is_open()
bool otto::util::ByteFile::is_open
Definition at line 77 of file bytefile.cpp.
{
     return fstream.is_open();
   }
length()
Position otto::util::SoundFile::length ()
Definition at line 192 of file soundfile.cpp.
References audioOffset, sample_size, and otto::util::ByteFile::size().
{
     return (ByteFile::size() - audioOffset) / sample_size;
   }
open()
void otto::util::ByteFile::open
Definition at line 35 of file bytefile.cpp.
{
     if (is_open()) {
       throw "File already open";
     }
     path = p;
     fstream.open(p.c_str(), std::ios::in | std::ios::out | std::ios::binary);
     if (!fstream || size() == 0) {
       // File didnt exist, create it
       create_file();
     }
     read_file();
   }
position()
Position otto::util::SoundFile::position ()
Definition at line 183 of file soundfile.cpp.
References audioOffset, otto::util::ByteFile::position(), sample_size, and seek().
{
     Position r = (ByteFile::position() - audioOffset) / sample_size;
     if (r < 0) {
       seek(0);
       return 0;
     }
     return r;
   }
read_file()
void otto::util::SoundFile::read_file () override virtual
Reimplemented from otto::util::ByteFile.
Definition at line 106 of file soundfile.cpp.
References otto::util::SoundFile::Info::AIFF, otto::util::exception::append(), otto::util::bytes< len >::as_u(), otto::filesystem::path::c_str(), otto::util::Header::chunks, otto::util::ByteFile::create_file(), otto::util::Header::format, otto::util::ByteFile::Chunk::id, info, otto::util::ByteFile::path, otto::util::ByteFile::Chunk::read(), replace_custom_chunk(), seek(), otto::util::ByteFile::seek(), otto::util::bytes< len >::str(), otto::util::SoundFile::Info::type, otto::util::SoundFile::Error::UnrecognizedFileType, and otto::util::SoundFile::Info::WAVE.
{
     ByteFile::seek(0);
     Header header;
     header.read(*this);
     if (header.id == "RIFF" && header.format == "WAVE") {
       info.type = Info::Type::WAVE;
     } else if (header.id == "FORM" && header.format == "AIFF") {
       info.type = Info::Type::AIFF;
     } else if (header.id.as_u() == 0) {
       create_file();
     } else {
       throw Error::UnrecognizedFileType.append(
         fmt::format("Got {} while reading file {}", header.id.str(), path.c_str()));
     }
     switch (info.type) {
     case Info::Type::WAVE:
       LOG_F(INFO, "Reading Wave file: {}", path);
       LOG_F(INFO, "-------------------");
       for (auto&& chunk : header.chunks) {
         if (chunk->id == "fmt ")
           chunk = std::make_unique<WAVE_fmt>(*chunk);
         if (chunk->id == "data")
           chunk = std::make_unique<WAVE_data>(*chunk);
         replace_custom_chunk(chunk);
         // re-read the chunk as the new type
         ByteFile::seek(chunk->beginning());
         chunk->read(*this);
         LOG_F(INFO, " Chunk:  {}", std::string((char*)chunk->id.data, 4));
         LOG_F(INFO, " Offset: {}", chunk->offset);
         LOG_F(INFO, " Size:   {}", chunk->size.as_u());
         LOG_F(INFO, "-------------------");
       } break;
       LOG_F(INFO, "Done reading file! ");
       LOG_F(INFO, "-------------------");
     case Info::Type::AIFF:
       throw "Unsupported file type. Currently only wav is supported";
     }
     seek(0);
   }
read_samples() [1/2]
template<typename OutIter , typename > void otto::util::SoundFile::read_samples (OutIter f, OutIter l)
Definition at line 109 of file soundfile.hpp.
References bytes_to_sample(), and otto::util::ByteFile::read_bytes().
{
     if constexpr (std::is_pointer_v<OutIter>) {
         auto r = ByteFile::read_bytes(reinterpret_cast<std::byte*>(f),
           reinterpret_cast<std::byte*>(l));
         r.if_err([&] (auto&& e) {
             std::generate(e, l, [] { return 0; });
           });
       } else {
       bytes<sample_size> buf;
       int i = 0;
       for (auto iter = f; iter != l; iter++, i++) {
         if (ByteFile::read_bytes(buf).is_err()) {
           std::generate(iter, l, [] { return 0; });
           break;
         }
         *iter = bytes_to_sample(buf);
       }
     }
   }
read_samples() [2/2]
template<typename OutIter , typename > void otto::util::SoundFile::read_samples (OutIter && iter, int n)
Definition at line 130 of file soundfile.hpp.
References bytes_to_sample(), otto::util::ByteFile::read_bytes(), and sample_size.
{
     if constexpr (std::is_pointer_v<OutIter>) {
         ByteFile::read_bytes(reinterpret_cast<std::byte*>(iter),
           n * sample_size).if_err(
             [&] (auto&& e) {
               std::generate_n(iter + e, n - e, [] { return 0; });
             });
       } else {
       bytes<sample_size> buf;
       int i = 0;
       for (auto cur = iter; i < n; iter++, i++) {
         auto r = ByteFile::read_bytes(buf);
         if (r.is_err()) {
           std::generate_n(cur, n - r.unwrap_err(), [] { return 0; });
           break;
         }
         *cur = bytes_to_sample(buf);
       }
     }
   }
replace_custom_chunk()
virtual void otto::util::SoundFile::replace_custom_chunk (std::unique_ptr< Chunk > & ptr) inline protected virtual
When extending <SoundFile>, override this function.
It should check the id of ptr, and if it matches, swap it with an instance of the correct class. If the chunk is unknown, leave it alone. After this, <Chunk::read> will be invoked on ptr.
Reimplemented in otto::util::TapeFile.
Definition at line 84 of file soundfile.hpp.
Referenced by read_file().
 {}
sample_to_bytes()
bytes<sample_size> otto::util::SoundFile::sample_to_bytes (Sample sample) inline protected
Definition at line 96 of file soundfile.hpp.
References otto::util::bytes< len >::cast().
Referenced by write_samples().
{
       bytes<sample_size> bytes;
       bytes.cast<Sample>() = sample;
       return bytes;
     }
seek()
Position otto::util::SoundFile::seek (Position p)
Definition at line 178 of file soundfile.cpp.
References audioOffset, sample_size, and otto::util::ByteFile::seek().
Referenced by position(), and read_file().
{
     return (ByteFile::seek(audioOffset + p * sample_size)
       - audioOffset) / sample_size;
   }
write_file()
void otto::util::SoundFile::write_file () override virtual
Reimplemented from otto::util::ByteFile.
Definition at line 152 of file soundfile.cpp.
References add_custom_chunks(), otto::util::SoundFile::Info::AIFF, audioOffset, otto::util::Header::chunks, otto::util::Header::format, otto::util::ByteFile::fstream, otto::util::ByteFile::Chunk::id, info, otto::util::ByteFile::path, otto::util::ByteFile::seek(), otto::util::ByteFile::size(), otto::util::SoundFile::Info::type, otto::util::SoundFile::Info::WAVE, and otto::util::ByteFile::Chunk::write().
{
     ByteFile::seek(0);
     Header header;
     switch (info.type) {
     case Info::Type::WAVE:
       LOG_F(INFO, "Writing Wave file: {}", path);
       LOG_F(INFO, "-------------------");
       header.id = "RIFF";
       header.format = "WAVE";
       header.chunks.push_back(std::make_unique<WAVE_fmt>());
       add_custom_chunks(header.chunks);
       header.chunks.push_back(std::make_unique<WAVE_data>());
       header.chunks.back()->size = ByteFile::size() - audioOffset;
       header.write(*this);
       LOG_F(INFO, "Wrote {} chunks", header.chunks.size());
       LOG_IF_F(ERROR, !fstream.good(), "fstream errored");
       LOG_F(INFO, "-------------------");
       break;
     case Info::Type::AIFF:
       throw "Unsupported type. Currently only wav is supported";
     }
   }
write_samples() [1/2]
template<typename InIter , typename > void otto::util::SoundFile::write_samples (InIter f, InIter l)
Definition at line 152 of file soundfile.hpp.
References sample_to_bytes(), and otto::util::ByteFile::write_bytes().
{
     if constexpr (std::is_pointer_v<InIter>) {
       ByteFile::write_bytes(reinterpret_cast<std::byte*>(f),
                             reinterpret_cast<std::byte*>(l));
     } else {
       std::for_each(f, l, [&] (Sample s) {
           ByteFile::write_bytes(sample_to_bytes(s));
         });
     }
   }
write_samples() [2/2]
template<typename InIter , typename > void otto::util::SoundFile::write_samples (InIter && i, int n)
Definition at line 164 of file soundfile.hpp.
References otto::util::for_each_n(), sample_size, sample_to_bytes(), and otto::util::ByteFile::write_bytes().
{
     if constexpr (std::is_pointer_v<InIter>) {
       ByteFile::write_bytes(reinterpret_cast<std::byte*>(i), n * sample_size);
     } else {
       for_each_n(std::forward<InIter>(i), n, [&] (Sample s) {
           ByteFile::write_bytes(sample_to_bytes(s));
         });
     }
   }
Friends And Related Function Documentation
Header
friend struct Header friend
Definition at line 86 of file soundfile.hpp.
WAVE_data
friend struct WAVE_data friend
Definition at line 88 of file soundfile.hpp.
WAVE_fmt
friend struct WAVE_fmt friend
Definition at line 87 of file soundfile.hpp.
Member Data Documentation
audioOffset
ByteFile::Position otto::util::SoundFile::audioOffset {0} protected
Definition at line 90 of file soundfile.hpp.
Referenced by length(), position(), seek(), and write_file().
info
struct otto::util::SoundFile::Info otto::util::SoundFile::info
Referenced by read_file(), otto::util::TapeFile::TapeFile(), and write_file().
sample_size
constexpr std::size_t otto::util::SoundFile::sample_size = sizeof(Sample) static
Size in bytes of one sample.
Definition at line 20 of file soundfile.hpp.
Referenced by length(), position(), read_samples(), seek(), and write_samples().
The documentation for this class was generated from the following files:
/home/topisani/dev/OTTO/src/util/soundfile.hpp
/home/topisani/dev/OTTO/src/util/soundfile.cpp