OTTO: ChorusComb< Tv, Si, Tp, Td > Class Template Reference
ChorusComb< Tv, Si, Tp, Td > Class Template Reference
Detailed Description
template<class Tv = gam::real, template< class > class Si = gam::ipl::Linear, class Tp = gam::real, class Td = gam::DomainObserver>
class ChorusComb< Tv, Si, Tp, Td >
Variable length delay-line with feedback and/or feedforward.
The general comb filter transfer function provides N evenly spaced poles and/or zeroes around the unit circle. Feedback and feedforward produce evenly spaced resonances and notches, respectively, in the frequency response. Positive feeds result in even harmonics and negative feeds give odd harmonics. If the feedback and feedforward amounts are inverses of each other, an Nth order all-pass filter results. Comb filters are stable as long as |feedback| < 1.
Template Parameters
Tv Value (sample) type
Si Interpolation strategy
Tp Parameter type
Td Domain type
Definition at line 27 of file chorus.hpp.
#include <chorus.hpp>
Public Member Functions
ChorusComb (float delayMax, const Tp &ffd=Tp(0), const Tp &fbk=Tp(0))
void decay (float units, float end=0.001f)
Set number of units for response to decay to end value.
void allPass (const Tp &v)
Sets feedback to argument and feedforward to argument negated.
void fbk (const Tp &v)
Set feedback amount, in (-1, 1)
void ffd (const Tp &v)
Set feedforward amount [-1, 1].
void feeds (const Tp &fwd, const Tp &bwd)
void set (float delay, const Tp &ffd, const Tp &fbk)
Set several parameters.
void set_delays (float d0, float d1, float d2, float d3)
void operator() (const Tv &in, Tv &oL, Tv &oR)
Returns next filtered value.
float norm () const
Get unity gain scale factor.
float normFbk () const
Get unity gain scale factor due to feedback.
float normFfd () const
Get unity gain scale factor due to feedforward.
Tp ffd () const
Get feedforward amount.
Tp fbk () const
Get feedback amount.
Protected Attributes
Tp mFFD
Tp mFBK
Constructor & Destructor Documentation
ChorusComb()
template<class Tv = gam::real, template< class > class Si = gam::ipl::Linear, class Tp = gam::real, class Td = gam::DomainObserver> TM1 ChorusComb< Tv, Si, Tp, Td >::ChorusComb (float delayMax, const Tp & ffd = Tp(0), const Tp & fbk = Tp(0))
Parameters
[in] delay Delay length. The size of the delay line will be the smallest possible power of two.
[in] N Number of taps on the delay line.
[in] ffd Feedforward amount, in [-1, 1]
[in] fbk Feedback amount, in (-1, 1)
Definition at line 72 of file chorus.hpp.
Member Function Documentation
decay()
template<class Tv = gam::real, template< class > class Si = gam::ipl::Linear, class Tp = gam::real, class Td = gam::DomainObserver> TM1 void ChorusComb< Tv, Si, Tp, Td >::decay (float units, float end = 0.001f)
Set number of units for response to decay to end value.
The sign of the decay length determines the sign of the feedback coefficient. The default end value of 0.001 (-60 dB) is the reverberation time of the filter. Setting the decay amount effects only the feedback value. The decay must be updated whenever the delay length of the filter changes.
Definition at line 82 of file chorus.hpp.
allPass()
template<class Tv = gam::real, template< class > class Si = gam::ipl::Linear, class Tp = gam::real, class Td = gam::DomainObserver> TM1 void ChorusComb< Tv, Si, Tp, Td >::allPass (const Tp & v)
Sets feedback to argument and feedforward to argument negated.
Definition at line 91 of file chorus.hpp.
fbk() [1/2]
template<class Tv = gam::real, template< class > class Si = gam::ipl::Linear, class Tp = gam::real, class Td = gam::DomainObserver> TM1 void ChorusComb< Tv, Si, Tp, Td >::fbk (const Tp & v)
Set feedback amount, in (-1, 1)
Definition at line 92 of file chorus.hpp.
Referenced by ChorusEffect< T >::fbk().
ffd() [1/2]
template<class Tv = gam::real, template< class > class Si = gam::ipl::Linear, class Tp = gam::real, class Td = gam::DomainObserver> TM1 void ChorusComb< Tv, Si, Tp, Td >::ffd (const Tp & v)
Set feedforward amount [-1, 1].
Definition at line 93 of file chorus.hpp.
Referenced by ChorusEffect< T >::ffd().
feeds()
template<class Tv = gam::real, template< class > class Si = gam::ipl::Linear, class Tp = gam::real, class Td = gam::DomainObserver> void ChorusComb< Tv, Si, Tp, Td >::feeds (const Tp & fwd, const Tp & bwd)
Definition at line 52 of file chorus.hpp.
set()
template<class Tv = gam::real, template< class > class Si = gam::ipl::Linear, class Tp = gam::real, class Td = gam::DomainObserver> TM1 void ChorusComb< Tv, Si, Tp, Td >::set (float delay, const Tp & ffd, const Tp & fbk)
Set several parameters.
Definition at line 94 of file chorus.hpp.
set_delays()
template<class Tv = gam::real, template< class > class Si = gam::ipl::Linear, class Tp = gam::real, class Td = gam::DomainObserver> TM1 void ChorusComb< Tv, Si, Tp, Td >::set_delays (float d0, float d1, float d2, float d3)
Definition at line 87 of file chorus.hpp.
Referenced by ChorusEffect< T >::modulate().
operator()()
template<class Tv = gam::real, template< class > class Si = gam::ipl::Linear, class Tp = gam::real, class Td = gam::DomainObserver> TM1 void ChorusComb< Tv, Si, Tp, Td >::operator() (const Tv & in, Tv & oL, Tv & oR)
Returns next filtered value.
Definition at line 76 of file chorus.hpp.
norm()
template<class Tv = gam::real, template< class > class Si = gam::ipl::Linear, class Tp = gam::real, class Td = gam::DomainObserver> TM1 float ChorusComb< Tv, Si, Tp, Td >::norm () const
Get unity gain scale factor.
Definition at line 98 of file chorus.hpp.
normFbk()
template<class Tv = gam::real, template< class > class Si = gam::ipl::Linear, class Tp = gam::real, class Td = gam::DomainObserver> TM1 float ChorusComb< Tv, Si, Tp, Td >::normFbk () const
Get unity gain scale factor due to feedback.
Definition at line 99 of file chorus.hpp.
normFfd()
template<class Tv = gam::real, template< class > class Si = gam::ipl::Linear, class Tp = gam::real, class Td = gam::DomainObserver> TM1 float ChorusComb< Tv, Si, Tp, Td >::normFfd () const
Get unity gain scale factor due to feedforward.
Definition at line 100 of file chorus.hpp.
ffd() [2/2]
template<class Tv = gam::real, template< class > class Si = gam::ipl::Linear, class Tp = gam::real, class Td = gam::DomainObserver> TM1 Tp ChorusComb< Tv, Si, Tp, Td >::ffd () const
Get feedforward amount.
Definition at line 97 of file chorus.hpp.
Referenced by ChorusComb< T, gam::ipl::Linear >::feeds().
fbk() [2/2]
template<class Tv = gam::real, template< class > class Si = gam::ipl::Linear, class Tp = gam::real, class Td = gam::DomainObserver> TM1 Tp ChorusComb< Tv, Si, Tp, Td >::fbk () const
Get feedback amount.
Definition at line 96 of file chorus.hpp.
Referenced by ChorusComb< T, gam::ipl::Linear >::feeds().
Member Data Documentation
mFFD
template<class Tv = gam::real, template< class > class Si = gam::ipl::Linear, class Tp = gam::real, class Td = gam::DomainObserver> Tp ChorusComb< Tv, Si, Tp, Td >::mFFD protected
Definition at line 66 of file chorus.hpp.
mFBK
template<class Tv = gam::real, template< class > class Si = gam::ipl::Linear, class Tp = gam::real, class Td = gam::DomainObserver> Tp ChorusComb< Tv, Si, Tp, Td >::mFBK protected
Definition at line 66 of file chorus.hpp.
The documentation for this class was generated from the following file:
/home/travis/build/topisani/OTTO/src/util/dsp/chorus.hpp