OTTO: /home/travis/build/topisani/OTTO/src/util/enum.hpp File Reference
enum.hpp File Reference
#include <array>
#include <better_enum.hpp>
#include <json.hpp>
#include "util/type_traits.hpp"
Classes
struct otto::util::enum_map< Enum, T >
Namespaces
otto
The property system.
otto::util
Functions
template<typename Enum >
auto serialize (const Enum &e) -> std::enable_if_t< otto::util::BetterEnum::is< Enum >, nlohmann::json >
Serialize a BetterEnum to json.
template<typename Enum >
auto deserialize (Enum &p, const nlohmann::json &j) -> std::enable_if_t< otto::util::BetterEnum::is< Enum >, nlohmann::json >
Deserialize a BetterEnum from json.
Function Documentation
serialize()
template<typename Enum > auto serialize (const Enum & e) -> std::enable_if_t<otto::util::BetterEnum::is<Enum>, nlohmann::json>
Serialize a BetterEnum to json.
Definition at line 98 of file enum.hpp.
Referenced by otto::core::props::serialize(), and to_json().
deserialize()
template<typename Enum > auto deserialize (Enum & p, const nlohmann::json & j) -> std::enable_if_t<otto::util::BetterEnum::is<Enum>, nlohmann::json>
Deserialize a BetterEnum from json.
Definition at line 106 of file enum.hpp.
References std::string::c_str().
Referenced by otto::core::props::deserialize(), and from_json().