OTTO: Reflection
Reflection
Detailed Description
The OTTO reflection library is based on MetaStuff by Elias daler.
You register classes for reflection using the macros DECL_REFLECTION or DECL_REFLECTION_OUTSIDE, or by manually declaring the member reflect_members or nonmember register_members, along with reflect_name and register_name
Reflection is mainly used for serialization, using otto::util::serialize and otto::util::deserialize, but can be used for other purposes as well. The main function is reflect::for_all_members, which can be used to iterate over members of a struct.
Classes
struct otto::reflect::MemberAccessor< Class, T, AT, Data >
struct otto::reflect::MemberAccessor< Class, T, AccessorType::ReadOnly, Data >
struct otto::reflect::MemberAccessor< Class, T, AccessorType::ReadWrite, Data >
struct otto::reflect::MemberAccessor< Class, T, AccessorType::MutableRef, Data >
struct otto::reflect::Member< Class, T, AT, AccessorData >
A representation of a registered member.
struct otto::reflect::type_list< Args >
type_list is array of types
struct otto::reflect::_has_reflect_member< T >
struct otto::reflect::constructor_args< T >
Macros
#define DECL_REFLECTION_OUTSIDE(Type, ...)
#define DECL_REFLECTION(Type, ...)
#define DECL_REFLECTION_EMPTY(Type)
Typedefs
template<typename MemberType >
using otto::reflect::get_member_type = typename std::decay_t< MemberType >::member_type
MemberType is Member<T, Class>
template<typename T >
using otto::reflect::constructor_arguments = typename constructor_args< T >::types
Enumerations
enum otto::reflect::AccessorType { otto::reflect::AccessorType::ReadOnly, otto::reflect::AccessorType::ReadWrite, otto::reflect::AccessorType::MutableRef }
Functions
template<typename Class , typename Callable , typename = std::enable_if_t<mpark::lib::is_invocable<Callable, Class&>::value>>
constexpr auto otto::reflect::member (util::string_ref, Callable &&ref_getter)
template<typename Class , typename Getter , typename Setter , typename = std::enable_if_t<mpark::lib::is_invocable<Getter, const Class&>::value>>
constexpr auto otto::reflect::member (util::string_ref, Getter &&getter, Setter &&setter)
template<typename... Args>
constexpr auto otto::reflect::members (Args &&... args)
template<typename Class , typename = std::enable_if_t<_has_reflect_member<Class>::value>>
constexpr auto otto::reflect::register_members ()
function used for registration of classes by user
template<typename Class , typename = std::enable_if_t<_has_reflect_member<Class>::value>>
constexpr util::string_ref otto::reflect::register_name ()
function used for registration of class name by user
template<typename Class >
constexpr util::string_ref otto::reflect::get_name ()
returns set name for class
template<typename Class >
constexpr std::size_t otto::reflect::get_member_count ()
returns the number of registered members of the class
template<typename Class >
constexpr const auto & otto::reflect::get_members ()
returns std::tuple of Members
template<typename Class >
constexpr bool otto::reflect::is_registered ()
Check if class has registerMembers<T> specialization (has been registered)
template<typename Class >
constexpr bool otto::reflect::ctor_registered ()
Check if Class has non-default ctor registered.
template<typename Class >
bool otto::reflect::has_member (const char *name)
Check if class T has member.
template<typename Class , typename F , typename = std::enable_if_t<is_registered<Class>()>>
void otto::reflect::for_all_members (F &&f)
template<typename Class , typename F , typename = std::enable_if_t<!is_registered<Class>()>, typename = void>
void otto::reflect::for_all_members (F &&f)
version for non-registered classes (to generate less template stuff)
template<typename Class , typename T , typename F >
void otto::reflect::for_member (const char *name, F &&f)
Do F for member named 'name' with type T. It's important to pass correct type of the member.
template<typename T , typename Class >
T otto::reflect::get_member_value (Class &obj, const char *name)
Get value of the member named 'name'.
template<typename T , typename Class , typename V , typename = std::enable_if_t<std::is_constructible<T, V>::value>>
void otto::reflect::set_member_value (Class &obj, const char *name, V &&value)
Set value of the member named 'name'.
Class Documentation
otto::reflect::MemberAccessor
struct otto::reflect::MemberAccessor
otto::reflect::MemberAccessor< Class, T, AccessorType::ReadOnly, Data >
struct otto::reflect::MemberAccessor< Class, T, AccessorType::ReadOnly, Data >
Public Member Functions
constexpr MemberAccessor (util::function_ptr< const T &, const Data &, const Class & > getter, Data const &data)
Public Attributes
util::function_ptr< const T &, const Data &, const Class & > get_const
Data data
Constructor & Destructor Documentation
MemberAccessor()
template<typename Class , typename T , typename Data > constexpr otto::reflect::MemberAccessor< Class, T, AccessorType::ReadOnly, Data >::MemberAccessor (util::function_ptr< const T &, const Data &, const Class & > getter, Data const & data) constexpr
Definition at line 30 of file member.hpp.
Member Data Documentation
get_const
template<typename Class , typename T , typename Data > util::function_ptr<const T&, const Data&, const Class&> otto::reflect::MemberAccessor< Class, T, AccessorType::ReadOnly, Data >::get_const
Definition at line 34 of file member.hpp.
data
template<typename Class , typename T , typename Data > Data otto::reflect::MemberAccessor< Class, T, AccessorType::ReadOnly, Data >::data
Definition at line 35 of file member.hpp.
otto::reflect::MemberAccessor< Class, T, AccessorType::ReadWrite, Data >
struct otto::reflect::MemberAccessor< Class, T, AccessorType::ReadWrite, Data >
Public Member Functions
constexpr MemberAccessor (util::function_ptr< const T &, const Data &, const Class & > get, util::function_ptr< void, const Data &, Class &, const T & > set, const Data &data)
Public Attributes
util::function_ptr< const T &, const Data &, const Class & > get_const
util::function_ptr< void, const Data &, Class &, const T & > set
Data data
Constructor & Destructor Documentation
MemberAccessor()
template<typename Class , typename T , typename Data > constexpr otto::reflect::MemberAccessor< Class, T, AccessorType::ReadWrite, Data >::MemberAccessor (util::function_ptr< const T &, const Data &, const Class & > get, util::function_ptr< void, const Data &, Class &, const T & > set, const Data & data) constexpr
Definition at line 40 of file member.hpp.
Member Data Documentation
get_const
template<typename Class , typename T , typename Data > util::function_ptr<const T&, const Data&, const Class&> otto::reflect::MemberAccessor< Class, T, AccessorType::ReadWrite, Data >::get_const
Definition at line 45 of file member.hpp.
set
template<typename Class , typename T , typename Data > util::function_ptr<void, const Data&, Class&, const T&> otto::reflect::MemberAccessor< Class, T, AccessorType::ReadWrite, Data >::set
Definition at line 46 of file member.hpp.
data
template<typename Class , typename T , typename Data > Data otto::reflect::MemberAccessor< Class, T, AccessorType::ReadWrite, Data >::data
Definition at line 47 of file member.hpp.
otto::reflect::MemberAccessor< Class, T, AccessorType::MutableRef, Data >
struct otto::reflect::MemberAccessor< Class, T, AccessorType::MutableRef, Data >
Public Member Functions
constexpr MemberAccessor (util::function_ptr< T &, const Data &, Class & > get, util::function_ptr< const T &, const Data &, const Class & > get_const, const Data &data)
Public Attributes
util::function_ptr< T &, const Data &, Class & > get
util::function_ptr< const T &, const Data &, const Class & > get_const
Data data
Constructor & Destructor Documentation
MemberAccessor()
template<typename Class , typename T , typename Data > constexpr otto::reflect::MemberAccessor< Class, T, AccessorType::MutableRef, Data >::MemberAccessor (util::function_ptr< T &, const Data &, Class & > get, util::function_ptr< const T &, const Data &, const Class & > get_const, const Data & data) constexpr
Definition at line 52 of file member.hpp.
Member Data Documentation
get
template<typename Class , typename T , typename Data > util::function_ptr<T&, const Data&, Class&> otto::reflect::MemberAccessor< Class, T, AccessorType::MutableRef, Data >::get
Definition at line 57 of file member.hpp.
get_const
template<typename Class , typename T , typename Data > util::function_ptr<const T&, const Data&, const Class&> otto::reflect::MemberAccessor< Class, T, AccessorType::MutableRef, Data >::get_const
Definition at line 58 of file member.hpp.
data
template<typename Class , typename T , typename Data > Data otto::reflect::MemberAccessor< Class, T, AccessorType::MutableRef, Data >::data
Definition at line 59 of file member.hpp.
otto::reflect::Member
struct otto::reflect::Member
Public Types
using Accessor = MemberAccessor< Class, T, AT, AccessorData >
using class_type = Class
using member_type = T
using type = T
Public Member Functions
constexpr Member (util::string_ref name, const Accessor &ma)
constexpr util::string_ref get_name () const
constexpr const T & get (const Class &obj) const
constexpr decltype(auto) get (Class &obj) const
constexpr T & get_ref (Class &obj) const
template<typename V , typename = std::enable_if_t<std::is_constructible<T, V>::value>>
constexpr void set (Class &obj, V &&value) const
Static Public Member Functions
constexpr static bool has_setter () noexcept
constexpr static bool can_get_ref () noexcept
Member Typedef Documentation
Accessor
template<typename Class, typename T, AccessorType AT, typename AccessorData> using otto::reflect::Member< Class, T, AT, AccessorData >::Accessor = MemberAccessor<Class, T, AT, AccessorData>
Definition at line 68 of file member.hpp.
class_type
template<typename Class, typename T, AccessorType AT, typename AccessorData> using otto::reflect::Member< Class, T, AT, AccessorData >::class_type = Class
Definition at line 69 of file member.hpp.
member_type
template<typename Class, typename T, AccessorType AT, typename AccessorData> using otto::reflect::Member< Class, T, AT, AccessorData >::member_type = T
Definition at line 70 of file member.hpp.
type
template<typename Class, typename T, AccessorType AT, typename AccessorData> using otto::reflect::Member< Class, T, AT, AccessorData >::type = T
Definition at line 71 of file member.hpp.
Constructor & Destructor Documentation
Member()
template<typename Class , typename T , AccessorType AT, typename AD > constexpr otto::reflect::Member< Class, T, AT, AD >::Member (util::string_ref name, const Accessor & ma) constexpr
Definition at line 11 of file member.inl.
Member Function Documentation
get_name()
template<typename Class, typename T, AccessorType AT, typename AccessorData> constexpr util::string_ref otto::reflect::Member< Class, T, AT, AccessorData >::get_name () const constexpr
Definition at line 75 of file member.hpp.
has_setter()
template<typename Class, typename T, AccessorType AT, typename AccessorData> constexpr static bool otto::reflect::Member< Class, T, AT, AccessorData >::has_setter () static constexpr noexcept
Definition at line 79 of file member.hpp.
References otto::reflect::ReadOnly.
can_get_ref()
template<typename Class, typename T, AccessorType AT, typename AccessorData> constexpr static bool otto::reflect::Member< Class, T, AT, AccessorData >::can_get_ref () static constexpr noexcept
Definition at line 83 of file member.hpp.
References otto::reflect::MutableRef.
get() [1/2]
template<typename Class , typename T , AccessorType AT, typename AD > constexpr const T & otto::reflect::Member< Class, T, AT, AD >::get (const Class & obj) const constexpr
Definition at line 16 of file member.inl.
get() [2/2]
template<typename Class, typename T, AccessorType AT, typename AccessorData> constexpr decltype(auto) otto::reflect::Member< Class, T, AT, AccessorData >::get (Class & obj) const constexpr
get_ref()
template<typename Class , typename T , AccessorType AT, typename AD > constexpr T & otto::reflect::Member< Class, T, AT, AD >::get_ref (Class & obj) const constexpr
Definition at line 30 of file member.inl.
set()
template<typename Class , typename T , AccessorType AT, typename AD > template<typename V , typename > constexpr void otto::reflect::Member< Class, T, AT, AD >::set (Class & obj, V && value) const constexpr
Definition at line 38 of file member.inl.
otto::reflect::type_list
struct otto::reflect::type_list
Public Types
template<std::size_t N>
using type = std::tuple_element_t< N, std::tuple< Args... > >
using indices = std::index_sequence_for< Args... >
Static Public Attributes
static const size_t size = sizeof...(Args)
Member Typedef Documentation
type
template<typename... Args> template<std::size_t N> using otto::reflect::type_list< Args >::type = std::tuple_element_t<N, std::tuple<Args...> >
Definition at line 21 of file reflect.hpp.
indices
template<typename... Args> using otto::reflect::type_list< Args >::indices = std::index_sequence_for<Args...>
Definition at line 22 of file reflect.hpp.
Member Data Documentation
size
template<typename... Args> const size_t otto::reflect::type_list< Args >::size = sizeof...(Args) static
Definition at line 23 of file reflect.hpp.
otto::reflect::_has_reflect_member
struct otto::reflect::_has_reflect_member
Static Public Member Functions
template<typename C >
static std::true_type test (decltype(&C::reflect_members))
template<typename C >
static std::false_type test (...)
Static Public Attributes
static constexpr bool value = decltype(test<T>(nullptr))::value
Member Function Documentation
test() [1/2]
template<typename T > template<typename C > static std::true_type otto::reflect::_has_reflect_member< T >::test (decltype &::reflect_members) static
test() [2/2]
template<typename T > template<typename C > static std::false_type otto::reflect::_has_reflect_member< T >::test (...) static
Member Data Documentation
value
template<typename T > constexpr bool otto::reflect::_has_reflect_member< T >::value = decltype(test<T>(nullptr))::value static constexpr
Definition at line 37 of file reflect.hpp.
otto::reflect::constructor_args
struct otto::reflect::constructor_args
Class Members
typedef type_list<> types
Macro Definition Documentation
DECL_REFLECTION_OUTSIDE
#define DECL_REFLECTION_OUTSIDE (Type, ...)
Value:
namespace otto::reflect {                                                                        \
    template<>                                                                                     \
    constexpr auto register_members<Type>()                                                        \
    {                                                                                              \
      return ::otto::reflect::members(                                                             \
        FOR_EACH_LAST_SEP(_REFLECT_STRUCT_ARGS, (Type), __VA_ARGS__));                             \
    }                                                                                              \
    template<>                                                                                     \
    constexpr ::otto::util::string_ref register_name<Type>()                                                \
    {                                                                                              \
      return #Type                                                                                 \
    }                                                                                              \
  }
Definition at line 20 of file reflection.hpp.
DECL_REFLECTION
#define DECL_REFLECTION (Type, ...)
Value:
static constexpr auto reflect_members()                                                          \
  {                                                                                                \
    return ::otto::reflect::members(FOR_EACH_LAST_SEP(_REFLECT_STRUCT_ARGS, (Type), __VA_ARGS__)); \
  }                                                                                                \
  static constexpr ::otto::util::string_ref reflect_name()                                                  \
  {                                                                                                \
    return #Type;                                                                                  \
  }
Used inside a class to register its members
Definition at line 37 of file reflection.hpp.
DECL_REFLECTION_EMPTY
#define DECL_REFLECTION_EMPTY (Type)
Value:
static constexpr auto reflect_members()                                                          \
  {                                                                                                \
    return ::otto::reflect::members();                                                             \
  }                                                                                                \
  static constexpr ::otto::util::string_ref reflect_name()                                                  \
  {                                                                                                \
    return #Type;                                                                                  \
  }
Definition at line 48 of file reflection.hpp.
Typedef Documentation
get_member_type
template<typename MemberType > using otto::reflect::get_member_type = typedef typename std::decay_t<MemberType>::member_type
MemberType is Member<T, Class>
Definition at line 21 of file member.hpp.
constructor_arguments
template<typename T > using otto::reflect::constructor_arguments = typedef typename constructor_args<T>::types
Definition at line 81 of file reflect.hpp.
Enumeration Type Documentation
AccessorType
enum otto::reflect::AccessorType strong
Enumerator
ReadOnly
ReadWrite
MutableRef
Definition at line 23 of file member.hpp.
Function Documentation
member() [1/2]
template<typename Class , typename Callable , typename = std::enable_if_t<mpark::lib::is_invocable<Callable, Class&>::value>> constexpr auto otto::reflect::member (util::string_ref name, Callable && ref_getter) constexpr
Definition at line 50 of file member.inl.
Referenced by otto::util::deserialize(), otto::reflect::for_member(), otto::reflect::get_member_value(), otto::reflect::has_member(), otto::util::serialize(), and otto::reflect::set_member_value().
member() [2/2]
template<typename Class , typename Getter , typename Setter , typename = std::enable_if_t<mpark::lib::is_invocable<Getter, const Class&>::value>> constexpr auto otto::reflect::member (util::string_ref name, Getter && getter, Setter && setter) constexpr
Definition at line 72 of file member.inl.
References std::make_pair(), and otto::reflect::ReadWrite.
members()
template<typename... Args> constexpr auto otto::reflect::members (Args &&... args) constexpr
Definition at line 12 of file reflect.inl.
References std::make_tuple().
Referenced by otto::reflect::get_members().
register_members()
template<typename Class , typename = std::enable_if_t<_has_reflect_member<Class>::value>> constexpr auto otto::reflect::register_members () constexpr
function used for registration of classes by user
Definition at line 42 of file reflect.hpp.
register_name()
template<typename Class , typename = std::enable_if_t<_has_reflect_member<Class>::value>> constexpr util::string_ref otto::reflect::register_name () constexpr
function used for registration of class name by user
Definition at line 49 of file reflect.hpp.
get_name()
template<typename Class > constexpr util::string_ref otto::reflect::get_name () constexpr
returns set name for class
Definition at line 33 of file reflect.inl.
get_member_count()
template<typename Class > constexpr std::size_t otto::reflect::get_member_count () constexpr
returns the number of registered members of the class
Definition at line 39 of file reflect.inl.
get_members()
template<typename Class > constexpr const auto & otto::reflect::get_members () constexpr
returns std::tuple of Members
Definition at line 45 of file reflect.inl.
References otto::reflect::members().
is_registered()
template<typename Class > constexpr bool otto::reflect::is_registered () constexpr
Check if class has registerMembers<T> specialization (has been registered)
Definition at line 57 of file reflect.inl.
ctor_registered()
template<typename Class > constexpr bool otto::reflect::ctor_registered () constexpr
Check if Class has non-default ctor registered.
Check if user registered non default constructor.
Definition at line 64 of file reflect.inl.
has_member()
template<typename Class > bool otto::reflect::has_member (const char * name)
Check if class T has member.
Definition at line 70 of file reflect.inl.
References otto::reflect::member().
for_all_members() [1/2]
template<typename Class , typename F , typename = std::enable_if_t<is_registered<Class>()>> void otto::reflect::for_all_members (F && f)
Definition at line 82 of file reflect.inl.
for_all_members() [2/2]
template<typename Class , typename F , typename = std::enable_if_t<!is_registered<Class>()>, typename = void> void otto::reflect::for_all_members (F && f)
version for non-registered classes (to generate less template stuff)
Definition at line 89 of file reflect.inl.
for_member()
template<typename Class , typename T , typename F > void otto::reflect::for_member (const char * name, F && f)
Do F for member named 'name' with type T. It's important to pass correct type of the member.
Definition at line 95 of file reflect.inl.
References otto::reflect::member().
get_member_value()
template<typename T , typename Class > T otto::reflect::get_member_value (Class & obj, const char * name)
Get value of the member named 'name'.
Definition at line 107 of file reflect.inl.
References otto::reflect::member().
set_member_value()
template<typename T , typename Class , typename V , typename = std::enable_if_t<std::is_constructible<T, V>::value>> void otto::reflect::set_member_value (Class & obj, const char * name, V && value)
Set value of the member named 'name'.
Definition at line 116 of file reflect.inl.
References otto::reflect::member().