OTTO: /home/topisani/dev/OTTO/src/main.cpp File Reference
main.cpp File Reference
#include <csignal>
#include "util/timer.hpp"
#include "core/audio/midi.hpp"
#include "core/globals.hpp"
#include "services/engines.hpp"
#include "services/presets.hpp"
#include "services/ui.hpp"
#include "services/logger.hpp"
#include "services/state.hpp"
#include "services/audio.hpp"
Functions
void cleanup ()
int handle_exception (const char *e)
int handle_exception (std::exception &e)
int handle_exception ()
int main (int argc, char *argv[])
Function Documentation
cleanup()
void cleanup ()
Definition at line 80 of file main.cpp.
References otto::service::state::save(), otto::util::timer::save_data(), otto::service::audio::shutdown(), and otto::service::engines::shutdown().
Referenced by handle_exception(), and main().
handle_exception() [1/3]
int handle_exception (const char * e)
Definition at line 57 of file main.cpp.
References cleanup(), and LOGE.
Referenced by main().
handle_exception() [2/3]
int handle_exception (std::exception & e)
Definition at line 65 of file main.cpp.
References cleanup(), and LOGE.
handle_exception() [3/3]
int handle_exception ()
Definition at line 73 of file main.cpp.
References cleanup(), and LOGE.
main()
int main (int argc, char * argv[])
Definition at line 22 of file main.cpp.
References cleanup(), handle_exception(), otto::global::handle_signal(), otto::service::logger::init(), otto::service::presets::init(), otto::service::engines::init(), otto::service::audio::init(), otto::service::ui::init(), otto::service::state::load(), otto::service::ui::main_ui_loop(), otto::service::audio::start(), and otto::service::engines::start().