OTTO: otto::core::audio::detail Namespace Reference
otto::core::audio::detail Namespace Reference
Functions
void register_faust_wrapper_events (dsp &_dsp, FaustOptions &opts)
std::unique_ptr< ui::Screen > make_envelope_screen (EnvelopeProps &props)
std::unique_ptr< ui::Screen > make_settings_screen (SettingsProps &props)
Function Documentation
make_envelope_screen()
std::unique_ptr< ui::Screen > otto::core::audio::detail::make_envelope_screen (EnvelopeProps & props)
Definition at line 32 of file voice_manager.cpp.
     {
       return std::make_unique<EnvelopeScreen>(props);
     }
make_settings_screen()
std::unique_ptr< ui::Screen > otto::core::audio::detail::make_settings_screen (SettingsProps & props)
Definition at line 37 of file voice_manager.cpp.
     {
       return std::make_unique<SettingsScreen>(props);
     }
register_faust_wrapper_events()
void otto::core::audio::detail::register_faust_wrapper_events (dsp & _dsp, FaustOptions & opts)
Definition at line 8 of file faust.cpp.
References otto::core::audio::FaustOptions::client, otto::service::audio::events::pre_init(), otto::service::audio::samplerate(), otto::service::audio::events::samplerate_change(), and otto::util::Event< Args >::subscribe().
Referenced by otto::core::audio::FaustWrapper< 0, 1 >::FaustWrapper().
   {
     service::audio::events::pre_init().subscribe([&]() {
         _dsp.init(service::audio::samplerate());
       _dsp.buildUserInterface(&opts);
     });
     service::audio::events::samplerate_change().subscribe([&](int samplerate) {
       _dsp.instanceInit(samplerate);
       opts.client.refresh_links();
     });
   }