OTTO: otto::nvg::ColorConverter Namespace Reference
otto::nvg::ColorConverter Namespace Reference
Classes
struct Rgb
struct Rgba
Typedefs
using byte = unsigned char
Functions
double clamp (double x, double a, double b)
double threeway_max (double a, double b, double c)
double threeway_min (double a, double b, double c)
double hue2rgb (double h, double m1, double m2)
Rgb hslToRgb (double h, double s, double l)
Converts an HSL color value to RGB.
void rgbToHsl (byte r, byte g, byte b, double hsl[])
Converts an RGB color value to HSL.
void rgbToHsv (byte r, byte g, byte b, double hsv[])
Converts an RGB color value to HSV.
void hsvToRgb (double h, double s, double v, byte rgb[])
Converts an HSV color value to RGB.
Typedef Documentation
byte
using otto::nvg::ColorConverter::byte = typedef unsigned char
Definition at line 9 of file ColorConverter.hpp.
Function Documentation
clamp()
double otto::nvg::ColorConverter::clamp (double x, double a, double b)
Definition at line 21 of file ColorConverter.hpp.
Referenced by otto::util::audio::Section< int >::clamp(), otto::util::audio::Graph::clip(), otto::nvg::Color::dim(), hslToRgb(), otto::core::ui::widgets::Waveform< Container >::point(), otto::core::ui::widgets::Waveform< Container >::point_ceil(), otto::core::ui::widgets::Waveform< Container >::point_floor(), and otto::util::math::split_values().
threeway_max()
double otto::nvg::ColorConverter::threeway_max (double a, double b, double c)
Definition at line 26 of file ColorConverter.hpp.
References std::max().
threeway_min()
double otto::nvg::ColorConverter::threeway_min (double a, double b, double c)
Definition at line 31 of file ColorConverter.hpp.
References std::min().
hue2rgb()
double otto::nvg::ColorConverter::hue2rgb (double h, double m1, double m2)
Definition at line 36 of file ColorConverter.hpp.
Referenced by hslToRgb().
hslToRgb()
Rgb otto::nvg::ColorConverter::hslToRgb (double h, double s, double l)
Converts an HSL color value to RGB.
Conversion formula adapted from http://en.wikipedia.org/wiki/HSL_color_space. Assumes h, s, and l are contained in the set [0, 1] and returns r, g, and b in the set [0, 255].
Parameters
double h The hue
double s The saturation
double l The lightness
Returns
Rgb The RGB representation
Definition at line 61 of file ColorConverter.hpp.
References clamp(), hue2rgb(), and std::modf().
Referenced by otto::nvg::Color::createWidthHSL().
rgbToHsl()
void otto::nvg::ColorConverter::rgbToHsl (byte r, byte g, byte b, double hsl[])
Converts an RGB color value to HSL.
Conversion formula adapted from http://en.wikipedia.org/wiki/HSL_color_space. Assumes r, g, and b are contained in the set [0, 255] and returns h, s, and l in the set [0, 1].
Parameters
byte r The red color value
byte g The green color value
byte b The blue color value
double hsl[] The HSL representation
Definition at line 90 of file ColorConverter.hpp.
rgbToHsv()
void otto::nvg::ColorConverter::rgbToHsv (byte r, byte g, byte b, double hsv[])
Converts an RGB color value to HSV.
Conversion formula adapted from http://en.wikipedia.org/wiki/HSV_color_space. Assumes r, g, and b are contained in the set [0, 255] and returns h, s, and v in the set [0, 1].
Parameters
byte r The red color value
byte g The green color value
byte b The blue color value
Returns
double hsv[] The HSV representation
Definition at line 107 of file ColorConverter.hpp.
hsvToRgb()
void otto::nvg::ColorConverter::hsvToRgb (double h, double s, double v, byte rgb[])
Converts an HSV color value to RGB.
Conversion formula adapted from http://en.wikipedia.org/wiki/HSV_color_space. Assumes h, s, and v are contained in the set [0, 1] and returns r, g, and b in the set [0, 255].
Parameters
double h The hue
double s The saturation
double v The value
Returns
byte rgb[] The RGB representation
Definition at line 123 of file ColorConverter.hpp.