OTTO: otto::service::ui::impl Namespace Reference
otto::service::ui::impl Namespace Reference
These functions are to be called only by the graphics drivers.
Functions
void draw_frame (core::ui::vg::Canvas &ctx)
Draws the current screen and overlays.
void keypress (Key key)
void rotary (RotaryEvent ev)
void keyrelease (Key key)
void flush_events ()
Actually executes the key and rotary events.
Detailed Description
These functions are to be called only by the graphics drivers.
Function Documentation
draw_frame()
void otto::service::ui::impl::draw_frame (vg::Canvas & ctx)
Draws the current screen and overlays.
Definition at line 123 of file ui.cpp.
References otto::core::ui::vg::Canvas::draw().
Referenced by otto::service::ui::main_ui_loop().
     {
       ctx.lineWidth(2);
       ctx.lineCap(vg::Canvas::LineCap::ROUND);
       ctx.lineJoin(vg::Canvas::Canvas::LineJoin::ROUND);
       cur_screen->draw(ctx);
     }
flush_events()
void otto::service::ui::impl::flush_events ()
Actually executes the key and rotary events.
Definition at line 146 of file ui.cpp.
References flush_events(), and otto::util::match().
Referenced by flush_events(), and otto::service::ui::main_ui_loop().
     {
       key_events.swap();
       for (auto& event : key_events.inner()) {
         util::match( //
           event,
           [](KeyPress ev) {
             keys[static_cast<unsigned>(ev.key)] = true;
             if (global_keypress(ev.key)) return;
             cur_screen->keypress(ev.key);
           },
           [](KeyRelease& ev) {
             keys[static_cast<unsigned>(ev.key)] = false;
             if (global_keypress(ev.key, false)) return;
             cur_screen->keyrelease(ev.key);
           });
       }
       rotary_events.swap();
       for (auto& event : rotary_events.inner()) {
         cur_screen->rotary(event);
       }
     }
keypress()
void otto::service::ui::impl::keypress (core::ui::Key key)
Dispatches to the event handler for the current screen, and handles global keys.
Can be executed from a separate thread
Definition at line 131 of file ui.cpp.
References keypress().
Referenced by otto::board::ui::handle_keyevent(), keypress(), and otto::board::ui::read_encoders().
     {
       key_events.outer().push_back(KeyPress{key});
     }
keyrelease()
void otto::service::ui::impl::keyrelease (core::ui::Key key)
Dispatches to the event handler for the current screen, and handles global keys.
Can be executed from a separate thread, but must be the same thread as keypress
Definition at line 141 of file ui.cpp.
References keyrelease().
Referenced by otto::board::ui::handle_keyevent(), and keyrelease().
     {
       key_events.outer().push_back(KeyRelease{key});
     }
rotary()
void otto::service::ui::impl::rotary (core::ui::RotaryEvent ev)
Send rotary event
Can be executed from a separate thread
Definition at line 136 of file ui.cpp.
References rotary().
Referenced by otto::board::ui::handle_keyevent(), otto::board::ui::read_encoders(), and rotary().
     {
       rotary_events.outer().push_back(ev);
     }