OTTO: otto::core::midi Namespace Reference
otto::core::midi Namespace Reference
Namespaces
detail
Classes
struct ControlChangeEvent
struct MidiEvent
struct NoteEvent
struct NoteOffEvent
struct NoteOnEvent
struct shared_vector
Typedefs
using AnyMidiEvent = mpark::variant< NoteOnEvent, NoteOffEvent, ControlChangeEvent >
Functions
constexpr int note_number (std::string_view sv) noexcept
AnyMidiEvent from_bytes (gsl::span< unsigned char > bytes, int time=0)
void generateFreqTable (double tuning=440)
constexpr const char * note_name (int key) noexcept
float note_freq (int key) noexcept
Typedef Documentation
AnyMidiEvent
using otto::core::midi::AnyMidiEvent = typedef mpark::variant<NoteOnEvent, NoteOffEvent, ControlChangeEvent>
Definition at line 159 of file midi.hpp.
Function Documentation
from_bytes()
AnyMidiEvent otto::core::midi::from_bytes (gsl::span< unsigned char > bytes, int time = 0) inline
Definition at line 161 of file midi.hpp.
References otto::core::midi::MidiEvent::ControlChange, otto::core::midi::NoteOnEvent::from_bytes(), otto::core::midi::NoteOffEvent::from_bytes(), otto::core::midi::ControlChangeEvent::from_bytes(), otto::core::midi::MidiEvent::NoteOff, and otto::core::midi::MidiEvent::NoteOn.
   {
     auto type = MidiEvent::Type(bytes[0] >> 4);
     switch (type) {
     case MidiEvent::Type::NoteOff:
       return NoteOffEvent::from_bytes(bytes, time);
     case MidiEvent::Type::NoteOn: //
       return NoteOnEvent::from_bytes(bytes, time);
     case MidiEvent::Type::ControlChange:
       return ControlChangeEvent::from_bytes(bytes, time);
     }
   }
generateFreqTable()
void otto::core::midi::generateFreqTable (double tuning = 440) inline
Definition at line 174 of file midi.hpp.
References otto::core::midi::detail::freq_table.
Referenced by otto::service::audio::init().
   {
     for (int i = 0; i < 128; i++) {
       detail::freq_table[i] = tuning * std::pow(2.0, double(i - 69) / double(12));
     }
   }
note_freq()
float otto::core::midi::note_freq (int key) inline noexcept
Definition at line 186 of file midi.hpp.
References otto::core::midi::detail::freq_table.
Referenced by otto::core::audio::VoiceManager< 6 >::process_before().
   {
     return detail::freq_table[key];
   }
note_name()
constexpr const char* otto::core::midi::note_name (int key) noexcept
Definition at line 181 of file midi.hpp.
References otto::core::midi::detail::note_names.
   {
     return detail::note_names[key];
   }
note_number()
constexpr int otto::core::midi::note_number (std::string_view sv) noexcept
Definition at line 35 of file midi.hpp.
References otto::core::midi::detail::note_names.
   {
     // std::find is not constexpr, so i roll my own
     auto iter = detail::note_names.cbegin();
     constexpr auto last = detail::note_names.cend();
     for (int i = 0; iter != last; ++i, ++iter) {
       if (*iter == sv) {
         return i;
       }
     }
     return -1;
   }