OTTO: otto::service::presets Namespace Reference
otto::service::presets Namespace Reference
Typedefs
using exception = util::as_exception< ErrorCode >
EngineManager exceptions. Contain an [ErrorCode]()
Enumerations
enum ErrorCode { ErrorCode::no_such_engine, ErrorCode::no_such_preset }
Error codes. Thrown with exceptions.
Functions
void init ()
const std::vector< std::string > & preset_names (const std::string &engine_name)
const std::string & name_of_idx (const std::string &engine_name, int idx)
int idx_of_name (const std::string &engine_name, const std::string &name)
void apply_preset (core::engines::AnyEngine &engine, const std::string &name, bool no_enable_callback)
void apply_preset (core::engines::AnyEngine &engine, int idx, bool no_enable_callback)
void load_preset_files ()
Typedef Documentation
exception
using otto::service::presets::exception = typedef util::as_exception<ErrorCode>
EngineManager exceptions. Contain an [ErrorCode]()
Definition at line 14 of file presets.hpp.
Enumeration Type Documentation
ErrorCode
enum otto::service::presets::ErrorCode strong
Error codes. Thrown with exceptions.
Enumerator
no_such_engine
no_such_preset
Definition at line 8 of file presets.hpp.
{
     no_such_engine,
     no_such_preset,
   };
Function Documentation
apply_preset() [1/2]
void otto::service::presets::apply_preset (core::engines::AnyEngine & engine, const std::string & name, bool no_enable_callback = false)
Apply preset to engine
Apply preset identified by name to engine
Exceptions
[exception]() with [ErrorCode::no_such_preset]() if no matching preset was found.
Definition at line 63 of file presets.cpp.
References otto::core::props::property_base::as(), otto::core::engines::AnyEngine::current_preset(), otto::util::find(), otto::core::engines::AnyEngine::name(), no_such_preset, otto::core::engines::AnyEngine::on_enable(), and otto::core::engines::AnyEngine::props().
Referenced by otto::core::engines::AnyEngine::from_json(), and otto::core::engines::EngineDispatcher< ET >::init().
   {
     auto& pd   = _preset_data[engine.name()];
     auto niter = util::find(pd.names, name);
     if (niter == pd.names.end()) {
       throw exception(ErrorCode::no_such_preset,
                       "No preset named '{}' for engine '{}'", name,
                       engine.name());
     }
     DLOGI("Applying preset {} to engine {}", name, engine.name());
     int idx = niter - pd.names.begin();
     engine.props().as<core::props::serializable>().from_json(pd.data[idx]);
     engine.current_preset(idx);
     if (!no_enable_callback) engine.on_enable();
   }
apply_preset() [2/2]
void otto::service::presets::apply_preset (core::engines::AnyEngine & engine, int idx, bool no_enable_callback = false)
Apply preset to engine
Apply preset identified by idx to engine
Exceptions
[exception]() with [ErrorCode::no_such_preset]() if no matching preset was found.
Definition at line 79 of file presets.cpp.
References otto::core::props::property_base::as(), otto::core::engines::AnyEngine::current_preset(), otto::core::engines::AnyEngine::name(), no_such_preset, otto::core::engines::AnyEngine::on_enable(), and otto::core::engines::AnyEngine::props().
   {
     auto& pd = _preset_data[engine.name()];
     if (idx < 0 || static_cast<std::size_t>(idx) >= pd.data.size()) {
       throw exception(ErrorCode::no_such_preset,
                       "Preset index {} is out range for engine '{}'", idx,
                       engine.name());
     }
     DLOGI("Applying preset {} to engine {}", pd.names[idx], engine.name());
     engine.props().as<core::props::serializable>().from_json(pd.data[idx]);
     engine.current_preset(idx);
     if (!no_enable_callback) engine.on_enable();
   }
idx_of_name()
int otto::service::presets::idx_of_name (const std::string & engine_name, const std::string & name)
Get the index of preset with name name
Exceptions
[exception]() with [ErrorCode::no_such_preset]() if no matching preset was found, or [ErrorCode::no_such_engine]() if no matching engine was found
Definition at line 51 of file presets.cpp.
References otto::util::find(), no_such_preset, and preset_names().
   {
     auto& names = preset_names(engine_name);
     auto found = util::find(names, name);
     if (found == names.end()) {
       throw exception(ErrorCode::no_such_preset,
                       "No preset named '{}' for engine '{}'", name,
                       engine_name);
     }
     return found - names.begin();
   }
init()
void otto::service::presets::init ()
Initialize preset manager
load_preset_files()
Definition at line 25 of file presets.cpp.
References otto::service::debug_ui::add_info(), and load_preset_files().
               {
     debug_ui::add_info(draw_debug_info);
     load_preset_files();
   }
load_preset_files()
void otto::service::presets::load_preset_files ()
(Re)load preset files
Invoked by [init](). Call to reload all preset files.
Exceptions
[filesystem::filesystem_error]()
Definition at line 93 of file presets.cpp.
References otto::util::find(), and otto::util::JsonFile::path().
Referenced by init().
   {
     LOG_SCOPE_FUNCTION(INFO);
     if (!fs::exists(presets_dir)) {
       DLOGI("Creating preset directory");
       fs::create_directories(presets_dir);
     }
     DLOGI("Loading presets");
     for (auto&& de : fs::recursive_directory_iterator(presets_dir)) {
       if (de.is_directory()) continue;
       auto filename = de.path().filename().string();
       if (filename.size() == 0 || filename.c_str()[0] == '.') continue;
       LOGI_SCOPE("Loading preset file {}", de.path());
       if (de.is_regular_file() || de.is_symlink()) {
         util::JsonFile jf{de.path()};
         jf.read();
         std::string engine = jf.data()["engine"];
         std::string name   = jf.data()["name"];
         auto& pd           = _preset_data[engine];
         if (auto found = util::find(pd.names, name); found != pd.names.end()) {
           pd.data[found - pd.names.begin()] = std::move(jf.data()["props"]);
           DLOGI("Reloaded preset '{}' for engine '{}", name, engine);
         } else {
           pd.names.push_back(name);
           pd.data.emplace_back(std::move(jf.data()["props"]));
           DLOGI("Loaded preset '{}' for engine '{}", name, engine);
         }
       }
     }
   }
name_of_idx()
const std::string & otto::service::presets::name_of_idx (const std::string & engine_name, int idx)
Get the name of preset with indx idx
Exceptions
[exception]() with [ErrorCode::no_such_preset]() if no matching preset was found, or [ErrorCode::no_such_engine]() if no matching engine was found
Definition at line 40 of file presets.cpp.
References no_such_preset, and preset_names().
Referenced by otto::core::engines::AnyEngine::to_json().
   {
     auto& names = preset_names(engine_name);
     if (idx < 0 || static_cast<std::size_t>(idx) >= names.size()) {
       throw exception(ErrorCode::no_such_preset,
                       "Preset index {} is out range for engine '{}'", idx,
                       engine_name);
     }
     return names[idx];
   }
preset_names()
const std::vector< std::string > & otto::service::presets::preset_names (const std::string & engine_name)
Get the names of presets for an engine
These presets can be applied using [apply_preset(AnyEngine&, const std::string&)]() or [apply_preset(AnyEngine&, int)]()
Exceptions
[exception]() with [ErrorCode::no_such_engine]() if no matching engine was found.
Remarks
This design is chosen so the engine manager has complete control over the actual preset data. Also it makes sense for the [otto::engines::EngineSelectorScreen](), which is probably the only place that really needs access
Definition at line 31 of file presets.cpp.
References no_such_engine.
Referenced by idx_of_name(), and name_of_idx().
   {
     auto eg_found = _preset_data.find(engine_name);
     if (eg_found == _preset_data.end()) {
       throw exception(ErrorCode::no_such_engine, "No presets for engine: {}", engine_name);
     }
     return eg_found->second.names;
   }