OTTO: otto::util::algorithm Namespace Reference
otto::util::algorithm Namespace Reference
Detailed Description
Inline namespace with algorithms similar to the ones found in the standard <algorithm> header.
Also, this namespace includes container-based wrappers for all standard algorithms. For more on those, see Container Standard Algorithms
Attention
otto::util::algorithm is an inline namespace, meaning all members can and should be accessed directly from the otto::util namespace i.e. as util::find_if(...), not util::algorithm::find_if(...). It is only a separate namespace for clarification of documentation and name resolution.
Functions
template<class StrIterator >
std::string join_strings (StrIterator b, StrIterator e, std::string_view js=", ")
Joins a sequence of strings, separating them using js
void string_replace (std::string &str, const std::string &oldStr, const std::string &newStr)
Find/Replace.
bool starts_with (std::string_view str, std::string_view prefix)
Check if string str starts with prefix
template<typename Container >
std::string join_strings (Container &&cont, std::string_view js=", ")
Joins a sequence of strings, separating them using js
template<int n, class Func >
constexpr auto generate_array (Func &&gen)
template<typename Container , typename T >
auto erase (Container &&cont, T &&t)
Erase elements from container.
template<typename Container , typename Pred >
auto erase_if (Container &&cont, Pred &&pred)
Erase elements from container by predicate.
template<typename InputIt , typename Size , typename F >
constexpr InputIt for_each_n (InputIt &&first, Size n, F &&f)
template<typename InputIt , typename F >
constexpr std::size_t indexed_for (InputIt &&first, InputIt &&last, F &&f)
for_each with access to an index value.
template<typename Rng , typename F >
constexpr std::size_t indexed_for (Rng &&rng, F &&f)
template<class InputIt , class Size , class F >
constexpr InputIt indexed_for_n (InputIt first, Size n, F &&f)
for_each_n with access to an index value.
template<class Rng , class Size , class F >
constexpr std::size_t indexed_for_n (Rng &&rng, Size n, F &&f)
template<typename Iter1 , typename Iter2 , typename F >
constexpr void for_both (Iter1 &&f1, Iter1 &&l1, Iter2 &&f2, Iter2 &&l2, F &&f)
template<typename Rng1 , typename Rng2 , typename F >
constexpr void for_both (Rng1 &&r1, Rng2 &&r2, F &&f)
template<typename Cont , typename T >
constexpr auto accumulate (Cont &&cont, T &&init)
Container based wrapper for std::accumulate()
template<typename Cont , typename T , typename BinaryOperation >
constexpr auto accumulate (Cont &&cont, T &&init, BinaryOperation &&op)
Container based wrapper for std::accumulate()
template<typename Cont , typename UnaryOperation >
constexpr void for_each (Cont &&cont, UnaryOperation &&op)
Container based wrapper for std::for_each()
template<typename Cont , typename OutputIterator >
decltype(auto) adjacent_difference (Cont &&cont, OutputIterator &&first)
Container based wrapper for std::adjacent_difference()
template<typename Cont >
decltype(auto) prev_permutation (Cont &&cont)
Container based wrapper for std::prev_permutation()
template<typename Cont , typename Compare >
decltype(auto) prev_permutation (Cont &&cont, Compare &&comp)
Container based wrapper for std::prev_permutation()
template<typename Cont >
decltype(auto) push_heap (Cont &&cont)
Container based wrapper for std::push_heap()
template<typename Cont , typename Compare >
decltype(auto) push_heap (Cont &&cont, Compare &&comp)
Container based wrapper for std::push_heap()
template<typename Cont , typename T >
decltype(auto) remove (Cont &&cont, T &&value)
Container based wrapper for std::remove()
template<typename Cont , typename OutputIterator , typename T >
decltype(auto) remove_copy (Cont &&cont, OutputIterator &&first, T &&value)
Container based wrapper for std::remove_copy()
template<typename Cont , typename OutputIterator , typename UnaryPredicate >
decltype(auto) remove_copy_if (Cont &&cont, OutputIterator &&first, UnaryPredicate &&p)
Container based wrapper for std::remove_copy_if()
template<typename Cont , typename UnaryPredicate >
decltype(auto) remove_if (Cont &&cont, UnaryPredicate &&p)
Container based wrapper for std::remove_if()
template<typename Cont , typename T , typename T2 >
decltype(auto) replace (Cont &&cont, T &&old_value, T2 &&new_value)
Container based wrapper for std::replace()
template<typename Cont , typename OutputIterator , typename T , typename T2 >
decltype(auto) replace_copy (Cont &&cont, OutputIterator &&first, T &&old_value, T2 &&new_value)
Container based wrapper for std::replace_copy()
template<typename Cont , typename OutputIterator , typename UnaryPredicate , typename T >
decltype(auto) replace_copy_if (Cont &&cont, OutputIterator &&first, UnaryPredicate &&p, T &&new_value)
Container based wrapper for std::replace_copy_if()
template<typename Cont , typename UnaryPredicate , typename T >
decltype(auto) replace_if (Cont &&cont, UnaryPredicate &&p, T &&new_value)
Container based wrapper for std::replace_if()
template<typename Cont >
decltype(auto) reverse (Cont &&cont)
Container based wrapper for std::reverse()
template<typename Cont , typename OutputIterator >
decltype(auto) reverse_copy (Cont &&cont, OutputIterator &&first)
Container based wrapper for std::reverse_copy()
template<typename Cont , typename ForwardIterator >
decltype(auto) rotate (Cont &&cont, ForwardIterator &&new_first)
Container based wrapper for std::rotate()
template<typename Cont , typename ForwardIterator , typename OutputIterator >
decltype(auto) rotate_copy (Cont &&cont, ForwardIterator &&new_first, OutputIterator &&first)
Container based wrapper for std::rotate_copy()
template<typename Cont , typename Cont2 >
decltype(auto) search (Cont &&cont, Cont2 &&cont2)
Container based wrapper for std::search()
template<typename Cont , typename Cont2 , typename BinaryPredicate >
decltype(auto) search (Cont &&cont, Cont2 &&cont2, BinaryPredicate &&p)
Container based wrapper for std::search()
template<typename Cont , typename Size , typename T >
decltype(auto) search_n (Cont &&cont, Size count, T &&value)
Container based wrapper for std::search_n()
template<typename Cont , typename Size , typename T , typename BinaryPredicate >
decltype(auto) search_n (Cont &&cont, Size count, T &&value, BinaryPredicate &&p)
Container based wrapper for std::search_n()
template<typename Cont , typename Cont2 , typename OutputIterator >
decltype(auto) set_difference (Cont &&cont, Cont2 &&cont2, OutputIterator &&first)
Container based wrapper for std::set_difference()
template<typename Cont , typename Cont2 , typename OutputIterator , typename Compare >
decltype(auto) set_difference (Cont &&cont, Cont2 &&cont2, OutputIterator &&first, Compare &&comp)
Container based wrapper for std::set_difference()
template<typename Cont , typename Cont2 , typename OutputIterator >
decltype(auto) set_intersection (Cont &&cont, Cont2 &&cont2, OutputIterator &&first)
Container based wrapper for std::set_intersection()
template<typename Cont , typename Cont2 , typename OutputIterator , typename Compare >
decltype(auto) set_intersection (Cont &&cont, Cont2 &&cont2, OutputIterator &&first, Compare &&comp)
Container based wrapper for std::set_intersection()
template<typename Cont , typename Cont2 , typename OutputIterator >
decltype(auto) set_symmetric_difference (Cont &&cont, Cont2 &&cont2, OutputIterator &&first)
Container based wrapper for std::set_symmetric_difference()
template<typename Cont , typename Cont2 , typename OutputIterator , typename Compare >
decltype(auto) set_symmetric_difference (Cont &&cont, Cont2 &&cont2, OutputIterator &&first, Compare &&comp)
Container based wrapper for std::set_symmetric_difference()
template<typename Cont , typename Cont2 , typename OutputIterator >
decltype(auto) set_union (Cont &&cont, Cont2 &&cont2, OutputIterator &&first)
Container based wrapper for std::set_union()
template<typename Cont , typename Cont2 , typename OutputIterator , typename Compare >
decltype(auto) set_union (Cont &&cont, Cont2 &&cont2, OutputIterator &&first, Compare &&comp)
Container based wrapper for std::set_union()
template<typename Cont , typename UniformRandomNumberGenerator >
decltype(auto) shuffle (Cont &&cont, UniformRandomNumberGenerator &&g)
Container based wrapper for std::shuffle()
template<typename Cont >
decltype(auto) sort (Cont &&cont)
Container based wrapper for std::sort()
template<typename Cont , typename Compare >
decltype(auto) sort (Cont &&cont, Compare &&comp)
Container based wrapper for std::sort()
template<typename Cont >
decltype(auto) sort_heap (Cont &&cont)
Container based wrapper for std::sort_heap()
template<typename Cont , typename Compare >
decltype(auto) sort_heap (Cont &&cont, Compare &&comp)
Container based wrapper for std::sort_heap()
template<typename Cont , typename UnaryPredicate >
decltype(auto) stable_partition (Cont &&cont, UnaryPredicate &&p)
Container based wrapper for std::stable_partition()
template<typename Cont >
decltype(auto) stable_sort (Cont &&cont)
Container based wrapper for std::stable_sort()
template<typename Cont , typename Compare >
decltype(auto) stable_sort (Cont &&cont, Compare &&comp)
Container based wrapper for std::stable_sort()
template<typename Cont , typename ForwardIterator >
decltype(auto) swap_ranges (Cont &&cont, ForwardIterator &&first)
Container based wrapper for std::swap_ranges()
template<typename Cont , typename Cont2 , typename F >
auto transform (Cont &&cont, Cont2 &&cont2, F &&f) -> decltype(begin(cont2))
Container based wrapper for std::transform()
template<typename Cont , typename Iter , typename F >
decltype(auto) transform (Cont &&cont, Iter &&iter, F &&f)
Container based wrapper for std::transform()
template<typename Cont , typename Cont2 , typename Cont3 , typename BinaryPredicate >
auto transform (Cont &&cont, Cont2 &&cont2, Cont3 &&cont3, BinaryPredicate &&f) -> decltype(begin(cont2), begin(cont3))
Container based wrapper for std::transform()
template<typename Cont , typename InputIterator , typename Cont3 , typename BinaryPredicate >
auto transform (Cont &&cont, InputIterator &&iter, Cont3 &&cont3, BinaryPredicate &&f) -> decltype(begin(cont), begin(cont3))
Container based wrapper for std::transform()
template<typename Cont , typename Cont2 , typename InputIterator , typename BinaryPredicate >
auto transform (Cont &&cont, Cont2 &&cont2, InputIterator &&iter, BinaryPredicate &&f) -> decltype(begin(cont), begin(cont2), iter)
Container based wrapper for std::transform()
template<typename Cont , typename InputIterator , typename OutputIterator , typename BinaryOperation >
decltype(auto) transform (Cont &&cont, InputIterator &&firstIn, OutputIterator &&firstOut, BinaryOperation &&op)
Container based wrapper for std::transform()
template<typename Cont >
decltype(auto) unique (Cont &&cont)
Container based wrapper for std::unique()
template<typename Cont , typename BinaryPredicate >
decltype(auto) unique (Cont &&cont, BinaryPredicate &&p)
Container based wrapper for std::unique()
template<typename Cont , typename OutputIterator >
decltype(auto) unique_copy (Cont &&cont, OutputIterator &&first)
Container based wrapper for std::unique_copy()
template<typename Cont , typename OutputIterator , typename BinaryPredicate >
decltype(auto) unique_copy (Cont &&cont, OutputIterator &&first, BinaryPredicate &&p)
Container based wrapper for std::unique_copy()
template<typename Cont , typename T >
decltype(auto) upper_bound (Cont &&cont, T &&value)
Container based wrapper for std::upper_bound()
template<typename Cont , typename T , typename Compare >
decltype(auto) upper_bound (Cont &&cont, T &&value, Compare &&comp)
Container based wrapper for std::upper_bound()
template<typename Cont , typename OutputIterator >
decltype(auto) copy (Cont &&cont, OutputIterator &&first)
Container based wrapper for std::copy()
template<typename Cont , typename OutputIterator , typename UnaryPredicate >
decltype(auto) copy_if (Cont &&cont, OutputIterator &&first, UnaryPredicate &&p)
Container based wrapper for std::copy_if()
template<typename Cont , typename T >
decltype(auto) fill (Cont &&cont, T &&value)
Container based wrapper for std::fill()
template<typename Cont , typename T >
decltype(auto) fill_n (Cont &&cont, std::size_t n, T &&value)
Container based wrapper for std::fill_n()
template<typename Cont , typename UnaryPredicate >
decltype(auto) any_of (Cont &&cont, UnaryPredicate &&p)
Container based wrapper for std::any_of()
template<typename Cont , typename UnaryPredicate >
decltype(auto) all_of (Cont &&cont, UnaryPredicate &&p)
Container based wrapper for std::all_of()
template<typename Cont , typename UnaryPredicate >
decltype(auto) none_of (Cont &&cont, UnaryPredicate &&p)
Container based wrapper for std::none_of()
template<typename Cont >
decltype(auto) max_element (Cont &&cont)
Container based wrapper for std::max_element()
template<typename Cont >
decltype(auto) min_element (Cont &&cont)
Container based wrapper for std::min_element()
template<typename Cont , typename Compare >
decltype(auto) min_element (Cont &&cont, Compare &&f)
Container based wrapper for std::min_element()
template<typename Cont , typename Compare >
decltype(auto) max_element (Cont &&cont, Compare &&f)
Container based wrapper for std::max_element()
template<typename Cont , typename T >
decltype(auto) find (Cont &&cont, T &&t)
Container based wrapper for std::find()
template<typename Cont , typename UnaryPredicate >
decltype(auto) find_if (Cont &&cont, UnaryPredicate &&f)
Container based wrapper for std::find_if()
Function Documentation
join_strings() [1/2]
template<class StrIterator > std::string otto::util::algorithm::join_strings (StrIterator b, StrIterator e, std::string_view js = ", ")
Joins a sequence of strings, separating them using js
Definition at line 30 of file algorithm.hpp.
References std::string::append(), std::string::empty(), and std::for_each().
Referenced by join_strings().
string_replace()
void otto::util::algorithm::string_replace (std::string & str, const std::string & oldStr, const std::string & newStr)
Find/Replace.
Definition at line 43 of file algorithm.hpp.
References std::string::find(), std::string::length(), and std::string::replace().
starts_with()
bool otto::util::algorithm::starts_with (std::string_view str, std::string_view prefix)
Check if string str starts with prefix
Definition at line 55 of file algorithm.hpp.
join_strings() [2/2]
template<typename Container > std::string otto::util::algorithm::join_strings (Container && cont, std::string_view js = ", ")
Joins a sequence of strings, separating them using js
Definition at line 62 of file algorithm.hpp.
References std::begin(), std::end(), and join_strings().
generate_array()
template<int n, class Func > constexpr auto otto::util::algorithm::generate_array (Func && gen) constexpr
Definition at line 77 of file algorithm.hpp.
erase()
template<typename Container , typename T > auto otto::util::algorithm::erase (Container && cont, T && t)
Erase elements from container.
Parameters
cont Must be a container with a erase(Iter, Iter) member function, erasing the items between the two iterators. Most mutable standard containers qualify.
t elements will be erased if they compare equal to this
Returns
whatever cont.erase() returns. For standard containers, this is the iterator pointing to the element after the last erased one.
Definition at line 93 of file algorithm.hpp.
References std::begin(), std::end(), and std::remove().
erase_if()
template<typename Container , typename Pred > auto otto::util::algorithm::erase_if (Container && cont, Pred && pred)
Erase elements from container by predicate.
Parameters
cont Must be a container with a erase(Iter, Iter) member function, erasing the items between the two iterators. Most mutable standard containers qualify.
pred A predicate that takes a element in the container. Each element for which this predicate returns true will be erased from the container.
Returns
whatever cont.erase() returns. For standard containers, this is the iterator pointing to the element after the last erased one.
Definition at line 110 of file algorithm.hpp.
References std::begin(), std::end(), and std::remove_if().
for_each_n()
template<typename InputIt , typename Size , typename F > constexpr InputIt otto::util::algorithm::for_each_n (InputIt && first, Size n, F && f) constexpr
Definition at line 121 of file algorithm.hpp.
Referenced by otto::util::SoundFile::write_samples().
indexed_for() [1/2]
template<typename InputIt , typename F > constexpr std::size_t otto::util::algorithm::indexed_for (InputIt && first, InputIt && last, F && f) constexpr
for_each with access to an index value.
Function called as f(*it, i)
For each item in range [first, last), invoke f with args *iter, i where iter is the current iterator, and i is an incrementing value, starting at zero. Use this instead of raw indexed loops wherever possible.
Parameters
first Input iterator to the begining of the range
last Input iterator to the end of the range
f Must be invocable with arguments value_type, std::size_t
Returns
The number of iterations performed
Definition at line 141 of file algorithm.hpp.
References std::for_each().
Referenced by indexed_for().
indexed_for() [2/2]
template<typename Rng , typename F > constexpr std::size_t otto::util::algorithm::indexed_for (Rng && rng, F && f) constexpr
Definition at line 152 of file algorithm.hpp.
References std::begin(), std::end(), and indexed_for().
indexed_for_n() [1/2]
template<class InputIt , class Size , class F > constexpr InputIt otto::util::algorithm::indexed_for_n (InputIt first, Size n, F && f) constexpr
for_each_n with access to an index value.
Function called as f(*it, i)
for n iterations, invoke f with args *iter, i where iter is the current iterator starting with first, and i is an incrementing value, starting at zero. Use this instead of raw indexed loops wherever possible.
Parameters
first Input iterator to the begining of the range
n Number of iterations to go through
f Must be invocable with arguments value_type, std::size_t
Returns
An iterator one past the last one visited
Definition at line 170 of file algorithm.hpp.
Referenced by indexed_for_n().
indexed_for_n() [2/2]
template<class Rng , class Size , class F > constexpr std::size_t otto::util::algorithm::indexed_for_n (Rng && rng, Size n, F && f) constexpr
Definition at line 179 of file algorithm.hpp.
References std::begin(), std::end(), and indexed_for_n().
for_both() [1/2]
template<typename Iter1 , typename Iter2 , typename F > constexpr void otto::util::algorithm::for_both (Iter1 && f1, Iter1 && l1, Iter2 && f2, Iter2 && l2, F && f) constexpr
Definition at line 185 of file algorithm.hpp.
Referenced by for_both().
for_both() [2/2]
template<typename Rng1 , typename Rng2 , typename F > constexpr void otto::util::algorithm::for_both (Rng1 && r1, Rng2 && r2, F && f) constexpr
Definition at line 195 of file algorithm.hpp.
References std::begin(), std::end(), and for_both().