OTTO: otto::reflect Namespace Reference
otto::reflect Namespace Reference
Classes
struct _has_reflect_member
struct _is_registered
struct _is_registered< T, std::void_t< decltype(register_members< T >())> >
struct constructor_args
struct Member
struct MemberAccessor
struct MemberAccessor< Class, T, AccessorType::MutableRef, Data >
struct MemberAccessor< Class, T, AccessorType::ReadOnly, Data >
struct MemberAccessor< Class, T, AccessorType::ReadWrite, Data >
Typedefs
template<typename MemberType >
using get_member_type = typename std::decay_t< MemberType >::member_type
MemberType is Member<T, Class>
template<typename T >
using constructor_arguments = typename constructor_args< T >::types
Enumerations
enum AccessorType { AccessorType::ReadOnly, AccessorType::ReadWrite, AccessorType::MutableRef }
Functions
template<typename Class , typename Callable , typename = std::enable_if_t<mpark::lib::is_invocable<Callable, Class&>::value>>
constexpr auto member (util::string_ref, Callable &&ref_getter)
template<typename Class , typename Getter , typename Setter , typename = std::enable_if_t<mpark::lib::is_invocable<Getter, const Class&>::value>>
constexpr auto member (util::string_ref, Getter &&getter, Setter &&setter)
template<typename... Args>
constexpr auto members (Args &&... args)
template<typename Class , typename = std::enable_if_t<_has_reflect_member<Class>::value>>
constexpr auto register_members ()
template<typename Class , typename = std::enable_if_t<_has_reflect_member<Class>::value>>
constexpr util::string_ref register_name ()
template<typename Class >
constexpr util::string_ref get_name ()
template<typename Class >
constexpr std::size_t get_member_count ()
template<typename Class >
constexpr const auto & get_members ()
template<typename Class >
constexpr bool is_registered ()
template<typename Class >
constexpr bool ctor_registered ()
template<typename Class >
bool has_member (const char *name)
template<typename Class , typename F , typename = std::enable_if_t<is_registered<Class>()>>
void for_all_members (F &&f)
template<typename Class , typename F , typename = std::enable_if_t<!is_registered<Class>()>, typename = void>
void for_all_members (F &&f)
template<typename Class , typename T , typename F >
void for_member (const char *name, F &&f)
template<typename T , typename Class >
T get_member_value (Class &obj, const char *name)
template<typename T , typename Class , typename V , typename = std::enable_if_t<std::is_constructible<T, V>::value>>
void set_member_value (Class &obj, const char *name, V &&value)
Class Documentation
otto::reflect::constructor_args
struct otto::reflect::constructor_args
Class Members
typedef type_list<> types
otto::reflect::MemberAccessor
struct otto::reflect::MemberAccessor
Typedef Documentation
get_member_type
template<typename MemberType > using otto::reflect::get_member_type = typedef typename std::decay_t<MemberType>::member_type
MemberType is Member<T, Class>
Definition at line 27 of file member.hpp.
constructor_arguments
template<typename T > using otto::reflect::constructor_arguments = typedef typename constructor_args<T>::types
Definition at line 112 of file reflect.hpp.
Enumeration Type Documentation
AccessorType
enum otto::reflect::AccessorType strong
Enumerator
ReadOnly
ReadWrite
MutableRef
Definition at line 29 of file member.hpp.
Function Documentation
member() [1/2]
template<typename Class , typename Callable , typename = std::enable_if_t<mpark::lib::is_invocable<Callable, Class&>::value>> constexpr auto otto::reflect::member (util::string_ref name, Callable && ref_getter) constexpr
Definition at line 49 of file member.inl.
Referenced by otto::util::deserialize(), for_member(), get_member_value(), has_member(), otto::util::serialize(), and set_member_value().
member() [2/2]
template<typename Class , typename Getter , typename Setter , typename = std::enable_if_t<mpark::lib::is_invocable<Getter, const Class&>::value>> constexpr auto otto::reflect::member (util::string_ref name, Getter && getter, Setter && setter) constexpr
Definition at line 71 of file member.inl.
References std::make_pair(), and ReadWrite.
members()
template<typename... Args> constexpr auto otto::reflect::members (Args &&... args) constexpr
Definition at line 12 of file reflect.inl.
References std::make_tuple().
Referenced by get_members().
register_members()
template<typename Class , typename = std::enable_if_t<_has_reflect_member<Class>::value>> constexpr auto otto::reflect::register_members () constexpr
Definition at line 72 of file reflect.hpp.
register_name()
template<typename Class , typename = std::enable_if_t<_has_reflect_member<Class>::value>> constexpr util::string_ref otto::reflect::register_name () constexpr
Definition at line 79 of file reflect.hpp.
get_name()
template<typename Class > constexpr util::string_ref otto::reflect::get_name () constexpr
Definition at line 33 of file reflect.inl.
get_member_count()
template<typename Class > constexpr std::size_t otto::reflect::get_member_count () constexpr
Definition at line 39 of file reflect.inl.
get_members()
template<typename Class > constexpr const auto & otto::reflect::get_members () constexpr
Definition at line 45 of file reflect.inl.
References members().
is_registered()
template<typename Class > constexpr bool otto::reflect::is_registered () constexpr
Definition at line 57 of file reflect.inl.
ctor_registered()
template<typename Class > constexpr bool otto::reflect::ctor_registered () constexpr
Definition at line 64 of file reflect.inl.
has_member()
template<typename Class > bool otto::reflect::has_member (const char * name)
Definition at line 70 of file reflect.inl.
References member().
for_all_members() [1/2]
template<typename Class , typename F , typename = std::enable_if_t<is_registered<Class>()>> void otto::reflect::for_all_members (F && f)
Definition at line 82 of file reflect.inl.
for_all_members() [2/2]
template<typename Class , typename F , typename = std::enable_if_t<!is_registered<Class>()>, typename = void> void otto::reflect::for_all_members (F && f)
Definition at line 89 of file reflect.inl.
for_member()
template<typename Class , typename T , typename F > void otto::reflect::for_member (const char * name, F && f)
Definition at line 95 of file reflect.inl.
References member().
get_member_value()
template<typename T , typename Class > T otto::reflect::get_member_value (Class & obj, const char * name)
Definition at line 107 of file reflect.inl.
References member().
set_member_value()
template<typename T , typename Class , typename V , typename = std::enable_if_t<std::is_constructible<T, V>::value>> void otto::reflect::set_member_value (Class & obj, const char * name, V && value)
Definition at line 116 of file reflect.inl.
References member().