OTTO: otto::services::test Namespace Reference
otto::services::test Namespace Reference
Classes
struct DummyAudioManager
struct DummyController
struct DummyEngineManager
struct DummyPresetManager
struct DummyStateManager
struct DummyUIManager
Functions
Application make_dummy_application ()
Application make_dummy_application_default_engines ()
Function Documentation
make_dummy_application()
Application otto::services::test::make_dummy_application ()
Definition at line 142 of file dummy_services.hpp.
References otto::services::ClockManager::create_default().
make_dummy_application_default_engines()
Application otto::services::test::make_dummy_application_default_engines ()
Definition at line 156 of file dummy_services.hpp.
References otto::services::ClockManager::create_default(), and otto::services::EngineManager::create_default().