OTTO: otto::util::math Namespace Reference
otto::util::math Namespace Reference
Functions
template<typename T >
constexpr bool between (T min, T max, T el)
float round (float f, int places)
template<typename T >
int sgn (T val)
template<typename T >
constexpr T modulo (T a, T b)
Real modulo for negative a too.
int modulo (int i, int n)
template<int N>
constexpr std::array< float, N > split_values (float f, float min, float max)
Split a number into N values between 0 and 1, each representing a Nth part of the range [min,max]
double vox_fasttanh2 (const double x)
float fasttanh3 (const float x)
Function Documentation
between()
template<typename T > constexpr bool otto::util::math::between (T min, T max, T el) constexpr
Definition at line 11 of file math.hpp.
round()
float otto::util::math::round (float f, int places)
Definition at line 16 of file math.hpp.
References std::pow(), and std::round().
sgn()
template<typename T > int otto::util::math::sgn (T val)
Definition at line 23 of file math.hpp.
modulo() [1/2]
template<typename T > constexpr T otto::util::math::modulo (T a, T b) constexpr
Real modulo for negative a too.
Definition at line 30 of file math.hpp.
References std::fmod().
Referenced by otto::core::props::OTTO_PROPS_MIXIN_LEAF().
modulo() [2/2]
int otto::util::math::modulo (int i, int n)
Definition at line 36 of file math.hpp.
split_values()
template<int N> constexpr std::array<float, N> otto::util::math::split_values (float f, float min, float max) constexpr
Split a number into N values between 0 and 1, each representing a Nth part of the range [min,max]
This is useful for UI especially, when you want to display a range of values by fading colours between N fixed points. See draw_pitch in drum_sampler.cpp for an example
Definition at line 48 of file math.hpp.
References otto::nvg::ColorConverter::clamp().
vox_fasttanh2()
double otto::util::math::vox_fasttanh2 (const double x)
Definition at line 59 of file math.hpp.
fasttanh3()
float otto::util::math::fasttanh3 (const float x)
Definition at line 68 of file math.hpp.