OTTO: otto::core::props::detail Namespace Reference
otto::core::props::detail Namespace Reference
Classes
struct is_array
struct is_array< std::array< T, N > >
struct is_disabler
struct is_disabler< no< Tag > >
struct properties_for_list
struct properties_for_list< tag_list< Tags... > >
Functions
template<typename HT , HookOrder HO, typename Mixin , CONCEPT_REQUIRES_(cpts::models< HookTag, HT, typename Mixin::value_type >()) >
void run_hook_if_handler (Mixin &m, MixinImpl::hook_t< Mixin, HT, HO > &h)
Run Mixin's handler for Hook if it has one.
template<typename H , typename Mixin , HookOrder HO, CONCEPT_REQUIRES_(cpts::models< HookTag, H, typename Mixin::value_type >()) >
auto run_all_hooks_impl (Mixin &m, MixinImpl::hook_t< Mixin, H, HO > &&hook)
template<typename H , typename Mixin , CONCEPT_REQUIRES_(cpts::models< HookTag, H, typename Mixin::value_type >() && !cpts::models< HookWithValue, MixinImpl::hook_t< Mixin, H >>()) >
void run_hook (Mixin &m)
Run handler for Hook for all of Mixins siblings.
template<typename H , typename Mixin , CONCEPT_REQUIRES_(cpts::models< HookTag, H, typename Mixin::value_type >() && cpts::models< HookWithValue, MixinImpl::hook_t< Mixin, H >>()) >
auto run_hook (Mixin &m, const HookWithValue::arg_type< MixinImpl::hook_t< Mixin, H >> &arg)
Run handler for Hook for all of Mixins siblings.
Function Documentation
run_all_hooks_impl()
template<typename H , typename Mixin , HookOrder HO, CONCEPT_REQUIRES_(cpts::models< HookTag, H, typename Mixin::value_type >()) > auto otto::core::props::detail::run_all_hooks_impl (Mixin & m, MixinImpl::hook_t< Mixin, H, HO > && hook)
Definition at line 286 of file type_traits.hpp.
References run_all_hooks_impl().
Referenced by run_all_hooks_impl().
{
       meta::for_each<typename Mixin::tag_list>(
         [&hook, &m](auto&& mtype) {
           run_hook_if_handler<H, HO>(
             m.template as<decltype(mtype._t())>(),
             hook);
       });
       return hook;
     }
run_hook() [1/2]
template<typename H , typename Mixin , CONCEPT_REQUIRES_(cpts::models< HookTag, H, typename Mixin::value_type >() && !cpts::models< HookWithValue, MixinImpl::hook_t< Mixin, H >>()) > void otto::core::props::detail::run_hook (Mixin & m)
Run handler for Hook for all of Mixins siblings.
Definition at line 302 of file type_traits.hpp.
References run_hook().
Referenced by run_hook().
     {
       MixinImpl::hook_t<Mixin, H, HookOrder::Before> hook {};
       auto h1 =
         run_all_hooks_impl<H, Mixin, HookOrder::Before>(m, std::move(hook));
       auto h2 = run_all_hooks_impl<H, Mixin, HookOrder::Early>(
         m, MixinImpl::hook_t<Mixin, H, HookOrder::Early>(std::move(h1)));
       auto h3 = run_all_hooks_impl<H, Mixin, HookOrder::Middle>(
         m, MixinImpl::hook_t<Mixin, H, HookOrder::Middle>(std::move(h2)));
       auto h4 = run_all_hooks_impl<H, Mixin, HookOrder::Late>(
         m, MixinImpl::hook_t<Mixin, H, HookOrder::Late>(std::move(h3)));
       auto h5 = run_all_hooks_impl<H, Mixin, HookOrder::After>(
         m, MixinImpl::hook_t<Mixin, H, HookOrder::After>(std::move(h4)));
     }
run_hook() [2/2]
template<typename H , typename Mixin , CONCEPT_REQUIRES_(cpts::models< HookTag, H, typename Mixin::value_type >() && cpts::models< HookWithValue, MixinImpl::hook_t< Mixin, H >>()) > auto otto::core::props::detail::run_hook (Mixin & m, const HookWithValue::arg_type< MixinImpl::hook_t< Mixin, H >> & arg)
Run handler for Hook for all of Mixins siblings.
Definition at line 323 of file type_traits.hpp.
References run_hook().
     {
       MixinImpl::hook_t<Mixin, H, HookOrder::Before> hook {arg};
       auto h1 =
         run_all_hooks_impl<H, Mixin, HookOrder::Before>(m, std::move(hook));
       auto h2 = run_all_hooks_impl<H, Mixin, HookOrder::Early>(
         m, MixinImpl::hook_t<Mixin, H, HookOrder::Early>(std::move(h1)));
       auto h3 = run_all_hooks_impl<H, Mixin, HookOrder::Middle>(
         m, MixinImpl::hook_t<Mixin, H, HookOrder::Middle>(std::move(h2)));
       auto h4 = run_all_hooks_impl<H, Mixin, HookOrder::Late>(
         m, MixinImpl::hook_t<Mixin, H, HookOrder::Late>(std::move(h3)));
       auto h5 = run_all_hooks_impl<H, Mixin, HookOrder::After>(
         m, MixinImpl::hook_t<Mixin, H, HookOrder::After>(std::move(h4)));
       return h5.value();
     }
run_hook_if_handler()
template<typename HT , HookOrder HO, typename Mixin , CONCEPT_REQUIRES_(cpts::models< HookTag, HT, typename Mixin::value_type >()) > void otto::core::props::detail::run_hook_if_handler (Mixin & m, MixinImpl::hook_t< Mixin, HT, HO > & h)
Run Mixin's handler for Hook if it has one.
Definition at line 274 of file type_traits.hpp.
References run_hook_if_handler().
Referenced by run_hook_if_handler().
     {
       if constexpr (MixinImpl::has_handler_v<Mixin, HT, HO>) {
         m.on_hook(h);
       }
     }