OTTO: otto::core::engines Namespace Reference
otto::core::engines Namespace Reference
Namespaces
internal
Classes
struct AnyEngine
Abstract base class for Engines.
struct Engine
Engine base class.
struct Engine< EngineType::synth >
struct Engine< EngineType::effect >
struct Engine< EngineType::sequencer >
struct Engine< EngineType::twist >
struct EngineScreen
A ui::Screen with a reference to the engine it belongs to.
struct EngineWithEnvelope
struct EngineDispatcher
Owns engines of type ET, and dispatches to a selected one of them.
struct EngineSelectorScreen
Typedefs
using SynthEngine = Engine< EngineType::synth >
using EffectEngine = Engine< EngineType::effect >
using SequencerEngine = Engine< EngineType::sequencer >
using TwistEngine = Engine< EngineType::twist >
Enumerations
enum EngineType {
EngineType::synth, EngineType::effect, EngineType::sequencer, EngineType::twist,
EngineType::misc
}
Engine type.
Functions
template<typename REngine , typename... Args>
void register_engine (Args &&...args)
Register an engine.
template<EngineType ET>
std::vector< std::unique_ptr
< Engine< ET > > > create_engines ()
Construct all registered engines of type ET
preset_wid (preset_names, prst_opts([&ed]() -> AnyEngine &{return ed.current();}))
Variables
template<typename E >
constexpr EngineType engine_type_v
Type trait to get engine type.
Typedef Documentation
using otto::core::engines::SynthEngine = typedef Engine<EngineType::synth>
Definition at line 159 of file engine.hpp.
using otto::core::engines::EffectEngine = typedef Engine<EngineType::effect>
Definition at line 168 of file engine.hpp.
using otto::core::engines::SequencerEngine = typedef Engine<EngineType::sequencer>
Definition at line 177 of file engine.hpp.
using otto::core::engines::TwistEngine = typedef Engine<EngineType::twist>
Definition at line 186 of file engine.hpp.
Enumeration Type Documentation
enum otto::core::engines::EngineType strong
Engine type.
Each engine has a type, which signifies the group it belongs to.
Enumerator
synth
Synth engines.
effect
FX engines.
sequencer
Sequencer engines.
twist
Twist engines - Not really engines in the same sense.
misc
Misc engines - used for stuff like the Master screen.
Definition at line 21 of file engine.hpp.
Function Documentation
template<typename REngine , typename... Args> void otto::core::engines::register_engine (Args &&... args)
Register an engine.
Store a function which constructs an REngine in a std::unique_ptr with args forwarded.
Definition at line 294 of file engine.hpp.
References otto::core::engines::internal::make_wrapper().
template<EngineType ET> std::vector< std::unique_ptr< Engine< ET > > > otto::core::engines::create_engines ()
Construct all registered engines of type ET
This is mostly useful for [EngineDispatcher<ET>]()
Call all the stored constructors for type ET, and move the resulting unique_ptrs into a vector, which is returned.
Definition at line 309 of file engine.hpp.
References std::vector< T >::emplace_back(), and std::vector< T >::reserve().
otto::core::engines::preset_wid (preset_names , prst_opts([&ed]() -> AnyEngine &{return ed.current();}))
Definition at line 41 of file engine_selector_screen.hpp.
Variable Documentation
template<typename E > constexpr EngineType otto::core::engines::engine_type_v
Initial value:
=
    decltype(internal::engine_type_impl_func(std::declval<E>()))::value
Type trait to get engine type.
SFINAE friendly, and will match any type that inherits from [Engine]()
Definition at line 205 of file engine.hpp.