OTTO: otto::service::engines Namespace Reference
otto::service::engines Namespace Reference
Typedefs
using exception = util::as_exception< ErrorCode >
EngineManager exceptions. Contain an [ErrorCode]()
Enumerations
enum ErrorCode { ErrorCode::no_such_engine }
Error codes. Thrown with exceptions.
Functions
void init ()
void start ()
void shutdown ()
core::audio::ProcessData< 2 > process (core::audio::ProcessData< 1 > external_in)
Process the engine audio chain.
AnyEngine *const by_name (const std::string &name) noexcept
Typedef Documentation
exception
using otto::service::engines::exception = typedef util::as_exception<ErrorCode>
EngineManager exceptions. Contain an [ErrorCode]()
Definition at line 18 of file engines.hpp.
Enumeration Type Documentation
ErrorCode
enum otto::service::engines::ErrorCode strong
Error codes. Thrown with exceptions.
Enumerator
no_such_engine
Definition at line 13 of file engines.hpp.
{
     no_such_engine,
   };
Function Documentation
by_name()
core::engines::AnyEngine *const otto::service::engines::by_name (const std::string & name) noexcept
Get an engine by name
Returns
nullptr if no such engine was found
Definition at line 145 of file engines.cpp.
Referenced by otto::service::ui::select_engine().
   {
     auto getter = engineGetters.find(name);
     if (getter == engineGetters.end()) return nullptr;
     return getter->second();
   }
init()
void otto::service::engines::init ()
Initialize engine manager
register engines.
construct engines
register key handlers
attach state loader/saver
Definition at line 30 of file engines.cpp.
References otto::service::state::attach(), otto::service::ui::current_screen(), otto::service::ui::display(), otto::core::engines::effect, otto::core::ui::envelope, otto::core::ui::fx1, otto::service::ui::is_pressed(), otto::core::ui::master, otto::service::ui::register_key_handler(), otto::service::ui::select_engine(), otto::core::ui::sequencer, otto::core::engines::sequencer, otto::core::ui::shift, otto::core::engines::synth, otto::core::ui::synth, and otto::core::ui::voices.
   {
     engineGetters.try_emplace("Synth", [&]() { return dynamic_cast<AnyEngine*>(&*synth); });
     engineGetters.try_emplace("Effect", [&]() { return dynamic_cast<AnyEngine*>(&*effect); });
     engineGetters.try_emplace("Sequencer", [&]() { return dynamic_cast<AnyEngine*>(&*sequencer); });
     register_engine<otto::engines::Euclid>();
     register_engine<otto::engines::NukeSynth>();
     register_engine<otto::engines::Wormhole>();
     register_engine<otto::engines::External>();
     sequencer.init();
     synth.init();
     effect.init();
     service::ui::register_key_handler(core::ui::Key::sequencer, [](core::ui::Key k) {
       if (service::ui::is_pressed(core::ui::Key::shift)) {
         service::ui::display(sequencer.selector_screen());
       } else {
         service::ui::select_engine("Sequencer");
         service::ui::display(sequencer->screen());
       }
     });
     service::ui::register_key_handler(core::ui::Key::synth, [](core::ui::Key k) {
       if (service::ui::is_pressed(core::ui::Key::shift)) {
         service::ui::display(synth.selector_screen());
       } else {
         service::ui::select_engine("Synth");
       }
     });
     service::ui::register_key_handler(core::ui::Key::envelope, [](core::ui::Key k) {
       auto* owner = dynamic_cast<core::engines::EngineWithEnvelope*>(&synth.current());
       if (owner) {
         if (service::ui::is_pressed(core::ui::Key::shift)) {
           service::ui::display(owner->voices_screen());
         } else {
           service::ui::display(owner->envelope_screen());
         }
       }
     });
     service::ui::register_key_handler(core::ui::Key::voices, [](core::ui::Key k) {
       auto* owner = dynamic_cast<core::engines::EngineWithEnvelope*>(&synth.current());
       if (owner) {
         service::ui::display(owner->voices_screen());
       }
     });
     service::ui::register_key_handler(core::ui::Key::fx1, [](core::ui::Key k) {
       if (service::ui::is_pressed(core::ui::Key::shift)) {
         service::ui::display(effect.selector_screen());
       } else {
         service::ui::select_engine("Effect");
       }
     });
     static core::ui::Screen* master_last_screen = nullptr;
     service::ui::register_key_handler(core::ui::Key::master,
                                       [](core::ui::Key k) {
                                         master_last_screen = service::ui::current_screen();
                                         service::ui::display(master.screen());
                                       },
                                       [](core::ui::Key k) {
                                         if (master_last_screen)
                                           service::ui::display(*master_last_screen);
                                       });
     auto load = [&](nlohmann::json& data) {
       synth.from_json(data["Synth"]);
       effect.from_json(data["Effect"]);
       master.from_json(data["Master"]);
       sequencer.from_json(data["Sequencer"]);
     };
     auto save = [&] {
       return nlohmann::json({{"Synth", synth.to_json()},
                              {"Effect", effect.to_json()},
                              {"Master", master.to_json()},
                              {"Sequencer", sequencer.to_json()}});
     };
     service::state::attach("Engines", load, save);
   }
process()
core::audio::ProcessData< 2 > otto::service::engines::process (core::audio::ProcessData< 1 > external_in)
Process the engine audio chain.
Definition at line 126 of file engines.cpp.
References otto::core::audio::AudioBufferPool::allocate_multi(), otto::core::audio::ProcessData< N >::audio, otto::service::audio::buffer_pool(), otto::core::engines::effect, otto::core::ui::master, otto::core::audio::ProcessData< N >::midi_only(), otto::core::audio::ProcessData< N >::nframes, otto::core::engines::sequencer, otto::core::engines::synth, and otto::util::zip().
   {
     // Main processor function
     auto midi_in = external_in.midi_only();
     auto seq_out = sequencer->process(midi_in);
     auto audio_out = service::audio::buffer_pool().allocate_multi<2>();
     auto synth_out = synth->process({external_in.audio, seq_out.midi, external_in.nframes});
     for (auto&& [snth, out] : util::zip(synth_out, audio_out)) {
       std::get<0>(out) = std::get<0>(snth);
       std::get<1>(out) = std::get<0>(snth);
     }
     synth_out.audio.release();
     auto fx_out = effect->process(seq_out.redirect(audio_out));
     audio_out.release();
     return master.process(std::move(fx_out));
   }
shutdown()
void otto::service::engines::shutdown ()
Destruct engines
Invoke [AnyEngine::on_disable]() for all enabled engines
Definition at line 124 of file engines.cpp.
 {}
start()
void otto::service::engines::start ()
Mark engines as started
Invoke [AnyEngine::on_enable]() for all selected engines
[services::state::load]() must have been invoked
Definition at line 117 of file engines.cpp.
References otto::core::engines::effect, otto::core::engines::sequencer, and otto::core::engines::synth.
   {
     sequencer.select(std::size_t(0));
     synth.select(std::size_t(0));
     effect.select(std::size_t(0));
   }