OTTO: otto::filesystem::px Namespace Reference
otto::filesystem::px Namespace Reference
Functions
path::format detect_format (const path::string_type &s)
bool is_separator (path::value_type c)
file_type to_file_type (int stat_mode)
file_type to_file_type (struct stat st, std::error_code &ec)
uintmax_t file_size (struct stat st, std::error_code &ec)
uintmax_t hard_link_count (struct stat st, std::error_code &ec)
file_time_type last_write_time (struct stat st, std::error_code &ec)
struct stat stat (path p, std::error_code &ec)
struct stat lstat (path p, std::error_code &ec)
file_status status (path p, struct stat &st, std::error_code &ec)
file_status link_status (path p, struct stat &st, std::error_code &ec)
Variables
const char * separators = "/\\"
Function Documentation
detect_format()
path::format otto::filesystem::px::detect_format (const path::string_type & s)
Definition at line 109 of file filesystem.cpp.
References otto::filesystem::path::generic_format.
Referenced by otto::filesystem::path::assign().
     {
       return path::generic_format;
     }
file_size()
uintmax_t otto::filesystem::px::file_size (struct stat st, std::error_code & ec)
Definition at line 146 of file filesystem.cpp.
     {
       if (ec.value() == 0) {
         ec.clear();
       } else {
         return 0;
       }
       return st.st_size;
     }
hard_link_count()
uintmax_t otto::filesystem::px::hard_link_count (struct stat st, std::error_code & ec)
Definition at line 156 of file filesystem.cpp.
     {
       if (ec.value() == 0) {
         ec.clear();
       } else {
         return 0;
       }
       return st.st_nlink;
     }
is_separator()
bool otto::filesystem::px::is_separator (path::value_type c)
Definition at line 114 of file filesystem.cpp.
References separators.
Referenced by otto::filesystem::path::has_filename(), otto::filesystem::path::is_absolute(), and otto::filesystem::path::iterator::operator--().
     {
       const char* s = separators;
       while (*s != 0) {
         if (*s++ == c) return true;
       }
       return false;
     }
last_write_time()
file_time_type otto::filesystem::px::last_write_time (struct stat st, std::error_code & ec)
Definition at line 166 of file filesystem.cpp.
     {
       if (ec.value() == 0) {
         ec.clear();
       } else {
         return {};
       }
 #if __APPLE__
       return file_time_type() +
              std::chrono::duration_cast<file_time_type::duration>(
                std::chrono::nanoseconds(st.st_mtimespec.tv_nsec));
 #else
       return file_time_type() +
              std::chrono::duration_cast<file_time_type::duration>(
                std::chrono::nanoseconds(st.st_mtim.tv_nsec));
 #endif
     }
link_status()
file_status otto::filesystem::px::link_status (path p, struct stat & st, std::error_code & ec)
Definition at line 223 of file filesystem.cpp.
References otto::filesystem::mask, otto::filesystem::none, otto::filesystem::not_found, stat(), and to_file_type().
     {
       if (::stat(p.c_str(), &st) != 0) {
         if (errno == ENOENT) {
           ec.clear();
           return file_status{file_type::not_found, perms::none};
         } else {
           ec = {errno, std::system_category()};
           return {};
         }
       }
       ec.clear();
       file_type type = to_file_type(st, ec);
       perms prms     = static_cast<perms>(st.st_mode) & perms::mask;
       return file_status{type, prms};
     }
lstat()
struct stat otto::filesystem::px::lstat (path p, std::error_code & ec)
Definition at line 195 of file filesystem.cpp.
References stat().
     {
       struct stat st;
       if (::lstat(p.c_str(), &st) != 0) {
         ec = {errno, std::system_category()};
       } else {
         ec.clear();
       }
       return st;
     }
stat()
struct stat otto::filesystem::px::stat (path p, std::error_code & ec)
Definition at line 184 of file filesystem.cpp.
Referenced by link_status(), lstat(), and status().
     {
       struct stat st;
       if (::stat(p.c_str(), &st) != 0) {
         ec = {errno, std::system_category()};
       } else {
         ec.clear();
       }
       return st;
     }
status()
file_status otto::filesystem::px::status (path p, struct stat & st, std::error_code & ec)
Definition at line 206 of file filesystem.cpp.
References otto::filesystem::mask, otto::filesystem::none, otto::filesystem::not_found, stat(), and to_file_type().
     {
       if (::stat(p.c_str(), &st) != 0) {
         if (errno == ENOENT) {
           ec.clear();
           return file_status{file_type::not_found, perms::none};
         } else {
           ec = {errno, std::system_category()};
           return {};
         }
       }
       ec.clear();
       file_type type = to_file_type(st, ec);
       perms prms     = static_cast<perms>(st.st_mode) & perms::mask;
       return file_status{type, prms};
     }
to_file_type() [1/2]
file_type otto::filesystem::px::to_file_type (int stat_mode)
Definition at line 123 of file filesystem.cpp.
References otto::filesystem::block, otto::filesystem::character, otto::filesystem::directory, otto::filesystem::fifo, otto::filesystem::regular, otto::filesystem::socket, otto::filesystem::symlink, and otto::filesystem::unknown.
Referenced by link_status(), status(), and to_file_type().
     {
       if (S_ISBLK(stat_mode)) return file_type::block;
       if (S_ISCHR(stat_mode)) return file_type::character;
       if (S_ISDIR(stat_mode)) return file_type::directory;
       if (S_ISFIFO(stat_mode)) return file_type::fifo;
       if (S_ISLNK(stat_mode)) return file_type::symlink;
       if (S_ISREG(stat_mode)) return file_type::regular;
       if (S_ISSOCK(stat_mode)) return file_type::socket;
       return file_type::unknown;
     }
to_file_type() [2/2]
file_type otto::filesystem::px::to_file_type (struct stat st, std::error_code & ec)
Definition at line 135 of file filesystem.cpp.
References otto::filesystem::none, otto::filesystem::not_found, and to_file_type().
     {
       if (ec != std::error_code()) {
         switch (ec.value()) {
         case ENOENT: return file_type::not_found;
         default: return file_type::none;
         }
       }
       return to_file_type(st.st_mode);
     }
Variable Documentation
separators
const char* otto::filesystem::px::separators = "/\\"
Definition at line 107 of file filesystem.cpp.
Referenced by otto::filesystem::path::has_parent_path(), otto::filesystem::path::has_relative_path(), is_separator(), otto::filesystem::path::remove_filename(), and otto::filesystem::path::replace_extension().