OTTO: otto::service::audio Namespace Reference
otto::service::audio Namespace Reference
Namespaces
events
Classes
struct AlsaAudioDriver
struct JackAudioDriver
struct RTAudioDriver
Typedefs
using AudioDriver = AlsaAudioDriver
Functions
AudioBufferPool & buffer_pool () noexcept
int samplerate () noexcept
Get the current samplerate.
void init ()
void start () noexcept
void shutdown ()
Close the audio driver.
bool running () noexcept
void process_audio_output (ProcessData< 2 > audio_output)
void send_midi_event (core::midi::AnyMidiEvent evt) noexcept
Typedef Documentation
AudioDriver
typedef RTAudioDriver otto::service::audio::AudioDriver
Definition at line 44 of file audio_driver.hpp.
Function Documentation
buffer_pool()
AudioBufferPool & otto::service::audio::buffer_pool () noexcept
Definition at line 75 of file audio.cpp.
References otto::service::audio::AlsaAudioDriver::get().
Referenced by otto::service::engines::process(), and otto::core::audio::FaustWrapper< 0, 1 >::process().
   {
     return AudioDriver::get().buffer_pool();
   }
init()
void otto::service::audio::init ()
Initialize components
Fire [events::pre_init]()
Generate midi frequency table
Initialize the audio driver
Definition at line 67 of file audio.cpp.
References otto::util::Event< Args >::fire(), otto::core::midi::generateFreqTable(), otto::service::audio::AlsaAudioDriver::get(), otto::service::audio::AlsaAudioDriver::init(), and otto::service::audio::events::pre_init().
   {
     events::pre_init().fire();
     core::midi::generateFreqTable(440);
     AudioDriver::get().init();
   }
process_audio_output()
void otto::service::audio::process_audio_output (ProcessData< 2 > audio_output)
Process the final output
Currently only used for debugging
Definition at line 95 of file audio.cpp.
   {
 #if OTTO_DEBUG_UI
       float max;
       for (auto&& [l, r] : audio_output) {
         float sum = l + r;
         if (std::abs(sum - max) > 0) {
           max = sum;
         }
       }
       if (max == 0) {
         debugInfo.buffers_lost++;
       }
       debugInfo.audio_graph.push(max / 2.f);
 #endif
   }
running()
bool otto::service::audio::running () noexcept
Check if audio is being processed
Returns
true if [start()]() has been called and [shutdown()]() hasn't
Definition at line 90 of file audio.cpp.
   {
     return _running;
   }
samplerate()
int otto::service::audio::samplerate () noexcept
Get the current samplerate.
Definition at line 63 of file audio.cpp.
References otto::service::audio::AlsaAudioDriver::get(), and otto::service::audio::AlsaAudioDriver::samplerate.
Referenced by otto::core::audio::detail::register_faust_wrapper_events().
{
     return AudioDriver::get().samplerate;
   }
send_midi_event()
void otto::service::audio::send_midi_event (core::midi::AnyMidiEvent) noexcept
Send a midi event into the system.
The core::midi namespace has some nice utils for constructing events.
Definition at line 113 of file audio.cpp.
References otto::service::audio::AlsaAudioDriver::get(), and otto::service::audio::AlsaAudioDriver::send_midi_event().
Referenced by otto::board::ui::handle_keyevent().
   {
     AudioDriver::get().send_midi_event(std::move(evt));
   }
shutdown()
void otto::service::audio::shutdown ()
Close the audio driver.
Definition at line 85 of file audio.cpp.
References otto::service::audio::AlsaAudioDriver::get(), and otto::service::audio::AlsaAudioDriver::shutdown().
   {
     AudioDriver::get().shutdown();
   }
start()
void otto::service::audio::start () noexcept
Start audio processing
running() == true
Definition at line 80 of file audio.cpp.
   {
     _running = true;
   }