OTTO: otto::std Namespace Reference
otto::std Namespace Reference
Functions
template<class Visitor , class Base , class Variant >
constexpr decltype(auto) visit (Visitor &&vis, otto::util::basic_variant_w_base< Base, Variant > &var)
template<class T , class Base , class Variant >
constexpr decltype(auto) get (otto::util::basic_variant_w_base< Base, Variant > &var)
Function Documentation
visit()
template<class Visitor , class Base , class Variant > constexpr decltype(auto) otto::std::visit (Visitor && vis, otto::util::basic_variant_w_base< Base, Variant > & var) constexpr
Definition at line 175 of file variant_w_base.hpp.
Referenced by otto::util::match().
get()
template<class T , class Base , class Variant > constexpr decltype(auto) otto::std::get (otto::util::basic_variant_w_base< Base, Variant > & var) constexpr
Definition at line 182 of file variant_w_base.hpp.
Referenced by otto::core::props::PropertyImpl< T, tag_list< Tags... > >::operator const value_type &(), and otto::core::props::OTTO_PROPS_MIXIN_LEAF().