OTTO: otto::core::props Namespace Reference
otto::core::props Namespace Reference
Namespaces
detail
mixin
Classes
struct add_required
struct add_required< tag_list< Tags... > >
struct branch_base
struct common
struct compare_tags
struct default_mixins
struct default_mixins< bool >
struct default_mixins< double >
struct default_mixins< float >
struct default_mixins< int >
struct default_mixins< void >
struct FaustLink
struct get_tag_list
struct Hook
A hook implementation concept.
struct HookTag
Concept of a hook tag type.
struct HookWithValue
Concept of a Hook with a value.
struct inherit_from_all
struct inherit_from_all_mixins
struct inherit_from_all_mixins< ValueType, tag_list< Tags... > >
struct is_initializer
struct is_initializer< Initializer, std::void_t< decltype(Initializer::_this_is_a_mixin_initializer_type_), typename Initializer::tag_type > >
struct MixinImpl
struct MixinTag
Concept for a Tag used to identify a mixin.
struct MixinValue
struct no
struct NonVoid
struct normalize_tags
Uniquify and sort tags by their name.
struct Properties
struct properties_base
struct PropertiesImpl
struct property_base
Base class of all properties, leaves and branches both.
struct PropertyImpl
struct PropertyImpl< T, tag_list< Tags... > >
struct remove_disabled_tags
struct TaggedTuple
Typedefs
template<typename ValueType , typename TagList >
using inherits_from_mixins_t = meta::_t< inherit_from_all_mixins< ValueType, TagList > >
using no_defaults = no< default_mixins< void > >
template<typename... Tags>
using tag_list = meta::list< Tags... >
Type used to list tags.
template<typename ValueType , typename... Tags>
using Property = PropertyImpl< ValueType, meta::_t< get_tag_list< ValueType, Tags... > >>
using no_serialize = no< serializable >
Enumerations
enum HookOrder {
HookOrder::Before, HookOrder::Early, HookOrder::Middle, HookOrder::Late,
HookOrder::After
}
Functions
constexpr bool compare_str (const char *a, const char *b)
template<typename Tag , typename... Args>
auto make_initializer (Args &&... args)
OTTO_PROPS_MIXIN (faust_link)
OTTO_PROPS_MIXIN_INTERFACE (faust_link)
OTTO_PROPS_MIXIN_BRANCH (faust_link)
OTTO_PROPS_MIXIN_LEAF (faust_link)
OTTO_PROPS_MIXIN (has_limits)
OTTO_PROPS_MIXIN_LEAF (has_limits)
OTTO_PROPS_MIXIN (pow2, REQUIRES(steppable))
OTTO_PROPS_MIXIN_LEAF (pow2)
OTTO_PROPS_MIXIN (exp_step)
OTTO_PROPS_MIXIN_LEAF (exp_step)
OTTO_PROPS_MIXIN (serializable)
OTTO_PROPS_MIXIN_BRANCH (serializable)
OTTO_PROPS_MIXIN_LEAF (serializable)
OTTO_PROPS_MIXIN (steppable, HOOKS((on_step, value_type)))
OTTO_PROPS_MIXIN_LEAF (steppable)
OTTO_PROPS_MIXIN (wrap, REQUIRES(has_limits))
OTTO_PROPS_MIXIN_LEAF (wrap)
Variables
template<typename TagList , typename T >
constexpr const bool contains_tag_v = meta::_v<meta::contains<TagList, T>>
Type trait to see if a tag_list contains a tag.
Typedef Documentation
inherits_from_mixins_t
template<typename ValueType , typename TagList > using otto::core::props::inherits_from_mixins_t = typedef meta::_t<inherit_from_all_mixins<ValueType, TagList> >
This type inherits from all mixins matched by Tags
See also
inherit_from_all_mixins_impl TagList == tag_list<...>
Definition at line 71 of file tag_list.hpp.
no_defaults
using otto::core::props::no_defaults = typedef no<default_mixins<void> >
Definition at line 93 of file tag_list.hpp.
no_serialize
using otto::core::props::no_serialize = typedef no<serializable>
Definition at line 47 of file props.hpp.
Property
template<typename ValueType , typename... Tags> using otto::core::props::Property = typedef PropertyImpl<ValueType, meta::_t<get_tag_list<ValueType, Tags...> >>
Definition at line 45 of file props.hpp.
tag_list
template<typename... Tags> using otto::core::props::tag_list = typedef meta::list<Tags...>
Type used to list tags.
Definition at line 16 of file type_traits.hpp.
Enumeration Type Documentation
HookOrder
enum otto::core::props::HookOrder strong
Order of hook handlers.
This is the second template argument to hook implementations, and is used to sort handlers.
Enumerator
Before
Should only read hook values.
Early
Change values early.
Middle
Change values in the middle. Default.
Late
Change values late.
After
Should only read hook values.
Definition at line 13 of file base.hpp.
{
     Before,
     Early,
     Middle,
     Late,
     After,
   };
Function Documentation
compare_str()
constexpr bool otto::core::props::compare_str (const char * a, const char * b)
Definition at line 18 of file tag_list.hpp.
   {
     for (; (*a != '\0') && (*b != '\0'); ++a, (void) ++b) {
       if (*a < *b) return true;
       if (*b < *a) return false;
     }
     return (*a == '\0') && (*b != '\0');
   }
make_initializer()
template<typename Tag , typename... Args> auto otto::core::props::make_initializer (Args &&... args)
Definition at line 124 of file tag_list.hpp.
   {
     return TaggedTuple<Tag, Args...>{
       std::forward_as_tuple(std::forward<Args>(args)...)};
   }
OTTO_PROPS_MIXIN() [1/7]
otto::core::props::OTTO_PROPS_MIXIN (has_limits)
OTTO_PROPS_MIXIN() [2/7]
otto::core::props::OTTO_PROPS_MIXIN (wrap , REQUIRES(has_limits))
OTTO_PROPS_MIXIN() [3/7]
otto::core::props::OTTO_PROPS_MIXIN (pow2 , REQUIRES(steppable))
OTTO_PROPS_MIXIN() [4/7]
otto::core::props::OTTO_PROPS_MIXIN (steppable , HOOKS((on_step, value_type)))
OTTO_PROPS_MIXIN() [5/7]
otto::core::props::OTTO_PROPS_MIXIN (faust_link)
OTTO_PROPS_MIXIN() [6/7]
otto::core::props::OTTO_PROPS_MIXIN (serializable)
OTTO_PROPS_MIXIN() [7/7]
otto::core::props::OTTO_PROPS_MIXIN (exp_step)
OTTO_PROPS_MIXIN_BRANCH() [1/2]
otto::core::props::OTTO_PROPS_MIXIN_BRANCH (faust_link)
Definition at line 30 of file faust_link.hpp.
References otto::core::props::property_base::as(), and otto::util::find_if().
{
     void refresh_links() override
     {
       for (property_base& itf : children()) {
         if (itf.is<faust_link>()) itf.as<faust_link>().refresh_links();
       }
     }
     void register_link(std::vector<std::string>::const_iterator first,
                        std::vector<std::string>::const_iterator last,
                        FaustLink link) override
     {
       auto found = util::find_if(
         children(),
         [& name = *first](auto&& child) { return child.get().name() == name; });
       if (found != children().end()) {
         auto& item = static_cast<property_base&>(*found);
         item.as<faust_link>().register_link(std::move(++first), std::move(last),
                                             link);
       } else {
         LOGW("Developer warning: Attempt to register a faust link for {} failed", *first);
       }
     }
     void clear() override {
       for (property_base& itf : children()) {
         if (itf.is<faust_link>()) itf.as<faust_link>().clear();
       }
     }
   };
OTTO_PROPS_MIXIN_BRANCH() [2/2]
otto::core::props::OTTO_PROPS_MIXIN_BRANCH (serializable)
Definition at line 35 of file serializable.hpp.
References otto::core::props::property_base::as(), and otto::util::find_if().
{
     void from_json(const nlohmann::json& o) override
     {
       CHECK_F(o.is_object(), "Expected json object");
       for (auto it = o.begin(); it != o.end(); ++it) {
         auto found = util::find_if(
           children(), [key = it.key()](property_base& prop) { return prop.name() == key; });
         if (found != children().end()) {
           auto& prop = static_cast<property_base&>(*found);
           if (prop.is<serializable>()) {
             auto& item = prop.as<serializable>();
             if (item.do_serialize) item.from_json(it.value());
           }
         } else {
           throw util::exception("No property found matching {}", it.key());
         }
       }
     }
     nlohmann::json to_json() const override
     {
       auto js = nlohmann::json::object();
       for (property_base& prop : children()) {
         if (prop.is<serializable>()) {
           if (prop.as<serializable>().do_serialize)
             js[prop.name()] = prop.as<serializable>().to_json();
         }
       }
       return js;
     }
   };
OTTO_PROPS_MIXIN_INTERFACE()
otto::core::props::OTTO_PROPS_MIXIN_INTERFACE (faust_link)
Definition at line 22 of file faust_link.hpp.
{
     virtual void refresh_links()          = 0;
     virtual void register_link(std::vector<std::string>::const_iterator first,
                                std::vector<std::string>::const_iterator last,
                                FaustLink) = 0;
     virtual void clear() = 0;
   };
OTTO_PROPS_MIXIN_LEAF() [1/7]
otto::core::props::OTTO_PROPS_MIXIN_LEAF (wrap)
Definition at line 13 of file wrap.hpp.
{
     OTTO_PROPS_MIXIN_DECLS(wrap);
     void on_hook(hook<has_limits::hooks::on_exceeded> & hook)
     {
       auto& hl = this->as<has_limits>();
       if (hook.value() < hl.min) {
         hook.value() =
           hl.max - ((hl.min - (is<steppable>() ? as<steppable>().step_size : 1)) - hook.value());
       } else if (hook.value() > hl.max) {
         hook.value() =
           hl.min + (hook.value() - (hl.max + (is<steppable>() ? as<steppable>().step_size : 1)));
       }
     }
   };
OTTO_PROPS_MIXIN_LEAF() [2/7]
otto::core::props::OTTO_PROPS_MIXIN_LEAF (pow2)
Definition at line 14 of file pow2.hpp.
{
     OTTO_PROPS_MIXIN_DECLS(pow2);
     value_type pow_2() const
     {
       return pow2_;
     }
     void on_hook(hook<common::hooks::on_set, HookOrder::After> const hook)
     {
       pow2_ = std::pow(2, hook.value());
     }
   private:
     value_type pow2_;
   };
OTTO_PROPS_MIXIN_LEAF() [3/7]
otto::core::props::OTTO_PROPS_MIXIN_LEAF (steppable)
Definition at line 15 of file steppable.hpp.
References otto::util::underlying().
{
     OTTO_PROPS_MIXIN_DECLS(steppable);
     static_assert(util::is_number_or_enum_v<value_type> || std::is_same_v<value_type, bool>,
                   "The 'steppable' mixin requires a number, bool or enum type");
     void init(value_type p_step_size = value_type{1})
     {
       // unwrap enums
       step_size = util::underlying(p_step_size);
     }
     void step(int n = 1)
     {
       auto& prop = dynamic_cast<property_type&>(*this);
       _current_step_count = n;
       auto new_value = run_hook<hooks::on_step>([&] () -> value_type {
         if constexpr (std::is_same_v<bool, value_type>) {
           return (prop.get() + n) % 2;
         } else if constexpr (std::is_enum_v<value_type>) {
           return static_cast<value_type>(util::underlying(prop.get()) + n * step_size);
         } else {
           return prop.get() + n * step_size;
         }
       }());
       prop.set(new_value);
     }
     util::enum_decay_t<value_type> step_size = 1;
     int _current_step_count;
   };
OTTO_PROPS_MIXIN_LEAF() [4/7]
otto::core::props::OTTO_PROPS_MIXIN_LEAF (has_limits)
Definition at line 20 of file has_limits.hpp.
References otto::util::underlying().
{
     OTTO_PROPS_MIXIN_DECLS(has_limits);
     static_assert(std::is_enum_v<value_type> || util::is_less_than_comparable_v<value_type>,
                   "Property type must be less than comparable for has_limits");
     static_assert(std::is_enum_v<value_type> || util::is_greater_than_comparable_v<value_type>,
                   "Property type must be greater than comparable for has_limits");
     void init(const value_type& pmin, const value_type& pmax)
     {
       min = util::underlying(pmin);
       max = util::underlying(pmax);
     }
     void on_hook(hook<common::hooks::on_set, HookOrder::Early> & hook)
     {
       auto& val = hook.value();
       if (util::underlying(val) < min) {
         auto hv = run_hook<hooks::on_exceeded>(util::underlying(val));
         hook.value() = static_cast<value_type>(hv == util::underlying(val) ? min : hv);
       } else if (util::underlying(val) > max) {
         auto hv = run_hook<hooks::on_exceeded>(util::underlying(val));
         hook.value() = static_cast<value_type>(hv == util::underlying(val) ? max : hv);
       }
     }
     value_type normalize() const
     {
       static_assert(!std::is_enum_v<value_type>,
                     "has_limits::normalize() is unavaliable for enums");
       auto& prop = dynamic_cast<property_type const&>(*this);
       return (prop.get() - min) / (max - min);
     }
     util::enum_decay_t<value_type> min = std::numeric_limits<util::enum_decay_t<value_type>>::min();
     util::enum_decay_t<value_type> max = std::numeric_limits<util::enum_decay_t<value_type>>::max();
   };
OTTO_PROPS_MIXIN_LEAF() [5/7]
otto::core::props::OTTO_PROPS_MIXIN_LEAF (exp_step)
Definition at line 33 of file pow2.hpp.
{
     OTTO_PROPS_MIXIN_DECLS(exp_step);
     auto on_hook(hook<steppable::hooks::on_step, HookOrder::After> const & hook)
     {
       auto& prop = dynamic_cast<property_type&>(*this);
       return prop.get() * std::pow((float) as<steppable>().step_size, (float) as<steppable>()._current_step_count);
     }
   };}
OTTO_PROPS_MIXIN_LEAF() [6/7]
otto::core::props::OTTO_PROPS_MIXIN_LEAF (faust_link)
Definition at line 61 of file faust_link.hpp.
References otto::core::props::FaustLink::faust_var_, and otto::core::props::FaustLink::ToFaust.
{
     OTTO_PROPS_MIXIN_DECLS(faust_link);
     void init(FaustLink::Type type)
     {
       type_ = type;
     }
     void refresh_links() override
     {
       auto& value = dynamic_cast<property_type*>(this)->get();
       if (type_ == FaustLink::Type::ToFaust) {
         for (auto&& fl : faust_links_) {
           *fl = value;
         }
       } else {
         for (auto&& fl : faust_links_) {
           dynamic_cast<property_type*>(this)->set(*fl);
         }
       }
     }
     void add_link(const FaustLink& fl)
     {
       faust_links_.push_back(fl.faust_var_);
     }
     void register_link(std::vector<std::string>::const_iterator first,
                        std::vector<std::string>::const_iterator last,
                        FaustLink link) override
     {
       add_link(std::move(link));
     }
     void clear() override
     {
       faust_links_.clear();
     }
     void on_hook(hook<common::hooks::on_set, HookOrder::After> & hook)
     {
       if (type_ == FaustLink::Type::ToFaust) {
         for (auto&& fl : faust_links_) {
           *fl = hook.value();
         }
       }
     }
     const FaustLink::Type& type = type_;
   private:
     FaustLink::Type type_ = FaustLink::Type::ToFaust;
     std::vector<float*> faust_links_;
   };
OTTO_PROPS_MIXIN_LEAF() [7/7]
otto::core::props::OTTO_PROPS_MIXIN_LEAF (serializable)
Definition at line 67 of file serializable.hpp.
References otto::util::copy(), and otto::util::underlying().
{
     OTTO_PROPS_MIXIN_DECLS(serializable);
     void init(bool do_serialize)
     {
       this->do_serialize = do_serialize;
     }
     nlohmann::json to_json() const override
     {
       // Unwrap enums
       return util::underlying(dynamic_cast<property_type const&>(*this).get());
     }
     void from_json(const nlohmann::json& js) override
     {
       if constexpr (std::is_enum_v<value_type>) {
         dynamic_cast<property_type&>(*this).set(
           static_cast<value_type>(static_cast<std::underlying_type_t<value_type>>(js)));
       } else if constexpr (detail::is_array<value_type>::value) {
         std::vector<typename value_type::value_type> vec = js;
         if (vec.size() == std::tuple_size_v<value_type>) {
           value_type array;
           util::copy(vec, array.begin());
           dynamic_cast<property_type&>(*this).set(std::move(array));
         } else {
           throw util::exception("Array had wront size");
         }
       } else {
         dynamic_cast<property_type&>(*this).set(js);
       }
     }
   };
Variable Documentation
contains_tag_v
template<typename TagList , typename T > constexpr const bool otto::core::props::contains_tag_v = meta::_v<meta::contains<TagList, T>>
Type trait to see if a tag_list contains a tag.
Definition at line 48 of file tag_list.hpp.