OTTO: otto::service::ui Namespace Reference
otto::service::ui Namespace Reference
Namespaces
impl
These functions are to be called only by the graphics drivers.
Typedefs
using KeyHandler = std::function< void(core::ui::Key k)>
Function type for key handlers.
Functions
bool is_pressed (core::ui::Key k) noexcept
Check if a key is currently pressed.
void select_engine (const std::string &engine_name)
Select an engine by name.
void select_engine (core::engines::AnyEngine &engine)
Select an engine.
const std::string & selected_engine_name ()
Get the currently selected engine.
void init ()
void display (Screen &screen)
core::ui::Screen * current_screen ()
void register_key_handler (core::ui::Key k, KeyHandler press_handler, KeyHandler release_handler=nullptr)
Register a key handler.
void main_ui_loop ()
Typedef Documentation
KeyHandler
using otto::service::ui::KeyHandler = typedef std::function<void(core::ui::Key k)>
Function type for key handlers.
Definition at line 33 of file ui.hpp.
Function Documentation
current_screen()
core::ui::Screen * otto::service::ui::current_screen ()
Definition at line 95 of file ui.cpp.
Referenced by otto::service::engines::init().
{
     return cur_screen;
   }
display()
void otto::service::ui::display (core::ui::Screen & screen)
Display a screen.
Calls [Screen::on_hide]() for the old screen, and then [Screen::on_show]() for the new screen
Definition at line 88 of file ui.cpp.
References otto::core::ui::Screen::on_show().
Referenced by otto::service::engines::init(), and select_engine().
   {
     cur_screen->on_hide();
     cur_screen = &screen;
     cur_screen->on_show();
   }
init()
void otto::service::ui::init ()
Definition at line 71 of file ui.cpp.
References otto::service::state::attach(), otto::board::ui::j, and select_engine().
   {
     register_screen_keys();
     auto load = [](const nlohmann::json& j) {
       if (j.is_object()) {
         _selected_engine_name = j["SelectedEngine"];
       }
       select_engine(_selected_engine_name);
     };
     auto save = []() { return nlohmann::json({{"SelectedEngine", _selected_engine_name}}); };
     service::state::attach("UI", load, save);
   }
is_pressed()
bool otto::service::ui::is_pressed (Key k) noexcept
Check if a key is currently pressed.
Definition at line 39 of file ui.cpp.
References otto::board::ui::k.
Referenced by otto::service::engines::init().
   {
     return keys[static_cast<unsigned>(k)];
   }
main_ui_loop()
void otto::service::ui::main_ui_loop ()
The main ui loop
This sets up all the device specific graphics, and calls [internal::draw_frame]() 60 times pr second, until [global::running]() is false, or the graphics are exitted by the user. It is also responsible for listening to keyevents, and calling [internal::keypress]() and [internal::keyrelease]() as apropriate.
On some platforms (OSX), all OpenGL calls must be made from the main thread, therefore this function is called from main().
One important note, is that this function is implemented in the graphics drivers. The drivers can be found in the "egl" (RPI native) and "glfw" (Windowing systems) folders.
Definition at line 28 of file egl_ui.cpp.
References otto::board::ui::EGLConnection::beginFrame(), otto::core::ui::vg::Canvas::clearColor(), otto::service::ui::impl::draw_frame(), otto::board::ui::EGLConnection::draw_size, otto::board::ui::e, otto::board::ui::EGLConnection::eglData, otto::board::ui::EGLConnection::endFrame(), otto::global::exit(), otto::board::ui::EGLConnection::exit(), otto::core::ui::vg::Canvas::fillStyle(), otto::core::ui::vg::Canvas::fillText(), otto::service::ui::impl::flush_events(), otto::core::ui::vg::Canvas::font(), otto::global::graphics_error, otto::board::ui::EGLConnection::Size::height, otto::board::ui::EGLConnection::init(), otto::global::running(), otto::global::ui_closed, and otto::board::ui::EGLConnection::Size::width.
   {
     EGLConnection egl;
     egl.init();
     #if OTTO_USE_FBCP
     auto fbcp = RpiFBCP{egl.eglData};
     bool use_fbcp = true;
     try {
       fbcp.init();
     } catch (util::exception& e) {
       LOGW("Error starting FBCP: {}", e.what());
       LOGI("If you are using an HDMI screen you probably meant to compile with OTTO_USE_FBCP=OFF");
       LOGI("FBCP has been disabled. /dev/fb0 will not be copied to /dev/fb1");
       use_fbcp = false;
     }
     #endif
     NVGcontext* nvg =
       nvgCreateGLES2(NVG_ANTIALIAS | NVG_STENCIL_STROKES | NVG_DEBUG);
     if (nvg == NULL) {
       LOGF("Could not init nanovg.\n");
       global::exit(global::ErrorCode::graphics_error);
       return;
     }
     vg::Canvas canvas(nvg, vg::width, vg::height);
     vg::initUtils(canvas);
     // I am unable to resize the EGL display, it is fixed at 720x480px, so this
     // is the temporary fix. Stretch everything to fill the display, and then
     // scale it down in fbcp. Actually only rendering 320x240 should also help
     // performance, so it is definately desired at some point
     float xscale = egl.draw_size.width / float(vg::width);
     float yscale = egl.draw_size.height / float(vg::height);
     canvas.setSize(egl.draw_size.width, egl.draw_size.height);
     using std::chrono::duration;
     using std::chrono::nanoseconds;
     using clock = std::chrono::high_resolution_clock;
     auto one_second = 1e9f;
     auto targetFPS = config["FPS"].get<float>();
     auto waitTime = nanoseconds(int(one_second / targetFPS));
     auto t0 = clock::now();
     bool showFps = config["Debug"];
     float fps;
     duration<double> lastFrameTime;
     std::thread kbd_thread = std::thread(otto::service::ui::read_keyboard);
     while (global::running()) {
       t0 = clock::now();
       otto::service::ui::impl::flush_events();
       // Update and render
       egl.beginFrame();
       canvas.clearColor(vg::Colours::Black);
       canvas.begineFrame(egl.draw_size.width, egl.draw_size.height);
       canvas.scale(xscale, yscale);
       ui::impl::draw_frame(canvas);
       if (showFps) {
         canvas.beginPath();
         canvas.font(15);
         canvas.font(vg::Fonts::Norm);
         canvas.fillStyle(vg::Colours::White);
         canvas.textAlign(vg::TextAlign::Left, vg::TextAlign::Baseline);
         canvas.fillText(fmt::format("{:.2f} FPS", fps), {0, vg::height});
       }
       canvas.endFrame();
       egl.endFrame();
       #if OTTO_USE_FBCP
       if (use_fbcp) fbcp.copy();
       #endif
       lastFrameTime = clock::now() - t0;
       std::this_thread::sleep_for(waitTime - lastFrameTime);
       auto ms = std::chrono::duration_cast<nanoseconds>(lastFrameTime).count();
       fps = one_second / ms;
     }
     nvgDeleteGLES2(nvg);
     egl.exit();
     global::exit(global::ErrorCode::ui_closed);
   }
register_key_handler()
void otto::service::ui::register_key_handler (Key k, KeyHandler press_handler, KeyHandler release_handler)
Register a key handler.
Definition at line 99 of file ui.cpp.
References otto::board::ui::k.
Referenced by otto::service::engines::init().
   {
     key_handlers.emplace(k, std::pair{std::move(press_handler), std::move(release_handler)});
   }
select_engine() [1/2]
void otto::service::ui::select_engine (const std::string & engine_name)
Select an engine by name.
Definition at line 44 of file ui.cpp.
References otto::service::engines::by_name(), and display().
Referenced by otto::service::engines::init(), and init().
   {
     _selected_engine_name = engine_name;
     auto engine = engines::by_name(engine_name);
     if (!engine) {
       engine = engines::by_name(initial_engine);
     }
     if (engine != nullptr) {
       display(engine->screen());
       _selected_engine_name = engine_name;
     }
   }
select_engine() [2/2]
void otto::service::ui::select_engine (core::engines::AnyEngine & engine)
Select an engine.
Definition at line 58 of file ui.cpp.
References display(), otto::core::engines::AnyEngine::name(), and otto::core::engines::AnyEngine::screen().
   {
     display(engine.screen());
     _selected_engine_name = engine.name();
   }
selected_engine_name()
const std::string & otto::service::ui::selected_engine_name ()
Get the currently selected engine.
Definition at line 64 of file ui.cpp.
   {
     return _selected_engine_name;
   }