OTTO: otto::filesystem Namespace Reference
otto::filesystem Namespace Reference
Namespaces
px
Classes
class directory_entry
class directory_iterator
class file_status
class filesystem_error
class path
class recursive_directory_iterator
struct space_info
Typedefs
using StringView = std::basic_string_view< path::value_type >
using DEntr = directory_entry
using DIter = directory_iterator
using RDIter = recursive_directory_iterator
using file_time_type = std::chrono::time_point< std::chrono::system_clock >
Enumerations
enum file_type {
file_type::none = 0, file_type::not_found, file_type::regular, file_type::directory,
file_type::symlink, file_type::block, file_type::character, file_type::fifo,
file_type::socket, file_type::unknown
}
File type enum.
enum copy_options {
copy_options::none = 0, copy_options::skip_existing, copy_options::overwrite_existing, copy_options::update_existing,
copy_options::recursive, copy_options::copy_symlinks, copy_options::skip_symlinks, copy_options::directories_only,
copy_options::create_symlinks, copy_options::create_hard_links
}
enum perms {
perms::none = 0, perms::owner_read = 0400, perms::owner_write = 0200, perms::owner_exec = 0100,
perms::owner_all = 0700, perms::group_read = 0040, perms::group_write = 0020, perms::group_exec = 0010,
perms::group_all = 0070, perms::others_read = 0004, perms::others_write = 0002, perms::others_exec = 0001,
perms::others_all = 0007, perms::all = 0777, perms::set_uid = 04000, perms::set_gid = 02000,
perms::sticky_bit = 01000, perms::mask = 07777, perms::unknown = 0xFFFF
}
enum perm_options { perm_options::replace, perm_options::add, perm_options::remove, perm_options::nofollow }
enum directory_options { directory_options::none, directory_options::follow_directory_symlink, directory_options::skip_permission_denied }
Functions
file_type operator & (file_type lhs, file_type rhs)
file_type operator| (file_type lhs, file_type rhs)
bool operator!= (file_type lhs, file_type rhs)
copy_options operator & (copy_options lhs, copy_options rhs)
copy_options operator| (copy_options lhs, copy_options rhs)
bool operator!= (copy_options lhs, copy_options rhs)
perms operator & (perms lhs, perms rhs)
perms operator| (perms lhs, perms rhs)
bool operator!= (perms lhs, perms rhs)
perm_options operator & (perm_options lhs, perm_options rhs)
perm_options operator| (perm_options lhs, perm_options rhs)
bool operator!= (perm_options lhs, perm_options rhs)
directory_options operator & (directory_options lhs, directory_options rhs)
directory_options operator| (directory_options lhs, directory_options rhs)
bool operator!= (directory_options lhs, directory_options rhs)
void swap (path &lhs, path &rhs) noexcept
size_t hash_value (const path &p) noexcept
bool operator< (const path &lhs, const path &rhs) noexcept
bool operator<= (const path &lhs, const path &rhs) noexcept
bool operator> (const path &lhs, const path &rhs) noexcept
bool operator>= (const path &lhs, const path &rhs) noexcept
bool operator== (const path &lhs, const path &rhs) noexcept
bool operator!= (const path &lhs, const path &rhs) noexcept
path operator/ (const path &lhs, const path &rhs) noexcept
directory_iterator begin (directory_iterator iter) noexcept
directory_iterator end (const directory_iterator &iter) noexcept
RDIter begin (RDIter iter) noexcept
RDIter end (const RDIter &iter) noexcept
path absolute (const path &p)
path absolute (const path &p, std::error_code &ec)
path canonical (const path &p)
path canonical (const path &p, std::error_code &ec)
bool copy_file (const path &from, const path &to)
bool copy_file (const path &from, const path &to, std::error_code &ec) noexcept
bool copy_file (const path &from, const path &to, copy_options options)
bool copy_file (const path &from, const path &to, copy_options options, std::error_code &ec) noexcept
bool create_directories (const path &p)
bool create_directories (const path &p, std::error_code &ec) noexcept
bool create_directory (const path &p)
bool create_directory (const path &p, std::error_code &ec) noexcept
path current_path ()
path current_path (std::error_code &ec)
void current_path (const path &p)
void current_path (const path &p, std::error_code &ec) noexcept
bool equivalent (const path &p1, const path &p2)
bool equivalent (const path &p1, const path &p2, std::error_code &ec) noexcept
bool exists (file_status status) noexcept
bool exists (const path &p)
bool exists (const path &p, std::error_code &ec) noexcept
bool is_block_file (file_status status) noexcept
bool is_block_file (const path &p)
bool is_block_file (const path &p, std::error_code &ec) noexcept
bool is_character_file (file_status status) noexcept
bool is_character_file (const path &p)
bool is_character_file (const path &p, std::error_code &ec) noexcept
bool is_directory (file_status status) noexcept
bool is_directory (const path &p)
bool is_directory (const path &p, std::error_code &ec) noexcept
bool is_fifo (file_status status) noexcept
bool is_fifo (const path &p)
bool is_fifo (const path &p, std::error_code &ec) noexcept
bool is_other (file_status status) noexcept
bool is_other (const path &p)
bool is_other (const path &p, std::error_code &ec) noexcept
bool is_regular_file (file_status status) noexcept
bool is_regular_file (const path &p)
bool is_regular_file (const path &p, std::error_code &ec) noexcept
bool is_socket (file_status status) noexcept
bool is_socket (const path &p)
bool is_socket (const path &p, std::error_code &ec) noexcept
bool is_symlink (file_status status) noexcept
bool is_symlink (const path &p)
bool is_symlink (const path &p, std::error_code &ec) noexcept
uintmax_t file_size (const path &p)
uintmax_t file_size (const path &p, std::error_code &ec) noexcept
uintmax_t hard_link_count (const path &p)
uintmax_t hard_link_count (const path &p, std::error_code &ec) noexcept
file_time_type last_write_time (const path &p)
file_time_type last_write_time (const path &p, std::error_code &ec) noexcept
file_status status (const path &p)
file_status status (const path &p, std::error_code &ec) noexcept
file_status symlink_status (const path &p)
file_status symlink_status (const path &p, std::error_code &ec) noexcept
bool remove (const path &p)
bool remove (const path &p, std::error_code &ec) noexcept
uintmax_t remove_all (const path &p)
uintmax_t remove_all (const path &p, std::error_code &ec) noexcept
void rename (const path &from, const path &to)
void rename (const path &from, const path &to, std::error_code &ec) noexcept
void resize_file (const path &p, uintmax_t size)
void resize_file (const path &p, uintmax_t size, std::error_code &ec) noexcept
template<class charT , class traits >
std::basic_ostream< charT, traits > & operator<< (std::basic_ostream< charT, traits > &os, const path &p)
template<class charT , class traits >
std::basic_istream< charT, traits > & operator>> (std::basic_istream< charT, traits > &is, path &p)
template<class Source >
path u8path (const Source &source)
template<class InputIterator >
path u8path (InputIterator first, InputIterator last)
void copy (const path &from, const path &to)
void copy (const path &from, const path &to, std::error_code &ec) noexcept
void copy (const path &from, const path &to, copy_options options)
void copy (const path &from, const path &to, copy_options options, std::error_code &ec) noexcept
void copy_symlink (const path &existing_symlink, const path &new_symlink)
void copy_symlink (const path &existing_symlink, const path &new_symlink, std::error_code &ec) noexcept
bool create_directory (const path &p, const path &attributes)
bool create_directory (const path &p, const path &attributes, std::error_code &ec) noexcept
void create_directory_symlink (const path &to, const path &new_symlink)
void create_directory_symlink (const path &to, const path &new_symlink, std::error_code &ec) noexcept
void create_hard_link (const path &to, const path &new_hard_link)
void create_hard_link (const path &to, const path &new_hard_link, std::error_code &ec) noexcept
void create_symlink (const path &to, const path &new_symlink)
void create_symlink (const path &to, const path &new_symlink, std::error_code &ec) noexcept
void permissions (const path &p, perms prms, perm_options opts=perm_options::replace)
void permissions (const path &p, perms prms, std::error_code &ec) noexcept
void permissions (const path &p, perms prms, perm_options opts, std::error_code &ec)
path proximate (const path &p, std::error_code &ec)
path proximate (const path &p, const path &base=current_path())
path proximate (const path &p, const path &base, std::error_code &ec)
path read_symlink (const path &p)
path read_symlink (const path &p, std::error_code &ec)
path relative (const path &p, std::error_code &ec)
path relative (const path &p, const path &base=current_path())
path relative (const path &p, const path &base, std::error_code &ec)
space_info space (const path &p)
space_info space (const path &p, std::error_code &ec) noexcept
bool status_known (file_status s) noexcept
path temp_directory_path ()
path temp_directory_path (std::error_code &ec)
path weakly_canonical (const path &p)
path weakly_canonical (const path &p, std::error_code &ec)
Typedef Documentation
DEntr
using otto::filesystem::DEntr = typedef directory_entry
Definition at line 815 of file filesystem.cpp.
DIter
using otto::filesystem::DIter = typedef directory_iterator
Definition at line 1044 of file filesystem.cpp.
file_time_type
using otto::filesystem::file_time_type = typedef std::chrono::time_point<std::chrono::system_clock>
Definition at line 276 of file filesystem.hpp.
RDIter
using otto::filesystem::RDIter = typedef recursive_directory_iterator
Definition at line 1184 of file filesystem.cpp.
StringView
using otto::filesystem::StringView = typedef std::basic_string_view<path::value_type>
Definition at line 242 of file filesystem.cpp.
Enumeration Type Documentation
copy_options
enum otto::filesystem::copy_options strong
Enumerator
none
skip_existing
overwrite_existing
update_existing
recursive
copy_symlinks
skip_symlinks
directories_only
create_symlinks
create_hard_links
Definition at line 238 of file filesystem.hpp.
{
     none = 0,
     skip_existing,
     overwrite_existing,
     update_existing,
     recursive,
     copy_symlinks,
     skip_symlinks,
     directories_only,
     create_symlinks,
     create_hard_links
   };
directory_options
enum otto::filesystem::directory_options strong
Enumerator
none
follow_directory_symlink
skip_permission_denied
Definition at line 280 of file filesystem.hpp.
{
     none,
     follow_directory_symlink,
     skip_permission_denied
   };
file_type
enum otto::filesystem::file_type strong
File type enum.
Enumerator
none
not_found
regular
directory
symlink
block
character
fifo
socket
unknown
Definition at line 225 of file filesystem.hpp.
{
     none = 0,
     not_found,
     regular,
     directory,
     symlink,
     block,
     character,
     fifo,
     socket,
     unknown
   };
perm_options
enum otto::filesystem::perm_options strong
Enumerator
replace
add
remove
nofollow
Definition at line 278 of file filesystem.hpp.
 { replace, add, remove, nofollow };
perms
enum otto::filesystem::perms strong
Enumerator
none
owner_read
owner_write
owner_exec
owner_all
group_read
group_write
group_exec
group_all
others_read
others_write
others_exec
others_all
all
set_uid
set_gid
sticky_bit
mask
unknown
Definition at line 251 of file filesystem.hpp.
                    {
     none        = 0,
     owner_read  = 0400,  // Read permission, owner
     owner_write = 0200,  // Write permission, owner
     owner_exec  = 0100,  // Execute/search permission, owner
     owner_all   = 0700,  // Read, write, execute/search by owner;
                          // owner_read | owner_write | owner_exec
     group_read  = 0040,  // Read permission, group
     group_write = 0020,  // Write permission, group
     group_exec  = 0010,  // Execute/search permission, group
     group_all   = 0070,  // Read, write, execute/search by group;
                          // group_read | group_write | group_exec
     others_read  = 0004, // Read permission, others
     others_write = 0002, // Write permission, others
     others_exec  = 0001, // Execute/search permission, others
     others_all   = 0007, // Read, write, execute/search by others;
                          // others_read | others_write | others_exec
     all        = 0777,   // owner_all | group_all | others_all
     set_uid    = 04000,  // Set-user-ID on execution
     set_gid    = 02000,  // Set-group-ID on execution
     sticky_bit = 01000,  // Operating system dependent.
     mask       = 07777,  // all | set_uid | set_gid | sticky_bit
     unknown    = 0xFFFF
   };
Function Documentation
absolute() [1/2]
path otto::filesystem::absolute (const path & p)
Definition at line 1299 of file filesystem.cpp.
References absolute().
Referenced by absolute(), and create_directories().
   {
     std::error_code ec;
     auto tmp = absolute(p, ec);
     if (ec != std::error_code()) {
       throw filesystem_error("In filesystem::absolute", p, ec);
     }
     return tmp;
   }
absolute() [2/2]
path otto::filesystem::absolute (const path & p, std::error_code & ec)
Definition at line 1309 of file filesystem.cpp.
References absolute(), and current_path().
   {
     return current_path() / p;
   }
begin() [1/2]
directory_iterator otto::filesystem::begin (directory_iterator iter) noexcept
Definition at line 1171 of file filesystem.cpp.
References begin().
Referenced by begin().
   {
     return iter;
   }
begin() [2/2]
recursive_directory_iterator otto::filesystem::begin (RDIter iter) noexcept
Definition at line 1287 of file filesystem.cpp.
References begin().
   {
     return iter;
   }
canonical() [1/2]
path otto::filesystem::canonical (const path & p)
Definition at line 1314 of file filesystem.cpp.
References canonical().
Referenced by canonical().
   {
     std::error_code ec;
     auto tmp = canonical(p, ec);
     if (ec != std::error_code()) {
       throw filesystem_error("In filesystem::canonical", p, ec);
     }
     return tmp;
   }
canonical() [2/2]
path otto::filesystem::canonical (const path & p, std::error_code & ec)
Definition at line 1324 of file filesystem.cpp.
References canonical(), and otto::filesystem::path::clear().
   {
     char tmp[PATH_MAX];
     if (realpath(p.c_str(), tmp) == nullptr) {
       ec = {errno, std::system_category()};
     } else {
       ec.clear();
     }
     return path(tmp);
   }
copy() [1/4]
void otto::filesystem::copy (const path & from, const path & to)
copy() [2/4]
void otto::filesystem::copy (const path & from, const path & to, std::error_code & ec) noexcept
copy() [3/4]
void otto::filesystem::copy (const path & from, const path & to, copy_options options)
copy() [4/4]
void otto::filesystem::copy (const path & from, const path & to, copy_options options, std::error_code & ec) noexcept
copy_file() [1/4]
bool otto::filesystem::copy_file (const path & from, const path & to)
Definition at line 1362 of file filesystem.cpp.
References copy_file().
Referenced by copy_file().
   {
     std::error_code ec;
     auto tmp = copy_file(from, to, ec);
     if (ec != std::error_code()) {
       throw filesystem_error("In filesystem::copy_file", from, to, ec);
     }
     return tmp;
   }
copy_file() [2/4]
bool otto::filesystem::copy_file (const path & from, const path & to, std::error_code & ec) noexcept
Definition at line 1372 of file filesystem.cpp.
References copy_file().
   {
     return copy_file(from, to, copy_options::none);
   }
copy_file() [3/4]
bool otto::filesystem::copy_file (const path & from, const path & to, copy_options options)
Definition at line 1377 of file filesystem.cpp.
References copy_file().
   {
     std::error_code ec;
     auto tmp = copy_file(from, to, options, ec);
     if (ec != std::error_code()) {
       throw filesystem_error("In filesystem::copy_file", from, to, ec);
     }
     return tmp;
   }
copy_file() [4/4]
bool otto::filesystem::copy_file (const path & from, const path & to, copy_options options, std::error_code & ec) noexcept
Definition at line 1387 of file filesystem.cpp.
References copy_file(), equivalent(), and is_regular_file().
   {
     auto t = status(to, ec);
     if (!is_regular_file(from) ||
         (t.type() != file_type::not_found &&
          (t.type() != file_type::regular || equivalent(from, to) ||
           (options &
            (copy_options::skip_existing | copy_options::overwrite_existing |
             copy_options::update_existing)) == copy_options::none))) {
       ec.assign(EEXIST, std::system_category());
     } else {
       if (t.type() == file_type::not_found ||
           (options & copy_options::overwrite_existing) != copy_options::none ||
           ((options & copy_options::update_existing) != copy_options::none &&
            last_write_time(from) > last_write_time(to))) {
         std::ifstream src(from, std::ios::binary);
         std::ofstream dst(to, std::ios::binary | std::ios::trunc);
         dst << src.rdbuf();
         if (errno != 0) {
           ec = {errno, std::system_category()};
         } else {
           ec.clear();
           return true;
         }
       }
     }
     return false;
   }
copy_symlink() [1/2]
void otto::filesystem::copy_symlink (const path & existing_symlink, const path & new_symlink)
copy_symlink() [2/2]
void otto::filesystem::copy_symlink (const path & existing_symlink, const path & new_symlink, std::error_code & ec) noexcept
create_directories() [1/2]
bool otto::filesystem::create_directories (const path & p)
Definition at line 1426 of file filesystem.cpp.
References create_directories().
Referenced by create_directories().
   {
     std::error_code ec;
     auto tmp = create_directories(p, ec);
     if (ec != std::error_code()) {
       throw filesystem_error("In filesystem::create_directories", p, ec);
     }
     return tmp;
   }
create_directories() [2/2]
bool otto::filesystem::create_directories (const path & p, std::error_code & ec) noexcept
Definition at line 1436 of file filesystem.cpp.
References absolute(), create_directories(), create_directory(), and is_directory().
   {
     path abs = absolute(p, ec);
     if (ec != std::error_code()) return false;
     path part;
     for (const auto& d : p) {
       part /= d;
       if (!is_directory(part, ec)) {
         if (!create_directory(part, ec)) {
           return false;
         }
       }
       if (ec != std::error_code()) return false;
     }
     return true;
   }
create_directory() [1/4]
bool otto::filesystem::create_directory (const path & p, const path & attributes)
create_directory() [2/4]
bool otto::filesystem::create_directory (const path & p, const path & attributes, std::error_code & ec) noexcept
create_directory() [3/4]
bool otto::filesystem::create_directory (const path & p)
Definition at line 1453 of file filesystem.cpp.
References create_directory().
Referenced by create_directories(), and create_directory().
   {
     std::error_code ec;
     auto tmp = create_directory(p, ec);
     if (ec != std::error_code()) {
       throw filesystem_error("In filesystem::create_directory", p, ec);
     }
     return tmp;
   }
create_directory() [4/4]
bool otto::filesystem::create_directory (const path & p, std::error_code & ec) noexcept
Definition at line 1463 of file filesystem.cpp.
References create_directory(), and is_directory().
   {
     auto error = mkdir(p.c_str(), static_cast<int>(perms::all));
     if (error && !is_directory(p)) {
       ec = {errno, std::system_category()};
     } else {
       ec.clear();
     }
     return !error;
   }
create_directory_symlink() [1/2]
void otto::filesystem::create_directory_symlink (const path & to, const path & new_symlink)
create_directory_symlink() [2/2]
void otto::filesystem::create_directory_symlink (const path & to, const path & new_symlink, std::error_code & ec) noexcept
create_hard_link() [1/2]
void otto::filesystem::create_hard_link (const path & to, const path & new_hard_link)
create_hard_link() [2/2]
void otto::filesystem::create_hard_link (const path & to, const path & new_hard_link, std::error_code & ec) noexcept
create_symlink() [1/2]
void otto::filesystem::create_symlink (const path & to, const path & new_symlink)
create_symlink() [2/2]
void otto::filesystem::create_symlink (const path & to, const path & new_symlink, std::error_code & ec) noexcept
current_path() [1/4]
path otto::filesystem::current_path ()
Definition at line 1492 of file filesystem.cpp.
References current_path().
Referenced by absolute(), and current_path().
   {
     std::error_code ec;
     auto tmp = current_path(ec);
     if (ec != std::error_code()) {
       throw filesystem_error("In filesystem::current_path", ec);
     }
     return tmp;
   }
current_path() [2/4]
path otto::filesystem::current_path (std::error_code & ec)
Definition at line 1502 of file filesystem.cpp.
References otto::filesystem::path::clear(), and current_path().
   {
     char temp[PATH_MAX];
     if (::getcwd(temp, PATH_MAX) == nullptr) {
       ec = {errno, std::system_category()};
     } else {
       ec.clear();
     }
     return path(temp);
   }
current_path() [3/4]
void otto::filesystem::current_path (const path & p)
Definition at line 1513 of file filesystem.cpp.
References current_path().
   {
     std::error_code ec;
     current_path(p, ec);
     if (ec != std::error_code()) {
       throw filesystem_error("In filesystem::current_path", p, ec);
     }
   }
current_path() [4/4]
void otto::filesystem::current_path (const path & p, std::error_code & ec) noexcept
Definition at line 1522 of file filesystem.cpp.
References current_path().
   {
     if (chdir(p.c_str()) == 0) {
       ec = {errno, std::system_category()};
     } else {
       ec.clear();
     }
   }
end() [1/2]
directory_iterator otto::filesystem::end (const directory_iterator & iter) noexcept
Definition at line 1176 of file filesystem.cpp.
References end().
Referenced by end(), otto::filesystem::recursive_directory_iterator::operator++(), and otto::filesystem::recursive_directory_iterator::pop().
   {
     return {};
   }
end() [2/2]
recursive_directory_iterator otto::filesystem::end (const RDIter & iter) noexcept
Definition at line 1292 of file filesystem.cpp.
References end().
   {
     return {};
   }
equivalent() [1/2]
bool otto::filesystem::equivalent (const path & p1, const path & p2)
Definition at line 1531 of file filesystem.cpp.
References equivalent().
Referenced by copy_file(), and equivalent().
   {
     std::error_code ec;
     auto tmp = equivalent(p1, p2, ec);
     if (ec != std::error_code()) {
       throw filesystem_error("In filesystem::equivalent", p1, p2, ec);
     }
     return tmp;
   }
equivalent() [2/2]
bool otto::filesystem::equivalent (const path & p1, const path & p2, std::error_code & ec) noexcept
Definition at line 1541 of file filesystem.cpp.
References equivalent().
   {
     struct stat st1;
     struct stat st2;
     if (::stat(p1.c_str(), &st1) || ::stat(p2.c_str(), &st2)) {
       ec = {errno, std::system_category()};
       return false;
     } else {
       ec.clear();
       return st1.st_dev == st2.st_dev && st1.st_ino == st2.st_ino;
     }
   }
exists() [1/3]
bool otto::filesystem::exists (file_status status) noexcept
Definition at line 1554 of file filesystem.cpp.
References exists(), and otto::filesystem::file_status::type().
Referenced by otto::filesystem::directory_entry::exists(), exists(), is_other(), otto::filesystem::directory_entry::refresh(), remove(), and otto::filesystem::path::replace_extension().
   {
     return status.type() != file_type::not_found;
   }
exists() [2/3]
bool otto::filesystem::exists (const path & p)
Definition at line 1559 of file filesystem.cpp.
References exists().
   {
     return exists(status(p));
   }
exists() [3/3]
bool otto::filesystem::exists (const path & p, std::error_code & ec) noexcept
Definition at line 1564 of file filesystem.cpp.
References exists().
   {
     return exists(status(p, ec));
   }
file_size() [1/2]
uintmax_t otto::filesystem::file_size (const path & p)
Definition at line 1690 of file filesystem.cpp.
   {
     std::error_code ec;
     auto res = file_size(p, ec);
     if (ec != std::error_code()) {
       throw filesystem_error("In filesystem::file_size", p, ec);
     }
     return res;
   }
file_size() [2/2]
uintmax_t otto::filesystem::file_size (const path & p, std::error_code & ec) noexcept
Definition at line 1700 of file filesystem.cpp.
   {
     auto st = px::stat(p, ec);
     return px::file_size(st, ec);
   }
hard_link_count() [1/2]
uintmax_t otto::filesystem::hard_link_count (const path & p)
Definition at line 1706 of file filesystem.cpp.
   {
     std::error_code ec;
     auto res = hard_link_count(p, ec);
     if (ec != std::error_code()) {
       throw filesystem_error("In filesystem::hard_link_count", p, ec);
     }
     return res;
   }
hard_link_count() [2/2]
uintmax_t otto::filesystem::hard_link_count (const path & p, std::error_code & ec) noexcept
Definition at line 1716 of file filesystem.cpp.
   {
     auto st = px::stat(p, ec);
     return px::hard_link_count(st, ec);
   }
hash_value()
size_t otto::filesystem::hash_value (const path & p) noexcept
Definition at line 611 of file filesystem.cpp.
   {
     return std::hash<path::string_type>()(p.generic_string());
   }
is_block_file() [1/3]
bool otto::filesystem::is_block_file (file_status status) noexcept
Definition at line 1569 of file filesystem.cpp.
References is_block_file(), and otto::filesystem::file_status::type().
Referenced by otto::filesystem::directory_entry::is_block_file(), and is_block_file().
   {
     return status.type() == file_type::block;
   }
is_block_file() [2/3]
bool otto::filesystem::is_block_file (const path & p)
Definition at line 1574 of file filesystem.cpp.
References is_block_file().
   {
     return is_block_file(status(p));
   }
is_block_file() [3/3]
bool otto::filesystem::is_block_file (const path & p, std::error_code & ec) noexcept
Definition at line 1579 of file filesystem.cpp.
References is_block_file().
   {
     return is_block_file(status(p, ec));
   }
is_character_file() [1/3]
bool otto::filesystem::is_character_file (file_status status) noexcept
Definition at line 1584 of file filesystem.cpp.
References is_character_file(), and otto::filesystem::file_status::type().
Referenced by otto::filesystem::directory_entry::is_character_file(), and is_character_file().
   {
     return status.type() == file_type::character;
   }
is_character_file() [2/3]
bool otto::filesystem::is_character_file (const path & p)
Definition at line 1589 of file filesystem.cpp.
References is_character_file().
   {
     return is_character_file(status(p));
   }
is_character_file() [3/3]
bool otto::filesystem::is_character_file (const path & p, std::error_code & ec) noexcept
Definition at line 1594 of file filesystem.cpp.
References is_character_file().
   {
     return is_character_file(status(p, ec));
   }
is_directory() [1/3]
bool otto::filesystem::is_directory (file_status status) noexcept
Definition at line 1599 of file filesystem.cpp.
References is_directory(), and otto::filesystem::file_status::type().
Referenced by create_directories(), create_directory(), otto::filesystem::directory_entry::is_directory(), is_directory(), is_other(), and remove_all().
   {
     return status.type() == file_type::directory;
   }
is_directory() [2/3]
bool otto::filesystem::is_directory (const path & p)
Definition at line 1604 of file filesystem.cpp.
References is_directory().
   {
     return is_directory(status(p));
   }
is_directory() [3/3]
bool otto::filesystem::is_directory (const path & p, std::error_code & ec) noexcept
Definition at line 1609 of file filesystem.cpp.
References is_directory().
Referenced by otto::filesystem::recursive_directory_iterator::recursive_directory_iterator().
   {
     return is_directory(status(p, ec));
   }
is_fifo() [1/3]
bool otto::filesystem::is_fifo (file_status status) noexcept
Definition at line 1614 of file filesystem.cpp.
References is_fifo(), and otto::filesystem::file_status::type().
Referenced by otto::filesystem::directory_entry::is_fifo(), and is_fifo().
   {
     return status.type() == file_type::fifo;
   }
is_fifo() [2/3]
bool otto::filesystem::is_fifo (const path & p)
Definition at line 1619 of file filesystem.cpp.
References is_fifo().
   {
     return is_fifo(status(p));
   }
is_fifo() [3/3]
bool otto::filesystem::is_fifo (const path & p, std::error_code & ec) noexcept
Definition at line 1624 of file filesystem.cpp.
References is_fifo().
   {
     return is_fifo(status(p, ec));
   }
is_other() [1/3]
bool otto::filesystem::is_other (file_status status) noexcept
Definition at line 1629 of file filesystem.cpp.
References exists(), is_directory(), is_other(), is_regular_file(), and is_symlink().
Referenced by otto::filesystem::directory_entry::is_other(), and is_other().
   {
     return exists(status) && !is_regular_file(status) &&
            !is_directory(status) && !is_symlink(status);
   }
is_other() [2/3]
bool otto::filesystem::is_other (const path & p)
Definition at line 1635 of file filesystem.cpp.
References is_other().
   {
     return is_other(status(p));
   }
is_other() [3/3]
bool otto::filesystem::is_other (const path & p, std::error_code & ec) noexcept
Definition at line 1640 of file filesystem.cpp.
References is_other().
   {
     return is_other(status(p, ec));
   }
is_regular_file() [1/3]
bool otto::filesystem::is_regular_file (file_status status) noexcept
Definition at line 1645 of file filesystem.cpp.
References is_regular_file(), and otto::filesystem::file_status::type().
Referenced by copy_file(), is_other(), otto::filesystem::directory_entry::is_regular_file(), and is_regular_file().
   {
     return status.type() == file_type::regular;
   }
is_regular_file() [2/3]
bool otto::filesystem::is_regular_file (const path & p)
Definition at line 1650 of file filesystem.cpp.
References is_regular_file().
   {
     return is_regular_file(status(p));
   }
is_regular_file() [3/3]
bool otto::filesystem::is_regular_file (const path & p, std::error_code & ec) noexcept
Definition at line 1655 of file filesystem.cpp.
References is_regular_file().
   {
     return is_regular_file(status(p, ec));
   }
is_socket() [1/3]
bool otto::filesystem::is_socket (file_status status) noexcept
Definition at line 1660 of file filesystem.cpp.
References is_socket(), and otto::filesystem::file_status::type().
Referenced by otto::filesystem::directory_entry::is_socket(), and is_socket().
   {
     return status.type() == file_type::socket;
   }
is_socket() [2/3]
bool otto::filesystem::is_socket (const path & p)
Definition at line 1665 of file filesystem.cpp.
References is_socket().
   {
     return is_socket(status(p));
   }
is_socket() [3/3]
bool otto::filesystem::is_socket (const path & p, std::error_code & ec) noexcept
Definition at line 1670 of file filesystem.cpp.
References is_socket().
   {
     return is_socket(status(p, ec));
   }
is_symlink() [1/3]
bool otto::filesystem::is_symlink (file_status status) noexcept
Definition at line 1675 of file filesystem.cpp.
References is_symlink(), and otto::filesystem::file_status::type().
Referenced by is_other(), otto::filesystem::directory_entry::is_symlink(), and is_symlink().
   {
     return status.type() == file_type::symlink;
   }
is_symlink() [2/3]
bool otto::filesystem::is_symlink (const path & p)
Definition at line 1680 of file filesystem.cpp.
References is_symlink().
   {
     return is_symlink(status(p));
   }
is_symlink() [3/3]
bool otto::filesystem::is_symlink (const path & p, std::error_code & ec) noexcept
Definition at line 1685 of file filesystem.cpp.
References is_symlink().
   {
     return is_symlink(status(p, ec));
   }
last_write_time() [1/2]
file_time_type otto::filesystem::last_write_time (const path & p)
Definition at line 1722 of file filesystem.cpp.
Referenced by otto::filesystem::directory_entry::last_write_time().
   {
     std::error_code ec;
     auto res = last_write_time(p, ec);
     if (ec != std::error_code()) {
       throw filesystem_error("In filesystem::last_write_time", p, ec);
     }
     return res;
   }
last_write_time() [2/2]
file_time_type otto::filesystem::last_write_time (const path & p, std::error_code & ec) noexcept
Definition at line 1732 of file filesystem.cpp.
   {
     auto st = px::stat(p, ec);
     return px::last_write_time(st, ec);
   }
operator &() [1/5]
file_type otto::filesystem::operator& (file_type lhs, file_type rhs)
Definition at line 19 of file filesystem.cpp.
   {
     return file_type{std::underlying_type_t<file_type>(lhs) &
                      std::underlying_type_t<file_type>(rhs)};
   }
operator &() [2/5]
copy_options otto::filesystem::operator& (copy_options lhs, copy_options rhs)
Definition at line 35 of file filesystem.cpp.
   {
     return copy_options{std::underlying_type_t<copy_options>(lhs) &
                         std::underlying_type_t<copy_options>(rhs)};
   }
operator &() [3/5]
perms otto::filesystem::operator& (perms lhs, perms rhs)
Definition at line 52 of file filesystem.cpp.
   {
     return perms{std::underlying_type_t<perms>(lhs) &
                  std::underlying_type_t<perms>(rhs)};
   }
operator &() [4/5]
perm_options otto::filesystem::operator& (perm_options lhs, perm_options rhs)
Definition at line 70 of file filesystem.cpp.
   {
     return perm_options{std::underlying_type_t<perm_options>(lhs) &
                         std::underlying_type_t<perm_options>(rhs)};
   }
operator &() [5/5]
directory_options otto::filesystem::operator& (directory_options lhs, directory_options rhs)
Definition at line 86 of file filesystem.cpp.
   {
     return directory_options{std::underlying_type_t<directory_options>(lhs) &
                              std::underlying_type_t<directory_options>(rhs)};
   }
operator!=() [1/6]
bool otto::filesystem::operator!= (file_type lhs, file_type rhs)
Definition at line 29 of file filesystem.cpp.
   {
     return std::underlying_type_t<directory_options>(lhs) !=
            std::underlying_type_t<directory_options>(rhs);
   }
operator!=() [2/6]
bool otto::filesystem::operator!= (copy_options lhs, copy_options rhs)
Definition at line 46 of file filesystem.cpp.
   {
     return std::underlying_type_t<directory_options>(lhs) !=
            std::underlying_type_t<directory_options>(rhs);
   }
operator!=() [3/6]
bool otto::filesystem::operator!= (perms lhs, perms rhs)
Definition at line 64 of file filesystem.cpp.
   {
     return std::underlying_type_t<directory_options>(lhs) !=
            std::underlying_type_t<directory_options>(rhs);
   }
operator!=() [4/6]
bool otto::filesystem::operator!= (perm_options lhs, perm_options rhs)
Definition at line 80 of file filesystem.cpp.
   {
     return std::underlying_type_t<directory_options>(lhs) !=
            std::underlying_type_t<directory_options>(rhs);
   }
operator!=() [5/6]
bool otto::filesystem::operator!= (directory_options lhs, directory_options rhs)
Definition at line 96 of file filesystem.cpp.
   {
     return std::underlying_type_t<directory_options>(lhs) !=
            std::underlying_type_t<directory_options>(rhs);
   }
operator!=() [6/6]
bool otto::filesystem::operator!= (const path & lhs, const path & rhs) noexcept
Definition at line 641 of file filesystem.cpp.
   {
     return !(lhs == rhs);
   }
operator/()
path otto::filesystem::operator/ (const path & lhs, const path & rhs) noexcept
Definition at line 646 of file filesystem.cpp.
   {
     return path(lhs) /= rhs;
   }
operator<()
bool otto::filesystem::operator< (const path & lhs, const path & rhs) noexcept
Definition at line 616 of file filesystem.cpp.
   {
     return lhs.compare(rhs) < 0;
   }
operator<<()
template<class charT , class traits > std::basic_ostream< charT, traits > & otto::filesystem::operator<< (std::basic_ostream< charT, traits > & os, const path & p)
Definition at line 800 of file filesystem.hpp.
   {
     os << p.native();
     return os;
   }
operator<=()
bool otto::filesystem::operator<= (const path & lhs, const path & rhs) noexcept
Definition at line 621 of file filesystem.cpp.
   {
     return !(rhs < lhs);
   }
operator==()
bool otto::filesystem::operator== (const path & lhs, const path & rhs) noexcept
Definition at line 636 of file filesystem.cpp.
   {
     return !(lhs < rhs) && !(rhs < lhs);
   }
operator>()
bool otto::filesystem::operator> (const path & lhs, const path & rhs) noexcept
Definition at line 626 of file filesystem.cpp.
   {
     return rhs < lhs;
   }
operator>=()
bool otto::filesystem::operator>= (const path & lhs, const path & rhs) noexcept
Definition at line 631 of file filesystem.cpp.
   {
     return !(lhs < rhs);
   }
operator>>()
template<class charT , class traits > std::basic_istream< charT, traits > & otto::filesystem::operator>> (std::basic_istream< charT, traits > & is, path & p)
Definition at line 809 of file filesystem.hpp.
   {
     is >> p.native();
     return is;
   }
operator|() [1/5]
file_type otto::filesystem::operator| (file_type lhs, file_type rhs)
Definition at line 24 of file filesystem.cpp.
   {
     return file_type{std::underlying_type_t<file_type>(lhs) |
                      std::underlying_type_t<file_type>(rhs)};
   }
operator|() [2/5]
copy_options otto::filesystem::operator| (copy_options lhs, copy_options rhs)
Definition at line 40 of file filesystem.cpp.
   {
     return copy_options{std::underlying_type_t<copy_options>(lhs) |
                         std::underlying_type_t<copy_options>(rhs)};
   }
operator|() [3/5]
perms otto::filesystem::operator| (perms lhs, perms rhs)
Definition at line 58 of file filesystem.cpp.
   {
     return perms{std::underlying_type_t<perms>(lhs) |
                  std::underlying_type_t<perms>(rhs)};
   }
operator|() [4/5]
perm_options otto::filesystem::operator| (perm_options lhs, perm_options rhs)
Definition at line 75 of file filesystem.cpp.
   {
     return perm_options{std::underlying_type_t<perm_options>(lhs) |
                         std::underlying_type_t<perm_options>(rhs)};
   }
operator|() [5/5]
directory_options otto::filesystem::operator| (directory_options lhs, directory_options rhs)
Definition at line 91 of file filesystem.cpp.
   {
     return directory_options{std::underlying_type_t<directory_options>(lhs) |
                              std::underlying_type_t<directory_options>(rhs)};
   }
permissions() [1/3]
void otto::filesystem::permissions (const path & p, perms prms, perm_options opts = perm_options::replace)
permissions() [2/3]
void otto::filesystem::permissions (const path & p, perms prms, std::error_code & ec) noexcept
permissions() [3/3]
void otto::filesystem::permissions (const path & p, perms prms, perm_options opts, std::error_code & ec)
proximate() [1/3]
path otto::filesystem::proximate (const path & p, std::error_code & ec)
proximate() [2/3]
path otto::filesystem::proximate (const path & p, const path & base = current_path())
proximate() [3/3]
path otto::filesystem::proximate (const path & p, const path & base, std::error_code & ec)
read_symlink() [1/2]
path otto::filesystem::read_symlink (const path & p)
read_symlink() [2/2]
path otto::filesystem::read_symlink (const path & p, std::error_code & ec)
relative() [1/3]
path otto::filesystem::relative (const path & p, std::error_code & ec)
relative() [2/3]
path otto::filesystem::relative (const path & p, const path & base = current_path())
relative() [3/3]
path otto::filesystem::relative (const path & p, const path & base, std::error_code & ec)
remove() [1/2]
bool otto::filesystem::remove (const path & p)
Definition at line 1789 of file filesystem.cpp.
   {
     std::error_code ec;
     auto tmp = remove(p, ec);
     if (ec != std::error_code()) {
       throw filesystem_error("In filesystem::remove", p, ec);
     }
     return tmp;
   }
remove() [2/2]
bool otto::filesystem::remove (const path & p, std::error_code & ec) noexcept
Definition at line 1799 of file filesystem.cpp.
References exists().
   {
     if (!exists(p, ec)) return false;
     if (::remove(p.c_str())) {
       ec = {errno, std::system_category()};
       return false;
     } else {
       ec.clear();
       return true;
     }
   }
remove_all() [1/2]
uintmax_t otto::filesystem::remove_all (const path & p)
Definition at line 1811 of file filesystem.cpp.
References remove_all().
Referenced by remove_all().
   {
     std::error_code ec;
     auto tmp = remove_all(p, ec);
     if (ec != std::error_code()) {
       throw filesystem_error("In filesystem::remove_all", p, ec);
     }
     return tmp;
   }
remove_all() [2/2]
uintmax_t otto::filesystem::remove_all (const path & p, std::error_code & ec) noexcept
Definition at line 1821 of file filesystem.cpp.
References is_directory(), and remove_all().
   {
     uintmax_t n = 0;
     if (is_directory(p, ec)) {
       if (ec) return -1;
       for (auto&& de : recursive_directory_iterator(p)) {
         remove(de, ec);
         if (ec) return -1;
         n++;
       }
       n += static_cast<uintmax_t>(remove(p, ec));
     }
     if (ec) return -1;
     return n;
   }
rename() [1/2]
void otto::filesystem::rename (const path & from, const path & to)
Definition at line 1838 of file filesystem.cpp.
References rename().
Referenced by rename().
   {
     std::error_code ec;
     rename(from, to, ec);
     if (ec != std::error_code()) {
       throw filesystem_error("In filesystem::rename", from, to, ec);
     }
   }
rename() [2/2]
void otto::filesystem::rename (const path & from, const path & to, std::error_code & ec) noexcept
Definition at line 1847 of file filesystem.cpp.
References rename().
   {
     if (::rename(from.c_str(), to.c_str())) {
       ec = {errno, std::system_category()};
     } else {
       ec.clear();
     }
   }
resize_file() [1/2]
void otto::filesystem::resize_file (const path & p, uintmax_t size)
Definition at line 1856 of file filesystem.cpp.
References resize_file().
Referenced by resize_file().
   {
     std::error_code ec;
     resize_file(p, size, ec);
     if (ec != std::error_code()) {
       throw filesystem_error("In filesystem::resize_file", p, ec);
     }
   }
resize_file() [2/2]
void otto::filesystem::resize_file (const path & p, uintmax_t size, std::error_code & ec) noexcept
Definition at line 1865 of file filesystem.cpp.
References resize_file().
   {
     if (::truncate(p.c_str(), static_cast<off_t>(size))) {
       ec = {errno, std::system_category()};
     } else {
       ec.clear();
     }
   }
space() [1/2]
space_info otto::filesystem::space (const path & p)
space() [2/2]
space_info otto::filesystem::space (const path & p, std::error_code & ec) noexcept
status() [1/2]
file_status otto::filesystem::status (const path & p)
Definition at line 1738 of file filesystem.cpp.
   {
     std::error_code ec;
     auto res = status(p, ec);
     if (ec != std::error_code()) {
       throw filesystem_error("In filesystem::status", p, ec);
     }
     return res;
   }
status() [2/2]
file_status otto::filesystem::status (const path & p, std::error_code & ec) noexcept
Definition at line 1748 of file filesystem.cpp.
   {
     struct stat st;
     return px::status(p, st, ec);
   }
status_known()
bool otto::filesystem::status_known (file_status s) noexcept
swap()
void otto::filesystem::swap (path & lhs, path & rhs) noexcept
Definition at line 606 of file filesystem.cpp.
Referenced by otto::filesystem::path::swap().
   {
     lhs.swap(rhs);
   }
symlink_status() [1/2]
file_status otto::filesystem::symlink_status (const path & p)
Definition at line 1754 of file filesystem.cpp.
References symlink_status().
Referenced by otto::filesystem::directory_entry::refresh(), and symlink_status().
   {
     std::error_code ec;
     auto res = symlink_status(p, ec);
     if (ec != std::error_code()) {
       throw filesystem_error("In filesystem::symlink_status", p, ec);
     }
     return res;
   }
symlink_status() [2/2]
file_status otto::filesystem::symlink_status (const path & p, std::error_code & ec) noexcept
Definition at line 1764 of file filesystem.cpp.
References symlink_status().
   {
     struct stat st;
     return px::status(p, st, ec);
   }
temp_directory_path() [1/2]
path otto::filesystem::temp_directory_path ()
temp_directory_path() [2/2]
path otto::filesystem::temp_directory_path (std::error_code & ec)
u8path() [1/2]
template<class Source > path otto::filesystem::u8path (const Source & source)
u8path() [2/2]
template<class InputIterator > path otto::filesystem::u8path (InputIterator first, InputIterator last)
weakly_canonical() [1/2]
path otto::filesystem::weakly_canonical (const path & p)
weakly_canonical() [2/2]
path otto::filesystem::weakly_canonical (const path & p, std::error_code & ec)