OTTO: otto::util Namespace Reference
otto::util Namespace Reference
Namespaces
audio
detail
dsp
math
timer
A simple stack-based library used to time nested parts of a program.
tuple
view
Classes
struct AdjacentRange
struct as_exception
struct atomic_swap
class ByteFile
TODO: Documentation.
struct bytes
struct cache_base
struct cached
struct declval< T2 >())> >
class dyn_array
struct enum_decay
Get the underlying type if T is an enum, otherwise just T.
struct enum_decay< T, std::enable_if_t< std::is_enum_v< T > > >
struct Event
An event registry and dispatcher.
struct exception
class FilterIterImpl
class float_step_iterator
class GeneratingIterImpl
struct Header
struct int_n_bytes
struct int_n_bytes< 1 >
struct int_n_bytes< 2 >
struct int_n_bytes< 4 >
struct int_n_bytes< 8 >
struct is_equal_comparable
Check if a type is equal comparable to another type (or itself)
struct is_equal_comparable< T1, T1 >
struct is_equal_comparable< T1, T2, std::void_t< decltype(std::declval< T1 >()==std::declval< T2 >())> >
struct is_greater_than_comparable
Check if a type is greater than comparable to another type (or itself)
struct is_greater_than_comparable< T1, T1 >
struct is_iterator
struct is_iterator< iter, type, category, std::enable_if_t< std::is_same_v< std::remove_reference_t< iter >, std::iterator_traits< std::remove_reference_t< iter > >::value_type > &&std::is_base_of_v< std::remove_reference_t< iter >, std::iterator_traits< std::remove_reference_t< iter > >::iterator_category > > >
struct is_less_than_comparable
Check if a type is less than comparable to another type (or itself)
struct is_less_than_comparable< T1, T1 >
struct is_number
Any arithmetic type except bool.
struct is_number< T, std::enable_if_t< std::is_arithmetic_v< T > &&!std::is_same_v< T, bool > > >
struct is_number_or_enum
struct is_number_or_enum< T, std::enable_if_t< std::is_enum_v< T >||is_number_v< T > > >
struct is_one_of
class iterator_adaptor_impl
class iterator_adaptor_impl< Impl, std::bidirectional_iterator_tag >
class iterator_adaptor_impl< Impl, std::random_access_iterator_tag >
struct JsonFile
class locked
Wrap any type in a mutex, and guarantee that it is locked on every access.
struct overloaded
Overload lambdas.
struct result
class ringbuffer
struct select_type
struct select_type< false, T1, T2 >
struct select_type< true, T1, T2 >
struct sequence
A simple sequence of data, defined by a pair of iterators.
class SoundFile
A file handler for sound (wav, aiff) files.
struct TAPEChunk
class TapeFile
class TransformIteratorImpl
struct TRCKChunk
struct void_t< decltype(std::declval< T1 >()< std::declval< T2 >())> >
struct WAVE_data
struct WAVE_fmt
struct wrapping_array
class ZippedIteratorImpl
struct ZippedRange
Typedefs
template<typename Impl >
using iterator_adaptor = iterator_adaptor_impl< Impl, typename detail::iterator_category< Impl >::type >
template<typename Generator >
using generating_iterator = iterator_adaptor< GeneratingIterImpl< Generator > >
template<typename... Iterators>
using zipped_iterator = iterator_adaptor< ZippedIteratorImpl< Iterators... > >
template<typename Iter >
using adjacent_pair_iterator = iterator_adaptor< detail::AdjacentIterImpl< Iter > >
template<typename WrappedIter , typename Callable >
using transform_iterator = iterator_adaptor< TransformIteratorImpl< WrappedIter, Callable > >
template<typename WrappedIter , typename Predicate >
using filter_iterator = iterator_adaptor< FilterIterImpl< WrappedIter, Predicate > >
using json = nlohmann::json
using Chunk = ByteFile::Chunk
using Position = SoundFile::Position
using SliceData = TapeFile::SliceData
template<typename T >
using enum_decay_t = typename enum_decay< T >::type
template<bool b, typename T1 , typename T2 >
using select_type_t = typename select_type< b, T1, T2 >::type
template<int N>
using int_n_bytes_t = typename int_n_bytes< N >::type
template<int N>
using int_n_bytes_u_t = typename int_n_bytes< N >::utype
template<typename F , typename... Args>
using is_invocable = mpark::lib::is_invocable< F, Args... >
template<typename R , typename F , typename... Args>
using is_invocable_r = mpark::lib::is_invocable_r< R, F, Args... >
template<typename F , typename... Args>
using invoke_result = mpark::lib::invoke_result< F, Args... >
template<typename F , typename... Args>
using invoke_result_t = mpark::lib::invoke_result_t< F, Args... >
Functions
template<class StrIterator >
std::string join_strings (StrIterator b, StrIterator e, std::string_view js=", ")
Joins a sequence of strings, separating them using js
template<typename Container >
std::string join_strings (Container &&cont, std::string_view js=", ")
Joins a sequence of strings, separating them using js
template<int n, class Func >
constexpr auto generate_array (Func &&gen)
template<typename InputIt , typename Size , typename F >
constexpr InputIt for_each_n (InputIt &&first, Size n, F &&f)
template<typename InputIt , typename F >
constexpr std::size_t indexed_for (InputIt &&first, InputIt &&last, F &&f)
template<typename Rng , typename F >
constexpr std::size_t indexed_for (Rng &&rng, F &&f)
template<class InputIt , class Size , class F >
constexpr InputIt indexed_for_n (InputIt first, Size n, F &&f)
template<class Rng , class Size , class F >
constexpr std::size_t indexed_for_n (Rng &&rng, Size n, F &&f)
template<typename Iter1 , typename Iter2 , typename F >
constexpr void for_both (Iter1 &&f1, Iter1 &&l1, Iter2 &&f2, Iter2 &&l2, F &&f)
template<typename Rng1 , typename Rng2 , typename F >
constexpr void for_both (Rng1 &&r1, Rng2 &&r2, F &&f)
template<typename Cont , typename T >
constexpr auto accumulate (Cont &&cont, T &&init)
template<typename Cont , typename T , typename BinaryOperation >
constexpr auto accumulate (Cont &&cont, T &&init, BinaryOperation &&op)
template<typename Cont , typename OutputIterator >
decltype(auto) adjacent_difference (Cont &&cont, OutputIterator &&first)
template<typename Cont >
decltype(auto) prev_permutation (Cont &&cont)
template<typename Cont , typename Compare >
decltype(auto) prev_permutation (Cont &&cont, Compare &&comp)
template<typename Cont >
decltype(auto) push_heap (Cont &&cont)
template<typename Cont , typename Compare >
decltype(auto) push_heap (Cont &&cont, Compare &&comp)
template<typename Cont , typename T >
decltype(auto) remove (Cont &&cont, T &&value)
template<typename Cont , typename OutputIterator , typename T >
decltype(auto) remove_copy (Cont &&cont, OutputIterator &&first, T &&value)
template<typename Cont , typename OutputIterator , typename UnaryPredicate >
decltype(auto) remove_copy_if (Cont &&cont, OutputIterator &&first, UnaryPredicate &&p)
template<typename Cont , typename UnaryPredicate >
decltype(auto) remove_if (Cont &&cont, UnaryPredicate &&p)
template<typename Cont , typename T , typename T2 >
decltype(auto) replace (Cont &&cont, T &&old_value, T2 &&new_value)
template<typename Cont , typename OutputIterator , typename T , typename T2 >
decltype(auto) replace_copy (Cont &&cont, OutputIterator &&first, T &&old_value, T2 &&new_value)
template<typename Cont , typename OutputIterator , typename UnaryPredicate , typename T >
decltype(auto) replace_copy_if (Cont &&cont, OutputIterator &&first, UnaryPredicate &&p, T &&new_value)
template<typename Cont , typename UnaryPredicate , typename T >
decltype(auto) replace_if (Cont &&cont, UnaryPredicate &&p, T &&new_value)
template<typename Cont >
decltype(auto) reverse (Cont &&cont)
template<typename Cont , typename OutputIterator >
decltype(auto) reverse_copy (Cont &&cont, OutputIterator &&first)
template<typename Cont , typename ForwardIterator >
decltype(auto) rotate (Cont &&cont, ForwardIterator &&new_first)
template<typename Cont , typename ForwardIterator , typename OutputIterator >
decltype(auto) rotate_copy (Cont &&cont, ForwardIterator &&new_first, OutputIterator &&first)
template<typename Cont , typename Cont2 >
decltype(auto) search (Cont &&cont, Cont2 &&cont2)
template<typename Cont , typename Cont2 , typename BinaryPredicate >
decltype(auto) search (Cont &&cont, Cont2 &&cont2, BinaryPredicate &&p)
template<typename Cont , typename Size , typename T >
decltype(auto) search_n (Cont &&cont, Size count, T &&value)
template<typename Cont , typename Size , typename T , typename BinaryPredicate >
decltype(auto) search_n (Cont &&cont, Size count, T &&value, BinaryPredicate &&p)
template<typename Cont , typename Cont2 , typename OutputIterator >
decltype(auto) set_difference (Cont &&cont, Cont2 &&cont2, OutputIterator &&first)
template<typename Cont , typename Cont2 , typename OutputIterator , typename Compare >
decltype(auto) set_difference (Cont &&cont, Cont2 &&cont2, OutputIterator &&first, Compare &&comp)
template<typename Cont , typename Cont2 , typename OutputIterator >
decltype(auto) set_intersection (Cont &&cont, Cont2 &&cont2, OutputIterator &&first)
template<typename Cont , typename Cont2 , typename OutputIterator , typename Compare >
decltype(auto) set_intersection (Cont &&cont, Cont2 &&cont2, OutputIterator &&first, Compare &&comp)
template<typename Cont , typename Cont2 , typename OutputIterator >
decltype(auto) set_symmetric_difference (Cont &&cont, Cont2 &&cont2, OutputIterator &&first)
template<typename Cont , typename Cont2 , typename OutputIterator , typename Compare >
decltype(auto) set_symmetric_difference (Cont &&cont, Cont2 &&cont2, OutputIterator &&first, Compare &&comp)
template<typename Cont , typename Cont2 , typename OutputIterator >
decltype(auto) set_union (Cont &&cont, Cont2 &&cont2, OutputIterator &&first)
template<typename Cont , typename Cont2 , typename OutputIterator , typename Compare >
decltype(auto) set_union (Cont &&cont, Cont2 &&cont2, OutputIterator &&first, Compare &&comp)
template<typename Cont , typename UniformRandomNumberGenerator >
decltype(auto) shuffle (Cont &&cont, UniformRandomNumberGenerator &&g)
template<typename Cont >
decltype(auto) sort (Cont &&cont)
template<typename Cont , typename Compare >
decltype(auto) sort (Cont &&cont, Compare &&comp)
template<typename Cont >
decltype(auto) sort_heap (Cont &&cont)
template<typename Cont , typename Compare >
decltype(auto) sort_heap (Cont &&cont, Compare &&comp)
template<typename Cont , typename UnaryPredicate >
decltype(auto) stable_partition (Cont &&cont, UnaryPredicate &&p)
template<typename Cont >
decltype(auto) stable_sort (Cont &&cont)
template<typename Cont , typename Compare >
decltype(auto) stable_sort (Cont &&cont, Compare &&comp)
template<typename Cont , typename ForwardIterator >
decltype(auto) swap_ranges (Cont &&cont, ForwardIterator &&first)
template<typename Cont , typename Cont2 , typename F >
auto transform (Cont &&cont, Cont2 &&cont2, F &&f) -> decltype(begin(cont2))
template<typename Cont , typename Iter , typename F >
decltype(auto) transform (Cont &&cont, Iter &&iter, F &&f)
template<typename Cont , typename Cont2 , typename Cont3 , typename BinaryPredicate >
auto transform (Cont &&cont, Cont2 &&cont2, Cont3 &&cont3, BinaryPredicate &&f) -> decltype(begin(cont2), begin(cont3))
template<typename Cont , typename InputIterator , typename Cont3 , typename BinaryPredicate >
auto transform (Cont &&cont, InputIterator &&iter, Cont3 &&cont3, BinaryPredicate &&f) -> decltype(begin(cont), begin(cont3))
template<typename Cont , typename Cont2 , typename InputIterator , typename BinaryPredicate >
auto transform (Cont &&cont, Cont2 &&cont2, InputIterator &&iter, BinaryPredicate &&f) -> decltype(begin(cont), begin(cont2), iter)
template<typename Cont , typename InputIterator , typename OutputIterator , typename BinaryOperation >
decltype(auto) transform (Cont &&cont, InputIterator &&firstIn, OutputIterator &&firstOut, BinaryOperation &&op)
template<typename Cont >
decltype(auto) unique (Cont &&cont)
template<typename Cont , typename BinaryPredicate >
decltype(auto) unique (Cont &&cont, BinaryPredicate &&p)
template<typename Cont , typename OutputIterator >
decltype(auto) unique_copy (Cont &&cont, OutputIterator &&first)
template<typename Cont , typename OutputIterator , typename BinaryPredicate >
decltype(auto) unique_copy (Cont &&cont, OutputIterator &&first, BinaryPredicate &&p)
template<typename Cont , typename T >
decltype(auto) upper_bound (Cont &&cont, T &&value)
template<typename Cont , typename T , typename Compare >
decltype(auto) upper_bound (Cont &&cont, T &&value, Compare &&comp)
template<typename Cont , typename OutputIterator >
decltype(auto) copy (Cont &&cont, OutputIterator &&first)
template<typename Cont , typename OutputIterator , typename UnaryPredicate >
decltype(auto) copy_if (Cont &&cont, OutputIterator &&first, UnaryPredicate &&p)
template<typename Cont , typename T >
decltype(auto) fill (Cont &&cont, T &&value)
template<typename Cont , typename T >
decltype(auto) fill_n (Cont &&cont, std::size_t n, T &&value)
template<typename Cont , typename UnaryPredicate >
decltype(auto) any_of (Cont &&cont, UnaryPredicate &&p)
template<typename Cont , typename UnaryPredicate >
decltype(auto) all_of (Cont &&cont, UnaryPredicate &&p)
template<typename Cont , typename UnaryPredicate >
decltype(auto) none_of (Cont &&cont, UnaryPredicate &&p)
template<typename Cont >
decltype(auto) max_element (Cont &&cont)
template<typename Cont >
decltype(auto) min_element (Cont &&cont)
template<typename Cont , typename Compare >
decltype(auto) min_element (Cont &&cont, Compare &&f)
template<typename Cont , typename Compare >
decltype(auto) max_element (Cont &&cont, Compare &&f)
template<typename Cont , typename T >
decltype(auto) find (Cont &&cont, T &&t)
template<typename Cont , typename UnaryPredicate >
decltype(auto) find_if (Cont &&cont, UnaryPredicate &&f)
void swap (ByteFile &first, ByteFile &sec)
template<typename DataRef , typename... Args>
as_exception (DataRef &&dr, const std::string &message, Args &&... args) -> as_exception< std::decay_t< DataRef >>
template<typename Iterator >
float_step_iterator (const Iterator &iter, float step) -> float_step_iterator< Iterator >
template<typename I , typename V = typename detail::value_type<std::decay_t<I>>::type>
auto float_step (I &&iter, float step=1)
Create a float_step_iterator.
template<typename Generator >
generating_iterator< Generator > generator (Generator &&gen)
template<typename... Iterators>
zipped_iterator< Iterators... > zip_iters (Iterators... iters)
Create a zipped iterator from iterators.
template<typename... Ranges>
auto zip (Ranges &&... ranges)
Create a zipped range from ranges.
template<typename Range >
auto adjacent_pairs (Range &rng)
template<typename BIter , typename EIter >
auto adjacent_pairs (BIter f, EIter l)
std::string to_string (JsonFile::ErrorCode ec)
template<typename E >
constexpr auto underlying (E e) noexcept -> std::enable_if_t<!std::is_enum_v< E >, E >
Cast scoped enums to their underlying numeric type.
template<typename E , typename = std::enable_if_t<std::is_enum_v<E>>>
constexpr auto underlying (E e) noexcept
template<typename... Ls>
overloaded (Ls...) -> overloaded< std::decay_t< Ls >... >
template<typename Var , typename... Lambdas>
decltype(auto) match (Var &&v, Lambdas &&... ls)
template<typename Var , typename... Lambdas>
decltype(auto) partial_match (Var &&v, Lambdas &&... ls)
template<typename Type , typename Ret , typename... Args>
auto capture_this (Ret(Type::*func)(Args...), Type *object)
Get a callable from a member pointer and an object.
template<typename Type , typename Ret , typename... Args>
auto capture_this (Ret(Type::*func)(Args...), Type &object)
Variables
template<typename T >
constexpr bool is_number_v = is_number<T>::value
template<typename T >
constexpr bool is_number_or_enum_v = is_number_or_enum<T>::value
template<typename T1 , typename T2 = T1>
constexpr bool is_equal_comparable_v = is_equal_comparable<T1, T2>::value
template<typename T1 , typename T2 = T1>
constexpr bool is_less_than_comparable_v = is_less_than_comparable<T1, T2>::value
template<typename T1 , typename T2 = T1>
constexpr bool is_greater_than_comparable_v = is_greater_than_comparable<T1, T2>::value
template<bool b, typename T1 , typename T2 >
constexpr bool select_type_v = select_type<b, T1, T2>::value
template<typename T , typename... Ts>
constexpr bool is_one_of_v = (std::is_same_v<T, Ts> || ...)
template<typename iter , typename type , typename category >
constexpr bool is_iterator_v = is_iterator<iter, type, category>::value
template<typename F , typename... Args>
constexpr bool is_invocable_v = mpark::lib::is_invocable<F, Args...>::value
template<typename R , typename F , typename... Args>
constexpr bool is_invocable_r_v
const constexpr auto nullmatch = [](const auto&&) {}
Match any type, do nothing with it.
Typedef Documentation
adjacent_pair_iterator
template<typename Iter > using otto::util::adjacent_pair_iterator = typedef iterator_adaptor<detail::AdjacentIterImpl<Iter> >
Definition at line 878 of file iterator.hpp.
Chunk
typedef ByteFile::Chunk otto::util::Chunk
Definition at line 6 of file soundfile.cpp.
enum_decay_t
template<typename T > using otto::util::enum_decay_t = typedef typename enum_decay<T>::type
Definition at line 87 of file type_traits.hpp.
filter_iterator
template<typename WrappedIter , typename Predicate > using otto::util::filter_iterator = typedef iterator_adaptor<FilterIterImpl<WrappedIter, Predicate> >
Filter Iterator
Definition at line 1051 of file iterator.hpp.
generating_iterator
template<typename Generator > using otto::util::generating_iterator = typedef iterator_adaptor<GeneratingIterImpl<Generator> >
Generating iterator
Supplied with a generator function, this iterator will generate a value each time its called.
Definition at line 695 of file iterator.hpp.
int_n_bytes_t
template<int N> using otto::util::int_n_bytes_t = typedef typename int_n_bytes<N>::type
Definition at line 186 of file type_traits.hpp.
int_n_bytes_u_t
template<int N> using otto::util::int_n_bytes_u_t = typedef typename int_n_bytes<N>::utype
Definition at line 189 of file type_traits.hpp.
invoke_result
template<typename F , typename... Args> using otto::util::invoke_result = typedef mpark::lib::invoke_result<F, Args...>
Definition at line 207 of file type_traits.hpp.
invoke_result_t
template<typename F , typename... Args> using otto::util::invoke_result_t = typedef mpark::lib::invoke_result_t<F, Args...>
Definition at line 210 of file type_traits.hpp.
is_invocable
template<typename F , typename... Args> using otto::util::is_invocable = typedef mpark::lib::is_invocable<F, Args...>
Definition at line 194 of file type_traits.hpp.
is_invocable_r
template<typename R , typename F , typename... Args> using otto::util::is_invocable_r = typedef mpark::lib::is_invocable_r<R, F, Args...>
Definition at line 200 of file type_traits.hpp.
iterator_adaptor
template<typename Impl > using otto::util::iterator_adaptor = typedef iterator_adaptor_impl<Impl, typename detail::iterator_category<Impl>::type>
Zero overhead wrapper to create iterators
Template Parameters
Impl must define the following member functions:
void advance(difference_type);
reference dereference();
bool equal(const Impl&);
For random access iterators, it must also define
std::ptrdiff_t difference(const Impl&);
Other than those, it must define a copy constructor, and the member types iterator_category and value_type, Any other of the five iterator_traits types will also be used from Impl if avaliable
Definition at line 355 of file iterator.hpp.
json
using otto::util::json = typedef nlohmann::json
Definition at line 8 of file jsonfile.cpp.
Position
using otto::util::Position = typedef SoundFile::Position
Definition at line 7 of file soundfile.cpp.
select_type_t
template<bool b, typename T1 , typename T2 > using otto::util::select_type_t = typedef typename select_type<b, T1, T2>::type
Definition at line 107 of file type_traits.hpp.
SliceData
using otto::util::SliceData = typedef TapeFile::SliceData
Definition at line 6 of file tapefile.cpp.
transform_iterator
template<typename WrappedIter , typename Callable > using otto::util::transform_iterator = typedef iterator_adaptor<TransformIteratorImpl<WrappedIter, Callable> >
Transforming Iterator
Definition at line 975 of file iterator.hpp.
zipped_iterator
template<typename... Iterators> using otto::util::zipped_iterator = typedef iterator_adaptor<ZippedIteratorImpl<Iterators...> >
Zipped iterator
Iterates over multiple iterators at the same time
Its very useful with structured bindings and for loops. Using the helper function [otto::util::zip], you can iterate over multiple ranges like this:
for (auto&& [r1, r2] : util::zip(range1, range2)) {
  ...
}
Definition at line 798 of file iterator.hpp.
Function Documentation
accumulate() [1/2]
template<typename Cont , typename T > constexpr auto otto::util::accumulate (Cont && cont, T && init)
Definition at line 150 of file algorithm.hpp.
   {
     // TODO C++20: std::accumulate is constexpr
     using std::begin, std::end;
     auto first = begin(cont);
     auto last = end(cont);
     for (; first != last; ++first) init = init + *first;
     return init;
   }
accumulate() [2/2]
template<typename Cont , typename T , typename BinaryOperation > constexpr auto otto::util::accumulate (Cont && cont, T && init, BinaryOperation && op)
Definition at line 161 of file algorithm.hpp.
   {
     // TODO C++20: std::accumulate is constexpr
     using std::begin, std::end;
     auto first = begin(cont);
     auto last = end(cont);
     for (; first != last; ++first) init = op(init, *first);
     return init;
   }
adjacent_difference()
template<typename Cont , typename OutputIterator > decltype(auto) otto::util::adjacent_difference (Cont && cont, OutputIterator && first)
Definition at line 174 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::adjacent_difference(begin(cont), end(cont),
                                     std::forward<OutputIterator>(first));
   }
adjacent_pairs() [1/2]
template<typename Range > auto otto::util::adjacent_pairs (Range & rng)
Definition at line 920 of file iterator.hpp.
Referenced by otto::core::ui::vg::Canvas::plotRounded().
{
     return AdjacentRange{rng};
   }
adjacent_pairs() [2/2]
template<typename BIter , typename EIter > auto otto::util::adjacent_pairs (BIter f, EIter l)
Definition at line 925 of file iterator.hpp.
{
     return AdjacentRange{util::sequence(f, l)};
   }
all_of()
template<typename Cont , typename UnaryPredicate > decltype(auto) otto::util::all_of (Cont && cont, UnaryPredicate && p)
Definition at line 743 of file algorithm.hpp.
Referenced by otto::engines::Euclid::process().
   {
     using std::begin;
     using std::end;
     return std::all_of(begin(cont), end(cont), std::forward<UnaryPredicate>(p));
   }
any_of()
template<typename Cont , typename UnaryPredicate > decltype(auto) otto::util::any_of (Cont && cont, UnaryPredicate && p)
Definition at line 735 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::any_of(begin(cont), end(cont), std::forward<UnaryPredicate>(p));
   }
as_exception()
template<typename DataRef , typename... Args> otto::util::as_exception (DataRef && dr, const std::string & message, Args &&... args) -> as_exception< std::decay_t< DataRef >>
capture_this() [1/2]
template<typename Type , typename Ret , typename... Args> auto otto::util::capture_this (Ret(Type::*)(Args...) func, Type * object)
Get a callable from a member pointer and an object.
Definition at line 53 of file utility.hpp.
{
     return [object, func] (Args... args) -> Ret { return (object->*func)(args...);};
   }
capture_this() [2/2]
template<typename Type , typename Ret , typename... Args> auto otto::util::capture_this (Ret(Type::*)(Args...) func, Type & object)
Definition at line 57 of file utility.hpp.
{
     return [&object, func] (Args... args) -> Ret { return (object.*func)(args...);};
   }
copy()
template<typename Cont , typename OutputIterator > decltype(auto) otto::util::copy (Cont && cont, OutputIterator && first)
Definition at line 698 of file algorithm.hpp.
Referenced by otto::core::props::OTTO_PROPS_MIXIN_LEAF().
   {
     using std::begin;
     using std::end;
     return std::copy(begin(cont), end(cont),
                      std::forward<OutputIterator>(first));
   }
copy_if()
template<typename Cont , typename OutputIterator , typename UnaryPredicate > decltype(auto) otto::util::copy_if (Cont && cont, OutputIterator && first, UnaryPredicate && p)
Definition at line 707 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::copy_if(begin(cont), end(cont),
                         std::forward<OutputIterator>(first),
                         std::forward<UnaryPredicate>(p));
   }
fill()
template<typename Cont , typename T > decltype(auto) otto::util::fill (Cont && cont, T && value)
Definition at line 719 of file algorithm.hpp.
Referenced by otto::engines::Euclid::process(), and otto::engines::Euclid::Channel::update_notes().
   {
     using std::begin;
     using std::end;
     return std::fill(begin(cont), end(cont), std::forward<T>(value));
   }
fill_n()
template<typename Cont , typename T > decltype(auto) otto::util::fill_n (Cont && cont, std::size_t n, T && value)
Definition at line 727 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::fill_n(begin(cont), n, std::forward<T>(value));
   }
find()
template<typename Cont , typename T > decltype(auto) otto::util::find (Cont && cont, T && t)
Definition at line 792 of file algorithm.hpp.
Referenced by otto::service::presets::apply_preset(), otto::service::presets::idx_of_name(), and otto::service::presets::load_preset_files().
   {
     using std::begin;
     using std::end;
     return std::find(begin(cont), end(cont), std::forward<T>(t));
   }
find_if()
template<typename Cont , typename UnaryPredicate > decltype(auto) otto::util::find_if (Cont && cont, UnaryPredicate && f)
Definition at line 800 of file algorithm.hpp.
Referenced by otto::core::engines::EngineDispatcher< ET >::from_json(), otto::core::props::OTTO_PROPS_MIXIN_BRANCH(), and otto::core::engines::EngineDispatcher< ET >::select().
   {
     using std::begin;
     using std::end;
     return std::find_if(begin(cont), end(cont),
                         std::forward<UnaryPredicate>(f));
   }
float_step()
template<typename I , typename V = typename detail::value_type<std::decay_t<I>>::type> auto otto::util::float_step (I && iter, float step = 1)
Create a float_step_iterator.
Definition at line 647 of file iterator.hpp.
   {
     return float_step_iterator<std::decay_t<I>,
       V>{std::forward<I>(iter), step};
   }
float_step_iterator()
template<typename Iterator > otto::util::float_step_iterator (const Iterator & iter, float step) -> float_step_iterator< Iterator >
for_both() [1/2]
template<typename Iter1 , typename Iter2 , typename F > constexpr void otto::util::for_both (Iter1 && f1, Iter1 && l1, Iter2 && f2, Iter2 && l2, F && f)
Definition at line 127 of file algorithm.hpp.
Referenced by for_both().
   {
     Iter1 i1 = std::forward<Iter1>(f1);
     Iter2 i2 = std::forward<Iter2>(f2);
     for (; i1 != l1 && i2 != l2; i1++, i2++) {
       std::invoke(f, *i1, *i2);
     }
   }
for_both() [2/2]
template<typename Rng1 , typename Rng2 , typename F > constexpr void otto::util::for_both (Rng1 && r1, Rng2 && r2, F && f)
Definition at line 137 of file algorithm.hpp.
References for_both().
   {
     for_both(std::begin(r1), std::end(r1), std::begin(r2), std::end(r2),
              std::forward<F>(f));
   }
for_each_n()
template<typename InputIt , typename Size , typename F > constexpr InputIt otto::util::for_each_n (InputIt && first, Size n, F && f)
Definition at line 62 of file algorithm.hpp.
Referenced by otto::util::SoundFile::write_samples().
   {
     for (Size i = 0; i < n; ++first, ++i) {
       std::invoke(f, *first);
     }
     return first;
   }
generate_array()
template<int n, class Func > constexpr auto otto::util::generate_array (Func && gen)
Definition at line 49 of file algorithm.hpp.
References otto::util::detail::generate_array_impl().
   {
     auto intseq = std::make_integer_sequence<int, n>();
     return detail::generate_array_impl(std::move(intseq),
                                        std::forward<Func>(gen));
   }
generator()
template<typename Generator > generating_iterator<Generator> otto::util::generator (Generator && gen)
Create a generating iterator
Definition at line 701 of file iterator.hpp.
{
     return generating_iterator<Generator>(std::forward<Generator>(gen));
   }
indexed_for() [1/2]
template<typename InputIt , typename F > constexpr std::size_t otto::util::indexed_for (InputIt && first, InputIt && last, F && f)
for_each with access to an index value. Function called as f(*it, i)
For each item in range [first, last), invoke f with args *iter, i where iter is the current iterator, and i is an incrementing value, starting at zero. Use this instead of raw indexed loops wherever possible.
Parameters
first Input iterator to the begining of the range
last Input iterator to the end of the range
f Must be invocable with arguments value_type, std::size_t
Returns
The number of iterations performed
Definition at line 82 of file algorithm.hpp.
Referenced by indexed_for().
   {
     std::size_t i = 0;
     std::for_each(std::forward<InputIt>(first), std::forward<InputIt>(last),
                   [&](auto&& a) {
                     std::invoke(f, a, i);
                     i++;
                   });
     return i;
   }
indexed_for() [2/2]
template<typename Rng , typename F > constexpr std::size_t otto::util::indexed_for (Rng && rng, F && f)
Definition at line 94 of file algorithm.hpp.
References indexed_for().
   {
     return indexed_for(std::begin(rng), std::end(rng), std::forward<F>(f));
   }
indexed_for_n() [1/2]
template<class InputIt , class Size , class F > constexpr InputIt otto::util::indexed_for_n (InputIt first, Size n, F && f)
for_each_n with access to an index value. Function called as f(*it, i)
for n iterations, invoke f with args *iter, i where iter is the current iterator starting with first, and i is an incrementing value, starting at zero. Use this instead of raw indexed loops wherever possible.
Parameters
first Input iterator to the begining of the range
n Number of iterations to go through
f Must be invocable with arguments value_type, std::size_t
Returns
An iterator one past the last one visited
Definition at line 112 of file algorithm.hpp.
Referenced by indexed_for_n().
   {
     for (Size i = 0; i < n; ++first, ++i) {
       std::invoke(f, *first, i);
     }
     return first;
   }
indexed_for_n() [2/2]
template<class Rng , class Size , class F > constexpr std::size_t otto::util::indexed_for_n (Rng && rng, Size n, F && f)
Definition at line 121 of file algorithm.hpp.
References indexed_for_n().
   {
     return indexed_for_n(std::begin(rng), std::end(rng), n, std::forward<F>(f));
   }
join_strings() [1/2]
template<class StrIterator > std::string otto::util::join_strings (StrIterator b, StrIterator e, std::string_view js = ", ")
Joins a sequence of strings, separating them using js
Definition at line 16 of file algorithm.hpp.
Referenced by otto::engines::EuclidScreen::draw_recording(), and join_strings().
   {
     std::string result;
     std::for_each(b, e, [&](auto&& s) {
       if (!result.empty()) {
         result.append(js);
       }
       result.append(s);
     });
     return result;
   }
join_strings() [2/2]
template<typename Container > std::string otto::util::join_strings (Container && cont, std::string_view js = ", ")
Joins a sequence of strings, separating them using js
Definition at line 32 of file algorithm.hpp.
References join_strings().
   {
     return join_strings(std::begin(cont), std::end(cont), js);
   }
match()
template<typename Var , typename... Lambdas> decltype(auto) otto::util::match (Var && v, Lambdas &&... ls)
Pattern matching for std::variant.
One of Lambdas is required to match
Definition at line 28 of file utility.hpp.
Referenced by otto::service::ui::impl::flush_events(), partial_match(), otto::engines::Euclid::process(), otto::core::audio::VoiceManager< 6 >::process_after(), and otto::core::audio::VoiceManager< 6 >::process_before().
   {
     auto&& matcher = overloaded<Lambdas...>(std::forward<Lambdas>(ls)...);
     // ADL to use std::visit or mpark::visit
     // TODO: Remove this when the standard is adapted
     return visit(std::move(matcher), std::forward<Var>(v));
   }
max_element() [1/2]
template<typename Cont > decltype(auto) otto::util::max_element (Cont && cont)
Definition at line 760 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::max_element(begin(cont), end(cont));
   }
max_element() [2/2]
template<typename Cont , typename Compare > decltype(auto) otto::util::max_element (Cont && cont, Compare && f)
Definition at line 784 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::max_element(begin(cont), end(cont), std::forward<Compare>(f));
   }
min_element() [1/2]
template<typename Cont > decltype(auto) otto::util::min_element (Cont && cont)
Definition at line 768 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::min_element(begin(cont), end(cont));
   }
min_element() [2/2]
template<typename Cont , typename Compare > decltype(auto) otto::util::min_element (Cont && cont, Compare && f)
Definition at line 776 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::min_element(begin(cont), end(cont), std::forward<Compare>(f));
   }
none_of()
template<typename Cont , typename UnaryPredicate > decltype(auto) otto::util::none_of (Cont && cont, UnaryPredicate && p)
Definition at line 751 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::none_of(begin(cont), end(cont),
                         std::forward<UnaryPredicate>(p));
   }
overloaded()
template<typename... Ls> otto::util::overloaded (Ls...) -> overloaded< std::decay_t< Ls >... >
partial_match()
template<typename Var , typename... Lambdas> decltype(auto) otto::util::partial_match (Var && v, Lambdas &&... ls)
Pattern matching for std::variant.
Does not require all states of v to be matched, and defaults to no action.
Definition at line 44 of file utility.hpp.
References match(), and nullmatch.
   {
     return match(std::forward<Var>(v), std::forward<Lambdas>(ls)..., nullmatch);
   }
prev_permutation() [1/2]
template<typename Cont > decltype(auto) otto::util::prev_permutation (Cont && cont)
Definition at line 183 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::prev_permutation(begin(cont), end(cont));
   }
prev_permutation() [2/2]
template<typename Cont , typename Compare > decltype(auto) otto::util::prev_permutation (Cont && cont, Compare && comp)
Definition at line 191 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::prev_permutation(begin(cont), end(cont),
                                  std::forward<Compare>(comp));
   }
push_heap() [1/2]
template<typename Cont > decltype(auto) otto::util::push_heap (Cont && cont)
Definition at line 200 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::push_heap(begin(cont), end(cont));
   }
push_heap() [2/2]
template<typename Cont , typename Compare > decltype(auto) otto::util::push_heap (Cont && cont, Compare && comp)
Definition at line 208 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::push_heap(begin(cont), end(cont), std::forward<Compare>(comp));
   }
remove()
template<typename Cont , typename T > decltype(auto) otto::util::remove (Cont && cont, T && value)
Definition at line 216 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::remove(begin(cont), end(cont), std::forward<T>(value));
   }
remove_copy()
template<typename Cont , typename OutputIterator , typename T > decltype(auto) otto::util::remove_copy (Cont && cont, OutputIterator && first, T && value)
Definition at line 224 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::remove_copy(begin(cont), end(cont),
                             std::forward<OutputIterator>(first),
                             std::forward<T>(value));
   }
remove_copy_if()
template<typename Cont , typename OutputIterator , typename UnaryPredicate > decltype(auto) otto::util::remove_copy_if (Cont && cont, OutputIterator && first, UnaryPredicate && p)
Definition at line 234 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::remove_copy_if(begin(cont), end(cont),
                                std::forward<OutputIterator>(first),
                                std::forward<UnaryPredicate>(p));
   }
remove_if()
template<typename Cont , typename UnaryPredicate > decltype(auto) otto::util::remove_if (Cont && cont, UnaryPredicate && p)
Definition at line 246 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::remove_if(begin(cont), end(cont),
                           std::forward<UnaryPredicate>(p));
   }
replace()
template<typename Cont , typename T , typename T2 > decltype(auto) otto::util::replace (Cont && cont, T && old_value, T2 && new_value)
Definition at line 255 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::replace(begin(cont), end(cont), std::forward<T>(old_value),
                         std::forward<T2>(new_value));
   }
replace_copy()
template<typename Cont , typename OutputIterator , typename T , typename T2 > decltype(auto) otto::util::replace_copy (Cont && cont, OutputIterator && first, T && old_value, T2 && new_value)
Definition at line 264 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::replace_copy(
       begin(cont), end(cont), std::forward<OutputIterator>(first),
       std::forward<T>(old_value), std::forward<T2>(old_value));
   }
replace_copy_if()
template<typename Cont , typename OutputIterator , typename UnaryPredicate , typename T > decltype(auto) otto::util::replace_copy_if (Cont && cont, OutputIterator && first, UnaryPredicate && p, T && new_value)
Definition at line 280 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::replace_copy(
       begin(cont), end(cont), std::forward<OutputIterator>(first),
       std::forward<UnaryPredicate>(p), std::forward<T>(new_value));
   }
replace_if()
template<typename Cont , typename UnaryPredicate , typename T > decltype(auto) otto::util::replace_if (Cont && cont, UnaryPredicate && p, T && new_value)
Definition at line 293 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::replace_if(begin(cont), end(cont),
                            std::forward<UnaryPredicate>(p),
                            std::forward<T>(new_value));
   }
reverse()
template<typename Cont > decltype(auto) otto::util::reverse (Cont && cont)
Definition at line 303 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::reverse(begin(cont), end(cont));
   }
reverse_copy()
template<typename Cont , typename OutputIterator > decltype(auto) otto::util::reverse_copy (Cont && cont, OutputIterator && first)
Definition at line 311 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::reverse_copy(begin(cont), end(cont),
                              std::forward<OutputIterator>(first));
   }
rotate()
template<typename Cont , typename ForwardIterator > decltype(auto) otto::util::rotate (Cont && cont, ForwardIterator && new_first)
Definition at line 320 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::rotate(begin(cont), std::forward<ForwardIterator>(new_first),
                        end(cont));
   }
rotate_copy()
template<typename Cont , typename ForwardIterator , typename OutputIterator > decltype(auto) otto::util::rotate_copy (Cont && cont, ForwardIterator && new_first, OutputIterator && first)
Definition at line 329 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::rotate_copy(begin(cont),
                             std::forward<ForwardIterator>(new_first), end(cont),
                             std::forward<OutputIterator>(first));
   }
search() [1/2]
template<typename Cont , typename Cont2 > decltype(auto) otto::util::search (Cont && cont, Cont2 && cont2)
Definition at line 341 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::search(begin(cont), end(cont), begin(cont2), end(cont2));
   }
search() [2/2]
template<typename Cont , typename Cont2 , typename BinaryPredicate > decltype(auto) otto::util::search (Cont && cont, Cont2 && cont2, BinaryPredicate && p)
Definition at line 349 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::search(begin(cont), end(cont), begin(cont2), end(cont2),
                        std::forward<BinaryPredicate>(p));
   }
search_n() [1/2]
template<typename Cont , typename Size , typename T > decltype(auto) otto::util::search_n (Cont && cont, Size count, T && value)
Definition at line 358 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::search_n(begin(cont), end(cont), count, std::forward<T>(value));
   }
search_n() [2/2]
template<typename Cont , typename Size , typename T , typename BinaryPredicate > decltype(auto) otto::util::search_n (Cont && cont, Size count, T && value, BinaryPredicate && p)
Definition at line 366 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::search_n(begin(cont), end(cont), count, std::forward<T>(value),
                          std::forward<BinaryPredicate>(p));
   }
set_difference() [1/2]
template<typename Cont , typename Cont2 , typename OutputIterator > decltype(auto) otto::util::set_difference (Cont && cont, Cont2 && cont2, OutputIterator && first)
Definition at line 378 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::set_difference(begin(cont), end(cont), begin(cont2), end(cont2),
                                std::forward<OutputIterator>(first));
   }
set_difference() [2/2]
template<typename Cont , typename Cont2 , typename OutputIterator , typename Compare > decltype(auto) otto::util::set_difference (Cont && cont, Cont2 && cont2, OutputIterator && first, Compare && comp)
Definition at line 392 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::set_difference(begin(cont), end(cont), begin(cont2), end(cont2),
                                std::forward<OutputIterator>(first),
                                std::forward<Compare>(comp));
   }
set_intersection() [1/2]
template<typename Cont , typename Cont2 , typename OutputIterator > decltype(auto) otto::util::set_intersection (Cont && cont, Cont2 && cont2, OutputIterator && first)
Definition at line 405 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::set_intersection(begin(cont), end(cont), begin(cont2),
                                  end(cont2),
                                  std::forward<OutputIterator>(first));
   }
set_intersection() [2/2]
template<typename Cont , typename Cont2 , typename OutputIterator , typename Compare > decltype(auto) otto::util::set_intersection (Cont && cont, Cont2 && cont2, OutputIterator && first, Compare && comp)
Definition at line 420 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::set_intersection(
       begin(cont), end(cont), begin(cont2), end(cont2),
       std::forward<OutputIterator>(first), std::forward<Compare>(comp));
   }
set_symmetric_difference() [1/2]
template<typename Cont , typename Cont2 , typename OutputIterator > decltype(auto) otto::util::set_symmetric_difference (Cont && cont, Cont2 && cont2, OutputIterator && first)
Definition at line 433 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::set_symmetric_difference(begin(cont), end(cont), begin(cont2),
                                          end(cont2),
                                          std::forward<OutputIterator>(first));
   }
set_symmetric_difference() [2/2]
template<typename Cont , typename Cont2 , typename OutputIterator , typename Compare > decltype(auto) otto::util::set_symmetric_difference (Cont && cont, Cont2 && cont2, OutputIterator && first, Compare && comp)
Definition at line 448 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::set_symmetric_difference(
       begin(cont), end(cont), begin(cont2), end(cont2),
       std::forward<OutputIterator>(first), std::forward<Compare>(comp));
   }
set_union() [1/2]
template<typename Cont , typename Cont2 , typename OutputIterator > decltype(auto) otto::util::set_union (Cont && cont, Cont2 && cont2, OutputIterator && first)
Definition at line 461 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::set_union(begin(cont), end(cont), begin(cont2), end(cont2),
                           std::forward<OutputIterator>(first));
   }
set_union() [2/2]
template<typename Cont , typename Cont2 , typename OutputIterator , typename Compare > decltype(auto) otto::util::set_union (Cont && cont, Cont2 && cont2, OutputIterator && first, Compare && comp)
Definition at line 473 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::set_union(begin(cont), end(cont), begin(cont2), end(cont2),
                           std::forward<OutputIterator>(first),
                           std::forward<Compare>(comp));
   }
shuffle()
template<typename Cont , typename UniformRandomNumberGenerator > decltype(auto) otto::util::shuffle (Cont && cont, UniformRandomNumberGenerator && g)
Definition at line 486 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::shuffle(begin(cont), end(cont),
                         std::forward<UniformRandomNumberGenerator>(g));
   }
sort() [1/2]
template<typename Cont > decltype(auto) otto::util::sort (Cont && cont)
Definition at line 495 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::sort(begin(cont), end(cont));
   }
sort() [2/2]
template<typename Cont , typename Compare > decltype(auto) otto::util::sort (Cont && cont, Compare && comp)
Definition at line 503 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::sort(begin(cont), end(cont), std::forward<Compare>(comp));
   }
sort_heap() [1/2]
template<typename Cont > decltype(auto) otto::util::sort_heap (Cont && cont)
Definition at line 511 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::sort_heap(begin(cont), end(cont));
   }
sort_heap() [2/2]
template<typename Cont , typename Compare > decltype(auto) otto::util::sort_heap (Cont && cont, Compare && comp)
Definition at line 519 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::sort_heap(begin(cont), end(cont), std::forward<Compare>(comp));
   }
stable_partition()
template<typename Cont , typename UnaryPredicate > decltype(auto) otto::util::stable_partition (Cont && cont, UnaryPredicate && p)
Definition at line 527 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::stable_partition(begin(cont), end(cont),
                                  std::forward<UnaryPredicate>(p));
   }
stable_sort() [1/2]
template<typename Cont > decltype(auto) otto::util::stable_sort (Cont && cont)
Definition at line 536 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::stable_sort(begin(cont), end(cont));
   }
stable_sort() [2/2]
template<typename Cont , typename Compare > decltype(auto) otto::util::stable_sort (Cont && cont, Compare && comp)
Definition at line 544 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::stable_sort(begin(cont), end(cont),
                             std::forward<Compare>(comp));
   }
swap()
void otto::util::swap (ByteFile & first, ByteFile & sec)
Definition at line 30 of file bytefile.cpp.
{
     using std::swap;
     // TODO: Do swaps;
   }
swap_ranges()
template<typename Cont , typename ForwardIterator > decltype(auto) otto::util::swap_ranges (Cont && cont, ForwardIterator && first)
Definition at line 553 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::swap_ranges(begin(cont), end(cont),
                             std::forward<ForwardIterator>(first));
   }
to_string()
std::string otto::util::to_string (JsonFile::ErrorCode)
String representation of JsonFile::ErrorCode.
This is used by util::as_exception to print the error message.
Definition at line 57 of file jsonfile.cpp.
   {
     using ErrorCode = JsonFile::ErrorCode;
     switch (ec) {
     case ErrorCode::none: return "";
     case ErrorCode::invalid_json: return "Invalid json";
     case ErrorCode::missing_header: return "OTTO Preset header missing";
     case ErrorCode::unknown_version: return "Unknown preset format version";
     case ErrorCode::invalid_data: return "Invalid preset data. Take a look at the specification again";
     }
   }
transform() [1/6]
template<typename Cont , typename Cont2 , typename F > auto otto::util::transform (Cont && cont, Cont2 && cont2, F && f) -> decltype(begin(cont2))
Definition at line 562 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::transform(begin(cont), end(cont), begin(cont2),
                           std::forward<F>(f));
   }
transform() [2/6]
template<typename Cont , typename Iter , typename F > decltype(auto) otto::util::transform (Cont && cont, Iter && iter, F && f)
Definition at line 571 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::transform(begin(cont), end(cont), std::forward<Iter>(iter),
                           std::forward<F>(f));
   }
transform() [3/6]
template<typename Cont , typename Cont2 , typename Cont3 , typename BinaryPredicate > auto otto::util::transform (Cont && cont, Cont2 && cont2, Cont3 && cont3, BinaryPredicate && f) -> decltype(begin(cont2), begin(cont3))
Definition at line 583 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::transform(begin(cont), end(cont), begin(cont2), begin(cont3),
                           std::forward<BinaryPredicate>(f));
   }
transform() [4/6]
template<typename Cont , typename InputIterator , typename Cont3 , typename BinaryPredicate > auto otto::util::transform (Cont && cont, InputIterator && iter, Cont3 && cont3, BinaryPredicate && f) -> decltype(begin(cont), begin(cont3))
Definition at line 596 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::transform(begin(cont), end(cont),
                           std::forward<InputIterator>(iter), begin(cont3),
                           std::forward<BinaryPredicate>(f));
   }
transform() [5/6]
template<typename Cont , typename Cont2 , typename InputIterator , typename BinaryPredicate > auto otto::util::transform (Cont && cont, Cont2 && cont2, InputIterator && iter, BinaryPredicate && f) -> decltype(begin(cont), begin(cont2), iter)
Definition at line 612 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::transform(begin(cont), end(cont), begin(cont2),
                           std::forward<InputIterator>(iter),
                           std::forward<BinaryPredicate>(f));
   }
transform() [6/6]
template<typename Cont , typename InputIterator , typename OutputIterator , typename BinaryOperation > decltype(auto) otto::util::transform (Cont && cont, InputIterator && firstIn, OutputIterator && firstOut, BinaryOperation && op)
Definition at line 629 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::transform(begin(cont), end(cont),
                           std::forward<InputIterator>(firstIn),
                           std::forward<OutputIterator>(firstOut),
                           std::forward<BinaryOperation>(op));
   }
underlying() [1/2]
template<typename E > constexpr auto otto::util::underlying (E e) -> std::enable_if_t<!std::is_enum_v<E>, E> noexcept
Cast scoped enums to their underlying numeric type.
Definition at line 215 of file type_traits.hpp.
Referenced by otto::board::ui::Modifiers::is(), otto::board::ui::Modifiers::operator &(), otto::board::ui::Modifiers::operator|(), otto::core::props::OTTO_PROPS_MIXIN_LEAF(), and otto::board::ui::Modifiers::set().
   {
     return e;
   }
underlying() [2/2]
template<typename E , typename = std::enable_if_t<std::is_enum_v<E>>> constexpr auto otto::util::underlying (E e) noexcept
Definition at line 221 of file type_traits.hpp.
   {
     return static_cast<std::underlying_type_t<E>>(e);
   }
unique() [1/2]
template<typename Cont > decltype(auto) otto::util::unique (Cont && cont)
Definition at line 643 of file algorithm.hpp.
Referenced by otto::engines::Euclid::process().
   {
     using std::begin;
     using std::end;
     return std::unique(begin(cont), end(cont));
   }
unique() [2/2]
template<typename Cont , typename BinaryPredicate > decltype(auto) otto::util::unique (Cont && cont, BinaryPredicate && p)
Definition at line 651 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::unique(begin(cont), end(cont),
                        std::forward<BinaryPredicate>(p));
   }
unique_copy() [1/2]
template<typename Cont , typename OutputIterator > decltype(auto) otto::util::unique_copy (Cont && cont, OutputIterator && first)
Definition at line 660 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::unique_copy(begin(cont), end(cont),
                             std::forward<OutputIterator>(first));
   }
unique_copy() [2/2]
template<typename Cont , typename OutputIterator , typename BinaryPredicate > decltype(auto) otto::util::unique_copy (Cont && cont, OutputIterator && first, BinaryPredicate && p)
Definition at line 669 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::unique_copy(begin(cont), end(cont),
                             std::forward<OutputIterator>(first),
                             std::forward<BinaryPredicate>(p));
   }
upper_bound() [1/2]
template<typename Cont , typename T > decltype(auto) otto::util::upper_bound (Cont && cont, T && value)
Definition at line 681 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::upper_bound(begin(cont), end(cont), std::forward<T>(value));
   }
upper_bound() [2/2]
template<typename Cont , typename T , typename Compare > decltype(auto) otto::util::upper_bound (Cont && cont, T && value, Compare && comp)
Definition at line 689 of file algorithm.hpp.
   {
     using std::begin;
     using std::end;
     return std::upper_bound(begin(cont), end(cont), std::forward<T>(value),
                             std::forward<Compare>(comp));
   }
zip()
template<typename... Ranges> auto otto::util::zip (Ranges &&... ranges)
Create a zipped range from ranges.
Definition at line 831 of file iterator.hpp.
Referenced by otto::util::audio::add_all(), and otto::service::engines::process().
{
     return ZippedRange<Ranges...>(std::forward<Ranges>(ranges)...);
   }
zip_iters()
template<typename... Iterators> zipped_iterator<Iterators...> otto::util::zip_iters (Iterators... iters)
Create a zipped iterator from iterators.
Definition at line 802 of file iterator.hpp.
{
     return zipped_iterator<Iterators...>(iters...);
   }
Variable Documentation
is_equal_comparable_v
template<typename T1 , typename T2 = T1> constexpr bool otto::util::is_equal_comparable_v = is_equal_comparable<T1, T2>::value
Definition at line 45 of file type_traits.hpp.
is_greater_than_comparable_v
template<typename T1 , typename T2 = T1> constexpr bool otto::util::is_greater_than_comparable_v = is_greater_than_comparable<T1, T2>::value
Definition at line 73 of file type_traits.hpp.
is_invocable_r_v
template<typename R , typename F , typename... Args> constexpr bool otto::util::is_invocable_r_v
Initial value:
=
    mpark::lib::is_invocable_r<R, F, Args...>::value
Definition at line 203 of file type_traits.hpp.
is_invocable_v
template<typename F , typename... Args> constexpr bool otto::util::is_invocable_v = mpark::lib::is_invocable<F, Args...>::value
Definition at line 197 of file type_traits.hpp.
is_iterator_v
template<typename iter , typename type , typename category > constexpr bool otto::util::is_iterator_v = is_iterator<iter, type, category>::value
true if iter is an iterator over type, with category of at least category
Checks std::iterator_traits
Definition at line 150 of file type_traits.hpp.
is_less_than_comparable_v
template<typename T1 , typename T2 = T1> constexpr bool otto::util::is_less_than_comparable_v = is_less_than_comparable<T1, T2>::value
Definition at line 59 of file type_traits.hpp.
is_number_or_enum_v
template<typename T > constexpr bool otto::util::is_number_or_enum_v = is_number_or_enum<T>::value inline
Definition at line 31 of file type_traits.hpp.
is_number_v
template<typename T > constexpr bool otto::util::is_number_v = is_number<T>::value inline
Definition at line 20 of file type_traits.hpp.
is_one_of_v
template<typename T , typename... Ts> constexpr bool otto::util::is_one_of_v = (std::is_same_v<T, Ts> || ...)
Definition at line 118 of file type_traits.hpp.
nullmatch
const constexpr auto otto::util::nullmatch = [](const auto&&) {}
Match any type, do nothing with it.
Definition at line 37 of file utility.hpp.
Referenced by partial_match().
select_type_v
template<bool b, typename T1 , typename T2 > constexpr bool otto::util::select_type_v = select_type<b, T1, T2>::value
Definition at line 110 of file type_traits.hpp.