OTTO: otto::test Namespace Reference
otto::test Namespace Reference
Classes
struct measure
Functions
void show_gui (core::ui::vg::Size size, std::function< void(core::ui::vg::Canvas &ctx)> draw)
void show_gui (std::function< void(core::ui::vg::Canvas &ctx)> draw)
void truncateFile (const filesystem::path &p)
Variables
fs::path dir = fs::current_path() / "testdir"
Function Documentation
show_gui() [1/2]
void otto::test::show_gui (core::ui::vg::Size size, std::function< void(core::ui::vg::Canvas &ctx)> draw)
Referenced by show_gui().
show_gui() [2/2]
void otto::test::show_gui (std::function< void(core::ui::vg::Canvas &ctx)> draw)
Definition at line 12 of file graphics.t.hpp.
References otto::core::ui::vg::height, std::move(), show_gui(), and otto::core::ui::vg::width.
truncateFile()
void otto::test::truncateFile (const filesystem::path & p)
Definition at line 27 of file testing.t.hpp.
References std::fstream::close(), and std::fstream::open().
Variable Documentation
dir
fs::path otto::test::dir = fs::current_path() / "testdir"
Definition at line 25 of file testing.t.hpp.