OTTO: otto::util::iterator::view Namespace Reference
otto::util::iterator::view Namespace Reference
Detailed Description
This namespace contains lazily evaluated "views" into containers.
Functions
template<typename Range , typename Callable >
auto transform (Range &&r, Callable &&c)
template<typename Range , typename Predicate >
auto filter (Range &&r, Predicate &&c)
Function Documentation
template<typename Range , typename Callable > auto otto::util::iterator::view::transform (Range && r, Callable && c)
Definition at line 995 of file iterator.hpp.
References std::begin(), otto::filesystem::begin(), and std::end().
template<typename Range , typename Predicate > auto otto::util::iterator::view::filter (Range && r, Predicate && c)
Definition at line 1079 of file iterator.hpp.
References std::begin(), otto::filesystem::begin(), and std::end().