OTTO: otto::service::audio::events Namespace Reference
otto::service::audio::events Namespace Reference
Functions
util::Event & pre_init ()
util::Event< unsigned > & buffersize_change ()
util::Event< unsigned > & samplerate_change ()
Function Documentation
pre_init()
util::Event & otto::service::audio::events::pre_init ()
Definition at line 47 of file audio.cpp.
Referenced by otto::service::audio::init().
buffersize_change()
util::Event< unsigned > & otto::service::audio::events::buffersize_change ()
Definition at line 52 of file audio.cpp.
Referenced by otto::service::audio::AlsaAudioDriver::init().
samplerate_change()
util::Event< unsigned > & otto::service::audio::events::samplerate_change ()
Definition at line 57 of file audio.cpp.
Referenced by otto::service::audio::AlsaAudioDriver::init().