OTTO: otto::otto::util Namespace Reference
otto::otto::util Namespace Reference
Functions
std::string to_lowercase (std::string_view sv) noexcept
std::string to_uppercase (std::string_view sv) noexcept
std::string to_string (int i) noexcept
std::string to_string (long i) noexcept
std::string to_string (long long i) noexcept
std::string to_string (unsigned int i) noexcept
std::string to_string (unsigned long i) noexcept
std::string to_string (unsigned long long i) noexcept
std::string to_string (float i) noexcept
std::string to_string (double i) noexcept
std::string to_string (long double i) noexcept
std::string_view to_string (bool b) noexcept
std::string_view to_string (std::string_view sv) noexcept
template<>
tl::expected< int, StringConvErr > from_string (std::string_view sv) noexcept
template<>
tl::expected< long, StringConvErr > from_string (std::string_view sv) noexcept
template<>
tl::expected< long long, StringConvErr > from_string (std::string_view sv) noexcept
template<>
tl::expected< unsigned int, StringConvErr > from_string (std::string_view sv) noexcept
template<>
tl::expected< unsigned long, StringConvErr > from_string (std::string_view sv) noexcept
template<>
tl::expected< unsigned long long, StringConvErr > from_string (std::string_view sv) noexcept
template<>
tl::expected< float, StringConvErr > from_string (std::string_view sv) noexcept
template<>
tl::expected< double, StringConvErr > from_string (std::string_view sv) noexcept
template<>
tl::expected< long double, StringConvErr > from_string (std::string_view sv) noexcept
template<>
tl::expected< bool, StringConvErr > from_string (std::string_view sv) noexcept
template<>
tl::expected< std::string_view, StringConvErr > from_string (std::string_view sv) noexcept
Function Documentation
to_lowercase()
std::string otto::otto::util::to_lowercase (std::string_view sv) noexcept
Definition at line 61 of file string_conversions.hpp.
References std::back_inserter(), std::string::reserve(), and std::transform().
Referenced by from_string(), and otto::core::engine::EngineDispatcher< ET, Engines >::select().
to_uppercase()
std::string otto::otto::util::to_uppercase (std::string_view sv) noexcept
Definition at line 69 of file string_conversions.hpp.
References std::back_inserter(), std::string::reserve(), and std::transform().
to_string() [1/11]
std::string otto::otto::util::to_string (int i) noexcept
Definition at line 77 of file string_conversions.hpp.
References std::to_string().
to_string() [2/11]
std::string otto::otto::util::to_string (long i) noexcept
Definition at line 81 of file string_conversions.hpp.
References std::to_string().
to_string() [3/11]
std::string otto::otto::util::to_string (long long i) noexcept
Definition at line 85 of file string_conversions.hpp.
References std::to_string().
to_string() [4/11]
std::string otto::otto::util::to_string (unsigned int i) noexcept
Definition at line 89 of file string_conversions.hpp.
References std::to_string().
to_string() [5/11]
std::string otto::otto::util::to_string (unsigned long i) noexcept
Definition at line 93 of file string_conversions.hpp.
References std::to_string().
to_string() [6/11]
std::string otto::otto::util::to_string (unsigned long long i) noexcept
Definition at line 97 of file string_conversions.hpp.
References std::to_string().
to_string() [7/11]
std::string otto::otto::util::to_string (float i) noexcept
Definition at line 102 of file string_conversions.hpp.
References std::to_string().
to_string() [8/11]
std::string otto::otto::util::to_string (double i) noexcept
Definition at line 106 of file string_conversions.hpp.
References std::to_string().
to_string() [9/11]
std::string otto::otto::util::to_string (long double i) noexcept
Definition at line 110 of file string_conversions.hpp.
References std::to_string().
to_string() [10/11]
std::string_view otto::otto::util::to_string (bool b) noexcept
Definition at line 115 of file string_conversions.hpp.
to_string() [11/11]
std::string_view otto::otto::util::to_string (std::string_view sv) noexcept
Definition at line 119 of file string_conversions.hpp.
from_string() [1/11]
template<> tl::expected<int, StringConvErr> otto::otto::util::from_string (std::string_view sv) noexcept
Definition at line 125 of file string_conversions.hpp.
References otto::util::invalid_input, otto::util::out_of_range, and std::strtol().
from_string() [2/11]
template<> tl::expected<long, StringConvErr> otto::otto::util::from_string (std::string_view sv) noexcept
Definition at line 140 of file string_conversions.hpp.
References otto::util::invalid_input, otto::util::out_of_range, and std::strtol().
from_string() [3/11]
template<> tl::expected<long long, StringConvErr> otto::otto::util::from_string (std::string_view sv) noexcept
Definition at line 155 of file string_conversions.hpp.
References otto::util::invalid_input, otto::util::out_of_range, and std::strtoll().
from_string() [4/11]
template<> tl::expected<unsigned int, StringConvErr> otto::otto::util::from_string (std::string_view sv) noexcept
Definition at line 170 of file string_conversions.hpp.
References otto::util::invalid_input, otto::util::out_of_range, and std::strtoul().
from_string() [5/11]
template<> tl::expected<unsigned long, StringConvErr> otto::otto::util::from_string (std::string_view sv) noexcept
Definition at line 185 of file string_conversions.hpp.
References otto::util::invalid_input, otto::util::out_of_range, and std::strtoul().
from_string() [6/11]
template<> tl::expected<unsigned long long, StringConvErr> otto::otto::util::from_string (std::string_view sv) noexcept
Definition at line 200 of file string_conversions.hpp.
References otto::util::invalid_input, otto::util::out_of_range, and std::strtoull().
from_string() [7/11]
template<> tl::expected<float, StringConvErr> otto::otto::util::from_string (std::string_view sv) noexcept
Definition at line 216 of file string_conversions.hpp.
References otto::util::invalid_input, otto::util::out_of_range, and std::strtof().
from_string() [8/11]
template<> tl::expected<double, StringConvErr> otto::otto::util::from_string (std::string_view sv) noexcept
Definition at line 232 of file string_conversions.hpp.
References otto::util::invalid_input, otto::util::out_of_range, and std::strtod().
from_string() [9/11]
template<> tl::expected<long double, StringConvErr> otto::otto::util::from_string (std::string_view sv) noexcept
Definition at line 247 of file string_conversions.hpp.
References otto::util::invalid_input, otto::util::out_of_range, and std::strtold().
from_string() [10/11]
template<> tl::expected<bool, StringConvErr> otto::otto::util::from_string (std::string_view sv) noexcept
Definition at line 263 of file string_conversions.hpp.
References otto::util::out_of_range, and otto::util::to_lowercase().
from_string() [11/11]
template<> tl::expected<std::string_view, StringConvErr> otto::otto::util::from_string (std::string_view sv) noexcept
Definition at line 271 of file string_conversions.hpp.