OTTO: otto::util::view Namespace Reference
otto::util::view Namespace Reference
Functions
template<typename Range , typename Callable >
auto transform (Range &&r, Callable &&c)
template<typename Range , typename Predicate >
auto filter (Range &&r, Predicate &&c)
Function Documentation
transform()
template<typename Range , typename Callable > auto otto::util::view::transform (Range && r, Callable && c)
Definition at line 1077 of file iterator.hpp.
References std::begin(), otto::filesystem::begin(), and std::end().
filter()
template<typename Range , typename Predicate > auto otto::util::view::filter (Range && r, Predicate && c)
Definition at line 1090 of file iterator.hpp.
References std::begin(), otto::filesystem::begin(), and std::end().