OTTO: otto::service::state Namespace Reference
otto::service::state Namespace Reference
Typedefs
using Loader = std::function< void(nlohmann::json &json)>
Decoder.
using Saver = std::function< nlohmann::json()>
Encoder.
Functions
void load ()
Read data/state.json and invoke attached loaders.
void save ()
Invoke attached savers and write data/state.json
void attach (std::string name, Loader load, Saver save)
void detach (const std::string &name)
void detach (std::string name)
Typedef Documentation
Loader
using otto::service::state::Loader = typedef std::function<void(nlohmann::json& json)>
Decoder.
Definition at line 9 of file state.hpp.
Saver
using otto::service::state::Saver = typedef std::function<nlohmann::json()>
Encoder.
Definition at line 11 of file state.hpp.
Function Documentation
attach()
void otto::service::state::attach (std::string name, Loader load, Saver save)
Attach state handler with a name
Exceptions
[otto::util::exception]() If a handler has already been attached with the name name
Definition at line 106 of file state.cpp.
References load(), and save().
Referenced by otto::service::engines::init(), and otto::service::ui::init().
   {
     State::instance().attach(std::move(name), std::move(load), std::move(save));
   }
detach() [1/2]
void otto::service::state::detach (std::string name)
Detach a state handler
Exceptions
[otto::util::exception]() If no such handler is attached
detach() [2/2]
void otto::service::state::detach (const std::string & name)
Definition at line 111 of file state.cpp.
   {
     State::instance().detach(name);
   }
load()
void otto::service::state::load ()
Read data/state.json and invoke attached loaders.
Definition at line 96 of file state.cpp.
Referenced by attach().
   {
     State::instance().load();
   }
save()
void otto::service::state::save ()
Invoke attached savers and write data/state.json
Definition at line 101 of file state.cpp.
Referenced by attach().
   {
     State::instance().save();
   }