OTTO: otto::util::iterator Namespace Reference
otto::util::iterator Namespace Reference
Detailed Description
This namespace contains custom iterator types and general helper classes for working with containers
Attention
otto::util::iterator is an inline namespace, meaning all members can and should be accessed directly from the otto::util namespace i.e. as util::float_step(...), not util::iterator::float_step(...). It is only a separate namespace for clarification of documentation and name resolution.
Namespaces
view
Classes
struct adjacent_pair_iterator
struct AdjacentRange
struct circular_iterator
Circular Iterator.
struct filter_iterator
Filter iterator.
class float_step_iterator
struct generating_iterator
Generating iterator.
struct iterator_facade
Zero overhead wrapper to create iterators.
struct iterator_facade< Derived, Va, std::random_access_iterator_tag, Re, Po, Di >
struct iterator_facade< Derived, ValueType, std::bidirectional_iterator_tag, Reference, Pointer, Difference >
struct sequence
A simple sequence of data, defined by a pair of iterators.
struct transform_iterator
Transform iterator.
struct zipped_iterator
Zipped iterator.
struct ZippedRange
Functions
template<typename Iterator >
float_step_iterator (const Iterator &iter, float step) -> float_step_iterator< Iterator >
template<typename I , typename V = typename detail::value_type<std::decay_t<I>>::type>
auto float_step (I &&iter, float step=1)
Create a float_step_iterator.
template<typename Generator >
generating_iterator< Generator > generator (Generator &&gen)
Create a generating iterator.
template<typename... Iterators>
zipped_iterator< Iterators... > zip_iters (Iterators... iters)
Create a zipped iterator from iterators.
template<typename... Ranges>
auto zip (Ranges &&... ranges)
Create a ZippedRange from ranges.
template<typename Range >
auto adjacent_pairs (Range &rng)
template<typename BIter , typename EIter >
auto adjacent_pairs (BIter f, EIter l)
Function Documentation
float_step_iterator()
template<typename Iterator > otto::util::iterator::float_step_iterator (const Iterator & iter, float step) -> float_step_iterator< Iterator >
float_step()
template<typename I , typename V = typename detail::value_type<std::decay_t<I>>::type> auto otto::util::iterator::float_step (I && iter, float step = 1)
Create a float_step_iterator.
Definition at line 696 of file iterator.hpp.
generator()
template<typename Generator > generating_iterator<Generator> otto::util::iterator::generator (Generator && gen)
Create a generating iterator.
Definition at line 747 of file iterator.hpp.
Referenced by otto::util::iterator::generating_iterator< Generator >::generating_iterator().
zip_iters()
template<typename... Iterators> zipped_iterator<Iterators...> otto::util::iterator::zip_iters (Iterators... iters)
Create a zipped iterator from iterators.
Definition at line 838 of file iterator.hpp.
zip()
template<typename... Ranges> auto otto::util::iterator::zip (Ranges &&... ranges)
Create a ZippedRange from ranges.
Its very useful with structured bindings and for loops, letting you iterate over multiple containers at once:
for (auto&& [r1, r2] : util::zip(range1, range2)) {
  ...
}
Definition at line 882 of file iterator.hpp.
Referenced by otto::util::audio::add_all(), and otto::core::voices::VoiceManager< Post, 6 >::VoiceManager().
adjacent_pairs() [1/2]
template<typename Range > auto otto::util::iterator::adjacent_pairs (Range & rng)
Definition at line 960 of file iterator.hpp.
adjacent_pairs() [2/2]
template<typename BIter , typename EIter > auto otto::util::iterator::adjacent_pairs (BIter f, EIter l)
Definition at line 966 of file iterator.hpp.