OTTO: otto::board::ui Namespace Reference
otto::board::ui Namespace Reference
Classes
class EGLConnection
struct Modifiers
A set of modifiers.
struct RpiFBCP
Enumerations
enum Key {
Key::unknown = KEY_UNKNOWN, Key::space = KEY_SPACE, Key::apostrophe = KEY_APOSTROPHE, Key::comma = KEY_COMMA,
Key::minus = KEY_MINUS, Key::period = KEY_DOT, Key::slash = KEY_SLASH, Key::n0 = KEY_0,
Key::n1 = KEY_1, Key::n2 = KEY_2, Key::n3 = KEY_3, Key::n4 = KEY_4,
Key::n5 = KEY_5, Key::n6 = KEY_6, Key::n7 = KEY_7, Key::n8 = KEY_8,
Key::n9 = KEY_9, Key::semicolon = KEY_SEMICOLON, Key::equal = KEY_EQUAL, Key::a = KEY_A,
Key::b = KEY_B, Key::c = KEY_C, Key::d = KEY_D, Key::e = KEY_E,
Key::f = KEY_F, Key::g = KEY_G, Key::h = KEY_H, Key::i = KEY_I,
Key::j = KEY_J, Key::k = KEY_K, Key::l = KEY_L, Key::m = KEY_M,
Key::n = KEY_N, Key::o = KEY_O, Key::p = KEY_P, Key::q = KEY_Q,
Key::r = KEY_R, Key::s = KEY_S, Key::t = KEY_T, Key::u = KEY_U,
Key::v = KEY_V, Key::w = KEY_W, Key::x = KEY_X, Key::y = KEY_Y,
Key::z = KEY_Z, Key::left_bracket = KEY_LEFTBRACE, Key::backslash = KEY_BACKSLASH, Key::right_bracket = KEY_RIGHTBRACE,
Key::grave_accent = KEY_GRAVE, Key::escape = KEY_ESC, Key::enter = KEY_ENTER, Key::tab = KEY_TAB,
Key::backspace = KEY_BACKSPACE, Key::insert = KEY_INSERT, Key::del = KEY_DELETE, Key::right = KEY_RIGHT,
Key::left = KEY_LEFT, Key::down = KEY_DOWN, Key::up = KEY_UP, Key::page_up = KEY_PAGEUP,
Key::page_down = KEY_PAGEDOWN, Key::home = KEY_HOME, Key::end = KEY_END, Key::caps_lock = KEY_CAPSLOCK,
Key::scroll_lock = KEY_SCROLLLOCK, Key::num_lock = KEY_NUMLOCK, Key::print_screen = KEY_PRINT, Key::pause = KEY_PAUSE,
Key::f1 = KEY_F1, Key::f2 = KEY_F2, Key::f3 = KEY_F3, Key::f4 = KEY_F4,
Key::f5 = KEY_F5, Key::f6 = KEY_F6, Key::f7 = KEY_F7, Key::f8 = KEY_F8,
Key::f9 = KEY_F9, Key::f10 = KEY_F10, Key::f11 = KEY_F11, Key::f12 = KEY_F12,
Key::f13 = KEY_F13, Key::f14 = KEY_F14, Key::f15 = KEY_F15, Key::f16 = KEY_F16,
Key::f17 = KEY_F17, Key::f18 = KEY_F18, Key::f19 = KEY_F19, Key::f20 = KEY_F20,
Key::f21 = KEY_F21, Key::f22 = KEY_F22, Key::f23 = KEY_F23, Key::f24 = KEY_F24,
Key::kp_0 = KEY_KP0, Key::kp_1 = KEY_KP1, Key::kp_2 = KEY_KP2, Key::kp_3 = KEY_KP3,
Key::kp_4 = KEY_KP4, Key::kp_5 = KEY_KP5, Key::kp_6 = KEY_KP6, Key::kp_7 = KEY_KP7,
Key::kp_8 = KEY_KP8, Key::kp_9 = KEY_KP9, Key::kp_decimal = KEY_KPDOT, Key::kp_divide = KEY_KPSLASH,
Key::kp_multiply = KEY_KPASTERISK, Key::kp_subtract = KEY_KPMINUS, Key::kp_add = KEY_KPPLUS, Key::kp_enter = KEY_KPENTER,
Key::kp_equal = KEY_KPEQUAL, Key::left_shift = KEY_LEFTSHIFT, Key::left_control = KEY_LEFTCTRL, Key::left_alt = KEY_LEFTALT,
Key::left_super = KEY_LEFTMETA, Key::right_shift = KEY_RIGHTSHIFT, Key::right_control = KEY_RIGHTCTRL, Key::right_alt = KEY_RIGHTALT,
Key::right_super = KEY_RIGHTMETA, Key::menu = KEY_MENU, Key::last = KEY_LAST, Key::unknown = GLFW_KEY_UNKNOWN,
Key::space = GLFW_KEY_SPACE, Key::apostrophe = GLFW_KEY_APOSTROPHE, Key::comma = GLFW_KEY_COMMA, Key::minus = GLFW_KEY_MINUS,
Key::period = GLFW_KEY_PERIOD, Key::slash = GLFW_KEY_SLASH, Key::n0 = GLFW_KEY_0, Key::n1 = GLFW_KEY_1,
Key::n2 = GLFW_KEY_2, Key::n3 = GLFW_KEY_3, Key::n4 = GLFW_KEY_4, Key::n5 = GLFW_KEY_5,
Key::n6 = GLFW_KEY_6, Key::n7 = GLFW_KEY_7, Key::n8 = GLFW_KEY_8, Key::n9 = GLFW_KEY_9,
Key::semicolon = GLFW_KEY_SEMICOLON, Key::equal = GLFW_KEY_EQUAL, Key::a = GLFW_KEY_A, Key::b = GLFW_KEY_B,
Key::c = GLFW_KEY_C, Key::d = GLFW_KEY_D, Key::e = GLFW_KEY_E, Key::f = GLFW_KEY_F,
Key::g = GLFW_KEY_G, Key::h = GLFW_KEY_H, Key::i = GLFW_KEY_I, Key::j = GLFW_KEY_J,
Key::k = GLFW_KEY_K, Key::l = GLFW_KEY_L, Key::m = GLFW_KEY_M, Key::n = GLFW_KEY_N,
Key::o = GLFW_KEY_O, Key::p = GLFW_KEY_P, Key::q = GLFW_KEY_Q, Key::r = GLFW_KEY_R,
Key::s = GLFW_KEY_S, Key::t = GLFW_KEY_T, Key::u = GLFW_KEY_U, Key::v = GLFW_KEY_V,
Key::w = GLFW_KEY_W, Key::x = GLFW_KEY_X, Key::y = GLFW_KEY_Y, Key::z = GLFW_KEY_Z,
Key::left_bracket = GLFW_KEY_LEFT_BRACKET, Key::backslash = GLFW_KEY_BACKSLASH, Key::right_bracket = GLFW_KEY_RIGHT_BRACKET, Key::grave_accent = GLFW_KEY_GRAVE_ACCENT,
Key::world_1 = GLFW_KEY_WORLD_1, Key::world_2 = GLFW_KEY_WORLD_2, Key::escape = GLFW_KEY_ESCAPE, Key::enter = GLFW_KEY_ENTER,
Key::tab = GLFW_KEY_TAB, Key::backspace = GLFW_KEY_BACKSPACE, Key::insert = GLFW_KEY_INSERT, Key::del = GLFW_KEY_DELETE,
Key::right = GLFW_KEY_RIGHT, Key::left = GLFW_KEY_LEFT, Key::down = GLFW_KEY_DOWN, Key::up = GLFW_KEY_UP,
Key::page_up = GLFW_KEY_PAGE_UP, Key::page_down = GLFW_KEY_PAGE_DOWN, Key::home = GLFW_KEY_HOME, Key::end = GLFW_KEY_END,
Key::caps_lock = GLFW_KEY_CAPS_LOCK, Key::scroll_lock = GLFW_KEY_SCROLL_LOCK, Key::num_lock = GLFW_KEY_NUM_LOCK, Key::print_screen = GLFW_KEY_PRINT_SCREEN,
Key::pause = GLFW_KEY_PAUSE, Key::f1 = GLFW_KEY_F1, Key::f2 = GLFW_KEY_F2, Key::f3 = GLFW_KEY_F3,
Key::f4 = GLFW_KEY_F4, Key::f5 = GLFW_KEY_F5, Key::f6 = GLFW_KEY_F6, Key::f7 = GLFW_KEY_F7,
Key::f8 = GLFW_KEY_F8, Key::f9 = GLFW_KEY_F9, Key::f10 = GLFW_KEY_F10, Key::f11 = GLFW_KEY_F11,
Key::f12 = GLFW_KEY_F12, Key::f13 = GLFW_KEY_F13, Key::f14 = GLFW_KEY_F14, Key::f15 = GLFW_KEY_F15,
Key::f16 = GLFW_KEY_F16, Key::f17 = GLFW_KEY_F17, Key::f18 = GLFW_KEY_F18, Key::f19 = GLFW_KEY_F19,
Key::f20 = GLFW_KEY_F20, Key::f21 = GLFW_KEY_F21, Key::f22 = GLFW_KEY_F22, Key::f23 = GLFW_KEY_F23,
Key::f24 = GLFW_KEY_F24, Key::f25 = GLFW_KEY_F25, Key::kp_0 = GLFW_KEY_KP_0, Key::kp_1 = GLFW_KEY_KP_1,
Key::kp_2 = GLFW_KEY_KP_2, Key::kp_3 = GLFW_KEY_KP_3, Key::kp_4 = GLFW_KEY_KP_4, Key::kp_5 = GLFW_KEY_KP_5,
Key::kp_6 = GLFW_KEY_KP_6, Key::kp_7 = GLFW_KEY_KP_7, Key::kp_8 = GLFW_KEY_KP_8, Key::kp_9 = GLFW_KEY_KP_9,
Key::kp_decimal = GLFW_KEY_KP_DECIMAL, Key::kp_divide = GLFW_KEY_KP_DIVIDE, Key::kp_multiply = GLFW_KEY_KP_MULTIPLY, Key::kp_subtract = GLFW_KEY_KP_SUBTRACT,
Key::kp_add = GLFW_KEY_KP_ADD, Key::kp_enter = GLFW_KEY_KP_ENTER, Key::kp_equal = GLFW_KEY_KP_EQUAL, Key::left_shift = GLFW_KEY_LEFT_SHIFT,
Key::left_control = GLFW_KEY_LEFT_CONTROL, Key::left_alt = GLFW_KEY_LEFT_ALT, Key::left_super = GLFW_KEY_LEFT_SUPER, Key::right_shift = GLFW_KEY_RIGHT_SHIFT,
Key::right_control = GLFW_KEY_RIGHT_CONTROL, Key::right_alt = GLFW_KEY_RIGHT_ALT, Key::right_super = GLFW_KEY_RIGHT_SUPER, Key::menu = GLFW_KEY_MENU,
Key::last = GLFW_KEY_LAST
}
Linux keys.
enum Modifier {
Modifier::none = 0, Modifier::shift = 0b0001, Modifier::ctrl = 0b0010, Modifier::alt = 0b0100,
Modifier::super = 0b1000, Modifier::none = 0, Modifier::shift = GLFW_MOD_SHIFT, Modifier::ctrl = GLFW_MOD_CONTROL,
Modifier::alt = GLFW_MOD_ALT, Modifier::super = GLFW_MOD_SUPER
}
Modifiers.
enum Action {
Action::press, Action::release, Action::repeat, Action::press = GLFW_PRESS,
Action::release = GLFW_RELEASE, Action::repeat = GLFW_REPEAT
}
enum Key {
Key::unknown = KEY_UNKNOWN, Key::space = KEY_SPACE, Key::apostrophe = KEY_APOSTROPHE, Key::comma = KEY_COMMA,
Key::minus = KEY_MINUS, Key::period = KEY_DOT, Key::slash = KEY_SLASH, Key::n0 = KEY_0,
Key::n1 = KEY_1, Key::n2 = KEY_2, Key::n3 = KEY_3, Key::n4 = KEY_4,
Key::n5 = KEY_5, Key::n6 = KEY_6, Key::n7 = KEY_7, Key::n8 = KEY_8,
Key::n9 = KEY_9, Key::semicolon = KEY_SEMICOLON, Key::equal = KEY_EQUAL, Key::a = KEY_A,
Key::b = KEY_B, Key::c = KEY_C, Key::d = KEY_D, Key::e = KEY_E,
Key::f = KEY_F, Key::g = KEY_G, Key::h = KEY_H, Key::i = KEY_I,
Key::j = KEY_J, Key::k = KEY_K, Key::l = KEY_L, Key::m = KEY_M,
Key::n = KEY_N, Key::o = KEY_O, Key::p = KEY_P, Key::q = KEY_Q,
Key::r = KEY_R, Key::s = KEY_S, Key::t = KEY_T, Key::u = KEY_U,
Key::v = KEY_V, Key::w = KEY_W, Key::x = KEY_X, Key::y = KEY_Y,
Key::z = KEY_Z, Key::left_bracket = KEY_LEFTBRACE, Key::backslash = KEY_BACKSLASH, Key::right_bracket = KEY_RIGHTBRACE,
Key::grave_accent = KEY_GRAVE, Key::escape = KEY_ESC, Key::enter = KEY_ENTER, Key::tab = KEY_TAB,
Key::backspace = KEY_BACKSPACE, Key::insert = KEY_INSERT, Key::del = KEY_DELETE, Key::right = KEY_RIGHT,
Key::left = KEY_LEFT, Key::down = KEY_DOWN, Key::up = KEY_UP, Key::page_up = KEY_PAGEUP,
Key::page_down = KEY_PAGEDOWN, Key::home = KEY_HOME, Key::end = KEY_END, Key::caps_lock = KEY_CAPSLOCK,
Key::scroll_lock = KEY_SCROLLLOCK, Key::num_lock = KEY_NUMLOCK, Key::print_screen = KEY_PRINT, Key::pause = KEY_PAUSE,
Key::f1 = KEY_F1, Key::f2 = KEY_F2, Key::f3 = KEY_F3, Key::f4 = KEY_F4,
Key::f5 = KEY_F5, Key::f6 = KEY_F6, Key::f7 = KEY_F7, Key::f8 = KEY_F8,
Key::f9 = KEY_F9, Key::f10 = KEY_F10, Key::f11 = KEY_F11, Key::f12 = KEY_F12,
Key::f13 = KEY_F13, Key::f14 = KEY_F14, Key::f15 = KEY_F15, Key::f16 = KEY_F16,
Key::f17 = KEY_F17, Key::f18 = KEY_F18, Key::f19 = KEY_F19, Key::f20 = KEY_F20,
Key::f21 = KEY_F21, Key::f22 = KEY_F22, Key::f23 = KEY_F23, Key::f24 = KEY_F24,
Key::kp_0 = KEY_KP0, Key::kp_1 = KEY_KP1, Key::kp_2 = KEY_KP2, Key::kp_3 = KEY_KP3,
Key::kp_4 = KEY_KP4, Key::kp_5 = KEY_KP5, Key::kp_6 = KEY_KP6, Key::kp_7 = KEY_KP7,
Key::kp_8 = KEY_KP8, Key::kp_9 = KEY_KP9, Key::kp_decimal = KEY_KPDOT, Key::kp_divide = KEY_KPSLASH,
Key::kp_multiply = KEY_KPASTERISK, Key::kp_subtract = KEY_KPMINUS, Key::kp_add = KEY_KPPLUS, Key::kp_enter = KEY_KPENTER,
Key::kp_equal = KEY_KPEQUAL, Key::left_shift = KEY_LEFTSHIFT, Key::left_control = KEY_LEFTCTRL, Key::left_alt = KEY_LEFTALT,
Key::left_super = KEY_LEFTMETA, Key::right_shift = KEY_RIGHTSHIFT, Key::right_control = KEY_RIGHTCTRL, Key::right_alt = KEY_RIGHTALT,
Key::right_super = KEY_RIGHTMETA, Key::menu = KEY_MENU, Key::last = KEY_LAST, Key::unknown = GLFW_KEY_UNKNOWN,
Key::space = GLFW_KEY_SPACE, Key::apostrophe = GLFW_KEY_APOSTROPHE, Key::comma = GLFW_KEY_COMMA, Key::minus = GLFW_KEY_MINUS,
Key::period = GLFW_KEY_PERIOD, Key::slash = GLFW_KEY_SLASH, Key::n0 = GLFW_KEY_0, Key::n1 = GLFW_KEY_1,
Key::n2 = GLFW_KEY_2, Key::n3 = GLFW_KEY_3, Key::n4 = GLFW_KEY_4, Key::n5 = GLFW_KEY_5,
Key::n6 = GLFW_KEY_6, Key::n7 = GLFW_KEY_7, Key::n8 = GLFW_KEY_8, Key::n9 = GLFW_KEY_9,
Key::semicolon = GLFW_KEY_SEMICOLON, Key::equal = GLFW_KEY_EQUAL, Key::a = GLFW_KEY_A, Key::b = GLFW_KEY_B,
Key::c = GLFW_KEY_C, Key::d = GLFW_KEY_D, Key::e = GLFW_KEY_E, Key::f = GLFW_KEY_F,
Key::g = GLFW_KEY_G, Key::h = GLFW_KEY_H, Key::i = GLFW_KEY_I, Key::j = GLFW_KEY_J,
Key::k = GLFW_KEY_K, Key::l = GLFW_KEY_L, Key::m = GLFW_KEY_M, Key::n = GLFW_KEY_N,
Key::o = GLFW_KEY_O, Key::p = GLFW_KEY_P, Key::q = GLFW_KEY_Q, Key::r = GLFW_KEY_R,
Key::s = GLFW_KEY_S, Key::t = GLFW_KEY_T, Key::u = GLFW_KEY_U, Key::v = GLFW_KEY_V,
Key::w = GLFW_KEY_W, Key::x = GLFW_KEY_X, Key::y = GLFW_KEY_Y, Key::z = GLFW_KEY_Z,
Key::left_bracket = GLFW_KEY_LEFT_BRACKET, Key::backslash = GLFW_KEY_BACKSLASH, Key::right_bracket = GLFW_KEY_RIGHT_BRACKET, Key::grave_accent = GLFW_KEY_GRAVE_ACCENT,
Key::world_1 = GLFW_KEY_WORLD_1, Key::world_2 = GLFW_KEY_WORLD_2, Key::escape = GLFW_KEY_ESCAPE, Key::enter = GLFW_KEY_ENTER,
Key::tab = GLFW_KEY_TAB, Key::backspace = GLFW_KEY_BACKSPACE, Key::insert = GLFW_KEY_INSERT, Key::del = GLFW_KEY_DELETE,
Key::right = GLFW_KEY_RIGHT, Key::left = GLFW_KEY_LEFT, Key::down = GLFW_KEY_DOWN, Key::up = GLFW_KEY_UP,
Key::page_up = GLFW_KEY_PAGE_UP, Key::page_down = GLFW_KEY_PAGE_DOWN, Key::home = GLFW_KEY_HOME, Key::end = GLFW_KEY_END,
Key::caps_lock = GLFW_KEY_CAPS_LOCK, Key::scroll_lock = GLFW_KEY_SCROLL_LOCK, Key::num_lock = GLFW_KEY_NUM_LOCK, Key::print_screen = GLFW_KEY_PRINT_SCREEN,
Key::pause = GLFW_KEY_PAUSE, Key::f1 = GLFW_KEY_F1, Key::f2 = GLFW_KEY_F2, Key::f3 = GLFW_KEY_F3,
Key::f4 = GLFW_KEY_F4, Key::f5 = GLFW_KEY_F5, Key::f6 = GLFW_KEY_F6, Key::f7 = GLFW_KEY_F7,
Key::f8 = GLFW_KEY_F8, Key::f9 = GLFW_KEY_F9, Key::f10 = GLFW_KEY_F10, Key::f11 = GLFW_KEY_F11,
Key::f12 = GLFW_KEY_F12, Key::f13 = GLFW_KEY_F13, Key::f14 = GLFW_KEY_F14, Key::f15 = GLFW_KEY_F15,
Key::f16 = GLFW_KEY_F16, Key::f17 = GLFW_KEY_F17, Key::f18 = GLFW_KEY_F18, Key::f19 = GLFW_KEY_F19,
Key::f20 = GLFW_KEY_F20, Key::f21 = GLFW_KEY_F21, Key::f22 = GLFW_KEY_F22, Key::f23 = GLFW_KEY_F23,
Key::f24 = GLFW_KEY_F24, Key::f25 = GLFW_KEY_F25, Key::kp_0 = GLFW_KEY_KP_0, Key::kp_1 = GLFW_KEY_KP_1,
Key::kp_2 = GLFW_KEY_KP_2, Key::kp_3 = GLFW_KEY_KP_3, Key::kp_4 = GLFW_KEY_KP_4, Key::kp_5 = GLFW_KEY_KP_5,
Key::kp_6 = GLFW_KEY_KP_6, Key::kp_7 = GLFW_KEY_KP_7, Key::kp_8 = GLFW_KEY_KP_8, Key::kp_9 = GLFW_KEY_KP_9,
Key::kp_decimal = GLFW_KEY_KP_DECIMAL, Key::kp_divide = GLFW_KEY_KP_DIVIDE, Key::kp_multiply = GLFW_KEY_KP_MULTIPLY, Key::kp_subtract = GLFW_KEY_KP_SUBTRACT,
Key::kp_add = GLFW_KEY_KP_ADD, Key::kp_enter = GLFW_KEY_KP_ENTER, Key::kp_equal = GLFW_KEY_KP_EQUAL, Key::left_shift = GLFW_KEY_LEFT_SHIFT,
Key::left_control = GLFW_KEY_LEFT_CONTROL, Key::left_alt = GLFW_KEY_LEFT_ALT, Key::left_super = GLFW_KEY_LEFT_SUPER, Key::right_shift = GLFW_KEY_RIGHT_SHIFT,
Key::right_control = GLFW_KEY_RIGHT_CONTROL, Key::right_alt = GLFW_KEY_RIGHT_ALT, Key::right_super = GLFW_KEY_RIGHT_SUPER, Key::menu = GLFW_KEY_MENU,
Key::last = GLFW_KEY_LAST
}
GLFW keys.
enum Modifier {
Modifier::none = 0, Modifier::shift = 0b0001, Modifier::ctrl = 0b0010, Modifier::alt = 0b0100,
Modifier::super = 0b1000, Modifier::none = 0, Modifier::shift = GLFW_MOD_SHIFT, Modifier::ctrl = GLFW_MOD_CONTROL,
Modifier::alt = GLFW_MOD_ALT, Modifier::super = GLFW_MOD_SUPER
}
GLFW modifiers.
enum Action {
Action::press, Action::release, Action::repeat, Action::press = GLFW_PRESS,
Action::release = GLFW_RELEASE, Action::repeat = GLFW_REPEAT
}
Functions
void handle_keyevent (Action, Modifiers, Key)
Bind keys by implementing this function.
std::vector< input_event > read_events (int device)
void read_mouse ()
void read_encoders ()
void read_keyboard ()
Enumeration Type Documentation
Action [1/2]
enum otto::board::ui::Action strong
Enumerator
press
release
repeat
press
release
repeat
Definition at line 194 of file keys.hpp.
 { press, release, repeat };
Action [2/2]
enum otto::board::ui::Action strong
Enumerator
press
release
repeat
press
release
repeat
Definition at line 202 of file keys.hpp.
                      {
     press = GLFW_PRESS, release = GLFW_RELEASE, repeat = GLFW_REPEAT
   };
Key [1/2]
enum otto::board::ui::Key strong
Linux keys.
Enumerator
unknown
space
apostrophe
comma
minus
period
slash
n0
n1
n2
n3
n4
n5
n6
n7
n8
n9
semicolon
equal
a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z
left_bracket
backslash
right_bracket
grave_accent
escape
enter
tab
backspace
insert
del
right
left
down
up
page_up
page_down
home
end
caps_lock
scroll_lock
num_lock
print_screen
pause
f1
f2
f3
f4
f5
f6
f7
f8
f9
f10
f11
f12
f13
f14
f15
f16
f17
f18
f19
f20
f21
f22
f23
f24
kp_0
kp_1
kp_2
kp_3
kp_4
kp_5
kp_6
kp_7
kp_8
kp_9
kp_decimal
kp_divide
kp_multiply
kp_subtract
kp_add
kp_enter
kp_equal
left_shift
left_control
left_alt
left_super
right_shift
right_control
right_alt
right_super
menu
last
unknown
space
apostrophe
comma
minus
period
slash
n0
n1
n2
n3
n4
n5
n6
n7
n8
n9
semicolon
equal
a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z
left_bracket
backslash
right_bracket
grave_accent
world_1
world_2
escape
enter
tab
backspace
insert
del
right
left
down
up
page_up
page_down
home
end
caps_lock
scroll_lock
num_lock
print_screen
pause
f1
f2
f3
f4
f5
f6
f7
f8
f9
f10
f11
f12
f13
f14
f15
f16
f17
f18
f19
f20
f21
f22
f23
f24
f25
kp_0
kp_1
kp_2
kp_3
kp_4
kp_5
kp_6
kp_7
kp_8
kp_9
kp_decimal
kp_divide
kp_multiply
kp_subtract
kp_add
kp_enter
kp_equal
left_shift
left_control
left_alt
left_super
right_shift
right_control
right_alt
right_super
menu
last
Definition at line 10 of file keys.hpp.
                   {
     unknown = KEY_UNKNOWN,
     /* Printable keys */
     space = KEY_SPACE,
     apostrophe = KEY_APOSTROPHE,
     comma = KEY_COMMA,
     minus = KEY_MINUS,
     period = KEY_DOT,
     slash = KEY_SLASH,
     n0 = KEY_0,
     n1 = KEY_1,
     n2 = KEY_2,
     n3 = KEY_3,
     n4 = KEY_4,
     n5 = KEY_5,
     n6 = KEY_6,
     n7 = KEY_7,
     n8 = KEY_8,
     n9 = KEY_9,
     semicolon = KEY_SEMICOLON,
     equal = KEY_EQUAL,
     a = KEY_A,
     b = KEY_B,
     c = KEY_C,
     d = KEY_D,
     e = KEY_E,
     f = KEY_F,
     g = KEY_G,
     h = KEY_H,
     i = KEY_I,
     j = KEY_J,
     k = KEY_K,
     l = KEY_L,
     m = KEY_M,
     n = KEY_N,
     o = KEY_O,
     p = KEY_P,
     q = KEY_Q,
     r = KEY_R,
     s = KEY_S,
     t = KEY_T,
     u = KEY_U,
     v = KEY_V,
     w = KEY_W,
     x = KEY_X,
     y = KEY_Y,
     z = KEY_Z,
     left_bracket = KEY_LEFTBRACE,
     backslash = KEY_BACKSLASH,
     right_bracket = KEY_RIGHTBRACE,
     grave_accent = KEY_GRAVE,
     /* Function keys */
     escape = KEY_ESC,
     enter = KEY_ENTER,
     tab = KEY_TAB,
     backspace = KEY_BACKSPACE,
     insert = KEY_INSERT,
     del = KEY_DELETE,
     right = KEY_RIGHT,
     left = KEY_LEFT,
     down = KEY_DOWN,
     up = KEY_UP,
     page_up = KEY_PAGEUP,
     page_down = KEY_PAGEDOWN,
     home = KEY_HOME,
     end = KEY_END,
     caps_lock = KEY_CAPSLOCK,
     scroll_lock = KEY_SCROLLLOCK,
     num_lock = KEY_NUMLOCK,
     print_screen = KEY_PRINT,
     pause = KEY_PAUSE,
     f1 = KEY_F1,
     f2 = KEY_F2,
     f3 = KEY_F3,
     f4 = KEY_F4,
     f5 = KEY_F5,
     f6 = KEY_F6,
     f7 = KEY_F7,
     f8 = KEY_F8,
     f9 = KEY_F9,
     f10 = KEY_F10,
     f11 = KEY_F11,
     f12 = KEY_F12,
     f13 = KEY_F13,
     f14 = KEY_F14,
     f15 = KEY_F15,
     f16 = KEY_F16,
     f17 = KEY_F17,
     f18 = KEY_F18,
     f19 = KEY_F19,
     f20 = KEY_F20,
     f21 = KEY_F21,
     f22 = KEY_F22,
     f23 = KEY_F23,
     f24 = KEY_F24,
     kp_0 = KEY_KP0,
     kp_1 = KEY_KP1,
     kp_2 = KEY_KP2,
     kp_3 = KEY_KP3,
     kp_4 = KEY_KP4,
     kp_5 = KEY_KP5,
     kp_6 = KEY_KP6,
     kp_7 = KEY_KP7,
     kp_8 = KEY_KP8,
     kp_9 = KEY_KP9,
     kp_decimal = KEY_KPDOT,
     kp_divide = KEY_KPSLASH,
     kp_multiply = KEY_KPASTERISK,
     kp_subtract = KEY_KPMINUS,
     kp_add = KEY_KPPLUS,
     kp_enter = KEY_KPENTER,
     kp_equal = KEY_KPEQUAL,
     left_shift = KEY_LEFTSHIFT,
     left_control = KEY_LEFTCTRL,
     left_alt = KEY_LEFTALT,
     left_super = KEY_LEFTMETA,
     right_shift = KEY_RIGHTSHIFT,
     right_control = KEY_RIGHTCTRL,
     right_alt = KEY_RIGHTALT,
     right_super = KEY_RIGHTMETA,
     menu = KEY_MENU,
     last = KEY_LAST,
   };
Key [2/2]
enum otto::board::ui::Key strong
GLFW keys.
Enumerator
unknown
space
apostrophe
comma
minus
period
slash
n0
n1
n2
n3
n4
n5
n6
n7
n8
n9
semicolon
equal
a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z
left_bracket
backslash
right_bracket
grave_accent
escape
enter
tab
backspace
insert
del
right
left
down
up
page_up
page_down
home
end
caps_lock
scroll_lock
num_lock
print_screen
pause
f1
f2
f3
f4
f5
f6
f7
f8
f9
f10
f11
f12
f13
f14
f15
f16
f17
f18
f19
f20
f21
f22
f23
f24
kp_0
kp_1
kp_2
kp_3
kp_4
kp_5
kp_6
kp_7
kp_8
kp_9
kp_decimal
kp_divide
kp_multiply
kp_subtract
kp_add
kp_enter
kp_equal
left_shift
left_control
left_alt
left_super
right_shift
right_control
right_alt
right_super
menu
last
unknown
space
apostrophe
comma
minus
period
slash
n0
n1
n2
n3
n4
n5
n6
n7
n8
n9
semicolon
equal
a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z
left_bracket
backslash
right_bracket
grave_accent
world_1
world_2
escape
enter
tab
backspace
insert
del
right
left
down
up
page_up
page_down
home
end
caps_lock
scroll_lock
num_lock
print_screen
pause
f1
f2
f3
f4
f5
f6
f7
f8
f9
f10
f11
f12
f13
f14
f15
f16
f17
f18
f19
f20
f21
f22
f23
f24
f25
kp_0
kp_1
kp_2
kp_3
kp_4
kp_5
kp_6
kp_7
kp_8
kp_9
kp_decimal
kp_divide
kp_multiply
kp_subtract
kp_add
kp_enter
kp_equal
left_shift
left_control
left_alt
left_super
right_shift
right_control
right_alt
right_super
menu
last
Definition at line 12 of file keys.hpp.
                   {
     unknown = GLFW_KEY_UNKNOWN,
     /* Printable keys */
     space = GLFW_KEY_SPACE,
     apostrophe = GLFW_KEY_APOSTROPHE,
     comma = GLFW_KEY_COMMA,
     minus = GLFW_KEY_MINUS,
     period = GLFW_KEY_PERIOD,
     slash = GLFW_KEY_SLASH,
     n0 = GLFW_KEY_0,
     n1 = GLFW_KEY_1,
     n2 = GLFW_KEY_2,
     n3 = GLFW_KEY_3,
     n4 = GLFW_KEY_4,
     n5 = GLFW_KEY_5,
     n6 = GLFW_KEY_6,
     n7 = GLFW_KEY_7,
     n8 = GLFW_KEY_8,
     n9 = GLFW_KEY_9,
     semicolon = GLFW_KEY_SEMICOLON,
     equal = GLFW_KEY_EQUAL,
     a = GLFW_KEY_A,
     b = GLFW_KEY_B,
     c = GLFW_KEY_C,
     d = GLFW_KEY_D,
     e = GLFW_KEY_E,
     f = GLFW_KEY_F,
     g = GLFW_KEY_G,
     h = GLFW_KEY_H,
     i = GLFW_KEY_I,
     j = GLFW_KEY_J,
     k = GLFW_KEY_K,
     l = GLFW_KEY_L,
     m = GLFW_KEY_M,
     n = GLFW_KEY_N,
     o = GLFW_KEY_O,
     p = GLFW_KEY_P,
     q = GLFW_KEY_Q,
     r = GLFW_KEY_R,
     s = GLFW_KEY_S,
     t = GLFW_KEY_T,
     u = GLFW_KEY_U,
     v = GLFW_KEY_V,
     w = GLFW_KEY_W,
     x = GLFW_KEY_X,
     y = GLFW_KEY_Y,
     z = GLFW_KEY_Z,
     left_bracket = GLFW_KEY_LEFT_BRACKET,
     backslash = GLFW_KEY_BACKSLASH,
     right_bracket = GLFW_KEY_RIGHT_BRACKET,
     grave_accent = GLFW_KEY_GRAVE_ACCENT,
     world_1 = GLFW_KEY_WORLD_1,
     world_2 = GLFW_KEY_WORLD_2,
     /* Function keys */
     escape = GLFW_KEY_ESCAPE,
     enter = GLFW_KEY_ENTER,
     tab = GLFW_KEY_TAB,
     backspace = GLFW_KEY_BACKSPACE,
     insert = GLFW_KEY_INSERT,
     del = GLFW_KEY_DELETE,
     right = GLFW_KEY_RIGHT,
     left = GLFW_KEY_LEFT,
     down = GLFW_KEY_DOWN,
     up = GLFW_KEY_UP,
     page_up = GLFW_KEY_PAGE_UP,
     page_down = GLFW_KEY_PAGE_DOWN,
     home = GLFW_KEY_HOME,
     end = GLFW_KEY_END,
     caps_lock = GLFW_KEY_CAPS_LOCK,
     scroll_lock = GLFW_KEY_SCROLL_LOCK,
     num_lock = GLFW_KEY_NUM_LOCK,
     print_screen = GLFW_KEY_PRINT_SCREEN,
     pause = GLFW_KEY_PAUSE,
     f1 = GLFW_KEY_F1,
     f2 = GLFW_KEY_F2,
     f3 = GLFW_KEY_F3,
     f4 = GLFW_KEY_F4,
     f5 = GLFW_KEY_F5,
     f6 = GLFW_KEY_F6,
     f7 = GLFW_KEY_F7,
     f8 = GLFW_KEY_F8,
     f9 = GLFW_KEY_F9,
     f10 = GLFW_KEY_F10,
     f11 = GLFW_KEY_F11,
     f12 = GLFW_KEY_F12,
     f13 = GLFW_KEY_F13,
     f14 = GLFW_KEY_F14,
     f15 = GLFW_KEY_F15,
     f16 = GLFW_KEY_F16,
     f17 = GLFW_KEY_F17,
     f18 = GLFW_KEY_F18,
     f19 = GLFW_KEY_F19,
     f20 = GLFW_KEY_F20,
     f21 = GLFW_KEY_F21,
     f22 = GLFW_KEY_F22,
     f23 = GLFW_KEY_F23,
     f24 = GLFW_KEY_F24,
     f25 = GLFW_KEY_F25,
     kp_0 = GLFW_KEY_KP_0,
     kp_1 = GLFW_KEY_KP_1,
     kp_2 = GLFW_KEY_KP_2,
     kp_3 = GLFW_KEY_KP_3,
     kp_4 = GLFW_KEY_KP_4,
     kp_5 = GLFW_KEY_KP_5,
     kp_6 = GLFW_KEY_KP_6,
     kp_7 = GLFW_KEY_KP_7,
     kp_8 = GLFW_KEY_KP_8,
     kp_9 = GLFW_KEY_KP_9,
     kp_decimal = GLFW_KEY_KP_DECIMAL,
     kp_divide = GLFW_KEY_KP_DIVIDE,
     kp_multiply = GLFW_KEY_KP_MULTIPLY,
     kp_subtract = GLFW_KEY_KP_SUBTRACT,
     kp_add = GLFW_KEY_KP_ADD,
     kp_enter = GLFW_KEY_KP_ENTER,
     kp_equal = GLFW_KEY_KP_EQUAL,
     left_shift = GLFW_KEY_LEFT_SHIFT,
     left_control = GLFW_KEY_LEFT_CONTROL,
     left_alt = GLFW_KEY_LEFT_ALT,
     left_super = GLFW_KEY_LEFT_SUPER,
     right_shift = GLFW_KEY_RIGHT_SHIFT,
     right_control = GLFW_KEY_RIGHT_CONTROL,
     right_alt = GLFW_KEY_RIGHT_ALT,
     right_super = GLFW_KEY_RIGHT_SUPER,
     menu = GLFW_KEY_MENU,
     last = GLFW_KEY_LAST,
   };
Modifier [1/2]
enum otto::board::ui::Modifier strong
Modifiers.
Enumerator
none
shift
ctrl
alt
super
none
shift
ctrl
alt
super
Definition at line 138 of file keys.hpp.
{
     none = 0,
     shift = 0b0001,
     ctrl = 0b0010,
     alt = 0b0100,
     super = 0b1000,
   };
Modifier [2/2]
enum otto::board::ui::Modifier strong
GLFW modifiers.
Enumerator
none
shift
ctrl
alt
super
none
shift
ctrl
alt
super
Definition at line 143 of file keys.hpp.
{
     none = 0,
     shift = GLFW_MOD_SHIFT,
     ctrl = GLFW_MOD_CONTROL,
     alt = GLFW_MOD_ALT,
     super = GLFW_MOD_SUPER,
   };
Function Documentation
handle_keyevent()
void otto::board::ui::handle_keyevent (Action action, Modifiers mods, Key key)
Bind keys by implementing this function.
Definition at line 10 of file keys.cpp.
References a, alt, otto::core::ui::Blue, ctrl, d, e, f, otto::core::ui::Green, i, k, otto::service::ui::impl::keypress(), otto::service::ui::impl::keyrelease(), left_shift, m, n, n0, n1, n2, n3, n4, n5, n6, n7, n9, o, p, press, q, r, otto::core::ui::Red, release, repeat, right_shift, otto::service::ui::impl::rotary(), s, otto::service::audio::send_midi_event(), shift, t, u, w, otto::core::ui::White, and y.
Referenced by read_keyboard().
   {
     auto send_midi = [action](int note) {
       if (action == Action::press) {
         auto evt = core::midi::NoteOnEvent{note};
         service::audio::send_midi_event(evt);
         LOGI("Press key {}", evt.key);
       } else if (action == Action::release) {
         service::audio::send_midi_event(core::midi::NoteOffEvent{note});
         LOGI("Release key {}", note);
       }
     };
     using OKey = core::ui::Key;
     auto send_key = [action](OKey k, bool repeat = false) {
       if (action == Action::press || (action == Action::repeat && repeat))
         service::ui::impl::keypress(k);
       else if (action == Action::release)
         service::ui::impl::keyrelease(k);
     };
     auto send_rotary = [action](core::ui::Rotary rot, int n) {
       if (action == Action::press || (action == Action::repeat))
         service::ui::impl::rotary({rot, n});
     };
     if (mods & Modifier::alt) {
       switch (key) {
       case Key::q: send_midi(17); return;
       case Key::n2: send_midi(18); return;
       case Key::w: send_midi(19); return;
       case Key::n3: send_midi(20); return;
       case Key::e: send_midi(21); return;
       case Key::r: send_midi(22); return;
       case Key::n5: send_midi(23); return;
       case Key::t: send_midi(24); return;
       case Key::n6: send_midi(25); return;
       case Key::y: send_midi(26); return;
       case Key::n7: send_midi(27); return;
       case Key::u: send_midi(28); return;
       case Key::i: send_midi(29); return;
       case Key::n9: send_midi(30); return;
       case Key::o: send_midi(31); return;
       case Key::n0: send_midi(32); return;
       case Key::p: send_midi(33); return;
       default: break;
       }
     }
     bool ctrl = mods & Modifier::ctrl;
     switch (key) {
       // Rotaries
     case Key::q:
       if (ctrl)
         send_key(OKey::blue_click);
       else
         send_rotary(core::ui::Rotary::Blue, 1);
       break;
     case Key::a:
       if (ctrl)
         send_key(OKey::blue_click);
       else
         send_rotary(core::ui::Rotary::Blue, -1);
       break;
     case Key::w:
       if (ctrl)
         send_key(OKey::green_click);
       else
         send_rotary(core::ui::Rotary::Green, 1);
       break;
     case Key::s:
       if (ctrl)
         send_key(OKey::green_click);
       else
         send_rotary(core::ui::Rotary::Green, -1);
       break;
     case Key::e:
       if (ctrl)
         send_key(OKey::white_click);
       else
         send_rotary(core::ui::Rotary::White, 1);
       break;
     case Key::d:
       if (ctrl)
         send_key(OKey::white_click);
       else
         send_rotary(core::ui::Rotary::White, -1);
       break;
     case Key::r:
       if (ctrl)
         send_key(OKey::red_click);
       else
         send_rotary(core::ui::Rotary::Red, 1);
       break;
     case Key::f:
       if (ctrl)
         send_key(OKey::red_click);
       else
         send_rotary(core::ui::Rotary::Red, -1);
       break;
     // Engines
     case Key::n1: send_key(OKey::sequencer); break;
     case Key::n2: send_key(OKey::synth); break;
     case Key::n3: send_key(OKey::envelope); break;
     case Key::n4: send_key(OKey::voices); break;
     case Key::n5: send_key(OKey::fx1); break;
     case Key::p: send_key(OKey::play); break;
     case Key::m: send_key(OKey::master); break;
     case Key::left_shift: [[fallthrough]];
     case Key::right_shift: send_key(OKey::shift); break;
     default: break;
     }
   }
read_encoders()
void otto::board::ui::read_encoders ()
Definition at line 104 of file rpi_input.cpp.
References otto::core::ui::blue_click, otto::core::ui::RotaryEvent::clicks, end, otto::core::ui::green_click, otto::service::ui::impl::keypress(), otto::core::ui::red_click, otto::core::ui::RotaryEvent::rotary, otto::service::ui::impl::rotary(), otto::global::running(), and otto::core::ui::white_click.
Referenced by read_keyboard().
   {
     auto file = fopen("/dev/ttyACM0", "r");
     if (file == nullptr) {
       LOGW("Encoder device not found (expected /dev/ttyACM0). Continuing without it");
       return;
     }
     char* line = nullptr;
     std::size_t len;
     std::size_t read;
     while (global::running()) {
       read = getline(&line, &len, file);
       if (len >= 2) {
         if (line[1] == 'P') {
           switch (line[0]) {
           case 'B': service::ui::impl::keypress(core::ui::Key::blue_click); break;
           case 'G': service::ui::impl::keypress(core::ui::Key::green_click); break;
           case 'Y': service::ui::impl::keypress(core::ui::Key::white_click); break;
           case 'R': service::ui::impl::keypress(core::ui::Key::red_click); break;
           default: break;
           }
           continue;
         }
         RotaryEvent rot;
         switch (line[0]) {
         case 'B': rot.rotary = Rotary::Blue; break;
         case 'G': rot.rotary = Rotary::Green; break;
         case 'Y': rot.rotary = Rotary::White; break;
         case 'R': rot.rotary = Rotary::Red; break;
         default: rot.rotary = Rotary{-1};
         }
         if (rot.rotary == Rotary{-1}) continue;
         char* end = line + len;
         rot.clicks = std::strtol(line + 1, &end, 10);
         service::ui::impl::rotary(rot);
       }
     }
   }
read_events()
std::vector<input_event> otto::board::ui::read_events (int device)
Definition at line 61 of file rpi_input.cpp.
Referenced by read_keyboard(), and read_mouse().
   {
     struct input_event events[event_buffer_size];
     int rd = read(device, events, sizeof(events));
     if (rd <= 0) {
       return std::vector<input_event>();
     }
     int count = rd / sizeof(struct input_event);
     return std::vector<input_event>(events, events + count);
   }
read_keyboard()
void otto::board::ui::read_keyboard ()
Definition at line 145 of file rpi_input.cpp.
References alt, ctrl, handle_keyevent(), otto::global::input_error, left, press, read_encoders(), read_events(), release, repeat, right, otto::global::running(), shift, and super.
   {
     Modifiers left;
     Modifiers right;
     int keyboard = [] {
       int dev = open_device("0-event-kbd", true);
       if (dev < 0) dev = open_device("event-kbd", true);
       return dev;
     }();
     std::thread encoder_thread = std::thread{[] { read_encoders(); }};
     if (keyboard == -1) {
       throw global::exception(global::ErrorCode::input_error, "Could not find a keyboard!");
     }
     while (global::running()) {
       auto events = read_events(keyboard);
       for (const auto& event : events) {
         if (event.type == EV_KEY) {
           auto pressed = event.value != 0;
           switch (event.code) {
           case KEY_LEFTCTRL: left.set(Modifier::ctrl, pressed); break;
           case KEY_RIGHTCTRL: right.set(Modifier::ctrl, pressed); break;
           case KEY_LEFTALT: left.set(Modifier::alt, pressed); break;
           case KEY_RIGHTALT: right.set(Modifier::alt, pressed); break;
           case KEY_LEFTSHIFT: left.set(Modifier::shift, pressed); break;
           case KEY_RIGHTSHIFT: right.set(Modifier::shift, pressed); break;
           case KEY_LEFTMETA: left.set(Modifier::super, pressed); break;
           case KEY_RIGHTMETA: right.set(Modifier::super, pressed); break;
           }
           Action action = [event] {
             switch (event.value) {
             case key_release: return Action::release;
             case key_press: return Action::press;
             case key_repeat: return Action::repeat;
             default: return Action{-1};
             }
           }();
           handle_keyevent(action, left | right, board::ui::Key(event.code));
         }
       }
     }
   }
read_mouse()
void otto::board::ui::read_mouse ()
Definition at line 73 of file rpi_input.cpp.
References otto::global::input_error, and read_events().
   {
     static int mouse = open_device("event-mouse");
     if (mouse == -1) {
       throw global::exception(global::ErrorCode::input_error,
                               "Could not find a mouse or touchscreen!");
     }
     auto events = read_events(mouse);
     for (const auto& event : events) {
       switch (event.type) {
       case EV_KEY:
         switch (event.value) {
         case key_press: LOGI("Mouse button down: {}", event.code); break;
         case key_release: LOGI("Mouse button up: {}", event.code); break;
         }
       case EV_REL:
         switch (event.code) {
         case 0: LOGI("Mouse moved left/right: {}", event.value); break;
         case 1: LOGI("Mouse moved left/right: {}", event.value); break;
         }
       case EV_ABS: LOGI("Mouse absolute event: {}, {}", event.code, event.value); break;
       }
     }
   }