OTTO: otto::util::Header Struct Reference
otto::util::Header Struct Reference
Public Member Functions
Header ()=default
Header (Chunk &o)
void read_fields (ByteFile &file) override
void write_fields (ByteFile &file) override
Public Member Functions inherited from otto::util::ByteFile::Chunk
Chunk (bytes< 4 > id={0, 0, 0, 0})
Chunk (const Chunk &o)
virtual ~Chunk ()=default
Position beginning ()
Position past_end ()
void write (ByteFile &file)
void read (ByteFile &file)
Public Attributes
bytes< 4 > format
std::vector< std::unique_ptr< Chunk > > chunks
Public Attributes inherited from otto::util::ByteFile::Chunk
bytes< 4 > id
bytes< 4 > size = {0,0,0,0}
Position offset
Detailed Description
Definition at line 9 of file soundfile.cpp.
Constructor & Destructor Documentation
Header() [1/2]
otto::util::Header::Header () default
Header() [2/2]
otto::util::Header::Header (Chunk & o) inline
Definition at line 11 of file soundfile.cpp.
 : Chunk(o) {}
Member Function Documentation
read_fields()
void otto::util::Header::read_fields (ByteFile & file) inline override virtual
Reimplemented from otto::util::ByteFile::Chunk.
Definition at line 16 of file soundfile.cpp.
References otto::util::bytes< len >::as_u(), otto::util::ByteFile::Chunk::Chunk(), chunks, otto::util::ByteFile::for_chunks_in_range(), format, otto::util::ByteFile::Chunk::offset, otto::util::ByteFile::read_bytes(), and otto::util::ByteFile::Chunk::size.
{
       file.read_bytes(format).unwrap_ok();
       file.for_chunks_in_range(offset + 12, offset + 8 + size.as_u(),
         [&](Chunk& c) {
           chunks.emplace_back(new Chunk(c));
         });
     }
write_fields()
void otto::util::Header::write_fields (ByteFile & file) inline override virtual
Reimplemented from otto::util::ByteFile::Chunk.
Definition at line 24 of file soundfile.cpp.
References chunks, format, and otto::util::ByteFile::write_bytes().
{
       file.write_bytes(format);
       for (auto&& c : chunks) {
         c->write(file);
       }
     }
Member Data Documentation
chunks
std::vector<std::unique_ptr<Chunk> > otto::util::Header::chunks
Definition at line 14 of file soundfile.cpp.
Referenced by read_fields(), otto::util::SoundFile::read_file(), write_fields(), and otto::util::SoundFile::write_file().
format
bytes<4> otto::util::Header::format
Definition at line 13 of file soundfile.cpp.
Referenced by read_fields(), otto::util::SoundFile::read_file(), write_fields(), and otto::util::SoundFile::write_file().
The documentation for this struct was generated from the following file:
/home/topisani/dev/OTTO/src/util/soundfile.cpp