OTTO: otto::core::audio::WaveformView Struct Reference
otto::core::audio::WaveformView Struct Reference
Detailed Description
Definition at line 39 of file waveform.hpp.
#include <waveform.hpp>
Public Types
using iterator = std::vector< float >::const_iterator
Public Member Functions
auto begin () const noexcept
auto end () const noexcept
auto operator[] (int idx) const
auto size () const noexcept
std::pair< float, float > point_for_time (int idx) const
iterator iter_for_time (int idx) const
Member Typedef Documentation
iterator
using otto::core::audio::WaveformView::iterator = std::vector<float>::const_iterator
Definition at line 40 of file waveform.hpp.
Member Function Documentation
begin()
auto otto::core::audio::WaveformView::begin () const noexcept
Definition at line 42 of file waveform.hpp.
References std::vector< T >::begin().
end()
auto otto::core::audio::WaveformView::end () const noexcept
Definition at line 47 of file waveform.hpp.
References std::vector< T >::end().
operator[]()
auto otto::core::audio::WaveformView::operator[] (int idx) const
Definition at line 52 of file waveform.hpp.
References OTTO_ASSERT, and std::vector< T >::size().
size()
auto otto::core::audio::WaveformView::size () const noexcept
Definition at line 57 of file waveform.hpp.
References std::vector< T >::size().
point_for_time()
std::pair<float, float> otto::core::audio::WaveformView::point_for_time (int idx) const
iter_for_time()
iterator otto::core::audio::WaveformView::iter_for_time (int idx) const
The documentation for this struct was generated from the following file:
/home/travis/build/topisani/OTTO/src/core/audio/waveform.hpp