OTTO: otto::util::string_ref Struct Reference
otto::util::string_ref Struct Reference
Detailed Description
This class is a non owning reference to a null terminated string.
Definition at line 11 of file string_ref.hpp.
#include <string_ref.hpp>
Public Types
using const_iterator = const char *
types
using const_reverse_iterator = std::reverse_iterator< const_iterator >
Public Member Functions
constexpr string_ref ()
construct/copy.
constexpr string_ref (const string_ref &other)
constexpr string_ref & operator= (const string_ref &rhs)
constexpr string_ref (const char *s)
string_ref (const std::string &s)
constexpr operator std::string_view () const noexcept
constexpr const_iterator begin () const
iterators
constexpr const_iterator end () const
constexpr const_iterator cbegin () const
constexpr const_iterator cend () const
constexpr const_reverse_iterator rbegin () const
constexpr const_reverse_iterator rend () const
constexpr const_reverse_iterator crbegin () const
constexpr const_reverse_iterator crend () const
constexpr size_t size () const
capacity
constexpr size_t length () const
constexpr size_t max_size () const
constexpr bool empty () const
constexpr const char * data () const
element access
constexpr int compare (string_ref x) const
string operations
constexpr bool starts_with (string_ref x) const
constexpr bool ends_with (string_ref x) const
constexpr size_t find (string_ref s) const
constexpr size_t find (char c) const
constexpr std::string_view substr (size_t pos, size_t n=npos) const
constexpr const char * c_str () const noexcept
Static Public Attributes
const static size_t npos
constants
Member Typedef Documentation
const_iterator
using otto::util::string_ref::const_iterator = const char*
types
Definition at line 13 of file string_ref.hpp.
const_reverse_iterator
using otto::util::string_ref::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 14 of file string_ref.hpp.
Constructor & Destructor Documentation
string_ref() [1/4]
constexpr otto::util::string_ref::string_ref () constexpr
construct/copy.
Definition at line 20 of file string_ref.hpp.
string_ref() [2/4]
constexpr otto::util::string_ref::string_ref (const string_ref & other) constexpr
Definition at line 21 of file string_ref.hpp.
string_ref() [3/4]
constexpr otto::util::string_ref::string_ref (const char * s) constexpr
Definition at line 28 of file string_ref.hpp.
string_ref() [4/4]
otto::util::string_ref::string_ref (const std::string & s)
Definition at line 32 of file string_ref.hpp.
Member Function Documentation
operator=()
constexpr string_ref& otto::util::string_ref::operator= (const string_ref & rhs) constexpr
Definition at line 22 of file string_ref.hpp.
operator std::string_view()
constexpr otto::util::string_ref::operator std::string_view () const constexpr noexcept
Definition at line 34 of file string_ref.hpp.
begin()
constexpr const_iterator otto::util::string_ref::begin () const constexpr
iterators
Definition at line 39 of file string_ref.hpp.
Referenced by crend(), and rend().
end()
constexpr const_iterator otto::util::string_ref::end () const constexpr
Definition at line 43 of file string_ref.hpp.
Referenced by crbegin(), and rbegin().
cbegin()
constexpr const_iterator otto::util::string_ref::cbegin () const constexpr
Definition at line 47 of file string_ref.hpp.
cend()
constexpr const_iterator otto::util::string_ref::cend () const constexpr
Definition at line 51 of file string_ref.hpp.
rbegin()
constexpr const_reverse_iterator otto::util::string_ref::rbegin () const constexpr
Definition at line 55 of file string_ref.hpp.
References end().
rend()
constexpr const_reverse_iterator otto::util::string_ref::rend () const constexpr
Definition at line 59 of file string_ref.hpp.
References begin().
crbegin()
constexpr const_reverse_iterator otto::util::string_ref::crbegin () const constexpr
Definition at line 63 of file string_ref.hpp.
References end().
crend()
constexpr const_reverse_iterator otto::util::string_ref::crend () const constexpr
Definition at line 67 of file string_ref.hpp.
References begin().
size()
constexpr size_t otto::util::string_ref::size () const constexpr
capacity
Definition at line 73 of file string_ref.hpp.
length()
constexpr size_t otto::util::string_ref::length () const constexpr
Definition at line 77 of file string_ref.hpp.
max_size()
constexpr size_t otto::util::string_ref::max_size () const constexpr
Definition at line 81 of file string_ref.hpp.
empty()
constexpr bool otto::util::string_ref::empty () const constexpr
Definition at line 85 of file string_ref.hpp.
data()
constexpr const char* otto::util::string_ref::data () const constexpr
element access
Definition at line 91 of file string_ref.hpp.
compare()
constexpr int otto::util::string_ref::compare (string_ref x) const constexpr
string operations
Definition at line 97 of file string_ref.hpp.
starts_with()
constexpr bool otto::util::string_ref::starts_with (string_ref x) const constexpr
Definition at line 102 of file string_ref.hpp.
References substr().
ends_with()
constexpr bool otto::util::string_ref::ends_with (string_ref x) const constexpr
Definition at line 107 of file string_ref.hpp.
References substr().
find() [1/2]
constexpr size_t otto::util::string_ref::find (string_ref s) const constexpr
Definition at line 112 of file string_ref.hpp.
find() [2/2]
constexpr size_t otto::util::string_ref::find (char c) const constexpr
Definition at line 117 of file string_ref.hpp.
substr()
constexpr std::string_view otto::util::string_ref::substr (size_t pos, size_t n = npos) const constexpr
Definition at line 122 of file string_ref.hpp.
Referenced by ends_with(), and starts_with().
c_str()
constexpr const char* otto::util::string_ref::c_str () const constexpr noexcept
Definition at line 127 of file string_ref.hpp.
Referenced by otto::util::operator<<().
Member Data Documentation
npos
const static size_t otto::util::string_ref::npos static
constants
Definition at line 17 of file string_ref.hpp.
The documentation for this struct was generated from the following file:
/home/travis/build/topisani/OTTO/src/util/string_ref.hpp