OTTO: otto::engines::Euclid::Channel Struct Reference
otto::engines::Euclid::Channel Struct Reference
#include <euclid.hpp>
Public Member Functions
void update_notes ()
Channel (int n)
Public Attributes
Property< int > length
Property< int > hits = {this, "Hits", 0, has_limits::init(0, max_length), steppable::init(1)}
Property< int > rotation
Property< std::array< int, 6 > > notes = {this, "Notes", std::array<int, 6>{{-1, -1, -1, -1, -1, -1}}}
int _beat_counter = 0
std::array< bool, max_length > _hits_enabled
Additional Inherited Members
Public Types inherited from otto::core::props::Properties<>
using Super = meta::_t< detail::properties_for_list< meta::_t< get_tag_list< void, Tags... > >> >
Detailed Description
Definition at line 20 of file euclid.hpp.
Constructor & Destructor Documentation
Channel()
otto::engines::Euclid::Channel::Channel (int n)
Definition at line 31 of file euclid.hpp.
Member Function Documentation
update_notes()
void otto::engines::Euclid::Channel::update_notes ()
Definition at line 135 of file euclid.cpp.
References _hits_enabled, otto::util::fill(), hits, length, rotation, and otto::util::math::round().
Member Data Documentation
length
Property<int> otto::engines::Euclid::Channel::length
Initial value:
= {this, "Length", max_length, has_limits::init(0, max_length),
                                    steppable::init(1)}
Definition at line 21 of file euclid.hpp.
Referenced by update_notes().
hits
Property<int> otto::engines::Euclid::Channel::hits = {this, "Hits", 0, has_limits::init(0, max_length), steppable::init(1)}
Definition at line 23 of file euclid.hpp.
Referenced by update_notes().
rotation
Property<int> otto::engines::Euclid::Channel::rotation
Initial value:
= {this, "Rotation", 0, has_limits::init(0, max_length),
                                steppable::init(1)}
Definition at line 24 of file euclid.hpp.
Referenced by update_notes().
notes
Property<std::array<int, 6> > otto::engines::Euclid::Channel::notes = {this, "Notes", std::array<int, 6>{{-1, -1, -1, -1, -1, -1}}}
Definition at line 27 of file euclid.hpp.
_beat_counter
int otto::engines::Euclid::Channel::_beat_counter = 0
Definition at line 33 of file euclid.hpp.
Referenced by otto::engines::EuclidScreen::draw_channel().
_hits_enabled
std::array<bool, max_length> otto::engines::Euclid::Channel::_hits_enabled
Definition at line 34 of file euclid.hpp.
Referenced by update_notes().
The documentation for this struct was generated from the following files:
/home/topisani/dev/OTTO/src/engines/seq/euclid/euclid.hpp
/home/topisani/dev/OTTO/src/engines/seq/euclid/euclid.cpp