OTTO: otto::core::engine::EngineSelectorScreen Struct Reference
otto::core::engine::EngineSelectorScreen Struct Reference
Detailed Description
Definition at line 11 of file engine_selector_screen.hpp.
#include <engine_selector_screen.hpp>
Public Member Functions
template<EngineType ET>
EngineSelectorScreen (EngineDispatcher< ET > &)
\exclude
void rotary (ui::RotaryEvent) override
This should be used for handling rotary events.
void draw (ui::vg::Canvas &) override
Draw this widget to the context.
void on_show () override
Run by MainUI when switching to this screen.
void on_hide () override
Run by MainUI when switching to another screen.
Public Member Functions inherited from otto::core::ui::Screen
Screen ()
virtual ~Screen ()
virtual bool keypress (Key)
Run by MainUI when a key is pressed.
virtual bool keyrelease (Key)
Run by MainUI when a key is released.
Public Member Functions inherited from otto::core::ui::vg::Drawable
Drawable ()=default
virtual ~Drawable ()=default
Constructor & Destructor Documentation
EngineSelectorScreen()
template<EngineType ET> otto::core::engine::EngineSelectorScreen::EngineSelectorScreen (EngineDispatcher< ET > & ed)
\exclude
Definition at line 38 of file engine_selector_screen.hpp.
References otto::core::engine::EngineDispatcher< ET >::current(), otto::core::engine::EngineDispatcher< ET >::engine_factories(), and otto::core::engine::EngineDispatcher< ET >::select().
Member Function Documentation
rotary()
void otto::core::engine::EngineSelectorScreen::rotary (ui::RotaryEvent) override virtual
This should be used for handling rotary events.
Reimplemented from otto::core::ui::Screen.
draw()
void otto::core::engine::EngineSelectorScreen::draw (ui::vg::Canvas & ctx) override virtual
Draw this widget to the context.
Called from the parent's draw method.
Parameters
ctx the canvas to draw on.
Implements otto::core::ui::vg::Drawable.
on_show()
void otto::core::engine::EngineSelectorScreen::on_show () override virtual
Run by MainUI when switching to this screen.
Reimplemented from otto::core::ui::Screen.
on_hide()
void otto::core::engine::EngineSelectorScreen::on_hide () override virtual
Run by MainUI when switching to another screen.
Reimplemented from otto::core::ui::Screen.
The documentation for this struct was generated from the following file:
/home/travis/build/topisani/OTTO/src/core/engine/engine_selector_screen.hpp