OTTO: otto::nvg::Color Struct Reference
otto::nvg::Color Struct Reference
Detailed Description
Definition at line 13 of file Color.hpp.
#include <Color.hpp>
Public Member Functions
Color ()
Color (const unsigned int color)
Construct a color with an unsigned integer value.
Color (Byte _r, Byte _g, Byte _b, Byte _a=255)
Construct color with it's components value in the range [0,255].
Color (int _r, int _g, int _b, int _a=255)
Construct color with it's components value in the range [0,255].
Color (unsigned _r, unsigned _g, unsigned _b, unsigned _a=255)
Construct color with it's components value in the range [0,255].
Color (float _r, float _g, float _b, float _a=1.0f)
Construct color with it's components value in the range [0,1].
operator unsigned int () const
Convert the color to unsigned int as the color code.
Byte & operator[] (int index)
const Byte operator[] (int index) const
bool operator== (const Color &color)
bool operator< (const Color &color)
Color & operator= (const unsigned int color)
Color & operator+= (const Color &color)
Color & operator-= (const Color &color)
Color & operator*= (const Color &color)
Color operator+ (const Color &color)
Color operator- (const Color &color)
Color operator* (const Color &color)
Color & set (unsigned int color)
Color & set (float _r, float _g, float _b, float _a)
Color & set (Byte _r, Byte _g, Byte _b, Byte _a)
Color & set (unsigned _r, unsigned _g, unsigned _b, unsigned _a)
Color & set (int _r, int _g, int _b, int _a)
unsigned int code () const
float redf () const
float greenf () const
float bluef () const
float alphaf () const
Color mix (Color c, float ratio) const
Color dim (float amount) const
Color brighten (float amount) const
Static Public Member Functions
static Color floats (float r, float g, float b, float a=1)
static Color bytes (uint8_t r, uint8_t g, uint8_t b, uint8_t a=0xFF)
static Color createWidthHSL (float _h, float _s, float _l, float _a=1.0f)
Additional Inherited Members
Public Attributes inherited from otto::nvg::ColorConverter::Rgba
byte a = 0
Public Attributes inherited from otto::nvg::ColorConverter::Rgb
byte r = 0
byte g = 0
byte b = 0
Constructor & Destructor Documentation
Color() [1/6]
otto::nvg::Color::Color ()
Definition at line 14 of file Color.hpp.
References otto::nvg::ColorConverter::Rgba::a, otto::nvg::ColorConverter::Rgb::b, otto::nvg::ColorConverter::Rgb::g, and otto::nvg::ColorConverter::Rgb::r.
Referenced by bytes(), and floats().
Color() [2/6]
otto::nvg::Color::Color (const unsigned int color)
Construct a color with an unsigned integer value.
Parameters
color The color code value
Definition at line 23 of file Color.hpp.
References set().
Color() [3/6]
otto::nvg::Color::Color (Byte _r, Byte _g, Byte _b, Byte _a = 255)
Construct color with it's components value in the range [0,255].
Parameters
_r The red component value
_g The green component value
_b The blue component value
_a The alpha component value
Definition at line 35 of file Color.hpp.
References set().
Color() [4/6]
otto::nvg::Color::Color (int _r, int _g, int _b, int _a = 255)
Construct color with it's components value in the range [0,255].
Parameters
_r The red component value
_g The green component value
_b The blue component value
_a The alpha component value
Definition at line 47 of file Color.hpp.
References set().
Color() [5/6]
otto::nvg::Color::Color (unsigned _r, unsigned _g, unsigned _b, unsigned _a = 255)
Construct color with it's components value in the range [0,255].
Parameters
_r The red component value
_g The green component value
_b The blue component value
_a The alpha component value
Definition at line 59 of file Color.hpp.
References set().
Color() [6/6]
otto::nvg::Color::Color (float _r, float _g, float _b, float _a = 1.0f)
Construct color with it's components value in the range [0,1].
Parameters
_r The red component value
_g The green component value
_b The blue component value
_a The alpha component value
Definition at line 71 of file Color.hpp.
References set().
Member Function Documentation
operator unsigned int()
otto::nvg::Color::operator unsigned int () const
Convert the color to unsigned int as the color code.
Definition at line 77 of file Color.hpp.
References code().
operator[]() [1/2]
Byte& otto::nvg::Color::operator[] (int index)
Definition at line 82 of file Color.hpp.
References otto::nvg::ColorConverter::Rgba::a, otto::nvg::ColorConverter::Rgb::b, otto::nvg::ColorConverter::Rgb::g, OTTO_UNREACHABLE, and otto::nvg::ColorConverter::Rgb::r.
operator[]() [2/2]
const Byte otto::nvg::Color::operator[] (int index) const
Definition at line 92 of file Color.hpp.
References otto::nvg::ColorConverter::Rgba::a, otto::nvg::ColorConverter::Rgb::b, otto::nvg::ColorConverter::Rgb::g, OTTO_UNREACHABLE, and otto::nvg::ColorConverter::Rgb::r.
operator==()
bool otto::nvg::Color::operator== (const Color & color)
Definition at line 103 of file Color.hpp.
References code().
operator<()
bool otto::nvg::Color::operator< (const Color & color)
Definition at line 107 of file Color.hpp.
References code().
operator=()
Color& otto::nvg::Color::operator= (const unsigned int color)
Definition at line 112 of file Color.hpp.
References set().
operator+=()
Color& otto::nvg::Color::operator+= (const Color & color)
Definition at line 117 of file Color.hpp.
References otto::nvg::ColorConverter::Rgba::a, otto::nvg::ColorConverter::Rgb::b, otto::nvg::ColorConverter::Rgb::g, and otto::nvg::ColorConverter::Rgb::r.
operator-=()
Color& otto::nvg::Color::operator-= (const Color & color)
Definition at line 126 of file Color.hpp.
References otto::nvg::ColorConverter::Rgba::a, otto::nvg::ColorConverter::Rgb::b, otto::nvg::ColorConverter::Rgb::g, std::max(), and otto::nvg::ColorConverter::Rgb::r.
operator*=()
Color& otto::nvg::Color::operator*= (const Color & color)
Definition at line 136 of file Color.hpp.
References otto::nvg::ColorConverter::Rgba::a, otto::nvg::ColorConverter::Rgb::b, otto::nvg::ColorConverter::Rgb::g, and otto::nvg::ColorConverter::Rgb::r.
operator+()
Color otto::nvg::Color::operator+ (const Color & color)
Definition at line 144 of file Color.hpp.
operator-()
Color otto::nvg::Color::operator- (const Color & color)
Definition at line 151 of file Color.hpp.
operator*()
Color otto::nvg::Color::operator* (const Color & color)
Definition at line 158 of file Color.hpp.
set() [1/5]
Color& otto::nvg::Color::set (unsigned int color)
Definition at line 165 of file Color.hpp.
References otto::nvg::ColorConverter::Rgba::a, otto::nvg::ColorConverter::Rgb::b, otto::nvg::ColorConverter::Rgb::g, and otto::nvg::ColorConverter::Rgb::r.
Referenced by Color(), and operator=().
set() [2/5]
Color& otto::nvg::Color::set (float _r, float _g, float _b, float _a)
Definition at line 174 of file Color.hpp.
References otto::nvg::ColorConverter::Rgba::a, otto::nvg::ColorConverter::Rgb::b, otto::nvg::ColorConverter::Rgb::g, and otto::nvg::ColorConverter::Rgb::r.
set() [3/5]
Color& otto::nvg::Color::set (Byte _r, Byte _g, Byte _b, Byte _a)
Definition at line 183 of file Color.hpp.
References otto::nvg::ColorConverter::Rgba::a, otto::nvg::ColorConverter::Rgb::b, otto::nvg::ColorConverter::Rgb::g, and otto::nvg::ColorConverter::Rgb::r.
set() [4/5]
Color& otto::nvg::Color::set (unsigned _r, unsigned _g, unsigned _b, unsigned _a)
Definition at line 192 of file Color.hpp.
References otto::nvg::ColorConverter::Rgba::a, otto::nvg::ColorConverter::Rgb::b, otto::nvg::ColorConverter::Rgb::g, and otto::nvg::ColorConverter::Rgb::r.
set() [5/5]
Color& otto::nvg::Color::set (int _r, int _g, int _b, int _a)
Definition at line 201 of file Color.hpp.
References otto::nvg::ColorConverter::Rgba::a, otto::nvg::ColorConverter::Rgb::b, otto::nvg::ColorConverter::Rgb::g, and otto::nvg::ColorConverter::Rgb::r.
floats()
Color otto::nvg::Color::floats (float r, float g, float b, float a = 1) static
Definition at line 251 of file Color.hpp.
References otto::nvg::ColorConverter::Rgba::a, otto::nvg::ColorConverter::Rgb::b, Color(), otto::nvg::ColorConverter::Rgb::g, and otto::nvg::ColorConverter::Rgb::r.
bytes()
Color otto::nvg::Color::bytes (uint8_t r, uint8_t g, uint8_t b, uint8_t a = 0xFF) static
Definition at line 256 of file Color.hpp.
References otto::nvg::ColorConverter::Rgba::a, otto::nvg::ColorConverter::Rgb::b, Color(), otto::nvg::ColorConverter::Rgb::g, and otto::nvg::ColorConverter::Rgb::r.
code()
unsigned int otto::nvg::Color::code () const
Definition at line 213 of file Color.hpp.
References otto::nvg::ColorConverter::Rgba::a, otto::nvg::ColorConverter::Rgb::b, otto::nvg::ColorConverter::Rgb::g, and otto::nvg::ColorConverter::Rgb::r.
Referenced by operator unsigned int(), operator<(), and operator==().
redf()
float otto::nvg::Color::redf () const
Definition at line 223 of file Color.hpp.
References otto::nvg::ColorConverter::Rgb::r.
greenf()
float otto::nvg::Color::greenf () const
Definition at line 227 of file Color.hpp.
References otto::nvg::ColorConverter::Rgb::g.
bluef()
float otto::nvg::Color::bluef () const
Definition at line 231 of file Color.hpp.
References otto::nvg::ColorConverter::Rgb::b.
alphaf()
float otto::nvg::Color::alphaf () const
Definition at line 235 of file Color.hpp.
References otto::nvg::ColorConverter::Rgba::a.
createWidthHSL()
static Color otto::nvg::Color::createWidthHSL (float _h, float _s, float _l, float _a = 1.0f) static
Definition at line 240 of file Color.hpp.
References otto::nvg::ColorConverter::hslToRgb().
mix()
Color otto::nvg::Color::mix (Color c, float ratio) const
Definition at line 261 of file Color.hpp.
References otto::nvg::ColorConverter::Rgba::a, otto::nvg::ColorConverter::Rgb::b, otto::nvg::ColorConverter::Rgb::g, and otto::nvg::ColorConverter::Rgb::r.
dim()
Color otto::nvg::Color::dim (float amount) const
Definition at line 271 of file Color.hpp.
References otto::nvg::ColorConverter::Rgba::a, otto::nvg::ColorConverter::Rgb::b, otto::nvg::ColorConverter::clamp(), otto::nvg::ColorConverter::Rgb::g, and otto::nvg::ColorConverter::Rgb::r.
brighten()
Color otto::nvg::Color::brighten (float amount) const
Definition at line 282 of file Color.hpp.
References otto::nvg::ColorConverter::Rgba::a, otto::nvg::ColorConverter::Rgb::b, otto::nvg::ColorConverter::Rgb::g, and otto::nvg::ColorConverter::Rgb::r.
The documentation for this struct was generated from the following file:
/home/travis/build/topisani/OTTO/src/core/ui/nvg/Color.hpp