OTTO: otto::util::cache_base< T > Struct Template Reference
otto::util::cache_base< T > Struct Template Reference abstract
#include <cache.hpp>
Public Member Functions
void invalidate ()
Invalidate the cache.
bool valid () const
Check if the cache is valid.
const T & value ()
Access the cached value.
const T * operator-> ()
const T & operator* ()
Protected Member Functions
virtual void refresh ()=0
Protected Attributes
bool _valid = false
Detailed Description
template<typename T>
struct otto::util::cache_base< T >
A CRTP style cache base class.
The cached value is imutable, and lazilly refreshed. This wrapper is not thread safe at invalidation!
T shall be DefaultConstructible
Definition at line 16 of file cache.hpp.
Member Function Documentation
invalidate()
template<typename T> void otto::util::cache_base< T >::invalidate () inline
Invalidate the cache.
Definition at line 19 of file cache.hpp.
     {
       _valid = false;
     }
operator*()
template<typename T> const T& otto::util::cache_base< T >::operator* () inline
Access the cached value
Alias to value()
Definition at line 50 of file cache.hpp.
{
       return value();
     }
operator->()
template<typename T> const T* otto::util::cache_base< T >::operator-> () inline
Access the cached value
Alias to value()
Definition at line 43 of file cache.hpp.
{
       return &value();
     }
refresh()
template<typename T> virtual void otto::util::cache_base< T >::refresh () protected pure virtual
Refresh the cache
It should be implemented in the derived class, and it is called by value() when the cache is invalid
Referenced by otto::util::cache_base< PointCache >::value().
valid()
template<typename T> bool otto::util::cache_base< T >::valid () const inline
Check if the cache is valid.
Definition at line 25 of file cache.hpp.
     {
       return _valid;
     }
value()
template<typename T> const T& otto::util::cache_base< T >::value () inline
Access the cached value.
Definition at line 31 of file cache.hpp.
Referenced by otto::util::cache_base< PointCache >::operator*(), and otto::util::cache_base< PointCache >::operator->().
     {
       if (!_valid) {
         refresh();
         _valid = true;
       }
       return dynamic_cast<const T&>(*this);
     }
Member Data Documentation
_valid
template<typename T> bool otto::util::cache_base< T >::_valid = false protected
Definition at line 62 of file cache.hpp.
Referenced by otto::util::cache_base< PointCache >::invalidate(), otto::util::cache_base< PointCache >::valid(), and otto::util::cache_base< PointCache >::value().
The documentation for this struct was generated from the following file:
/home/topisani/dev/OTTO/src/util/cache.hpp