OTTO: otto::core::engines::internal::wrapper< T > Struct Template Reference
otto::core::engines::internal::wrapper< T > Struct Template Reference
Detailed Description
template<typename T>
struct otto::core::engines::internal::wrapper< T >
Wrapper for capturing parameter packs by forwarding.
Definition at line 271 of file engine.hpp.
#include <engine.hpp>
Public Member Functions
template<typename X , typename = std::enable_if_t<std::is_convertible_v<T, X>>>
wrapper (X &&x)
T get () const
Public Attributes
T value
Constructor & Destructor Documentation
template<typename T > template<typename X , typename = std::enable_if_t<std::is_convertible_v<T, X>>> otto::core::engines::internal::wrapper< T >::wrapper (X && x)
Definition at line 276 of file engine.hpp.
References otto::core::engines::internal::wrapper< T >::get().
Member Function Documentation
template<typename T > T otto::core::engines::internal::wrapper< T >::get () const
Definition at line 279 of file engine.hpp.
References otto::core::engines::internal::wrapper< T >::get().
Referenced by otto::core::engines::internal::wrapper< T >::get(), and otto::core::engines::internal::wrapper< T >::wrapper().
Member Data Documentation
template<typename T > T otto::core::engines::internal::wrapper< T >::value
Definition at line 273 of file engine.hpp.
The documentation for this struct was generated from the following file:
/home/travis/build/topisani/OTTO/src/core/engines/engine.hpp