OTTO: otto::core::midi::shared_vector< T > Struct Template Reference
otto::core::midi::shared_vector< T > Struct Template Reference
#include <midi.hpp>
Public Types
using value_type = T
Public Member Functions
shared_vector ()=default
shared_vector (std::vector< value_type > &&other)
shared_vector (const std::vector< value_type > &other)
auto begin ()
auto end ()
auto begin () const
auto end () const
auto cbegin () const
auto cend () const
auto && front ()
auto && back ()
auto && front () const
auto && back () const
auto & operator* ()
auto & operator* () const
auto & operator-> ()
auto & operator-> () const
auto & operator[] (std::size_t i)
auto clear ()
auto push_back (const value_type &el)
template<typename... Ref>
auto && emplace_back (Ref &&... args)
Public Attributes
std::shared_ptr< std::vector< value_type > > _data = std::make_shared<std::vector<value_type>>()
int _test_field
Detailed Description
template<typename T>
struct otto::core::midi::shared_vector< T >
Definition at line 192 of file midi.hpp.
Member Typedef Documentation
value_type
template<typename T> using otto::core::midi::shared_vector< T >::value_type = T
Definition at line 193 of file midi.hpp.
Constructor & Destructor Documentation
shared_vector() [1/3]
template<typename T> otto::core::midi::shared_vector< T >::shared_vector () default
shared_vector() [2/3]
template<typename T> otto::core::midi::shared_vector< T >::shared_vector (std::vector< value_type > && other) inline
Definition at line 197 of file midi.hpp.
       : _data(std::make_shared<std::vector<value_type>>(std::move(other)))
     {}
shared_vector() [3/3]
template<typename T> otto::core::midi::shared_vector< T >::shared_vector (const std::vector< value_type > & other) inline
Definition at line 201 of file midi.hpp.
       : _data(std::make_shared<std::vector<value_type>>(other))
     {}
Member Function Documentation
back() [1/2]
template<typename T> auto&& otto::core::midi::shared_vector< T >::back () inline
Definition at line 234 of file midi.hpp.
     {
       return _data->back();
     }
back() [2/2]
template<typename T> auto&& otto::core::midi::shared_vector< T >::back () const inline
Definition at line 242 of file midi.hpp.
     {
       return _data->back();
     }
begin() [1/2]
template<typename T> auto otto::core::midi::shared_vector< T >::begin () inline
Definition at line 205 of file midi.hpp.
     {
       return _data->begin();
     }
begin() [2/2]
template<typename T> auto otto::core::midi::shared_vector< T >::begin () const inline
Definition at line 213 of file midi.hpp.
     {
       return _data->begin();
     }
cbegin()
template<typename T> auto otto::core::midi::shared_vector< T >::cbegin () const inline
Definition at line 221 of file midi.hpp.
     {
       return _data->cbegin();
     }
cend()
template<typename T> auto otto::core::midi::shared_vector< T >::cend () const inline
Definition at line 225 of file midi.hpp.
     {
       return _data->cend();
     }
clear()
template<typename T> auto otto::core::midi::shared_vector< T >::clear () inline
Definition at line 270 of file midi.hpp.
     {
       _data->clear();
     }
emplace_back()
template<typename T> template<typename... Ref> auto&& otto::core::midi::shared_vector< T >::emplace_back (Ref &&... args) inline
Definition at line 281 of file midi.hpp.
     {
       return _data->emplace_back(std::forward<Ref>(args)...);
     };
end() [1/2]
template<typename T> auto otto::core::midi::shared_vector< T >::end () inline
Definition at line 209 of file midi.hpp.
     {
       return _data->end();
     }
end() [2/2]
template<typename T> auto otto::core::midi::shared_vector< T >::end () const inline
Definition at line 217 of file midi.hpp.
     {
       return _data->end();
     }
front() [1/2]
template<typename T> auto&& otto::core::midi::shared_vector< T >::front () inline
Definition at line 230 of file midi.hpp.
     {
       return _data->front();
     }
front() [2/2]
template<typename T> auto&& otto::core::midi::shared_vector< T >::front () const inline
Definition at line 238 of file midi.hpp.
     {
       return _data->front();
     }
operator*() [1/2]
template<typename T> auto& otto::core::midi::shared_vector< T >::operator* () inline
Definition at line 247 of file midi.hpp.
     {
       return *_data;
     }
operator*() [2/2]
template<typename T> auto& otto::core::midi::shared_vector< T >::operator* () const inline
Definition at line 251 of file midi.hpp.
     {
       return *_data;
     }
operator->() [1/2]
template<typename T> auto& otto::core::midi::shared_vector< T >::operator-> () inline
Definition at line 256 of file midi.hpp.
     {
       return &*_data;
     }
operator->() [2/2]
template<typename T> auto& otto::core::midi::shared_vector< T >::operator-> () const inline
Definition at line 260 of file midi.hpp.
     {
       return &*_data;
     }
operator[]()
template<typename T> auto& otto::core::midi::shared_vector< T >::operator[] (std::size_t i) inline
Definition at line 265 of file midi.hpp.
     {
       return (_data)[i];
     }
push_back()
template<typename T> auto otto::core::midi::shared_vector< T >::push_back (const value_type & el) inline
Definition at line 275 of file midi.hpp.
     {
       _data->push_back(el);
     }
Member Data Documentation
_data
template<typename T> std::shared_ptr<std::vector<value_type> > otto::core::midi::shared_vector< T >::_data = std::make_shared<std::vector<value_type>>()
Definition at line 286 of file midi.hpp.
Referenced by otto::core::midi::shared_vector< midi::AnyMidiEvent >::back(), otto::core::midi::shared_vector< midi::AnyMidiEvent >::begin(), otto::core::midi::shared_vector< midi::AnyMidiEvent >::cbegin(), otto::core::midi::shared_vector< midi::AnyMidiEvent >::cend(), otto::core::midi::shared_vector< midi::AnyMidiEvent >::clear(), otto::core::midi::shared_vector< midi::AnyMidiEvent >::emplace_back(), otto::core::midi::shared_vector< midi::AnyMidiEvent >::end(), otto::core::midi::shared_vector< midi::AnyMidiEvent >::front(), otto::core::midi::shared_vector< midi::AnyMidiEvent >::operator*(), otto::core::midi::shared_vector< midi::AnyMidiEvent >::operator->(), otto::core::midi::shared_vector< midi::AnyMidiEvent >::operator[](), and otto::core::midi::shared_vector< midi::AnyMidiEvent >::push_back().
_test_field
template<typename T> int otto::core::midi::shared_vector< T >::_test_field
Initial value:
= [] {
      DLOGI("Constructed a shared_vector");
      return 0;
    }()
Definition at line 288 of file midi.hpp.
The documentation for this struct was generated from the following file:
/home/topisani/dev/OTTO/src/core/audio/midi.hpp