OTTO: otto::engines::MasterScreen Struct Reference
otto::engines::MasterScreen Struct Reference
Public Member Functions
void draw (Canvas &ctx) override
void rotary (RotaryEvent e) override
Public Member Functions inherited from otto::core::engines::EngineScreen< Master >
EngineScreen (Master *engine)
virtual ~EngineScreen ()
Public Member Functions inherited from otto::core::ui::Screen
Screen ()
virtual ~Screen ()
virtual bool keypress (Key)
virtual bool keyrelease (Key)
virtual void rotary (RotaryEvent)
This should be used for handling rotary events.
virtual void on_show ()
Run by MainUI when switching to this screen.
virtual void on_hide ()
Run by MainUI when switching to another screen.
Public Member Functions inherited from otto::core::ui::vg::Drawable
Drawable ()=default
virtual ~Drawable ()=default
virtual void draw (Canvas &ctx)=0
Additional Inherited Members
Protected Attributes inherited from otto::core::engines::EngineScreen< Master >
Master & engine
Detailed Description
Definition at line 16 of file master.cpp.
Member Function Documentation
draw()
void otto::engines::MasterScreen::draw (Canvas & ctx) override
Definition at line 46 of file master.cpp.
References otto::core::ui::vg::Canvas::bezierCurveTo(), otto::core::ui::vg::Colour::bytes(), otto::core::ui::vg::Canvas::circle(), otto::core::engines::EngineScreen< Master >::engine, otto::core::ui::vg::Canvas::fill(), otto::core::ui::vg::Canvas::fillStyle(), otto::core::ui::vg::Canvas::fillText(), otto::core::ui::vg::Canvas::font(), otto::core::ui::vg::Canvas::lineTo(), otto::core::ui::vg::Canvas::moveTo(), otto::core::ui::vg::Canvas::rotateAround(), otto::core::ui::vg::Canvas::stroke(), and otto::core::ui::vg::Canvas::strokeStyle().
   {
     using namespace ui::vg;
     // Text
     ctx.font(Fonts::Bold, 26);
     ctx.fillStyle(Colour::bytes(255, 255, 255));
     ctx.fillText("master volume", 86.6, 189.9);
     // Dot
     ctx.save();
     ctx.beginPath();
     ctx.circle({160,110},4);
     ctx.fillStyle(Colours::Green);
     ctx.fill();
     ctx.lineWidth(6.0);
     ctx.strokeStyle(Colour::bytes(147, 192, 34));
     ctx.lineCap(Canvas::LineCap::ROUND);
     ctx.lineJoin(Canvas::LineJoin::ROUND);
     ctx.stroke();
     // Dial
     float rotation = -2.15 + engine.props.volume * 4.3;
     ctx.save();
     ctx.rotateAround(rotation,{160,110});
     ctx.beginPath();
     ctx.moveTo(160.0, 110.8);
     ctx.lineTo(160.0, 73.4);
     ctx.stroke();
     ctx.restore();
     // Outer circle
     ctx.restore();
     ctx.beginPath();
     ctx.moveTo(109.4, 144.9);
     ctx.bezierCurveTo(102.8, 135.1, 99.0, 123.4, 99.0, 110.8);
     ctx.bezierCurveTo(99.0, 77.1, 126.3, 49.8, 160.0, 49.8);
     ctx.bezierCurveTo(193.7, 49.8, 221.0, 77.1, 221.0, 110.8);
     ctx.bezierCurveTo(221.0, 122.6, 217.6, 133.7, 211.8, 143.0);
     ctx.lineWidth(6.0);
     ctx.strokeStyle(Colour::bytes(99, 99, 99));
     ctx.lineCap(Canvas::LineCap::ROUND);
     ctx.lineJoin(Canvas::LineJoin::ROUND);
     ctx.stroke();
     ctx.restore();
   }
rotary()
void otto::engines::MasterScreen::rotary (RotaryEvent e) override
Definition at line 40 of file master.cpp.
References otto::core::engines::EngineScreen< Master >::engine.
   {
     auto& props = engine.props;
     props.volume.step(ev.clicks);
   }
The documentation for this struct was generated from the following file:
/home/topisani/dev/OTTO/src/engines/misc/master/master.cpp