OTTO: otto::core::props::branch_base Struct Reference
otto::core::props::branch_base Struct Reference
Detailed Description
Base class of all property branches.
All mixin branches inherit virtually from this
Definition at line 91 of file base.hpp.
#include <base.hpp>
Public Types
using storage_type = std::vector< std::reference_wrapper< property_base >>
Public Member Functions
branch_base ()
storage_type & children ()
storage_type const & children () const
void push_back (property_base *ptr)
void push_back (property_base &ref)
Public Member Functions inherited from otto::core::props::property_base
property_base (branch_base *parent=nullptr, std::string const &name="")
virtual ~property_base ()=default
const std::string & name () const noexcept
branch_base const *const parent () const noexcept
template<typename Tag >
bool is () const noexcept
template<typename Tag >
mixin::interface< Tag > & as ()
template<typename Tag >
mixin::interface< Tag > const & as () const
bool is_branch () const noexcept
template<typename Tag >
mixin::branch< Tag > & as_branch ()
template<typename Tag >
mixin::branch< Tag > const & as_branch () const
Member Typedef Documentation
using otto::core::props::branch_base::storage_type = std::vector<std::reference_wrapper<property_base>>
Definition at line 93 of file base.hpp.
Constructor & Destructor Documentation
otto::core::props::branch_base::branch_base ()
Definition at line 97 of file base.hpp.
Member Function Documentation
storage_type& otto::core::props::branch_base::children ()
Definition at line 99 of file base.hpp.
storage_type const& otto::core::props::branch_base::children () const
Definition at line 103 of file base.hpp.
void otto::core::props::branch_base::push_back (property_base * ptr)
Definition at line 107 of file base.hpp.
References std::vector< T >::push_back(), and std::ref().
void otto::core::props::branch_base::push_back (property_base & ref)
Definition at line 111 of file base.hpp.
References std::vector< T >::push_back(), and std::ref().
The documentation for this struct was generated from the following file:
/home/travis/build/topisani/OTTO/src/core/props/internal/base.hpp