OTTO: otto::core::ui::widgets::Waveform< Container > Struct Template Reference
otto::core::ui::widgets::Waveform< Container > Struct Template Reference
Detailed Description
template<typename Container>
struct otto::core::ui::widgets::Waveform< Container >
Draws a waveform from data.
Definition at line 13 of file waveform_widget.hpp.
#include <waveform_widget.hpp>
Public Types
using Range = util::audio::Section< int >
Public Member Functions
Waveform (const Container &cont, vg::Size s, float top_val=1.f)
void draw (vg::Canvas &)
Draw the entire waveform using the default plotter (plotRounded).
template<typename Plotter >
void draw (vg::Canvas &, Plotter &&)
Draw the entire waveform using Plotter
void draw_range (vg::Canvas &, Range subrange)
Draw a subset of the waveform using the default plotter (plotRounded).
template<typename Plotter >
void draw_range (vg::Canvas &, Range subrange, Plotter &&)
Draw a subset of the waveform using Plotter.
Range range () const
The viewed range.
void range (Range r)
Set the viewed range.
float top_val () const
void top_val (float v)
vg::Point point (int index)
Get the graphical point for a sample index.
vg::Point point_floor (int index)
vg::Point point_ceil (int index)
Public Member Functions inherited from otto::core::ui::Widget
Widget ()
Widget (vg::Size size)
Public Member Functions inherited from otto::core::ui::vg::Drawable
Drawable ()=default
virtual ~Drawable ()=default
Public Attributes
util::audio::Section< float > radius_range = {2.f, 4.f}
Public Attributes inherited from otto::core::ui::Widget
vg::Size size
Member Typedef Documentation
Range
template<typename Container > using otto::core::ui::widgets::Waveform< Container >::Range = util::audio::Section<int>
Definition at line 14 of file waveform_widget.hpp.
Constructor & Destructor Documentation
Waveform()
template<typename Container > otto::core::ui::widgets::Waveform< Container >::Waveform (const Container & cont, vg::Size s, float top_val = 1.f)
Definition at line 18 of file waveform_widget.hpp.
Member Function Documentation
draw() [1/2]
template<typename C > void otto::core::ui::widgets::Waveform< C >::draw (vg::Canvas & ctx) virtual
Draw the entire waveform using the default plotter (plotRounded).
Implements otto::core::ui::vg::Drawable.
Definition at line 159 of file waveform_widget.hpp.
References otto::core::ui::vg::Canvas::plotRounded().
draw() [2/2]
template<typename C > template<typename Plotter > void otto::core::ui::widgets::Waveform< C >::draw (vg::Canvas & ctx, Plotter && p)
Draw the entire waveform using Plotter
\requires Plotter should be invocable as void(ctx, first, last)
Definition at line 168 of file waveform_widget.hpp.
References std::begin().
draw_range() [1/2]
template<typename C > void otto::core::ui::widgets::Waveform< C >::draw_range (vg::Canvas & ctx, Range subrange)
Draw a subset of the waveform using the default plotter (plotRounded).
Useful for colouring different parts differently.
Parameters
subrange The range to draw, with 0 at [*Waveform<C>::range]().in
\requires subrange should be within [*Waveform::range]() - range.in
Definition at line 178 of file waveform_widget.hpp.
References otto::core::ui::vg::Canvas::plotRounded().
draw_range() [2/2]
template<typename C > template<typename Plotter > void otto::core::ui::widgets::Waveform< C >::draw_range (vg::Canvas & ctx, Range subrange, Plotter && p)
Draw a subset of the waveform using Plotter.
Useful for colouring different parts differently.
Parameters
subrange The range to draw, with 0 at [*Waveform::range]()().in
\requires subrange should be within [*Waveform::range]() - range.in
\requires Plotter should be invocable as void(ctx, first, last)
Definition at line 187 of file waveform_widget.hpp.
References std::begin(), std::ceil(), std::floor(), otto::util::audio::Section< T >::in, std::max(), and otto::util::audio::Section< T >::out.
range() [1/2]
template<typename Container > Range otto::core::ui::widgets::Waveform< Container >::range () const
The viewed range.
Start and end indexes into the container coresponding to left/right edges of the widget
Definition at line 61 of file waveform_widget.hpp.
range() [2/2]
template<typename Container > void otto::core::ui::widgets::Waveform< Container >::range (Range r)
Set the viewed range.
Invalidates the cache if the new value is different from the old
Definition at line 68 of file waveform_widget.hpp.
References std::max().
top_val() [1/2]
template<typename Container > float otto::core::ui::widgets::Waveform< Container >::top_val () const
Definition at line 76 of file waveform_widget.hpp.
top_val() [2/2]
template<typename Container > void otto::core::ui::widgets::Waveform< Container >::top_val (float v)
Definition at line 80 of file waveform_widget.hpp.
point()
template<typename Container > vg::Point otto::core::ui::widgets::Waveform< Container >::point (int index)
Get the graphical point for a sample index.
Definition at line 89 of file waveform_widget.hpp.
References otto::core::ui::vg::Size::h, otto::util::audio::Section< T >::in, std::round(), and otto::core::ui::Widget::size.
point_floor()
template<typename Container > vg::Point otto::core::ui::widgets::Waveform< Container >::point_floor (int index)
Definition at line 98 of file waveform_widget.hpp.
References std::floor(), otto::core::ui::vg::Size::h, otto::util::audio::Section< T >::in, and otto::core::ui::Widget::size.
point_ceil()
template<typename Container > vg::Point otto::core::ui::widgets::Waveform< Container >::point_ceil (int index)
Definition at line 107 of file waveform_widget.hpp.
References std::ceil(), otto::core::ui::vg::Size::h, otto::util::audio::Section< T >::in, and otto::core::ui::Widget::size.
Member Data Documentation
radius_range
template<typename Container > util::audio::Section<float> otto::core::ui::widgets::Waveform< Container >::radius_range = {2.f, 4.f}
Definition at line 16 of file waveform_widget.hpp.
The documentation for this struct was generated from the following file:
/home/travis/build/topisani/OTTO/src/core/ui/waveform_widget.hpp