OTTO: otto::services::test::DummyAudioManager Struct Reference
otto::services::test::DummyAudioManager Struct Reference final
Detailed Description
Definition at line 92 of file dummy_services.hpp.
#include <dummy_services.hpp>
Public Member Functions
DummyAudioManager ()
core::audio::ProcessData< 2 > process ()
void set_bs_sr (int buffer_size, int sample_rate)
Public Member Functions inherited from otto::services::AudioManager
AudioManager ()
Fires Events::pre_init and generates midi frequency table.
core::audio::AudioBufferPool & buffer_pool () noexcept
Use this to get audio buffers.
void send_midi_event (core::midi::AnyMidiEvent) noexcept
Send a midi event into the system.
int samplerate () const noexcept
Get the samplerate.
int buffer_size () const noexcept
Get the buffer size.
unsigned buffer_number () const noexcept
Get the current buffer number.
void wait_one () const noexcept
Wait at least until the current process call is done.
void start () noexcept
Start audio processing.
bool running () noexcept
Check if audio should be processed.
float cpu_time () noexcept
The amount of cpu time spent on average since the last call to this function.
Public Member Functions inherited from otto::core::Service
Service ()=default
virtual ~Service ()=default
Service (const Service &)=delete
Service (Service &&)=delete
auto operator= (const Service &)=delete
auto operator= (Service &&)=delete
Static Public Member Functions
static DummyAudioManager & current ()
Static Public Member Functions inherited from otto::services::AudioManager
static AudioManager & current () noexcept
Get the current instance of this service.
Additional Inherited Members
Public Attributes inherited from otto::services::AudioManager
struct otto::services::AudioManager::Events events
Protected Attributes inherited from otto::services::AudioManager
util::double_buffered< core::midi::shared_vector< core::midi::AnyMidiEvent > > midi_bufs = {{}, {}}
std::atomic_int _samplerate = 48000
std::atomic_uint _buffer_size = 256
std::atomic_uint _buffer_number = 0
util::audio::Graph _cpu_time
Constructor & Destructor Documentation
DummyAudioManager()
otto::services::test::DummyAudioManager::DummyAudioManager ()
Definition at line 93 of file dummy_services.hpp.
References set_bs_sr().
Member Function Documentation
process()
core::audio::ProcessData<2> otto::services::test::DummyAudioManager::process ()
Definition at line 97 of file dummy_services.hpp.
References otto::services::AudioManager::_buffer_number, otto::services::AudioManager::_buffer_size, otto::services::Application::audio_manager, otto::services::Application::current(), otto::services::Application::engine_manager, LOGE, LOGW_IF, otto::services::AudioManager::midi_bufs, std::move(), otto::services::AudioManager::running(), and otto::services::Application::running().
set_bs_sr()
void otto::services::test::DummyAudioManager::set_bs_sr (int buffer_size, int sample_rate)
Definition at line 129 of file dummy_services.hpp.
References otto::services::AudioManager::_buffer_size, otto::services::AudioManager::buffer_pool(), otto::services::AudioManager::buffer_size(), and otto::core::audio::AudioBufferPool::set_buffer_size().
Referenced by DummyAudioManager().
current()
static DummyAudioManager& otto::services::test::DummyAudioManager::current () static
Definition at line 135 of file dummy_services.hpp.
References otto::services::Application::current().
The documentation for this struct was generated from the following file:
/home/travis/build/topisani/OTTO/test/dummy_services.hpp