OTTO: otto::engines::NukeSynthScreen Struct Reference
otto::engines::NukeSynthScreen Struct Reference
Public Member Functions
void draw (Canvas &ctx) override
bool keypress (Key key) override
void rotary (RotaryEvent e) override
Public Member Functions inherited from otto::core::engines::EngineScreen< NukeSynth >
EngineScreen (NukeSynth *engine)
virtual ~EngineScreen ()
Public Member Functions inherited from otto::core::ui::Screen
Screen ()
virtual ~Screen ()
virtual bool keypress (Key)
Run by MainUI when a key is pressed.
virtual bool keyrelease (Key)
Run by MainUI when a key is released.
virtual void rotary (RotaryEvent)
This should be used for handling rotary events.
virtual void on_show ()
Run by MainUI when switching to this screen.
virtual void on_hide ()
Run by MainUI when switching to another screen.
Public Member Functions inherited from otto::core::ui::vg::Drawable
Drawable ()=default
virtual ~Drawable ()=default
virtual void draw (Canvas &ctx)=0
Draw this widget to the context.
Additional Inherited Members
Protected Attributes inherited from otto::core::engines::EngineScreen< NukeSynth >
NukeSynth & engine
Detailed Description
Definition at line 17 of file nuke.cpp.
Member Function Documentation
draw()
void otto::engines::NukeSynthScreen::draw (Canvas & ctx) override
Definition at line 71 of file nuke.cpp.
References otto::core::ui::vg::Canvas::arc(), otto::filesystem::begin(), otto::core::ui::vg::Canvas::bezierCurveTo(), otto::core::ui::vg::Colours::Blue, otto::filesystem::end(), otto::core::ui::vg::Canvas::fill(), otto::core::ui::vg::Canvas::fillStyle(), otto::core::ui::vg::Colours::Gray50, otto::core::ui::vg::Colours::Green, otto::core::ui::vg::Canvas::group(), otto::core::ui::vg::Canvas::lineTo(), otto::core::ui::vg::Canvas::moveTo(), otto::core::ui::vg::Colours::Pink, otto::core::ui::vg::Canvas::plotLines(), otto::core::ui::vg::Colours::Red, otto::core::ui::vg::Canvas::rotateAround(), otto::core::ui::vg::Canvas::stroke(), otto::core::ui::vg::Canvas::strokeStyle(), otto::core::ui::vg::Colours::White, and otto::core::ui::vg::Colours::Yellow.
keypress()
bool otto::engines::NukeSynthScreen::keypress (Key key) override
Definition at line 46 of file nuke.cpp.
rotary()
void otto::engines::NukeSynthScreen::rotary (RotaryEvent e) override
Definition at line 51 of file nuke.cpp.
References otto::core::ui::vg::Colours::Blue, otto::core::engines::EngineScreen< NukeSynth >::engine, otto::core::ui::vg::Colours::Green, otto::core::ui::vg::Colours::Red, and otto::core::ui::vg::Colours::White.
The documentation for this struct was generated from the following file:
/home/topisani/dev/OTTO/src/engines/synths/nuke/nuke.cpp