OTTO: PanSM Struct Reference
PanSM Struct Reference
Detailed Description
Equal-power 2-channel panner (Stereo-to-Mono)
Definition at line 4 of file pan.hpp.
#include <pan.hpp>
Public Member Functions
PanSM (float pos=0)
float operator() (float position, float in1, float in2)
Filter sample (mono to stereo)
float operator() (float in1, float in2)
Filter sample (mono to stereo)
void pos (float v)
Set position (constant power law)
void volume1 (float v)
void volume2 (float v)
Protected Attributes
float w1
float w2
float vol1 = 0.5
float vol2 = 0.5
Constructor & Destructor Documentation
PanSM()
PanSM::PanSM (float pos = 0)
Parameters
[in] pos Position, in [-1, 1]
Definition at line 6 of file pan.hpp.
References pos().
Member Function Documentation
operator()() [1/2]
float PanSM::operator() (float position, float in1, float in2)
Filter sample (mono to stereo)
Definition at line 12 of file pan.hpp.
References pos(), w1, and w2.
operator()() [2/2]
float PanSM::operator() (float in1, float in2)
Filter sample (mono to stereo)
Definition at line 19 of file pan.hpp.
References w1, and w2.
pos()
void PanSM::pos (float v)
Set position (constant power law)
Parameters
[in] v Position, in [-1, 1]
Definition at line 26 of file pan.hpp.
References vol1, vol2, w1, and w2.
Referenced by operator()(), and PanSM().
volume1()
void PanSM::volume1 (float v)
Definition at line 39 of file pan.hpp.
References vol1.
volume2()
void PanSM::volume2 (float v)
Definition at line 42 of file pan.hpp.
References vol2.
Member Data Documentation
w1
float PanSM::w1 protected
Definition at line 47 of file pan.hpp.
Referenced by operator()(), and pos().
w2
float PanSM::w2 protected
Definition at line 47 of file pan.hpp.
Referenced by operator()(), and pos().
vol1
float PanSM::vol1 = 0.5 protected
Definition at line 48 of file pan.hpp.
Referenced by pos(), and volume1().
vol2
float PanSM::vol2 = 0.5 protected
Definition at line 49 of file pan.hpp.
Referenced by pos(), and volume2().
The documentation for this struct was generated from the following file:
/home/travis/build/topisani/OTTO/src/util/dsp/pan.hpp