OTTO: otto::core::audio::FaustWrapper< Cin, Cout > Struct Template Reference
otto::core::audio::FaustWrapper< Cin, Cout > Struct Template Reference
#include <faust.hpp>
Public Member Functions
FaustWrapper ()
FaustWrapper (std::unique_ptr< dsp > &&d, FaustClient &client)
virtual ~FaustWrapper ()
audio::ProcessData< Cout > process (audio::ProcessData< Cin > data)
Public Attributes
FaustOptions opts
std::unique_ptr< dsp > fDSP
Detailed Description
template<int Cin, int Cout>
struct otto::core::audio::FaustWrapper< Cin, Cout >
A Wrapper for faust scripts All interactions with faust should go through this wrapper
Template Parameters
Cin The number of input audio channels. Make sure this corresponds with the actually called faust script
Cout The number of output audio channels Make sure this corresponds with the actually called faust script
Definition at line 157 of file faust.hpp.
Constructor & Destructor Documentation
FaustWrapper() [1/2]
template<int Cin, int Cout> otto::core::audio::FaustWrapper< Cin, Cout >::FaustWrapper () inline
Definition at line 162 of file faust.hpp.
 {};
FaustWrapper() [2/2]
template<int Cin, int Cout> otto::core::audio::FaustWrapper< Cin, Cout >::FaustWrapper (std::unique_ptr< dsp > && d, FaustClient & client) inline
Definition at line 164 of file faust.hpp.
                                                               : opts(client), fDSP(std::move(d))
     {
       if (fDSP->getNumInputs() != Cin || fDSP->getNumOutputs() != Cout) {
         throw std::runtime_error("A faustwrapper was instantiated with a "
                                  "non-matching faust dsp instance");
       }
       detail::register_faust_wrapper_events(*fDSP, opts);
     }
~FaustWrapper()
template<int Cin, int Cout> virtual otto::core::audio::FaustWrapper< Cin, Cout >::~FaustWrapper () inline virtual
Definition at line 174 of file faust.hpp.
 {}
Member Function Documentation
process()
template<int Cin, int Cout> audio::ProcessData<Cout> otto::core::audio::FaustWrapper< Cin, Cout >::process (audio::ProcessData< Cin > data) inline
Definition at line 176 of file faust.hpp.
Referenced by otto::engines::Master::process(), otto::engines::Wormhole::process(), and otto::engines::NukeSynth::process().
     {
       auto out = service::audio::buffer_pool().allocate_multi<Cout>();
       auto in_bufs = data.audio.data();
       auto out_bufs = out.data();
       fDSP->compute(data.nframes, in_bufs.data(), out_bufs.data());
       return data.redirect(out);
     }
Member Data Documentation
fDSP
template<int Cin, int Cout> std::unique_ptr<dsp> otto::core::audio::FaustWrapper< Cin, Cout >::fDSP
Definition at line 160 of file faust.hpp.
Referenced by otto::core::audio::FaustWrapper< 0, 1 >::FaustWrapper(), and otto::core::audio::FaustWrapper< 0, 1 >::process().
opts
template<int Cin, int Cout> FaustOptions otto::core::audio::FaustWrapper< Cin, Cout >::opts
Definition at line 158 of file faust.hpp.
Referenced by otto::core::audio::FaustWrapper< 0, 1 >::FaustWrapper().
The documentation for this struct was generated from the following file:
/home/topisani/dev/OTTO/src/core/audio/faust.hpp