OTTO: otto::board::ui::Modifiers Struct Reference
otto::board::ui::Modifiers Struct Reference
A set of modifiers.
#include <keys.hpp>
Public Member Functions
constexpr Modifiers (std::initializer_list< Modifier > mods={}) noexcept
constexpr Modifiers (Modifier data) noexcept
constexpr Modifiers (std::underlying_type_t< Modifier > data) noexcept
constexpr bool is (Modifier m) const noexcept
constexpr void set (Modifier m, bool flag=true) noexcept
constexpr Modifiers operator & (Modifier m) const noexcept
constexpr Modifiers operator| (Modifier m) const noexcept
constexpr Modifiers operator| (Modifiers m) const noexcept
constexpr operator bool () const noexcept
constexpr Modifiers (std::initializer_list< Modifier > mods={}) noexcept
constexpr Modifiers (Modifier data) noexcept
constexpr Modifiers (std::underlying_type_t< Modifier > data) noexcept
constexpr bool is (Modifier m) const noexcept
constexpr void set (Modifier m, bool flag=true) noexcept
constexpr Modifiers operator & (Modifier m) const noexcept
constexpr Modifiers operator| (Modifier m) const noexcept
constexpr Modifiers operator| (Modifiers m) const noexcept
constexpr operator bool () const noexcept
Public Attributes
std::underlying_type_t< Modifier > data = 0
Detailed Description
A set of modifiers.
Definition at line 147 of file keys.hpp.
Constructor & Destructor Documentation
Modifiers() [1/6]
constexpr otto::board::ui::Modifiers::Modifiers (std::initializer_list< Modifier > mods = {}) inline noexcept
Definition at line 150 of file keys.hpp.
                                                              {}) noexcept
       : data{util::accumulate(mods, 0, [](auto m1, Modifier m2) {
           return util::underlying(m1) | util::underlying(m2);
         })}
     {}
Modifiers() [2/6]
constexpr otto::board::ui::Modifiers::Modifiers (Modifier data) inline noexcept
Definition at line 156 of file keys.hpp.
 : data(util::underlying(data)) {}
Modifiers() [3/6]
constexpr otto::board::ui::Modifiers::Modifiers (std::underlying_type_t< Modifier > data) inline noexcept
Definition at line 158 of file keys.hpp.
 : data(data) {}
Modifiers() [4/6]
constexpr otto::board::ui::Modifiers::Modifiers (std::initializer_list< Modifier > mods = {}) inline noexcept
Definition at line 155 of file keys.hpp.
                                                              {}) noexcept
       : data{util::accumulate(mods, 0, [](auto m1, Modifier m2) {
           return util::underlying(m1) | util::underlying(m2);
         })}
     {}
Modifiers() [5/6]
constexpr otto::board::ui::Modifiers::Modifiers (Modifier data) inline noexcept
Definition at line 161 of file keys.hpp.
                                                 : data(util::underlying(data))
     {}
Modifiers() [6/6]
constexpr otto::board::ui::Modifiers::Modifiers (std::underlying_type_t< Modifier > data) inline noexcept
Definition at line 164 of file keys.hpp.
       : data(data)
     {}
Member Function Documentation
is() [1/2]
constexpr bool otto::board::ui::Modifiers::is (Modifier m) const inline noexcept
Definition at line 160 of file keys.hpp.
References data, otto::board::ui::m, and otto::util::underlying().
     {
       return util::underlying(m) & data;
     }
is() [2/2]
constexpr bool otto::board::ui::Modifiers::is (Modifier m) const inline noexcept
Definition at line 168 of file keys.hpp.
References data, otto::board::ui::m, and otto::util::underlying().
     {
       return util::underlying(m) & data;
     }
operator &() [1/2]
constexpr Modifiers otto::board::ui::Modifiers::operator& (Modifier m) const inline noexcept
Definition at line 173 of file keys.hpp.
References data, otto::board::ui::m, and otto::util::underlying().
     {
       return {data & util::underlying(m)};
     }
operator &() [2/2]
constexpr Modifiers otto::board::ui::Modifiers::operator& (Modifier m) const inline noexcept
Definition at line 181 of file keys.hpp.
References data, otto::board::ui::m, and otto::util::underlying().
     {
       return {data & util::underlying(m)};
     }
operator bool() [1/2]
constexpr otto::board::ui::Modifiers::operator bool () const inline noexcept
Definition at line 188 of file keys.hpp.
References data.
     {
       return data != 0;
     }
operator bool() [2/2]
constexpr otto::board::ui::Modifiers::operator bool () const inline noexcept
Definition at line 196 of file keys.hpp.
References data.
     {
       return data != 0;
     }
operator|() [1/4]
constexpr Modifiers otto::board::ui::Modifiers::operator| (Modifier m) const inline noexcept
Definition at line 178 of file keys.hpp.
References data, otto::board::ui::m, and otto::util::underlying().
     {
       return {data | util::underlying(m)};
     }
operator|() [2/4]
constexpr Modifiers otto::board::ui::Modifiers::operator| (Modifiers m) const inline noexcept
Definition at line 183 of file keys.hpp.
References data, and otto::board::ui::m.
     {
       return {data | m.data};
     }
operator|() [3/4]
constexpr Modifiers otto::board::ui::Modifiers::operator| (Modifier m) const inline noexcept
Definition at line 186 of file keys.hpp.
References data, otto::board::ui::m, and otto::util::underlying().
     {
       return {data | util::underlying(m)};
     }
operator|() [4/4]
constexpr Modifiers otto::board::ui::Modifiers::operator| (Modifiers m) const inline noexcept
Definition at line 191 of file keys.hpp.
References data, and otto::board::ui::m.
     {
       return {data | m.data};
     }
set() [1/2]
constexpr void otto::board::ui::Modifiers::set (Modifier m, bool flag = true) inline noexcept
Definition at line 165 of file keys.hpp.
References data, otto::board::ui::m, and otto::util::underlying().
     {
       if (flag)
         data |= util::underlying(m);
       else
         data &= ~util::underlying(m);
     }
set() [2/2]
constexpr void otto::board::ui::Modifiers::set (Modifier m, bool flag = true) inline noexcept
Definition at line 173 of file keys.hpp.
References data, otto::board::ui::m, and otto::util::underlying().
     {
       if (flag)
         data |= util::underlying(m);
       else
         data &= ~util::underlying(m);
     }
Member Data Documentation
data
std::underlying_type_t< Modifier > otto::board::ui::Modifiers::data = 0
Definition at line 148 of file keys.hpp.
Referenced by is(), operator &(), operator bool(), operator|(), and set().
The documentation for this struct was generated from the following file:
/home/topisani/dev/OTTO/boards/parts/ui/egl/include/board/ui/keys.hpp