OTTO: otto::engines::EuclidScreen Struct Reference
otto::engines::EuclidScreen Struct Reference
Classes
struct State
Public Member Functions
void draw (Canvas &ctx) override
bool keypress (Key key) override
void rotary (RotaryEvent e) override
void draw_normal (Canvas &ctx)
void draw_recording (Canvas &ctx)
void refresh_state ()
void draw_channel (ui::vg::Canvas &ctx, State::ChannelState &chan)
Public Member Functions inherited from otto::core::engines::EngineScreen< Euclid >
EngineScreen (Euclid *engine)
virtual ~EngineScreen ()
Public Member Functions inherited from otto::core::ui::Screen
Screen ()
virtual ~Screen ()
virtual bool keypress (Key)
virtual bool keyrelease (Key)
virtual void rotary (RotaryEvent)
This should be used for handling rotary events.
virtual void on_show ()
Run by MainUI when switching to this screen.
virtual void on_hide ()
Run by MainUI when switching to another screen.
Public Member Functions inherited from otto::core::ui::vg::Drawable
Drawable ()=default
virtual ~Drawable ()=default
virtual void draw (Canvas &ctx)=0
Public Attributes
struct otto::engines::EuclidScreen::State state
Additional Inherited Members
Protected Attributes inherited from otto::core::engines::EngineScreen< Euclid >
Euclid & engine
Detailed Description
Definition at line 20 of file euclid.cpp.
Member Function Documentation
draw()
void otto::engines::EuclidScreen::draw (Canvas & ctx) override
Definition at line 184 of file euclid.cpp.
   {
     if (engine.recording)
       draw_recording(ctx);
     else
       draw_normal(ctx);
   }
draw_channel()
void otto::engines::EuclidScreen::draw_channel (ui::vg::Canvas & ctx, State::ChannelState & chan)
Definition at line 260 of file euclid.cpp.
References otto::engines::Euclid::Channel::_beat_counter, otto::core::ui::vg::Canvas::arc(), otto::core::ui::vg::Colour::bytes(), otto::engines::EuclidScreen::State::ChannelState::channel, otto::core::ui::vg::Canvas::circle(), otto::core::ui::vg::Canvas::fill(), otto::engines::EuclidScreen::State::ChannelState::hits, otto::engines::EuclidScreen::State::ChannelState::is_current, otto::engines::EuclidScreen::State::ChannelState::length, otto::engines::EuclidScreen::State::ChannelState::radius, and otto::core::ui::vg::Canvas::stroke().
   {
     using namespace ui::vg;
     auto hit_colour = chan.is_current ? Colour(Colours::Blue) : Colour::bytes(0x88, 0x72, 0x8E);
     auto len_colour = chan.is_current ? Colour(Colours::Green) : hit_colour;
     if (chan.length == 0) {
       ctx.lineWidth(6);
       ctx.beginPath();
       ctx.circle(state.center, chan.radius);
       ctx.stroke(len_colour);
       return;
     }
     for (auto& hit : util::sequence(chan.hits.begin(), chan.hits.begin() + chan.length)) {
       ctx.beginPath();
       ctx.circle(hit.point, hit.active ? 7 : 3);
       ctx.fill(hit_colour);
     }
     if (chan.length < state.max_length) {
       ctx.lineWidth(6);
       ctx.beginPath();
       ctx.arc(state.center, chan.radius,
               2 * M_PI * ((chan.length - 0.3) / float(state.max_length) - 0.25),
               2 * M_PI * ((state.max_length - 1 + 0.3) / float(state.max_length) - 0.25));
       ctx.stroke(len_colour);
     }
     auto& hit =
       chan.hits.at((chan.channel->_beat_counter + (engine.running ? 0 : 1)) % chan.length);
     ctx.beginPath();
     float r = (hit.active ? 7 : 3);
     if (engine.running) r *= (1 - (engine._counter / float(engine._samples_per_beat)));
     ctx.circle(hit.point, r);
     ctx.fill(Colours::Red);
   }
draw_normal()
void otto::engines::EuclidScreen::draw_normal (Canvas & ctx)
Definition at line 214 of file euclid.cpp.
References otto::core::ui::vg::Canvas::arc(), otto::core::ui::vg::Canvas::fillStyle(), otto::core::ui::vg::Canvas::fillText(), otto::core::ui::vg::Canvas::font(), and otto::core::ui::vg::Canvas::stroke().
   {
     using namespace ui::vg;
     auto& props = engine.props;
     auto& current = props.channels.at(props.channel);
     for (auto& chan : state.channels) {
       draw_channel(ctx, chan);
     }
     ctx.lineWidth(6);
     ctx.beginPath();
     ctx.arc(state.center, 25, -M_PI / 2.f,
             2.0 * M_PI * (current.rotation / float(state.max_length) - 0.25));
     ctx.stroke(Colours::Red);
     ctx.font(Fonts::Norm, 22.0);
     ctx.fillStyle(Colours::White);
     ctx.fillText("length", 252, 41.6);
     ctx.save();
     ctx.font(Fonts::Norm, 35.0);
     ctx.fillStyle(Colours::Green);
     ctx.fillText(std::to_string(current.length), 252, 72.9);
     ctx.font(Fonts::Norm, 22.0);
     ctx.fillStyle(Colours::White);
     ctx.fillText("pulses", 252, 108.7);
     ctx.font(Fonts::Norm, 35.0);
     ctx.fillStyle(Colours::Yellow);
     ctx.fillText(std::to_string(current.hits), 252, 140.0);
     ctx.font(Fonts::Norm, 22.0);
     ctx.fillStyle(Colours::White);
     ctx.fillText("offset", 252, 173.9);
     ctx.font(Fonts::Norm, 35.0);
     ctx.fillStyle(Colours::Red);
     ctx.fillText(std::to_string(current.rotation), 252, 205.3);
     ctx.restore();
   }
draw_recording()
void otto::engines::EuclidScreen::draw_recording (Canvas & ctx)
Definition at line 192 of file euclid.cpp.
References otto::core::ui::vg::Canvas::fillStyle(), otto::core::ui::vg::Canvas::fillText(), otto::util::view::filter(), otto::core::ui::vg::Canvas::font(), otto::util::join_strings(), and otto::util::view::transform().
   {
     using namespace ui::vg;
     auto& current = engine.current_channel();
     ctx.font(Fonts::Norm, 40);
     ctx.beginPath();
     ctx.fillStyle(Colours::Red);
     ctx.textAlign(HorizontalAlign::Center, VerticalAlign::Middle);
     ctx.fillText("CHANNEL NOTES", {160, 50});
     ctx.beginPath();
     ctx.fillText(util::join_strings(
                    util::view::transform(
                      util::view::filter(current.notes.get(), [](int note) { return note >= 0; }),
                      [](int note) { return midi::note_name(note); }),
                    " "),
                  {160, 120});
   }
keypress()
bool otto::engines::EuclidScreen::keypress (Key key) override
Definition at line 164 of file euclid.cpp.
   {
     switch (key) {
     case ui::Key::blue_click: [[fallthrough]];
     case ui::Key::green_click: [[fallthrough]];
     case ui::Key::white_click: [[fallthrough]];
     case ui::Key::red_click:
       if (engine.recording) {
         engine.recording = std::nullopt;
       } else {
         engine._has_pressed_keys = false;
         engine.recording = engine.current_channel().notes;
       }
       break;
     case ui::Key::play: engine._should_run = !engine._should_run; break;
     default: return false; ;
     }
     return true;
   }
refresh_state()
void otto::engines::EuclidScreen::refresh_state ()
Definition at line 301 of file euclid.cpp.
   {
     auto& props = engine.props;
     auto& current = props.channels.at(props.channel);
     state.max_length = 0;
     for (auto& chan : props.channels) {
       if (state.max_length < chan.length) state.max_length = chan.length;
     }
     for (int i = 0; i < 4; i++) {
       auto& chan = props.channels.at(i);
       auto& cs = state.channels.at(i);
       cs.channel = &chan;
       cs.radius = 40 + i * 20;
       cs.is_current = &chan == &current;
       cs.length = chan.length;
       for (int i = 0; i < cs.length; i++) {
         auto& hs = cs.hits.at(i);
         float angle = 2.0 * M_PI * (i / float(state.max_length) - 0.25);
         hs.point = state.center + Point{cs.radius * std::cos(angle), cs.radius * std::sin(angle)};
         hs.active = chan._hits_enabled.at(i);
       }
     }
   }
rotary()
void otto::engines::EuclidScreen::rotary (RotaryEvent e) override
Definition at line 147 of file euclid.cpp.
   {
     if (engine.recording) return;
     auto& props = engine.props;
     auto& current = props.channels.at(props.channel);
     switch (ev.rotary) {
     case Rotary::Blue: props.channel.step(ev.clicks); break;
     case Rotary::Green: current.length.step(ev.clicks); break;
     case Rotary::White: current.hits.step(ev.clicks); break;
     case Rotary::Red: current.rotation.step(ev.clicks); break;
     }
     current.update_notes();
     refresh_state();
   }
Member Data Documentation
state
struct otto::engines::EuclidScreen::State otto::engines::EuclidScreen::state
The documentation for this struct was generated from the following file:
/home/topisani/dev/OTTO/src/engines/seq/euclid/euclid.cpp