OTTO: otto::util::enum_map< Enum, T > Struct Template Reference
otto::util::enum_map< Enum, T > Struct Template Reference
Detailed Description
template<typename Enum, typename T>
struct otto::util::enum_map< Enum, T >
Definition at line 12 of file enum.hpp.
#include <enum.hpp>
Public Types
using value_type = T
using iterator = typename std::array< T, Enum::_size()>::iterator
using const_iterator = typename std::array< T, Enum::_size()>::const_iterator
Public Member Functions
constexpr auto begin () noexcept
constexpr auto begin () const noexcept
constexpr auto end () noexcept
constexpr auto end () const noexcept
constexpr value_type & front () noexcept
constexpr const value_type & front () const noexcept
constexpr value_type & back () noexcept
constexpr const value_type & back () const noexcept
constexpr value_type & operator[] (Enum e) noexcept
constexpr const value_type & operator[] (Enum e) const noexcept
constexpr value_type & at (Enum e)
constexpr const value_type & at (Enum e) const
constexpr value_type * data () noexcept
constexpr const value_type * data () const noexcept
Static Public Member Functions
static constexpr std::size_t size () noexcept
Public Attributes
std::array< T, Enum::_size()> _data
Member Typedef Documentation
value_type
template<typename Enum, typename T> using otto::util::enum_map< Enum, T >::value_type = T
Definition at line 13 of file enum.hpp.
iterator
template<typename Enum, typename T> using otto::util::enum_map< Enum, T >::iterator = typename std::array<T, Enum::_size()>::iterator
Definition at line 14 of file enum.hpp.
const_iterator
template<typename Enum, typename T> using otto::util::enum_map< Enum, T >::const_iterator = typename std::array<T, Enum::_size()>::const_iterator
Definition at line 15 of file enum.hpp.
Member Function Documentation
size()
template<typename Enum, typename T> static constexpr std::size_t otto::util::enum_map< Enum, T >::size () static constexpr noexcept
Definition at line 17 of file enum.hpp.
begin() [1/2]
template<typename Enum, typename T> constexpr auto otto::util::enum_map< Enum, T >::begin () constexpr noexcept
Definition at line 22 of file enum.hpp.
begin() [2/2]
template<typename Enum, typename T> constexpr auto otto::util::enum_map< Enum, T >::begin () const constexpr noexcept
Definition at line 27 of file enum.hpp.
end() [1/2]
template<typename Enum, typename T> constexpr auto otto::util::enum_map< Enum, T >::end () constexpr noexcept
Definition at line 32 of file enum.hpp.
end() [2/2]
template<typename Enum, typename T> constexpr auto otto::util::enum_map< Enum, T >::end () const constexpr noexcept
Definition at line 37 of file enum.hpp.
front() [1/2]
template<typename Enum, typename T> constexpr value_type& otto::util::enum_map< Enum, T >::front () constexpr noexcept
Definition at line 42 of file enum.hpp.
front() [2/2]
template<typename Enum, typename T> constexpr const value_type& otto::util::enum_map< Enum, T >::front () const constexpr noexcept
Definition at line 47 of file enum.hpp.
back() [1/2]
template<typename Enum, typename T> constexpr value_type& otto::util::enum_map< Enum, T >::back () constexpr noexcept
Definition at line 52 of file enum.hpp.
back() [2/2]
template<typename Enum, typename T> constexpr const value_type& otto::util::enum_map< Enum, T >::back () const constexpr noexcept
Definition at line 57 of file enum.hpp.
operator[]() [1/2]
template<typename Enum, typename T> constexpr value_type& otto::util::enum_map< Enum, T >::operator[] (Enum e) constexpr noexcept
Definition at line 62 of file enum.hpp.
operator[]() [2/2]
template<typename Enum, typename T> constexpr const value_type& otto::util::enum_map< Enum, T >::operator[] (Enum e) const constexpr noexcept
Definition at line 67 of file enum.hpp.
at() [1/2]
template<typename Enum, typename T> constexpr value_type& otto::util::enum_map< Enum, T >::at (Enum e) constexpr
Definition at line 72 of file enum.hpp.
at() [2/2]
template<typename Enum, typename T> constexpr const value_type& otto::util::enum_map< Enum, T >::at (Enum e) const constexpr
Definition at line 77 of file enum.hpp.
data() [1/2]
template<typename Enum, typename T> constexpr value_type* otto::util::enum_map< Enum, T >::data () constexpr noexcept
Definition at line 82 of file enum.hpp.
data() [2/2]
template<typename Enum, typename T> constexpr const value_type* otto::util::enum_map< Enum, T >::data () const constexpr noexcept
Definition at line 87 of file enum.hpp.
Member Data Documentation
_data
template<typename Enum, typename T> std::array<T, Enum::_size()> otto::util::enum_map< Enum, T >::_data
Definition at line 92 of file enum.hpp.
Referenced by otto::util::enum_map< ScreenEnum, std::function >::at(), otto::util::enum_map< ScreenEnum, std::function >::back(), otto::util::enum_map< ScreenEnum, std::function >::begin(), otto::util::enum_map< ScreenEnum, std::function >::data(), otto::util::enum_map< ScreenEnum, std::function >::end(), otto::util::enum_map< ScreenEnum, std::function >::front(), and otto::util::enum_map< ScreenEnum, std::function >::operator[]().
The documentation for this struct was generated from the following file:
/home/travis/build/topisani/OTTO/src/util/enum.hpp