OTTO: otto::core::audio::VoiceManager< N > Struct Template Reference
otto::core::audio::VoiceManager< N > Struct Template Reference
Detailed Description
template<int N>
struct otto::core::audio::VoiceManager< N >
Definition at line 89 of file voice_manager.hpp.
#include <voice_manager.hpp>
Public Member Functions
VoiceManager (props::properties_base &parent)
void process_before (audio::ProcessData< 0 > data)
void process_after (audio::ProcessData< 0 > data)
ui::Screen & envelope_screen () noexcept
ui::Screen & settings_screen () noexcept
Public Attributes
int last_voice
props::Properties< props::no_serialize > voices_props
std::array< VoiceProps, N > voices
EnvelopeProps envelope_props
SettingsProps settings_props
Constructor & Destructor Documentation
VoiceManager()
template<int N> otto::core::audio::VoiceManager< N >::VoiceManager (props::properties_base & parent)
Definition at line 100 of file voice_manager.hpp.
References std::deque< T >::push_back().
Member Function Documentation
process_before()
template<int N> void otto::core::audio::VoiceManager< N >::process_before (audio::ProcessData< 0 > data)
Definition at line 219 of file voice_manager.hpp.
References DLOGI, otto::core::midi::NoteEvent::key, otto::util::match(), otto::core::audio::ProcessData< 0 >::midi, otto::core::midi::note_freq(), and otto::core::midi::NoteEvent::velocity.
process_after()
template<int N> void otto::core::audio::VoiceManager< N >::process_after (audio::ProcessData< 0 > data)
Definition at line 242 of file voice_manager.hpp.
References otto::util::match(), and otto::core::audio::ProcessData< 0 >::midi.
envelope_screen()
template<int N> ui::Screen& otto::core::audio::VoiceManager< N >::envelope_screen () noexcept
Definition at line 115 of file voice_manager.hpp.
settings_screen()
template<int N> ui::Screen& otto::core::audio::VoiceManager< N >::settings_screen () noexcept
Definition at line 119 of file voice_manager.hpp.
Member Data Documentation
last_voice
template<int N> int otto::core::audio::VoiceManager< N >::last_voice
Definition at line 90 of file voice_manager.hpp.
voices_props
template<int N> props::Properties<props::no_serialize> otto::core::audio::VoiceManager< N >::voices_props
Definition at line 92 of file voice_manager.hpp.
voices
template<int N> std::array<VoiceProps, N> otto::core::audio::VoiceManager< N >::voices
Initial value:
= util::generate_array<N>(
      [this](auto n) { return VoiceProps(&voices_props, std::to_string(n)); })
Definition at line 94 of file voice_manager.hpp.
envelope_props
template<int N> EnvelopeProps otto::core::audio::VoiceManager< N >::envelope_props
Definition at line 97 of file voice_manager.hpp.
settings_props
template<int N> SettingsProps otto::core::audio::VoiceManager< N >::settings_props
Definition at line 98 of file voice_manager.hpp.
The documentation for this struct was generated from the following file:
/home/travis/build/topisani/OTTO/src/core/audio/voice_manager.hpp