OTTO: otto::util::bytes< len > Struct Template Reference
otto::util::bytes< len > Struct Template Reference
#include <bytefile.hpp>
Public Member Functions
bytes ()=default
bytes (const bytes &o)
bytes (const std::initializer_list< std::byte > bs)
bytes (const std::initializer_list< unsigned char > bs)
bytes (const char str[len+1])
template<std::size_t N = len, typename Num = int_n_bytes_u_t<N>>
bytes (Num d)
std::byte * begin ()
std::byte * end ()
const std::byte * begin () const
const std::byte * end () const
bool operator== (const bytes &rhs) const
bool operator== (const char *rhs) const
bool operator!= (const bytes &rhs) const
bool operator!= (const char *rhs) const
template<typename T >
T & cast ()
template<std::size_t N = len, typename Num = int_n_bytes_t<N>>
Num & as_i ()
template<std::size_t N = len, typename Num = int_n_bytes_u_t<N>>
Num & as_u ()
operator char * () const
std::string str () const
Static Public Member Functions
template<std::size_t N = len, typename Num = int_n_bytes_u_t<N>>
static bytes from_u (Num n)
template<std::size_t N = len, typename Num = int_n_bytes_t<N>>
static bytes from_i (Num n)
Public Attributes
std::byte data [len]
Detailed Description
template<std::size_t len>
struct otto::util::bytes< len >
Definition at line 15 of file bytefile.hpp.
Constructor & Destructor Documentation
bytes() [1/6]
template<std::size_t len> otto::util::bytes< len >::bytes () default
bytes() [2/6]
template<std::size_t len> otto::util::bytes< len >::bytes (const bytes< len > & o) inline
Definition at line 20 of file bytefile.hpp.
{
       std::copy(o.begin(), o.end(), data);
     }
bytes() [3/6]
template<std::size_t len> otto::util::bytes< len >::bytes (const std::initializer_list< std::byte > bs) inline
Definition at line 24 of file bytefile.hpp.
{
       data = bs;
     }
bytes() [4/6]
template<std::size_t len> otto::util::bytes< len >::bytes (const std::initializer_list< unsigned char > bs) inline
Definition at line 28 of file bytefile.hpp.
{
       std::transform(bs.begin(), bs.end(), begin(),
         [] (auto uc) {return std::byte(uc);});
     }
bytes() [5/6]
template<std::size_t len> otto::util::bytes< len >::bytes (const char str[len+1]) inline
Definition at line 33 of file bytefile.hpp.
{
       std::copy_n(str, len,
         reinterpret_cast<char*>(data));
     }
bytes() [6/6]
template<std::size_t len> template<std::size_t N = len, typename Num = int_n_bytes_u_t<N>> otto::util::bytes< len >::bytes (Num d) inline
Definition at line 39 of file bytefile.hpp.
                     {
       cast<Num>() = d;
     }
Member Function Documentation
as_i()
template<std::size_t len> template<std::size_t N = len, typename Num = int_n_bytes_t<N>> Num& otto::util::bytes< len >::as_i () inline
Definition at line 65 of file bytefile.hpp.
Referenced by otto::util::bytes< 4 >::from_i().
                   {
       return cast<Num>();
     }
as_u()
template<std::size_t len> template<std::size_t N = len, typename Num = int_n_bytes_u_t<N>> Num& otto::util::bytes< len >::as_u () inline
Definition at line 70 of file bytefile.hpp.
Referenced by otto::util::bytes< 4 >::from_u(), otto::util::ByteFile::Chunk::past_end(), otto::util::Header::read_fields(), otto::util::TRCKChunk::read_fields(), otto::util::WAVE_fmt::read_fields(), otto::util::SoundFile::read_file(), otto::util::ByteFile::Chunk::write(), and otto::util::WAVE_fmt::write_fields().
                   {
       return cast<Num>();
     }
begin() [1/2]
template<std::size_t len> std::byte* otto::util::bytes< len >::begin () inline
Definition at line 43 of file bytefile.hpp.
Referenced by otto::util::bytes< 4 >::bytes(), and otto::util::bytes< 4 >::operator==().
 {return data;}
begin() [2/2]
template<std::size_t len> const std::byte* otto::util::bytes< len >::begin () const inline
Definition at line 45 of file bytefile.hpp.
 {return data;}
cast()
template<std::size_t len> template<typename T > T& otto::util::bytes< len >::cast () inline
Definition at line 60 of file bytefile.hpp.
Referenced by otto::util::SoundFile::bytes_to_sample(), and otto::util::SoundFile::sample_to_bytes().
                 {
       return *reinterpret_cast<std::decay_t<T>*>(data);
     }
end() [1/2]
template<std::size_t len> std::byte* otto::util::bytes< len >::end () inline
Definition at line 44 of file bytefile.hpp.
Referenced by otto::util::bytes< 4 >::operator==().
 {return data + len;}
end() [2/2]
template<std::size_t len> const std::byte* otto::util::bytes< len >::end () const inline
Definition at line 46 of file bytefile.hpp.
 {return data + len;}
from_i()
template<std::size_t len> template<std::size_t N = len, typename Num = int_n_bytes_t<N>> static bytes otto::util::bytes< len >::from_i (Num n) inline static
Definition at line 91 of file bytefile.hpp.
{
       bytes ret;
       ret.as_i() = n;
       return ret;
     }
from_u()
template<std::size_t len> template<std::size_t N = len, typename Num = int_n_bytes_u_t<N>> static bytes otto::util::bytes< len >::from_u (Num n) inline static
Definition at line 84 of file bytefile.hpp.
{
       bytes ret;
       ret.as_u() = n;
       return ret;
     }
operator char *()
template<std::size_t len> otto::util::bytes< len >::operator char * () const inline explicit
Definition at line 74 of file bytefile.hpp.
{
       return (char*) data;
     }
operator!=() [1/2]
template<std::size_t len> bool otto::util::bytes< len >::operator!= (const bytes< len > & rhs) const inline
Definition at line 56 of file bytefile.hpp.
 {return !(*this == rhs);}
operator!=() [2/2]
template<std::size_t len> bool otto::util::bytes< len >::operator!= (const char * rhs) const inline
Definition at line 57 of file bytefile.hpp.
 {return !(*this == rhs);}
operator==() [1/2]
template<std::size_t len> bool otto::util::bytes< len >::operator== (const bytes< len > & rhs) const inline
Definition at line 48 of file bytefile.hpp.
{
       return std::equal(begin(), end(), rhs.begin());
     }
operator==() [2/2]
template<std::size_t len> bool otto::util::bytes< len >::operator== (const char * rhs) const inline
Definition at line 52 of file bytefile.hpp.
{
       return std::equal(begin(), end(), reinterpret_cast<const std::byte*>(rhs));
     }
str()
template<std::size_t len> std::string otto::util::bytes< len >::str () const inline
Definition at line 78 of file bytefile.hpp.
Referenced by otto::util::bytes< 4 >::bytes(), and otto::util::SoundFile::read_file().
{
       return {(char*)data, len};
     }
Member Data Documentation
data
template<std::size_t len> std::byte otto::util::bytes< len >::data[len]
Definition at line 16 of file bytefile.hpp.
Referenced by otto::util::bytes< 4 >::begin(), otto::util::bytes< 4 >::bytes(), otto::util::bytes< 4 >::cast(), otto::util::bytes< 4 >::end(), otto::util::bytes< 4 >::operator char *(), otto::util::bytes< 4 >::str(), and otto::util::ByteFile::write_bytes().
The documentation for this struct was generated from the following file:
/home/topisani/dev/OTTO/src/util/bytefile.hpp