OTTO: otto::services::ClockManager Struct Reference
otto::services::ClockManager Struct Reference
Detailed Description
The service managing the clock.
The clock can be started or stopped by an internal or external source, and should be used by the sequencer, the looper, and arpeggiators.
Definition at line 17 of file clock_manager.hpp.
#include <clock_manager.hpp>
Public Types
using ClockCounter = core::clock::ClockCounter
using ClockRange = core::clock::ClockRange
using Time = core::clock::Time
Public Member Functions
ClockManager () noexcept
float bpm () const noexcept
int samples_pr_beat () const noexcept
bool running () const noexcept
void set_bpm (float bpm) noexcept
void start () noexcept
void stop (bool reset=true) noexcept
void reset () noexcept
ClockRange step_frames (int nframes)
Public Member Functions inherited from otto::core::Service
Service ()=default
virtual ~Service ()=default
Service (const Service &)=delete
Service (Service &&)=delete
auto operator= (const Service &)=delete
auto operator= (Service &&)=delete
Static Public Member Functions
static std::unique_ptr< ClockManager > create_default () noexcept
static ClockManager & current () noexcept
Member Typedef Documentation
ClockCounter
using otto::services::ClockManager::ClockCounter = core::clock::ClockCounter
Definition at line 18 of file clock_manager.hpp.
ClockRange
using otto::services::ClockManager::ClockRange = core::clock::ClockRange
Definition at line 19 of file clock_manager.hpp.
Time
using otto::services::ClockManager::Time = core::clock::Time
Definition at line 20 of file clock_manager.hpp.
Constructor & Destructor Documentation
ClockManager()
otto::services::ClockManager::ClockManager () noexcept
Member Function Documentation
create_default()
static std::unique_ptr<ClockManager> otto::services::ClockManager::create_default () static noexcept
Definition at line 26 of file clock_manager.hpp.
Referenced by otto::services::test::make_dummy_application(), and otto::services::test::make_dummy_application_default_engines().
current()
static ClockManager& otto::services::ClockManager::current () static noexcept
Definition at line 31 of file clock_manager.hpp.
References otto::services::Application::clock_manager, and otto::services::Application::current().
bpm()
float otto::services::ClockManager::bpm () const noexcept
samples_pr_beat()
int otto::services::ClockManager::samples_pr_beat () const noexcept
running()
bool otto::services::ClockManager::running () const noexcept
set_bpm()
void otto::services::ClockManager::set_bpm (float bpm) noexcept
start()
void otto::services::ClockManager::start () noexcept
stop()
void otto::services::ClockManager::stop (bool reset = true) noexcept
reset()
void otto::services::ClockManager::reset () noexcept
step_frames()
ClockRange otto::services::ClockManager::step_frames (int nframes)
The documentation for this struct was generated from the following file:
/home/travis/build/topisani/OTTO/src/services/clock_manager.hpp