OTTO: otto::core::audio::AudioBufferPool Struct Reference
otto::core::audio::AudioBufferPool Struct Reference
#include <processor.hpp>
Public Member Functions
AudioBufferPool (std::size_t buffer_size)
AudioBufferHandle allocate ()
template<std::size_t N>
MultiChannelAudioBufferHandle< N > allocate_multi ()
AudioBufferHandle allocate_clear ()
template<std::size_t N>
MultiChannelAudioBufferHandle< N > allocate_multi_clear ()
void reserve (std::size_t n)
Detailed Description
Definition at line 291 of file processor.hpp.
Constructor & Destructor Documentation
AudioBufferPool()
otto::core::audio::AudioBufferPool::AudioBufferPool (std::size_t buffer_size) inline
Definition at line 292 of file processor.hpp.
References reserve().
                                            : buffer_size(buffer_size)
     {
       // For now this is hardcoded, which is nice, cause we notice if we suddenly are using too many
       // buffers
       reserve(4);
     }
Member Function Documentation
allocate()
AudioBufferHandle otto::core::audio::AudioBufferPool::allocate () inline
Definition at line 299 of file processor.hpp.
References reserve().
Referenced by allocate_clear(), and allocate_multi().
     {
       for (int i = 0; i < reference_counts.size(); i++) {
         if (reference_counts[i] < 1) {
           if (i > _max_val) {
             LOGI("Using {} buffers", i + 1);
             _max_val = i;
           }
           reference_counts[i] = 0;
           int index = i * buffer_size;
           return {data.get() + index, buffer_size, reference_counts[i]};
         }
       }
       DLOGI("Allocating a new audio buffer. this pool now has {} buffers", _avaliable_buffers);
       reserve(_avaliable_buffers + 1);
       return allocate();
     }
allocate_clear()
AudioBufferHandle otto::core::audio::AudioBufferPool::allocate_clear () inline
Definition at line 324 of file processor.hpp.
References allocate().
Referenced by allocate_multi_clear().
     {
       auto res = allocate();
       res.clear();
       return res;
     }
allocate_multi()
template<std::size_t N> MultiChannelAudioBufferHandle<N> otto::core::audio::AudioBufferPool::allocate_multi () inline
Definition at line 318 of file processor.hpp.
References allocate().
Referenced by otto::service::engines::process(), and otto::core::audio::FaustWrapper< 0, 1 >::process().
     {
       if constexpr (N == 1) return allocate();
       if constexpr (N == 2) return {allocate(), allocate()};
     }
allocate_multi_clear()
template<std::size_t N> MultiChannelAudioBufferHandle<N> otto::core::audio::AudioBufferPool::allocate_multi_clear () inline
Definition at line 332 of file processor.hpp.
References allocate_clear().
     {
       if constexpr (N == 1) return allocate_clear();
       if constexpr (N == 2) return {allocate_clear(), allocate_clear()};
     }
reserve()
void otto::core::audio::AudioBufferPool::reserve (std::size_t n) inline
Definition at line 338 of file processor.hpp.
Referenced by allocate(), and AudioBufferPool().
     {
       if (_avaliable_buffers > 0) {
         LOGF("Requested {} buffers. only {} avaliable", n, _avaliable_buffers);
         return;
       }
       if (n > _avaliable_buffers) {
         data = std::make_unique<float[]>(n * buffer_size);
         _avaliable_buffers = n;
         reference_counts.resize(_avaliable_buffers, 0);
       }
     }
The documentation for this struct was generated from the following file:
/home/topisani/dev/OTTO/src/core/audio/processor.hpp