OTTO: otto::engines::ExternalScreen Struct Reference
otto::engines::ExternalScreen Struct Reference
Public Member Functions
void draw (Canvas &ctx) override
void rotary (RotaryEvent e) override
Public Member Functions inherited from otto::core::engines::EngineScreen< External >
EngineScreen (External *engine)
virtual ~EngineScreen ()
Public Member Functions inherited from otto::core::ui::Screen
Screen ()
virtual ~Screen ()
virtual bool keypress (Key)
virtual bool keyrelease (Key)
virtual void rotary (RotaryEvent)
This should be used for handling rotary events.
virtual void on_show ()
Run by MainUI when switching to this screen.
virtual void on_hide ()
Run by MainUI when switching to another screen.
Public Member Functions inherited from otto::core::ui::vg::Drawable
Drawable ()=default
virtual ~Drawable ()=default
virtual void draw (Canvas &ctx)=0
Additional Inherited Members
Protected Attributes inherited from otto::core::engines::EngineScreen< External >
External & engine
Detailed Description
Definition at line 14 of file external.cpp.
Member Function Documentation
draw()
void otto::engines::ExternalScreen::draw (Canvas & ctx) override
Definition at line 43 of file external.cpp.
References otto::core::engines::EngineScreen< External >::engine, otto::core::ui::vg::Canvas::fillStyle(), otto::core::ui::vg::Canvas::fillText(), otto::core::ui::vg::Canvas::font(), otto::core::ui::vg::Canvas::lineTo(), otto::core::ui::vg::Canvas::moveTo(), and otto::core::ui::vg::Canvas::stroke().
   {
     using namespace ui::vg;
     auto& props = engine.props;
     ctx.font(Fonts::Bold, 40);
     ctx.beginPath();
     ctx.fillStyle(Colours::Blue);
     ctx.textAlign(HorizontalAlign::Center, VerticalAlign::Baseline);
     ctx.fillText("EXTERNAL IN", {160, 60});
     ctx.font(Fonts::Bold, 100);
     ctx.beginPath();
     ctx.fillStyle(Colours::Blue);
     ctx.textAlign(HorizontalAlign::Center, VerticalAlign::Top);
     ctx.fillText(fmt::format("{}", (int) std::round(props.gain* 100.0)), {160, 70});
     ctx.beginPath();
     ctx.moveTo({40, 200});
     ctx.lineTo({40 + 240 * engine.graph.average, 200});
     ctx.lineWidth(6);
     ctx.stroke(Colours::White);
     engine.graph.clear();
   }
rotary()
void otto::engines::ExternalScreen::rotary (RotaryEvent e) override
Definition at line 37 of file external.cpp.
References otto::core::engines::EngineScreen< External >::engine.
   {
     auto& props = engine.props;
     props.gain.step(ev.clicks);
   }
The documentation for this struct was generated from the following file:
/home/topisani/dev/OTTO/src/engines/synths/external/external.cpp