OTTO: otto::util::shared_ptr_vec< T > Struct Template Reference
otto::util::shared_ptr_vec< T > Struct Template Reference
Detailed Description
template<typename T>
struct otto::util::shared_ptr_vec< T >
A convenience wrapper for std::vector<std::shared_ptr<T>>
Definition at line 312 of file ptr_vec.hpp.
#include <ptr_vec.hpp>
Public Types
using value_type = T
using iterator = double_iterator< typename decltype(data_)::iterator >
using const_iterator = double_iterator< typename decltype(data_)::const_iterator >
using reverse_iterator = double_iterator< typename decltype(data_)::reverse_iterator >
using const_reverse_iterator = double_iterator< typename decltype(data_)::const_reverse_iterator >
Public Member Functions
value_type & push_back (const value_type &v)
value_type & push_back (value_type &&v)
value_type & push_back (std::shared_ptr< value_type > ptr)
template<typename... Args>
value_type & emplace_back (Args &&... args)
std::shared_ptr< value_type > erase (const value_type &v)
std::size_t size () const noexcept
bool empty () const noexcept
std::size_t capacity () const noexcept
std::size_t max_size () const noexcept
void reserve (std::size_t new_cap)
void shrink_to_fit ()
value_type & operator[] (std::size_t n)
const value_type & operator[] (std::size_t n) const
value_type & at (std::size_t n)
const value_type & at (std::size_t n) const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
value_type & front ()
value_type & back ()
const value_type & front () const
const value_type & back () const
std::vector< std::shared_ptr< value_type > > & underlying ()
Member Typedef Documentation
value_type
template<typename T> using otto::util::shared_ptr_vec< T >::value_type = T
Definition at line 313 of file ptr_vec.hpp.
iterator
template<typename T> using otto::util::shared_ptr_vec< T >::iterator = double_iterator<typename decltype(data_)::iterator>
Definition at line 319 of file ptr_vec.hpp.
const_iterator
template<typename T> using otto::util::shared_ptr_vec< T >::const_iterator = double_iterator<typename decltype(data_)::const_iterator>
Definition at line 320 of file ptr_vec.hpp.
reverse_iterator
template<typename T> using otto::util::shared_ptr_vec< T >::reverse_iterator = double_iterator<typename decltype(data_)::reverse_iterator>
Definition at line 322 of file ptr_vec.hpp.
const_reverse_iterator
template<typename T> using otto::util::shared_ptr_vec< T >::const_reverse_iterator = double_iterator<typename decltype(data_)::const_reverse_iterator>
Definition at line 323 of file ptr_vec.hpp.
Member Function Documentation
push_back() [1/3]
template<typename T> value_type& otto::util::shared_ptr_vec< T >::push_back (const value_type & v)
Definition at line 325 of file ptr_vec.hpp.
References std::move(), and std::vector< T >::push_back().
Referenced by otto::util::shared_ptr_vec< T >::emplace_back().
push_back() [2/3]
template<typename T> value_type& otto::util::shared_ptr_vec< T >::push_back (value_type && v)
Definition at line 333 of file ptr_vec.hpp.
References std::move(), and std::vector< T >::push_back().
push_back() [3/3]
template<typename T> value_type& otto::util::shared_ptr_vec< T >::push_back (std::shared_ptr< value_type > ptr)
Definition at line 341 of file ptr_vec.hpp.
References std::shared_ptr< T >::get(), std::move(), and std::vector< T >::push_back().
emplace_back()
template<typename T> template<typename... Args> value_type& otto::util::shared_ptr_vec< T >::emplace_back (Args &&... args)
Definition at line 349 of file ptr_vec.hpp.
References otto::util::shared_ptr_vec< T >::push_back().
erase()
template<typename T> std::shared_ptr<value_type> otto::util::shared_ptr_vec< T >::erase (const value_type & v)
Definition at line 354 of file ptr_vec.hpp.
References std::vector< T >::begin(), std::vector< T >::end(), std::vector< T >::erase(), std::find_if(), and std::move().
Referenced by otto::util::erase().
size()
template<typename T> std::size_t otto::util::shared_ptr_vec< T >::size () const noexcept
Definition at line 365 of file ptr_vec.hpp.
References std::vector< T >::size().
empty()
template<typename T> bool otto::util::shared_ptr_vec< T >::empty () const noexcept
Definition at line 370 of file ptr_vec.hpp.
References std::vector< T >::empty().
capacity()
template<typename T> std::size_t otto::util::shared_ptr_vec< T >::capacity () const noexcept
Definition at line 375 of file ptr_vec.hpp.
References std::vector< T >::capacity().
max_size()
template<typename T> std::size_t otto::util::shared_ptr_vec< T >::max_size () const noexcept
Definition at line 380 of file ptr_vec.hpp.
References std::vector< T >::max_size().
reserve()
template<typename T> void otto::util::shared_ptr_vec< T >::reserve (std::size_t new_cap)
Definition at line 385 of file ptr_vec.hpp.
References std::vector< T >::reserve().
shrink_to_fit()
template<typename T> void otto::util::shared_ptr_vec< T >::shrink_to_fit ()
Definition at line 390 of file ptr_vec.hpp.
References std::vector< T >::shrink_to_fit().
operator[]() [1/2]
template<typename T> value_type& otto::util::shared_ptr_vec< T >::operator[] (std::size_t n)
Definition at line 395 of file ptr_vec.hpp.
operator[]() [2/2]
template<typename T> const value_type& otto::util::shared_ptr_vec< T >::operator[] (std::size_t n) const
Definition at line 400 of file ptr_vec.hpp.
at() [1/2]
template<typename T> value_type& otto::util::shared_ptr_vec< T >::at (std::size_t n)
Definition at line 405 of file ptr_vec.hpp.
References std::vector< T >::at().
at() [2/2]
template<typename T> const value_type& otto::util::shared_ptr_vec< T >::at (std::size_t n) const
Definition at line 410 of file ptr_vec.hpp.
References std::vector< T >::at().
begin() [1/2]
template<typename T> iterator otto::util::shared_ptr_vec< T >::begin ()
Definition at line 415 of file ptr_vec.hpp.
References std::vector< T >::begin().
end() [1/2]
template<typename T> iterator otto::util::shared_ptr_vec< T >::end ()
Definition at line 419 of file ptr_vec.hpp.
References std::vector< T >::end().
begin() [2/2]
template<typename T> const_iterator otto::util::shared_ptr_vec< T >::begin () const
Definition at line 423 of file ptr_vec.hpp.
References std::vector< T >::begin().
end() [2/2]
template<typename T> const_iterator otto::util::shared_ptr_vec< T >::end () const
Definition at line 427 of file ptr_vec.hpp.
References std::vector< T >::end().
rbegin() [1/2]
template<typename T> reverse_iterator otto::util::shared_ptr_vec< T >::rbegin ()
Definition at line 432 of file ptr_vec.hpp.
References std::vector< T >::rbegin().
rend() [1/2]
template<typename T> reverse_iterator otto::util::shared_ptr_vec< T >::rend ()
Definition at line 436 of file ptr_vec.hpp.
References std::vector< T >::rend().
rbegin() [2/2]
template<typename T> const_reverse_iterator otto::util::shared_ptr_vec< T >::rbegin () const
Definition at line 440 of file ptr_vec.hpp.
References std::vector< T >::rbegin().
rend() [2/2]
template<typename T> const_reverse_iterator otto::util::shared_ptr_vec< T >::rend () const
Definition at line 444 of file ptr_vec.hpp.
References std::vector< T >::rend().
front() [1/2]
template<typename T> value_type& otto::util::shared_ptr_vec< T >::front ()
Definition at line 449 of file ptr_vec.hpp.
References std::vector< T >::front().
back() [1/2]
template<typename T> value_type& otto::util::shared_ptr_vec< T >::back ()
Definition at line 454 of file ptr_vec.hpp.
References std::vector< T >::back().
front() [2/2]
template<typename T> const value_type& otto::util::shared_ptr_vec< T >::front () const
Definition at line 459 of file ptr_vec.hpp.
References std::vector< T >::front().
back() [2/2]
template<typename T> const value_type& otto::util::shared_ptr_vec< T >::back () const
Definition at line 464 of file ptr_vec.hpp.
References std::vector< T >::back().
underlying()
template<typename T> std::vector<std::shared_ptr<value_type> >& otto::util::shared_ptr_vec< T >::underlying ()
Definition at line 469 of file ptr_vec.hpp.
The documentation for this struct was generated from the following file:
/home/travis/build/topisani/OTTO/src/util/ptr_vec.hpp