OTTO: otto::core::ui::vg::icons::Arrow Struct Reference
otto::core::ui::vg::icons::Arrow Struct Reference
A simple arrow.
#include <icons.hpp>
Public Types
enum Direction { Up, Down, Left, Right }
Public Member Functions
void draw (Canvas &) override
Public Member Functions inherited from otto::core::ui::vg::Drawable
Drawable ()=default
virtual ~Drawable ()=default
Public Attributes
Direction dir = Right
bool stopped = false
Add stop line ->|.
bool looping = false
Loop arrow - CW for Up/Right, CCW for Down/Left.
float headRatio = 0.25
headLength/arrowLength
Public Attributes inherited from otto::core::ui::vg::icons::Icon
Size size
Colour colour
float lineWidth = 2
Detailed Description
A simple arrow.
Definition at line 16 of file icons.hpp.
Member Enumeration Documentation
Direction
enum otto::core::ui::vg::icons::Arrow::Direction
Enumerator
Up
Down
Left
Right
Definition at line 18 of file icons.hpp.
                    {
       Up, Down, Left, Right
     };
Member Function Documentation
draw()
void otto::core::ui::vg::icons::Arrow::draw (Canvas & ctx) override virtual
Draw this widget to the context.
Called from the parent's draw method.
Parameters
ctx the canvas to draw on.
Reimplemented from otto::core::ui::vg::icons::Icon.
Definition at line 7 of file icons.cpp.
References otto::core::ui::vg::Canvas::arcTo(), otto::core::ui::vg::Size::center(), otto::core::ui::vg::icons::Icon::colour, dir, Down, otto::core::ui::vg::Canvas::fill(), otto::core::ui::vg::Canvas::fillStyle(), otto::core::ui::vg::Size::h, headRatio, Left, otto::core::ui::vg::Canvas::lineTo(), otto::core::ui::vg::icons::Icon::lineWidth, looping, otto::core::ui::vg::Canvas::moveTo(), Right, otto::core::ui::vg::Canvas::rotateAround(), otto::core::ui::vg::icons::Icon::size, stopped, otto::core::ui::vg::Canvas::stroke(), otto::core::ui::vg::Canvas::strokeStyle(), otto::core::ui::vg::Size::swapWH(), otto::core::ui::vg::Canvas::translate(), Up, otto::core::ui::vg::Size::w, and otto::core::ui::vg::Point::x.
{
     ctx.save();
     ctx.lineJoin(Canvas::LineJoin::ROUND);
     ctx.lineCap(Canvas::LineCap::ROUND);
     ctx.lineWidth(lineWidth);
     if (!looping) {
       float s;
       Size rsize;
       switch (dir) {
       case Up:
         s = size.h;
         rsize = size;
         break;
       case Right:
         s = size.w;
         rsize = size.swapWH();
         ctx.rotateAround(0.5 * M_PI, Size(s,s).center());
         break;
       case Down:
         s = size.h;
         rsize = size;
         ctx.rotateAround(1.0 * M_PI, size.center());
         break;
       case Left:
         s = size.w;
         rsize = size.swapWH();
         ctx.rotateAround(0.5 * M_PI, Size(s,s).center());
         ctx.rotateAround(1.0 * M_PI, rsize.center());
       }
       Point start = {rsize.w / 2.f, rsize.h};
       Point end = {rsize.w / 2.f, 0};
       Point cp1 = {
         float(rsize.w - rsize.h * headRatio * M_SQRT2) / 2.f,
         float(rsize.h * headRatio)
       };
       Point cp2 = {
         float(rsize.w + rsize.h * headRatio * M_SQRT2) / 2.f,
         float(rsize.h * headRatio)
       };
       ctx.beginPath();
       ctx.moveTo(start);
       ctx.lineTo(end);
       ctx.lineTo(cp1);
       ctx.lineTo(cp2);
       ctx.lineTo(end);
       if (stopped) {
         ctx.moveTo(cp1.x, end.y);
         ctx.lineTo(cp2.x, end.y);
       }
       ctx.strokeStyle(colour);
       ctx.fillStyle(colour);
       ctx.stroke();
       ctx.fill();
     } else {
       // Draw looping arrow.
       const float scale = std::min(size.w / 12, size.h / 6);
       ctx.translate(size.w / 2 - 6 * scale, size.h / 2 - 3 * scale);
       const float r   = 3 * scale;
       Point cp1 = Point{5, 0} * scale;
       const Point cp2 = Point{3, 0} * scale;
       const Point ap1 = Point{0, 0} * scale;
       const Point cp3 = Point{0, 3} * scale;
       const Point ap2 = Point{0, 6} * scale;
       const Point cp4 = Point{3, 6} * scale;
       const Point cp5 = Point{9, 6} * scale;
       const Point ap3 = Point{12, 6} * scale;
       const Point cp6 = Point{12, 3} * scale;
       const Point ap4 = Point{12, 0} * scale;
       const Point cp7 = Point{9, 0} * scale;
       Point cp8 = Point{7, 0} * scale;
       Point hp1, hp2, hp3;
       switch (dir) {
       case Up:
       case Right:
         hp1 = cp1 + Point(1, 0) * scale;
         hp2 = hp1 - Point(scale * 2, scale * 2 * M_SQRT2 / 2.f);
         hp3 = hp1 - Point(scale * 2, -scale * 2 * M_SQRT2 / 2.f);
         cp8 = Point{8, 0} * scale;
         break;
       case Down:
       case Left:
         hp1 = cp8 - Point(1, 0) * scale;
         hp2 = hp1 + Point(scale * 2, scale * 2 * M_SQRT2 / 2.f);
         hp3 = hp1 + Point(scale * 2, -scale * 2 * M_SQRT2 / 2.f);
         cp1 = Point{4, 0} * scale;
         break;
       }
       ctx.beginPath();
       ctx.moveTo(cp1);
       ctx.lineTo(cp2);
       ctx.arcTo(ap1, cp3, r);
       ctx.arcTo(ap2, cp4, r);
       ctx.lineTo(cp5);
       ctx.arcTo(ap3, cp6, r);
       ctx.arcTo(ap4, cp7, r);
       ctx.lineTo(cp8);
       ctx.strokeStyle(colour);
       ctx.stroke();
       // Arrow head
       ctx.beginPath();
       ctx.moveTo(hp1);
       ctx.lineTo(hp2);
       ctx.lineTo(hp3);
       ctx.lineTo(hp1);
       ctx.fill(colour);
       ctx.stroke(colour);
     }
     ctx.restore();
   }
Member Data Documentation
dir
Direction otto::core::ui::vg::icons::Arrow::dir = Right
Definition at line 22 of file icons.hpp.
Referenced by draw().
headRatio
float otto::core::ui::vg::icons::Arrow::headRatio = 0.25
headLength/arrowLength
Definition at line 28 of file icons.hpp.
Referenced by draw().
looping
bool otto::core::ui::vg::icons::Arrow::looping = false
Loop arrow - CW for Up/Right, CCW for Down/Left.
Definition at line 26 of file icons.hpp.
Referenced by draw().
stopped
bool otto::core::ui::vg::icons::Arrow::stopped = false
Add stop line ->|.
Definition at line 24 of file icons.hpp.
Referenced by draw().
The documentation for this struct was generated from the following files:
/home/topisani/dev/OTTO/src/core/ui/icons.hpp
/home/topisani/dev/OTTO/src/core/ui/icons.cpp