OTTO: otto::core::audio::AudioBufferHandle Struct Reference
otto::core::audio::AudioBufferHandle Struct Reference
A handle to an audio buffer.
#include <processor.hpp>
Public Types
using iterator = float *
using const_iterator = const float *
Public Member Functions
AudioBufferHandle (float *data, std::size_t length, int &reference_count)
~AudioBufferHandle ()
AudioBufferHandle (AudioBufferHandle &&rhs)
AudioBufferHandle (const AudioBufferHandle &rhs)
int reference_count () const
float * data () const
std::size_t size () const
iterator begin ()
iterator end ()
iterator begin () const
iterator end () const
float & operator[] (std::size_t i)
const float & operator[] (std::size_t i) const
void release ()
void clear ()
AudioBufferHandle slice (int idx, int length=-1)
float * data ()
Detailed Description
A handle to an audio buffer.
Definition at line 45 of file processor.hpp.
Member Typedef Documentation
const_iterator
using otto::core::audio::AudioBufferHandle::const_iterator = const float*
Definition at line 47 of file processor.hpp.
iterator
using otto::core::audio::AudioBufferHandle::iterator = float*
Definition at line 46 of file processor.hpp.
Constructor & Destructor Documentation
AudioBufferHandle() [1/3]
otto::core::audio::AudioBufferHandle::AudioBufferHandle (float * data, std::size_t length, int & reference_count) inline
Definition at line 49 of file processor.hpp.
       : _data(data), _length(length), _reference_count(&reference_count)
     {
       (*_reference_count)++;
     }
~AudioBufferHandle()
otto::core::audio::AudioBufferHandle::~AudioBufferHandle () inline
Definition at line 55 of file processor.hpp.
     {
       if (_reference_count) (*_reference_count)--;
     };
AudioBufferHandle() [2/3]
otto::core::audio::AudioBufferHandle::AudioBufferHandle (AudioBufferHandle && rhs) inline
Definition at line 60 of file processor.hpp.
       : _data(rhs._data), _length(rhs._length), _reference_count(rhs._reference_count)
     {
       rhs._data = nullptr;
       rhs._reference_count = nullptr;
     }
AudioBufferHandle() [3/3]
otto::core::audio::AudioBufferHandle::AudioBufferHandle (const AudioBufferHandle & rhs) inline
Definition at line 67 of file processor.hpp.
       : _data(rhs._data), _length(rhs._length), _reference_count(rhs._reference_count)
     {
       (*_reference_count)++;
     }
Member Function Documentation
begin() [1/2]
iterator otto::core::audio::AudioBufferHandle::begin () inline
Definition at line 88 of file processor.hpp.
Referenced by clear().
     {
       return _data;
     }
begin() [2/2]
iterator otto::core::audio::AudioBufferHandle::begin () const inline
Definition at line 96 of file processor.hpp.
     {
       return _data;
     }
clear()
void otto::core::audio::AudioBufferHandle::clear () inline
Definition at line 122 of file processor.hpp.
References begin(), and end().
     {
       std::fill(begin(), end(), 0);
     }
data() [1/2]
float* otto::core::audio::AudioBufferHandle::data () const inline
Definition at line 78 of file processor.hpp.
     {
       return _data;
     }
data() [2/2]
float* otto::core::audio::AudioBufferHandle::data () inline
Definition at line 140 of file processor.hpp.
     {
       return _data;
     }
end() [1/2]
iterator otto::core::audio::AudioBufferHandle::end () inline
Definition at line 92 of file processor.hpp.
Referenced by clear().
     {
       return _data + _length;
     }
end() [2/2]
iterator otto::core::audio::AudioBufferHandle::end () const inline
Definition at line 100 of file processor.hpp.
     {
       return _data + _length;
     }
operator[]() [1/2]
float& otto::core::audio::AudioBufferHandle::operator[] (std::size_t i) inline
Definition at line 105 of file processor.hpp.
     {
       return _data[i];
     }
operator[]() [2/2]
const float& otto::core::audio::AudioBufferHandle::operator[] (std::size_t i) const inline
Definition at line 110 of file processor.hpp.
     {
       return _data[i];
     }
reference_count()
int otto::core::audio::AudioBufferHandle::reference_count () const inline
Definition at line 73 of file processor.hpp.
     {
       return *_reference_count;
     }
release()
void otto::core::audio::AudioBufferHandle::release () inline
Definition at line 115 of file processor.hpp.
     {
       (*_reference_count)--;
       _reference_count = nullptr;
       _data = nullptr;
     }
size()
std::size_t otto::core::audio::AudioBufferHandle::size () const inline
Definition at line 83 of file processor.hpp.
     {
       return _length;
     }
slice()
AudioBufferHandle otto::core::audio::AudioBufferHandle::slice (int idx, int length = -1) inline
Get only a slice of the audio.
Parameters
idx The index to start from
length The number of frames to keep in the slice If length is negative, nframes - idx will be used parameter idx shall be in the range [0, _length), and length shall be in range [0, nframes - idx]
Definition at line 134 of file processor.hpp.
     {
       length = length < 0 ? _length - idx : length;
       return {_data + idx, length, *_reference_count};
     }
The documentation for this struct was generated from the following file:
/home/topisani/dev/OTTO/src/core/audio/processor.hpp