OTTO: otto::core::engine::EngineDispatcher< ET, Engines > Struct Template Reference
otto::core::engine::EngineDispatcher< ET, Engines > Struct Template Reference final
Detailed Description
template<EngineType ET, typename... Engines>
struct otto::core::engine::EngineDispatcher< ET, Engines >
Owns engines of type ET, and dispatches to a selected one of them.
Definition at line 30 of file engine_dispatcher.hpp.
#include <engine_dispatcher.hpp>
Public Types
enum ErrorCode { ErrorCode::none = 0, ErrorCode::engine_not_found, ErrorCode::type_mismatch }
using exception = util::as_exception< ErrorCode >
using ITypedEngine = engine::ITypedEngine< ET >
using variant = util::variant_w_base< ITypedEngine, Engines... >
using DataMap = foonathan::array::flat_map< util::string_ref, nlohmann::json >
Public Member Functions
EngineDispatcher (bool allow_off)
void init ()
Construct all registered engines.
ITypedEngine & current () noexcept override
Access the currently selected engine.
const ITypedEngine & current () const noexcept override
int current_idx () const noexcept override
ITypedEngine const * operator-> () const noexcept
Access the currently selected engine.
ITypedEngine * operator-> () noexcept
Access the currently selected engine.
ITypedEngine & select (util::string_ref name) override
Select engine by name.
ITypedEngine & select (int index) override
Select engine by index.
std::vector< util::string_ref > make_name_list () const override
ui::Screen & selector_screen () noexcept
Access the screen used to select engines/presets.
const DataMap & data_of_engines () const noexcept
nlohmann::json to_json () const
void from_json (const nlohmann::json &)
Public Member Functions inherited from otto::core::engine::IEngineDispatcher
IEngineDispatcher (bool allow_off) noexcept
virtual ~IEngineDispatcher ()=default
Static Public Attributes
static constexpr const EngineType engine_type = ET
Additional Inherited Members
Public Attributes inherited from otto::core::engine::IEngineDispatcher
const bool allow_off = false
Is the engine allowed to be in an "OFF" state?
Member Typedef Documentation
exception
template<EngineType ET, typename... Engines> using otto::core::engine::EngineDispatcher< ET, Engines >::exception = util::as_exception<ErrorCode>
Definition at line 33 of file engine_dispatcher.hpp.
ITypedEngine
template<EngineType ET, typename... Engines> using otto::core::engine::EngineDispatcher< ET, Engines >::ITypedEngine = engine::ITypedEngine<ET>
Definition at line 36 of file engine_dispatcher.hpp.
variant
template<EngineType ET, typename... Engines> using otto::core::engine::EngineDispatcher< ET, Engines >::variant = util::variant_w_base<ITypedEngine, Engines...>
Definition at line 37 of file engine_dispatcher.hpp.
DataMap
template<EngineType ET, typename... Engines> using otto::core::engine::EngineDispatcher< ET, Engines >::DataMap = foonathan::array::flat_map<util::string_ref, nlohmann::json>
Definition at line 38 of file engine_dispatcher.hpp.
Member Enumeration Documentation
ErrorCode
template<EngineType ET, typename... Engines> enum otto::core::engine::EngineDispatcher::ErrorCode strong
Enumerator
none
engine_not_found
type_mismatch
Definition at line 31 of file engine_dispatcher.hpp.
Constructor & Destructor Documentation
EngineDispatcher()
template<EngineType ET, typename... Engines> otto::core::engine::EngineDispatcher< ET, Engines >::EngineDispatcher (bool allow_off)
Definition at line 41 of file engine_dispatcher.hpp.
Member Function Documentation
init()
template<EngineType ET, typename... Egs> void otto::core::engine::EngineDispatcher< ET, Egs >::init ()
Construct all registered engines.
Only call this after all engines are registered
Definition at line 18 of file engine_dispatcher.inl.
current() [1/2]
template<EngineType ET, typename... Egs> ITypedEngine< ET > & otto::core::engine::EngineDispatcher< ET, Egs >::current () override virtual noexcept
Access the currently selected engine.
Implements otto::core::engine::IEngineDispatcher.
Definition at line 24 of file engine_dispatcher.inl.
current() [2/2]
template<EngineType ET, typename... Egs> const ITypedEngine< ET > & otto::core::engine::EngineDispatcher< ET, Egs >::current () const override virtual noexcept
Implements otto::core::engine::IEngineDispatcher.
Definition at line 37 of file engine_dispatcher.inl.
current_idx()
template<EngineType ET, typename... Egs> int otto::core::engine::EngineDispatcher< ET, Egs >::current_idx () const override virtual noexcept
Implements otto::core::engine::IEngineDispatcher.
Definition at line 30 of file engine_dispatcher.inl.
operator->() [1/2]
template<EngineType ET, typename... Egs> const ITypedEngine< ET > * otto::core::engine::EngineDispatcher< ET, Egs >::operator-> () const noexcept
Access the currently selected engine.
Definition at line 50 of file engine_dispatcher.inl.
operator->() [2/2]
template<EngineType ET, typename... Egs> ITypedEngine< ET > * otto::core::engine::EngineDispatcher< ET, Egs >::operator-> () noexcept
Access the currently selected engine.
Definition at line 44 of file engine_dispatcher.inl.
select() [1/2]
template<EngineType ET, typename... Egs> ITypedEngine< ET > & otto::core::engine::EngineDispatcher< ET, Egs >::select (util::string_ref name) override virtual
Select engine by name.
\effects Find engine with name name, and select(engine)
Exceptions
<tt>util::exception</tt> when no matching engine was found
Implements otto::core::engine::IEngineDispatcher.
Definition at line 56 of file engine_dispatcher.inl.
References otto::meta::for_each(), LOGE, and otto::util::to_lowercase().
select() [2/2]
template<EngineType ET, typename... Egs> ITypedEngine< ET > & otto::core::engine::EngineDispatcher< ET, Egs >::select (int index) override virtual
Select engine by index.
If index is < 0, and allow_off, select the null engine.
Exceptions
<tt>util::exception</tt> when index is out of bounds
Implements otto::core::engine::IEngineDispatcher.
Definition at line 84 of file engine_dispatcher.inl.
References otto::meta::for_each(), and LOGE.
make_name_list()
template<EngineType ET, typename... Egs> std::vector< util::string_ref > otto::core::engine::EngineDispatcher< ET, Egs >::make_name_list () const override virtual
Implements otto::core::engine::IEngineDispatcher.
Definition at line 113 of file engine_dispatcher.inl.
References std::vector< T >::emplace_back(), otto::meta::for_each(), and std::vector< T >::reserve().
selector_screen()
template<EngineType ET, typename... Egs> ui::Screen & otto::core::engine::EngineDispatcher< ET, Egs >::selector_screen () noexcept
Access the screen used to select engines/presets.
The returned screen has the dynamic type [EngineSelectorScreen]() \preconditions [init]() has previously been called
Definition at line 125 of file engine_dispatcher.inl.
data_of_engines()
template<EngineType ET, typename... Egs> const foonathan::array::flat_map< util::string_ref, nlohmann::json > & otto::core::engine::EngineDispatcher< ET, Egs >::data_of_engines () const noexcept
Definition at line 132 of file engine_dispatcher.inl.
to_json()
template<EngineType ET, typename... Egs> nlohmann::json otto::core::engine::EngineDispatcher< ET, Egs >::to_json () const
Definition at line 138 of file engine_dispatcher.inl.
from_json()
template<EngineType ET, typename... Egs> void otto::core::engine::EngineDispatcher< ET, Egs >::from_json (const nlohmann::json & j)
Definition at line 152 of file engine_dispatcher.inl.
Member Data Documentation
engine_type
template<EngineType ET, typename... Engines> constexpr const EngineType otto::core::engine::EngineDispatcher< ET, Engines >::engine_type = ET static constexpr
Definition at line 35 of file engine_dispatcher.hpp.
The documentation for this struct was generated from the following files:
/home/travis/build/topisani/OTTO/src/core/engine/engine_dispatcher.hpp
/home/travis/build/topisani/OTTO/src/core/engine/engine_dispatcher.inl