OTTO: otto::services::graph< N > Struct Template Reference
otto::services::graph< N > Struct Template Reference
Detailed Description
template<std::size_t N>
struct otto::services::graph< N >
Definition at line 20 of file debug_ui.hpp.
#include <debug_ui.hpp>
Public Member Functions
void push (float val)
void plot (std::string name)
void plot (std::string name, float min, float max)
Member Function Documentation
push()
template<std::size_t N> void otto::services::graph< N >::push (float val)
Definition at line 21 of file debug_ui.hpp.
References std::max(), std::min(), std::move(), and otto::util::ringbuffer< T, N >::push().
plot() [1/2]
template<std::size_t N> void otto::services::graph< N >::plot (std::string name)
Definition at line 28 of file debug_ui.hpp.
plot() [2/2]
template<std::size_t N> void otto::services::graph< N >::plot (std::string name, float min, float max)
Definition at line 33 of file debug_ui.hpp.
The documentation for this struct was generated from the following file:
/home/travis/build/topisani/OTTO/src/services/debug_ui.hpp