OTTO: otto::core::ui::vg::Canvas Struct Reference
otto::core::ui::vg::Canvas Struct Reference
#include <canvas.hpp>
Public Types
using Super = NanoCanvas::Canvas
Public Member Functions
Canvas (NVGcontext *ctx, Size size, float scaleRatio=1.0f)
Canvas (NVGcontext *ctx, float width, float height, float scaleRatio=1.0f)
Canvas (const Canvas &)=delete
Canvas is non-copyable.
auto operator= (const Canvas &)=delete
Canvas is non-copyable.
Canvas (Canvas &&)=default
Canvas is movable.
Canvas & operator= (Canvas &&)=default
Canvas is movable.
Size size () const noexcept
Get the canvas size.
Canvas & moveTo (Point p)
Canvas & lineTo (Point p)
Canvas & arcTo (Point p1, Point p2, float r)
Canvas & quadraticCurveTo (Point control, Point end)
Canvas & bezierCurveTo (Point cp1, Point cp2, Point end)
Canvas & arc (Point cp, float r, float sAngle, float eAngle, bool counterclockwise=false)
Canvas & rect (Point p, Size s)
Canvas & roundedRect (Point p, Size s, float r)
Canvas & circle (Point p, float r)
Canvas & ellipse (Point p, float rx, float ry)
Canvas & clearColor (const Colour &color)
Canvas & font (const Font &f, float size)
Canvas & fillText (const std::string &text, Point p, float rowWidth=NAN)
Canvas & fillStyle (const Colour &color)
Canvas & strokeStyle (const Colour &color)
Canvas & fill (const Colour &color)
Canvas & stroke (const Colour &color)
Canvas & translate (Point p)
Canvas & rotateAround (float r, Point p)
Canvas & scaleTowards (float s, Point p)
Canvas & draw (Drawable &d)
Canvas & draw (Drawable &&d)
Canvas & drawAt (Point p, Drawable &&d)
Canvas & drawAt (Point p, Drawable &d)
template<typename FuncRef >
Canvas & group (FuncRef &&func)
Canvas & callAt (Point p, const std::function< void(void)> &f)
template<typename It >
Canvas & plotBezier (It pointB, It pointE, float f=0.5, float t=1)
template<typename Iter >
void plotRounded (Iter first, Iter last, float max_radius)
template<typename Iter >
void plotLines (Iter first, Iter last)
template<typename It >
Canvas & plotPoints (It first, It last, float r, Colour c)
Canvas & debugDot (Point p, Colour c=0xFFFF00)
Detailed Description
A modified NanoCanvas interface.
Allows for usage of [*Point]() and [*Size]() classes
Definition at line 253 of file canvas.hpp.
Member Typedef Documentation
Super
using otto::core::ui::vg::Canvas::Super = NanoCanvas::Canvas
Definition at line 254 of file canvas.hpp.
Constructor & Destructor Documentation
Canvas() [1/4]
otto::core::ui::vg::Canvas::Canvas (NVGcontext * ctx, Size size, float scaleRatio = 1.0f) inline
Definition at line 261 of file canvas.hpp.
                                                                 :
       Canvas(ctx, size.w, size.h, scaleRatio) {}
Canvas() [2/4]
otto::core::ui::vg::Canvas::Canvas (NVGcontext * ctx, float width, float height, float scaleRatio = 1.0f) inline
Definition at line 264 of file canvas.hpp.
                                                                                 :
       Super(ctx, width, height, scaleRatio) {}
Canvas() [3/4]
otto::core::ui::vg::Canvas::Canvas (const Canvas &) delete
Canvas is non-copyable.
Canvas() [4/4]
otto::core::ui::vg::Canvas::Canvas (Canvas &&) default
Canvas is movable.
Member Function Documentation
arc()
Canvas& otto::core::ui::vg::Canvas::arc (Point cp, float r, float sAngle, float eAngle, bool counterclockwise = false) inline
Definition at line 313 of file canvas.hpp.
References otto::core::ui::vg::Point::x, and otto::core::ui::vg::Point::y.
Referenced by otto::engines::EuclidScreen::draw_channel(), and otto::engines::EuclidScreen::draw_normal().
{
       Super::arc(cp.x, cp.y, r, sAngle, eAngle, counterclockwise);
       return *this;
     }
arcTo()
Canvas& otto::core::ui::vg::Canvas::arcTo (Point p1, Point p2, float r) inline
Definition at line 295 of file canvas.hpp.
References otto::core::ui::vg::Point::x, and otto::core::ui::vg::Point::y.
Referenced by otto::core::ui::vg::icons::Arrow::draw(), and plotRounded().
{
       Super::arcTo(p1.x, p1.y, p2.x, p2.y, r);
       return *this;
     }
bezierCurveTo()
Canvas& otto::core::ui::vg::Canvas::bezierCurveTo (Point cp1, Point cp2, Point end) inline
Definition at line 307 of file canvas.hpp.
References otto::core::ui::vg::Point::x, and otto::core::ui::vg::Point::y.
Referenced by otto::engines::WormholeScreen::draw(), otto::engines::MasterScreen::draw(), and plotBezier().
{
       Super::bezierCurveTo(cp1.x, cp1.y, cp2.x, cp2.y, end.x, end.y);
       return *this;
     }
callAt()
Canvas& otto::core::ui::vg::Canvas::callAt (Point p, const std::function< void(void)> & f) inline
Definition at line 446 of file canvas.hpp.
References translate().
{
       save();
       translate(p);
       f();
       restore();
       return *this;
     }
circle()
Canvas& otto::core::ui::vg::Canvas::circle (Point p, float r) inline
Definition at line 332 of file canvas.hpp.
Referenced by debugDot(), otto::engines::MasterScreen::draw(), otto::engines::WormholeScreen::draw(), otto::engines::EuclidScreen::draw_channel(), and plotPoints().
{
       Super::circle(p.x, p.y, r);
       return *this;
     }
clearColor()
Canvas& otto::core::ui::vg::Canvas::clearColor (const Colour & color) inline
Definition at line 345 of file canvas.hpp.
Referenced by otto::service::ui::main_ui_loop().
{
       Super::clearColor(color);
       return *this;
     }
debugDot()
Canvas& otto::core::ui::vg::Canvas::debugDot (Point p, Colour c = 0xFFFF00) inline
Definition at line 551 of file canvas.hpp.
References circle(), and fill().
{
       beginPath();
       circle(p, 1);
       fill(c);
       return *this;
     }
draw() [1/2]
Canvas& otto::core::ui::vg::Canvas::draw (Drawable & d) inline
Definition at line 412 of file canvas.hpp.
Referenced by otto::service::ui::impl::draw_frame().
{
       d.draw(*this);
       return *this;
     }
draw() [2/2]
Canvas& otto::core::ui::vg::Canvas::draw (Drawable && d) inline
Definition at line 417 of file canvas.hpp.
{
       d.draw(*this);
       return *this;
     }
drawAt() [1/2]
Canvas& otto::core::ui::vg::Canvas::drawAt (Point p, Drawable && d) inline
Definition at line 422 of file canvas.hpp.
References translate().
Referenced by otto::core::engines::EngineSelectorScreen::draw().
{
       save();
       translate(p);
       d.draw(*this);
       restore();
       return *this;
     }
drawAt() [2/2]
Canvas& otto::core::ui::vg::Canvas::drawAt (Point p, Drawable & d) inline
Definition at line 430 of file canvas.hpp.
References translate().
{
       save();
       translate(p);
       d.draw(*this);
       restore();
       return *this;
     }
ellipse()
Canvas& otto::core::ui::vg::Canvas::ellipse (Point p, float rx, float ry) inline
Definition at line 338 of file canvas.hpp.
{
       Super::ellipse(p.x, p.y, rx, ry);
       return *this;
     }
fill()
Canvas& otto::core::ui::vg::Canvas::fill (const Colour & color) inline
Definition at line 378 of file canvas.hpp.
Referenced by debugDot(), otto::core::audio::EnvelopeScreen::draw(), otto::engines::WormholeScreen::draw(), otto::engines::MasterScreen::draw(), otto::core::ui::vg::icons::Arrow::draw(), otto::engines::EuclidScreen::draw_channel(), and plotPoints().
{
       Super::fillStyle(color);
       Super::fill();
       return *this;
     }
fillStyle()
Canvas& otto::core::ui::vg::Canvas::fillStyle (const Colour & color) inline
Definition at line 366 of file canvas.hpp.
Referenced by otto::engines::ExternalScreen::draw(), otto::engines::WormholeScreen::draw(), otto::engines::MasterScreen::draw(), otto::core::audio::SettingsScreen::draw(), otto::core::ui::vg::icons::Arrow::draw(), otto::core::ui::SelectorWidget::draw(), otto::engines::EuclidScreen::draw_normal(), otto::engines::EuclidScreen::draw_recording(), and otto::service::ui::main_ui_loop().
{
       Super::fillStyle(color);
       return *this;
     }
fillText()
Canvas& otto::core::ui::vg::Canvas::fillText (const std::string & text, Point p, float rowWidth = NAN) inline
Definition at line 358 of file canvas.hpp.
Referenced by otto::engines::ExternalScreen::draw(), otto::engines::WormholeScreen::draw(), otto::engines::MasterScreen::draw(), otto::core::audio::SettingsScreen::draw(), otto::core::ui::SelectorWidget::draw(), otto::engines::EuclidScreen::draw_normal(), otto::engines::EuclidScreen::draw_recording(), and otto::service::ui::main_ui_loop().
{
       Super::fillText(text, p.x, p.y, rowWidth);
       return *this;
     }
font()
Canvas& otto::core::ui::vg::Canvas::font (const Font & f, float size) inline
Definition at line 351 of file canvas.hpp.
References size().
Referenced by otto::engines::ExternalScreen::draw(), otto::engines::WormholeScreen::draw(), otto::engines::MasterScreen::draw(), otto::core::audio::SettingsScreen::draw(), otto::core::ui::SelectorWidget::draw(), otto::engines::EuclidScreen::draw_normal(), otto::engines::EuclidScreen::draw_recording(), and otto::service::ui::main_ui_loop().
{
       Super::font(f);
       Super::font(size);
       return *this;
     }
group()
template<typename FuncRef > Canvas& otto::core::ui::vg::Canvas::group (FuncRef && func) inline
Definition at line 439 of file canvas.hpp.
Referenced by otto::engines::WormholeScreen::draw().
{
         save();
         func();
         restore();
         return *this;
     }
lineTo()
Canvas& otto::core::ui::vg::Canvas::lineTo (Point p) inline
Definition at line 289 of file canvas.hpp.
Referenced by otto::core::audio::EnvelopeScreen::draw(), otto::engines::ExternalScreen::draw(), otto::engines::WormholeScreen::draw(), otto::engines::MasterScreen::draw(), otto::core::ui::vg::icons::Arrow::draw(), plotLines(), and plotRounded().
{
       Super::lineTo(p.x, p.y);
       return *this;
     }
moveTo()
Canvas& otto::core::ui::vg::Canvas::moveTo (Point p) inline
Definition at line 283 of file canvas.hpp.
Referenced by otto::core::audio::EnvelopeScreen::draw(), otto::engines::ExternalScreen::draw(), otto::engines::MasterScreen::draw(), otto::engines::WormholeScreen::draw(), otto::core::ui::vg::icons::Arrow::draw(), plotBezier(), plotLines(), and plotRounded().
{
       Super::moveTo(p.x, p.y);
       return *this;
     }
operator=() [1/2]
auto otto::core::ui::vg::Canvas::operator= (const Canvas &) delete
Canvas is non-copyable.
operator=() [2/2]
Canvas& otto::core::ui::vg::Canvas::operator= (Canvas &&) default
Canvas is movable.
plotBezier()
template<typename It > Canvas& otto::core::ui::vg::Canvas::plotBezier (It pointB, It pointE, float f = 0.5, float t = 1) inline
Definition at line 455 of file canvas.hpp.
References bezierCurveTo(), moveTo(), otto::core::ui::vg::Point::x, and otto::core::ui::vg::Point::y.
{
       moveTo(*pointB);
       float m = 0;
       Point d1;
       Point prev = *pointB;
       Point cur = prev;
       Point next = prev;
       for (auto it = pointB; it != pointE; ++it) {
         prev = cur;
         cur = next;
         next = *it;
         if (cur == prev) continue;
         m = (next.y - prev.y) / (next.x - prev.x);
         Point d2 = {
           (next.x - cur.x) * -f,
           0
         };
         d2.y = d2.x * m * t;
         bezierCurveTo(prev - d1, cur + d2, cur);
         d1 = d2;
       }
       return *this;
     }
plotLines()
template<typename Iter > void otto::core::ui::vg::Canvas::plotLines (Iter first, Iter last) inline
Plot a curve between points using straight lines
Parameters
first An iterator to the first point
last An iterator one past the last point It shall be an InputIterator<Point>
Definition at line 520 of file canvas.hpp.
References lineTo(), and moveTo().
     {
       if (first == last) return;
       moveTo(*first++);
       for (auto p : util::sequence(first, last)) {
         lineTo(p);
       }
     }
plotPoints()
template<typename It > Canvas& otto::core::ui::vg::Canvas::plotPoints (It first, It last, float r, Colour c) inline
A scatterplot of points
Parameters
first An iterator to the first point
last An iterator one past the last point
r The radius of the points
c The colour of the points It shall be an InputIterator<Point>
Definition at line 539 of file canvas.hpp.
References circle(), and fill().
     {
       std::for_each(first, last, [this, c, r] (Point p) {
           beginPath();
           circle(p, r);
           fill(c);
         });
       return *this;
     }
plotRounded()
template<typename Iter > void otto::core::ui::vg::Canvas::plotRounded (Iter first, Iter last, float max_radius) inline
Draw a curve between points using only horizontal and vertical lines and rounded corners
This is the algorithm used by the samplers, and in general to display waveforms
Parameters
first An iterator to the first point
last An iterator one past the last point
maxR The maximum radius for curves, in pixels. If negative, there is no limit It shall be an InputIterator<Point>
Definition at line 493 of file canvas.hpp.
References otto::util::adjacent_pairs(), arcTo(), lineTo(), moveTo(), and otto::core::ui::vg::Point::x.
Referenced by otto::core::ui::widgets::Waveform< Container >::draw(), and otto::core::ui::widgets::Waveform< Container >::draw_range().
     {
       if (first == last) return;
       moveTo(*first);
       for (auto [p1, p2] : util::adjacent_pairs(first, last))
       {
         float dx = std::abs(p2.x - p1.x);
         float dy = std::abs(p2.y - p1.y);
         float r = std::min({dx / 2.f, dy / 2.f, max_radius});
         vg::Point md = (p1 + p2) / 2.0;
         vg::Point cp1 = {md.x, p1.y};
         vg::Point cp2 = md;
         vg::Point cp3 = {md.x, p2.y};
         arcTo(cp1, cp2, r);
         arcTo(cp3, p2, r);
       }
       lineTo(*(--last));
     }
quadraticCurveTo()
Canvas& otto::core::ui::vg::Canvas::quadraticCurveTo (Point control, Point end) inline
Definition at line 301 of file canvas.hpp.
References otto::core::ui::vg::Point::x, and otto::core::ui::vg::Point::y.
Referenced by otto::core::audio::EnvelopeScreen::draw().
{
       Super::quadraticCurveTo(control.x, control.y, end.x, end.y);
       return *this;
     }
rect()
Canvas& otto::core::ui::vg::Canvas::rect (Point p, Size s) inline
Definition at line 320 of file canvas.hpp.
Referenced by otto::core::ui::SelectorWidget::draw().
{
       Super::rect(p.x, p.y, s.w, s.h);
       return *this;
     }
rotateAround()
Canvas& otto::core::ui::vg::Canvas::rotateAround (float r, Point p) inline
Definition at line 398 of file canvas.hpp.
References translate().
Referenced by otto::engines::MasterScreen::draw(), and otto::core::ui::vg::icons::Arrow::draw().
{
       translate(p);
       rotate(r);
       translate(-p);
       return *this;
     }
roundedRect()
Canvas& otto::core::ui::vg::Canvas::roundedRect (Point p, Size s, float r) inline
Definition at line 326 of file canvas.hpp.
{
       Super::roundedRect(p.x, p.y, s.w, s.h, r);
       return *this;
     }
scaleTowards()
Canvas& otto::core::ui::vg::Canvas::scaleTowards (float s, Point p) inline
Definition at line 405 of file canvas.hpp.
References translate().
Referenced by otto::engines::WormholeScreen::draw().
{
       translate(p);
       scale(s, s);
       translate(-p);
       return *this;
     }
size()
Size otto::core::ui::vg::Canvas::size () const inline noexcept
Get the canvas size.
Definition at line 278 of file canvas.hpp.
Referenced by font().
{
       return {m_width, m_height};
     }
stroke()
Canvas& otto::core::ui::vg::Canvas::stroke (const Colour & color) inline
Definition at line 385 of file canvas.hpp.
Referenced by otto::core::audio::EnvelopeScreen::draw(), otto::engines::ExternalScreen::draw(), otto::engines::MasterScreen::draw(), otto::engines::WormholeScreen::draw(), otto::core::ui::vg::icons::Arrow::draw(), otto::engines::EuclidScreen::draw_channel(), and otto::engines::EuclidScreen::draw_normal().
{
       Super::strokeStyle(color);
       Super::stroke();
       return *this;
     }
strokeStyle()
Canvas& otto::core::ui::vg::Canvas::strokeStyle (const Colour & color) inline
Definition at line 372 of file canvas.hpp.
Referenced by otto::engines::WormholeScreen::draw(), otto::engines::MasterScreen::draw(), and otto::core::ui::vg::icons::Arrow::draw().
{
       Super::strokeStyle(color);
       return *this;
     }
translate()
Canvas& otto::core::ui::vg::Canvas::translate (Point p) inline
Definition at line 393 of file canvas.hpp.
Referenced by callAt(), otto::engines::WormholeScreen::draw(), otto::core::ui::vg::icons::Arrow::draw(), drawAt(), rotateAround(), and scaleTowards().
{
       Super::translate(p.x, p.y);
       return *this;
     }
The documentation for this struct was generated from the following file:
/home/topisani/dev/OTTO/src/core/ui/canvas.hpp