OTTO: otto::util::Slot Struct Reference
otto::util::Slot Struct Reference
Detailed Description
Type-erased connection.
Definition at line 16 of file signals.hpp.
#include <signals.hpp>
Public Member Functions
Slot ()=default
Slot (Slot *&ptr, std::function< void()> d) noexcept
Slot (const Slot &)=delete
Slot & operator= (const Slot &)=delete
Slot (Slot &&rhs)
Slot & operator= (Slot &&rhs)
~Slot () noexcept
void disconnect () noexcept
void clear () noexcept
Called by Signal on destruction.
Constructor & Destructor Documentation
Slot() [1/4]
otto::util::Slot::Slot () default
Slot() [2/4]
otto::util::Slot::Slot (Slot *& ptr, std::function< void()> d) noexcept
Definition at line 19 of file signals.hpp.
Slot() [3/4]
otto::util::Slot::Slot (const Slot &) delete
Slot() [4/4]
otto::util::Slot::Slot (Slot && rhs)
Definition at line 27 of file signals.hpp.
References std::move().
~Slot()
otto::util::Slot::~Slot () noexcept
Definition at line 41 of file signals.hpp.
References disconnect().
Member Function Documentation
operator=() [1/2]
Slot& otto::util::Slot::operator= (const Slot &) delete
operator=() [2/2]
Slot& otto::util::Slot::operator= (Slot && rhs)
Definition at line 31 of file signals.hpp.
References clear(), and disconnect().
disconnect()
void otto::util::Slot::disconnect () noexcept
Definition at line 46 of file signals.hpp.
Referenced by operator=(), and ~Slot().
clear()
void otto::util::Slot::clear () noexcept
Called by Signal on destruction.
Definition at line 54 of file signals.hpp.
Referenced by operator=(), and otto::util::Signal< Args >::Connection::~Connection().
The documentation for this struct was generated from the following file:
/home/travis/build/topisani/OTTO/src/util/signals.hpp