OTTO: otto::core::engines::EngineDispatcher< ET > Struct Template Reference
otto::core::engines::EngineDispatcher< ET > Struct Template Reference
Owns engines of type ET, and dispatches to a selected one of them.
#include <engine_dispatcher.hpp>
Public Types
enum ErrorCode { ErrorCode::none = 0, ErrorCode::engine_not_found, ErrorCode::type_mismatch }
using exception = util::as_exception< ErrorCode >
Public Member Functions
void init ()
Engine< ET > & current () noexcept
Access the currently selected engine.
const Engine< ET > & current () const noexcept
Engine< ET > & operator* () noexcept
Access the currently selected engine.
const Engine< ET > & operator* () const noexcept
Access the currently selected engine.
Engine< ET > const * operator-> () const noexcept
Access the currently selected engine.
Engine< ET > * operator-> () noexcept
Access the currently selected engine.
Engine< ET > & select (Engine< ET > *ptr)
Engine< ET > & select (Engine< ET > &ref)
Engine< ET > & select (std::size_t idx)
Engine< ET > & select (const std::string &name)
ui::Screen & selector_screen () noexcept
const std::vector< std::unique_ptr< Engine< ET > > > & engines () const noexcept
nlohmann::json to_json () const
void from_json (const nlohmann::json &)
Static Public Attributes
static constexpr const EngineType type = ET
Detailed Description
template<EngineType ET>
struct otto::core::engines::EngineDispatcher< ET >
Owns engines of type ET, and dispatches to a selected one of them.
Definition at line 13 of file engine_dispatcher.hpp.
Member Typedef Documentation
exception
template<EngineType ET> using otto::core::engines::EngineDispatcher< ET >::exception = util::as_exception<ErrorCode>
Definition at line 16 of file engine_dispatcher.hpp.
Member Enumeration Documentation
ErrorCode
template<EngineType ET> enum otto::core::engines::EngineDispatcher::ErrorCode strong
Enumerator
none
engine_not_found
type_mismatch
Definition at line 14 of file engine_dispatcher.hpp.
 { none = 0, engine_not_found, type_mismatch };
Member Function Documentation
current() [1/2]
template<EngineType ET> Engine< ET > & otto::core::engines::EngineDispatcher< ET >::current () noexcept
Access the currently selected engine.
Definition at line 31 of file engine_dispatcher.cpp.
   {
     return *_current;
   }
current() [2/2]
template<EngineType ET> const Engine< ET > & otto::core::engines::EngineDispatcher< ET >::current () const noexcept
Definition at line 37 of file engine_dispatcher.cpp.
   {
     return *_current;
   }
engines()
template<EngineType ET> const std::vector< std::unique_ptr< Engine< ET > > > & otto::core::engines::EngineDispatcher< ET >::engines () const noexcept
Definition at line 109 of file engine_dispatcher.cpp.
   {
     return _engines;
   }
from_json()
template<EngineType ET> void otto::core::engines::EngineDispatcher< ET >::from_json (const nlohmann::json & j)
Definition at line 125 of file engine_dispatcher.cpp.
References otto::util::find_if().
   {
     if (j.is_object()) {
       for (auto iter = j.begin(); iter != j.end(); iter++) {
         auto found = util::find_if(_engines, [name = iter.key()](auto&& eptr) {
           return eptr->name() == name;
         });
         if (found == _engines.end()) {
           throw exception(ErrorCode::engine_not_found);
         }
         (*found)->from_json(iter.value());
       }
     }
   }
init()
template<EngineType ET> void otto::core::engines::EngineDispatcher< ET >::init ()
Construct all registered engines
Only call this after all engines are registered
construct [_engines]() using [otto::engines:create_engines<ET>]()
instantiate [_selector_screen]() with a new [EngineSelectorScreen<ET>]()
Definition at line 11 of file engine_dispatcher.cpp.
References otto::service::presets::apply_preset().
   {
     _engines = create_engines<ET>();
     if (_engines.empty()) {
       throw util::exception(
         "No engines registered. Can't construct EngineDispatcher");
     }
     for (auto&& engine : _engines) {
       // Apply default presets to all engines
       try {
         int idx = engine->current_preset();
         service::presets::apply_preset(*engine, std::max(idx, 0), true);
       } catch (service::presets::exception& e) {
         DLOGI(e.what());
       }
     }
     _selector_screen = std::make_unique<EngineSelectorScreen>(*this);
   }
operator*() [1/2]
template<EngineType ET> Engine< ET > & otto::core::engines::EngineDispatcher< ET >::operator* () noexcept
Access the currently selected engine.
Definition at line 43 of file engine_dispatcher.cpp.
   {
     return *_current;
   }
operator*() [2/2]
template<EngineType ET> const Engine< ET > & otto::core::engines::EngineDispatcher< ET >::operator* () const noexcept
Access the currently selected engine.
Definition at line 49 of file engine_dispatcher.cpp.
   {
     return *_current;
   }
operator->() [1/2]
template<EngineType ET> const Engine< ET > * otto::core::engines::EngineDispatcher< ET >::operator-> () const noexcept
Access the currently selected engine.
Definition at line 61 of file engine_dispatcher.cpp.
   {
     return _current;
   }
operator->() [2/2]
template<EngineType ET> Engine< ET > * otto::core::engines::EngineDispatcher< ET >::operator-> () noexcept
Access the currently selected engine.
Definition at line 55 of file engine_dispatcher.cpp.
   {
     return _current;
   }
select() [1/4]
template<EngineType ET> Engine< ET > & otto::core::engines::EngineDispatcher< ET >::select (Engine< ET > * ptr)
Select engine
ptr >= _engines.begin() && ptr < _engines.end()
If _current is not null, _current->on_disable(). Then, assign ptr to _current, and invoke ptr->on_enable()
current() == *ptr
Returns
current()
Definition at line 80 of file engine_dispatcher.cpp.
References otto::core::engines::AnyEngine::on_enable().
Referenced by otto::core::engines::EngineSelectorScreen::EngineSelectorScreen().
   {
     if (_current == ptr && ptr != nullptr) return *_current;
     if (_current != nullptr) _current->on_disable();
     _current = ptr;
     _current->on_enable();
     return *_current;
   }
select() [2/4]
template<EngineType ET> Engine< ET > & otto::core::engines::EngineDispatcher< ET >::select (Engine< ET > & ref)
Select engine
select(&ref)
Definition at line 90 of file engine_dispatcher.cpp.
   {
     return select(&ref);
   }
select() [3/4]
template<EngineType ET> Engine< ET > & otto::core::engines::EngineDispatcher< ET >::select (std::size_t idx)
Select engine by index
select(_engines.begin() + idx)
Definition at line 96 of file engine_dispatcher.cpp.
   {
     return select((_engines.begin().base() + idx)->get());
   }
select() [4/4]
template<EngineType ET> Engine< ET > & otto::core::engines::EngineDispatcher< ET >::select (const std::string & name)
Select engine by name
Find engine with name name, and select(engine)
Exceptions
<tt>util::exception</tt> when no matching engine was found
Definition at line 67 of file engine_dispatcher.cpp.
References otto::util::find_if().
   {
     auto iter = util::find_if(
       _engines, [&name](auto&& eg) { return eg->name() == name; });
     if (iter != _engines.end()) {
       select((*iter).get());
     } else {
       throw util::exception("Engine '{}' not found", name);
     }
     return *_current;
   }
selector_screen()
template<EngineType ET> ui::Screen & otto::core::engines::EngineDispatcher< ET >::selector_screen () noexcept
Access the screen used to select engines/presets
The returned screen has the dynamic type [EngineSelectorScreen]() [init]() has previously been called
Definition at line 102 of file engine_dispatcher.cpp.
   {
     return *_selector_screen;
   }
to_json()
template<EngineType ET> nlohmann::json otto::core::engines::EngineDispatcher< ET >::to_json () const
Definition at line 115 of file engine_dispatcher.cpp.
   {
     nlohmann::json j = nlohmann::json::object();
     for (auto&& engine : _engines) {
       j[engine->name()] = engine->to_json();
     }
     return j;
   }
Member Data Documentation
type
template<EngineType ET> constexpr const EngineType otto::core::engines::EngineDispatcher< ET >::type = ET static
Definition at line 18 of file engine_dispatcher.hpp.
The documentation for this struct was generated from the following files:
/home/topisani/dev/OTTO/src/core/engines/engine_dispatcher.hpp
/home/topisani/dev/OTTO/src/core/engines/engine_dispatcher.cpp