OTTO: otto::core::audio::EnvelopeScreen Struct Reference
otto::core::audio::EnvelopeScreen Struct Reference
Public Member Functions
EnvelopeScreen (EnvelopeProps &props)
void draw (ui::vg::Canvas &) override
void rotary (ui::RotaryEvent ev) override
This should be used for handling rotary events.
Public Member Functions inherited from otto::core::ui::Screen
Screen ()
virtual ~Screen ()
virtual bool keypress (Key)
virtual bool keyrelease (Key)
virtual void on_show ()
Run by MainUI when switching to this screen.
virtual void on_hide ()
Run by MainUI when switching to another screen.
Public Member Functions inherited from otto::core::ui::vg::Drawable
Drawable ()=default
virtual ~Drawable ()=default
Public Attributes
EnvelopeProps & props
Detailed Description
Definition at line 7 of file voice_manager.cpp.
Constructor & Destructor Documentation
EnvelopeScreen()
otto::core::audio::EnvelopeScreen::EnvelopeScreen (EnvelopeProps & props) inline
Definition at line 9 of file voice_manager.cpp.
       : props (props)
     {}
Member Function Documentation
draw()
void otto::core::audio::EnvelopeScreen::draw (ui::vg::Canvas & ctx) override virtual
Draw this widget to the context.
Called from the parent's draw method.
Parameters
ctx the canvas to draw on.
Implements otto::core::ui::vg::Drawable.
Definition at line 75 of file voice_manager.cpp.
References otto::core::ui::vg::Canvas::fill(), otto::core::ui::vg::Canvas::lineTo(), otto::core::ui::vg::Canvas::moveTo(), otto::core::ui::vg::Canvas::quadraticCurveTo(), and otto::core::ui::vg::Canvas::stroke().
   {
     constexpr auto b = vg::Box{ 30.f, 60.f, 260.f, 110.f };
     const float spacing = 10.f;
     const float max_width = (b.width - 3 * spacing) / 3.f;
     const float aw = max_width * props.attack.normalize();
     const float dw = max_width * props.decay.normalize();
     const float sh = b.height * props.sustain.normalize();
     const float rw = max_width * props.release.normalize();
     ctx.lineWidth(6.f);
     const float arc_size = 0.9;
     ctx.beginPath();
     ctx.moveTo(b.x, b.y + b.height + spacing);
     ctx.lineTo(b.x + b.width, b.y + b.height + spacing);
     ctx.stroke(Colours::White);
     ctx.beginPath();
     ctx.moveTo(b.x, b.y + b.height);
     ctx.quadraticCurveTo({b.x + aw * arc_size, b.y + b.height * arc_size}, {b.x + aw, b.y}); // curve
     ctx.lineTo(b.x + aw, b.y + b.height);
     ctx.closePath();
     ctx.stroke(Colours::Blue);
     ctx.fill(Colours::Blue);
     ctx.beginPath();
     ctx.moveTo(b.x + aw + spacing, b.y + b.height);
     ctx.lineTo(b.x + aw + spacing, b.y);
     ctx.quadraticCurveTo({b.x + aw + spacing + dw * (1 - arc_size), b.y + (b.height - sh) * arc_size}, {b.x + aw + spacing + dw, b.y + b.height - sh}); // curve
     ctx.lineTo(b.x + aw + spacing + dw, b.y + b.height);
     ctx.closePath();
     ctx.stroke(Colours::Green);
     ctx.fill(Colours::Green);
     ctx.beginPath();
     ctx.moveTo(b.x + aw + spacing + dw + spacing,      b.y + b.height - sh);
     ctx.lineTo(b.x + b.width - spacing - rw, b.y + b.height - sh);
     ctx.lineTo(b.x + b.width - spacing - rw, b.y + b.height);
     ctx.lineTo(b.x + aw + spacing + dw + spacing, b.y + b.height);
     ctx.closePath();
     ctx.stroke(Colours::Yellow);
     ctx.fill(Colours::Yellow);
     ctx.beginPath();
     ctx.moveTo(b.x + b.width - rw, b.y + b.height);
     ctx.lineTo(b.x + b.width - rw, b.y + b.height - sh);
     ctx.quadraticCurveTo({b.x + b.width - rw * arc_size, b.y + b.height - sh * (1 - arc_size)}, {b.x + b.width,      b.y + b.height});
     ctx.closePath();
     ctx.stroke(Colours::Red);
     ctx.fill(Colours::Red);
   }
rotary()
void otto::core::audio::EnvelopeScreen::rotary (ui::RotaryEvent) override virtual
This should be used for handling rotary events.
Reimplemented from otto::core::ui::Screen.
Definition at line 58 of file voice_manager.cpp.
References otto::core::ui::RotaryEvent::clicks, and otto::core::ui::RotaryEvent::rotary.
{
     switch (ctx.rotary) {
     case Rotary::Blue:
       props.attack.step(ctx.clicks);
       break;
     case Rotary::Green:
       props.decay.step(ctx.clicks);
       break;
     case Rotary::White:
       props.sustain.step(ctx.clicks);
       break;
     case Rotary::Red:
       props.release.step(ctx.clicks);
       break;
     }
   }
Member Data Documentation
props
EnvelopeProps& otto::core::audio::EnvelopeScreen::props
Definition at line 16 of file voice_manager.cpp.
The documentation for this struct was generated from the following file:
/home/topisani/dev/OTTO/src/core/audio/voice_manager.cpp