OTTO: otto::nvg::Canvas Class Reference
otto::nvg::Canvas Class Reference
Detailed Description
Author
Geequlim
Definition at line 81 of file Canvas.hpp.
#include <Canvas.hpp>
Public Member Functions
Canvas (NVGcontext *ctx, float width, float height, float scaleRatio=1.0f)
Construct a canvas with NanoVG Context.
Canvas (NVGcontext *ctx, Size size, float scaleRatio=1.0f)
Canvas (const Canvas &)=delete
Canvas is non-copyable.
auto operator= (const Canvas &)=delete
Canvas is non-copyable.
Canvas (Canvas &&)=default
Canvas is movable.
Canvas & operator= (Canvas &&)=default
Canvas is movable.
Size size () const noexcept
Get the canvas size.
Canvas & moveTo (float x, float y)
Moves the path to the specified point in the canvas, without creating a line.
Canvas & moveTo (Point p)
Canvas & lineTo (float x, float y)
Adds a new point and creates a line from that point to the last specified point in the canvas.
Canvas & lineTo (Point p)
Canvas & arcTo (float x1, float y1, float x2, float y2, float r)
Creates an arc/curve between two tangents on the canvas.
Canvas & arcTo (Point p1, Point p2, float r)
Canvas & quadraticCurveTo (float cpx, float cpy, float x, float y)
Creates a quadratic Bézier curve.
Canvas & quadraticCurveTo (Point control, Point end)
Canvas & bezierCurveTo (float cp1x, float cp1y, float cp2x, float cp2y, float x, float y)
Creates a cubic Bézier curve.
Canvas & bezierCurveTo (Point cp1, Point cp2, Point end)
Canvas & arc (float x, float y, float r, float sAngle, float eAngle, bool counterclockwise=false)
Creates an arc/curve (used to create circles, or parts of circles) The arc() method creates an arc/curve (used to create circles, or parts of circles).
Canvas & arc (Point cp, float r, float sAngle, float eAngle, bool counterclockwise=false)
Canvas & closePath ()
Close current path with a line segment.
Canvas & rect (float x, float y, float w, float h)
Creates a rectangle.
Canvas & rect (Point p, Size s)
Canvas & rect (Box b)
Canvas & centeredSquare (Point p, float side_length)
Canvas & roundedRect (float x, float y, float w, float h, float r)
Creates a rounded rectangle.
Canvas & roundedRect (Point p, Size s, float r)
Canvas & roundedRect (Box b, float r)
Canvas & circle (float cx, float cy, float r)
Creates a circle.
Canvas & circle (Point p, float r)
Canvas & ellipse (float cx, float cy, float rx, float ry)
Creates an ellipse.
Canvas & ellipse (Point p, float rx, float ry)
Canvas & fill ()
Fills the current drawing (path)
Canvas & fill (const Color &color)
Canvas & stroke ()
Actually draws the path you have defined.
Canvas & stroke (const Color &color)
Canvas & fillRect (float x, float y, float w, float h)
Draws a "filled" rectangle.
Canvas & strokeRect (float x, float y, float w, float h)
Draws a rectangle (no fill)
Canvas & clearColor (const Color &color)
Clear the canvas with color.
Canvas & fillText (const std::string &text, float x, float y, float rowWidth=NAN)
Draws "filled" text on the canvas.
Canvas & fillText (const std::string &text, Point p, float rowWidth=NAN)
Canvas & drawImage (Image &image, float x, float y, float width=NAN, float height=NAN, float sx=0, float sy=0, float swidth=NAN, float sheight=NAN)
Draws an image onto the canvas.
Canvas & draw (Drawable &d)
Canvas & draw (Drawable &&d)
Canvas & drawAt (Point p, Drawable &&d)
Canvas & drawAt (Point p, Drawable &d)
template<typename FuncRef >
Canvas & group (FuncRef &&func)
template<typename FuncRef >
Canvas & callAt (Point p, FuncRef &&f)
template<typename It >
Canvas & plotBezier (It pointB, It pointE, float f=0.5, float t=1)
template<typename Iter >
Canvas & plotRounded (Iter first, Iter last, float max_radius)
Draw a curve between points using only horizontal and vertical lines and rounded corners.
template<typename Iter >
Canvas & plotLines (Iter first, Iter last)
Plot a curve between points using straight lines.
template<typename It >
Canvas & plotPoints (It first, It last, float r, Color c)
A scatterplot of points.
Canvas & debugDot (Point p, Color c=0xFFFF00)
Canvas & lineCap (LineCap cap)
Set the style of the end caps for a line.
Canvas & lineJoin (LineJoin join)
Set the type of corner created, when two lines meet.
Canvas & lineWidth (float width)
Set the current line width.
Canvas & miterLimit (float limit)
Sets the maximum miter length.
Canvas & globalAlpha (float alpha)
Sets the current alpha or transparency value of the drawing.
Canvas & fillStyle (const Color &color)
Sets the color to fill the drawing.
Canvas & fillStyle (const Paint &paint)
Set the gradient or pattern paint used to fill the drawing.
Canvas & strokeStyle (const Color &color)
Set the color used for strokes.
Canvas & strokeStyle (const Paint &paint)
Set the gradient or pattern paint used for strokes.
Canvas & font (const Font &font)
Set current font for text rendering.
Canvas & font (float size)
Set font size for current text style.
Canvas & font (const Font &f, float size)
Set current font and size for text rendering.
Canvas & textAlign (HorizontalAlign hAlign, VerticalAlign vAlign)
Sets the text alignment of current text style.
Canvas & fillStyle (const TextStyle &textStyle)
Set styles for text rendering.
float measureText (const std::string &text, float rowWidth=NAN)
Check the width of the text, before writing it on the canvas.
float measureText (const std::string &text, float x, float y, float *bounds, float rowWidth=NAN)
Check the boundary of the text, before writing it on the canvas.
Box measureText (const std::string &text, Point p, float rowWidth=NAN)
Canvas & globalCompositeOperation (CompositeOperation op)
Canvas & scale (float scalewidth, float scaleheight)
Scales the current drawing, bigger or smaller.
Canvas & scaleTowards (float s, Point p)
Scales the current drawing, bigger or smaller.
Canvas & rotate (float angle)
Rotates the current drawing.
Canvas & rotateAround (float r, Point p)
Rotates the current drawing.
Canvas & translate (float x, float y)
Remaps the (0,0) position on the canvas.
Canvas & translate (Point p)
Canvas & transform (float a, float b, float c, float d, float e, float f)
Replaces the current transformation matrix for the drawing.
Canvas & setTransform (float a, float b, float c, float d, float e, float f)
Resets the current transform to the identity matrix.
Canvas & restTransform ()
Resets the current transform to the identity matrix.
Canvas & beginFrame (int windowWidth, int windowHeight)
Begin drawing a new frame.
Canvas & cancelFrame ()
Cancels drawing the current frame.
void endFrame ()
Ends drawing flushing remaining render state.
Canvas & beginPath ()
Begins a path, or resets the current path.
Canvas & pathWinding (Winding dir)
Sets the current path winding.
Canvas & clip (float x, float y, float w, float h)
Clip of a rectangular region.
Canvas & resetClip ()
Reset clip state ,remove all clip region.
Canvas & save ()
Pushe and save the current render state into a state stack.
Canvas & restore ()
Pop and restore current render state.
Canvas & reset ()
Resets current render state to default values.
bool valid () const
Check is the context avaliable.
Canvas & setSize (float width, float height)
Set canvas size.
Canvas & setPosition (float x, float y)
Set position of the canvas.
Canvas & setScaleRatio (float ratio)
Set scale ration of the canvas.
void local2Global (float &x, float &y)
Convert coordinates in canvas to coordinates in windows.
void global2Local (float &x, float &y)
Convert coordinates in windows to coordinates in canvas.
NVGcontext * nvgContext ()
Get the NanoVG context for advanced contol.
Static Public Member Functions
static Paint createLinearGradient (float x0, float y0, float x1, float y1, const Color &scolor, const Color &ecolor)
Creates a linear gradient (to use on canvas content)
static Paint createRadialGradient (float cx, float cy, float r1, float r2, const Color &icolor, const Color &ocolor)
Creates a radial/circular gradient (to use on canvas content)
static Paint createBoxGradient (float x, float y, float w, float h, float r, float f, Color icol, Color ocol)
Creates and returns a box gradient.
static Paint createPattern (const Image &image, float ox, float oy, float w, float h, float angle=0.0f, float alpha=1.0f)
Creates and returns an image pattern paint.
Protected Attributes
NVGcontext * m_nvgCtx
The NanoVG context.
float m_width
The width of the canvas.
float m_height
The height of the canvas.
float m_scaleRatio
Buffer / window size ratio.
float m_xPos
The x-coordinate of the canvas in window.
float m_yPos
The y-coordinate of the canvas in window.
Constructor & Destructor Documentation
Canvas() [1/4]
otto::nvg::Canvas::Canvas (NVGcontext * ctx, float width, float height, float scaleRatio = 1.0f)
Construct a canvas with NanoVG Context.
Parameters
ctx The NanoVG Context used for this canvas
width The width of the canvas, in pixels
height The height of the canvas, in pixels
scaleRatio The device pixel ration
Canvas() [2/4]
otto::nvg::Canvas::Canvas (NVGcontext * ctx, Size size, float scaleRatio = 1.0f)
Canvas() [3/4]
otto::nvg::Canvas::Canvas (const Canvas &) delete
Canvas is non-copyable.
Canvas() [4/4]
otto::nvg::Canvas::Canvas (Canvas &&) default
Canvas is movable.
Member Function Documentation
operator=() [1/2]
auto otto::nvg::Canvas::operator= (const Canvas &) delete
Canvas is non-copyable.
operator=() [2/2]
Canvas& otto::nvg::Canvas::operator= (Canvas &&) default
Canvas is movable.
size()
Size otto::nvg::Canvas::size () const noexcept
Get the canvas size.
moveTo() [1/2]
Canvas& otto::nvg::Canvas::moveTo (float x, float y)
Moves the path to the specified point in the canvas, without creating a line.
The moveTo() method moves the path to the specified point in the canvas, without creating a line.
Parameters
x The x-coordinate of where to move the path to
y The y-coordinate of where to move the path to
Returns
The Canvas to operate with
moveTo() [2/2]
Canvas& otto::nvg::Canvas::moveTo (Point p)
lineTo() [1/2]
Canvas& otto::nvg::Canvas::lineTo (float x, float y)
Adds a new point and creates a line from that point to the last specified point in the canvas.
The lineTo() method adds a new point and creates a line from that point to the last specified point in the canvas (this method does not draw the line).
Parameters
x The x-coordinate of where to create the line to
y The y-coordinate of where to create the line to
Returns
The Canvas to operate with
lineTo() [2/2]
Canvas& otto::nvg::Canvas::lineTo (Point p)
arcTo() [1/2]
Canvas& otto::nvg::Canvas::arcTo (float x1, float y1, float x2, float y2, float r)
Creates an arc/curve between two tangents on the canvas.
Parameters
x1 The x-coordinate of the first tangent
y1 The y-coordinate of the first tangent
x2 The x-coordinate of the second tangent
y2 The y-coordinate of the second tangent
r The radius of the arc
Returns
The Canvas to operate with
arcTo() [2/2]
Canvas& otto::nvg::Canvas::arcTo (Point p1, Point p2, float r)
quadraticCurveTo() [1/2]
Canvas& otto::nvg::Canvas::quadraticCurveTo (float cpx, float cpy, float x, float y)
Creates a quadratic Bézier curve.
The quadraticCurveTo() method adds a point to the current path by using the specified control points that represent a quadratic Bézier curve.
A quadratic Bézier curve requires two points. The first point is a control point that is used in the quadratic Bézier calculation and the second point is the ending point for the curve. The starting point for the curve is the last point in the current path. If a path does not exist, use the beginPath() and moveTo() methods to define a starting point.
Parameters
cpx The x-coordinate of the Bézier control point
cpy The y-coordinate of the Bézier control point
x The x-coordinate of the ending point
y The y-coordinate of the ending point
Returns
The Canvas to operate with
quadraticCurveTo() [2/2]
Canvas& otto::nvg::Canvas::quadraticCurveTo (Point control, Point end)
bezierCurveTo() [1/2]
Canvas& otto::nvg::Canvas::bezierCurveTo (float cp1x, float cp1y, float cp2x, float cp2y, float x, float y)
Creates a cubic Bézier curve.
The bezierCurveTo() method adds a point to the current path by using the specified control points that represent a cubic Bézier curve.
A cubic bezier curve requires three points. The first two points are control points that are used in the cubic Bézier calculation and the last point is the ending point for the curve. The starting point for the curve is the last point in the current path. If a path does not exist, use the beginPath() and moveTo() methods to define a starting point.
Parameters
cp1x The x-coordinate of the first Bézier control point
cp1y The y-coordinate of the first Bézier control point
cp2x The x-coordinate of the second Bézier control point
cp2y The y-coordinate of the second Bézier control point
x The x-coordinate of the ending point
y The y-coordinate of the ending point
Returns
The Canvas to operate with
bezierCurveTo() [2/2]
Canvas& otto::nvg::Canvas::bezierCurveTo (Point cp1, Point cp2, Point end)
arc() [1/2]
Canvas& otto::nvg::Canvas::arc (float x, float y, float r, float sAngle, float eAngle, bool counterclockwise = false)
Creates an arc/curve (used to create circles, or parts of circles) The arc() method creates an arc/curve (used to create circles, or parts of circles).
Note
Tip: To create a circle with arc(): Set start angle to 0 and end angle to 2*π.
Parameters
x The x-coordinate of the center of the circle
y The y-coordinate of the center of the circle
r The radius of the circle
sAngle The starting angle, in radians (0 is at the 3 o'clock position of the arc's circle)
eAngle The ending angle, in radians
counterclockwise Optional. Specifies whether the drawing should be counterclockwise or clockwise. False is default, and indicates clockwise, while true indicates counter-clockwise.
Returns
arc() [2/2]
Canvas& otto::nvg::Canvas::arc (Point cp, float r, float sAngle, float eAngle, bool counterclockwise = false)
closePath()
Canvas& otto::nvg::Canvas::closePath ()
Close current path with a line segment.
Returns
The canvas to operate with
rect() [1/3]
Canvas& otto::nvg::Canvas::rect (float x, float y, float w, float h)
Creates a rectangle.
The rect() method creates a rectangle.
Parameters
x The x-coordinate of the upper-left corner of the rectangle
y The y-coordinate of the upper-left corner of the rectangle
w The width of the rectangle, in pixels
h The height of the rectangle, in pixels
Returns
The canvas which the path be added to
rect() [2/3]
Canvas& otto::nvg::Canvas::rect (Point p, Size s)
rect() [3/3]
Canvas& otto::nvg::Canvas::rect (Box b)
centeredSquare()
Canvas& otto::nvg::Canvas::centeredSquare (Point p, float side_length)
roundedRect() [1/3]
Canvas& otto::nvg::Canvas::roundedRect (float x, float y, float w, float h, float r)
Creates a rounded rectangle.
Parameters
x The x-coordinate of the upper-left corner of the rectangle
y The y-coordinate of the upper-left corner of the rectangle
w The width of the rectangle, in pixels
h The height of the rectangle, in pixels
r The radius of the circle formed by 4 corners of the rounded rectangle
Returns
The canvas to create path
roundedRect() [2/3]
Canvas& otto::nvg::Canvas::roundedRect (Point p, Size s, float r)
roundedRect() [3/3]
Canvas& otto::nvg::Canvas::roundedRect (Box b, float r)
circle() [1/2]
Canvas& otto::nvg::Canvas::circle (float cx, float cy, float r)
Creates a circle.
Parameters
cx The x-coordinate of center point for the circle
cy The y-coordinate of center point for the circle
r The radius of the circle
Returns
The canvas to create path
circle() [2/2]
Canvas& otto::nvg::Canvas::circle (Point p, float r)
ellipse() [1/2]
Canvas& otto::nvg::Canvas::ellipse (float cx, float cy, float rx, float ry)
Creates an ellipse.
Parameters
cx The x-coordinate of center point for the ellipse
cy The x-coordinate of center point for the ellipse
rx The radius of the ellipse in horizentoal
ry The radius of the ellipse in vertical
Returns
The canvas to create path
ellipse() [2/2]
Canvas& otto::nvg::Canvas::ellipse (Point p, float rx, float ry)
fill() [1/2]
Canvas& otto::nvg::Canvas::fill ()
Fills the current drawing (path)
The fill() method fills the current drawing (path). The default color is black.
Note
If the path is not closed, the fill() method will add a line from the last point to the startpoint of the path to close the path (like closePath()), and then fill the path.
Returns
The canvas to fill
fill() [2/2]
Canvas& otto::nvg::Canvas::fill (const Color & color)
stroke() [1/2]
Canvas& otto::nvg::Canvas::stroke ()
Actually draws the path you have defined.
The stroke() method actually draws the path you have defined with all those moveTo() and lineTo() methods. The default color is black.
Returns
The canvas to stroke
stroke() [2/2]
Canvas& otto::nvg::Canvas::stroke (const Color & color)
fillRect()
Canvas& otto::nvg::Canvas::fillRect (float x, float y, float w, float h)
Draws a "filled" rectangle.
The fillRect() method draws a "filled" rectangle. The default color of the fill is black.
Parameters
x The x-coordinate of the upper-left corner of the rectangle
y The y-coordinate of the upper-left corner of the rectangle
w The width of the rectangle, in pixels
h The height of the rectangle, in pixels
Returns
The canvas to draw
strokeRect()
Canvas& otto::nvg::Canvas::strokeRect (float x, float y, float w, float h)
Draws a rectangle (no fill)
The strokeRect() method draws a rectangle (no fill). The default color of the stroke is black.
Parameters
x The x-coordinate of the upper-left corner of the rectangle
y The y-coordinate of the upper-left corner of the rectangle
w The width of the rectangle, in pixels
h The height of the rectangle, in pixels
Returns
The canvas to draw
clearColor()
Canvas& otto::nvg::Canvas::clearColor (const Color & color)
Clear the canvas with color.
Parameters
color The color to fill the hole canvas
Returns
The canvas to operate with
fillText() [1/2]
Canvas& otto::nvg::Canvas::fillText (const std::string & text, float x, float y, float rowWidth = NAN)
Draws "filled" text on the canvas.
Parameters
text Specifies the text that will be written on the canvas
x The x coordinate where to start painting the text (relative to the canvas)
y The y coordinate where to start painting the text (relative to the canvas)
rowWidth The max row width of the text box,NAN is not limited
Returns
The canvas to operate with
fillText() [2/2]
Canvas& otto::nvg::Canvas::fillText (const std::string & text, Point p, float rowWidth = NAN)
drawImage()
Canvas& otto::nvg::Canvas::drawImage (Image & image, float x, float y, float width = NAN, float height = NAN, float sx = 0, float sy = 0, float swidth = NAN, float sheight = NAN)
Draws an image onto the canvas.
The drawImage() method can also draw parts of an image, and/or increase/reduce the image size.
Parameters
image Specifies the image to use
x The x coordinate where to place the image on the canvas
y The y coordinate where to place the image on the canvas
width The width of the image to use (stretch or reduce the image),NAN as the default be the same as wdith of the clipped area
height The height of the image to use (stretch or reduce the image),NAN as the default be the same as wdith of the clipped area
sx The x coordinate where to start clipping,0 as the default
sy The y coordinate where to start clipping,0 as the default
swidth The wdith of the clipped image,NAN as defualt to clip to right side of the image
sheight The height of the clipped image,NAN as defualt to clip to bottom side of the image
Returns
The canvas to draw this image
draw() [1/2]
Canvas& otto::nvg::Canvas::draw (Drawable & d)
draw() [2/2]
Canvas& otto::nvg::Canvas::draw (Drawable && d)
drawAt() [1/2]
Canvas& otto::nvg::Canvas::drawAt (Point p, Drawable && d)
drawAt() [2/2]
Canvas& otto::nvg::Canvas::drawAt (Point p, Drawable & d)
group()
template<typename FuncRef > Canvas & otto::nvg::Canvas::group (FuncRef && func)
Definition at line 897 of file Canvas.hpp.
callAt()
template<typename FuncRef > Canvas & otto::nvg::Canvas::callAt (Point p, FuncRef && f)
Definition at line 906 of file Canvas.hpp.
plotBezier()
template<typename It > Canvas & otto::nvg::Canvas::plotBezier (It pointB, It pointE, float f = 0.5, float t = 1)
Definition at line 916 of file Canvas.hpp.
References otto::nvg::Point::x, and otto::nvg::Point::y.
plotRounded()
template<typename Iter > Canvas & otto::nvg::Canvas::plotRounded (Iter first, Iter last, float max_radius)
Draw a curve between points using only horizontal and vertical lines and rounded corners.
This is the algorithm used by the samplers, and in general to display waveforms
Parameters
first An iterator to the first point
last An iterator one past the last point
maxR The maximum radius for curves, in pixels. If negative, there is no limit \requires It shall be an InputIterator<Point>
Definition at line 941 of file Canvas.hpp.
References std::min(), and otto::nvg::Point::x.
Referenced by otto::core::ui::widgets::Waveform< Container >::draw(), and otto::core::ui::widgets::Waveform< Container >::draw_range().
plotLines()
template<typename Iter > Canvas & otto::nvg::Canvas::plotLines (Iter first, Iter last)
Plot a curve between points using straight lines.
Parameters
first An iterator to the first point
last An iterator one past the last point \requires It shall be an InputIterator<Point>
Definition at line 967 of file Canvas.hpp.
References std::for_each().
plotPoints()
template<typename It > Canvas & otto::nvg::Canvas::plotPoints (It first, It last, float r, Color c)
A scatterplot of points.
Parameters
first An iterator to the first point
last An iterator one past the last point
r The radius of the points
c The colour of the points \requires It shall be an InputIterator<Point>
Definition at line 977 of file Canvas.hpp.
References std::for_each().
debugDot()
Canvas& otto::nvg::Canvas::debugDot (Point p, Color c = 0xFFFF00)
lineCap()
Canvas& otto::nvg::Canvas::lineCap (LineCap cap)
Set the style of the end caps for a line.
Parameters
cap The line cap style
Returns
The canvas to operate with
lineJoin()
Canvas& otto::nvg::Canvas::lineJoin (LineJoin join)
Set the type of corner created, when two lines meet.
Parameters
join The line join style
Returns
The canvas to operate with
lineWidth()
Canvas& otto::nvg::Canvas::lineWidth (float width)
Set the current line width.
Parameters
width The current line width, in pixels
Returns
The canvas to operate with
miterLimit()
Canvas& otto::nvg::Canvas::miterLimit (float limit)
Sets the maximum miter length.
The miter length is the distance between the inner corner and the outer corner where two lines meet.
The miter length grows bigger as the angle of the corner gets smaller.
Note
The miterLimit property works only if the lineJoin attribute is "miter".
Parameters
limit A positive number that specifies the maximum miter length. If the current miter length exceeds the miterLimit, the corner will display as lineJoin "bevel"
Returns
The canvas to operate with
globalAlpha()
Canvas& otto::nvg::Canvas::globalAlpha (float alpha)
Sets the current alpha or transparency value of the drawing.
Parameters
alpha new alpha vlaue of canvas
Returns
The canvas to operate with
fillStyle() [1/3]
Canvas& otto::nvg::Canvas::fillStyle (const Color & color)
Sets the color to fill the drawing.
Parameters
color The color to fill with
Returns
The canvas to operate with
fillStyle() [2/3]
Canvas& otto::nvg::Canvas::fillStyle (const Paint & paint)
Set the gradient or pattern paint used to fill the drawing.
Parameters
paint The paint used to fill the drawing
Returns
The canvas to operate with
strokeStyle() [1/2]
Canvas& otto::nvg::Canvas::strokeStyle (const Color & color)
Set the color used for strokes.
Parameters
color Stroke color
Returns
The canvas to operate with
strokeStyle() [2/2]
Canvas& otto::nvg::Canvas::strokeStyle (const Paint & paint)
Set the gradient or pattern paint used for strokes.
Parameters
paint The paint used to fill the drawing
Returns
The canvas to operate with
font() [1/3]
Canvas& otto::nvg::Canvas::font (const Font & font)
Set current font for text rendering.
Note
If the face of the font is invalid ,it doesn't work
See also
NanoCanvas::Font
Parameters
font The font to use
Returns
The canvas to operate with
font() [2/3]
Canvas& otto::nvg::Canvas::font (float size)
Set font size for current text style.
Parameters
size The font size
Returns
The canvas to operate with
font() [3/3]
Canvas& otto::nvg::Canvas::font (const Font & f, float size)
Set current font and size for text rendering.
Note
If the face of the font is invalid, it doesn't work
See also
NanoCanvas::Font
Parameters
font The font to use
size The font size
Returns
The canvas to operate with
textAlign()
Canvas& otto::nvg::Canvas::textAlign (HorizontalAlign hAlign, VerticalAlign vAlign)
Sets the text alignment of current text style.
Parameters
hAlign The horizontak alignment
vAlign The verical alignment
See also
TextAlign::HorizontalAlign
TextAlign::VerticalAlign
Returns
The canvas to operate with
fillStyle() [3/3]
Canvas& otto::nvg::Canvas::fillStyle (const TextStyle & textStyle)
Set styles for text rendering.
Parameters
textStyle The text style to use
See also
NanoCanvas::TextStyle
Returns
The canvas to operate with
createLinearGradient()
static Paint otto::nvg::Canvas::createLinearGradient (float x0, float y0, float x1, float y1, const Color & scolor, const Color & ecolor) static
Creates a linear gradient (to use on canvas content)
Parameters
x0 The x-coordinate of the start point of the gradient
y0 The y-coordinate of the start point of the gradient
x1 The x-coordinate of the end point of the gradient
y1 The y-coordinate of the end point of the gradient
scolor The start color
outter The end color
Returns
The created gradient style object.
createRadialGradient()
static Paint otto::nvg::Canvas::createRadialGradient (float cx, float cy, float r1, float r2, const Color & icolor, const Color & ocolor) static
Creates a radial/circular gradient (to use on canvas content)
Parameters
cx The x-coordinate of the circle of the gradient
cy The y-coordinate of the circle of the gradient
r1 The radius of the inner circle
r2 The radius of the outter circle
icolor The color on inner circle
ocolor The color on outer circle
Returns
The created gradient style object.
createBoxGradient()
static Paint otto::nvg::Canvas::createBoxGradient (float x, float y, float w, float h, float r, float f, Color icol, Color ocol) static
Creates and returns a box gradient.
Box gradient is a feathered rounded rectangle, it is useful for rendering drop shadows or highlights for
boxes.
Parameters
x The x-coordinate of the upper-left corner of the rectangle
y The y-coordinate of the upper-left corner of the rectangle
w The width of the rectangle, in pixels
h The height of the rectangle, in pixels
r The radius of the circle formed by 4 corners of the rounded rectangle
f How blurry the border of the rectangle is
icol The inner color of the gradient
ocol The outer color of the gradient
Returns
The created gradient style object.
createPattern()
static Paint otto::nvg::Canvas::createPattern (const Image & image, float ox, float oy, float w, float h, float angle = 0.0f, float alpha = 1.0f) static
Creates and returns an image pattern paint.
Parameters
image Specifies the image of the pattern to use
ox The x-coordinate of the upper-left corner of the image would be draw
oy The y-coordinate of the upper-left corner of the image would be draw
w The width of the pattern
h The height of the pattern
angle The rotation around the top-left corner in radians
alpha The transparent of the image pattern
Returns
The patter paint created
measureText() [1/3]
float otto::nvg::Canvas::measureText (const std::string & text, float rowWidth = NAN)
Check the width of the text, before writing it on the canvas.
Parameters
text The text to be measured
rowWidth The max row width of the text box,NAN is not limited
Returns
The width of the specified text
measureText() [2/3]
float otto::nvg::Canvas::measureText (const std::string & text, float x, float y, float * bounds, float rowWidth = NAN)
Check the boundary of the text, before writing it on the canvas.
Parameters
text The text to be measured
x The x-coordinate of the text
y The y-coordinate of the text
bounds [in] The float array to store boundary values should be a pointer to float[4]
rowWidth The max row width of the text box,NAN is not limited
Returns
The width of the specified text
measureText() [3/3]
Box otto::nvg::Canvas::measureText (const std::string & text, Point p, float rowWidth = NAN)
globalCompositeOperation()
Canvas& otto::nvg::Canvas::globalCompositeOperation (CompositeOperation op)
scale()
Canvas& otto::nvg::Canvas::scale (float scalewidth, float scaleheight)
Scales the current drawing, bigger or smaller.
Note
If you scale a drawing, all future drawings will also be scaled. The positioning will also be scaled. If you scale(2,2); drawings will be positioned twice as far from the left and top of the canvas as you specify.
Parameters
scalewidth Scales the width of the current drawing (1=100%, 0.5=50%, 2=200%, etc.)
scaleheight Scales the height of the current drawing (1=100%, 0.5=50%, 2=200%, etc.)
Returns
The canvas to scale with
scaleTowards()
Canvas& otto::nvg::Canvas::scaleTowards (float s, Point p)
Scales the current drawing, bigger or smaller.
Note
If you scale a drawing, all future drawings will also be scaled. The positioning will also be scaled. If you scale(2,2); drawings will be positioned twice as far from the left and top of the canvas as you specify.
Parameters
s Scales the width and height of the current drawing (1=100%, 0.5=50%, 2=200%, etc.)
p the point to scale towards (the point that doesnt move)
Returns
The canvas to scale with
rotate()
Canvas& otto::nvg::Canvas::rotate (float angle)
Rotates the current drawing.
Note
: The rotation will only affect drawings made AFTER the rotation is done.
To calculate from degrees to radians: degrees*Math.PI/180.
Example: to rotate 5 degrees, specify the following: 5*Math.PI/180
Parameters
angle The rotation angle, in radians.
Returns
The canvas to rotate with
rotateAround()
Canvas& otto::nvg::Canvas::rotateAround (float r, Point p)
Rotates the current drawing.
Note
: The rotation will only affect drawings made AFTER the rotation is done.
To calculate from degrees to radians: degrees*Math.PI/180.
Example: to rotate 5 degrees, specify the following: 5*Math.PI/180
Parameters
angle The rotation angle, in radians.
p The point to rotate around.
Returns
The canvas to rotate with
translate() [1/2]
Canvas& otto::nvg::Canvas::translate (float x, float y)
Remaps the (0,0) position on the canvas.
Note
When you call a method such as fillRect() after translate(), the value is added to the x- and y-coordinate values.
Parameters
x The value to add to horizontal (x) coordinates
y The value to add to vertical (y) coordinates
Returns
The canvas to translate with
translate() [2/2]
Canvas& otto::nvg::Canvas::translate (Point p)
transform()
Canvas& otto::nvg::Canvas::transform (float a, float b, float c, float d, float e, float f)
Replaces the current transformation matrix for the drawing.
Each object on the canvas has a current transformation matrix. @n
The transform() method replaces the current transformation matrix. It multiplies the current transformation matrix with the matrix described by:
a c e
b d f
0 0 1
In other words, the transform() method lets you scale, rotate, move, and skew the current context.
Note
The transformation will only affect drawings made after the transform() method is called.
The transform() method behaves relatively to other transformations made by rotate(), scale(), translate(), or transform(). Example: If you already have set your drawing to scale by two, and the transform() method scales your drawings by two, your drawings will now scale by four.
Tip: Check out the setTransform() method, which does not behave relatively to other transformations.
Parameters
a Scales the drawing horizontally
b Skew the the drawing horizontally
c Skew the the drawing vertically
d Scales the drawing vertically
e Moves the the drawing horizontally
f Moves the the drawing vertically
Returns
The canvas to transform with
setTransform()
Canvas& otto::nvg::Canvas::setTransform (float a, float b, float c, float d, float e, float f)
Resets the current transform to the identity matrix.
Then runs transform()
Parameters
a Scales the drawing horizontally
b Skew the the drawing horizontally
c Skew the the drawing vertically
d Scales the drawing vertically
e Moves the the drawing horizontally
f Moves the the drawing vertically
See also
Canvas::transform()
Canvas::restTransform()
Returns
The canvas to set transform with
restTransform()
Canvas& otto::nvg::Canvas::restTransform ()
Resets the current transform to the identity matrix.
Returns
The canvas to set transform with
beginFrame()
Canvas& otto::nvg::Canvas::beginFrame (int windowWidth, int windowHeight)
Begin drawing a new frame.
Calls to Canvas drawing API should be wrapped in beginFrame() & endFrame() beginFrame() defines the size of the window to render to in relation currently set viewport (i.e. glViewport on GL backends).
Parameters
windowWidth Width of your window
windowHeight Height of your window
Returns
The canvas to begin frame with
cancelFrame()
Canvas& otto::nvg::Canvas::cancelFrame ()
Cancels drawing the current frame.
Returns
The canvas to cancle draw
endFrame()
void otto::nvg::Canvas::endFrame ()
Ends drawing flushing remaining render state.
beginPath()
Canvas& otto::nvg::Canvas::beginPath ()
Begins a path, or resets the current path.
Returns
The canvas to create path
pathWinding()
Canvas& otto::nvg::Canvas::pathWinding (Winding dir)
Sets the current path winding.
Parameters
dir CVS_CW or CVS_CW
Returns
The canvas to operate with
clip()
Canvas& otto::nvg::Canvas::clip (float x, float y, float w, float h)
Clip of a rectangular region.
Parameters
x The x-coordinate of the upper-left corner of the clip region
y The y-coordinate of the upper-left corner of the clip region
w The width of the clip region, in pixels
h The width of the clip region, in pixels
Returns
The canvas to clip with
resetClip()
Canvas& otto::nvg::Canvas::resetClip ()
Reset clip state ,remove all clip region.
Returns
The canvas to reset
save()
Canvas& otto::nvg::Canvas::save ()
Pushe and save the current render state into a state stack.
Note
A matching restore() must be used to restore the state.
Returns
The canvas to save state
restore()
Canvas& otto::nvg::Canvas::restore ()
Pop and restore current render state.
Returns
The canvas to restore state
reset()
Canvas& otto::nvg::Canvas::reset ()
Resets current render state to default values.
Does not affect the render state stack.
Returns
The canvas to reset state
valid()
bool otto::nvg::Canvas::valid () const
Check is the context avaliable.
Returns
Is the context avaliable
Definition at line 799 of file Canvas.hpp.
setSize()
Canvas& otto::nvg::Canvas::setSize (float width, float height)
Set canvas size.
Parameters
width The width of the canvas, in pixels
height The height of the canvas, in pixels
Returns
The canvas to resize
Definition at line 810 of file Canvas.hpp.
References otto::core::ui::vg::height, and otto::core::ui::vg::width.
setPosition()
Canvas& otto::nvg::Canvas::setPosition (float x, float y)
Set position of the canvas.
Parameters
x The x-coordinate of the upper-left corner of the rectangle
y The y-coordinate of the upper-left corner of the rectangle
Returns
The canvas to change position
Definition at line 823 of file Canvas.hpp.
setScaleRatio()
Canvas& otto::nvg::Canvas::setScaleRatio (float ratio)
Set scale ration of the canvas.
Device pixel ration allows to control the rendering on Hi-DPI devices. For example, GLFW returns two dimension for an opened window: window size and frame buffer size. In that case you would set windowWidth/Height to the window size devicePixelRatio to: frameBufferWidth / windowWidth.
Parameters
ratio The device pixel ration
Returns
The canvas to set scale ration with
Definition at line 841 of file Canvas.hpp.
local2Global()
void otto::nvg::Canvas::local2Global (float & x, float & y)
Convert coordinates in canvas to coordinates in windows.
Parameters
x [inout] The x-coordinate to convert
y [inout] The x-coordinate to convert
Definition at line 852 of file Canvas.hpp.
global2Local()
void otto::nvg::Canvas::global2Local (float & x, float & y)
Convert coordinates in windows to coordinates in canvas.
Parameters
x [inout] The x-coordinate to convert
y [inout] The x-coordinate to convert
Definition at line 863 of file Canvas.hpp.
nvgContext()
NVGcontext* otto::nvg::Canvas::nvgContext ()
Get the NanoVG context for advanced contol.
Returns
The NanoVG context of this canvas
Definition at line 874 of file Canvas.hpp.
Member Data Documentation
m_nvgCtx
NVGcontext* otto::nvg::Canvas::m_nvgCtx protected
The NanoVG context.
Definition at line 881 of file Canvas.hpp.
m_width
float otto::nvg::Canvas::m_width protected
The width of the canvas.
Definition at line 883 of file Canvas.hpp.
m_height
float otto::nvg::Canvas::m_height protected
The height of the canvas.
Definition at line 885 of file Canvas.hpp.
m_scaleRatio
float otto::nvg::Canvas::m_scaleRatio protected
Buffer / window size ratio.
Definition at line 887 of file Canvas.hpp.
m_xPos
float otto::nvg::Canvas::m_xPos protected
The x-coordinate of the canvas in window.
Definition at line 889 of file Canvas.hpp.
m_yPos
float otto::nvg::Canvas::m_yPos protected
The y-coordinate of the canvas in window.
Definition at line 891 of file Canvas.hpp.
The documentation for this class was generated from the following file:
/home/travis/build/topisani/OTTO/src/core/ui/nvg/Canvas.hpp