OTTO: otto::core::audio::FaustOptions Struct Reference
otto::core::audio::FaustOptions Struct Reference
#include <faust.hpp>
Public Member Functions
FaustOptions (FaustClient &client)
void openTabBox (const char *label) override
void openHorizontalBox (const char *label) override
void openVerticalBox (const char *label) override
void closeBox () override
void addHorizontalBargraph (const char *label, FAUSTFLOAT *zone, FAUSTFLOAT min, FAUSTFLOAT max) override
void addVerticalBargraph (const char *label, FAUSTFLOAT *zone, FAUSTFLOAT min, FAUSTFLOAT max) override
void addButton (const char *label, FAUSTFLOAT *zone) override
void addCheckButton (const char *label, FAUSTFLOAT *zone) override
void addVerticalSlider (const char *label, FAUSTFLOAT *zone, FAUSTFLOAT init, FAUSTFLOAT min, FAUSTFLOAT max, FAUSTFLOAT step) override
void addHorizontalSlider (const char *label, FAUSTFLOAT *zone, FAUSTFLOAT init, FAUSTFLOAT min, FAUSTFLOAT max, FAUSTFLOAT step) override
void addNumEntry (const char *label, FAUSTFLOAT *zone, FAUSTFLOAT init, FAUSTFLOAT min, FAUSTFLOAT max, FAUSTFLOAT step) override
void registerOption (const char *label, FAUSTFLOAT *ptr, FAUSTFLOAT init, FAUSTFLOAT min, FAUSTFLOAT max, FAUSTFLOAT step, FaustLink::Type type=FaustLink::Type::ToFaust)
Public Attributes
FaustClient & client
Detailed Description
Definition at line 34 of file faust.hpp.
Constructor & Destructor Documentation
FaustOptions()
otto::core::audio::FaustOptions::FaustOptions (FaustClient & client) inline
Definition at line 35 of file faust.hpp.
 : client(client) {}
Member Function Documentation
addButton()
void otto::core::audio::FaustOptions::addButton (const char * label, FAUSTFLOAT * zone) inline override
Definition at line 82 of file faust.hpp.
References registerOption().
     {
       this->registerOption(label, zone, 0, 0, 1, 1);
     }
addCheckButton()
void otto::core::audio::FaustOptions::addCheckButton (const char * label, FAUSTFLOAT * zone) inline override
Definition at line 87 of file faust.hpp.
References registerOption().
     {
       this->registerOption(label, zone, 0, 0, 1, 1);
     }
addHorizontalBargraph()
void otto::core::audio::FaustOptions::addHorizontalBargraph (const char * label, FAUSTFLOAT * zone, FAUSTFLOAT min, FAUSTFLOAT max) inline override
Definition at line 66 of file faust.hpp.
References otto::core::props::FaustLink::FromFaust, and registerOption().
Referenced by addVerticalBargraph().
     {
       registerOption(label, zone, 0, min, max, 0, FaustLink::Type::FromFaust);
     }
addHorizontalSlider()
void otto::core::audio::FaustOptions::addHorizontalSlider (const char * label, FAUSTFLOAT * zone, FAUSTFLOAT init, FAUSTFLOAT min, FAUSTFLOAT max, FAUSTFLOAT step) inline override
Definition at line 102 of file faust.hpp.
References registerOption().
     {
       this->registerOption(label, zone, init, min, max, step);
     }
addNumEntry()
void otto::core::audio::FaustOptions::addNumEntry (const char * label, FAUSTFLOAT * zone, FAUSTFLOAT init, FAUSTFLOAT min, FAUSTFLOAT max, FAUSTFLOAT step) inline override
Definition at line 112 of file faust.hpp.
References registerOption().
     {
       this->registerOption(label, zone, init, min, max, step);
     }
addVerticalBargraph()
void otto::core::audio::FaustOptions::addVerticalBargraph (const char * label, FAUSTFLOAT * zone, FAUSTFLOAT min, FAUSTFLOAT max) inline override
Definition at line 74 of file faust.hpp.
References addHorizontalBargraph().
     {
       addHorizontalBargraph(label, zone, min, max);
     }
addVerticalSlider()
void otto::core::audio::FaustOptions::addVerticalSlider (const char * label, FAUSTFLOAT * zone, FAUSTFLOAT init, FAUSTFLOAT min, FAUSTFLOAT max, FAUSTFLOAT step) inline override
Definition at line 92 of file faust.hpp.
References registerOption().
     {
       this->registerOption(label, zone, init, min, max, step);
     }
closeBox()
void otto::core::audio::FaustOptions::closeBox () inline override
Definition at line 62 of file faust.hpp.
     {
       if (!boxes.empty()) boxes.pop_back();
     }
openHorizontalBox()
void otto::core::audio::FaustOptions::openHorizontalBox (const char * label) inline override
Definition at line 46 of file faust.hpp.
     {
       if (atRoot) {
         atRoot = false;
       } else {
         boxes.push_back(label);
       }
     }
openTabBox()
void otto::core::audio::FaustOptions::openTabBox (const char * label) inline override
Definition at line 37 of file faust.hpp.
     {
       if (atRoot) {
         atRoot = false;
       } else {
         boxes.push_back(label);
       }
     }
openVerticalBox()
void otto::core::audio::FaustOptions::openVerticalBox (const char * label) inline override
Definition at line 54 of file faust.hpp.
     {
       if (atRoot) {
         atRoot = false;
       } else {
         boxes.push_back(label);
       }
     }
registerOption()
void otto::core::audio::FaustOptions::registerOption (const char * label, FAUSTFLOAT * ptr, FAUSTFLOAT init, FAUSTFLOAT min, FAUSTFLOAT max, FAUSTFLOAT step, FaustLink::Type type = FaustLink::Type::ToFaust) inline
Definition at line 122 of file faust.hpp.
References client.
Referenced by addButton(), addCheckButton(), addHorizontalBargraph(), addHorizontalSlider(), addNumEntry(), and addVerticalSlider().
     {
       boxes.emplace_back(label);
       client.register_link(std::begin(boxes), std::end(boxes), FaustLink{ptr, type});
       boxes.pop_back();
     }
Member Data Documentation
client
FaustClient& otto::core::audio::FaustOptions::client
Definition at line 135 of file faust.hpp.
Referenced by otto::core::audio::detail::register_faust_wrapper_events(), and registerOption().
The documentation for this struct was generated from the following file:
/home/topisani/dev/OTTO/src/core/audio/faust.hpp