OTTO: otto::core::engines::AnyEngine Struct Reference
otto::core::engines::AnyEngine Struct Reference
#include <engine.hpp>
Public Member Functions
AnyEngine (std::string const &name, props::properties_base &props, std::unique_ptr< ui::Screen > screen)
AnyEngine ()=delete
virtual ~AnyEngine ()=default
virtual void on_enable ()
virtual void on_disable ()
const std::string & name () const noexcept
The name of this module.
ui::Screen & screen () noexcept
const ui::Screen & screen () const noexcept
int current_preset () const noexcept
int current_preset (int new_val) noexcept
nlohmann::json to_json () const
void from_json (const nlohmann::json &j)
props::properties_base & props () noexcept
props::properties_base const & props () const noexcept
Detailed Description
Abstract base class for Engines
Use this when refering to a generic engine
Definition at line 37 of file engine.hpp.
Constructor & Destructor Documentation
AnyEngine() [1/2]
otto::core::engines::AnyEngine::AnyEngine (std::string const & name, props::properties_base & props, std::unique_ptr< ui::Screen > screen)
Definition at line 9 of file engine.cpp.
     : _props(props),
       _name(name),
       _screen(std::move(screen))
   {}
AnyEngine() [2/2]
otto::core::engines::AnyEngine::AnyEngine () delete
~AnyEngine()
virtual otto::core::engines::AnyEngine::~AnyEngine () virtual default
Member Function Documentation
current_preset() [1/2]
int otto::core::engines::AnyEngine::current_preset () const noexcept
The currently selected preset
Returns
-1 if no preset has been set
Definition at line 43 of file engine.cpp.
Referenced by otto::service::presets::apply_preset().
   {
     return _current_preset;
   }
current_preset() [2/2]
int otto::core::engines::AnyEngine::current_preset (int new_val) noexcept
Set the current preset
Should only be called from [presets::apply_preset]()
Returns
new_val
Definition at line 48 of file engine.cpp.
   {
     return _current_preset = new_val;
   }
from_json()
void otto::core::engines::AnyEngine::from_json (const nlohmann::json & j)
Deserialize the engine
If a preset was set, apply it. Then deserialize the properties.
See also
to_json
Exceptions
same as [presets::apply_preset(AnyEngine&, const std::string&)] if the json contains a preset name. [nlohmann::json::exception](), see it for details.
Definition at line 67 of file engine.cpp.
References otto::service::presets::apply_preset(), otto::core::props::property_base::as(), and props().
   {
     if (j.is_object()) {
       auto iter = j.find("preset");
       if (iter != j.end()) {
         service::presets::apply_preset(*this, iter->get<std::string>(), true);
       }
       if (props().is<props::serializable>())
         props().as<props::serializable>().from_json(j["props"]);
     }
   }
name()
const std::string & otto::core::engines::AnyEngine::name () const noexcept
The name of this module.
Definition at line 18 of file engine.cpp.
Referenced by otto::service::presets::apply_preset(), and otto::service::ui::select_engine().
   {
     return _name;
   }
on_disable()
virtual void otto::core::engines::AnyEngine::on_disable () inline virtual
Called when this module is disabled
The samplers use this to load the sample file.
TODO: Define "disabled" None
Definition at line 62 of file engine.hpp.
 {}
on_enable()
virtual void otto::core::engines::AnyEngine::on_enable () inline virtual
Called when this module is enabled
The samplers use this to load the sample file.
TODO: Define "enabled" None
Reimplemented in otto::engines::Euclid.
Definition at line 54 of file engine.hpp.
Referenced by otto::service::presets::apply_preset(), and otto::core::engines::EngineDispatcher< ET >::select().
 {}
props() [1/2]
props::properties_base & otto::core::engines::AnyEngine::props () noexcept
Definition at line 33 of file engine.cpp.
Referenced by otto::service::presets::apply_preset(), from_json(), and to_json().
   {
     return _props;
   }
props() [2/2]
props::properties_base const & otto::core::engines::AnyEngine::props () const noexcept
Definition at line 38 of file engine.cpp.
   {
     return _props;
   }
screen() [1/2]
ui::Screen & otto::core::engines::AnyEngine::screen () noexcept
Definition at line 23 of file engine.cpp.
Referenced by otto::engines::Euclid::Euclid(), otto::engines::Euclid::on_enable(), and otto::service::ui::select_engine().
   {
     return *_screen;
   }
screen() [2/2]
ui::Screen const & otto::core::engines::AnyEngine::screen () const noexcept
Definition at line 28 of file engine.cpp.
   {
     return *_screen;
   }
to_json()
nlohmann::json otto::core::engines::AnyEngine::to_json () const
Serialize the engine
Format
{
  "preset": "<preset_name>",
  "props": "<props.to_json()>"
}
"preset" is omitted if presets::name_of_idx(current_preset()) throws an exception. <props.to_json()> is the serialized properties
Exceptions
[nlohmann::json::exception](),see it for details.
Definition at line 53 of file engine.cpp.
References otto::core::props::property_base::as(), otto::service::presets::name_of_idx(), and props().
   {
     nlohmann::json j;
     if (props().is<props::serializable>()) {
       j["props"] = props().as<props::serializable>().to_json();
       try {
         j["preset"] = service::presets::name_of_idx(_name, _current_preset);
       } catch (service::presets::exception& e) {
         // no preset set, all is good
       }
     }
     return j;
   }
The documentation for this struct was generated from the following files:
/home/topisani/dev/OTTO/src/core/engines/engine.hpp
/home/topisani/dev/OTTO/src/core/engines/engine.cpp