OTTO: otto::core::clock::ClockRange Struct Reference
otto::core::clock::ClockRange Struct Reference
Detailed Description
Definition at line 25 of file clock.hpp.
#include <clock.hpp>
Public Member Functions
operator Time () const
The lowest time in this range.
Time time () const
The lowest time in this range.
bool contains_multiple (Time n) const noexcept
Check whether this range contains a multiple of n.
int count_multiple (Time n) const noexcept
Counts the number of times this range contains a multiple of n.
int position_of_multiple (Time n) const noexcept
Public Attributes
Time begin
Time end
Member Function Documentation
operator Time()
otto::core::clock::ClockRange::operator Time () const
The lowest time in this range.
Definition at line 30 of file clock.hpp.
References time().
time()
Time otto::core::clock::ClockRange::time () const
The lowest time in this range.
Definition at line 36 of file clock.hpp.
References begin.
Referenced by operator Time().
contains_multiple()
bool otto::core::clock::ClockRange::contains_multiple (Time n) const noexcept
Check whether this range contains a multiple of n.
@requires count > 0
Definition at line 44 of file clock.hpp.
References count_multiple().
count_multiple()
int otto::core::clock::ClockRange::count_multiple (Time n) const noexcept
Counts the number of times this range contains a multiple of n.
@requires count > 0
Definition at line 52 of file clock.hpp.
References begin, end, std::max(), and OTTO_ASSERT.
Referenced by contains_multiple().
position_of_multiple()
int otto::core::clock::ClockRange::position_of_multiple (Time n) const noexcept
Definition at line 58 of file clock.hpp.
References begin, and OTTO_ASSERT.
Member Data Documentation
begin
Time otto::core::clock::ClockRange::begin
Definition at line 26 of file clock.hpp.
Referenced by count_multiple(), position_of_multiple(), and time().
end
Time otto::core::clock::ClockRange::end
Definition at line 27 of file clock.hpp.
Referenced by count_multiple(), and otto::core::clock::ClockCounter::step().
The documentation for this struct was generated from the following file:
/home/travis/build/topisani/OTTO/src/core/audio/clock.hpp