OTTO: otto::core::midi::ControlChangeEvent Struct Reference
otto::core::midi::ControlChangeEvent Struct Reference
Detailed Description
Definition at line 139 of file midi.hpp.
#include <midi.hpp>
Public Member Functions
ControlChangeEvent (const MidiEvent &event)
std::array< byte, 3 > to_bytes ()
Public Member Functions inherited from otto::core::midi::MidiEvent
std::array< byte, 1 > to_bytes ()
Static Public Member Functions
static ControlChangeEvent from_bytes (gsl::span< byte > bytes, int time=0)
Static Public Member Functions inherited from otto::core::midi::MidiEvent
static MidiEvent from_bytes (gsl::span< byte > bytes, int time=0)
Public Attributes
int controler = 0
int value = 0
Public Attributes inherited from otto::core::midi::MidiEvent
Type type
int channel
int time
Additional Inherited Members
Public Types inherited from otto::core::midi::MidiEvent
enum Type { Type::NoteOff = 0b1000, Type::NoteOn = 0b1001, Type::ControlChange = 0b1011 }
using byte = unsigned char
Static Public Attributes inherited from otto::core::midi::MidiEvent
static constexpr std::size_t max_data_size = 2
Constructor & Destructor Documentation
ControlChangeEvent()
otto::core::midi::ControlChangeEvent::ControlChangeEvent (const MidiEvent & event)
Definition at line 143 of file midi.hpp.
Referenced by from_bytes().
Member Function Documentation
to_bytes()
std::array<byte, 3> otto::core::midi::ControlChangeEvent::to_bytes ()
Definition at line 145 of file midi.hpp.
References otto::core::midi::MidiEvent::channel, controler, otto::core::midi::MidiEvent::type, and value.
from_bytes()
static ControlChangeEvent otto::core::midi::ControlChangeEvent::from_bytes (gsl::span< byte > bytes, int time = 0) static
Definition at line 150 of file midi.hpp.
References ControlChangeEvent(), otto::core::midi::MidiEvent::from_bytes(), and otto::core::midi::MidiEvent::time.
Referenced by otto::core::midi::from_bytes().
Member Data Documentation
controler
int otto::core::midi::ControlChangeEvent::controler = 0
Definition at line 140 of file midi.hpp.
Referenced by to_bytes().
value
int otto::core::midi::ControlChangeEvent::value = 0
Definition at line 141 of file midi.hpp.
Referenced by to_bytes().
The documentation for this struct was generated from the following file:
/home/travis/build/topisani/OTTO/src/core/audio/midi.hpp