OTTO: otto::util::wrapping_array< T, N > Struct Template Reference
otto::util::wrapping_array< T, N > Struct Template Reference
#include <ringbuffer.hpp>
Classes
struct IteratorImpl
Specification for iterator.
Public Types
using value_type = T
using iterator = util::iterator_adaptor< IteratorImpl< value_type > >
using const_iterator = util::iterator_adaptor< IteratorImpl< const value_type > >
Public Member Functions
iterator begin ()
const_iterator begin () const
value_type * data ()
iterator iter (std::size_t index)
const_iterator iter (std::size_t index) const
const_iterator citer (std::size_t index) const
value_type & operator[] (std::size_t idx)
Static Public Member Functions
static constexpr std::size_t wrap (std::size_t index)
Get the buffer position corresponding to position
Public Attributes
std::array< value_type, size > storage
Static Public Attributes
static constexpr std::size_t size = N
Detailed Description
template<typename T, std::size_t N>
struct otto::util::wrapping_array< T, N >
Definition at line 13 of file ringbuffer.hpp.
Member Typedef Documentation
value_type
template<typename T, std::size_t N> using otto::util::wrapping_array< T, N >::value_type = T
Definition at line 57 of file ringbuffer.hpp.
iterator
template<typename T, std::size_t N> using otto::util::wrapping_array< T, N >::iterator = util::iterator_adaptor<IteratorImpl<value_type> >
Definition at line 59 of file ringbuffer.hpp.
const_iterator
template<typename T, std::size_t N> using otto::util::wrapping_array< T, N >::const_iterator = util::iterator_adaptor<IteratorImpl<const value_type> >
Definition at line 60 of file ringbuffer.hpp.
Member Function Documentation
wrap()
template<typename T, std::size_t N> static constexpr std::size_t otto::util::wrapping_array< T, N >::wrap (std::size_t index) static
Get the buffer position corresponding to position
Definition at line 17 of file ringbuffer.hpp.
Referenced by otto::util::wrapping_array< T, N >::IteratorImpl< Val >::advance(), and otto::util::wrapping_array< float, N >::operator[]().
begin() [1/2]
template<typename T, std::size_t N> iterator otto::util::wrapping_array< T, N >::begin ()
Definition at line 62 of file ringbuffer.hpp.
begin() [2/2]
template<typename T, std::size_t N> const_iterator otto::util::wrapping_array< T, N >::begin () const
Definition at line 63 of file ringbuffer.hpp.
data()
template<typename T, std::size_t N> value_type* otto::util::wrapping_array< T, N >::data ()
Definition at line 64 of file ringbuffer.hpp.
iter() [1/2]
template<typename T, std::size_t N> iterator otto::util::wrapping_array< T, N >::iter (std::size_t index)
Definition at line 66 of file ringbuffer.hpp.
Referenced by otto::util::ringbuffer< float, N >::begin(), and otto::util::ringbuffer< float, N >::end().
iter() [2/2]
template<typename T, std::size_t N> const_iterator otto::util::wrapping_array< T, N >::iter (std::size_t index) const
Definition at line 67 of file ringbuffer.hpp.
citer()
template<typename T, std::size_t N> const_iterator otto::util::wrapping_array< T, N >::citer (std::size_t index) const
Definition at line 68 of file ringbuffer.hpp.
Referenced by otto::util::ringbuffer< float, N >::begin(), and otto::util::ringbuffer< float, N >::end().
operator[]()
template<typename T, std::size_t N> value_type& otto::util::wrapping_array< T, N >::operator[] (std::size_t idx)
Definition at line 70 of file ringbuffer.hpp.
Member Data Documentation
size
template<typename T, std::size_t N> constexpr std::size_t otto::util::wrapping_array< T, N >::size = N static
Definition at line 14 of file ringbuffer.hpp.
Referenced by otto::util::wrapping_array< float, N >::wrap().
storage
template<typename T, std::size_t N> std::array<value_type, size> otto::util::wrapping_array< T, N >::storage
Definition at line 58 of file ringbuffer.hpp.
Referenced by otto::util::wrapping_array< float, N >::begin(), otto::util::wrapping_array< float, N >::citer(), otto::util::wrapping_array< float, N >::data(), otto::util::ringbuffer< float, N >::data(), otto::util::wrapping_array< float, N >::iter(), otto::util::wrapping_array< float, N >::operator[](), otto::util::ringbuffer< float, N >::operator[](), and otto::util::ringbuffer< float, N >::push().
The documentation for this struct was generated from the following file:
/home/topisani/dev/OTTO/src/util/ringbuffer.hpp