OTTO: otto::engines::NukeSynth Struct Reference
otto::engines::NukeSynth Struct Reference
#include <nuke.hpp>
Classes
struct Props
Public Member Functions
NukeSynth ()
audio::ProcessData< 1 > process (audio::ProcessData< 1 >) override
ui::Screen & envelope_screen () override
ui::Screen & voices_screen () override
Public Member Functions inherited from otto::core::engines::AnyEngine
AnyEngine (std::string const &name, props::properties_base &props, std::unique_ptr< ui::Screen > screen)
AnyEngine ()=delete
virtual ~AnyEngine ()=default
virtual void on_enable ()
virtual void on_disable ()
const std::string & name () const noexcept
The name of this module.
ui::Screen & screen () noexcept
const ui::Screen & screen () const noexcept
int current_preset () const noexcept
int current_preset (int new_val) noexcept
nlohmann::json to_json () const
void from_json (const nlohmann::json &j)
props::properties_base & props () noexcept
props::properties_base const & props () const noexcept
Public Attributes
otto::engines::NukeSynth::Props props
Detailed Description
Definition at line 14 of file nuke.hpp.
Constructor & Destructor Documentation
NukeSynth()
otto::engines::NukeSynth::NukeSynth ()
Definition at line 28 of file nuke.cpp.
     : SynthEngine("Nuke", props, std::make_unique<NukeSynthScreen>(this)),
       voice_mgr_(props),
       faust_(std::make_unique<FAUSTCLASS>(), props)
 {}
Member Function Documentation
envelope_screen()
ui::Screen& otto::engines::NukeSynth::envelope_screen () inline override virtual
Implements otto::core::engines::EngineWithEnvelope.
Definition at line 29 of file nuke.hpp.
{
       return voice_mgr_.envelope_screen();
     }
process()
audio::ProcessData< 1 > otto::engines::NukeSynth::process (audio::ProcessData< 1 > data) override virtual
Implements otto::core::engines::Engine< EngineType::synth >.
Definition at line 34 of file nuke.cpp.
References otto::core::audio::FaustWrapper< Cin, Cout >::process(), otto::core::audio::VoiceManager< N >::process_after(), and otto::core::audio::VoiceManager< N >::process_before().
 {
     voice_mgr_.process_before(data.midi_only());
     auto res = faust_.process(data.midi_only());
     voice_mgr_.process_after(data.midi_only());
     return res;
 }
voices_screen()
ui::Screen& otto::engines::NukeSynth::voices_screen () inline override virtual
Implements otto::core::engines::EngineWithEnvelope.
Definition at line 33 of file nuke.hpp.
{
       return voice_mgr_.settings_screen();
     }
Member Data Documentation
props
otto::engines::NukeSynth::Props otto::engines::NukeSynth::props
The documentation for this struct was generated from the following files:
/home/topisani/dev/OTTO/src/engines/synths/nuke/nuke.hpp
/home/topisani/dev/OTTO/src/engines/synths/nuke/nuke.cpp