OTTO: otto::core::props::property_base Struct Reference
otto::core::props::property_base Struct Reference
Base class of all properties, leaves and branches both.
#include <base.hpp>
Public Member Functions
property_base (branch_base *parent=nullptr, std::string const &name="")
virtual ~property_base ()=default
const std::string & name () const noexcept
branch_base const *const parent () const noexcept
template<typename Tag >
bool is () const noexcept
template<typename Tag >
mixin::interface< Tag > & as ()
template<typename Tag >
mixin::interface< Tag > const & as () const
bool is_branch () const noexcept
template<typename Tag >
mixin::branch< Tag > & as_branch ()
template<typename Tag >
mixin::branch< Tag > const & as_branch () const
Detailed Description
Base class of all properties, leaves and branches both.
Definition at line 36 of file base.hpp.
Constructor & Destructor Documentation
property_base()
otto::core::props::property_base::property_base (branch_base * parent = nullptr, std::string const & name = "")
Definition at line 5 of file base.cpp.
References parent(), and otto::core::props::branch_base::push_back().
~property_base()
virtual otto::core::props::property_base::~property_base () virtual default
Member Function Documentation
name()
const std::string& otto::core::props::property_base::name () const noexcept
Definition at line 41 of file base.hpp.
parent()
branch_base const* const otto::core::props::property_base::parent () const noexcept
Definition at line 46 of file base.hpp.
Referenced by property_base().
is()
template<typename Tag > bool otto::core::props::property_base::is () const noexcept
Definition at line 52 of file base.hpp.
as() [1/2]
template<typename Tag > mixin::interface<Tag>& otto::core::props::property_base::as ()
Definition at line 58 of file base.hpp.
Referenced by otto::service::presets::apply_preset(), otto::core::engines::AnyEngine::from_json(), otto::core::props::OTTO_PROPS_MIXIN_BRANCH(), and otto::core::engines::AnyEngine::to_json().
as() [2/2]
template<typename Tag > mixin::interface<Tag> const& otto::core::props::property_base::as () const
Definition at line 64 of file base.hpp.
is_branch()
bool otto::core::props::property_base::is_branch () const noexcept
Definition at line 119 of file base.hpp.
as_branch() [1/2]
template<typename Tag > mixin::branch<Tag>& otto::core::props::property_base::as_branch ()
Definition at line 72 of file base.hpp.
as_branch() [2/2]
template<typename Tag > mixin::branch<Tag> const& otto::core::props::property_base::as_branch () const
Definition at line 78 of file base.hpp.
The documentation for this struct was generated from the following files:
/home/topisani/dev/OTTO/src/core/props/internal/base.hpp
/home/topisani/dev/OTTO/src/core/props/internal/base.cpp