OTTO: otto::test::measure Struct Reference
otto::test::measure Struct Reference
Detailed Description
Definition at line 27 of file testing.t.hpp.
#include <testing.t.hpp>
Public Types
using TimeT = std::chrono::nanoseconds
Static Public Member Functions
template<typename F , typename... Args>
static auto execution (F &&func, Args &&... args)
Member Typedef Documentation
TimeT
using otto::test::measure::TimeT = std::chrono::nanoseconds
Definition at line 28 of file testing.t.hpp.
Member Function Documentation
execution()
template<typename F , typename... Args> static auto otto::test::measure::execution (F && func, Args &&... args) static
Definition at line 31 of file testing.t.hpp.
References std::chrono::duration_cast(), std::forward(), std::chrono::steady_clock::now(), and otto::service::audio::start().
The documentation for this struct was generated from the following file:
/home/travis/build/topisani/OTTO/test/testing.t.hpp