OTTO: otto::util::ref_vec< T > Struct Template Reference
otto::util::ref_vec< T > Struct Template Reference
Detailed Description
template<typename T>
struct otto::util::ref_vec< T >
A vector of references to T.
Definition at line 529 of file ptr_vec.hpp.
#include <ptr_vec.hpp>
Public Types
using value_type = std::decay_t< T >
using iterator = double_iterator< typename decltype(data_)::iterator >
using const_iterator = double_iterator< typename decltype(data_)::const_iterator >
using reverse_iterator = double_iterator< typename decltype(data_)::reverse_iterator >
using const_reverse_iterator = double_iterator< typename decltype(data_)::const_reverse_iterator >
Public Member Functions
ref_vec ()=default
ref_vec (std::initializer_list< value_type * > lst)
template<typename InputIter >
ref_vec (InputIter iter1, InputIter iter2)
template<typename Range >
ref_vec (Range &&rng)
value_type & push_back (value_type &v)
value_type & push_back (non_null_ptr< value_type > ptr)
value_type & emplace_back (value_type &v)
std::unique_ptr< value_type > erase (const value_type &v)
std::size_t size () const noexcept
bool empty () const noexcept
std::size_t capacity () const noexcept
std::size_t max_size () const noexcept
void reserve (std::size_t new_cap)
void shrink_to_fit ()
value_type & operator[] (std::size_t n)
const value_type & operator[] (std::size_t n) const
value_type & at (std::size_t n)
const value_type & at (std::size_t n) const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
value_type & front ()
value_type & back ()
const value_type & front () const
const value_type & back () const
std::vector< value_type * > & underlying ()
Member Typedef Documentation
value_type
template<typename T > using otto::util::ref_vec< T >::value_type = std::decay_t<T>
Definition at line 530 of file ptr_vec.hpp.
iterator
template<typename T > using otto::util::ref_vec< T >::iterator = double_iterator<typename decltype(data_)::iterator>
Definition at line 536 of file ptr_vec.hpp.
const_iterator
template<typename T > using otto::util::ref_vec< T >::const_iterator = double_iterator<typename decltype(data_)::const_iterator>
Definition at line 537 of file ptr_vec.hpp.
reverse_iterator
template<typename T > using otto::util::ref_vec< T >::reverse_iterator = double_iterator<typename decltype(data_)::reverse_iterator>
Definition at line 539 of file ptr_vec.hpp.
const_reverse_iterator
template<typename T > using otto::util::ref_vec< T >::const_reverse_iterator = double_iterator<typename decltype(data_)::const_reverse_iterator>
Definition at line 540 of file ptr_vec.hpp.
Constructor & Destructor Documentation
ref_vec() [1/4]
template<typename T > otto::util::ref_vec< T >::ref_vec () default
ref_vec() [2/4]
template<typename T > otto::util::ref_vec< T >::ref_vec (std::initializer_list< value_type * > lst)
Definition at line 544 of file ptr_vec.hpp.
ref_vec() [3/4]
template<typename T > template<typename InputIter > otto::util::ref_vec< T >::ref_vec (InputIter iter1, InputIter iter2)
Definition at line 548 of file ptr_vec.hpp.
References std::back_inserter(), std::distance(), std::vector< T >::reserve(), and std::transform().
ref_vec() [4/4]
template<typename T > template<typename Range > otto::util::ref_vec< T >::ref_vec (Range && rng)
Definition at line 556 of file ptr_vec.hpp.
Member Function Documentation
push_back() [1/2]
template<typename T > value_type& otto::util::ref_vec< T >::push_back (value_type & v)
Definition at line 559 of file ptr_vec.hpp.
References std::vector< T >::push_back().
Referenced by otto::util::ref_vec< T >::emplace_back().
push_back() [2/2]
template<typename T > value_type& otto::util::ref_vec< T >::push_back (non_null_ptr< value_type > ptr)
Definition at line 565 of file ptr_vec.hpp.
References std::vector< T >::push_back().
emplace_back()
template<typename T > value_type& otto::util::ref_vec< T >::emplace_back (value_type & v)
Definition at line 571 of file ptr_vec.hpp.
References otto::util::ref_vec< T >::push_back().
erase()
template<typename T > std::unique_ptr<value_type> otto::util::ref_vec< T >::erase (const value_type & v)
Definition at line 576 of file ptr_vec.hpp.
References std::vector< T >::begin(), std::vector< T >::end(), std::vector< T >::erase(), std::find_if(), and std::move().
size()
template<typename T > std::size_t otto::util::ref_vec< T >::size () const noexcept
Definition at line 587 of file ptr_vec.hpp.
References std::vector< T >::size().
empty()
template<typename T > bool otto::util::ref_vec< T >::empty () const noexcept
Definition at line 592 of file ptr_vec.hpp.
References std::vector< T >::empty().
capacity()
template<typename T > std::size_t otto::util::ref_vec< T >::capacity () const noexcept
Definition at line 597 of file ptr_vec.hpp.
References std::vector< T >::capacity().
max_size()
template<typename T > std::size_t otto::util::ref_vec< T >::max_size () const noexcept
Definition at line 602 of file ptr_vec.hpp.
References std::vector< T >::max_size().
reserve()
template<typename T > void otto::util::ref_vec< T >::reserve (std::size_t new_cap)
Definition at line 607 of file ptr_vec.hpp.
References std::vector< T >::reserve().
shrink_to_fit()
template<typename T > void otto::util::ref_vec< T >::shrink_to_fit ()
Definition at line 612 of file ptr_vec.hpp.
References std::vector< T >::shrink_to_fit().
operator[]() [1/2]
template<typename T > value_type& otto::util::ref_vec< T >::operator[] (std::size_t n)
Definition at line 617 of file ptr_vec.hpp.
operator[]() [2/2]
template<typename T > const value_type& otto::util::ref_vec< T >::operator[] (std::size_t n) const
Definition at line 622 of file ptr_vec.hpp.
at() [1/2]
template<typename T > value_type& otto::util::ref_vec< T >::at (std::size_t n)
Definition at line 627 of file ptr_vec.hpp.
References std::vector< T >::at().
at() [2/2]
template<typename T > const value_type& otto::util::ref_vec< T >::at (std::size_t n) const
Definition at line 632 of file ptr_vec.hpp.
References std::vector< T >::at().
begin() [1/2]
template<typename T > iterator otto::util::ref_vec< T >::begin ()
Definition at line 637 of file ptr_vec.hpp.
References std::vector< T >::begin().
end() [1/2]
template<typename T > iterator otto::util::ref_vec< T >::end ()
Definition at line 641 of file ptr_vec.hpp.
References std::vector< T >::end().
begin() [2/2]
template<typename T > const_iterator otto::util::ref_vec< T >::begin () const
Definition at line 645 of file ptr_vec.hpp.
References std::vector< T >::begin().
end() [2/2]
template<typename T > const_iterator otto::util::ref_vec< T >::end () const
Definition at line 649 of file ptr_vec.hpp.
References std::vector< T >::end().
rbegin() [1/2]
template<typename T > reverse_iterator otto::util::ref_vec< T >::rbegin ()
Definition at line 654 of file ptr_vec.hpp.
References std::vector< T >::rbegin().
rend() [1/2]
template<typename T > reverse_iterator otto::util::ref_vec< T >::rend ()
Definition at line 658 of file ptr_vec.hpp.
References std::vector< T >::rend().
rbegin() [2/2]
template<typename T > const_reverse_iterator otto::util::ref_vec< T >::rbegin () const
Definition at line 662 of file ptr_vec.hpp.
References std::vector< T >::rbegin().
rend() [2/2]
template<typename T > const_reverse_iterator otto::util::ref_vec< T >::rend () const
Definition at line 666 of file ptr_vec.hpp.
References std::vector< T >::rend().
front() [1/2]
template<typename T > value_type& otto::util::ref_vec< T >::front ()
Definition at line 671 of file ptr_vec.hpp.
References std::vector< T >::front().
back() [1/2]
template<typename T > value_type& otto::util::ref_vec< T >::back ()
Definition at line 676 of file ptr_vec.hpp.
References std::vector< T >::back().
front() [2/2]
template<typename T > const value_type& otto::util::ref_vec< T >::front () const
Definition at line 681 of file ptr_vec.hpp.
References std::vector< T >::front().
back() [2/2]
template<typename T > const value_type& otto::util::ref_vec< T >::back () const
Definition at line 686 of file ptr_vec.hpp.
References std::vector< T >::back().
underlying()
template<typename T > std::vector<value_type*>& otto::util::ref_vec< T >::underlying ()
Definition at line 691 of file ptr_vec.hpp.
The documentation for this struct was generated from the following file:
/home/travis/build/topisani/OTTO/src/util/ptr_vec.hpp