OTTO: otto::engines::Euclid Struct Reference
otto::engines::Euclid Struct Reference
#include <euclid.hpp>
Classes
struct Channel
struct Props
Public Member Functions
Euclid ()
void on_enable () override
audio::ProcessData< 0 > process (audio::ProcessData< 0 >) override
Channel & current_channel ()
Public Member Functions inherited from otto::core::engines::AnyEngine
AnyEngine (std::string const &name, props::properties_base &props, std::unique_ptr< ui::Screen > screen)
AnyEngine ()=delete
virtual ~AnyEngine ()=default
virtual void on_disable ()
const std::string & name () const noexcept
The name of this module.
ui::Screen & screen () noexcept
const ui::Screen & screen () const noexcept
int current_preset () const noexcept
int current_preset (int new_val) noexcept
nlohmann::json to_json () const
void from_json (const nlohmann::json &j)
props::properties_base & props () noexcept
props::properties_base const & props () const noexcept
Public Attributes
otto::engines::Euclid::Props props
std::optional< std::array< int, 6 > > recording = std::nullopt
bool running = false
Static Public Attributes
static constexpr int max_length = 16
Friends
struct EuclidScreen
Detailed Description
Definition at line 17 of file euclid.hpp.
Constructor & Destructor Documentation
Euclid()
otto::engines::Euclid::Euclid ()
Definition at line 55 of file euclid.cpp.
References otto::core::engines::AnyEngine::screen().
                  : SequencerEngine("Euclid", props, std::make_unique<EuclidScreen>(this))
   {
     static_cast<EuclidScreen*>(&screen())->refresh_state();
   }
Member Function Documentation
current_channel()
Channel& otto::engines::Euclid::current_channel () inline
Definition at line 58 of file euclid.hpp.
Referenced by process().
     {
       return props.channels.at(props.channel);
     }
on_enable()
void otto::engines::Euclid::on_enable () override virtual
Called when this module is enabled
The samplers use this to load the sample file.
TODO: Define "enabled" None
Reimplemented from otto::core::engines::AnyEngine.
Definition at line 60 of file euclid.cpp.
References otto::core::engines::AnyEngine::screen().
   {
     for (auto& c : props.channels) c.update_notes();
     static_cast<EuclidScreen*>(&screen())->refresh_state();
   }
process()
audio::ProcessData< 0 > otto::engines::Euclid::process (audio::ProcessData< 0 > data) override virtual
Implements otto::core::engines::Engine< EngineType::sequencer >.
Definition at line 66 of file euclid.cpp.
References otto::util::all_of(), current_channel(), otto::util::fill(), otto::core::midi::NoteEvent::key, otto::util::match(), recording, running, and otto::util::unique().
   {
     auto& current = current_channel();
     // Copy for thread safety
     if (auto recording = this->recording; recording) {
       for (auto& event : data.midi) {
         util::match(event,
                     [&](midi::NoteOnEvent& ev) {
                       if (!_has_pressed_keys) {
                         util::fill(recording.value(), -1);
                         current.notes.set(recording.value());
                         _has_pressed_keys = true;
                       }
                       for (auto& note : recording.value()) {
                         if (note >= 0) continue;
                         note = ev.key;
                         break;
                       }
                       util::unique(recording.value(), std::equal_to<char>());
                       current.notes = recording.value();
                     },
                     [&](midi::NoteOffEvent& ev) {
                       for (auto& note : recording.value()) {
                         if (note != ev.key) continue;
                         note = -1;
                       }
                       if (util::all_of(recording.value(), [](int note) { return note < 0; })) {
                         recording = std::nullopt;
                       }
                     },
                     [](auto&&) {});
         this->recording = recording;
         if (!recording) break;
         ;
       }
     }
     if (_should_run) running = true;
     if (!running) return data;
     if (!_should_run && running) {
       _counter = _samples_per_beat;
       running = false;
       return data;
     }
     auto next_beat = _samples_per_beat - _counter;
     if (next_beat <= data.nframes) {
       for (auto& channel : props.channels) {
         if (channel.length > 0) {
           channel._beat_counter++;
           channel._beat_counter %= channel.length;
           if (running && channel._hits_enabled.at(channel._beat_counter)) {
             for (auto note : channel.notes.get()) {
               if (note >= 0) {
                 data.midi.push_back(midi::NoteOnEvent(note));
                 data.midi.push_back(midi::NoteOffEvent(note));
               }
             }
           }
         }
       }
     }
     _counter += data.nframes;
     _counter %= _samples_per_beat;
     return data;
   }
Friends And Related Function Documentation
EuclidScreen
friend struct EuclidScreen friend
Definition at line 68 of file euclid.hpp.
Member Data Documentation
max_length
constexpr int otto::engines::Euclid::max_length = 16 static
Definition at line 18 of file euclid.hpp.
props
otto::engines::Euclid::Props otto::engines::Euclid::props
recording
std::optional<std::array<int, 6> > otto::engines::Euclid::recording = std::nullopt
Definition at line 63 of file euclid.hpp.
Referenced by process().
running
bool otto::engines::Euclid::running = false
Definition at line 65 of file euclid.hpp.
Referenced by process().
The documentation for this struct was generated from the following files:
/home/topisani/dev/OTTO/src/engines/seq/euclid/euclid.hpp
/home/topisani/dev/OTTO/src/engines/seq/euclid/euclid.cpp