OTTO: otto::util::iterator::ZippedRange< Ranges > Struct Template Reference
otto::util::iterator::ZippedRange< Ranges > Struct Template Reference
Detailed Description
template<typename... Ranges>
struct otto::util::iterator::ZippedRange< Ranges >
Definition at line 844 of file iterator.hpp.
#include <iterator.hpp>
Public Member Functions
ZippedRange (Ranges &&... ranges)
auto begin ()
auto begin () const
auto end ()
auto end () const
Public Attributes
zipped_iterator< std::decay_t< decltype(std::begin(std::declval< Ranges >)))>... > first
zipped_iterator< std::decay_t< decltype(std::end(std::declval< Ranges >)))>... > last
Constructor & Destructor Documentation
ZippedRange()
template<typename... Ranges> otto::util::iterator::ZippedRange< Ranges >::ZippedRange (Ranges &&... ranges)
Definition at line 845 of file iterator.hpp.
References std::begin().
Member Function Documentation
begin() [1/2]
template<typename... Ranges> auto otto::util::iterator::ZippedRange< Ranges >::begin ()
Definition at line 847 of file iterator.hpp.
References otto::util::iterator::ZippedRange< Ranges >::first.
begin() [2/2]
template<typename... Ranges> auto otto::util::iterator::ZippedRange< Ranges >::begin () const
Definition at line 852 of file iterator.hpp.
References otto::util::iterator::ZippedRange< Ranges >::first.
end() [1/2]
template<typename... Ranges> auto otto::util::iterator::ZippedRange< Ranges >::end ()
Definition at line 857 of file iterator.hpp.
References otto::util::iterator::ZippedRange< Ranges >::last.
end() [2/2]
template<typename... Ranges> auto otto::util::iterator::ZippedRange< Ranges >::end () const
Definition at line 862 of file iterator.hpp.
References otto::util::iterator::ZippedRange< Ranges >::last.
Member Data Documentation
first
template<typename... Ranges> zipped_iterator<std::decay_t<decltype(std::begin(std::declval<Ranges>)))>...> otto::util::iterator::ZippedRange< Ranges >::first
Definition at line 867 of file iterator.hpp.
Referenced by otto::util::iterator::ZippedRange< Ranges >::begin().
last
template<typename... Ranges> zipped_iterator<std::decay_t<decltype(std::end(std::declval<Ranges>)))>...> otto::util::iterator::ZippedRange< Ranges >::last
Definition at line 869 of file iterator.hpp.
Referenced by otto::util::iterator::ZippedRange< Ranges >::end().
The documentation for this struct was generated from the following file:
/home/travis/build/topisani/OTTO/src/util/iterator.hpp