OTTO: otto::services::AudioManager Struct Reference
otto::services::AudioManager Struct Reference
Detailed Description
Definition at line 15 of file audio_manager.hpp.
#include <audio_manager.hpp>
Classes
struct Events
Public Member Functions
AudioManager ()
Fires Events::pre_init and generates midi frequency table.
core::audio::AudioBufferPool & buffer_pool () noexcept
Use this to get audio buffers.
void send_midi_event (core::midi::AnyMidiEvent) noexcept
Send a midi event into the system.
int samplerate () const noexcept
Get the samplerate.
int buffer_size () const noexcept
Get the buffer size.
unsigned buffer_number () const noexcept
Get the current buffer number.
void wait_one () const noexcept
Wait at least until the current process call is done.
void start () noexcept
Start audio processing.
bool running () noexcept
Check if audio should be processed.
float cpu_time () noexcept
The amount of cpu time spent on average since the last call to this function.
Public Member Functions inherited from otto::core::Service
Service ()=default
virtual ~Service ()=default
Service (const Service &)=delete
Service (Service &&)=delete
auto operator= (const Service &)=delete
auto operator= (Service &&)=delete
Static Public Member Functions
static AudioManager & current () noexcept
Get the current instance of this service.
Public Attributes
struct otto::services::AudioManager::Events events
Protected Attributes
util::double_buffered< core::midi::shared_vector< core::midi::AnyMidiEvent > > midi_bufs = {{}, {}}
std::atomic_int _samplerate = 48000
std::atomic_uint _buffer_size = 256
std::atomic_uint _buffer_number = 0
util::audio::Graph _cpu_time
Class Documentation
otto::services::AudioManager::Events
struct otto::services::AudioManager::Events
Class Members
Signal pre_init
Constructor & Destructor Documentation
AudioManager()
otto::services::AudioManager::AudioManager ()
Fires Events::pre_init and generates midi frequency table.
Note
_buffer_pool is constructed with a buffer size of 1. The subclass needs to change this using AudioBufferPool::set_buffer_size as soon as possible
Member Function Documentation
buffer_pool()
core::audio::AudioBufferPool& otto::services::AudioManager::buffer_pool () noexcept
Use this to get audio buffers.
There are currently a maximum of 4 avaliable, so make sure to release them when you're done with them!
Referenced by otto::services::test::DummyAudioManager::set_bs_sr().
send_midi_event()
void otto::services::AudioManager::send_midi_event (core::midi::AnyMidiEvent) noexcept
Send a midi event into the system.
The core::midi namespace has some nice utils for constructing events.
samplerate()
int otto::services::AudioManager::samplerate () const noexcept
Get the samplerate.
Definition at line 34 of file audio_manager.hpp.
References _samplerate.
buffer_size()
int otto::services::AudioManager::buffer_size () const noexcept
Get the buffer size.
Definition at line 37 of file audio_manager.hpp.
References _buffer_size.
Referenced by otto::services::test::DummyAudioManager::set_bs_sr().
buffer_number()
unsigned otto::services::AudioManager::buffer_number () const noexcept
Get the current buffer number.
i.e. number of {buffer_size()} chunks of samples since the start
Can be used to wait until the current process call is over
Definition at line 44 of file audio_manager.hpp.
References _buffer_number.
wait_one()
void otto::services::AudioManager::wait_one () const noexcept
Wait at least until the current process call is done.
start()
void otto::services::AudioManager::start () noexcept
Start audio processing.
Sets running() = true
running()
bool otto::services::AudioManager::running () noexcept
Check if audio should be processed.
Returns
true if start() has been called
Referenced by otto::services::test::DummyAudioManager::process().
cpu_time()
float otto::services::AudioManager::cpu_time () noexcept
The amount of cpu time spent on average since the last call to this function.
current()
static AudioManager& otto::services::AudioManager::current () static noexcept
Get the current instance of this service.
Alias to Application::current().audio_manager
Definition at line 65 of file audio_manager.hpp.
References otto::services::Application::audio_manager, and otto::services::Application::current().
Referenced by otto::services::RTAudioAudioManager::current().
Member Data Documentation
events
struct otto::services::AudioManager::Events otto::services::AudioManager::events
midi_bufs
util::double_buffered<core::midi::shared_vector<core::midi::AnyMidiEvent> > otto::services::AudioManager::midi_bufs = {{}, {}} protected
Definition at line 74 of file audio_manager.hpp.
Referenced by otto::services::test::DummyAudioManager::process().
_samplerate
std::atomic_int otto::services::AudioManager::_samplerate = 48000 protected
Definition at line 75 of file audio_manager.hpp.
Referenced by samplerate().
_buffer_size
std::atomic_uint otto::services::AudioManager::_buffer_size = 256 protected
Definition at line 76 of file audio_manager.hpp.
Referenced by buffer_size(), otto::services::test::DummyAudioManager::process(), and otto::services::test::DummyAudioManager::set_bs_sr().
_buffer_number
std::atomic_uint otto::services::AudioManager::_buffer_number = 0 protected
Definition at line 77 of file audio_manager.hpp.
Referenced by buffer_number(), and otto::services::test::DummyAudioManager::process().
_cpu_time
util::audio::Graph otto::services::AudioManager::_cpu_time protected
Definition at line 78 of file audio_manager.hpp.
The documentation for this struct was generated from the following file:
/home/travis/build/topisani/OTTO/src/services/audio_manager.hpp