OTTO: otto::core::audio::SettingsScreen Struct Reference
otto::core::audio::SettingsScreen Struct Reference
Public Member Functions
SettingsScreen (SettingsProps &props)
void draw (ui::vg::Canvas &) override
void rotary (ui::RotaryEvent ev) override
This should be used for handling rotary events.
Public Member Functions inherited from otto::core::ui::Screen
Screen ()
virtual ~Screen ()
virtual bool keypress (Key)
virtual bool keyrelease (Key)
virtual void on_show ()
Run by MainUI when switching to this screen.
virtual void on_hide ()
Run by MainUI when switching to another screen.
Public Member Functions inherited from otto::core::ui::vg::Drawable
Drawable ()=default
virtual ~Drawable ()=default
Public Attributes
SettingsProps & props
Detailed Description
Definition at line 19 of file voice_manager.cpp.
Constructor & Destructor Documentation
SettingsScreen()
otto::core::audio::SettingsScreen::SettingsScreen (SettingsProps & props) inline
Definition at line 21 of file voice_manager.cpp.
       : props (props)
     {}
Member Function Documentation
draw()
void otto::core::audio::SettingsScreen::draw (ui::vg::Canvas & ctx) override virtual
Draw this widget to the context.
Called from the parent's draw method.
Parameters
ctx the canvas to draw on.
Implements otto::core::ui::vg::Drawable.
Definition at line 141 of file voice_manager.cpp.
References otto::core::ui::vg::Canvas::fillStyle(), otto::core::ui::vg::Canvas::fillText(), otto::core::ui::vg::Canvas::font(), otto::core::ui::vg::height, and otto::core::audio::to_string().
   {
     using namespace ui::vg;
     ctx.font(Fonts::Norm, 35);
     constexpr float x_pad = 30;
     constexpr float y_pad = 50;
     constexpr float space = (height - 2.f * y_pad) / 3.f;
     ctx.beginPath();
     ctx.fillStyle(Colours::Blue);
     ctx.textAlign(HorizontalAlign::Left, VerticalAlign::Middle);
     ctx.fillText("play mode", {x_pad, y_pad});
     ctx.beginPath();
     ctx.fillStyle(Colours::Blue);
     ctx.textAlign(HorizontalAlign::Right, VerticalAlign::Middle);
     ctx.fillText(to_string(props.play_mode), {width - x_pad, y_pad});
     ctx.beginPath();
     ctx.fillStyle(Colours::Green);
     ctx.textAlign(HorizontalAlign::Left, VerticalAlign::Middle);
     ctx.fillText("portamento", {x_pad, y_pad + space});
     ctx.beginPath();
     ctx.fillStyle(Colours::Green);
     ctx.textAlign(HorizontalAlign::Right, VerticalAlign::Middle);
     ctx.fillText(fmt::format("{:3.2}", props.portamento), {width - x_pad, y_pad + space});
     ctx.beginPath();
     ctx.fillStyle(Colours::Yellow);
     ctx.textAlign(HorizontalAlign::Left, VerticalAlign::Middle);
     ctx.fillText("octave", {x_pad, y_pad + 2 * space});
     ctx.beginPath();
     ctx.fillStyle(Colours::Yellow);
     ctx.textAlign(HorizontalAlign::Right, VerticalAlign::Middle);
     ctx.fillText(fmt::format("{:+}", props.octave), {width - x_pad, y_pad + 2 * space});
     ctx.beginPath();
     ctx.fillStyle(Colours::Red);
     ctx.textAlign(HorizontalAlign::Left, VerticalAlign::Middle);
     ctx.fillText("transpose", {x_pad, y_pad + 3 * space});
     ctx.beginPath();
     ctx.fillStyle(Colours::Red);
     ctx.textAlign(HorizontalAlign::Right, VerticalAlign::Middle);
     ctx.fillText(fmt::format("{:+}", props.transpose), {width - x_pad, y_pad + 3 * space});
   }
rotary()
void otto::core::audio::SettingsScreen::rotary (ui::RotaryEvent) override virtual
This should be used for handling rotary events.
Reimplemented from otto::core::ui::Screen.
Definition at line 131 of file voice_manager.cpp.
References otto::core::ui::RotaryEvent::clicks, and otto::core::ui::RotaryEvent::rotary.
   {
     switch (ev.rotary) {
       case Rotary::Blue: props.play_mode.step(ev.clicks); break;
       case Rotary::Green: props.portamento.step(ev.clicks); break;
       case Rotary::White: props.octave.step(ev.clicks); break;
       case Rotary::Red: props.transpose.step(ev.clicks); break;
     }
   }
Member Data Documentation
props
SettingsProps& otto::core::audio::SettingsScreen::props
Definition at line 28 of file voice_manager.cpp.
The documentation for this struct was generated from the following file:
/home/topisani/dev/OTTO/src/core/audio/voice_manager.cpp