OTTO: otto::util::ByteFile::Chunk Struct Reference
otto::util::ByteFile::Chunk Struct Reference
Detailed Description
Definition at line 139 of file bytefile.hpp.
#include <bytefile.hpp>
Public Member Functions
Chunk (bytes< 4 > id={0, 0, 0, 0})
Chunk (const Chunk &o)
virtual ~Chunk ()=default
Position beginning ()
Position past_end ()
void write (ByteFile &file)
virtual void write_fields (ByteFile &file)
void read (ByteFile &file)
virtual void read_fields (ByteFile &file)
Public Attributes
bytes< 4 > id
bytes< 4 > size = {0,0,0,0}
Position offset
Constructor & Destructor Documentation
Chunk() [1/2]
otto::util::ByteFile::Chunk::Chunk (bytes< 4 > id = {0,0,0,0})
Definition at line 145 of file bytefile.hpp.
Referenced by otto::util::Header::read_fields().
Chunk() [2/2]
otto::util::ByteFile::Chunk::Chunk (const Chunk & o)
Definition at line 146 of file bytefile.hpp.
~Chunk()
virtual otto::util::ByteFile::Chunk::~Chunk () virtual default
Member Function Documentation
beginning()
Position otto::util::ByteFile::Chunk::beginning ()
Definition at line 149 of file bytefile.hpp.
References offset.
Referenced by otto::util::ByteFile::for_chunks_in_range().
past_end()
Position otto::util::ByteFile::Chunk::past_end ()
Definition at line 154 of file bytefile.hpp.
References otto::util::bytes< len >::as_u(), offset, and size.
Referenced by otto::util::ByteFile::for_chunks_in_range(), and write().
write()
void otto::util::ByteFile::Chunk::write (ByteFile & file)
Definition at line 159 of file bytefile.hpp.
References otto::util::bytes< len >::as_u(), offset, past_end(), otto::util::ByteFile::position(), otto::util::ByteFile::seek(), size, otto::util::ByteFile::write_bytes(), and write_fields().
Referenced by otto::util::SoundFile::write_file().
write_fields()
virtual void otto::util::ByteFile::Chunk::write_fields (ByteFile & file) virtual
Reimplemented in otto::util::WAVE_data, otto::util::WAVE_fmt, otto::util::TAPEChunk, otto::util::Header, and otto::util::TRCKChunk.
Definition at line 174 of file bytefile.hpp.
Referenced by write().
read()
void otto::util::ByteFile::Chunk::read (ByteFile & file)
Definition at line 176 of file bytefile.hpp.
References offset, otto::util::ByteFile::position(), otto::util::ByteFile::read_bytes(), read_fields(), and size.
Referenced by otto::util::ByteFile::for_chunks_in_range(), and otto::util::SoundFile::read_file().
read_fields()
virtual void otto::util::ByteFile::Chunk::read_fields (ByteFile & file) virtual
Reimplemented in otto::util::WAVE_data, otto::util::TAPEChunk, otto::util::WAVE_fmt, otto::util::TRCKChunk, and otto::util::Header.
Definition at line 183 of file bytefile.hpp.
Referenced by read().
Member Data Documentation
id
bytes<4> otto::util::ByteFile::Chunk::id
Definition at line 140 of file bytefile.hpp.
Referenced by otto::util::SoundFile::read_file(), otto::util::TapeFile::replace_custom_chunk(), and otto::util::SoundFile::write_file().
size
bytes<4> otto::util::ByteFile::Chunk::size = {0,0,0,0}
Definition at line 141 of file bytefile.hpp.
Referenced by past_end(), read(), otto::util::Header::read_fields(), and write().
offset
Position otto::util::ByteFile::Chunk::offset
Definition at line 143 of file bytefile.hpp.
Referenced by beginning(), past_end(), read(), otto::util::Header::read_fields(), otto::util::WAVE_data::read_fields(), write(), and otto::util::WAVE_data::write_fields().
The documentation for this struct was generated from the following file:
/home/topisani/dev/OTTO/src/util/bytefile.hpp