OTTO: otto::services::Application Struct Reference
otto::services::Application Struct Reference
Detailed Description
Definition at line 60 of file application.hpp.
#include <application.hpp>
Classes
struct Events
Public Types
enum ErrorCode {
ErrorCode::none = 0, ErrorCode::ui_closed, ErrorCode::user_exit, ErrorCode::audio_error,
ErrorCode::graphics_error, ErrorCode::input_error, ErrorCode::signal_recieved
}
using exception = util::as_exception< ErrorCode >
Public Member Functions
Application (ServiceStorage< LogManager >::Factory log_factory, ServiceStorage< StateManager >::Factory state_factory, ServiceStorage< PresetManager >::Factory preset_factory, ServiceStorage< AudioManager >::Factory audio_factory, ServiceStorage< ClockManager >::Factory clock_factory, ServiceStorage< UIManager >::Factory ui_factory, ServiceStorage< Controller >::Factory controller, ServiceStorage< EngineManager >::Factory engine_factory)
virtual ~Application ()
void exit (ErrorCode ec) noexcept
bool running () noexcept
ErrorCode error () noexcept
Static Public Member Functions
static Application & current () noexcept
The current Application.
static void handle_signal (int signal) noexcept
Public Attributes
const filesystem::path data_dir {"data"}
struct otto::services::Application::Events events
ServiceStorage< LogManager > log_manager
ServiceStorage< StateManager > state_manager
ServiceStorage< PresetManager > preset_manager
ServiceStorage< AudioManager > audio_manager
ServiceStorage< ClockManager > clock_manager
ServiceStorage< UIManager > ui_manager
ServiceStorage< Controller > controller
ServiceStorage< EngineManager > engine_manager
Class Documentation
otto::services::Application::Events
struct otto::services::Application::Events
Class Members
Signal post_init
Signal pre_exit
Member Typedef Documentation
exception
using otto::services::Application::exception = util::as_exception<ErrorCode>
Definition at line 71 of file application.hpp.
Member Enumeration Documentation
ErrorCode
enum otto::services::Application::ErrorCode strong
Enumerator
none
ui_closed
user_exit
audio_error
graphics_error
input_error
signal_recieved
Definition at line 61 of file application.hpp.
Constructor & Destructor Documentation
Application()
otto::services::Application::Application (ServiceStorage< LogManager >::Factory log_factory, ServiceStorage< StateManager >::Factory state_factory, ServiceStorage< PresetManager >::Factory preset_factory, ServiceStorage< AudioManager >::Factory audio_factory, ServiceStorage< ClockManager >::Factory clock_factory, ServiceStorage< UIManager >::Factory ui_factory, ServiceStorage< Controller >::Factory controller, ServiceStorage< EngineManager >::Factory engine_factory)
~Application()
virtual otto::services::Application::~Application () virtual
Member Function Documentation
current()
static Application& otto::services::Application::current () static noexcept
The current Application.
When an Application is constructed, this function will be pointed to it. The one who constructs the application still has to destruct it when done with it.
There should obviously only ever be one Application instance in the process.
Referenced by otto::services::ClockManager::current(), otto::services::AudioManager::current(), otto::services::UIManager::current(), otto::services::test::DummyAudioManager::current(), otto::services::Controller::current(), otto::services::test::DummyAudioManager::process(), and otto::core::engine::EngineDispatcher< ET, Engines >::select().
exit()
void otto::services::Application::exit (ErrorCode ec) noexcept
running()
bool otto::services::Application::running () noexcept
Referenced by otto::services::test::DummyAudioManager::process().
error()
ErrorCode otto::services::Application::error () noexcept
handle_signal()
static void otto::services::Application::handle_signal (int signal) static noexcept
Member Data Documentation
data_dir
const filesystem::path otto::services::Application::data_dir {"data"}
Definition at line 72 of file application.hpp.
events
struct otto::services::Application::Events otto::services::Application::events
log_manager
ServiceStorage<LogManager> otto::services::Application::log_manager
Definition at line 106 of file application.hpp.
state_manager
ServiceStorage<StateManager> otto::services::Application::state_manager
Definition at line 107 of file application.hpp.
preset_manager
ServiceStorage<PresetManager> otto::services::Application::preset_manager
Definition at line 108 of file application.hpp.
audio_manager
ServiceStorage<AudioManager> otto::services::Application::audio_manager
Definition at line 109 of file application.hpp.
Referenced by otto::services::AudioManager::current(), otto::services::test::DummyAudioManager::process(), and otto::core::engine::EngineDispatcher< ET, Engines >::select().
clock_manager
ServiceStorage<ClockManager> otto::services::Application::clock_manager
Definition at line 110 of file application.hpp.
Referenced by otto::services::ClockManager::current().
ui_manager
ServiceStorage<UIManager> otto::services::Application::ui_manager
Definition at line 111 of file application.hpp.
Referenced by otto::services::UIManager::current().
controller
ServiceStorage<Controller> otto::services::Application::controller
Definition at line 112 of file application.hpp.
Referenced by otto::services::Controller::current().
engine_manager
ServiceStorage<EngineManager> otto::services::Application::engine_manager
Definition at line 113 of file application.hpp.
Referenced by otto::services::test::DummyAudioManager::process().
The documentation for this struct was generated from the following file:
/home/travis/build/topisani/OTTO/src/services/application.hpp