OTTO: otto::util::local_vector< T, Capacity > Struct Template Reference
otto::util::local_vector< T, Capacity > Struct Template Reference
Detailed Description
template<typename T, std::size_t Capacity>
struct otto::util::local_vector< T, Capacity >
Definition at line 12 of file local_vector.hpp.
#include <local_vector.hpp>
Public Types
enum error { error::full, error::empty }
Error codes.
using value_type = T
using iterator = value_type *
using const_iterator = const value_type *
using exception = util::as_exception< error >
Public Member Functions
constexpr local_vector ()
constexpr local_vector (std::initializer_list< value_type > il)
~local_vector () noexcept
constexpr std::size_t size () const noexcept
constexpr bool empty () const noexcept
constexpr bool full () const noexcept
constexpr auto begin () noexcept
constexpr auto begin () const noexcept
constexpr auto end () noexcept
constexpr auto end () const noexcept
constexpr value_type & front () noexcept
constexpr const value_type & front () const noexcept
constexpr value_type & back () noexcept
constexpr const value_type & back () const noexcept
constexpr value_type & operator[] (std::size_t idx) noexcept
constexpr value_type * data () noexcept
constexpr const value_type * data () const noexcept
constexpr tl::expected< value_type *, error > push_back (const value_type &e) noexcept
constexpr tl::expected< value_type *, error > push_back (value_type &&e) noexcept
template<typename... Args, typename Enable = std::enable_if_t<std::is_constructible_v<value_type, Args...>>>
constexpr tl::expected< value_type *, error > emplace_back (Args &&... args) noexcept
constexpr tl::expected< iterator, error > insert_before (iterator iter, const value_type &value) noexcept
Inserts value before pos.
constexpr iterator insert (iterator iter, const value_type &value)
Inserts value before iter.
constexpr tl::expected< void, error > pop_back () noexcept
constexpr void clear () noexcept
Static Public Member Functions
static constexpr std::size_t capacity () noexcept
Member Typedef Documentation
value_type
template<typename T, std::size_t Capacity> using otto::util::local_vector< T, Capacity >::value_type = T
Definition at line 13 of file local_vector.hpp.
iterator
template<typename T, std::size_t Capacity> using otto::util::local_vector< T, Capacity >::iterator = value_type*
Definition at line 14 of file local_vector.hpp.
const_iterator
template<typename T, std::size_t Capacity> using otto::util::local_vector< T, Capacity >::const_iterator = const value_type*
Definition at line 15 of file local_vector.hpp.
exception
template<typename T, std::size_t Capacity> using otto::util::local_vector< T, Capacity >::exception = util::as_exception<error>
Definition at line 25 of file local_vector.hpp.
Member Enumeration Documentation
error
template<typename T, std::size_t Capacity> enum otto::util::local_vector::error strong
Error codes.
Enumerator
full
The vector is at capacity.
empty
The vecctor is empty.
Definition at line 18 of file local_vector.hpp.
Constructor & Destructor Documentation
local_vector() [1/2]
template<typename T, std::size_t Capacity> constexpr otto::util::local_vector< T, Capacity >::local_vector () constexpr
Definition at line 27 of file local_vector.hpp.
local_vector() [2/2]
template<typename T, std::size_t Capacity> constexpr otto::util::local_vector< T, Capacity >::local_vector (std::initializer_list< value_type > il) constexpr
Definition at line 29 of file local_vector.hpp.
~local_vector()
template<typename T, std::size_t Capacity> otto::util::local_vector< T, Capacity >::~local_vector () noexcept
Definition at line 37 of file local_vector.hpp.
Member Function Documentation
capacity()
template<typename T, std::size_t Capacity> static constexpr std::size_t otto::util::local_vector< T, Capacity >::capacity () static constexpr noexcept
Definition at line 45 of file local_vector.hpp.
Referenced by otto::util::local_vector< std::uint8_t, 6 >::full().
size()
template<typename T, std::size_t Capacity> constexpr std::size_t otto::util::local_vector< T, Capacity >::size () const constexpr noexcept
Definition at line 50 of file local_vector.hpp.
Referenced by otto::util::local_vector< std::uint8_t, 6 >::empty(), and otto::util::local_vector< std::uint8_t, 6 >::full().
empty()
template<typename T, std::size_t Capacity> constexpr bool otto::util::local_vector< T, Capacity >::empty () const constexpr noexcept
Definition at line 55 of file local_vector.hpp.
Referenced by otto::util::local_vector< std::uint8_t, 6 >::clear(), otto::util::local_vector< std::uint8_t, 6 >::pop_back(), and otto::engines::Sequencer::PolySequence::Step::triggered().
full()
template<typename T, std::size_t Capacity> constexpr bool otto::util::local_vector< T, Capacity >::full () const constexpr noexcept
Definition at line 60 of file local_vector.hpp.
Referenced by otto::util::local_vector< std::uint8_t, 6 >::emplace_back().
begin() [1/2]
template<typename T, std::size_t Capacity> constexpr auto otto::util::local_vector< T, Capacity >::begin () constexpr noexcept
Definition at line 67 of file local_vector.hpp.
Referenced by otto::util::local_vector< std::uint8_t, 6 >::front().
begin() [2/2]
template<typename T, std::size_t Capacity> constexpr auto otto::util::local_vector< T, Capacity >::begin () const constexpr noexcept
Definition at line 72 of file local_vector.hpp.
end() [1/2]
template<typename T, std::size_t Capacity> constexpr auto otto::util::local_vector< T, Capacity >::end () constexpr noexcept
Definition at line 77 of file local_vector.hpp.
Referenced by otto::util::local_vector< std::uint8_t, 6 >::insert_before().
end() [2/2]
template<typename T, std::size_t Capacity> constexpr auto otto::util::local_vector< T, Capacity >::end () const constexpr noexcept
Definition at line 82 of file local_vector.hpp.
front() [1/2]
template<typename T, std::size_t Capacity> constexpr value_type& otto::util::local_vector< T, Capacity >::front () constexpr noexcept
Definition at line 89 of file local_vector.hpp.
front() [2/2]
template<typename T, std::size_t Capacity> constexpr const value_type& otto::util::local_vector< T, Capacity >::front () const constexpr noexcept
Definition at line 94 of file local_vector.hpp.
back() [1/2]
template<typename T, std::size_t Capacity> constexpr value_type& otto::util::local_vector< T, Capacity >::back () constexpr noexcept
Definition at line 99 of file local_vector.hpp.
Referenced by otto::util::local_vector< std::uint8_t, 6 >::emplace_back().
back() [2/2]
template<typename T, std::size_t Capacity> constexpr const value_type& otto::util::local_vector< T, Capacity >::back () const constexpr noexcept
Definition at line 104 of file local_vector.hpp.
operator[]()
template<typename T, std::size_t Capacity> constexpr value_type& otto::util::local_vector< T, Capacity >::operator[] (std::size_t idx) constexpr noexcept
Definition at line 109 of file local_vector.hpp.
data() [1/2]
template<typename T, std::size_t Capacity> constexpr value_type* otto::util::local_vector< T, Capacity >::data () constexpr noexcept
Definition at line 113 of file local_vector.hpp.
Referenced by otto::util::local_vector< std::uint8_t, 6 >::back(), otto::util::local_vector< std::uint8_t, 6 >::begin(), otto::util::local_vector< std::uint8_t, 6 >::emplace_back(), otto::util::local_vector< std::uint8_t, 6 >::end(), otto::util::local_vector< std::uint8_t, 6 >::operator[](), and otto::util::local_vector< std::uint8_t, 6 >::pop_back().
data() [2/2]
template<typename T, std::size_t Capacity> constexpr const value_type* otto::util::local_vector< T, Capacity >::data () const constexpr noexcept
Definition at line 126 of file local_vector.hpp.
push_back() [1/2]
template<typename T, std::size_t Capacity> constexpr tl::expected<value_type*, error> otto::util::local_vector< T, Capacity >::push_back (const value_type & e) constexpr noexcept
Definition at line 141 of file local_vector.hpp.
Referenced by otto::util::local_vector< std::uint8_t, 6 >::insert_before(), and otto::util::local_vector< std::uint8_t, 6 >::local_vector().
push_back() [2/2]
template<typename T, std::size_t Capacity> constexpr tl::expected<value_type*, error> otto::util::local_vector< T, Capacity >::push_back (value_type && e) constexpr noexcept
Definition at line 146 of file local_vector.hpp.
emplace_back()
template<typename T, std::size_t Capacity> template<typename... Args, typename Enable = std::enable_if_t<std::is_constructible_v<value_type, Args...>>> constexpr tl::expected<value_type*, error> otto::util::local_vector< T, Capacity >::emplace_back (Args &&... args) constexpr noexcept
Definition at line 152 of file local_vector.hpp.
Referenced by otto::util::local_vector< std::uint8_t, 6 >::push_back().
insert_before()
template<typename T, std::size_t Capacity> constexpr tl::expected<iterator, error> otto::util::local_vector< T, Capacity >::insert_before (iterator iter, const value_type & value) constexpr noexcept
Inserts value before pos.
Definition at line 161 of file local_vector.hpp.
Referenced by otto::util::local_vector< std::uint8_t, 6 >::insert().
insert()
template<typename T, std::size_t Capacity> constexpr iterator otto::util::local_vector< T, Capacity >::insert (iterator iter, const value_type & value) constexpr
Inserts value before iter.
NOTE: use insert_before for noexcept version
Mainly provided for use with STL algorithms like transform.
Exceptions
tl::bad_expected_access<error> if there was an error when inserting
Definition at line 177 of file local_vector.hpp.
pop_back()
template<typename T, std::size_t Capacity> constexpr tl::expected<void, error> otto::util::local_vector< T, Capacity >::pop_back () constexpr noexcept
Definition at line 182 of file local_vector.hpp.
Referenced by otto::util::local_vector< std::uint8_t, 6 >::clear().
clear()
template<typename T, std::size_t Capacity> constexpr void otto::util::local_vector< T, Capacity >::clear () constexpr noexcept
Definition at line 190 of file local_vector.hpp.
Referenced by otto::engines::Sequencer::PolySequence::Step::clear(), and otto::util::local_vector< std::uint8_t, 6 >::~local_vector().
The documentation for this struct was generated from the following file:
/home/travis/build/topisani/OTTO/src/util/local_vector.hpp