OTTO: otto::service::audio::AlsaAudioDriver Struct Reference
otto::service::audio::AlsaAudioDriver Struct Reference
#include <audio_driver.hpp>
Public Member Functions
void init ()
void shutdown ()
void send_midi_event (core::midi::AnyMidiEvent)
Static Public Member Functions
static AlsaAudioDriver & get () noexcept
Public Attributes
std::atomic_int samplerate = 44100
Detailed Description
Definition at line 17 of file audio_driver.hpp.
Member Function Documentation
get()
AlsaAudioDriver & otto::service::audio::AlsaAudioDriver::get () static noexcept
Definition at line 183 of file audio_driver.cpp.
Referenced by otto::service::audio::buffer_pool(), otto::service::audio::init(), otto::service::audio::samplerate(), otto::service::audio::send_midi_event(), and otto::service::audio::shutdown().
   {
     static AlsaAudioDriver instance{};
     return instance;
   }
init()
void otto::service::audio::AlsaAudioDriver::init ()
Definition at line 189 of file audio_driver.cpp.
References otto::service::audio::events::buffersize_change(), samplerate, and otto::service::audio::events::samplerate_change().
Referenced by otto::service::audio::init().
   {
     int rc;
     rc = snd_pcm_open(&playback_handle, "default", SND_PCM_STREAM_PLAYBACK, 0);
     LOGF_IF(rc < 0, "Unable to open PCM playback device: {}", snd_strerror(rc));
     rc = snd_pcm_open(&capture_handle, "default", SND_PCM_STREAM_CAPTURE, 0);
     LOGF_IF(rc < 0, "Unable to open PCM playback device: {}", snd_strerror(rc));
     setup_alsa_device(playback_handle, 2);
     setup_alsa_device(capture_handle, 1);
     rc = snd_seq_open(&seq_handle, "default", SND_SEQ_OPEN_DUPLEX, 0);
     LOGF_IF(rc < 0, "Unable to open sequencer device: {}", snd_strerror(rc));
     snd_seq_set_client_name(seq_handle, "OTTO");
     rc = snd_seq_create_simple_port(
       seq_handle, "OTTO", SND_SEQ_PORT_CAP_WRITE | SND_SEQ_PORT_CAP_SUBS_WRITE,
       SND_SEQ_PORT_TYPE_APPLICATION);
     LOGF_IF(rc < 0, "Error creating sequencer port: {}", snd_strerror(rc));
     LOGI("Opened sequencer");
     audio_thread = std::thread([this] { main_loop(); });
     events::buffersize_change().fire(buffer_size);
     events::samplerate_change().fire(samplerate);
   }
send_midi_event()
void otto::service::audio::AlsaAudioDriver::send_midi_event (core::midi::AnyMidiEvent evt)
Definition at line 245 of file audio_driver.cpp.
References otto::util::atomic_swap< T >::outer().
Referenced by otto::service::audio::send_midi_event().
   {
     midi_bufs.outer().emplace_back(std::move(evt));
   }
shutdown()
void otto::service::audio::AlsaAudioDriver::shutdown ()
Definition at line 218 of file audio_driver.cpp.
Referenced by otto::service::audio::shutdown().
   {
     snd_pcm_close(playback_handle);
     LOG_F(INFO, "Closing Alsa client");
   }
Member Data Documentation
samplerate
std::atomic_int otto::service::audio::AlsaAudioDriver::samplerate = 44100
Definition at line 23 of file audio_driver.hpp.
Referenced by init(), and otto::service::audio::samplerate().
The documentation for this struct was generated from the following files:
/home/topisani/dev/OTTO/boards/parts/audio/alsa/include/board/audio_driver.hpp
/home/topisani/dev/OTTO/boards/parts/audio/alsa/src/audio_driver.cpp